linera-io/linera-protocol

Cargo.lock, Cargo.toml, examples/Cargo.lock, linera-execution/src/wasm/system_api.rs, linera-sdk/src/contract/runtime.rs, linera-sdk/src/service/runtime.rs, linera-sdk/wit/contract-system-api.wit, linera-sdk/wit/service-system-api.wit, linera-witty/src/exported_function_interface/guest_interface.rs, linera-witty/src/runtime/wasmer/export_function.rs, linera-witty/src/runtime/wasmer/function.rs, linera-witty/src/runtime/wasmer/parameters.rs, linera-witty/src/runtime/wasmtime/export_function.rs, linera-witty/src/runtime/wasmtime/parameters.rs
This is a second attempt to fix the issue, the first one (#2429) blocked publishing new crate versions because it depended on a fix that was upstreamed to `wasmtime`, but hadn't been included in a release yet. To remove the blocker it was reverted (by #2435)  but now the newly released version 25.0.0 of `wasmtime` includes the fix that's needed.
When exporting functions with a specific signature type (with parameters that are flattened to exactly 16 flat types and with a return type that flattens to more than one flat type) to a Wasm instance, Witty's `#[wit_export]` macro would incorrectly lower all parameters and return types to the type.
This is different from what was specified in the [specification](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#fl …
=> Fix witty export of functions with 16 parameters second attempt

Cargo.lock, linera-client/src/client_context.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/data_types.rs, linera-core/src/local_node.rs, linera-core/src/unit_tests/worker_tests.rs, linera-rpc/Cargo.toml, linera-rpc/proto/rpc.proto, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/src/linera/main.rs, linera-service/src/node_service.rs
* `cargo machete` found an unused dependency in `linera-rpc`.
* `*_first_nth` is grammatically wrong.
* [Attributes should come after comments.](https://doc.rust-lang.org/nightly/style-guide/#doc-comments) We do this mostly consistently, except in `client` and `local_node`.
* In some places we make multiple `prepare_chain` calls in a row.
* Remove the unused dependency.
* Rename to `*_first_n`.
* Move attributes below the comments.
* Remove redundant calls.
Tests should catch any regressions.
Removing the redundant calls did not make a significant difference in performance, at least not when I ran `test_end_to_end_repeated_transfers` locally in release mode.
=> Misc minor fixes.

linera-views/src/views/key_value_store_view.rs
The `KeyValueStoreView` is not exactly a `KeyValueStore` so we cannot put the `metering.rs` metrics.
* The functions used by the `execution_state_actor.rs` are `get`, `multi_get`, `contains_key(s)` and `find_key*_by_prefix`.
* The metrics were added for each.
This should help identify the latencies for the `KeyValueStoreView` that are relevant to the smart contracts.
The CI. But so far there is nom impact on the tests so far.
Not relevant.
=> Latency metrics for the `KeyValueStoreView`.

examples/non-fungible/README.md, examples/non-fungible/src/lib.rs, examples/non-fungible/web-frontend/src/App.js, linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-chain/src/data_types.rs, linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/value_cache_tests.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/mod.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/format.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/grpc_proxy.rs, linera-service/src/node_service.rs, linera-service/src/proxy.rs, linera-service/tests/linera_net_tests.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
Right now we have `BlobContent` always as a blob of bytes, but it can have many forms. This causes us to have to serialize/deserialize into those forms back and forth in the code more than we have to.
Encode the blob type into the `BlobContent`. Now `BlobId` and `BlobContent` will have the type encoded in them. They're supposed to be a 1:1 mapping to each other. This will avoid unecessary serialization/deserialization
CI
=> Make BlobContent into enum

linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/linera_net_tests.rs
In some end-to-end tests we run the node service with the `Skip` policy, so it doesn't automatically process its inbox. That means the outcomes of the explicit calls to `process_inbox` should be deterministic.
Check that these calls do return one new certificate hash.
This should make the tests fail earlier if there is a problem.
- (Related to debugging https://github.com/linera-io/linera-protocol/pull/2538.)
=> Assert that the inboxes are not empty.

linera-core/src/chain_worker/state/attempted_changes.rs, linera-service/tests/linera_net_tests.rs
There is a bug in `process_cross_chain_update`: `new_outbox_entries` is meant to be `true` if any `receive_message_bundle` returned true, so I used `||` without taking into account that that short-circuits, so the `receive_message_bundle` call isn't actually made if `new_outbox_entries` is already `true`.
Switch the order of the arguments.
Since this is a simple fix, we could merge that as soon as possible. Coming up with a scenario that exposes this and writing a regression test will take some time (https://github.com/linera-io/linera-protocol/issues/2544). The failure will probably look similar to the one in https://github.com/linera-io/linera-protocol/pull/2538, but this fix didn't address that.
- be released in a …
=> Receive bundles even if new_outbox_entries.

Cargo.lock, examples/Cargo.lock, linera-rpc/build.rs, linera-storage-service/build.rs
fix CI after a semver violation by `tonic-build` (when building with `-D warnings`)
* Run `cargo update`
* Apply the suggestion
I didn't add `--locked` to the line
```
cargo install --path linera-service --bin linera --bin linera-server --debug
```
in `.github/workflows/docker.yml` because I thought most users may not pass `--locked`.
CI
=> fix fatal warning for tonic_build in CI

linera-storage-service/src/client.rs, linera-storage-service/src/common.rs
We want to achieve the best performance and the `storage-service` does not use the LRU caching.
* The LRU was implemented in a similar way to `ScyllaDb` / `DynamoDb` which lead to a streamlinging of the code
* Perhaps controversially, the variable `LRU_STORAGE_SERVICE_METRICS` is introduced in the `linera-storage-service/src/common.rs`. This is because the variable is set in `metering.rs` but feature gated by `RocksDb`, `ScyllaDb` and `DynamoDb`. Since the feature `storage-service` is not available in `linera-views`. This is why we have the duplication.
CI for the correctness of the tests.
Performance analysis.
Model setup:
* Use the `test_wasm_end_to_end_amm` on release and debug mode.
* Use the scripting program `run_and_obtain_metrics` from …
=> Add the LRU caching to the `storage-service`

linera-client/src/client_context.rs, linera-client/src/unit_tests/chain_listener.rs
The `Client` is always called `"Client node"`. This makes debugging difficult in tests involving multiple clients.
Include the chain ID(s) in the name.
No changed logic, but it should make debugging end-to-end tests easier.
- (Found while debugging https://github.com/linera-io/linera-protocol/pull/2538.)
=> Include chain in client node name.

CLI.md, linera-chain/src/test.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/benches/client_benchmarks.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/system.rs, linera-execution/tests/test_system_execution.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/block.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/linera/main.rs, linera-service/src/node_service.rs
As described in the [issue](https://github.com/linera-io/linera-protocol/issues/2554), we no longer need `UserData` argument. 
Closes https://github.com/linera-io/linera-protocol/issues/2554 .
Remove `UserData` arg from `Transfer`/`Claim` and `Burn` commands.
- Nothing to do
=> RM UserData from Transfer command and node service.

.github/workflows/long_faucet_chain_test.yml, linera-service/tests/linera_net_tests.rs
One of the CI tests takes to long to finish, and also doesn't stress as much as it should.
Move the test to a separate GitHub Actions workflow, that only runs _after_ a PR has been merged. That way it still detects any problems, but doesn't block the usual development workflow.
Manually ran the test command, but still need to check how GitHub will handle it.
Nothing needed because this only affects tests.
=> Move long faucet chain test to different CI workflow

Cargo.lock, Cargo.toml, examples/Cargo.lock, linera-chain/src/unit_tests/chain_tests.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-execution/Cargo.toml, linera-execution/src/lib.rs, linera-execution/src/test_utils/mod.rs, linera-execution/tests/wasm.rs, linera-storage/src/lib.rs
We are `Arc`ing a type that is already internally an `Arc` and therefore has cheap `Clone`.
Remove the `Arc` (using `dyn-clone` to forward cloning to the boxed trait objects instead). 
CI.
=> `linera-execution`: remove unnecessary `Arc`

linera-client/src/client_options.rs, linera-client/src/storage.rs, linera-indexer/lib/src/rocks_db.rs, linera-storage-service/src/server.rs, linera-views/benches/stores.rs, linera-views/src/backends/rocks_db.rs
The RocksDb storage is a very important store for which every impact in performance is key.
* The effective computation was moved to `inner_*` functions which are not async.
* The constructor of the RocksDbStoreInternal is now building a boolean indicating whether to use `spawn_blocking` or `block_in_place`.
* Each method is choosen according to the context.
(A) It has been verified that the `linera-views` tests are running with `spawn_blocking` and the benchmarks
with `block_in_place`.
(B) Correctness should be provided by the CI.
(C) Since this is a performance improvement PR, performance results are needed.
* This was done with: `cargo bench store_rocksdb_ --features rocksdb`.
* As the benchmarks numbers are quite unstable, it was repeated 10 times with the …
=> Improve the performance of the RocksDb.

linera-service/tests/linera_net_tests.rs
The new GitHub Actions workflow to run the long Faucet chain test (PR #2533) was failing because it would exceed the 3 hour limit for the job.
Reduce the chain length so that the test runs in the allocated time limit.
Long term the test execution time should decrease, which should allow using a longer chain again.
TODO: Manually trigged a CI run, now waiting to check if it passes.
Nothing to do, this only affects CI and tests.
=> Use a shorter chain in the long faucet chain test

CLI.md, linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/node_provider.rs, linera-rpc/tests/transport.rs
When running `test_wasm_end_to_end_fungible::storage_service_grpc` locally I get a failure almost 10% of the time because of a gRPC error with status code `Unknown`. We consider these (and a few other) errors to be retryable when they occur in notification streams, but not in other requests.
Make the gRPC client retry all requests if the status code is considered retryable.
With this I ran the test 76 times without failure.
=> Retry all gRPC requests, not just notification streams.

linera-service/Cargo.toml, linera-service/src/lib.rs, linera-service/src/linera/main.rs, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs
A lot of our spans in `linera-service` had the name `run`, which made it sometimes difficult to distinguish their output on the console.
Demarcate the proxy a little more (moving `proxy.rs` and `grpc_proxy.rs` into their own subdirectory) and give them more unique spans.
CI.
None required.
=> Minor `linera-service` tracing output improvements

linera-core/src/client/mod.rs
I'm seeing what looks like sporadic deadlocks in the end-to-end tests (mostly fungible and matching engine) if I run them locally with the storage service.
Hold the client mutex only as long as needed.
Running this locally for ~50 times I couldn't reproduce the deadlock issue.
- The PR that presumably caused the issue: https://github.com/linera-io/linera-protocol/pull/2567
=> Don't keep the client mutex longer than necessary.

Cargo.lock, linera-service/Cargo.toml, linera-service/src/project.rs, linera-service/template/contract.rs.template, linera-service/template/lib.rs.template, linera-service/template/service.rs.template, linera-service/template/state.rs.template
When generating a new linera project we were using generic `Application` as the name for `struct`s, `trait`s, etc rather than given project name (used when calling `linera project new <name>` command).
Parse given project name to PascalCase and use where appropriate.
Closes https://github.com/linera-io/linera-protocol/issues/2577
Built the `linera` binary locally and run `linera project new my-counter`. The project builds correctly (after fixing dependencies' versions) and and the `my-counter` is used properly:
* `my_counter` as a module name.
* `MyCounter` as a name in `trait`s and `struct`s.
=> Use name in the code when generating new linera project

linera-core/src/client/mod.rs
Currently the client synchronizes the admin chain in addition to the user's chain (or whatever chain is currently being used) in every call to `find_received_certificates`, to make sure we have all committees, even the ones that have been created by the admin chain but not handled yet by the other chain. That is wasteful.
Synchronize the admin chain only when we encounter an incoming message from a future epoch.
No new features were added, and the admin chain change was just an optimization, where existing tests should catch any regressions.
- Previous attempt: https://github.com/linera-io/linera-protocol/pull/2473
- Reverted in https://github.com/linera-io/linera-protocol/pull/2483
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-check …
=> Sync admin chain only when needed

examples/amm/README.md, examples/amm/src/lib.rs, examples/counter/README.md, examples/counter/src/lib.rs, examples/crowd-funding/README.md, examples/crowd-funding/src/lib.rs, examples/fungible/README.md, examples/fungible/src/lib.rs, examples/gen-nft/README.md, examples/gen-nft/src/lib.rs, examples/hex-game/README.md, examples/hex-game/src/lib.rs, examples/matching-engine/README.md, examples/matching-engine/src/lib.rs, examples/native-fungible/README.md, examples/native-fungible/src/lib.rs, examples/non-fungible/README.md, examples/non-fungible/src/lib.rs, examples/social/README.md, examples/social/src/lib.rs
There are several links in the README's that don't actually link to a valid URL as they have environment variables within them.
Also `QUERY_RESULT` appears in the README's but we don't explain what it is or how to use it.
Fix the README's so that the user is instructed to run `echo` commands to get the proper URLs that need to be used.
Explain how to use `QUERY_RESULT` also.
CI
=> Some fixes on README's

Cargo.lock, Cargo.toml, examples/Cargo.lock, linera-execution/Cargo.toml, linera-execution/src/wasm/sanitizer.rs, linera-witty/Cargo.toml
We've recently had dependency version conflicts for `wat` between `wasmer` and `wasmtime`, which required releasing a new version of our `linera-wasmer` work every time an update for `wasmtime` was needed (#2427, #2530). That dependency on `wat` isn't actually needed on either runtime, except for a couple of tests.
Disable the `wat` features and additional features from `wasmer` and `wasmtime`.
Because `dev-dependencies` can't have optional dependencies, now `linera-execution` tests require `wasmer` so that it can enable the `wat` feature.
CI should catch regressions, since this just changes dependencies.
- Nothing to do / These changes follow the usual release cycle, as these changes should be backwards compatible.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/m …
=> Disable `wat` feature from `wasmer` and `wasmtime`

CLI.md, linera-client/src/client_options.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/tests/local_net_tests.rs
We don't want to deprecate old committees by default, especially on the public devnets and testnets.
Make `finalize-committee` a separate command.
We use it in the reconfiguration test now, and check that there is only one committee left at the end.
=> Make finalize-committee a separate command.

linera-client/src/client_context.rs, linera-core/src/client.rs
The `test_end_to_end_benchmark::storage_service_grpc` fails, because `make_chain_client` is called multiple times for the same chain.
Don't fail in that case, but compare the chain state to make sure it is up-to-date.
The latter also revealed that we missed some `update_wallet_from_client` calls.
Creating multiple chain clients is okay: `ChainClient` is already `Clone` anyway. Also, in the test the one chain client is dropped before the other one is created.
I ran the test 100 times in a loop and it didn't fail anymore.
- These changes should be ported to the `main` branch.
=> Allow creating a ChainClient if the chain is already in the map.

linera-client/src/chain_listener.rs
When a new chain is opened, the chain listener starts subscribing for notifications from all validators for the new chain.
In some cases, like the faucet, that will create a lot of connections.
Only subscribe if we own the new chain.
This should reduce the number of connections the faucet creates. CI should catch any regressions.
- These changes should be ported to main.
- We should release a new SDK, or at least use this version for the faucet.
=> Follow new chains only if we own them.

.github/workflows/rust.yml, linera-service/src/benchmark.rs, linera-service/tests/linera_net_tests.rs
The benchmark test doesn't run in CI at all, because it needs the `storage-service` feature.
Enable the feature.
This should now run the test in CI.
- I forgot to add that in #2596.
=> Add the storage-service feature to run the benchmark test in CI.

Cargo.toml, linera-rpc/src/grpc/conversions.rs
While working on the airdrop demo, I couldn't compile the application for `wasm32-unknown-unknown` after enabling `alloy-primitives`'s `k256` feature. The build failed because `getrandom` was included as a dependency.
After investigating the issue, it seems like not disabling `ed25519-dalek`'s default features in `linera-sdk` causes it to enable one of `k256` features that eventually includes `getrandom`.
Disable default features of the `ed25519-dalek` dependency.
A consequence of disabling the `std` feature from `ed25519-dalek` is that the `std::error::Error` trait isn't implemented for `ed25519_dalek::SignatureError`. Therefore, the `#[from]` attribute was removed from within the `GrpcProtoConversionError::SignatureError` variant. That means that it no longer uses a source error.
After …
=> Disable `ed25519-dalek` default features

docker/dashboards/linera-general.json, docker/docker-compose.yml, docker/prometheus.yml, docker/provisioning/dashboards/dashboards.yml
Validator operators currently do not have insights on how their validators are behaving and performing. 
Add a Prometheus / Grafana deployment along with some Linera-specific Grafana dashboards.
This is _strict subset_ of the Kubernetes dashboards, due to things like Cluster resource usage not being applicable under Docker Compose.
=> Docker compose metrics

linera-core/src/chain_worker/state/mod.rs
`get_blobs` is used when we process confirmed blocks, so it's actually wrong to not check storage here.
Check storage also when searching for the blobs.
CI but this will also be more triggered in following PRs
=> Check storage in get_blobs

linera-base/src/data_types.rs, linera-base/src/identifiers.rs
As we start adding new blob types, it would be good to have a common abstraction for how we generate the hashable bytes for blobs
Create the `blob_bytes` function. This will be more used also in following PRs.
CI
=> Introduce blob_bytes function

Cargo.lock, Cargo.toml, examples/Cargo.lock, linera-execution/Cargo.toml, linera-execution/src/wasm/wasmer.rs
We see a segfault in `wasmer-compiler-singlepass` code generation very occasionally in some cases.  In case it is the cause, and because we want this to be as predictable as possible anyway, disable multithreading for the `Singlepass` compiler.
Replace our dependency on `wasmer/singlepass` with a direct dependency on `wasmer-compiler-singlepass`, and turn off the `rayon` feature.
@afck needs to run the test many times as the only person who can reproduce the segfault. :)
=> `linera-execution`: disable multithreading in `wasmer-compiler-singlepass`

linera-views/src/test_utils/mod.rs, linera-views/tests/views_tests.rs
As much as this approach works, we already have a `shuffle` function in `SliceRandom`. Some points in favor of `SliceRandom`'s `shuffle`:
* This code executes multiple swaps between two randomly selected indices in the array, `SliceRandom::shuffle` performs an optimized Knuth shuffle which does `O(n)` swaps
* Some of these multiple swaps could also be redundant, which is less efficient in number of operations and randomness quality, becase multiple swaps also can potentially create a bias: since some elements can be swapped more times than others, we won't have every permutation be equally likely
Use `SliceRandom::shuffle` instead
CI
=> Remove random_shuffle in favor of SliceRandom's shuffle

linera-execution/src/execution.rs
Sending messages to multiple applications could lead to non-deterministic execution outcomes (issue #2615).
This was caused by the incorrect usage of `FuturesUnordered`, which led to a non-deterministic order of application registration messages.
Use `FuturesOrdered` instead in order to provide a deterministic order.
This can be tested manually with a block that sends messages to at least two different destinations or that requires two different applications to be registered on the receiving chain.
- [reviewer …
=> Fix unordered application registration messages

linera-service/src/cli_wrappers/remote_net.rs
Each `remote-net` test requests 10 new chains from the faucet, even though none use that many.
Only request three chains.
The tests passed for me locally this way. It should also make the daily test run against devnet and testnet more stable.
- These changes should be ported to the main branch.
=> Don't create 10 chains for each remote-net test.

linera-core/src/client/mod.rs, linera-core/src/lib.rs, linera-core/src/local_node.rs, linera-core/src/remote_node.rs, linera-core/src/updater.rs, linera-service/src/linera/main.rs
`linera_core::local_node` contains a lot of code that doesn't deal with the local node at all, and only interacts with a remote node.
Move `RemoteNode` to its own module. Move `try_query_certificates_from` to `RemoteNode`, since it doesn't use the local node at all. 
No logic was changed. CI should catch any regressions.
=> Move RemoteNode to its own module; move try_query_certificates_from there.

linera-execution/src/execution.rs
This is a port of #2621 to the testnet branch.
Sending messages to multiple applications could lead to non-deterministic execution outcomes (issue #2615).
This was caused by the incorrect usage of `FuturesUnordered`, which led to a non-deterministic order of application registration messages.
Use `FuturesOrdered` instead in order to provide a deterministic order.
This can be tested manually with a block that sends messages to at least two different destinations or that requires two different applications to be registered on the receiving chain.
Unit tests should be added later (#2624).
This is a backport of #2621, and should be included in the next release.
=> Fix unordered application registration messages (port to testnet)

.github/workflows/rust.yml, CLI.md, linera-client/src/client_options.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs, linera-service/tests/linera_net_tests.rs
It is a long running objective to have the `linera-net-tests` running on a single set of validators.
* The `storage-service` tests are disabled in `linera_net_tests.rs` by renaming their title from `storage_service_grpc` to `storage_test_service_grpc`.
* The related work for making the `remote-net` are added to the CI file.
(A) The CI should pass. The change is that some tests pass from running on the `storage-service` to running on the `remote-net`.
(B) The runtime of the 20 tests of linera_net_tests.rs is 691 seconds on the `storage-service` and 345 seconds on the `remote-net` by using 1 validator and 1 shard. However, when running on 4 validators and 4 shards, the gains are much more modest with 638 seconds. Due to the additional compilation work this translates …
=> Make the linera-net-tests run on `remote-net` instead of `storage-service`.

linera-service/src/proxy/main.rs
=> Fixed us typo in proxy.

Cargo.lock, linera-chain/Cargo.toml, linera-client/Cargo.toml, linera-core/Cargo.toml, linera-execution/Cargo.toml, linera-rpc/Cargo.toml, linera-sdk/Cargo.toml, linera-service/Cargo.toml, linera-storage-service/Cargo.toml, linera-storage/Cargo.toml, linera-views/Cargo.toml
Currently our `test` features are not necessarily depending on the `test` features from the crate's dependencies
Fix that and make sure our `test` feature depends on the `test` feature from our dependencies
CI
=> Make sure our test features depend on their dependencies test features

linera-chain/src/lib.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/mod.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/wasm.rs, linera-storage/src/lib.rs
* Some code was left over from when we removed the non-blobs bytecode code
* Some places in tests were not using the bytecode blobs properly
Fix those and properly mimic what we're doing with user contract/service code with blobs.
CI
=> Clean up left over Bytecode code + some related testing fixes

.github/workflows/long_faucet_chain_test.yml
The workflow file for the long faucet chain test had a job that was incorrectly named "benchmark". Which made CI summaries confusing.
Rename it to "long-faucet-chain-test".
CI should show the updated name.
- Nothing to do because this only affects CI.
=> Fix name of "long-faucet-chain-test" job in CI

Cargo.toml
`ed25519-dalek`'s `default` features ended up transitively including `getrandom` as a dependency, which was an issue for Linera Wasm applications that use `linera-sdk`. Therefore, it was disabled by PR #2602. However, that also disabled the `fast` feature, was caused a performance regression.
Re-enable the `fast` feature, together with the `zeroize` feature which is also important.
The long faucet chain test should now not timeout in CI.
- Nothing to do / These changes follow the usual release cycle, because this fixes a regression for an issue that is not present in any released version.
=> Fix performance regression caused by disabling `ed25519-dalek`'s `fast` feature

.github/workflows/long_faucet_chain_test.yml
The long faucet chain test job in CI takes a long time and the chain isn't even very long (currently at 3000 blocks). When running the test locally, I realized it was a lot faster, and when investigating I realized that CI was running in `debug` mode.
Run the test in `release` mode.
CI should now show that long faucet chain test is faster.
- Nothing to do because this only affects CI.
=> Run long faucet chain test in release mode

linera-service/src/cli_wrappers/wallet.rs
The long faucet chain test is failing due to query timeouts when initializing the wallet from the faucet. This happens because the faucet is still busy processing blocks.
The `cli_wrappers::wallet::NodeService::query_node()` method automatically retries for a few attempts on certain errors, in order to prevent failures due to race conditions. However, it did not retry in case of a timeout.
Treat `reqwest` timeout errors the same as errors reported through GraphQL.
CI should show that the long faucet chain test no longer fails because of the query timing out while initializing the wallet.
- Nothing to do because these changes only affect CI and tests.
=> Retry node service queries if they timeout

linera-core/src/client/mod.rs
Working on adding `download_certificates` endpoint and as part of the work I refactored `synchronized_received_certificates_from_validator` method a bit. Posting this small change as a separate PR to simplify and speedup discussions.
Refactor `synchronized_received_certificates_from_validator`
=> Refactor synchronized_received_certificates_from_validator

Cargo.lock, linera-core/src/client/mod.rs, linera-core/src/lib.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/test_utils.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/grpc/mod.rs, linera-rpc/src/message.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/server.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/Cargo.toml, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs
Running `linera sync-balance` command (on admin chain) takes a long time. Some metering and debugging revealed that majority of that time is spent downloading certificates from validators. This process is sequential in the scope of syncing a single chain – i.e. we iterate over all (missing) blocks from that chain and synchronize all the state which is required to properly validate the chain (including chains that sent messages to the chain-being-synced).
A quick, back-of-the-hand experiments showed that parallelising `synchronize_received_certificates_from_validator` increases the performance by the order of magnitude.
As part of that sequential process we fetch chains' certificates, one by one. We introduce a new `download_certificates(hashes)` endpoint to the `ValidatorNode` which can …
=> Add download certificates endpoint

linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs
The documentation for `ContractRuntime::query_service` was incorrect, because it led the reader to believe that it was only possible to query the current application's service, while in fact it could be used to query any application's service.
Fix the documentation.
Nothing needed, because this only affects documentation.
- Nothing to do, because the updated documentation should be released with the next version automatically.
=> Fix query target in `ContractRuntime::query_service` documentation

linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/notifier.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/src/linera/main.rs, linera-service/src/proxy/grpc.rs
The `join_all` in `synchronize_chain_state` returns only after the task associated with the last validator returns. So a single slow or faulty validator can slow down the client a lot.
Return from `sync_chain_state` once a quorum has finished.
On `testnet_boole`, this [this approach](https://github.com/afck/linera-protocol/commit/b20b4ae43888662630bf19df206184cd0f40ed6e) made `test_wasm_end_to_end_fungible::remote_net_grpc` pass after 37 seconds. Without it, it fails after 15 minutes.
- Fixes https://github.com/linera-io/linera-protocol/issues/2629.
- …
=> Return from sync_chain_state after a quorum has finished.

linera-chain/src/chain.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs
https://github.com/linera-io/linera-protocol/pull/2035 introduced a list of "tracked chains": In the local node, messages to non-tracked chains are not delivered and stay in the outbox.
However, `all_messages_delivered_up_to` doesn't take that into account yet, so if a chain is sending a message to a non-tracked chain, it would never return `true`, and if `wait_for_outgoing_messages` is `true`, `handle_certificate` could wait forever.
Return `true` from `all_messages_delivered_up_to` if all messages to _tracked_ chains have been delivered, ignoring remaining outbox entries for untracked chains.
TBD: This makes `wait_for_outgoing_messages` async and potentially much slower. We could instead add `tracked_outbox_counters` that count only messages to tracked chains. This would need to be …
=> Make all_messages_delivered_up_to take tracked_chains into account.

linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs
https://github.com/linera-io/linera-protocol/pull/2035 introduced a list of "tracked chains": In the local node, messages to non-tracked chains are not delivered and stay in the outbox.
However, `all_messages_delivered_up_to` doesn't take that into account yet, so if a chain is sending a message to a non-tracked chain, it would never return `true`, and if `wait_for_outgoing_messages` is `true`, `handle_certificate` could wait forever.
Return `true` from `all_messages_delivered_up_to` if all messages to _tracked_ chains have been delivered, ignoring remaining outbox entries for untracked chains.
TBD: I should add a regression test for this.
- This is the `testnet_boole` backport of https://github.com/linera-io/linera-protocol/pull/2562.
- It should be released in a new SDK.
- `main` …
=> Make all_messages_delivered_up_to take tracked_chains into account. (Boole backport)

linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/notifier.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/src/linera/main.rs, linera-service/src/proxy/grpc.rs
The `join_all` in `synchronize_chain_state` returns only after the task associated with the last validator returns. So a single slow or faulty validator can slow down the client a lot.
Return from `sync_chain_state` once a quorum has finished.
On `testnet_boole`, this [this approach](https://github.com/afck/linera-protocol/commit/b20b4ae43888662630bf19df206184cd0f40ed6e) made `test_wasm_end_to_end_fungible::remote_net_grpc` pass after 37 seconds. Without it, it fails after 15 minutes.
- This is the `testnet_boole` backport of https://github.com/linera-io/linera-protocol/pull/2653.
- It should be released in a new SDK.
- `main` version: https://github.com/linera-io/linera-protocol/pull/2653
- Fixes https://github.com/linera-io/linera-protocol/issues/2629.
- …
=> Return from sync_chain_state after a quorum has finished. (#2653)

linera-client/src/util.rs, linera-client/src/wallet.rs
When we try to save the wallet, the `pending_blobs` inside of `UserChain` will need to be serialized to JSON, but that map is currently a `BlobId`.
Write a custom serialization module for BTreeMaps that will serialize the keys as strings
Fixes #2665
CI + stacked #2646 on top of this and ran the benchmark test, it did not fail in the serialization anymore
=> Serialize BTreeMap with keys as strings

linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
The `read_certificates` is currently using the `join_all` operation which is not the right way to access several data at the same time with the storage.
The solution was to group the calls with a single call to `read_multi_values_bytes`. An additional metric was introduced for the `read_certificates`.
The CI is sufficient.
If the issue is important enough, then it could be merged into the TestNet.
=> Use the `read_multi_values_bytes` for the `read_certificates`

.github/workflows/docker.yml, configuration/compose/validator.toml, docker/docker-compose.yml
Docker validators had 1 shard which was a potential performance bottleneck.
Docker validators now have 4 shards using the deploy replica strategy.
Regressions will be caught by CI.
<!--
If this PR targets the `main` branch, **keep the applicable lines** to indicate if you
=> Docker validator has 4 shards.

linera-core/src/client/chain_state.rs, linera-core/src/client/mod.rs
The admin ID can't change, and we are locking the `ChainState` each time we access it.
We are locking and unlocking the `ChainState` multiple times in some cases to obtain the components of a chain's tip state (block hash, height and timestamp). If the state changed in between those instances, the components won't refer to the same state.
In some cases we return an error if the local node's chain is ahead of the `ChainState`. But in multi-owner chains, this can happen legitimately.
Move `admin_id` out of `ChainState`. Fetch the hash, height and timestamp in one go where necessary. Only do the check for single-owner chains.
Also, don't unnecessarily collect the known keys' owners, and use `contains_key` instead.
- Nothing to do / These changes follow the usual …
=> Fix some potential `ChainState` issues

linera-core/src/client/mod.rs, linera-core/src/data_types.rs
`synchronize_received_certificates_from_validators` synchronizes client's knowledge about a chain, from a validator, by going through incoming messages (from other chains) that node has seen for a chain being synchronized.
Currently, in `main`, we iterate sequentially through the `info.requested_received_log` and for every (`ChainAndHeight`) entry (`chain<>height` tuple) we do the following:
1. query local node (and check if we've already processed that entry)
2. query remote node (and learn a "certificate hash" corresponding to this particular entry)
3. download certificate from a remote node for that certificate hash
Assuming `n` chains with `m` entries (in `requested_received_log`) each we do `n * m` queries (with 2/3 being queries to a remote node). This turns out to be prohibitively …
=> Batch queries by chain when synchronizing certificates from validator.

kubernetes/linera-validator/helmfile.yaml
If no version is specified, the latest version of a Helm Chart is used, unintentionally breaking our validator deployment.
Pin ScyllaDB (and its dependency Cert Manager).
The pinned versions are what is used in `testnet-boole`.
<!--
If this PR targets the `main` branch, **keep the applicable lines** to indicate if you
recommend the changes to be picked in release branches, SDKs, and hotfixes.
This generally concerns only bug fixes.
=> Pin ScyllaDB Helm chart versions.

examples/Cargo.lock, linera-core/Cargo.toml, linera-core/src/chain_worker/state/mod.rs
The `create_cross_chain_request` is done by accessing the storage serially. This is suboptimal.
The `crate_cross_chain_request` are merged into a single `create_cross_chain_requests`.
The idea is to group all the calls into a single calls. This decreases the number of storage accesses.
Another correction is to add "linera-storage-service/test" to the `Cargo.toml` in order to make the compilation with test works in `linera-core`.
The CI.
I do not expect this to be important for the TestNet / DevNet.
None.
=> Group the `create_cross_chain_request` into a `create_cross_chain_requests`

Cargo.lock, Cargo.toml, examples/Cargo.lock
Explorer tests have been failing in all PRs
Seems to be related to `thiserror`, updating the version seems to fix it.
Explorer test should be green in CI now
Fixes #2686
=> Bump thiserror

.github/workflows/rust.yml
Old `wasm-pack` accepted a `--features` argument directly, but newer `wasm-pack` requires it be passed through escaped with a leading double-hyphen.  Sometimes we get one version or the other, for reasons I'm unsure of, but the older `wasm-pack` we have pinned also accepts the newer syntax, so let's just always pass it.  This should fix the flakiness we've been seeing with `wasm-pack` refusing to execute the test.
Add double hyphens to the invocation of `wasm-pack test` in CI for `linera-views`.
While we're at it, take the opportunity to test the `web-default` feature rather than hardcoding `web,indexeddb`.
CI.
Nothing special required, since this is a CI-only change.
=> `.github/workflows/rust.yml`: use newer `wasm-pack` syntax

.github/workflows/docker.yml, docker/compose.sh, scripts/deploy-validator.sh
Docker validators should provide their git commit when queried.
Inject the git commit into the docker build process.
```
$ linera --wallet wallet.json --storage rocksdb:linera.db query-validator grpc:localhost:19100
2024-10-22T19:34:21.838756Z  INFO linera::main: linera: Version information for new validator: Linera protocol: v0.13.0
RPC API hash: ZqNY7r+amtHKJVYpUngy/+yu/YXNTTgqJR17YOyWQtQ
GraphQL API hash: s/zNt/rFKTb63M7N6/Gfdmw4lRe+6+s8diGn6+A/Myk
WIT API hash: DTU+YHsJxaXJVywyYChS0/Kzu1lmAjAlUjtdayBz2hk
Source code: https://github.com/linera-io/linera-protocol/tree/fcdcd93a
9c46bc873013efc162f4e2a63cc27d7de9e4178297f898f426503c6d86c7dcc4
```
This generally concerns only bug fixes.
- be released …
=> Inject git commit into Docker image.

.github/workflows/long_faucet_chain_test.yml, linera-service/src/cli_wrappers/local_net.rs
Current logs in the faucet test seems to be approaching 100MB
Reduce log verbosity to `warn`
Also reduce timeout to 60min.
CI
=> CI: reduce verbosity in long faucet chain test

linera-base/src/data_types.rs, linera-client/src/client_context.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs
The `publish_bytecode` of the `client_context` is calling the `publish_bytecode` of the `chain_client`.
However, the `publish_bytecode` might be called several times via the `apply_client_command`. The problem is that the compression of the contract/service and the hash computation was done in the `publish_bytecode` of the `chain_client`. This means that the compression is done several times which is suboptimal.
* The `CompressedContractService` data type was introduced in the `linera-base`.
* The compression is done in the same way as in the `publish_bytecode` of the `chain_client`, that is panicking in case of error.
* The `publish_compressed_bytecode` is introduced to the `chain_client`.
This work was motivated by the problem of addressing timeout issues for the …
=> Improve the `publish_bytecode` functionality.

linera-core/src/client/mod.rs, linera-core/src/local_node.rs
Due to #2692, it is not guaranteed (although very likely) that `process_inbox` will process a message even if a quorum of validators have it.
Fully fixing this will require #2689 to be merged first.
Prepare for the fix by computing the sender chains that we need to wait for after synchronizing received certificates from validators.
This doesn't fully fix the issue yet. Once #2692 is fixed, we should be able to remove two of the `client_mutex` locked without making the tests flaky again.
- Part of #2692.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTI …
=> Compute which sender chains' message deliveries to wait for.

linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/delivery_notifier.rs, linera-core/src/chain_worker/mod.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/worker.rs
There was previously a risk of a race condition between registering a new delivery notifier and notifying the registered notifiers. This could lead to notifications being delayed or not being sent.
The race can happen because different `WorkerState` instances could be running and one of them attempts to register the notifier while another notifies that delivery has been made.
Handle the registration and notification inside the chain worker, which runs as an actor in its own task. That means that it isn't possible for the chain worker to race with itself.
To ensure that only the chain worker is able to register and notify, a new `DeliveryNotifier` helper type was created, and its `register` and `notify` methods can only be called by the `ChainWorkerWithAttemptedChanges`.
CI should catch …
=> Move delivery notifiers to chain worker

Cargo.lock, linera-client/Cargo.toml, linera-client/src/chain_listener.rs, linera-client/src/client_context.rs, linera-client/src/lib.rs, linera-client/src/unit_tests/chain_listener.rs, linera-client/src/unit_tests/mod.rs, linera-client/src/unit_tests/util.rs, linera-client/src/unit_tests/wallet.rs
CI was failing on PR #2646 with a JSON serialization failure. That was fixed by PR #2668 but we realized none of our tests covered this case.
Create a test that tries to save a wallet with pending blobs in it. Verified that before #2668 this test fails, and now it succeeds.
CI
=> Add unit test for saving wallet with pending blobs

linera-base/src/identifiers.rs, linera-client/src/util.rs, linera-client/src/wallet.rs
#2668 was not necessarily the best way we can fix this issue.
Always serialize `BlobId` as string if `is_human_readable`. Fixes #2671
Reverted #2668, made sure the `test_save_wallet_with_pending_blobs` test failed, and made sure it went back to passing with the new serialization implementation.
=> Always serialize BlobId as string if is_human_readable

.github/workflows/rust.yml
This step sometimes fails with API rate limit exceeded, but we don't actually need to run this from scratch everytime. Example failure: https://github.com/linera-io/linera-protocol/runs/31950311713
Cache this step
CI
=> Cache solc on CI

linera-service/src/proxy/grpc.rs
Currently if a call to `blob_last_used_by` returns an `Err`, we'll print a `ERROR` level log. That is not very accurate because validators could still be not fully in sync and some of them could be missing some blobs.
Change log level to `WARN`
CI
=> Return WARN if blob_last_used_by returns an Err in validators

Cargo.lock, linera-rpc/Cargo.toml, linera-rpc/src/grpc/transport.rs
TLS is broken for our client because we bumped Tonic, and Tonic 0.12 disables automatic TLS configuration when you use the `tls-roots` feature.
Enable TLS in `linera-rpc` when connecting, adding CA roots from `webpki-roots`.
=> `linera-rpc`: manually configure TLS for the client as required by Tonic ≥ 0.12

.github/workflows/docker.yml, docker/compose.sh
While getting #2683 across the finish line, I noticed some speed ups we could do to our Docker github workflow
We already build the docker image in `compose.sh`, so no need to do it again before running it.
#2683 made Docker CI last 20+ minutes. This brings it back to around 10 minutes. Docker CI should be sufficient testing here
=> Some optimizations on our Docker github workflow

linera-core/src/client/mod.rs, linera-core/src/local_node.rs
Due to https://github.com/linera-io/linera-protocol/issues/2692 `process_inbox` can in some cases return without processing a message, even though a quorum of validators already had the sending certificate.
The client mutex fixed this in most cases, but causes unnecessary contention.
Ensure that the messages are delivered using `retry_pending_cross_chain_requests`.
The tests should not be flaky anymore despite the removal of the two client locks.
- closes #2692 
=> Ensure received certificates' messages are delivered.

.github/workflows/docker.yml, .github/workflows/rust.yml, docker/compose.sh, examples/Cargo.lock, linera-base/src/identifiers.rs, linera-client/src/client_context.rs, linera-client/src/util.rs, linera-client/src/wallet.rs, linera-core/Cargo.toml, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/delivery_notifier.rs, linera-core/src/chain_worker/mod.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/chain_state.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/worker.rs, linera-service/src/proxy/grpc.rs, linera-storage-service/src/client.rs, linera-views/src/views/bucket_queue_view.rs, linera-views/tests/random_container_tests.rs
I've selectively picked PRs that landed on `main` ([diff](https://github.com/linera-io/linera-protocol/compare/devnet_2024_10_21...main)) that are missing from the `devnet_2024_10_21` branch.
PRs that I've skipped:
- https://github.com/linera-io/linera-protocol/pull/2679 - this adds a unit test (no effect on the release)
Everything else was cherry-picked (maybe we should be simply merging `main` ? that would have kept the history cleaner).
A PR that we definitely need to backport is:
- https://github.com/linera-io/linera-protocol/pull/2696
=> Backport some of the PRs from `main`

.github/workflows/docker.yml, docker/docker-compose.yml
PR #2603 is failing in CI because our custom runners isn't fully operational.
Tweak the CI workflow to not run in our custom runner.
CI should pass after this change.
SDK soon.
=> Use scylla production mode but disable it in CI

linera-service/src/cli_wrappers/remote_net.rs
A tiny optimization was found for the testing code. It's possible to use `unwrap_or_else` instead of `unwrap_or` in order to only execute the fallback option if the first option is unavailable.
Replace usage of `unwrap_or` which requires its argument to have been executed with `unwrap_or_else` which will only execute its argument if needed.
CI should catch any regressions, as this is a small refactor of the testing infrastructure.
- Nothing to do, because this only affects tests.
=> Skip reading environment variable and allocating a `String` if possible

linera-core/src/notifier.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-service/src/proxy/grpc.rs
We observe timeouts in GRPC clients when subscribing to a Linera proxy behind Nginx instances.
Make sure the GRPC `subscribe` immediately returns an empty value. This should force completion of the HTTP2 header and prevent the bug
* CI should catch any regression
* will need to be manually tested
=> Immediately acknowledge GRPC subscriptions

linera-service/src/cli_wrappers/remote_net.rs
The URL is currently incorrect, and changes often. It makes more sense to require the user to specify it when running the tests.
While running some tests with the `remote-net` feature enabled, they failed due to DNS issues. That was caused by an incorrect fallback URL that was hardcoded in the test.
Remove the fallback URL, and require the user to specify the remote URL.
Tested manually, checking that a test passes when `LINERA_FAUCET_URL` is properly configured and failing with the expected message when it's missing.
- Nothing to do, as this only affects tests.
=> Don't fallback to hardcoded devnet Faucet URL

docker/compose-proxy-entrypoint.sh, docker/compose-server-entrypoint.sh, docker/compose-server-init.sh, docker/docker-compose.yml
When using Docker Compose, we're not currently properly waiting for the service dependencies.
Add a health check, and remove the `init_done` file
CI: we can see from the Docker CI logs that both the `proxy` and `shard`s services only get created after `shard-init` exits:
```
Network docker_default  Creating
Network docker_default  Created
Volume "docker_grafana-storage"  Creating
Volume "docker_grafana-storage"  Created
Volume "docker_linera-scylla-data"  Creating
Volume "docker_linera-scylla-data"  Created
Container scylla  Creating
Container prometheus  Creating
Container grafana  Creating
Container prometheus  Created
Container scylla  Created
Container grafana  Created
Container shard-init  Creating
Container shard-init  Created
Container proxy  Creating
Container docker-shard-4 …
```
=> Depend on other services based on health checks for docker compose

linera-service/tests/linera_net_tests.rs
The long faucet chain test prints a lot of error messages reporting insufficient balance. This happens because the test creates many new chains with an empty balance, which prevents the chains from creating their genesis block receiving the current epoch.
These errors are useless, because those chains don't actually affect anything in the test, they only need to simulate a long faucet chain.
Add some tokens to the newly created chains.
Tested manually to see that the error messages disappear.
- These changes should be backported to the latest `devnet` and `testnet` branch, to help with debugging any problems in the long faucet chain test
- Closes #2645
=> Fix insufficient balance error messages in long faucet chain test

linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/linera_net_tests.rs
The long faucet chain test fails because the mutation to obtain a new chain from the faucet times out. This happens because the mutation is sent immediately after the faucet starts, and the faucet takes a while to start up. During startup, the wallet synchronizes all of its chains. This includes the (long) faucet chain, but also all the chains created earlier, which are useless from this point of the test onwards.
Remove the newly created chains from the wallet, so that they aren't synchronized when the faucet starts.
Tested manually to confirm the timeout disappears.
- These changes should be backported to the latest `devnet` and `testnet` branches, to prevent CI from failing for known reasons.
- 
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.m …
=> Fix faucet timeout in long faucet chain test

linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/linera_net_tests.rs
The long faucet chain test had two issues. One of them was that it printed a lot of useless "insufficient balance" errors. The second was that it wasn't stable, and would sometimes fail due to a timeout to obtain a new chain while the faucet was starting up.
Port the fixes on `main` to the `devnet_2024_10_21` branch:
- #2718
- #2721 
CI should show that test is more stable and less verbose.
- Nothing to do, this is the backport PR.
=> Port long faucet chain test fixes to devnet

linera-base/src/data_types.rs, linera-base/src/lib.rs, linera-base/src/limited_writer.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-core/src/worker.rs, linera-storage/src/lib.rs
Large blobs can make messages containing them exceed the gRPC message limit, and require a lot of storage and bandwidth.
In addition, we need to guard against small compressed bytecode that is excessively large when decompressed.
On testnet-boole, I successfully published a 6 MiB blob, but failed with 8 MiB.
Backport https://github.com/linera-io/linera-protocol/pull/2705, but hard-code the limits to remain backwards-compatible.
Make the blob limit 3 MiB, so that _two_ blobs (e.g. contract and service bytecode) fit in a block.
Make the bytecode limit 30 MiB.
The tests were backported, too.
This is the backport of https://github.com/linera-io/linera-protocol/pull/2705 to `testnet_boole`.
- `main` version: https://github.com/linera-io/linera-protocol/pull/2705
- [reviewer …
=> Add blob size limits. (#2705)

linera-base/src/data_types.rs, linera-core/src/chain_worker/state/temporary_changes.rs
In https://github.com/linera-io/linera-protocol/pull/2705 blob size limits were added. But blobs are put into the cache before their size is checked. If they are too large, they are now in the cache but will never be used.
Do the check before putting them in the cache.
This only avoids unnecessary caching. CI should catch any regressions.
- Related to https://github.com/linera-io/linera-protocol/pull/2705.
=> Don't cache blobs that are too large.

linera-core/src/client/chain_client_state.rs, linera-core/src/client/mod.rs
The name `ChainState` has caused confusion with `ChainStateView`. It's more a view of the current ongoing operations and synchronization of a chain client.
Rename `ChainState` to `ChainClientState`.
This is just renaming.
=> Rename ClientState to ChainClientState.

linera-service/src/server.rs, linera-service/src/util.rs
Allow editing the number of shard in a validator internal config file.
Create a command `linera-server edit-shards --server file.json --num-shards 4 --host 'shard-%' --port 8000 --metrics-host 'shard-%' --metrics-port 8001`
Because of port numbers, I figured we should use `%` when `num_shards` is written with 1 digits, `%%` for 2 digits, etc.
```
linera-server generate --validators configuration/local/validator_*.toml --committee committee.json --testing-prng-seed 1
linera-server edit-shards --server server_1.json --num-shards 02 --host 'shard-%%' --port '10000' --metrics-host 'shard-%%' --metrics-port '110%%'
```
- …
=> Shard editing command

linera-core/src/client/mod.rs, linera-rpc/src/grpc/client.rs
Increase verbosity of logs re: subscriptions
* Add one argument to `is_retryable`
* Report connection errors as warnings
CI + run a node service manually
[currently on the testnet branch]
=> Better logging for subscriptions

linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/mod.rs, linera-core/src/remote_node.rs
Synchronizing the admin chain on devnet-2024-10-21 is very slow.
In `synchronize_received_certificates_from_validator`:
* Make multiple requests for the _local_ chain infos of sender chains concurrently, but don't exceed the number of available chain workers.
* Fetch the _remote_ chain infos concurrently.
* Only make a single call to `download_certificates`, not one per sender chain.
* Don't track new chains unless they were created by one of our tracked chains.
* Simplifications: only take into account the highest sending block on each chain, rather than the list of sending blocks; update the tracker afterwards based on downloaded block heights.
This is only an optimization; CI should catch any regressions.
I ran locally, in release mode:
```
linera wallet init --with-other-chains …
```
=> Optimize `synchronize_received_certificates_from_validator`.

Cargo.toml
Our `Cargo.lock` locks us to Tonic 0.12.3, which is fine.  But since this version introduced backwards-incompatible API changes, and our `Cargo.toml` only specifies that we need version `0.12.0`, our build may break when building from a different workspace.
Upgrade Tonic to a minimum version of 0.12.3 in `Cargo.toml`. 
CI, and `linera-web`.
=> `Cargo.toml`: require tonic ≥ 0.12.3, below which we are not compatible

scripts/linera_net_helper.sh
Often when I launch a net with `linera_spawn_and_read_wallet_variables`, I also want to know the produced wallet variables.  Besides, it makes the output rather confusing, as it heralds some variables that are not forthcoming.
Print the variables, as well as sourcing them.
I tried it locally.
=> `scripts/linera_net_helper.sh`: also print out the environment variables

Cargo.lock, examples/Cargo.lock, linera-execution/Cargo.toml, linera-execution/src/wasm/wasmer.rs
We need to do this on native, where we use two different runtimes for compilation and running, but we don't need to (and indeed can't, without storing a copy of the Wasm bytecode separately) do it on the Web.
Failure to do this causes Wasmer to issue the very surprising error:
RuntimeError: call stack exhausted during Operation(0)
Conditionally compile the code to deserialize and reserialize the bytecode between `wasmer` backends, and disable it on the Web.
=> `linera_execution::wasm::wasmer`: don't serialize JS modules

linera-sdk/src/log.rs, linera-views/src/views/map_view.rs
The search for higher performance requires better timings. Some of those are accessible only on nightly compiles, which is not the case right now.
Two changes are made:
* Add documentation in `map:view.rs`.
* Replace `PanicInfo` by `PanicHookInfo` following the warnings.
With those changes, the following command
```
cargo +nightly test -- --report-time -Z unstable-options
```
is now working fine and reporting the times of the tests.
The CI.
Not relevant
=> Make the `cargo +nightly test` compile correctly.

linera-execution/src/wasm/mod.rs, linera-execution/src/wasm/module_cache.rs
Modules in both `wasmer` and `wasmtime` are cheap to clone already, being essentially `Arc`s inside.
Remove the unnecessary `Arc`, replacing it with a `Clone` bound.
CI.
=> `linera-execution`: remove unnecessary `Arc` from the module cache

.github/workflows/rust.yml, Cargo.toml, linera-base/Cargo.toml, linera-chain/Cargo.toml, linera-client/Cargo.toml, linera-core/Cargo.toml, linera-execution/Cargo.toml, linera-rpc/Cargo.toml, linera-sdk/Cargo.toml, linera-service/Cargo.toml, linera-storage-service/Cargo.toml, linera-storage/Cargo.toml, linera-views/Cargo.toml, linera-witty/Cargo.toml
Users should be able to use `linera net up` after `cargo install linera-storage-service linera-service` (without passing additional features).
Make `storage-service` a default feature
Caveat: `cargo test -p linera-service` will not pass anymore. Fixing this is a longer discussion (see e.g. #2699)
CI
=> Make storage-service a default feature

CLI.md, linera-client/src/client_options.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs
The commands `linera query-validator(s)` only superficially test validators.
Add a simple chain-info-query to the chain in use.
* CI
* manually tested a backport
=> Add GRPC test to `linera query-validator(s)`

linera-core/src/chain_worker/state/mod.rs
If a tracked chain A subscribes to another chain B, we need to process that `Subscribe` message from A to B, otherwise we won't locally create the cross-chain messages back from B to A.
Deliver messages if their target is tracked _or_ if the sender is subscribed to the target.
TBD
- These changes should be ported to `main`.
- They should be released in a new SDK.
- This is a (better?) alternative to https://github.com/linera-io/linera-protocol/pull/2767.
=> Deliver messages to untracked publisher chains.

linera-client/src/chain_listener.rs, linera-client/src/persistent/indexed_db.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/remote_node.rs, linera-core/src/worker.rs, linera-rpc/src/grpc/client.rs, linera-service/src/node_service.rs
Right now we use either `tracing::instrument` or `instrument` in different places.
For consistency (and grepability) it might be better to just do `instrument` everywhere.
CI
=> tracing::instrument -> instrument

.github/workflows/docker_image.yml
There seems to be some evidence online that `docker push -a` doesn't seem to be 100% reliable. We're seeing some images not have all the tags they're supposed to have.
`docker push` each tag individually, so we know for sure everything is being pushed and tagged properly.
Will push this to `devnet_2024_10_21`, which was the branch that we saw had this issue in the latest image.
=> Push all tags individually

linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/worker.rs, linera-sdk/src/test/chain.rs
This cache isn't needed, and actually was incorrect in how we were using it: the cache wrongfully technically gave access to unpublished blobs to any chain in the client, as well as masked a bug (we needed to be checking the chain manager's pending blobs in `get_blobs` also).
Remove the cache
Existing ts in CI should pass and confirm that this indeed wasn't needed.
I feel like this should probably be backported everywhere?
=> Remove blobs cache

linera-core/src/chain_worker/state/mod.rs
If a tracked chain A subscribes to another chain B, we need to process that `Subscribe` message from A to B, otherwise we won't locally create the cross-chain messages back from B to A.
https://github.com/linera-io/linera-protocol/pull/2768 fixes this on devnet.
Port https://github.com/linera-io/linera-protocol/pull/2768 to main.
Already in use on devnet.
- `devnet_2024_10_21` version: https://github.com/linera-io/linera-protocol/pull/2768
=> Deliver messages to untracked publisher chains. (#2768)

linera-core/src/client/mod.rs
In `find_received_certificates`, after downloading certificates from validators, we process them sequentially, by validator. This is not only slower than processing them in parallel, but in addition it will instantiate chain workers for the same sender chain multiple times, even if it's just to confirm that the previous validator had already provided all certificates and there's nothing to do.
Sort certificates by sender chain, and process the chains in parallel.
```
mkdir /tmp/devnet
cargo run --release --bin linera -- --wallet /tmp/devnet/wallet.json --storage rocksdb:/tmp/devnet/linera.db wallet init --with-other-chains e476187f6ddfeb9d588c7b45d3df334d5501d6499b3f9ad5595cae86cce16a65 --faucet https://faucet.devnet-2024-10-21.linera.net/
cargo run --release --bin linera -- --wallet …
```
=> Process downloaded certificates in parallel.

linera-core/src/client/mod.rs
https://github.com/linera-io/linera-protocol/pull/2762 significantly speeds up `find_received_certificates` on devnet.
Port it to main.
Tested the speedup manually on devnet. CI should catch regression.
- `devnet_2024_10_21` version: https://github.com/linera-io/linera-protocol/pull/2762
=> Process downloaded certificates in parallel. (#2762)

linera-core/src/client/mod.rs
We are currently continuing updating the tracker, even when we see an entry that we couldn't get or verify.
Break early to fix that
CI but maybe we should add a test that would catch this?
=> Stop updating tracker on first entry we couldn't get or verify

linera-execution/src/system.rs
Since `Subscribe` messages are handled off-chain, and trigger sending all previous messages in that channel, every newly created chain in an epoch greater than 0 will receive `CreateCommittee` messages for past epochs. These currently fail to execute.
Silently ignore past `CreateCommittee` messages instead.
https://github.com/linera-io/linera-protocol/issues/2772 is failing because of this, so it will test this fix.
- These changes should be ported to `main`,
- released in a new SDK,
- released in a validator hotfix.
- https://github.com/linera-io/linera-protocol/issues/2772 uncovered this issue.
- Bug ticket: https://github.com/linera-io/linera-protocol/issues/2791 (Will close when ported to main.)
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING. …
=> Accept past CreateCommittee messages.

linera-execution/src/system.rs
https://github.com/linera-io/linera-protocol/pull/2790 fixes a bug related to `CreateCommittee` messages.
Port it to `main`.
See https://github.com/linera-io/linera-protocol/pull/2790.
- These changes are applied to the devnet in https://github.com/linera-io/linera-protocol/pull/2790. They should be
- released in a new SDK,
- released in a validator hotfix.
- Fixes https://github.com/linera-io/linera-protocol/issues/2791.
=> Accept past CreateCommittee messages. (#2790)

linera-execution/src/system.rs
PR #2790 fixes a bug (issue #2791) where old `CreateCommittee` messages are rejected by the worker, and therefore prevents a chain from receiving newer epoch change messages. However, the fix led to a similar issue with the `RemoveCommittee` message, where the execution fails if the removed committee was not already in the set of known committees.
Don't fail if a `RemoveCommittee` message is received for a committee epoch that isn't in the chain's state.
CI will check this for regressions after PR #2797 is merged, which includes an end-to-end test for this issue.
- These changes should be backported to the latest `devnet` and `testnet` branches, because they contain a critical fix.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checkl …
=> Don't fail if removed committee doesn't exist.

linera-rpc/src/config.rs, linera-service/src/server.rs
If every validator has the same shard configuration all shards will be hot against all validators.
Use the validator name to shuffle chain allocation amongst shards.
=> Use the validator name to shuffle shards per validator.

linera-core/src/updater.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
The `updater.rs` has some issues with `read_blob_state` and `read_certificate` being used in loops while it is readily possible to use single operations.
The changes are straightforward:
* The `read_blob_states` is introduced in `linera-storage`.
* The `read_blob_states` is used on `missing_blob_ids` in the `updater.rs` code.
* The certificates are then read by the `read_certificates`.
There are other potential changes that could be done:
* `send_chain_information` could be grouped as well.
* `send_certificate` could be grouped as we
However, those require more discussion as they may impact the protocol.
The CI should be the one doing it.
The `read_multi_values` are checked in the `linera-views`.
That could be merged into the TestNet / DevNet as it does not change the way data is stored, …
=> Group download operations in `updater.rs`.

linera-service/tests/local_net_tests.rs
New chains were failing to process their inboxes because they attempted to accept old messages to change the epoch. However, the chain was already on a newer epoch, so the worker rejected those protected messages, which caused the error. The issue is described in more detail in #2791.
PRs #2790 and #2799 implement fixes for the issue, and this PR includes two regression tests for them.
Add two end-to-end tests to reproduce a minimal scenarios where the bug occurs.
CI should now reproduce the issue and pass after the fixes from #2790 and #2799.
- Nothing to do, as the important fix is in #2790 and #2799.
=> Test receipt of old epoch change messages

linera-core/src/chain_worker/state/mod.rs
The `get_blobs` function is iterating some `read_blob` operations, which are inefficient.
The chosen solution is simply to identify the missing blobs and then do a single storage query.
The CI.
This could be included in TestNet / DevNet upgrades as it does not impact the storage, just the way the queries are organized.
None.
=> Improve the `get_blobs` function

linera-core/src/chain_worker/state/mod.rs
In https://github.com/linera-io/linera-protocol/pull/2768 we changed the message delivery logic: messages to publisher chains are sent even if they are not tracked. That change isn't reflected in `all_messages_to_tracked_chains_delivered_up_to`, though.
Apply the same logic in `all_messages_to_tracked_chains_delivered_up_to`.
Since this depends on timing it is difficult to write a regression test for it with the current test frameworks.
- Related change: https://github.com/linera-io/linera-protocol/pull/2768
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTR …
=> Take subscriptions into account in all_messages_to_tracked_chains_delivered_up_to

scripts/install_hooks.sh
The git pre-push hook runs `cargo +nightly fmt`. If one has a nightly version locally that is different from the one in the toolchain file, this can fail.
Use the toolchain file instead.
It worked for me locally.
=> Use the configured nightly version in the pre-push hook.

.github/workflows/rust.yml, linera-client/src/unit_tests/mod.rs
On #1737 we added `continue-on-error` on the job level. AFAIU that will succeed even if the entire jobs fails with a cancellation for example, which will happen when we timeout.
This was causing this job to silently succeed while timing out for a while.
Split the different lints into their own jobs, adding parallelism and also giving us individual failures
CI
=> Fix lint CI and split it into multiple jobs

.github/workflows/rust.yml
CI takes a long time
Split into more jobs, which will make us do roughly the same amount of work, but more parallelized. So hopefully this reduces CI time without increasing github costs much.
CI
With this and the PR before this one (#2785), we went from having the `test` job sometimes take up to an hour, to now, running many jobs in parallel, the test that takes the longest is `check-all-features`, which takes around 30 minutes.
=> Split rust CI into more jobs

scripts/check_chain_loads.sh, scripts/deploy-validator.sh
Fix `scripts/deploy-validator.sh`
Replace `cd ..` by the appropriate command
Run similar code in `scripts/check_chain_loads.sh`
=> allow deployment script to run from the source of the repo

docker/docker-compose.yml, scripts/deploy-validator.sh
The linera docker image used with Docker compose is hard-coded to a local linera image. This forces validators to build images.
Use the pre-built images in artifact registry which are tagged with the branch name.
CI will catch regressions. Tested manually with `testnet_archimedes`.
=> Parameterise docker compose image

linera-core/src/client/mod.rs, linera-core/src/updater.rs
Following PR 2800, it was noted that the `send_chain_operations` were done inefficiently.
* Similarly to `send_chain_information_for_senders` a `BTreeMap` is created for the chain/blockheight.
* A stream is created for the sending of the data.
* The `ValidatorUpdater` is now `Clone` in order to be able to create the stream. This was not difficult as the two components of the stream were already clonable.
* The limitation to CHAIN_WORKER_LIMIT is enforced here which may or may not be a good idea.
Maybe the same use of a stream could be done for `send_chain_information_for_senders`.
The CI should suffice for that. This does not change the organization of the code.
This could be backported to the TestNet / DevNet.
None.
=> Reduce the number of `send_chain_information` and do them concurrently.

linera-core/src/updater.rs
Inspired by #2822, saw that we could do the same parallelization for `send_chain_information_for_senders` as well
Parallelize sending `send_chain_information`
CI
=> Parallelize send_chain_information_for_senders

linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/remote_node.rs, linera-service/src/linera/main.rs
Some methods of `LocalNode` use `RemoteNode` (and some don't even use `LocalNode` itself). The fact that there is a `LocalNodeError::NodeError` shows that these don't belong into that module at all.
Move functions that only use the remote node to `RemoteNode`. Move functions that use both the remote and the local node to `Client`. Remove `LocalNodeError::NodeError`.
(Further cleanups to distinguish between local and remote errors, especially in `communicate_with_quorum`, will be done in a follow-up PR.)
This is only a refactoring, so CI should catch any regressions.
- We _could_ backport these to devnet and testnet, to facilitate any future backports.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/mai …
=> Move functions between Client and LocalNode as appropriate

.github/workflows/rust.yml, linera-chain/src/chain.rs, linera-chain/src/inbox.rs, linera-chain/src/lib.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/data_types.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-sdk/src/test/chain.rs
The `test_end_to_end_open_multi_owner_chain` test fails against a network with multiple epochs, because the `transfer` command doesn't cause the client to download the received certificates.
In `prepare_chain`, check if `validated_incoming_bundles` is `Ok`.
If it is `Err`, that means we are missing some entries from the inbox that have already been received. In that situation, it is impossible for us to create a new block: our local node would not accept the proposal. So we have to call `find_received_certificates` to synchronize all the sender chains.
It's appropriate to add that to `prepare_chain`, because that function is meant to prepare us for adding a new block.
The added method call triggered a stack overflow in one test. This is because the `tracing::instrument` attribute seems to …
=> In prepare_chain, ensure validate_incoming_bundles is OK.

linera-views/src/backends/rocks_db.rs, linera-views/src/backends/value_splitting.rs
Issue #2828 is addressed here and only that issue.
Two changes are needed:
* Having `#[error(transparent)]. An alternative would have been `#[error("Inner store error: {0}")]`.
* Precising the `FilesystemError`.
There are other possibilities of improvement of the error handling, but this is for further PRs.
The CI is just what we need.
I think this kind of correction is useful for TestNet / DevNet operators.
None.
=> Correct 2828 issue.

linera-chain/src/data_types.rs, linera-client/src/client_options.rs, linera-core/src/node.rs
For fieldless enums, if we use glob imports before a match statement, and then remove one of the enum variants, that removed enum variant silently becomes a catch all in the match statement.
The compiler shows no errors for it.
Stop using glob imports for fieldless enums. Now removing a variant should cause a compilation error for these, as expected.
CI
=> Don't use glob imports for fieldless enums

linera-chain/src/test.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/system.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/test_system_execution.rs
It's currently possible for an application to transfer funds from the receiving chain's shared owner balance when receiving a message. The only authentication is off-chain, where it is assumed that owners will reject messages that move the shared chain balance without permission. However, by default the node services automatically receives messages. This means that it's too easy to mistakenly accept a message that transfers the shared chain balance tokens without the appropriate permission.
Reject transfer attempts when the authenticated signer is not one of the chain owners.
A new unit test was added to cover the scenario. The test fails before the fix and passes after the fix.
- These changes should be backported to the latest `devnet` branch and `testnet` branch, because it improves …
=> Fix unauthorized access to chain balance

linera-base/src/data_types.rs, linera-base/src/prometheus_util.rs, linera-chain/src/chain.rs, linera-core/src/client/mod.rs, linera-core/src/value_cache.rs, linera-core/src/worker.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/system.rs, linera-execution/src/wasm/mod.rs, linera-rpc/src/grpc/server.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/metering.rs, linera-views/src/metrics.rs, linera-views/src/views/bucket_queue_view.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/log_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/queue_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/register_view.rs, linera-views/src/views/set_view.rs
The creation of metrics is done via the use of metrics created by `LazyLock`. The error cases are never handled and instead the `expect` statement is used to unwrap.
Move the statements where they matter. This partially addresses issue #2795.
Not relevant. We probably should have some metrics being tested in the CI.
This should not change the use scenario for TestNet / DevNet.
=> Switch position of expect statement for metrics.

linera-chain/src/block.rs, linera-chain/src/certificate.rs, linera-chain/src/manager.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
Similarly to the previous PRs - add a new `TimeoutCertificate` type and use where appropriately.
SDK soon.
Closes https://github.com/linera-io/linera-protocol/issues/2843
=> Introduce and use TimeoutCertificate

linera-chain/src/certificate.rs, linera-chain/src/data_types.rs
In the process of adding separate types to discriminate between various types of certificate we have, a new generic type was introduct - `Hashed<T>`. That type had the same structure as already-existing `HashedCertificateValue` but it was generic of a value type it holds. This duplication was unnecessary.
Replace a `struct HashedCertificateValue` with a type alias `type HashedCertificateValue = Hashed<CertificateValue>`
Closes #2842 
=> Unify HashedCertificateValue with Hashed<T>

linera-rpc/src/grpc/server.rs, linera-storage-service/src/client.rs, linera-storage-service/src/common.rs
There are a bunch of places where we are calling `format!("http://{}"...)` where we already have a method for this.
Use the method instead.
=> Replaced redundant calls to format.

.github/workflows/documentation.yml, scripts/test_publish.sh
cargo-local-registry builds fine on rust 1.81.0
- Updated `test_publish.sh` script to document use the latest version of `cargo-local-registry`.
- Modified GitHub actions workflow `documentation.yml` to install latest `cargo-local-registry` version.
- Fixes #2338
=> chore: Remove pinned version of cargo-local-registry

CLI.md, linera-client/src/client_options.rs, linera-service/src/benchmark.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/cli_wrappers/local_net.rs, linera-service/src/cli_wrappers/mod.rs, linera-service/src/cli_wrappers/remote_net.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
When we run the end-to-end tests against devnet or testnet, they create many temporary chains. Unfortunately, right now these chains never unsubscribes from the admin chain, which increases the load when advancing epochs.
Close the chains when the test finish, so that they don't stay subscribed to the admin chain for epoch changes.
A manual test is needed to check if the chains are really being closed. Maybe after running the end-to-end tests we can check if there are any open chains.
- These changes should be backported to the latest `devnet` branch and `testnet` branches so that the tests can run with the new code to close chains when they have finished.
- Closes #2772
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING. …
=> Close chains after tests finish

linera-client/src/storage.rs, linera-indexer/lib/src/rocks_db.rs, linera-indexer/lib/src/scylla_db.rs, linera-service/src/cli_wrappers/local_net.rs, linera-storage-service/src/client.rs, linera-storage-service/src/common.rs, linera-storage-service/src/server.rs, linera-views/src/backends/dual.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/journaling.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/metering.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/backends/value_splitting.rs, linera-views/src/store.rs
We have the `Journaling`, `ValueSplitting`, `LruCaching` and `MeteredStore` but the potential is not fully exploited with a relatively large quantity of boilerplate code.
* The `get_name()` function is introduced to the `AdminKeyValueStore`. Unfortunately, it was not possible to have a `&'static str` since we want to have composed types and so composed names.
* The introduction of the `get_name()` allows removing all the `KeyValueStoreMetrics` static variables and instead having a global store that contains the `KeyValueStoreMeytrics`.
* That global variable allows to put metrics for the `AdminKeyValueStore` trait function.
* The `AdminKeyValueStore` is added to all the Adaptor.
* For the `LruCaching` this requires the introduction of the `LruSplittingConfig` that …
=> Restructure the composed store adaptors

linera-chain/src/data_types.rs
`has_message` returns `true` if the message index is less than the length of `messages()`, which is a `Vec<Vec<_>>`.
This is used when assigning and synchronizing a new chain in the wallet, in the `wallet init` and `assign` commands.
Fix the implementation.
We will add a regression test later.
=> Fix `has_message` implementation.

linera-core/src/unit_tests/client_tests.rs
In #2869 we fixed `has_message` and thus `certificate_for`: It checked the index of the _transaction_ rather than the _message_.
An assertion was added to an existing test that sends two messages in a single transaction: Thus it does have a message with index 1, even though it doesn't have a transaction with index 1.
I verified that this failed before #2869.
- This is a regression test for: #2869 
=> Add a regression test for #2869.

linera-chain/src/certificate.rs, linera-chain/src/data_types.rs, linera-core/benches/client_benchmarks.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/src/message.rs, linera-service/src/linera/main.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
We know that in storage we only ever have instances of _confirmed_ certificates.
Reflect that fact in the API of the `Storage`.
Closes https://github.com/linera-io/linera-protocol/issues/2860
=> Read confirmed certs

linera-chain/Cargo.toml, linera-chain/src/block.rs, linera-chain/src/certificate.rs, linera-chain/src/data_types.rs, linera-chain/src/manager.rs, linera-core/src/local_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/value_cache_tests.rs, linera-core/src/worker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/Cargo.toml, linera-service/src/linera/main.rs
With more and more places adjusted to work with standalone-types, it turned out we can remove some repetition between `CertificateValue` variants and new types. 
Make the new types be part of the `CertificateValue` enum variants.
=> Use standalone structs in CertificateValue enum

examples/hex-game/tests/hex_game.rs, linera-chain/src/certificate.rs, linera-chain/src/data_types.rs, linera-chain/src/unit_tests/data_types_tests.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/message.rs, linera-sdk/src/test/block.rs, linera-sdk/src/test/chain.rs, linera-sdk/src/test/validator.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs
During an ongoing refactor it turned out that the `Certificate` type could become an alias of `GenericCertificate<CertificateValue>`.
Unify the types.
None. CI will catch any regressions.
Closes https://github.com/linera-io/linera-protocol/issues/2872
=> Certificate is a type alias for GenericCertificate

linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/updater.rs, linera-execution/src/lib.rs
The code in updater.rs does a fairly expensive things. It download first the blob states and then
for each blob_state it downloads the certificates but then only reads the chain_id and the block_height
which seems wasteful.
The following changes:
* Add the `block_height` and `chain_id` to the blob_state. We cannot remove the `last_used_by` since it is used by the `download_certificate` function. The addition is not expensive as the `block_height` and `chain_id` are small data types.
* Update the `attempted_change.rs` by adding this information as this is the only place where blob_state is created.
* Correspondingly change the `updater.rs`.
The CI.
This changes the `BlobState`, so it is not a matter of recompiling and running again the validators. It does break the storage state. If an …
=> Add `BlockHeight` and `ChainId` to `BlobState`.

linera-chain/src/lib.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs, linera-views/src/views/mod.rs
We've had these two different error variants for blobs for a while: `BlobNotFoundOnRead` and `BlobsNotFound`. The motivation was to differentiate between errors when doing a storage read, and everything else. In the current state of the code, I don't think this distinction is really giving us much, and it complicates the code more.
We also have this `get_blobs_not_found` function that abstracts away the different nested error types.
Remove `BlobNotFoundOnRead`, and simplify things a bit. Wrote custom/manual `From` implementations for these different error types, so we can have a `BlobsNotFound` error everywhere and can get rid of `get_blobs_not_found`.
Fixes #2628
CI
=> Get rid of get_blobs_not_found and unify blob errors

linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/updater.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/lib.rs
`next_block_heights` uses only the `LocalNode`, `send_optimized_certificate` only the `RemoteNode`. The checks in `LocalNode::find_missing_blobs` are really checking whether the _remote_ node is faulty.
This and other minor cleanups is making https://github.com/linera-io/linera-protocol/pull/2871 hard to review.
Move the logic to the module it belongs in, in this separate PR, so https://github.com/linera-io/linera-protocol/pull/2871 can be about https://github.com/linera-io/linera-protocol/issues/2857 only.
Apart from two new errors and a bit more information in the log messages, this is only a refactoring without new logic.
- This is preparation for https://github.com/linera-io/linera-protocol/issues/2857
- [reviewer …
=> Move more functions to the right module in linera-core.

linera-chain/src/block.rs, linera-chain/src/certificate/hashed.rs, linera-chain/src/certificate/mod.rs, linera-chain/src/certificate/value.rs, linera-chain/src/data_types.rs, linera-chain/src/manager.rs, linera-chain/src/test.rs, linera-chain/src/unit_tests/data_types_tests.rs, linera-client/src/client_context.rs
`Vote` and `SignatureAggregator` both work with hardcoded types (`Certificate` and `HashedCertificateValue` respectively) which is an obstacle to full removal of `Certificate` from the codebase.
Make both generic over type they work with. 
Closes https://github.com/linera-io/linera-protocol/issues/2885
=> Generalize Vote and SignatureAggregator over type of value they hold.

linera-service/src/proxy/grpc.rs
A lot of the code around this function changed, and I think we forgot to also update the name
Change it from `client_for_proxy_worker` to `worker_client`. This is already inside `GrpcProxy`, so I think having `proxy` in the name is redundant. The name of the struct that this returns is `ValidatorWorkerClient`, so `worker_client` seemed to make the most sense.
I think (IMHO) this makes it a lot easier to understand what this function is returning.
CI
=> client_for_proxy_worker -> worker_client

CLI.md, linera-chain/src/data_types.rs, linera-chain/src/lib.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/client_options.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/unit_tests/client_tests.rs, linera-execution/src/policy.rs, linera-execution/tests/fee_consumption.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs
Large block proposals can make messages containing them exceed the gRPC message limit, and require a lot of storage and bandwidth, as they may contain several blobs.
Add configurable block proposal size limits. This is part of #2199
CI, incremented one of the tests
=> Block proposal size limits

linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/updater.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
We are currently converting lots of errors to `NodeError`s and treating them as if they were the validator's fault in `communicate_with_quorum`. In the long run we will want to properly distinguish these (https://github.com/linera-io/linera-protocol/issues/2857): A _local_ error should make us cancel all the tasks and return that error immediately. However, we need to carefully go through all the code that runs inside tasks passed into `communicate_with_quorum` and make sure that no local error can be triggered by a remote node.
As a step towards addressing https://github.com/linera-io/linera-protocol/issues/2857, accept `ChainClientError`s from the tasks passed into `communicate_with_quorum`, but convert them all to `NodeError`s. That way we can be sure we are not opening up a new …
=> Accept `ChainClientError`s in `communicate_with_quorum`.

linera-core/src/client/mod.rs
`ChainClientError` can contain errors from the local node or the validators. We should keep these explicit so we can distinguish between them.
Stop manually implementing the conversion from `LocalNodeError` to `ChainClientError`
CI
=> Keep LocalNodeError::BlobsNotFound explicit

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
Now that we're not propagating any `BlobsNotFound` errors to `ChainClientError`, this variant can be removed
Remove `ChainClientError::BlobsNotFound`. There was also one place where we were using `ChainClientError` when we should be using `NodeError`.
CI
=> Cleanup ChainClientError::BlobsNotFound

linera-base/src/crypto.rs, linera-base/src/data_types.rs, linera-base/src/graphql.rs, linera-chain/src/lib.rs, linera-client/src/client_options.rs, linera-client/src/config.rs, linera-client/src/persistent/file.rs, linera-core/src/worker.rs, linera-ethereum/src/common.rs, linera-execution/src/lib.rs, linera-execution/src/wasm/mod.rs, linera-rpc/src/grpc/mod.rs, linera-rpc/src/mass_client.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/codec.rs, linera-rpc/src/simple/transport.rs, linera-sdk/src/views/system_api.rs, linera-service/src/node_service.rs, linera-storage-service/src/common.rs, linera-version/src/version_info/type.rs, linera-views/src/backends/dual.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/mod.rs, linera-witty/src/runtime/error.rs
The way we do errors is a little bit disorganized. We need to cleanup.
* The `ArithmeticError` and `ViewError` are handled as `transparent`. The exception is `NodeError` because we want to have `PartialEq`, `Eq`, `Serialize` and other traits.
* For the error statements, if some entries are present, then they are printed if an error occurs.
The CI.
It should help operators of TestNet / DevNet.
None.
=> Cleanup of some errors.

linera-base/src/data_types.rs, linera-base/src/prometheus_util.rs, linera-chain/src/chain.rs, linera-core/src/client/mod.rs, linera-core/src/value_cache.rs, linera-core/src/worker.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/system.rs, linera-execution/src/wasm/mod.rs, linera-rpc/src/grpc/server.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/metrics.rs, linera-views/src/views/bucket_queue_view.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/log_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/queue_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/register_view.rs, linera-views/src/views/set_view.rs
The Prometheus entries is creating a lot of copy-pasted code which is bad taste. 
This PR does two things:
* Change the use statements which lead to smaller code.
* Introduce functions `bucket_latencies` and `bucket_interval` for creating the bucket of values in a more organized way.
The CI
The intervals have changed a bit. So, if the operation code strictly depends on the exact values of the buckets then
something else would have to be done.
None.
=> Simplify the Prometheus stuff

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
https://github.com/linera-io/linera-protocol/pull/2904 introduced block proposal size limits that are only enforced when the proposal was handled in the worker, not when staging block execution. This could result in the pending block getting set to an invalid proposal.
Handle the proposal in the local node before setting the pending block.
The explicit `clear_pending_block` call was removed from the test.
- Fixes https://github.com/linera-io/linera-protocol/issues/2906.
=> Set pending block only after making sure it is valid.

linera-chain/src/manager.rs, linera-core/src/client/chain_client_state.rs, linera-core/src/client/mod.rs, linera-core/src/data_types.rs
As discussed in https://github.com/linera-io/linera-protocol/pull/2925, this code is unnecessarily convoluted, and some of the checks are redundant.
Simplify the code.
The logic hasn't changed. CI should catch any regressions.
=> Inline `propose_block` and simplify `process_pending_block_without_prepare`.

linera-chain/src/data_types.rs
`--features benchmark` is failing due to missing `LiteVote::with_value` method - this method is feature-gated but only for `with_testing` on `main`.
Fix it by compiling `with_value` method for `feature = "benchmark"` as well.
CI.
=> Fix benchmarks compilation

linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
https://github.com/linera-io/linera-protocol/pull/2925 made the `test_end_to_end_listen_for_new_rounds::scylladb_grpc` test fail: If we only set the pending block after locally handling the block proposal then we don't set the block at all if we fail to find a suitable round number to propose in, which is what happens if we are not the leader in the current single-leader round, and the round has not timed out yet.
This change was originally made necessary by the introduction of the proposal size limit, which is applied to the whole `BlockProposal`. To make sure a block can always be re-proposed, it must only be applied to the block itself and its blobs. (https://github.com/linera-io/linera-protocol/issues/2924)
Don't handle the block proposal locally when setting the pending block. …
=> Don't handle proposal before setting the pending block.

.github/workflows/benchmarks.yml, .github/workflows/docker.yml, .github/workflows/docker_image.yml, .github/workflows/documentation.yml, .github/workflows/dynamodb.yml, .github/workflows/explorer.yml, .github/workflows/long_faucet_chain_test.yml, .github/workflows/rust.yml
Inspired by https://github.com/linera-io/linera-protocol/pull/2898, there's still some optimizations we can make to CI.
Based on the data here https://github.com/linera-io/linera-protocol/actions/metrics/performance?tab=jobs, adjust the runner size for some jobs and adjust the timeouts for others (so we can fail earlier in case of an issue).
There was also some jobs without a timeout, which is pretty dangerous because Github's default timeout is 6 hours 😅
So added timeouts for those based on the data.
CI
=> Optimize CI costs

linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs
`round_for_new_proposal` can just take the block reference now, instead of an option, as we don't have a `None` case for that in the codebase anymore.
Also, we can invert the order of the size limit checks for blobs and block proposal: it's more likely for the block proposal size to fail than the blobs, if the blobs fail the block proposal is likely to fail too.
That way we save potentially decompressing and checking the size of several blobs before actually failing on the block proposal size limit.
Do the changes
CI
=> Small cleanup

linera-chain/src/chain.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/chain_client_state.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/worker.rs, linera-service-graphql-client/gql/service_schema.graphql
The received certificate trackers are not persisted, so we download the complete `received_log` from each validator every time the `linera` binary starts.
Even if the log is up to date, we always call `synchronize_chain_state(admin_id)`, even if the chain being synchronized anyway is already the admin chain. We also make an actual gRPC request to download certificates, even if the number of certificate hashes is zero.
Persist the trackers as part of the chain state. (Used in the client only.)
Don't make a request if `download_certificates` is called with zero hashes.
Synchronize the admin chain first, and only if it is different from the current client's chain. Then call `prepare_chain` (so that even if it _is_ the admin chain it is now up to date), and finally call …
=> Persist the received certificate trackers; avoid redundant requests.

linera-chain/src/block.rs
Some implementations of `TryFrom` return a `&static str` as an error. However, `&static str` does not implement `std::error::Error`. This prevents `.try_into()?` from being used in tests that return `anyhow::Result<()>`.
Create a `ConversionError` error type, and use it instead of `&static str` in the relevant `TryFrom` implementations.
CI should catch any regressions, because this only affects types.
- Nothing to do, because this is just an internal refactor.
=> Remove `&static str` usage as error type

Cargo.lock, linera-chain/Cargo.toml, linera-chain/src/unit_tests/chain_tests.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/Cargo.toml, linera-execution/src/execution.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/mock_application.rs, linera-execution/src/test_utils/mod.rs, linera-execution/src/test_utils/system_execution_state.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/wasm.rs, linera-service/Cargo.toml, linera-storage/src/lib.rs
While writing some tests, I had a need to create a `MockApplication` with a specific `ApplicationId`. The current `register_mock_applications` test helper function did not support that, and that function was already scheduled to be replaced with a better alternative (issue #2851) that is more ergonomic.
Create a `RegisterMockApplication` trait that allows some tests to create and register `MockApplication`s. Refactor the tests to use them instead of `register_mock_applications`, and remove the old API.
CI should catch any regressions to the refactors made to the tests.
- Nothing to do, because this only affects tests.
- Closes #2851
=> Add `RegisterMockApplication` test helper extension

.github/workflows/performance_summary.yml, linera-summary/src/github.rs
There also exists a feature that allows us to add a job summary to a github job, as markdown: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#adding-a-job-summary
Add job summary to the Performance Summary CI job, so that we can have access to historical results of runs.
Tested it in the same way as the base PR. You can see it properly set the job summary in this job https://github.com/linera-io/linera-protocol/actions/runs/11983964611 for example
=> [summary] Set Job Summary to be the markdown results

linera-summary/src/github.rs, linera-summary/src/main.rs, linera-summary/src/performance_summary.rs
Right now the performance summary always "spams" the PR with comments, one for everytime the `Rust` workflow finishes successfully in CI.
Now that we have the summary attached to the performance summary CI job, we have a way of accessing the historical values for these things. So now we can just edit an existing comment instead of always creating a new one.
Will be tested with workflow dispatch, like in previous PRs. You can see that there's only one comment, and it's edited (instead of just commenting again)
=> [summary] Update existing comment

CLI.md, linera-client/src/client_options.rs, linera-client/src/wallet.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/src/node_service.rs, linera-service/src/wallet.rs
The end-to-end tests close their chains at the end. Sometimes that results in error messages because:
* the chain is not actually owned by that client, or
* the chain was already closed by another client.
Add an option to list only the _owned_ chains, and use that in the tests.
Return `None` from `ChainClient` if the chain was already closed, instead of an error.
A test was extended to verify that `None` is returned if the chain is already closed.
Listing only the owned chains is now used in the end-to-end tests.
- Fixes https://github.com/linera-io/linera-protocol/issues/2954.
=> Fix `close_chain` errors.

linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/batch.rs, linera-views/src/common.rs, linera-views/src/test_utils/mod.rs, linera-views/tests/store_tests.rs
The `ScyllaDb` is our main storage system. So, we need to remove limitations from it.
* A generic test for writing very big entries and doing a corresponding `multi_read_values` was introduced.
* The test was proven to be correct for ScyllaDb, but still matched as ignored as it takes too long to run.
* Tests show that a `read_multi_values` of 1.6G passes correctly even if slow. This is the maximum possible size (about 99 * 16M). So, no limitation problem here.
* The `ValueSplitting` is used for the ScyllaDb in order to have values larger than 16M.
* The constants are changed to more realistic values.
* Clean up the ensure statements for key sizes.
The CI + additional offline tests.
This changes the storage, 
- [reviewer …
=> Scylla improvement

linera-chain/src/certificate/confirmed.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/test_utils.rs, linera-explorer/rust-toolchain.toml, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/simple/client.rs, linera-rpc/tests/format.rs, linera-service/src/proxy/grpc.rs, linera-service/src/schema_export.rs
On the road to removal of `Certificate` and replacing it with more type-safe|specific API.
Here we do two things mainly:
- remove `download_certificate_value` (it was unused)
- change `download_certificate` from returning (old) `Certificate` type to `ConfirmedBlockCertificate`
SDK soon.
- [reviewer …
=> Simplify ValidatorNode API.

linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/worker.rs
A validator that has signed a block proposal must be able to provide everything so that a client is able to execute that proposal, too. So we need to store all published blobs in the chain manager.
Since we store the whole `BlockProposal` there, it is easiest to require that it always contains exactly the published blobs, and in the right order.
The added check is very short and the block proposals we produce in the client already pass it. Existing tests should catch any regressions.
- Closes https://github.com/linera-io/linera-protocol/issues/2963.
=> Require that BlockProposal contains exactly the published blobs.

linera-client/src/client_context.rs, linera-client/src/wallet.rs
`owned_chain_ids` and `own_chain_ids` do the same thing
Keep `owned_chain_ids`, as that name seems better
CI
=> Remove some code duplication

linera-core/src/client/mod.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/test_utils.rs, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/simple/client.rs, linera-service/src/schema_export.rs
On the mission to removal of `Certificate` type.
We already fixed `download_certificate` (singular) to return `ConfirmedBlockCertificate` in the previous PR, this one went unnoticed.
CI.
Closes https://github.com/linera-io/linera-protocol/issues/2974
=> ValidatorNode::download_certificates returns ConfirmedBlockCertificates

linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
It is redundant in some situations to call `prepare_chain` inside `execute_operations`: Whenever we are in connected mode, i.e. the client listener is running, we should not need to call `prepare_chain` or `synchronize_from_validators`, and instead rely on the notifications.
Remove the `prepare_chain` call, and instead call it explicitly if we are executing a CLI command, i.e. are not in connected mode.
Since this call is redundant, the logic should not have changed. Only in some client tests I had to add explicit `prepare_chain` calls, which is expected.
=> Remove redundant prepare_chain calls.

linera-chain/src/certificate/mod.rs, linera-chain/src/data_types.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/worker.rs, linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/system_execution_state.rs
Reading a blob that has already been used (published or read) on the same chain before is guaranteed to succeed, so it does not need an oracle response entry in the execution outcome.
Add a `used_blobs` field to the system execution state to keep track of all blobs that have been used on this chain so far. Only make oracle entries for blobs that have not been used before.
Tests have been updated to assert the new behavior.
- Closes https://github.com/linera-io/linera-protocol/issues/2964.
=> Blob use is only an oracle the first time per chain.

linera-base/src/data_types.rs, linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
Fast blocks must be deterministic, so no oracle calls are allowed. This goes for reading blobs (for the first time on this chain), too.
Remove the exception for reading blobs.
Automatically propose a regular block if we are super owner but the block uses oracles.
The `test_propose_block_with_messages_and_blobs` test has been extended to assert the new behavior.
- Closes https://github.com/linera-io/linera-protocol/issues/2654
- Closes https://github.com/linera-io/linera-protocol/issues/2965
=> No oracles in fast blocks; automatically propose a regular block if oracles.

.github/workflows/scylladb.yml, docker/docker-compose.yml
We want ScyllaDB pinned in GitHub workflows and for validators to avoid unwanted changes.
Pin ScyllaDB to the latest provably working version (6.2).
=> Pin scylla db docker container

linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
The end-to-end tests should end with the termination of the `net`. This was missing for one test of `linera_net_tests`.
The following was done to the tests in `linera_net_tests` and `local_net_tests`:
* If the test spawn a `node_service` then before the end of the test we have a `node_service.ensure_is_running()?`.
* If a `net` is spawned then at the end of the test we have a `net.ensure_is_running().await` and a `net.terminate`.
The CI. The corrections should make the behavior of the tests more predictable.
No impact.
=> Correct the termination of the end-to-end tests.

linera-chain/src/block.rs, linera-chain/src/certificate/mod.rs, linera-chain/src/manager.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/test_utils.rs
* `ConfirmedBlock::from_validated` is unused.
* `CertificateValueT::is_validated` doesn't actually use `&self`. Also, I will soon need it in non-test code.
* `ChainManager::create_vote` returns either a validated or confirmed block vote. There is currently a panic in the unreachable case that it returns both.
* Remove the unused function, as well as some unused `clone` calls and a redundant type annotation.
* Replace `is_validated` with a `const IS_VALIDATED`.
* Use `Either` and remove the panic.
=> Simplify some code related to certificates and the chain manager.

.github/workflows/rust.yml, linera-service/Cargo.toml, linera-service/src/cli_wrappers/existing_net.rs, linera-service/src/cli_wrappers/mod.rs, linera-service/tests/linera_net_tests.rs
I think I originally implemented this, it was originally running tests against the devnet on GCP. I don't remember what the name was then.
Regardless, now this has changed, and it actually just connects to any existing/running network that has a faucet.
I thought `RunningNet` sounded weird, `ExistingNet` sounded better. A `WithFaucet` suffix or something like that also sounded wrong. So I landed on `ExistingNet`.
Rename all remote net things into existing net. The feature for this also had kubernetes related stuff as a dependency, even though it uses nothing kubernetes related.
So removed that.
CI
=> RemoteNet -> ExistingNet

linera-client/src/client_options.rs, linera-service/src/cli_wrappers/docker.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs
When testing kubernetes related config changes locally with `linera net up --kubernetes`, there's no way to just use an existing docker image (if you're not testing something on the linera binaries, there's no need to rebuild the docker image every time)
Add options to skip building the image and just use an existing one. The name of the image to use also became a configurable option
Ran `linera net up --kubernetes` locally with these new arguments
=> Avoid build on linera net up --kubernetes

linera-service/src/project.rs, linera-service/template/Cargo.toml.template, linera-service/template/service.rs.template, linera-service/tests/local_net_tests.rs
The unit test code generated by `linera project new` was broken because the state type was missing the newly added `State` suffix (#2987).
Fix the generated unit test code, and update the `Cargo.toml` file to use the more up-to-date version that doesn't require a separate section of dependencies based on the target architecture.
The `test_project_new` test was updated to also run `cargo test` on the generated code, to prevent these bugs from happening again.
- Nothing to do, because this just fixes a bug that isn't present in any released version.
=> Fix test code generated by `linera project new`

linera-core/src/unit_tests/client_tests.rs
In some client tests we use `execute_operation` and put together a `SystemOperation::ChangeOwnership` manually, when there is the `change_ownership` method that does exactly that.
Use `change_ownership` instead.
This code should be equivalent, just with less repetition.
=> Use `change_ownership` in some tests, instead of `execute_operation`.

linera-chain/src/block.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/grpc/server.rs, linera-rpc/src/lib.rs, linera-rpc/src/message.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/server.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/chain.rs, linera-service/src/linera/main.rs, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs
Before this PR there are generic API endpoints (messages) that operate on a `Certificate` type, without differentiating between certificate types explicitly in the API.
This PR follows through and makes the differentiations at the API level in the following ways:
1. In `rpc.proto`:
- replace `HandleCertificateRequest` message with `HandleConfirmedCertificateRequest`, `HandleValidatedCertificateRequest` and `HandleTimeoutCertificateRequest`.
- replace `HandleCertificate` endpoint in `service ValidatorWorker` and `service ValidatorNode`  with `HandleConfirmedCertificate`, `HandleValidatedCertificate` and `HandleTimeoutCertificate`.
2. In `remote_node.rs` (and similar), replace `handle_certificate<T>` with per-certificate type methods.
Everything else follows from these two changes to …
=> Split APIs into per-certificate type endpoints

linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
It must always be possible to re-propose the locked block, even if the committee that certified a blob which the new block reads has been deprecated in the meantime. This would currently fail, in theory, because the validator tries to execute the proposal even if it includes a validated block certificate, and during execution it doesn't have access to the included blobs.
Include the whole execution outcome in the proposal and don't re-execute it.
The bug itself can't actually be triggered due to https://github.com/linera-io/linera-protocol/issues/2351: The validator would wrongly accept the deprecated blob.
- Fixes https://github.com/linera-io/linera-protocol/issues/2993.
- [reviewer …
=> Include the outcome in a re-proposal instead of re-executing.

Cargo.toml
The compilation with `lto="fat"` and `debug = true` causes out-of-memory problems.
The switch to thin alleviates the memory problem.
Running locally, we now have less problems with OOM. More work is needed to have 
That is relevant to the TestNet / DevNet.
None.
=> Switch to thin for lto.

linera-execution/src/execution_state_actor.rs, linera-execution/src/test_utils/mod.rs, linera-execution/tests/contract_runtime_apis.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/set_view.rs
In several applications, we only need the number of entries and the set of pairs `(I, V)`.
Fixes https://github.com/linera-io/linera-protocol/issues/2952
* The `fn count` was added to all the containers.
* The `index_values` functions are added to the `MapView` and `CustomMapView`.
* The code is correspondingly simplified.
* The trait requirements are simplified.
The added functions have their own tests. The change in other parts of the code should be handled by the existing code.
This change is a relatively minor one and does not change the TestNet / DevNet.
None.
=> Implement the `index_values` and `count` functions.

linera-core/src/client/mod.rs
In `receive_certificates_for_blobs` we simultaneously ask all validators for a certificate that (re-)certifies a blob. We then take the first response we get and call `receive_certificate`. That will fail because we don't have the blob yet, which we in turn request from all validators _sequentially_! Due to https://github.com/linera-io/linera-protocol/issues/3033, if the first validator we ask doesn't have it, we keep retrying a few times before we move on to the next one, which can take a long time.
Download the blob in question from the validator that sent us the certificate and is therefore expected to have it.
For me this reduced the `process-inbox` in https://github.com/linera-io/linera-protocol/issues/3029 from 53 to 7 seconds.
- These changes should be backported to the latest …
=> Download blobs from the node that gave us the certificate.

linera-core/src/client/mod.rs
The issue addressed by https://github.com/linera-io/linera-protocol/pull/3034 is also present on `main`.
Port it to `main`.
Tested manually (see #3034).
This is the port to `main`; it's already on `testnet_archimedes`.
- Port of #3034.
- Addresses the main concern (slowness) in #3029.
=> Download blobs from the node that gave us the certificate. (#3034)

.github/workflows/explorer.yml, linera-explorer/rust-toolchain.toml
Broken symlink in `linera-explorer/rust-toolchain.toml`.
Point it to the correct file.
=> Fixed broken symlink in linera-explorer/rust-toolchain.toml.

linera-rpc/src/grpc/client.rs, linera-service/Cargo.toml, linera-service/src/proxy/grpc.rs
The proxy returns a gRPC status with code `Unknown` for any `ViewError`, which causes the client to retry the request. For most errors, this doesn't make sense.
Map the errors to appropriate status codes. Don't retry on "not found" or "already exists" errors.
This brings down the 53 seconds from the scenario in https://github.com/linera-io/linera-protocol/issues/3029 to less than 9 seconds.
- These changes should
- These changes should be ported to the `main` branch.
- They might be superseded by https://github.com/linera-io/linera-protocol/issues/3033, but that will take much longer to implement and possibly needs some discussion.
- Related to https://github.com/linera-io/linera-protocol/issues/3029.
- [reviewer …
=> Map view error to appropriate status; don't retry if `NotFound`/`AlreadyExists`.

examples/gen-nft/README.md, examples/gen-nft/src/lib.rs, linera-views/src/backends/dual.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/journaling.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/common.rs, linera-views/src/context.rs, linera-views/src/views/bucket_queue_view.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/log_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/queue_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/register_view.rs, linera-views/src/views/set_view.rs, linera-views/tests/views_tests.rs
Two independent corrections. One for the `gen-nft/README.md` and another for the elimination of `Debug` trait requirements.
It was mentioned in previous PR that maybe we have too much requirements of `Debug` trait.
The unnecessary `Debug` have been removed.
We need to have `Debug` for the following types:
* The views need to have `Debug` since the corresponding code in the protocol code is `Debug`.
* The error types need to be `Debug`.
* The async_graphql need to be `Debug`as well.
The CI.
Not of importance to the TestNet / DevNet.
None.
=> Two corrections

linera-storage/src/db_storage.rs, linera-views-derive/src/lib.rs, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_C.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_C_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_CustomContext.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_CustomContext_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__GenericContext_T_.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__GenericContext_T__with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__path__to__ContextType.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__path__to__ContextType_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_C.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_C_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_CustomContext.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_CustomContext_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__GenericContext_T_.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__GenericContext_T__with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__path__to__ContextType.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__path__to__ContextType_with_where.snap, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/context.rs
The `write_batch`, `contains_keys`, and `read_multi_values_bytes` functions can return trivially in some cases.
This leads to some potential optimization.
It has emerged from https://github.com/linera-io/linera-protocol/pull/3010 that the preferred way to handle this is to handle it as early as possible.
Therefore the following was done:
* Add the tests in the `db_storage.rs` as we use the storage directly.
* Add the tests in the `LruCachingStore` since a non-trivial call can become a trivial call if the cache catches it.
* Remove the ScyllaDb tests as they should have been caught before.
* Add the tests in the `context.rs` since this is the go-to point for the views calls.
* Change the code for the `linera-views-derive`. This is needed since many of the `NUM_INIT_KEYS` are 0 …
=> Add tests of triviality

linera-views/src/views/map_view.rs
The performance of the `MapView` has recently emerged as a subject of concern. While the use of async Iterators is under discussion, it is clear that there are other issues.
* The enum type `ValueOrBytes` was introduced to represent the fact that in some cases we have the values and in some other cases its serialization.
* The function `for_each_key_value_while` no longer serializes the values; it just creates a `ValueOrBytes::Value`.
* The use of `iterator()` is replaced by a `into_iterator_owned()` since this avoids a `.to_vec()` in the construction of the `ValueOrBytes::Bytes`. Note that we cannot have a `Bytes(&`a [u8])` since indeed the scope of `f` is larger than the one in which the key values are created.
* Some `Clone` traits have to be added. But this …
=> Remove some serializations in `MapView`.

linera-core/src/worker.rs
We want to track validators that are potentially lagging behind (not signing as many blocks).
Add a Prometheus counter that counts for each validator, how many of the confirmed certificates we have processed they signed.
If we really want to keep an eye on this, we could even add an alert later on if the validator with the most signatures minus the validator with the least signatures is greater than some threshold.
Did a local run and checked the metrics:
=> Track certificates signed by each validator

linera-service/src/linera/main.rs
We would like a daily network uptime check.
Merge changes to query-validators.
Tested manually. CI will catch regressions.
- Nothing to do - this is client-side.
=> port linera query-validators has usable output on stdout to testnet-archimedes.

linera-base/src/crypto.rs, linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-chain/src/block.rs, linera-chain/src/certificate/hashed.rs, linera-chain/src/data_types.rs, linera-client/src/client_context.rs, linera-client/src/config.rs, linera-core/src/data_types.rs, linera-core/src/unit_tests/client_tests.rs, linera-execution/src/runtime.rs, linera-rpc/src/grpc/conversions.rs, linera-service/src/node_service.rs, linera-service/tests/linera_net_tests.rs, linera-storage/src/lib.rs, linera-views-derive/src/lib.rs, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-2.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-3.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-4.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-5.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-6.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-7.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-8.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code.snap
It's not necessary to clone the blob content just to hash it.
Change `BcsHashable` to not require `DeserializeOwned`, so that `BlobBytes` can borrow the bytes.
There were also a few other places where they were unnecessarily cloned.
- Supersedes https://github.com/linera-io/linera-protocol/pull/3049.
=> Avoid cloning blob content.

linera-rpc/src/message.rs
Code inspection reveals this error.
The conversion occurs when a response is processed. It has to be of the Response type.
The CI, even though it needs to be improved.
This should be deployed on TestNet / DevNet.
None.
=> Correct an error about the `MissingBlobIds`.

linera-base/src/hashed.rs
The comma after `T::type_name()` doesn't cause an error, but it is redundant, so I removed it to improve readability.
=> fix: improve readability Update hashed.rs

linera-rpc/src/config.rs
The correct form would be "cross-chain messages," where "cross-chain" functions as an adjective describing "messages."
=> typo fix Update config.rs

docker/docker-compose.yml
During testnet we would like validators to be updated automatically.
Add watch-tower to `docker-compose.yml` monitoring only the proxy and shards.
1. Kubernetes is going to require a different approach and is in general going to require more work + refactoring.
2. The validators _must_ use the external image tagged with the network name, for example:
```bash
./deploy-validator.sh my-domain.com --remote-image  us-docker.pkg.dev/linera-io-dev/linera-public-registry/linera:testnet-archimedes
```
If a local image is used, automatic updating won't work since provenance is not shared with remote images.
This is a feature not a bug, if validators want they _can_ build everything from scratch and opt-out from "forced" updates. However I see no reason why they might choose to.
Manual testing. CI …
=> Add watchtower service to automatically upgrade the shard and proxy.

CLI.md, linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/lib.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/updater.rs, linera-service/src/linera/main.rs
- Renamed `GRACE_PERIOD` to `DEFAULT_GRACE_PERIOD` ~~and altered its value~~,
- added grace period argument in communicate with quorum,
- added that value to `ChainClientOptions` and threaded through the `Client` builder,
- Refactored the `end_time` setting logic in the `communicate_with_quorum` function to improve the handling of unreachable quorum on any key,
- ~~also corrects a handful of typos (in comments and error messages) as I was reading in the area~~
Fixes #2836. /cc @afck for review @Twey for context
=> feat: Make the communicate_with_quorum grace period configurable

linera-views/src/backends/dual.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/journaling.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/views/bucket_queue_view.rs
Subsequent to PR https://github.com/linera-io/linera-protocol/pull/3039 several Debug statements were cleaned out while still needed. They are here reintroduced.
The policy for reintroducing the trait is that the configuration types must have the Debug traits.
The CI.
Of limited importance to developers of Linera.
See https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits
=> Reintroduce some Debug traits requirements.

linera-witty-macros/src/lib.rs, linera-witty-macros/src/unit_tests/wit_type.rs, linera-witty-macros/src/wit_type.rs
The `WitType` trait allows generating WIT snippets. The WIT type name used is by default the kebab-case version of the Rust type name. However, it is sometimes necessary or desirable to use a custom name in the WIT snippet.
Add a `#[witty(name = "custom-wit-type-name")]` attribute to allow overriding the default WIT type name.
A unit test was added to test the usage of the new attribute.
- These changes follow the usual release cycle, as it introduces a new backwards compatible Witty feature.
- Closes #2613
=> Allow specifying a custom WIT type name when deriving `WitType`

linera-chain/src/block.rs, linera-chain/src/unit_tests/data_types_tests.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
As described in https://github.com/linera-io/linera-protocol/issues/2980 we've started to see a lot of logs about validator forgetting a block it had already signed. As @afck correctly observed - the problem was that when inserting a `ConfirmedBlock` (and `ValidatedBlock`) into the `ExecutedBlock` cache, they were inserted under a hash of the wrapper type (`ConfirmedBlock`/`ValidatedBlock`) rather than the hash of `ExecutedBlock` they contained. This meant that when looking up the cached value we always failed to find it (since the keys were different) – hence the error log.
Here we serialize `ConfirmedBlock` and `ValidatedBlock` as their inner `ExecutedBlock`s they contain. This means that their hashes are now equivalent (which fixes the original problem with the cache) but could also …
=> Serialize Confirmed and Validated blocks as their inner blocks.

.github/workflows/docker.yml
Some of the stuff on `docker/` is not really used by the docker compose workflow, but we might as well have the whole directory as it's most files (we would have to add most of the files manually otherwise).
Then PRs like https://github.com/linera-io/linera-protocol/pull/3021 can trigger CI and have some sanity tests run before merging.
Trigger docker compose CI on all changes in the `docker` directory
CI
=> Run Docker Compose CI in all docker changes

linera-witty/src/type_traits/implementations/std/box.rs, linera-witty/src/type_traits/implementations/std/mod.rs, linera-witty/src/type_traits/implementations/std/rc.rs, linera-witty/src/type_traits/implementations/std/sync.rs, linera-witty/tests/common/types.rs, linera-witty/tests/wit_load.rs, linera-witty/tests/wit_store.rs, linera-witty/tests/wit_type.rs
It's not uncommon to want to store some values in the heap, but still be able to copy them to and from guest Wasm modules. For that to work, heap smart pointer types should implement the `WitType`, `WitLoad` and `WitStore` traits.
Create a new macro with the code to delegate implement the traits by delegating the items to the wrapped type, and use the macro to implement the traits for `Box`, `Rc`, and `Arc`.
Unit tests were modified to wrap all tested types in `Arc`, `Rc` and `Box` containers and check that it doesn't affect the loading and storing of the types.
Unit tests were added to check derived `WitType`, `WitLoad` and `WitStore` implementations for types that have `Arc`, `Rc` and `Box` fields.
- These changes introduce a backwards compatible feature, so they follow the usual …
=> Implement `WitType`, `WitLoad` and `WitStore` for pointer types

.github/workflows/rust.yml, linera-service/Cargo.toml, linera-service/src/cli_wrappers/mod.rs, linera-service/src/cli_wrappers/remote_net.rs, linera-service/tests/linera_net_tests.rs
* The new name is not particularly better than the previous one that made sense at least in contrast with local-net.
* The testnet branch and various test scripts use the old name.
Revert commit 909b3e725c86a1bdefd8dc01ac11006779388e54 (minus one detail)
CI
=> Revert "RemoteNet -> ExistingNet (#2998)"

linera-witty/src/imported_function_interface/parameters.rs, linera-witty/src/runtime/error.rs, linera-witty/src/runtime/memory.rs, linera-witty/src/test.rs, linera-witty/src/type_traits/implementations/std/string.rs, linera-witty/src/type_traits/implementations/std/vec.rs, linera-witty/src/type_traits/implementations/tests.rs, linera-witty/tests/common/types.rs, linera-witty/tests/wit_load.rs, linera-witty/tests/wit_store.rs, linera-witty/tests/wit_type.rs
When allocating heap memory in Witty, the alignment was incorrectly hard-coded to `1`. This causes issues when the allocated memory does not start at an aligned address. The code to store types will automatically add padding, which offsets the start of the write and can then overflow the allocated region.
Specify the allocation alignment whenever needed.
Unit tests were added, including one that reproduces the issue `wit_store::test_list_fields` and now passes with the fix.
SDK soon.
=> Fix Witty memory allocation alignment

examples/crowd-funding/src/contract.rs, examples/gen-nft/src/service.rs, examples/non-fungible/src/service.rs, linera-views/src/test_utils/test_views.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/set_view.rs
Several additional suggestions were forgotten in the PR https://github.com/linera-io/linera-protocol/pull/3036 
The following corrections were made:
* The `ValueOrBytes` is marked as private.
* The `count` used for `SetView`, `CollectionView`, `ReentrantCollectionView`, `MapView` and `KeyvalueStoreView` are `usize` which makes them architecture dependent. We switch to u32.
* The `FnMut(I, V)` forces a clone which is not always needed. So, it was replaced by `FnMut(I, Cow<'a, V>)`. Actually, the clone still occurs, but if someone were to want to just access the reference, it would be possible.
Unfortunately, the use of the Cow complexifies the call to the `for_each_key_value`. 
The CI.
This is a breaking change with TestNEt / DevNet as it changes the hashes values.
None.
=> Corrections to `MapView` after the introduction of `ValueOrBytes`.

linera-views/src/views/unit_tests/views.rs, linera-witty-macros/src/unit_tests/specialization.rs, linera-witty-macros/src/unit_tests/wit_load.rs, linera-witty-macros/src/unit_tests/wit_store.rs, linera-witty-macros/src/unit_tests/wit_type.rs, linera-witty/src/runtime/unit_tests/memory.rs, linera-witty/tests/wit_load.rs, linera-witty/tests/wit_store.rs, linera-witty/tests/wit_type.rs
Some tests were using "check" instead of "checks", which is different from the convention used everywhere else.
Fix the documentation to use "checks".
Nothing needed, because this only affects documentation.
- Nothing to do, because this only affects documentation.
=> Fix verb tense in test documentation

linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/wasm/system_api.rs, linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs, linera-sdk/wit/contract-system-api.wit
In some applications, we might want to instantiate other application as part of their functionality. For example, the "Requests for Quotes" app will want to instantiate the Matching Engine.
Add a `create_application` method to the contract API, callable from within applications, reflecting the flow of manually instantiating a new application.
This will be tested during test runs of the Requests for Quotes application.
=> Add a `create_application` contract API method

docker/docker-compose.yml
Pin the ScyllaDB minor version to avoid accidentally pulling upstream changes.
Pin the image version in Docker Compose.
=> Pin ScyllaDB minor version.

CLI.md, linera-client/src/client_options.rs, linera-client/src/util.rs, linera-service/src/linera/main.rs, linera-service/src/util.rs, linera-service/tests/readme_test.rs
This was suggested by the community and team members also hacked a local solution at times.
fixes #1456
* Some light refactoring
* Add a command `linera extract-script-from-markdown`. The command is hidden because we may arbitrarily change or remove it in the future.
CI
```
cargo build
target/debug/linera extract-script-from-markdown examples/fungible/README.md | bash
```
=> Create a tool to extract a bash script from a Linera README file

Cargo.lock, Cargo.toml, linera-views/src/backends/scylla_db.rs, linera-views/src/batch.rs
The support of ScyllaDb is critical as it is our main database for operations.
* Switch from `Logged` to `Unlogged` for the batch types. This is fine because our transactions are on a single root_key and a single partition key.
* Make the `expand_colliding_prefix_deletions` a little faster by not constructing the BTreeSet if it does not need to be used.
* Switch from version 0.12.0 to version 0.15.1
* Switch from Query to Prepared statements.
(A) The CI
(B) The runtimes are obtained by the benchmarks:
- `store_scylladb_write_batch`: 28.32 ms on this PR vs 31.607 ms
- `store_scylladb_find_key_values_by_prefix`: 15.025 ms vs 16.426 ms
- `store_scylladb_find_keys_by_prefix`: 1.5997 ms vs 3.1336 ms
- `store_scylladb_contains_keys`: 4.52 ms vs 4.46 ms
- `store_scylladb_contains_key`: 94.82 ms …
=> Improve the support for `ScyllaDb`.

linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/grpc/server.rs, linera-rpc/src/lib.rs, linera-rpc/src/message.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/server.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/chain.rs, linera-sdk/src/test/validator.rs, linera-service/src/linera/main.rs, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
Including blobs with the gRPC message that contains a block proposal or certificate severely limits the total size of the blobs. (See #3048.)
As a first step, remove the blobs from the `handle_confirmed_certificate` functions and messages.
Instead, when a validator sees a fully signed confirmed block it creates the blob states in its local storage even if it doesn't have the blobs yet. The client can then upload the blobs one by one, and the validator will accept them. Finally, the client can retry sending the certificate.
We don't do this for block proposals or validated blocks yet: These will need to be handled differently, because in these cases the blob has not necessarily been successfully published yet, so we should _not_ create a blob state. Instead, we will put these blobs into a …
=> Upload blobs for confirmed certificates separately.

linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/test_utils.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/message.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/server.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs
When I addressed https://github.com/linera-io/linera-protocol/pull/3108#discussion_r1909026114, I only renamed `UploadBlobContent` to `UploadBlob`. `DownloadBlobContent` has a name inconsistent with that now.
Rename `DownloadBlobContent` to `DownloadBlob`.
(Only renaming.)
- Original discussion: https://github.com/linera-io/linera-protocol/pull/3108#discussion_r1909026114
=> Rename DownloadBlobContent → DownloadBlob

linera-base/src/data_types.rs, linera-chain/src/manager.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/mod.rs, linera-core/src/node.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/worker.rs, linera-execution/src/lib.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/grpc/server.rs, linera-rpc/src/message.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/server.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs
Ultimately we want to transfer all blobs separately, rather than in a single message. (https://github.com/linera-io/linera-protocol/issues/3048)
This PR is one step towards that goal: When the client fetches the locked block from a validator, it now requests the corresponding blobs one by one, rather than all at once.
Add a `DownloadPendingBlob` endpoint; remove the locked blobs from the `ChainManagerInfo`.
Existing tests exercise this scenario, e.g. `test_finalize_locked_block_with_blobs`. 
- Part of #3048.
=> Fetch locked blobs individually, not in `ChainManagerInfo`.

CLI.md, linera-client/src/client_options.rs, linera-service/src/cli_wrappers/mod.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs, linera-service/tests/local_net_tests.rs
First step in addressing #2890
* Make a function of `find_owned_chains` out of the code in `ClientWrapper::drop()`
* Add an option `--with-faucet-chain N` to `linera net up` as well as `--faucet-port` and `--faucet-amount`
* Add a simple test
The only caveat is that `N` cannot be a chain-id (since we wouldn't know what to write) so we use the index amongst root chains (typically 1 for the first non-admin initial chain).
CI
=> Allow running a faucet from linera net up

linera-witty/src/type_traits/implementations/std/mod.rs, linera-witty/src/type_traits/implementations/std/primitives.rs, linera-witty/src/type_traits/implementations/std/slices.rs, linera-witty/src/type_traits/implementations/std/vec.rs, linera-witty/src/type_traits/mod.rs, linera-witty/tests/common/types.rs, linera-witty/tests/wit_load.rs, linera-witty/tests/wit_store.rs, linera-witty/tests/wit_type.rs
The WIT specification supports a `list` type, which Witty mapped only to `Vec` types. However, it's also possible to use arbitrary slices with that type. Heap slices (`Box<[T]>`, `Rc<[T]>`, `Arc<[T]>`) can be used to load and store from host to guest, while more generic slices (`&[T]`) can only be stored on the guest.
Implement `WitType`, `WitLoad` and `WitStore` for all slice types. More specifically, implement `WitType` and `WitStore` for generic slices (`&[T]`) and `WitLoad` for boxed slices (`Box<[T]>`). Then delegate implementations of all other types to them (including `Vec`, in order to avoid having duplicate code that's easy to get wrong).
Unit tests were added to cover the new types.
- [reviewer …
=> Implement Witty traits for slices

linera-views/src/views/register_view.rs, linera-views/src/views/unit_tests/views.rs
@afck ran into an issue where an assertion caught unexpected pending changes after voting for a block proposal. After investigating the issue, the cause seems to be that `RegisterView::flush` had an edge case where it wouldn't clear it's `update` field.
Clear the `update` field after successfully flushing.
A unit test was added to reproduce the issue.
=> Fix pending change after flushing `RegisterView`

linera-chain/src/chain.rs, linera-chain/src/manager.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/data_types.rs, linera-core/src/local_node.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs, linera-storage/src/lib.rs
Currently the chain manager is serialized as a whole and stored in a `RegisterView` in the chain state view. Since it contains blobs it can be very large, and the blobs are not needed every time the chain manager is loaded.
Make the chain manager a `View`, and put the blobs in a `MapView`.
This doesn't change any logic, so CI should catch regressions. (In fact, it already did: https://github.com/linera-io/linera-protocol/pull/3133)
- In preparation for: https://github.com/linera-io/linera-protocol/issues/3048
=> Make the chain manager a `View`.

linera-chain/src/manager.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-rpc/tests/format.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
In the fast round, the validators sign to confirm right away, so the block proposal must count as locked.
However, if the same block is re-proposed in a later round, the `proposed` field is overwritten and, due to the different round, is now not considered locked anymore.
Keep track of the fast round proposal as part of the `locked` field, too.
The problem was reproduced by extending `test_fast_proposal_is_locked`.
- Fixes https://github.com/linera-io/linera-protocol/issues/3134.
=> Remember a fast block proposal: it remains locked even if re-proposed.

linera-client/src/unit_tests/wallet.rs, linera-core/src/node.rs, linera-rpc/src/message.rs, linera-service/benches/transfers.rs
fix some typos in comment
SDK soon.
=> chore: fix some typos in comment

linera-chain/src/chain.rs, linera-client/src/client_context.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/grpc/server.rs, linera-rpc/src/lib.rs, linera-rpc/src/message.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/server.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/chain.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs
Ultimately we want to transfer all blobs separately, rather than in a single message. (https://github.com/linera-io/linera-protocol/issues/3048)
This PR is another step towards that goal: The blobs required by a validated block certificate are now uploaded separately, rather than in the same message as the certificate itself.
Add a map of missing blobs for the highest-round validated block to the chain state, and a `HandlePendingBlob` endpoint to populate that map.
There are already tests covering different scenarios with validated blocks' blobs. Where necessary, these were updated.
- Closes #3152.
=> Upload blobs for validated block certificates in separate messages.

linera-chain/src/block.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-chain/src/manager.rs, linera-chain/src/test.rs, linera-client/src/client_context.rs, linera-client/src/wallet.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/chain_client_state.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/message.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/block.rs, linera-service/src/linera/main.rs, linera-service/src/proxy/grpc.rs
The discussion https://github.com/linera-io/linera-protocol/pull/3101#discussion_r1913251835 was never resolved; a proposal has a content, which has a proposal.
Rename `Proposal` to `ProposedBlock`, to distinguish it from the outer type.
(I also added some destructuring in `Block::new`, because I ran into a naming conflict and this way the compiler will warn us if we add any fields and forget them there.)
Only renaming.
- Related to #3101
=> Rename `Proposal` back to `ProposedBlock`.

CLI.md, linera-base/src/ownership.rs, linera-base/src/unit_tests.rs, linera-chain/src/manager.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/client_options.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/system.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/contract/conversions_from_wit.rs, linera-sdk/src/contract/conversions_to_wit.rs, linera-sdk/src/test/block.rs, linera-sdk/wit/contract-system-api.wit, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/node_service.rs
For https://github.com/linera-io/linera-protocol/issues/3162, some chains need to be "permissionless", i.e. admit any signer as a block proposer, as far as the chain manager is concerned.
Add an `open_multi_leader_rounds` option. If it is `true`, the multi-leader rounds are not restricted to the chain owners anymore. (All other round types still are restricted as usual.)
A test was added.
- Closes #3163.
=> Add an option for open (permissionless) multi-leader rounds.

linera-core/src/node.rs
I noticed a typo in the word "ceritifcates" and corrected it to "certificates".
=> fix: fix typo Update node.rs

linera-core/src/chain_worker/delivery_notifier.rs
I noticed a grammar error in the phrase:  
> "it should only changed by"  
This has been corrected to:  
> "it should only be changed by"  
Thanks!
=> fix: Fix grammar mistake Update delivery_notifier.rs

linera-views/src/test_utils/test_views.rs, linera-views/src/views/unit_tests/views.rs
Recently, a long-standing bug was found in the `RegisterView`. 
Some implementing of `TestView` were done for `SetView` / `QueueView`.
The test that detects the found problem for the `RegisterView` was extended to all the view supporting `TestView`.
Simply improve the tests.
None
=> Improve the tests to the Views.

README.md
"logics", and "infos" should be "logic", and "info", as they are uncountable nouns in this context.
SDK soon.
=> fix: correct typo by changing "logics" to "logic" on README.md

examples/crowd-funding/README.md, examples/gen-nft/src/contract.rs, examples/non-fungible/src/contract.rs, linera-views/DESIGN.md
1. **File:** `examples/gen-nft/src/contract.rs`
- **Old Code:** `.expect("NFT {token_id} not found")`
- **New Code:** `.expect("NFT not found")`
2. **File:** `examples/non-fungible/src/contract.rs`
- **Old Code:** `.expect("NFT {token_id} not found")`
- **New Code:** `.expect("NFT not found")`
Improved clarity and consistency of error messages. The previous message included a placeholder `{token_id}` that was not replaced, leading to confusion. The new message "NFT not found" is clear and concise, aiding in debugging.
=> Fix Placeholder in NFT Error Messages

linera-chain/src/block.rs, linera-chain/src/lib.rs, linera-chain/src/manager.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-rpc/tests/format.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql
We are using the chain manager's `locked` field for two purposes:
* In validators, this is meant to track _this validator's_ locked block, i.e. the latest proposal it signed to confirm.
* In the client, it tracks the highest validated block (or fast proposal) we have seen, i.e. the highest block that _might_ be locked for any honest validator, so that the client knows which block it should re-propose in the next round.
This is confusing, and makes it more difficult to tackle issues like https://github.com/linera-io/linera-protocol/issues/2971.
Use the `locked` field for the first purpose, both in clients and validators: to track the highest block that _might_ be locked for any of the validators.
In a validator's chain manager, the block that is locked for _that validator_ is the one it …
=> Simplify chain manager logic.

Cargo.lock, examples/Cargo.lock, linera-storage-service/Cargo.toml, linera-storage-service/src/client.rs, linera-storage-service/src/server.rs
The `read_entries` code of the storage-service is doing a blocking loop. That is inefficient from the viewpoint of concurrency.
* A vector of handles is created.
* The handles are processed and then merged.
* On the server side, the code is changed so that it is no longer assumed that the request arrive in order.
The CI proved adequate. The `test_storage_service_big_raw_write` did catch the problem with the ordering of the requests.
Not relevant as we do not use so far the `storage-service` in TestNet / DevNet.
None.
=> Update the storage service reading.

kubernetes/linera-validator/helmfile.yaml, kubernetes/linera-validator/templates/grafana-cloud-auth-secret.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl
We're migrating our internal validators to send data to Grafana Cloud.
Starting with the local setup. This was useful to test the required changes that we'll likely need for the actual internal validator setup. We probably won't want to send metrics to Grafana Cloud from local runs all the time (specially for cost reasons), so this is disabled by default.
Grafana Cloud credentials are stored in a secret within GCP's Secret Manager. Since Grafana Cloud will be for our internal validators, then I figured storing the secret on GCP made sense.
Ran locally with `linera net up --kubernetes`, and saw the metrics in our Grafana Cloud instance:
If we want to start sending metrics to Grafana Cloud from our devnet/testnet, then:
- …
=> Send Prometheus metrics to Grafana Cloud

examples/fungible/src/service.rs, examples/gen-nft/src/service.rs, examples/hex-game/src/service.rs, examples/native-fungible/src/service.rs, examples/non-fungible/src/service.rs, linera-sdk/src/service/runtime.rs, linera-sdk/src/service/test_runtime.rs
Using the `ServiceRuntime` in services that use GraphQL requires wrapping the `ServiceRuntime` inside an `Arc<Mutex<_>>`, because the `async_graphql` crate requires the handler to be `Send`. This is bit burdensome for application developers, and is redundant because the `Service` is single-threaded and uses `Cell` for interior mutability.
Replace usages of `Cell` with `Mutex` inside the `ServiceRuntime`, and also do the same for `MockServiceRuntime`.
Update the examples to remove the redundant `Mutex`es.
This is an internal refactor, and application end-to-end tests should catch any regressions.
- Nothing to do / These changes follow the usual release cycle, because it only affects the SDK.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#review …
=> Use `Mutex` inside `ServiceRuntime` to make it `Send`

linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/unit_tests/value_cache_tests.rs, linera-core/src/value_cache.rs, linera-core/src/worker.rs
`ValueCache` is just an in-memory cache; it should not need an async mutex.
Use the standard library's `Mutex` instead. All `await`s have been removed from `value_cache.rs` and none of its methods return any locks, so no lock is held across an `await`.
=> Use an std mutex in `ValueCache`

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/grpc/server.rs, linera-rpc/src/simple/server.rs, linera-witty-macros/src/unit_tests/wit_load.rs
Some gRPC debug log messages are very large. This is because we are logging the protocol types from the `api` module in some cases.
Log the requests before converting them to the `api` types. Conversion happens automatically inside `delegate` anyway, and for our own types we try to keep `Debug` impls concise.
Also, log the handler name in addition to the request data.
(I also fixed some lines that exceeded the maximum length.)
Running locally, I now get e.g.:
```
sending gRPC request handler="download_blob" request=BlobId { blob_type: Data, hash: 465ed2f46f7ca6bc }
```
instead of:
```
sending gRPC request request=BlobId { bytes: [232, 108, 237, 16, 232, 93, 5, 167, 144, 2, 73, 160, 123, 228, 178, 55, 103, 1, 0, 221, 203, 106, 106, 155, 170, 44, 130, 138, 194, 98, 14, 2, 0, 0, 0, 0] }
``` …
=> Don't log api objects for gRPC requests.

CLI.md, linera-chain/src/certificate/lite.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-chain/src/lib.rs, linera-chain/src/manager.rs, linera-chain/src/pending_blobs.rs, linera-chain/src/test.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-execution/src/policy.rs, linera-execution/tests/fee_consumption.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs
Including blobs with the gRPC message that contains a block proposal or certificate severely limits the total size of the blobs. (See https://github.com/linera-io/linera-protocol/issues/3048.)
Remove the `blobs` field from block proposals, and handle blobs separately, with one message each.
I added a `maximum_published_blobs` limit per block, and limited the number of pending proposals with blobs to 1 for permissionless chains. (See https://github.com/linera-io/linera-protocol/issues/3203.)
The tests have been updated where necessary. Otherwise they already cover different scenarios involving proposals with blobs.
- Closes #3202
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#revie …
=> Upload proposals' blobs separately.

linera-indexer/graphql-client/README.md, linera-sdk/wit/README.md
HI! This PR fixes incorrect relative links in `README.md` files to ensure proper navigation and avoid broken references.
- Updated the relative path to `CONTRIBUTING.md` and `LICENSE` in `linera-indexer/graphql-client/README.md`
- Removed redundant description in `linera-sdk/wit/README.md` to maintain clarity and accuracy
#1974
=> fix: broken links in README files

linera-execution/src/applications.rs, linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-execution/src/unit_tests/applications_tests.rs
The work on the integration of the EVM into the `linera-execution` led to code reading and so to identification of some ways to improve the code.
* The functions `user` and `user_without_abi` are only used for testing purposes and so marked as such.
* The functions `find_dependencies` and `describe_applications_with_dependencies` are always used with an empty last argument in the code. The code is thus simplified.
* Many `clone()` operations in `system.rs` are not needed even though clippy did not detect this.
* The use of `Sender` / `oneshot::Sender` is inconcistent in the code.
The CI should detect it.
Follow the normal release plan.
None.
=> Several corrections to `linera-execution` code.

CLI.md, linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/test_utils.rs, linera-service/src/linera/main.rs
When trying to download a blob sequentially from each validator, a single unresponsive validator can considerably slow down the client. (Even worse if they maliciously respond, after a delay, with a gRPC error code that makes the client retry the request.)
After 1s (configurable) try a second, after 4s try a third validator in parallel, after 9s etc.
=> Limit waiting for a single node when downloading blobs.

linera-client/src/client_context.rs, linera-core/src/client/chain_state.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-service/src/node_service.rs
When a conflicting block is committed, the pending blobs are cleared, so if the client retries at the next height, it cannot find them anymore.
Always set the pending blobs together with the pending block.
`test_re_propose_locked_block_with_blobs` was modified to re-propose a `PublishDataBlob` operation. This fails for me without the fix.
An assertion was added that the pending blobs match the pending block. This would fail if the blobs were missing.
- These changes should be ported to the latest `main` branch.
- It could be released in a new SDK patch version.
- Possibly related: #3029
=> Don't forget pending blobs if retrying at the next height.

linera-service/src/server.rs
There is currently no way of telling what a validator's public key is without trying to read volume mounted config files.
Shards now log the validator public key on start-up.
Tested manually:
```
2025-01-31T12:46:23.411398Z  INFO linera_storage_server: Starting linera_storage_service on endpoint=127.0.0.1:35445
2025-01-31T12:46:24.424004Z  INFO linera_server: Wrote server config server_0.json
2025-01-31T12:46:24.424121Z  INFO linera_server: Wrote committee config committee.json
2025-01-31T12:46:24.445542Z DEBUG linera::main: linera_client::config: Persisted user chains
2025-01-31T12:46:24.462538Z  INFO linera::main: linera: Genesis config created in 18 ms
2025-01-31T12:46:24.517358Z  INFO GrpcProxy::run{public_address=0.0.0.0:9000 internal_address=0.0.0.0:10000 …
```
=> Print validator public key on shard start-up.

linera-service/src/server.rs
Cherry-picking  e919d054 to print the validator public-key on startup.
=> Print validator public key on shard start-up. (#3218)

examples/hex-game/README.md
Noticed a  typo in the instructions: "player player" → "player".
This fixes it for clarity. No other changes.
=> docs: Remove duplicate word in game instructions

linera-witty/src/util/merge.rs
I noticed a typo in a comment: "heterogenous" → "heterogeneous".
This PR corrects it to the proper spelling. No functional changes.
=> fix: Fix typo in "heterogeneous"

linera-service/tests/linera_net_tests.rs, linera-storage-service/src/client.rs
maitaining - maintaining 
for client - for the client
=> spelling and grammar issues in comments

linera-core/src/client/mod.rs, linera-service/src/linera/main.rs
In `assign_new_chain_to_key` we need a temporary `Client` instance tracking the new chain and its parent. We currently set all options to their defaults.
Use the configured options instead.
This should at best negligibly change performance when assigning a key to a new chain. CI will catch regressions.
- Closes #3237
=> Use configured client options in `assign_new_chain_to_key`.

linera-sdk/src/contract/test_runtime.rs
The original message is incorrect, as it indicates calling the set_can_close_chain method instead of the correct set_can_change_application_permissions. This is confusing, as developers may think they need to call the method to close the chain
SDK soon.
=> fix: incorrect method call message

examples/gen-nft/README.md
"a user provided prompt" → "a user-provided prompt"
(A hyphen is required in compound adjectives.)
=> docs: typo fix Update README.md

CLI.md, linera-client/src/client_options.rs, linera-client/src/storage.rs, linera-service/src/linera/main.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
Knowing the blobs that are in storage is useful for debugging. We implement this feature here.
The functionality is implemented from the `db_storage`. The problem is that the implementation depends on the serialization so a test is added for this.
The CI.
For the feature itself, it was tested locally from the command line for the non-fungible test.
A new functionality is added, but no break of storage schema occurs.
None.
=> Enable the listing of `BlobIds` from the command line.

Cargo.toml, examples/Cargo.lock
Our code currently doesn't build with `proptest` <1.6, as we rely on `std::ops::RangeFrom<u128>: proptest::strategy::Strategy`.  This is reflected in our lock file but not our manifest, possibly breaking builds that depend on our crates.
Update the manifest.
=> Correct our `proptest` requirement

linera-service/src/cli_wrappers/helmfile.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs
The docker image name is not actually getting propagated to the helmfile
Properly propagate the docker image name down to the helmfime, so the specified image is actaully used
Ran with a custom image, and it worked.
=> Actually use the correct docker image when docker_image_name is used

.github/workflows/rust.yml, linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/mass_client.rs, linera-rpc/src/simple/client.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/tests/local_net_tests.rs
We're gonna slowly change the design of this. Limiting the amount of in flight requests goes against our goal of stress testing a network with this
Remove that constraint
Ran `linera benchmark` with a few parameter variations
=> Remove max_in_flight from linera benchmark

linera-client/src/client_context.rs, linera-service/src/linera/main.rs
Will start paralellizing some parts of this existing flow
Paralellize initial validator sync step
=> Parallelize process_inboxes_and_force_validator_updates

linera-client/src/client_context.rs, linera-service/src/linera/main.rs
The block proposals are supposed to rotate and cancel each other out, but there's currently a bug in how we do it.
Fix the bug
=> Make generated block proposals cancel each other out

linera-client/src/client_context.rs, linera-service/src/linera/main.rs
This `RpcMessage` type is needed only when calling `mass_broadcast`, and it makes the code a bit more awkward because you have to check if it's a block proposal, when it'll always be
Return the actual `BlockProposal`s instead, and only convert them when needed.
=> make_benchmark_block_proposals now returns BlockProposals

linera-core/Cargo.toml, linera-service/Cargo.toml
The `unstable-oracles` feature currently has to be enabled manually for the `linera-core` and `linera-execution` crates. This makes it hard to rebuild the binaries while enabling the feature with a single command.
Link `linera-core` and `linera-execution`, so that if the feature is enabled in `linera-core`, it will also get enabled in `linera-execution`.
Add a new `unstable-oracles` feature to `linera-service`, and enable `linera-core`'s feature if it's enabled.
Manually tested with the following steps using the [`atoma-demo` repository](https://github.com/linera-io/atoma-demo).
```bash
export TEST_REV=9cdac7723e
cargo install linera-service --git https://github.com/jvff/linera-protocol-archive.git --rev "$TEST_REV" --features unstable-oracles
cargo install linera-storage-service --git …
```
=> Export `unstable-oracles` feature from `linera-service`

linera-storage/src/db_storage.rs
- Renamed `latest_epoches` → `latest_epochs` for proper pluralization.
=> Correct variable name typos in `db_storage.rs`**

linera-base/src/crypto/hash.rs, linera-base/src/crypto/keypair.rs, linera-base/src/crypto/mod.rs, linera-base/src/crypto/signature.rs, linera-base/src/lib.rs, linera-service-graphql-client/gql/service_schema.graphql
Soon I'll be adding a new signature scheme (secp256k1) and I thought `crypto.rs` started being too big and too generic. It'll be more managable to have different signature schemes and hashing in its respective files.
Turn `crypto.rs` file into a `crypto` module and extract code to separate files for:
- `CryptoHash` as `hash.rs`
- `Signature`as `signature.rs`
- `KeyPair` and `PublicKey` as `keypair.rs`
N/A
- Nothing to do
=> Make crypto.rs into a module and split into files.

linera-chain/src/block.rs, linera-chain/src/chain.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/temporary_changes.rs
To make https://github.com/linera-io/linera-protocol/issues/2025 possible, we need to better separate the code that verifies a certificate and handles outboxes and inboxes from the block execution code.
Don't call `execute_init_message` from `execute_block` at all: That is already unnecessary because it is called from `process_confirmed_block` and `receive_message_bundle`.
Extract some functions from `execute_block` and `process_confirmed_block` to make them easier to read, and deduplicate some of the logic.
CI
- Related to #2025 
=> Refactorings to make separation of execution from certificate handling easier.

linera-chain/src/outbox.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-views/DESIGN.md
- **Old Word:** `ie.`
- **New Word:** `i.e.`
- **Reason:** Added a comma for clarity and adherence to grammatical conventions.
=> Documentation Improvements

linera-core/src/data_types.rs, linera-core/src/worker.rs
Changes:
1. linera-core/src/data_types.rs:
- waiting be picked
+ waiting to be picked
Reason: Added missing "to" preposition for grammatical correctness
2. linera-core/src/data_types.rs:
- time or or whenever
+ time or whenever  
Reason: Removed duplicate "or" to fix redundancy
3. linera-core/src/worker.rs:
- does contain
+ does not contain
Reason: Added missing "not" to correctly express error condition
These changes improve documentation clarity and error message accuracy.
=> Fix Grammar and Clarity in Documentation and Error Messages

linera-base/src/identifiers.rs, linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
We want to use event streams for committee changes to address the admin chain's scalability issues. Ultimately we want to replace pub-sub channels with event streams entirely. (#365)
Write committed blocks' events to storage.
This doesn't use them yet, and just ports parts of https://github.com/linera-io/linera-protocol/pull/2309 to `main`, so we don't have to rebase them again in the future. CI should catch any regressions, and the event functionality itself will be tested in upcoming PRs, when events are actually used.
- Porting parts of #2309.
- Related to #365.
=> Write events to storage.

linera-faucet/client/README.md, linera-faucet/server/README.md
The `README.md` files in the `linera-faucet/client` and `linera-faucet/server` directories contained broken links to the `CONTRIBUTING.md` and `LICENSE` files. This PR fixes these links to ensure users can access the correct resources.
Updated the paths in the `README.md` files:
1. Changed `../CONTRIBUTING.md` to `../../CONTRIBUTING.md`.
2. Changed `../LICENSE` to `../../LICENSE`.
These changes ensure the links point to the correct files in the repository.
=> fix: 404 links in README.md files

linera-core/src/chain_worker/actor.rs, linera-core/src/worker.rs, linera-service/src/linera/main.rs
Testnet is currently experiencing some panics when an attempt is made to send a request to a chain worker actor. The panic message says that the endpoint is closed. One possible cause is #3295, where a storage error could cause an endpoint to be added to the chain worker cache but its respective actor task wouldn't start.
Refactor the `ChainWorkerActor` so that it has a `run` method that loads the chain state from storage and then handles the incoming requests. If loading the state fails, then the error is reported to the next requester, and loading will be reattempted while the actor is running and receiving requests.
CI should catch any regressions caused by this refactor.
#3299 tracks having a regression test for the issue.
- These changes should be backported to the latest `devnet` …
=> Fix dangling endpoint to chain worker actor that failed to start

Cargo.lock, examples/Cargo.lock, linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-chain/Cargo.toml, linera-chain/src/block.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs, linera-execution/src/unit_tests/system_tests.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/test_system_execution.rs, linera-execution/tests/wasm.rs, linera-sdk/src/test/block.rs, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs, linera-storage/src/lib.rs
The fact that events are in `RawExecutionOutcome` makes #365 more complicated. They also conceptually don't need to be in the structure whose purpose is mainly to associate messages with the correct application ID and authenticated signer.
Remove `events` from `RawExecutionOutcome`. Also remove `subscribe` and `unsubscribe`; the same argument applies to them.
Refactoring; CI should catch regressions.
- Related to #365
=> Move events and subscriptions out of `RawExecutionOutcome`.

linera-base/src/data_types.rs, linera-chain/src/block.rs, linera-chain/src/data_types.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-execution/src/transaction_tracker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs
`EventRecord` has its name because back then there was still another `Event` type. That is not the case anymore.
Rename `EventRecord` to `Event`.
Only renaming; CI would catch regressions.
=> Rename `EventRecord` → `Event`.

linera-rpc/src/grpc/client.rs
The gRPC status log currently does not show which validator connection it is about.
Include the validator address in the log.
CI
Example log:
`2025-02-12T16:56:00.764092Z ERROR linera::main:node_service{port=8080}:subscribe{address="https://linera-testnet.contributiondao.com:443"}:notification stream: linera_rpc::grpc::client: Unexpected gRPC status: status: Internal, message: "h2 protocol error: error reading a body from connection", details: [], metadata: MetadataMap { headers: {} }`
- These changes should released in a new SDK.
- They should be ported to the `main` branch.
- Related to #3300
=> Include validator address in gRPC status log.

Cargo.lock, examples/Cargo.lock, linera-base/Cargo.toml, linera-base/src/data_types.rs
The `FromStr` and `Display` implementations for `OracleResponse` are not used anywhere, and make it a lot more complicated to add new oracle variants, especially if they involve complex types. We will soon have to add one for events.
Remove `FromStr` and `Display`.
CI will tell us if it was used after all!
=> Remove `Display` and `FromStr` for `OracleResponse`.

.gitignore
For people using Cursor, we don't want their config files getting committed
Add `.cursor` to `.gitignore`
CI
=> Add .cursor to .gitignore

linera-client/src/client_context.rs, linera-service/src/linera/main.rs
Right now we don't respect the current Epoch when creating block proposals for the benchmark, as well as not getting the committee for the current epoch (we always just build a committee from the genesis config)
Send block proposals to committee of the current epoch, and build block proposals taking current epoch into consideration
CI + ran benchmark locally
=> [benchmark] Respect current Epoch and Committee on block proposal creation

linera-views/src/backends/rocks_db.rs
RocksDB is implemented as an SST. So it has some in memory buffer, that gets flushed to disk when certain criteria is met.
What was happening was that we weren't flushing data to disk frequently enough, and the implementation we're using to get an iterator in `find_keys_by_prefix` flushes some tombstones to disk, if necessary. And since we weren't flushing data to disk frequently enough, it often was.
This was causing an increase in those reads of a few tens of ms, which when trying to make the client achieve high TPS makes a big difference.
Reduce the size of the write buffer in general, so that we flush to disk more often. This overall seems to improve performance.
Based on this https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide#flushing-options
We had at most 2 write buffers …
=> Optimize RocksDB DB open options

linera-rpc/src/grpc/client.rs
This is an attempt to clean up https://github.com/linera-io/linera-protocol/pull/3313 a bit
Use `.in_scope()` as it seems cleaner
CI
=> Use .in_scope() in gRPC client

Cargo.lock, examples/Cargo.lock, linera-base/Cargo.toml, linera-base/src/lib.rs, linera-service/src/linera/net_up_utils.rs, linera-service/src/proxy/main.rs, linera-service/src/server.rs, linera-service/src/util.rs
This is a pretty useful function in general to be used by different binaries. It makes sense to have it be in a location that will avoid circular dependencies.
Move it to `linera-base`
CI + will use this from the client in the next PR
=> Move listen_for_shutdown_signals to linera-base

Cargo.lock, linera-client/Cargo.toml, linera-client/src/client_context.rs
Right now if you interrupt the benchmark, it might leave you in a state where the local node is inconsistent with the validators, the wallet hasn't been saved... etc
Gracefully shutdown the benchmark on interruption signals, making sure we never exit in the middle of sending a block proposal, and only saving the wallet on program exit.
Ran the benchmark locally, did Ctrl+C and saw it gracefully exit.
=> Gracefully shutdown benchmark

examples/counter/tests/single_chain.rs, examples/crowd-funding/src/state.rs
Comment on chain application initialization:
Old: Creates the application on a 'chain', initializing it with a 42 then add 15 and obtain 57.
New: Creates the application on a 'chain', initializing it with a 42 then adds 15 and obtains 57.
Reason: Fixed verb tense for consistency.
Comment on instantiation data:
Old: The instantiation data that determine the details the campaign.
New: The instantiation data that determine the details of the campaign.
Reason: Added missing preposition "of" for clarity.
=> Grammar and Clarity Fixes

linera-indexer/plugins/src/template.rs
There’s a small typo in `entrypoint2`: replace `Ok(self.view1.get(&key).await?)` with `Ok(self.view2.get(&key).await?)` because `view2` is the MapView that requires a key.
=> Correcting the Typo in `entrypoint2`

CLI.md, linera-client/src/client_options.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs, linera-service/tests/local_net_tests.rs
Right now we have a `--with-faucet-chain` option that both enables starting a faucet and also specifies what chain the faucet will be running on.
`linera faucet` however has a slightly different behavior, in which if you don't specify the chain, it just uses the default chain.
Introduce a `--with-faucet` option that controls whether a faucet will be started, which will by default start a faucet on the default chain, unless the `--faucet-chain` argument is provided.
Run it locally, see the faucet being started using the default chain as expected, and previous behavior also works
=> Introduce --with-faucet for net up using the default chain

linera-base/src/prometheus_util.rs
Right now we're generating the buckets, but it's not in an inclusive way, and it should be. For latency metrics, for example, you have `end_value` being 500ms, but one of the buckets is 159. Since we're using a multiplication factor of 3, the next bucket would go over 500ms, so we don't include it...
Make sure we always include the `end_value` bucket
CI + start a network locally and see the correct buckets exported
=> Make sure we include end_value in generated Prometheus buckets

CLI.md, linera-chain/src/block.rs, linera-client/src/client_options.rs, linera-client/src/storage.rs, linera-core/src/node.rs, linera-execution/src/applications.rs, linera-rpc/src/grpc/conversions.rs, linera-service/src/linera/main.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
We implement here the functionality of listing the Chain Ids from a storage.
The implementation follows the same path as from the implementation of the listing of the BlobIds by using the `list_root_keys`.
The functionality was tested locally by running the non-fungible test and listing the ChainIds.
Normal release schedule.
None.
=> Implement the functionalities of listing the `ChainIds`.

examples/ethereum-tracker/src/contract.rs, examples/ethereum-tracker/src/lib.rs, examples/ethereum-tracker/src/service.rs, linera-sdk/src/ethereum.rs
While working on PR #2631, the end-to-end test for the Ethereum Tracker example started failing. That happened because the updated HTTP request API also included the response headers in the oracle recording, and a "Date" header made the response non-deterministic.
Use the service to perform the HTTP request, and only send back to the contract the actual deterministic information that matters.
In order to do so, the `EthereumClient` had to be split in two, so that it could use either the contract system APIs or the service system APIs.
The end-to-end test passes locally in my repository when this fix is applied to the changes in PR #2631.
- Nothing to do / These changes follow the usual release cycle, as it only changes the example and the SDK.
- [reviewer …
=> Use service to query ethereum node in Ethereum Tracker example

linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/wasm/system_api.rs, linera-sdk/wit/service-system-api.wit
Removed query service from the BaseRuntime and moved it to the ContractRuntime as the ServiceRuntime doesn't need it.
=> Make `query_service` contract-only.

linera-chain/src/data_types.rs, linera-chain/src/manager.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
`Owner` in `BlockProposal` is redundant information (derived from public key that's already part of the `BlockProposal`).
Remove `owner` field from `BlockProposal`.
CI.
=> Remove Owner from BlockProposal.

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, linera-execution/Cargo.toml, linera-execution/build.rs, linera-execution/src/execution.rs, linera-execution/src/lib.rs, linera-execution/src/revm.rs, linera-execution/src/wasm/mod.rs, linera-execution/tests/revm.rs, linera-views/src/common.rs
We want to make Linera a Multi VM blockchain. Here is the first step toward having EVM support.
We use the REVM implementation which is flexible enough for our purposes. The following decisions were made:
* Just like Linera smart contracts, Ethereum smart contracts can return some values when called. 
* The nonce is used for building the smart contract address. Here we limit ourselves to just one address build from `Address::ZERO` with a nonce of 0. Something else would have to be done for handling more than one contract.
* REVM allows to make cross application calls. But right now, we call only one contract.
* Ethereum addresses are quite different from Linera ones. So Transfer of Ethereum are not supported.
* The feature `revm` is used for enabling this.
* `Revm` is introduced in …
=> Introduce Evm support in Linera.

linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-service/src/linera/main.rs, linera-service/tests/local_net_tests.rs
For the chains we're using during the benchmark, we were currently adding them to our wallet. However, that is not necessary.
Create chains for the benchmark, and don't add them to any wallet, just use them for the benchmark then close them.
Ran locally, saw that things worked correctly
=> Stop updating the wallet during linera benchmark

linera-rpc/src/grpc/server.rs, linera-service/src/proxy/grpc.rs
We don't need to track latencies below 1ms IMHO. Also, for the server latency, I noticed it would very often just shoot to 50ms and stay there the whole time. If you're using few shards (1, like me, for example), shard latency can actually be fairly high.
Adjust things
Check the changes on a local network
=> Adjust latency metrics buckets

docker/dashboards/linera-general.json, kubernetes/linera-validator/grafana-dashboards/linera-general.json, linera-rpc/src/grpc/server.rs, linera-service/src/proxy/grpc.rs
`1h` metrics honestly don't make much sense, because p99 for example could take forever to go down, even though the network is fine.
`1m` seems more reasonable.
Deploy a local network and check
=> Adjust dashboards to show 1m metrics

linera-witty/src/primitive_types/simple_type.rs, linera-witty/src/runtime/borrowed_instance.rs
Before: /// Marker trait to prevent [SimpleType] to be implemented for other types.
After: /// Marker trait to prevent [SimpleType] from being implemented for other types.
Reason: Corrects improper English usage—"prevent from being implemented" is the correct form.
Fixed incorrect phrasing in instance.rs
Before: //! Implementations of Wasm instance related traits to mutable borrows of instances.
After: //! Implementations of Wasm instance-related traits for mutable borrows of instances.
Reason: Adds a hyphen in "instance-related" (compound adjective) and replaces "to" with "for" for accuracy.
=> Fix Grammar and Clarity in Documentation Comments

Cargo.lock, Cargo.toml, linera-client/Cargo.toml, linera-client/src/benchmark.rs, linera-client/src/client_context.rs, linera-client/src/error.rs, linera-client/src/lib.rs, linera-core/src/client/mod.rs, linera-service/src/linera/main.rs
Right now on `linera benchmark` we do everything from a single thread. That doesn't scale much.
Spawn one task per chain, and split the desired BPS across the number of chains. For example, if the desired BPS is 10, and you have 10 chains, each task will need to reach 1 BPS.
Every task just tries to send as many block proposals as fast as possible. We don't control the BPS in the tasks, but we have a BPS control task for that. Once a task has sent the BPS amount of blocks successfully, it sends a message to the BPS control task. It uses a `crossbeam` channel for that, as it allows bounded channels with buffer size of 0.
If we have a buffer size of 0, that means that if the BPS control task is sleeping or processing another message, the sender task will be blocked. This is exactly what we …
=> Have one thread per chain on benchmark

CLI.md, README.md, linera-client/src/client_options.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/tests/linera_net_tests.rs, scripts/linera_net_helper.sh
* Allow README files to run on the testnet
* Do not hardcode chain IDs
* Create a command `request-chain`
* Use it in the main README file
* Also create a comment `follow-chain` while we're at it
Tested new CLI commands manually (together with `forget-keys` and `forget-chain`) + CI
These changes COULD be backported to the latest `testnet` branch, then be released in a new SDK.
=> Create command `request-chain` to allow using testnets in bash

packages.txt
Publishing the documentation fails on `main`.
Add the missing entries to `packages.txt`.
I reproduced the problem locally with `test_publish.sh`. The change fixes it.
=> Add missing faucet entries to packages.txt.

README.md, examples/amm/README.md, examples/counter/README.md, examples/crowd-funding/README.md, examples/fungible/README.md, examples/gen-nft/README.md, examples/hex-game/README.md, examples/llm/README.md, examples/matching-engine/README.md, examples/native-fungible/README.md, examples/non-fungible/README.md, examples/rfq/README.md, examples/social/README.md, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs, linera-service/tests/readme_test.rs
Allow removing the hard-coded OWNER variables from README tests
Make sure to return the owner on stdout every time the CLI generates a key pair.
I modified the main README file.
Continues #3385
=> Improve CLI for owners in bash tests

linera-client/src/config.rs
This line is printed repeatedly and is not that useful.
Make it `trace` level.
CI
=> reduce verbosity of "Persisted user chains"

CLI.md, linera-client/src/client_options.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs
This option is no longer needed after #3388.
Remove CLI option "linera net up --extra-wallets"
CI
=> remove CLI option "linera net up --extra-wallets"

INSTALL.md
Fix install after #3345.
Apple clang doesn't compile for Wasm. After #3345, clang is needed. However, LLVM v19 is an issue (to be discussed separately).
run `brew install llvm@18` locally and it solved the issue
=> update install for MacOS

CLI.md, linera-client/src/client_options.rs, linera-client/src/util.rs, linera-service/src/linera/main.rs
After #3393, wallet names do not need to be numbers
Support alphanumerical wallet names
CI
=> generalize --with-wallet N to --with-wallet ALPHANUM

examples/hex-game/README.md, examples/social/README.md
After #3393, wallet 0 no longer has to be used.
Be consistent in the name of wallets w.r.t. BASH variables
CI
=> nit: fix wallet name in example README

Cargo.lock, Cargo.toml, linera-faucet/Cargo.toml, linera-faucet/client/Cargo.toml, linera-faucet/client/src/lib.rs, linera-faucet/src/lib.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-version/src/version_info/type.rs
`anyhow::Error` doesn't implement `std::error::Error`, and therefore can't be converted to a JavaScript error (`wasm_bindgen::JsError`).
Give `linera-faucet-client` a dedicated error type, with help from `thiserror` and `thiserror-context`.
Refactor: should be tested by CI.
=> `linera-faucet-client`: remove `anyhow`

linera-base/src/data_types.rs, linera-base/src/prometheus_util.rs, linera-chain/src/chain.rs, linera-core/src/client/mod.rs, linera-core/src/worker.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/revm.rs, linera-execution/src/wasm/mod.rs, linera-rpc/src/grpc/server.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs, linera-views/src/metrics.rs, linera-views/src/views/bucket_queue_view.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/log_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/queue_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/register_view.rs, linera-views/src/views/set_view.rs
We currently use exponential buckets everywhere. As much as they're good in the sense that they generate less buckets, and can be cheaper on Grafana Cloud, etc, they make our buckets super wide, which makes our Prometheus data less accurate.
I need to spend some time later looking at the `testnet` data for these different metrics to adjust the buckets, but for not just changing proxy/server latencies to use linear buckets instead.
I also changed the default starting value to 0.001 as 1 microsecond should be enough for most of what we're measuring, and will take at least one bucket away from metrics using this.
Run a validator locally, see the metrics exported with the new buckets
=> Use linear buckets in some places

linera-client/src/storage.rs, linera-storage-service/src/common.rs, linera-views/src/backends/dual.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/store.rs
We'd like to simplify config management from databases.
The first step is to make storage config objects serializable.
CI
=> Make storage configs clonable and serializable

linera-rpc/src/grpc/server.rs, linera-service/src/proxy/grpc.rs
A lot of changes happened in this prometheus code that we didn't backport (mainly [#2878](https://github.com/linera-io/linera-protocol/pull/2878)). Backporting it would be a huge pain, so I'm just gonna change the buckets manually for now, and when we cut a new testnet we'll have the proper stuff in
Manually adjust buckets
CI
=> [testnet] Manually adjust proxy/server buckets for latencies

kubernetes/linera-validator/helmfile.yaml, kubernetes/linera-validator/templates/ingress.yaml
Right now when deploying networks we see a few warnings because we're using deprecated stuff
Stop using the deprecated stuff
Deployed a netowrk, didn't see the warnings anymore
=> Stop using deprecated stuff in yaml configs

linera-sdk/src/test/mod.rs
Let application unit tests be able to call `block.with_native_token_transfer` which need `Recipient`.
Export `linera_execution::system::Recipient` in `linera-sdk/src/test` crate.
CI
=> Export linera_execution::system::Recipient to application tests

Cargo.lock, examples/Cargo.lock, linera-sdk/Cargo.toml
Version 1.7.0 breaks semver compatibility by requiring the usage of a new Rust edition. More information is available in https://github.com/RustCrypto/formats/issues/1684.
We should pin it to the last version that we still support at least until we manage to update to the new Rust edition.
We may have to make a new SDK release with a new patch version.
=> Pin the version of the `base64ct` indirect dependency

linera-sdk/src/test/validator.rs
After switching to `k256` for secp256k1 our `benchmarks` job stopped failing. Most likely it's caused by `k256` being much slower and this leads to worker cache being busy and unable to handle new requests - which leads to test failures.
Double worker count for now.
CI
- Nothing to do
=> Double worker count in benchmarks

linera-sdk/src/service/runtime.rs, linera-sdk/src/service/test_runtime.rs
Allow it to be used in a shared reference to the runtime.
PR #2631 updated the runtime APIs to perform HTTP requests, but unfortunately the `ServiceRuntime::http_request` method had an unnecessary `&mut self` receiver. This makes it different from all other `ServiceRuntime` methods.
Change the receiver to be `&self`, and do the same in the `MockServiceRuntime`.
CI should catch any regressions by this refactor.
- Nothing to do / These changes follow the usual release cycle, because this fixes an issue with a feature that hasn't yet been released.
=> Remove `mut` from `ServiceRuntime::http_request`

.github/workflows/rust.yml, CLI.md, Cargo.lock, linera-client/src/client_options.rs, linera-execution/src/execution.rs, linera-execution/src/policy.rs, linera-service/Cargo.toml, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/cli_wrappers/local_net.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs
Right now we pass everything manually, but there's already a config that can make this easier
User the policy config instead
CI
=> Add --policy-config argument to create-genesis-config

kubernetes/linera-validator/templates/shards.yaml
Right now we start all shards one by one. That doesn't seem necessary, and when starting a large number of shards (like 100 or more), it can take a long time.
Change the pod management policy to start all shards at once, in parallel
Deployed a local kind network with 80 shards, saw all of them getting initialized in parallel, much faster
=> Start shards in parallel

linera-client/src/client_context.rs, linera-client/src/error.rs, linera-service/src/linera/main.rs
I'd like to also use this function from `linera-web`.
Move it into `linera-client`, and give it its own non-`anyhow` errors.
CI.
=> `linera-service`: move `assign_new_chain_to_key` to `linera-client`

linera-base/src/crypto/ed25519.rs, linera-base/src/crypto/mod.rs, linera-chain/src/data_types.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
In order to improve type-safety (and also in preparation for allowing for Ethereum keys as chain owners) we need to replace type alias with a struct.
Use newtype struct wrapper for `Ed25519` for now.
CI.
=> Use newtype wrapper for `Account` keys and signatures.

linera-chain/src/chain.rs, linera-chain/src/inbox.rs, linera-chain/src/outbox.rs, linera-rpc/src/grpc/server.rs
Would be nice to track size of inboxes/outboxes, as well as when the cross chain messages/notifications channel is full.
Add those metrics
Will deploy a local network to see the metrics being logged
=> Adding some metrics

linera-client/src/benchmark.rs, linera-client/src/client_options.rs, linera-service/src/linera/main.rs
Closing chains actually takes a surprisingly long time. The client will actually return fairly quickly, but the validators will be executing stuff for a while after the `CloseChain` operation is done. Also latency spikes while the validator is doing that.
It's probably something to be investigated as well, tbh.
For now, add an option to the benchmark to just not close the chains that are created for the benchmark (don't close them at the end), so that iteration with a lot of chains is faster.
Run it with the option, see that we exit quicker and the validators are not doing a bunch of stuff after the benchmark is exited.
=> Add option to not close chains on benchmark

kubernetes/linera-validator/grafana-dashboards/linera/execution.json, kubernetes/linera-validator/grafana-dashboards/linera/general.json, kubernetes/linera-validator/grafana-dashboards/linera/storage.json, kubernetes/linera-validator/grafana-dashboards/linera/views.json, kubernetes/linera-validator/grafana-dashboards/linera/vms/ethereum.json, kubernetes/linera-validator/templates/grafana-dashboards-config.yaml, kubernetes/linera-validator/templates/grafana-linera-dashboards-config.yaml, kubernetes/linera-validator/templates/grafana-linera-vms-dashboards-config.yaml, kubernetes/linera-validator/templates/grafana-scylla-dashboards-config.yaml, kubernetes/linera-validator/templates/grafana-scylla-manager-dashboards-config.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl
Created a bunch of dashboards in Grafana Cloud to help us have a better view of the network
Make sure self hosted Grafana also has these dashboards
Will deploy a local network and see the new dashboards
=> Match dashboards in self hosted Grafana to Grafana Cloud

linera-chain/src/chain.rs, linera-storage/src/db_storage.rs, linera-views/src/metrics.rs
The p99 for these is consistently or very frequently at the maximum value. This means we need to increase the maximum value for these buckets, as they're failing to capture all values
Increase bucket's maximum value
Will deploy a local network and see
- These changes should be backported to the testnet branch, but if we're cutting a new branch soon then it's not needed
=> Adjust some bucket limits

examples/Cargo.lock, examples/native-fungible/Cargo.toml, examples/native-fungible/tests/transfers.rs, linera-sdk/src/test/chain.rs
When writing applications that use native tokens, it helps to write integration tests if there's an easy way to query the on-chain native token balances.
Add a few helper methods to read the native account balances on an `ActiveChain`.
Integration tests that use the new helpers were added to the Native Fungible Token application example.
- Nothing to do / These changes follow the usual release cycle, because this introduces a new backwards compatible feature.
- Closes #3417
=> Allow reading native balances in integration tests

.github/workflows/rust.yml, linera-sdk/wit/base-runtime-api.wit, linera-sdk/wit/contract-runtime-api.wit, linera-sdk/wit/contract.wit, linera-sdk/wit/service-runtime-api.wit, linera-sdk/wit/service.wit
The WIT files are automatically generated by Witty from the Rust code. Therefore, they must be kept up-to-date with the Rust code for applications to work correctly.
There was a CI job to check this before, but it was accidentally removed when the CI jobs were refactored (#2786).
Add a new CI job to run `wit-generator -c`.
CI should show if the job executed successfully.
- Nothing to do because this only affects CI. Even though the WIT files were unsorted, they were correct.
=> Restore CI job to check WIT files

linera-chain/src/chain.rs, linera-chain/src/inbox.rs, linera-chain/src/outbox.rs
When running benchmarks, inbox size can shoot up to 10k pretty quickly...
Increase the end value bucket to a pretty generous value
Deploy network, see the new max value for metric
=> Adjust end value bucket for inbox size

linera-core/src/remote_node.rs
`std::time` is not supported on Wasm.
Use `linera_base::time` instead.
CI, and from `linera-web`.
- Backporting is not ~possible~ necessary but we may want to deploy a new `devnet` and release a new
SDK soon.
=> `linera-core`: use `linera_base::time`

.github/workflows/rust.yml, linera-base/src/prometheus_util.rs
So I was under the impression that getting the ceiling there would make us always include the end value, but I was wrong :)
Doing the same fix here for the end value that we did for the exponential buckets
Deployed a local network, saw that we actually see 500 as the max value now for example for proxy latency
=> End value fix for linear_bucket_interval

kubernetes/linera-validator/grafana-dashboards/linera/execution.json, kubernetes/linera-validator/grafana-dashboards/linera/general.json, kubernetes/linera-validator/grafana-dashboards/linera/storage.json, kubernetes/linera-validator/grafana-dashboards/linera/views.json, kubernetes/linera-validator/grafana-dashboards/linera/vms/ethereum.json
I noticed we didn't have a ScyllaDB container CPU usage, and some of the JSON here seemed to be specific to Grafana Cloud.
Add the ScyllaDB container CPU usage graph, and remove some stuff from the JSON
This was exported from a deployed network, so there shouldn't be any issues
=> Adding ScyllaDB CPU usage graph + some other changes

linera-ethereum/src/client.rs
The comparison of `"2.0"` with `result.jsonrpc` was incorrect. Since `"2.0"` is already a string literal, the dereference (`*`) was unnecessary and didn’t make sense. This could lead to unexpected behavior.  
Removed the unnecessary dereference to ensure proper string comparison in the JSON-RPC check.  
Verified that the comparison now works correctly by testing with valid and invalid `jsonrpc` versions. Ensured no regressions in existing functionality.  
No breaking changes. This is a straightforward fix that improves correctness. Safe to include in the next release.
=> chore: fix incorrect string comparison in JSON-RPC check

.github/workflows/rust.yml, .taplo.toml, Cargo.toml, INSTALL.md, examples/Cargo.toml, examples/agent/Cargo.toml, examples/ethereum-tracker/Cargo.toml, linera-base/Cargo.toml, linera-core/Cargo.toml, linera-ethereum/Cargo.toml, linera-execution/Cargo.toml, linera-explorer/Cargo.toml, linera-faucet/Cargo.toml, linera-faucet/server/Cargo.toml, linera-indexer/example/Cargo.toml, linera-indexer/graphql-client/Cargo.toml, linera-indexer/lib/Cargo.toml, linera-rpc/Cargo.toml, linera-sdk/Cargo.toml, linera-service-graphql-client/Cargo.toml, linera-service/Cargo.toml, linera-storage-service/Cargo.toml, linera-version/Cargo.toml, linera-witty/Cargo.toml
A fork of cargo-sort used in CI to normalize Cargo.toml files as the project is on life support. #3409
Migrate from cargo-sort to [Taplo](https://taplo.tamasfe.dev/), while current lint step should verify the order of dependencies alongside schema validation. 
CI
- https://taplo.tamasfe.dev/cli/usage/validation.html
=> Migrate from cargo-sort to Taplo (#3409)

Cargo.lock, Cargo.toml, linera-client/Cargo.toml, linera-client/src/benchmark.rs, linera-client/src/client_options.rs, linera-client/src/error.rs, linera-service/src/linera/main.rs
Right now, the only way of knowing if the benchmark is completely destroying validators is by checking Grafana for the metrics (which have a 2m delay), and stopping the benchmark manually. This is not ideal, as if latency becomes too high, the validators can take a very long time to recover after it.
Introduce a `--health_check_endpoints` to `linera benchmark`, that if provided, will query the specified metrics host:port pairs for metrics, to determine the health of the validators. For now this health is determined by the p99 proxy latency being below 400 ms.
We're querying the metrics endpoint from the proxy directly with this, so it works on all different kinds of deployments (docker compose, kubernetes, just binaries running locally, etc). The user is responsible for making sure the …
=> Query prometheus metrics from benchmark

linera-client/src/benchmark.rs, linera-client/src/client_options.rs, linera-service/src/linera/main.rs
Right now if we have the `--close-chains` option on, we'll close all the chains in parallel. If we don't, we'll process all the inboxes in parallel also before saving the benchmark chains to the wallet.
This is not ideal because depending on how many chains we're using, this can pound the validators pretty hard, and drive latency up to the point of us getting a bunch of timeouts when wrapping things up.
Also, when latency spikes up too much, the validators take a while to recover.
Introduce a `--wrap-up-max-in-flight` argument to limit the concurrency when wrapping things up
Tested locally, no timeouts anymore, and things actually go faster (if we timeout, we retry, and this can take a while until we actually eventually succeed within the timeout constraint)
- Nothing to do / These …
=> [benchmark] Don't obliterate validators as much when wrapping up

.github/workflows/rust.yml
We recently changed to use taplo sort instead of cargo sort
Update the CI job name to avoid confusion
CI
=> We're not using cargo sort anymore, change CI job name

linera-chain/src/block.rs, linera-chain/src/data_types.rs, linera-client/src/chain_listener.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/worker.rs, linera-execution/src/lib.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/node_service.rs
Working on https://github.com/linera-io/linera-protocol/pull/3432 I found a few issues that can be fixed separately.
* Move the operation inspection code from the two `published_blob_ids` implementations to `Operation` and deduplicate it.
* Use the `select!` macro in the client listener. This will make it easier to add another stream, to listen for admin chain events.
* Fix a typo where a blob ID was called `chain_id`.
* Add a check that events don't get overwritten. Testing this will be complicated, and possibly require more SDK features: https://github.com/linera-io/linera-protocol/issues/3488
* Treat `stage_new_committee` like other client operations. The issue with conflicting blocks needs to be addressed for all operations anyway, and admin operations are always on a single-user …
=> Check for overwriting events, fix typos, duplications, and minor inconsistencies.

.github/workflows/documentation.yml
This seems to be intermittently failing on `main`, seems like compilation is taking longer now making it timeout.
Since this runs only on `main`, we don't particularly care about it finishing quickly, so staying on `ubuntu-latest` seems ideal to reduce costs.
So just increasing the timeout. 
Merge
=> Increase test-crates-and-docrs timeout

linera-sdk/src/test/validator.rs
If we create new chain with `open_chain` in `contract.rs`, it won't be maintained by `TestValidator` in integration tests. Thus we won't be able to test some functionalities of the new chain in integration tests. For example, if we would like to call operation from another user chain to the created chain's application, the user chain should register the application firstly, then call it. At that time we'll get error `Chain not found` with the `TestValidator`.
If we could add exists chain to `TestValidator`, then I think we'll be able to test those created chains in integration tests.
CI
=> Add exists chain to TestValidator to test new created chain

.github/workflows/rust.yml
Taplo doesn't explain the problem on failure by default, which hurts developer experience.
Pass `--diff` alongside `--check`.  This causes Taplo to tell us what's wrong when checking fails instead of just failing silently.
CI.
=> `.github/workflows/rust.yml`: use `--diff` with `taplo`

linera-execution/src/committee.rs, linera-sdk/src/test/block.rs, linera-sdk/src/test/chain.rs, linera-sdk/src/test/validator.rs
In integration tests, the `ResourceControlPolicy` was hardcoded to use the default value. With the addition of an HTTP allow list (#3427), the tests aren't able to test any HTTP requests.
Allow changing the `ResourceControlPolicy` used inside a test, allowing to add hosts to the allow list. For the policy change to work, a new committee and epoch must be published. Therefore the epoch and committee can't be assumed to be constant anymore.
Wrote some (upcoming) tests that try to perform an HTTP request without changing the policy and after adding the host to the policy, and ensured that the former fails while the latter succeeds.
- These changes follow the usual release cycle, because this will help with tests that use a feature that has not yet been released.
- [reviewer …
=> Support custom `ResourceControlPolicy` in integration tests

linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/storage.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/test_utils/system_execution_state.rs, linera-indexer/lib/src/rocks_db.rs, linera-indexer/lib/src/scylla_db.rs, linera-service/src/schema_export.rs, linera-storage-service/src/client.rs, linera-storage-service/src/server.rs, linera-storage/src/db_storage.rs, linera-views/src/backends/dual.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/journaling.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/metering.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/backends/value_splitting.rs, linera-views/src/context.rs, linera-views/src/store.rs, linera-views/src/test_utils/mod.rs, linera-views/src/views/unit_tests/views.rs, rust-toolchain.toml
* First step in distinguishing immutable shared data from root views
* Simplify code
Do not pass a root key when calling the method `connect`.
The current code will use the empty vector, but this could also change later to enforce a separation between the locked mode (with root key -- for root views) and the default mode (no root key -- for blobs).
CI
=> Do not pass a root key when calling the method `connect`

linera-sdk/src/test/block.rs, linera-sdk/src/test/chain.rs
It is useful in integration tests to test the flow from a service mutation up to the contract execution. This could be done previously by calling `graphql_query` and then manually adding a new block. However, this had some limitations, as for example if the service called another service which created an operation for the called application could not easily be added.
Also, given how frequent GraphQL mutations are used in applications, it makes sense to make testing it as seamless as possible.
Add an `ActiveChain::graphql_mutation` helper method, which queries the service and attempts to create a block with the scheduled operations.
Tested manually in some upcoming integration tests for HTTP requests.
- These changes follow the usual release cycle, because they contain non-breaking new …
=> Simplify testing GraphGL mutations in integration tests

.github/workflows/rust.yml, Cargo.lock, linera-execution/src/revm.rs, linera-execution/src/test_utils/mod.rs, linera-execution/src/test_utils/solidity.rs, linera-execution/tests/revm.rs, linera-sdk/Cargo.toml, linera-sdk/build.rs, linera-sdk/src/abis/evm.rs, linera-sdk/src/abis/mod.rs, linera-service-graphql-client/tests/test.rs, linera-service/Cargo.toml, linera-service/build.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
The end-to-end test for Evm is needed as a tool.
* The compilation functionalities are moved to a `solidity.rs` file so that it can be used in the end-to-end test.
* The `EvmAbi` is implemented. The Evm applications are untyped so there is no point in adding specific types.
* The bytecode is written directly to file in order to have a system that works in the same way as for Wasm.
* The `VmRuntime`is added to the `publish_and_create`.
* The code in `revm` is changed so that it suits the framework of Wasm:
- The `handle_query` is parsing the initial entry and returning the parsed value.
- The `execute_operation` is not changed as it is put in the `schedule_operation`.
The design of the parsing of json entries is not great. But it reflects the design of json for the …
=> Implement the EVM test in the end-to-end test.

linera-views/src/backends/journaling.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/test_utils/mod.rs, linera-views/tests/store_tests.rs
* As noted by @MathieuDutSik in #3496, LRU-caching is incorrect outside views.
* However, journaling outside of views is also incorrect
On top of #3501, we simply deactivate the features that require exclusive access to an object in storage.
* Journaling is not authorized.
* LRU cache should never insert `None` but instead forget about the deleted key. (Not that we delete blobs but who knows in the future.)
We may want to rename `connect` and `clone_with_root_keys` later in another PR.
* CI
* Verified that this solves the issue with #3453
In principle, this chould be backported to the latest `testnet` branch.
=> Fix blob storage

linera-views/src/backends/lru_caching.rs
According to [style guidelines](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#naming-conventions), the proper variable names for values of `Option<Arc<Mutex<LruPrefixCache>>>` is
`lru_prefix_cache` or `cache`.
Rename fields and variables accordingly.
CI
=> [nit] some renaming in LRU cache

linera-chain/src/block.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-client/src/chain_listener.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs, linera-execution/src/unit_tests/system_tests.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/test_system_execution.rs, linera-execution/tests/wasm.rs, linera-service-graphql-client/src/service.rs
Simplify the code some more after #3513
* Move the definition of `OutgoingMessage` to `linera-execution`
* Use `OutgoingMessage` instead of `ExecutionOutcome` in the transaction tracker
`RawExecutionOutcome` is still use internally to `linera-execution` as a way to create messages, notably in `system.rs` (and in tests). We should probably also get rid of this concept at some point.
To be rebased on top of #3513
CI
This PR should not modify the protocol.
=> Refactor how outgoing messages are exported by linera-execution

linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-client/src/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/policy.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/system_execution_state.rs, linera-execution/src/transaction_tracker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/validator.rs, linera-storage/src/lib.rs
To make epoch changes scalable, we want to use events instead of messages (https://github.com/linera-io/linera-protocol/issues/365).
Remove the committee messages and add add `ProcessNewEpoch` and `ProcessRemovedEpoch` system _operations_ instead. The committee change operations on the admin change create events now, and the two new operations consume those events, i.e. verify that they exist, change the epoch and committees on the local chain, and create an `OracleResponse::Event` entry in the execution outcome.
Clients get notified about new epochs because they always follow/synchronize the admin chain and thus store the epoch change events locally. They will then run `process_inbox` which, in addition to incoming messages, looks for epoch change events, and includes the new operations …
=> Use events for adding and removing committees.

linera-sdk/src/test/validator.rs
Epoch changes were recently changed to use events (#3432), but the `TestValidator::change_resource_control_policy` was still trying to receive epoch change system messages instead of creating an operation to process the new epoch.
Use the new `SystemOperation::ProcessNewEpoch` to update the chains to use the new epoch, and skip updating the admin chain because it fails to try to process the same epoch twice.
Tested with a rebased version of the tests in #3509. The tests stop working after #3432 but pass again after this PR.
- These changes follow the usual release cycle, because it fixes an issue with SDK that is not present in any released version.
=> Fix epoch update in `TestValidator::change_resource_control_policy`

examples/gen-nft/src/service.rs, examples/llm/src/service.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/wasm/runtime_api.rs, linera-sdk/src/service/runtime.rs, linera-sdk/src/service/test_runtime.rs, linera-sdk/wit/service-runtime-api.wit
The `fetch_url` runtime API was superseded by the `perform_http_request` runtime API, which is more feature complete and has better safety mechanisms. Therefore the old API should be removed.
Remove the old API and update the examples to use the new API.
SDK soon, because this changes the WIT interface.
- Closes #3542 
=> Remove obsolete `fetch_url` serviece runtime API

linera-chain/src/unit_tests/chain_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/policy.rs, linera-execution/src/test_utils/mock_application.rs, linera-execution/tests/fee_consumption.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_schema.graphql
HTTP requests can take a long time to complete, or attempt to stay open indefinitely. This should not be allowed because it may stall a chain.
Add a `http_request_timeout` policy to `ResourceControlPolicy`, and configure all HTTP requests to use that timeout.
Wrote some [tests](https://github.com/jvff/linera-protocol-archive/compare/95da70cabb..test-http-timeouts-p1) out of this branch, possibly to be added to #3509.
- Backporting is not possible but we may want to deploy a new `devnet` and `testnet` and release a new
SDK soon, because this contains backwards incompatible changes to the chain state.
- Closes #3522 
=> Add timeouts for HTTP requests

.github/workflows/rust.yml, configuration/compose/validator.toml, configuration/k8s-local/validator_1.toml, configuration/local/validator_1.toml, configuration/local/validator_2.toml, configuration/local/validator_3.toml, configuration/local/validator_4.toml, linera-rpc/src/config.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/cli_wrappers/local_net.rs, linera-service/src/server.rs, scripts/deploy-validator.sh
The metrics host will always be the same as the internal host, because the internal host will actually have the metrics endpoint that the server pulls from. If we ever change to a strictly push model, this might change, but I don't see that changing anytime soon.
Remove metrics host as it's not necessary
CI
=> Remove metrics_host

linera-core/src/client/mod.rs, linera-core/src/unit_tests/test_helpers.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/resources.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/test_execution.rs
As we keep adding functionality to the contract runtime, more and more "system" execution state functions are called through contracts, and the distinction between the two error types becomes less meaningful and sometimes even an obstacle (e.g. for https://github.com/linera-io/linera-protocol/pull/3546). Several variants are duplicated between the two. The many levels of nesting also make some tests more difficult to read.
Merge `SystemExecutionError` into `ExecutionError`, deduplicating and removing unused variants.
CI
=> Merge `SystemExecutionError` into `ExecutionError`.

linera-chain/src/unit_tests/chain_tests.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/unit_tests/runtime_tests.rs, linera-execution/src/wasm/runtime_api.rs, linera-sdk/wit/service-runtime-api.wit
Services running as oracles should run in bounded time. Since adding a timeout was not possible, the Wasm runtimes' metering services need to be used. The goal is to instrument the services in order to force them to periodically check if they have exceeded their execution time, and stop executing if they have. For this to be possible, the runtime needs a new function to be called from the services.
Add a `ServiceRuntime::check_execution_time` runtime API for services, and export it to the WIT interface. Add an optional `deadline` to the `SyncRuntimeInternal` to be used by services running as oracles. When the new runtime API is called, return an error if it is has passed its deadline.
A unit test was added to check that execution stops early.
- Nothing to do / These changes follow the …
=> Add runtime API for services to stop executing on timeout

CLI.md, linera-base/src/data_types.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/client_options.rs, linera-execution/src/runtime.rs, linera-execution/tests/contract_runtime_apis.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/contract/conversions_to_wit.rs, linera-sdk/wit/contract-runtime-api.wit, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/node_service.rs
Chains may want to prevent applications from performing HTTP requests.
This adds a new field to ApplicationPermissions that controls which applications can make HTTP requests. If the calling application is not on the list, the call will fail with an UnauthorizedApplication error.
Unit tests were added that exercise new functionality.
- Closes #3531 
=> Add configurable permissions for making HTTP requests

linera-execution/src/runtime.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/fee_consumption.rs
HTTP oracles is a desired feature by partners and developers. It should be available on the next testnet.
Now that HTTP oracles have minimal limits, fees and permission configurations, allow it to be included in the next build.
Tested by running the "How-To Perform HTTP Requests" example's integration tests without enabling the `unstable-oracles` feature, and ensuring only the tests for services running as oracles fail:
https://github.com/jvff/linera-protocol-archive/commit/1a28b4d166b9b011e664b94117329d0fdb1bda44
SDK soon, because this requires the fees, limits and permissions that were recently merged and are breaking changes.
- Closes #3525 
- [reviewer …
=> Stabilize HTTP oracles

linera-core/src/join_set_ext.rs
On the Web, `reap_finished_tasks` busy-loops until all tasks are complete.  However, since it blocks the thread, this prevents any tasks from completing, leading to a deadlock.
Following the native implementation, optimistically reap only those tasks that have already finished, not blocking on any tasks that haven't.
Being manually tested with the `hosted-counter` example.
=> `linera_core::join_set_ext`: fix deadlock

linera-chain/Cargo.toml, linera-chain/src/unit_tests/chain_tests.rs, linera-core/Cargo.toml
On `main`, running `cargo test -p linera-chain` fails to compile. That happens because some tests assume that the `linera-execution/unstable-oracles` feature flag was always enabled. CI failed to catch this because all tests are currently being executing with that feature enabled.
Only include those tests if a new `linera-chain/unstable-oracles` feature is enabled, which is enabled if `linera-core/unstable-oracles` is enabled.
Ran `cargo test -p linera-chain` and `cargo test -p linera-chain --features unstable-oracles` manually.
CI was not updated because the current plan is to remove `unstable-oracles` in the next few days (#3524).
- Nothing to do, because this only affects tests.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checkl …
=> Fix inclusion of service-as-oracle tests in `linera-chain`

linera-execution/src/runtime.rs
The `BaseRuntime` trait was previously implemented for both `SyncRuntimeHandle` and `SyncRuntimeInternal`, but the implementation for the handle would just redirect all calls to the internal implementation. This is not necessary, because the internal type does not need to be used outside the module.
It also limits the flexibility of the internal type, since it has to implement the whole trait, instead of only what it needs to. This happened when trying to differentiate the implementation for the `ContractSyncRuntimeHandle` from the `ServiceSyncRuntimeHandle`.
Merge the implementations to remove the indirection.
CI should catch any regressions caused by this internal refactor.
- Nothing to do, because this is just an internal refactor.
- [reviewer …
=> Remove `BaseRuntime` implementation indirection

Cargo.lock, examples/amm/README.md, examples/crowd-funding/README.md, examples/social/README.md, linera-service/Cargo.toml, linera-service/src/node_service.rs
After #3217, we do not need to introspect service queries to applications.
* Minimize assumptions about application APIs. After this PR, we only assume UTF8 bytes as input and JSON as output.
* Simplify requests handlers
* Somehow this revealed silently failing queries in our README files. Also fix that.
Note the assumption on JSON outputs could be relaxed if we stopped returning the hash of the certified block and return the query response instead. However, this is a breaking change so this should be a separate PR.
CI
=> Simplify service requests

linera-chain/src/inbox.rs, linera-chain/src/outbox.rs, linera-views/benches/reentrant_collection_view.rs, linera-views/src/batch.rs, linera-views/src/context.rs, linera-views/src/views/bucket_queue_view.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/log_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/queue_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/register_view.rs, linera-views/src/views/set_view.rs, linera-views/src/views/unit_tests/views.rs, linera-views/tests/hashable_tests.rs, linera-views/tests/random_container_tests.rs, linera-views/tests/store_tests.rs, linera-views/tests/views_tests.rs
The `create_test_memory_context` had been reduced to a wrapper for `MemoryContext::new_for_testing`.
We can eliminate it.
The replacement is done in a straightforward way.
The CI.
Not relevant.
None.
=> Eliminate the `create_test_memory_context`.

linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs, linera-execution/tests/test_execution.rs
As of https://github.com/linera-io/linera-protocol/pull/3513, `RawExecutionOutcome` and `RawOutgoingMessage` are not really needed anymore.
Remove them.
In the first commit, their usage in production is replaced by directly creating `OutgoingMessage`s. The `linera-execution` tests still passed, so the behavior didn't change.
In the second commit, their usage is also removed from the tests.
Existing tests were updated.
=> Remove `RawExecutionOutcome` and `RawOutgoingMessage`.

linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/unit_tests/client_tests.rs
It's confusing that `validate_block` returns `None` if the block was already voted for.
(See: https://github.com/linera-io/linera-protocol/pull/3546#discussion_r2003147326) 
Split the method: First do basic validation and return `Skip` if already voted for.
Then try to load the blobs.
(https://github.com/linera-io/linera-protocol/pull/3546#discussion_r2003069161 is also addressed here.)
This is only a refactoring.
- Addressing review comments from https://github.com/linera-io/linera-protocol/pull/3546.
=> Split block proposal methods in the worker.

CLI.md, linera-client/src/client_options.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs
A reading of `ResourceControlPolicy` in `policy.rs` and `ResourceControlPolicy` in `client_options.rs` revealed some discrepancies which are most likely oversights.
Fixes #3532 
Implement the needed insert and rename `http_allow_list` as `http_request_allow_list`.
The CI.
Normal release process.
Closes #3532.
=> Add missing options from ResourceControlPolicy.

configuration/compose/validator.toml, linera-rpc/src/config.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/cli_wrappers/local_net.rs, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/pyroscope_server.rs, linera-service/src/server.rs
Right now for local runs, 100 samples per second seems to be a bit too aggressive and causes some local issues (connections fail, etc)
Decrease local runs to have 10 samples per second, and make that part of the config
Ran locally, was significantly seeing connection failures before, now they're gone
=> Use pyroscope sample rate as config parameter

Cargo.lock, Cargo.toml, examples/Cargo.lock, examples/Cargo.toml, examples/counter-no-graphql/Cargo.toml, examples/counter-no-graphql/README.md, examples/counter-no-graphql/src/contract.rs, examples/counter-no-graphql/src/lib.rs, examples/counter-no-graphql/src/service.rs, examples/counter-no-graphql/src/state.rs, linera-service/Cargo.toml, linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/linera_net_tests.rs
GraphQL is used all over the Linera code. This led to the question whether we can program a Linera application without GraphQL. This PR demonstrates that it is possible.
* Introduce an application `counter-no-graphql` that works without GraphQL but still uses the `linera-sdk`.
* The `ApplicationWrapper` has been restructured to separate between json queries and GraphQL queries.
This PR led to some further questions to address in next PRs:
* The `counter-no-graphql` application does not use GraphQL, but it still typed. We should also have a `counter_untyped` for which `execute_operation` takes a `Vec<u8>` and does not use the `linera-sdk` macros.
* Different serializations are being used in the code: `bcs::to_bytes` and `serde_json::to_vec`. No effort was made to …
=> Introduce one smart contract without GraphQL and the corresponding end-to-end test.

.github/workflows/rust.yml, linera-chain/Cargo.toml, linera-chain/src/unit_tests/chain_tests.rs, linera-core/Cargo.toml, linera-core/src/unit_tests/wasm_client_tests.rs, linera-execution/Cargo.toml, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/fee_consumption.rs, linera-sdk/Cargo.toml, linera-service/Cargo.toml
Running services as oracles is required for executing most HTTP requests due to non-deterministic answers. Now that running services as oracles is charged for and limited, it's possible to mark it as stable.
Remove the `unstable-oracles` feature.
- These changes follow the usual release cycle, since it adds a new feature to be included in the next testnet.
- Closes #3524 
=> Stabilize service as oracles

linera-rpc/binary_formats.yaml
Tracking binary formats is important but the corresponding file is buried in the directory tree and looks like just another test snapshot.
* Create a symlink to make the file more visible
This more stable link could also be used later for `serde_generate`
Nothing to do
=> (nit) add symlink to make binary formats more discoverable

linera-views/src/backends/lru_caching.rs
The LRU caching is very minimal and can be extended.
The PR #2500 implements several improvements to the LRU caching,
but it proved impossible to review. Splitting the changes more atomically
might be mergeable into main.
* The `Option<Vec<u8>>` is replaced by a `CacheEntry` that encodes the status if missing.
* The lifetime is removed from the `fn query`, but that does not matter since it was cloned just after.
* The cache success/fault is split with read_value/contains_key.
The CI.
None.
=> Introduce the caching of `contains_key` operations.

linera-core/src/value_cache.rs
This is a bit of a workaround to some of the inefficiencies we see on ScyllaDB, but also doesn't hurt to have a slightly bigger cache, as the hit rate of it seems to be pretty good.
Increase value cache size
CI + deployed a few networks with this
=> Increase value cache size

linera-chain/src/chain.rs
During block execution we keep track of the final block's size, but we are not taking into account the collection of created blobs.
Take them into account.
Writing a test for this will be very complicated. I created https://github.com/linera-io/linera-protocol/issues/3613 for this.
=> Take blobs into account for block size computation.

linera-client/src/benchmark.rs, linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-execution/src/execution.rs, linera-execution/src/lib.rs, linera-execution/tests/test_system_execution.rs, linera-sdk/src/test/chain.rs, linera-service/src/node_service.rs
While migrating to a newer nightly version of Rust (see #3622), some new lints were suggested. One of them was that the `Operation` type had unbalanced variants. More specifically, the `User` variant was small and had a heap allocation with the bytes for the user operation, while the `System` variant had a large `SystemOperation` type inside.
Apply the suggested fix by the linter to move the `SystemOperation` to the heap by boxing it.
- Nothing to do, because this is an internal refactor.
=> Reduce size of `Operation` type

examples/amm/src/contract.rs, examples/fungible/src/contract.rs, examples/gen-nft/src/contract.rs, examples/matching-engine/src/contract.rs, examples/native-fungible/src/contract.rs, examples/non-fungible/src/contract.rs, linera-base/src/ownership.rs, linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs
We are duplicating this logic in most examples. Probably a sign!
* Make a function `check_account_permission` available in the SDK
* Fix weird permission test in NFT apps
CI
=> Create function "check_account_permission" to remove duplicated code

linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-chain/src/chain.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-chain/src/unit_tests/inbox_tests.rs, linera-client/src/client_options.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/worker.rs, linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/mod.rs, linera-execution/src/test_utils/system_execution_state.rs, linera-execution/src/unit_tests/applications_tests.rs, linera-execution/src/unit_tests/system_tests.rs, linera-execution/tests/contract_runtime_apis.rs, linera-sdk/src/test/chain.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs, linera-service/src/node_service.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
Attempts to use different types for `ApplicationId<A>` from `ApplicationId<()>` show that the problem is more complicated than we thought. In the meantime, we have the "worst of both worlds".
* Remove the alias `UserApplicationId` and enjoy the short names.
* Rename `UserApplicationDescription` into `ApplicationDescription`.
CI
=> remove alias `UserApplicationId` and rename `UserApplicationDescription`

examples/native-fungible/src/contract.rs, examples/native-fungible/tests/transfers.rs, linera-base/src/identifiers.rs, linera-base/src/unit_tests.rs, linera-chain/src/test/mod.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/benchmark.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/benches/client_benchmarks.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/data_types.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution.rs, linera-execution/src/system.rs, linera-execution/src/unit_tests/system_tests.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/test_system_execution.rs, linera-indexer/example/tests/test.rs, linera-rpc/src/grpc/conversions.rs, linera-sdk/src/contract/test_runtime.rs, linera-service-graphql-client/tests/test.rs, linera-service/benches/transfers.rs
Address nits from #3625.
Add `const CHAIN` and use that instead of `fn chain()`. 
Use `AccountOwner::from` (instead of the variant directly) for consistency.
CI
=> Cleanups after #3625

linera-base/src/identifiers.rs, linera-chain/src/block.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-chain/src/unit_tests/data_types_tests.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-explorer/src/components/Block.test.ts, linera-explorer/src/components/Blocks.test.ts, linera-explorer/src/lib.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs
We are planning to optimize the client so it does not download all message sender chains (https://github.com/linera-io/linera-protocol/issues/3630). This requires adding data to the `Block` structure itself.
Add the new data to the blocks now, so the optimization is a client-side change and can be added even after the next testnet launch.
The tests were updated to expect the new entries.
- Closes #3630.
=> Add links to previous blocks with the same message recipients.

linera-base/src/identifiers.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/worker.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/system_execution_state.rs, linera-rpc/tests/format.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/block.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/node_service.rs
As of https://github.com/linera-io/linera-protocol/pull/3432 we are not using system channels anymore.
Remove the `SystemChannel` type and any system channel-specific logic, in particular the "off-chain subscription handling".
The `social` example tests make sure that _user_ pub-sub channels still work.
=> Remove system channels.

linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/graphql.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/system_execution_state.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs
`SystemMessage::Subscribe` and `Unsubscribe` were only used for system channels, which are now gone.
Remove them, and the `subscribers` collection in the system execution state view.
CI
- System channels were removed in https://github.com/linera-io/linera-protocol/pull/3634.
=> Remove unused `Subscribe` and `Unsubscribe` messages.

linera-chain/src/chain.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-execution/src/execution.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/transaction_tracker.rs, linera-execution/src/unit_tests/runtime_tests.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/revm.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/test_system_execution.rs, linera-execution/tests/wasm.rs
There are several methods in the block execution code with too many arguments (according to Clippy), and some with redundant arguments.
Remove the redundant arguments; move more information into the `TransactionTracker`; add `TransactionTracker` test constructors to deduplicate some code.
CI
=> Simplify block execution code; remove redundant arguments.

.github/workflows/docker.yml
Changes to the Rust toolchain can break the Linera Docker image.
Run the Docker workflow when there is a change to the Rust toolchain.
=> Run Docker workflow on toolchain changes.

linera-execution/src/test_utils/solidity.rs, linera-sdk/src/contract/mod.rs
There are a few ways to improve the developer experience of apps on Linera.
* Add the printing of the `Vec<u8>` that cannot be deserialized in `execute_operation` and `instantiate`. This is done in the same way as for `handle_query`.
* Print the actual compilation error in `get_bytecode_path` if it fails.
In both cases, the error message is built only if something goes wrong.
The CI.
Normal release schedule.
None.
=> Improve the developer experience of the `linera-sdk` and the solidity compiler.

linera-chain/src/chain.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-execution/src/resources.rs
The current way of computing the block size during execution is complicated (e.g. due to ULEB128 sequence lengths) and doesn't fully take into account the new block structure anyway: It computes the size of `ExecutedBlock`, not `Block`.
Remove the ULEB128 sequence length size tracking.
CI
The block size limit test still passes, because the small transaction that is used to push it past the size limit is bigger than the few sequence length bytes we are not taking into account, plus the hashes in the `BlockHeader`.
- Closes #3652.
=> Ignore small bounded values in block size limit.

.github/workflows/docker-compose.yml, README.md
Docker as a file name here is a bit ambiguous, and this tests only docker compose
Change name to `docker-compose` instead
CI
=> docker -> docker-compose

linera-client/src/storage.rs
Other databases support this (including dual store, which uses `RocksDB`)
Add support for namespace not to be provided, and use default in that case, aligning this with other databases implementation
CI
=> Support default namespace on RocksDB

linera-base/src/crypto/hash.rs, linera-base/src/data_types.rs
EVM applications should have a hash that is of length 20. We can achieve that by setting the last 12 bytes to 0.
The changes are done to the computation in the hash in the `data_types.rs`. It requires matching the `ApplicationDescription` for the blob type.
In that case, we need to deserialize the description in order to obtain the module_id and whether they are EVM or not.
It has to be done in two places.
The CI should be doing the adequate test.
Normal testing release.
None.
=> Change the way that `UserApplicationId` is computed for `ApplicationDescription` of EVM smart contracts.

examples/meta-counter/src/contract.rs, linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/revm.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs, linera-execution/src/wasm/runtime_api.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs, linera-sdk/wit/contract-runtime-api.wit, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs
The system needs to enforce that events are never overwritten anyway. It makes them much harder to use for applications if the applications need to keep track of that.
Replace the general `key: Vec<u8>` with `index: u32`. Instead of the application, the system now chooses the index, and always uses the next available number.
The tests have been updated, and already use system events.
The user application events will be tested more thoroughly later, when we have an example (probably `social`) that uses them.
=> Instead of a key, use an incrementing `index` for events.

CLI.md, linera-client/src/client_options.rs, linera-client/src/storage.rs, linera-indexer/lib/src/rocks_db.rs, linera-indexer/lib/src/scylla_db.rs, linera-service/src/proxy/main.rs, linera-service/src/server.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/store.rs, linera-views/tests/views_tests.rs
The current tracking is limited by the maximal size of the cache. This is a limited way to
control the size of the cache.
Two additional constraints are added:
* A maximal size of the total cache.
* A maximal size of individual entries in the cache.
* Those entries are added to the input parameters of all the relevant functions.
The CI.
None.
=> Add tracking of memory use in the caching.

examples/Cargo.lock, examples/Cargo.toml, examples/how-to/perform-http-requests/Cargo.toml, examples/how-to/perform-http-requests/README.md, examples/how-to/perform-http-requests/src/contract.rs, examples/how-to/perform-http-requests/src/lib.rs, examples/how-to/perform-http-requests/src/service.rs, examples/how-to/perform-http-requests/src/test_http_server.rs, examples/how-to/perform-http-requests/src/unit_tests/contract.rs, examples/how-to/perform-http-requests/src/unit_tests/service.rs, examples/how-to/perform-http-requests/tests/http_requests.rs, examples/how-to/perform-http-requests/tests/http_server/mod.rs, linera-base/src/crypto/secp256k1.rs, linera-sdk/src/test/mod.rs, linera-service/tests/readme_test.rs
Performing HTTP requests from applications is an important feature for Linera. There are a few different ways for applications to perform them, and there are tradeoffs between these ways. Therefore, this feature should be documented and a "How-To" example demonstrating how to use and test the feature would be useful.
Add an example that performs HTTP requests in all different ways, and test them.
Unit and integration tests were added to test not just the application, but also to serve as testing examples and to also test the HTTP allow-list.
- Nothing to do, because this is just a new example being added to the repository.
=> Add a "How-To" example for performing HTTP requests

flake.lock
`flake.nix` is too old to contain the compiler toolchains we use now.
Bump it.
Tested locally for build.
=> `flake.lock`: update for newer Rusts

linera-base/src/abi.rs, linera-sdk/src/abis/evm.rs, linera-sdk/src/contract/mod.rs, linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs, linera-sdk/src/test/block.rs
The EVM apps do not have a type associated with them, instead, the `Operation` / `Response` are `Vec<u8>`.
Using BCS for them is not adequate as it leads to some serialization followed by deserialization situations which
are suboptimal.
* The `{de}serialization_{operation,response}` is introduced in the `ContractAbi`.
* They use strings as error types. Using `bcs::Error` is not the point. And `anyhow::Error` is for tests and binaries.
* There is a standard implementation in the trait, which is overloaded in the `EvmAbi`.
* The use of BCS serialization is removed in the place of the code where it was and replaced by the introduced functions. They `unwrap()` as the use case of those functions always panics in case of errors.
* Whenever a serialization error occurs, …
=> Introduce the `{de}serialize_{operation,response}` to the ContractAbi.

linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/worker.rs
Resolve suspicious `ERROR`s in logs
* Do not drop notifiers silently if the query may succeed
* The error is still useful and should never happen.
Run tests locally => no more errors
=> Do not drop notifiers silently if the query may succeed

linera-chain/src/chain.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-sdk/src/test/chain.rs
In the future we want to cache execution outcomes, i.e. the `ExecutionStateView` associated with a particular state hash, but not the rest of `ChainStateView`.
Separate the first part of block execution, where `ExecutionStateView` is updated, from the rest, where the state hash, outboxes and other parts of the `ChainStateView` are modified.
CI
- 
=> Separate block execution proper from updating outboxes etc.

Cargo.lock, linera-base/src/vm.rs, linera-execution/src/revm.rs, linera-execution/src/test_utils/solidity.rs, linera-execution/tests/revm.rs, linera-sdk/src/abis/evm.rs, linera-service/Cargo.toml, linera-service/tests/linera_net_tests.rs
We use a hacky system for the processing of the query in `handle_query` of REVM. We want to streamline the
mechanism.
The code is adapted from a separate branch that implements the calls `EVM->{EVM,Wasm}` and `Wasm->EVM`
and the changes reflect that.
* The `EvmQuery` is introduced as a type for the input of queries, which reflects what it is.
* The `EvmQuery` is introduced in `linera-base` instead of `linera-execution` since this would force a dependency on `linera-execution` for `linera-sdk`.
* The tests `test_fuel_for_counter_revm_application` and `test_evm_end_to_end_counter` are simplified accordingly.
* The Query type of `EvmAbi` is changed to `EvmQuery`.
No tests are added, CI suffices.
Normal release schedule.
None.
=> Implement the `EvmQuery` for the EVM contracts

linera-chain/src/unit_tests/chain_tests.rs
This test fails on my laptop otherwise.
Increase the time available.
CI
=> fix test_service_as_oracles on slower machines

Cargo.lock, Cargo.toml, examples/Cargo.lock, examples/Cargo.toml, examples/call-evm-counter/Cargo.toml, examples/call-evm-counter/src/contract.rs, examples/call-evm-counter/src/lib.rs, examples/call-evm-counter/src/service.rs, linera-sdk/Cargo.toml, linera-sdk/build.rs, linera-sdk/src/abis/mod.rs, linera-sdk/src/linera_base_types.rs, linera-service/Cargo.toml, linera-service/tests/linera_net_tests.rs
The EVM smart contract have the `EvmAbi`. A test is needed to demonstrate on how to call them from Wasm.
The following changes are made:
* The `EvmQuery` is added to the `linera_base_types`.
* The `call-evm-counter` is added, which is a non GraphQL app.
* A demonstration of query and mutation is introduced in the end-to-end test.
There are some changes to the `linera-sdk`:
* The `EvmAbi` should not be protected by a `revm` feature as the fact that we use REVM is incidental.
* The `call-evm-counter` calling for the `revm` feature forces the `revm` feature by default which is unfortunate.
This is the first example of a query to a smart contract that leads to another `query_application` being created in the end-to-end test.
The introduced test demonstrates the functionality.
Normal release …
=> Implement the end-to-end test that calls an EVM smart contract.

linera-client/src/config.rs, linera-core/src/chain_worker/config.rs, linera-core/src/unit_tests/test_utils.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-execution/src/committee.rs, linera-sdk/src/test/validator.rs, linera-service/src/server.rs
Fallback chain owners (validators) will be done in a separate client process.
Remove unused (and not planned) account key from validator config.
CI
=> Remove unused account key from validator config

linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-chain/src/chain.rs, linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-execution/src/lib.rs, linera-execution/src/policy.rs, linera-execution/src/system.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-storage/src/lib.rs
The EVM Bytecode has only contract, not a service, or if there is a service, it is the same as the contract.
This leads to a duplication of the blobs that is unfortunate.
The changes are made accordingly and this leads to a relatively nice restructuration:
* The pair `(Blob, Blob)` are replaced by `Vec<Blob>`.
* The `load_contract/load_service` are restructured to accedd the `{contract,service}_bytecode_blob_id` from the application description.
* When calling an EVM smart contract, the service is provided but it has no impact on the running.
Coauthored by @afck
The CI
Normal release scheme.
None.
=> Introduce the `EvmBytecode` as `BlobType`.

linera-chain/src/chain.rs
The message counter currently counts how many `Vec<OutgoingMessage>` vectors there are in a block, which is the number of transactions.
Count the number of messages instead.
(Edit: This isn't actually used in Linera itself at all, but it it exposed as part of the chain state, e.g. for block explorers.)
The change is small and only affects metrics, so there is no dedicated test.
=> Count messages, not transactions, in the outgoing message counter.

.github/workflows/release.yml
We'd like to be able to tag git commits on network branches (i.e. `testnet_archimedes`) and trigger new releases to notify validators of hotfixes.
Add a workflow which pattern matches on git tags and triggers releases.
Need to test manually.
=> Network release workflow.

linera-views/src/backends/memory.rs
This PR fixes a typo in the MemoryStoreError enum variant name, changing "StoreAlreadyExist" to "StoreAlreadyExists" for consistency and correctness.
The change affects two locations:
1. In the error return statement in the sync_exists method
2. In the enum definition itself
This ensures consistent naming throughout the codebase and improves code readability.
=> Fix typo in MemoryStoreError enum variant name

linera-chain/src/block.rs, linera-chain/src/certificate/confirmed.rs, linera-chain/src/certificate/generic.rs, linera-chain/src/certificate/lite.rs, linera-chain/src/certificate/mod.rs, linera-chain/src/certificate/timeout.rs, linera-chain/src/certificate/validated.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-chain/src/manager.rs, linera-chain/src/test/mod.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-chain/src/unit_tests/data_types_tests.rs, linera-client/src/benchmark.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/src/grpc/conversions.rs, linera-sdk/src/test/block.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs
Andreas noticed that we're unnecessarily hashing `ConfirmedBlock` before creating a `Vote` for it. Intuitiveily it shouldn't be necessary - `ConfirmedBlock` already contains `Hashed<Block>` and when creating a vote for it we're adding the certificate's kind as well.
Change the code to operate on `T: CertificateValue` rather than `Hashed<T>`. All `CertificateValue` impls are required now to also have a `fn hash() -> CryptoHash`.
CI
=> Pass CertificateValue to Vote::new. Get rid of extra hashing.

linera-client/src/chain_listener.rs
The `select!` statement in the chain listener is very long and hard to read. It is also counterintuitive that we set `timeout` to "now" to process the inbox. (Thank Mateusz for pointing this out!)
Extract processing the inbox from the code, and call the new function instead of setting the timeout to now.
To remove some more code from the macro, filter the admin chain notifications using `StreamExt::filter`.
CI
- 
=> Extract some logic from `select` in the chain listener.

examples/how-to/perform-http-requests/tests/http_requests.rs, linera-chain/src/lib.rs, linera-core/src/worker.rs, linera-sdk/src/test/block.rs, linera-sdk/src/test/chain.rs, linera-sdk/src/test/mod.rs
The integration tests for the HTTP Requests How-To example (#3509) used the `#[should_panic]` attribute for testing failures. However, as [pointed out during review](https://github.com/linera-io/linera-protocol/pull/3509#discussion_r1986888526), these are quite broad and may lead to mistakes. Being able to assert the exact error leads to better tests and a better example for external developers.
Add `try_query`, `try_graphql_query` and `try_graphql_mutation` helper methods to the `ActiveChain` test interface. Use the new methods to replace usages of `#[should_panic]` with error type assertions.
To reduce boilerplate code, a `WorkerError::expect_execution_error` test helper method was added, that dives into the internal `ExecutionError` stored inside a `WorkerError`.
CI should catch any …
=> Replace `#[should_panic]` with assertions in HTTP example tests

linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/value_cache.rs, linera-core/src/worker.rs
Currently chain workers executes almost every block twice, both in the client's local node and the validators: Once when handling the proposal, and then again when handling the confirmed block.
Cache the `ExecutionStateView` when handling the proposal, and use the cached value for the confirmed block.
This is only done for blocks where no pub-sub channel subscribers are added or removed. (But these will be replaced by event streams soon anyway.)
The second part of https://github.com/linera-io/linera-protocol/issues/1401, caching intermediate states when _staging_ a block, is not part of this PR yet.
Most existing tests will use this, so CI would fail if it broke anything.
I locally added some logging to verify that a client test (`test_re_propose_locked_block_with_blobs`) has a lot of …
=> Cache execution states.

kubernetes/linera-validator/grafana-dashboards/linera/storage.json, linera-chain/src/block.rs, linera-chain/src/certificate/lite.rs, linera-chain/src/data_types.rs, linera-chain/src/unit_tests/data_types_tests.rs, linera-client/src/chain_listener.rs, linera-core/benches/client_benchmarks.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-explorer/src/components/Block.test.ts, linera-explorer/src/components/Block.vue, linera-explorer/src/components/Blocks.test.ts, linera-explorer/src/components/Blocks.vue, linera-indexer/example/tests/test.rs, linera-indexer/lib/src/indexer.rs, linera-indexer/lib/src/plugin.rs, linera-indexer/lib/src/service.rs, linera-indexer/plugins/src/operations.rs, linera-rpc/tests/format.rs, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql, linera-service-graphql-client/src/service.rs, linera-service/src/node_service.rs, linera-service/src/proxy/main.rs, linera-service/tests/linera_net_tests.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
We are not using the hash of `ConfirmedBlock` anymore, only the `Block` hash.
Make `ConfirmedBlock` not `BcsHashable`, remove uses of `Hashed<ConfirmedBlock>`.
CI
=> Make `ConfirmedBlock` not `BcsHashable`.

linera-service/src/proxy/main.rs
Useful for debugging and testing certain applications with `linera net up`
Just use environment variables.
CI
```
cargo build --bins
export LINERA_PROXY_RECV_TIMEOUT=0
target/debug/linera extract-script-from-markdown README.md | bash -e -x   # <-- fails with timeouts
```
These changes should be backported to the latest `testnet` branch
=> allow controlling proxy timeouts from the environment

CLI.md, linera-client/src/client_options.rs, linera-indexer/example/tests/test.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/main.rs, linera-service/src/node_service.rs, linera-service/src/schema_export.rs
Tests currently rely on a port finder to find an available port for the node service to listen on. However, this prevents the integration tests to run in parallel because the tests race to find available ports.
Change the node service to support using port `0` when binding, allowing the operating system to assign an arbitrary available port. The tests must then read the node service's output until it finds the port number.
Manually ran the integration tests, and then ran them in parallel.
- These changes follow the usual release cycle, because this changes the `linera service` CLI command in a non-backwards compatible way. Now not specifying the port forces the node service to listen on an arbitrary port, not the fallback `8080` port.
- [reviewer …
=> Allow the node service to select arbitrary ports

linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs
In https://github.com/linera-io/linera-protocol/pull/3692 I added basic user events, but subscriptions are not implemented yet. However, I optimistically added the contract runtime functions for subscriptions in that PR, too, so they are now user-visible but don't work yet.
Remove them from the contract runtime, so that if we release a new SDK, they don't show up yet.
CI
- Reverts a few lines of https://github.com/linera-io/linera-protocol/pull/3692.
=> Remove event subscription functions from contract runtime.

linera-client/src/chain_listener.rs, linera-client/src/unit_tests/chain_listener.rs, linera-faucet/server/src/lib.rs, linera-service/src/node_service.rs
The chain listener is currently one big complex loop. It is about to get more complicated when we add event stream subscriptions.
Split the loop into smaller methods. Move some of the local variables as fields into `ChainListener`. Introduce a `ChainClientListener` that tracks the local variables that are specific to a single chain.
CI
=> Refactor the chain listener

linera-base/src/identifiers.rs
Nicer output for `linera storage list_blob_ids`
* Use the derived `Debug` to display `BlobType`s without quotes
* Keep using `serde_json` for parsing (as opposed to importing `clap` or other crates)
CI
=> display BlobTypes without quotes

linera-storage/src/db_storage.rs
Help with #3665
* Create a key prefix for block exporters (each identified by a `u32`)
* Create a method `block_exporter_context` in `linera_storage::DbStorage`
CI
=> Create key space for block exporters

.github/workflows/rust.yml, CLI.md, docker/compose-server-init.sh, docker/proxy-init.sh, docker/server-init.sh, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs, linera-service/src/server.rs, linera-service/src/storage.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
Minimize boilerplate + clean up names
follows #3724
* (light) refactor how `--config` is handled, notably making it a global option
* create a trait `RunnableWithStore` so that the database command can be written in a single match.
* `linera storage initialize` now takes a genesis config (similar to `linera-server initialize` which could be killed next)
* a few minor code improvements
CI
=> Create trait `RunnableWithStore` to simplify the database tool

linera-storage/src/db_storage.rs
https://github.com/linera-io/linera-protocol/pull/3722 and https://github.com/linera-io/linera-protocol/pull/3729 were merged without rebasing, breaking the build.
Move `block_exporter_context` to the right `impl`.
CI
=> Fix build.

linera-chain/src/chain.rs, linera-chain/src/outbox.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-views/src/views/bucket_queue_view.rs
The `BucketQueueView` allows to use queues more efficiently.
It is known that using Queues on Key-Value stores is kind of an antipattern for KeyValue stores.
Grouping entries into buckets can reduce this problem.
The problem is that grouping increases the memory cost and exposes to possible Out Of Memory. Thus we did the following:
* For `QueueView` with `BlockHeight` being the type, we use a bucket size of 1000 since BlockHeight is just 8 bytes.
* For `QueueView` with `TimestampedBundleInInbox` we  use a bucket size of 100 since this type is essentially 4 Cryptohashes, a few number and a channel name which can be long but not too long.
* For `QueueView` with `MessageBundle` no change is made as this type can be very large.
It is to be pointed out that `BucketQueueView` has two …
=> Use `BucketQueueView` in the protocol.

docker/Dockerfile, docker/compose.sh, linera-service/src/cli_wrappers/docker.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs
While debugging the deadlock last week, it was evident that building an image for a local `kind` deployment in debug mode was not straight forward
Added `--build-mode` option to make this easier
Deployed locally, it works
=> Add --build-mode to net up --kubernetes

linera-client/src/benchmark.rs
Sometimes some of the tasks will lag behind for some reason and take longer to start. 
Have to investigate that, but for now let's log some information so we know not all tasks have started yet. Specially when dealing with a lot of chains, this is useful.
Run it, see messages printed
=> Print total tasks started on benchmark

linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
#3729 was not enough to re-use `run_with_storage` in the block exporter
* Move the new definition to the trait.
* Add the necessary associated type.
This is a little ugly but the alternative is to have different variants of the `Storage` trait depending on the app using it. This could be done later.
CI
=> make the block exporter context visible in the Storage trait

CLI.md, linera-service/src/linera/main.rs, linera-service/src/proxy/main.rs, linera-service/src/server.rs
The default limit is 512 blocking threads I believe. We might want more for benchmarks.
Add option to alter that number
CI + tested with benchmarks
=> Add max blocking threads option to client/server/proxy

linera-client/src/benchmark.rs
When you have a lot of chains, some of them might start sending requests before all tasks have started. This can cause the last tasks to struggle getting scheduled.
Synchronizing before starting should fix that
Will test on the benchmarks
=> All tasks wait before starting

linera-service/src/cli_wrappers/docker.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/linera/command.rs, linera-service/src/linera/net_up_utils.rs
This was a comment in the original PR, forgot to address before merging
Address comment and use enum
CI
=> Use enum for BuildMode

linera-storage/src/db_storage.rs
BCS serializing a `Vec<u8>` (blob bytes) for storage is redundant.
Store the bytes directly.
CI
- Closes #3749.
=> Avoid redundantly serializing blob bytes.

Cargo.lock, linera-base/src/task.rs, linera-client/Cargo.toml, linera-client/src/chain_listener.rs, linera-client/src/error.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/src/client/mod.rs, linera-faucet/server/Cargo.toml, linera-faucet/server/src/lib.rs, linera-service/src/linera/main.rs, linera-service/src/node_service.rs, scripts/linera_net_helper.sh
For https://github.com/linera-io/linera-protocol/issues/365 the chain listener will need to react to new block notifications on a publisher chain by processing the inboxes of all subscriber chains. That is difficult to implement with the current approach: we run a notification processing loop in a separate task for each chain.
Rewrite the chain listener so that there is a single top-level loop processing all events on all chains. That will make it easier to update chains based on events from _other_ chains.
`process_new_events` already does this, to update all non-admin chains for new epochs.
CI
- Preparation for #365.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-checkl …
=> Rewrite the chain listener as a single loop.

linera-chain/src/unit_tests/chain_tests.rs
`cargo test -p linera-chain` fails for me locally most of the time.
(Note that it only fails if I run _all_ the `linera-chain` tests. If it's _only_ `test_service_as_oracle_timeout_early_stop`, it passes.)
Multiply the durations in the test by 10, to make them less flaky.
With this change, `cargo test -p linera-chain` works for me, even in debug mode.
- Closes #3766.
=> Increase the durations in `test_service_as_oracle_timeout_early_stop`.

.github/workflows/dynamodb.yml, linera-service/src/cli_wrappers/local_net.rs, linera-service/src/storage.rs, linera-views/src/backends/dynamo_db.rs, spellcheck-dictionary.txt
We have not been using Localstack for several years and instead we use DynamoDB local.
Fixes #932 
The renaming is done in a straightforward way.
The CI
Normal release schedule.
None.
=> Remove the Localstack word from the source code

linera-service/tests/linera_net_tests.rs
`test_wasm_end_to_end_social_user_pub_sub` sometimes fails because it's not deterministic when the first block, with the `OpenChain` message, is created on `chain2`.
Synchronize after `open_and_assign`, so the `OpenChain` message is seen in the inbox right away.
The test passes for me now.
- These changes should be backported to the latest `testnet` branch.
=> Fix the `test_wasm_end_to_end_social_user_pub_sub` flakiness.

linera-faucet/Cargo.toml, linera-faucet/client/Cargo.toml, linera-faucet/server/Cargo.toml
Publishing the faucet crates fails because of missing metadata.
Add the metadata to `Cargo.toml`.
`scripts/test_publish.sh packages.txt test-registry`
- Port of https://github.com/linera-io/linera-protocol/pull/3778.
=> Add missing metadata so crates can be published. (#3778)

examples/how-to/perform-http-requests/README.md, linera-service/tests/readme_test.rs
The README test for the How To Perform HTTP Requests example was failing in CI, but not locally. After investigating the issue, the cause seems to be a race condition by running `cargo run --bin test_http_server &` in the background. This command didn't immediately start the test HTTP server, because it had to be built first, and that meant that on some computers (like in the CI) it could end up starting too late.
Build the `test_http_server` binary in the foreground, so that the `cargo run` command in the background is guaranteed to start the test HTTP server right afterwards.
CI now passes, whereas it previously failed without this fix.
- Nothing to do, because this only refactors a step in the README.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBU …
=> Fix How To Perform HTTP Requests readme test in CI

linera-client/src/client_context.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs
When benchmarking, it's better to not have chain creation blocks having to be executed in the middle of the benchmark. So we might as well add a confirmation so that we can get all the processes ready, and then start them as we please.
Add confirmation to start the benchmark, after preparing.
Ran this a few times already while benchmarking.
=> Ask confirmation to start benchmark

CLI.md, linera-service/src/linera/command.rs
If there is a default value, `clap` automatically adds that to the help text. (See `CLI.md`.)
Remove the redundant comment about the default value.
CI
=> Remove redundant default help text.

scripts/owner.sh
Verify and modify the ownership of our crates in bulk
We create `scripts/owner.sh`
* This script works like the other package-related scripts but runs `cargo owner`
* Because this command is potentially risky, we ask for the user to type "yes"
```
scripts/owner.sh packages.txt --list
```
=> Add a script to manage the ownership of the Linera crates

linera-execution/src/execution.rs, linera-service/tests/linera_net_tests.rs
The applications query uses `used_blobs`, but newly created applications are not actually added to `used_blobs`.
Return the keys of the user execution states map instead.
A regression test was added.
- Changes on main: https://github.com/linera-io/linera-protocol/pull/3818
=> Use execution state for `applications` query.

linera-chain/src/block.rs, linera-chain/src/certificate/confirmed.rs, linera-chain/src/certificate/validated.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-execution/src/execution.rs, linera-execution/src/system.rs, linera-service/tests/linera_net_tests.rs
The `applications` query uses `used_blobs`, but newly created applications are not actually added to `used_blobs`.
Add new applications to `used_blobs`.
Make the `applications` query return the applications with an execution state.
I added a regression test.
I also tested it locally:
```
cargo run --bin linera -- net up --with-faucet --faucet-port 8080
```
```
cargo run --bin linera -- wallet init --with-new-chain --faucet http://localhost:8080
cargo run --bin linera -- project publish-and-create examples/counter --json-argument "42"
cargo run --bin linera -- service --port 8081
```
Then `list_applications` doesn't show the new app. With this fix, it does.
Since this changes the execution semantics, we could consider a different workaround for the testnet: Instead of using `used_blobs`, …
=> Add new applications to `used_blobs`; change `applications` query.

linera-chain/src/chain.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/evm/revm.rs, linera-execution/src/execution.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/test_utils/mock_application.rs, linera-execution/src/test_utils/mod.rs, linera-execution/src/unit_tests/system_tests.rs, linera-execution/src/wasm/wasmer.rs, linera-execution/src/wasm/wasmtime.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/revm.rs, linera-execution/tests/service_runtime_apis.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/test_system_execution.rs, linera-execution/tests/wasm.rs
Some arguments and fields of `*Context` types are unused. The linter doesn't catch that because they are trait methods or public fields.
Remove the unused code.
CI
=> Remove unused context args and fields.

linera-execution/src/evm/database.rs, linera-service/src/linera-exporter/state.rs
**Description:**
This PR fixes minor typos in the codebase:
- Corrects "transferts" to "transfers" in the EVM TODO comment in database.rs
- Fixes "notfications" to "notifications" in the state exporter comment in linera-exporter/state.rs
These changes are purely cosmetic and don't affect functionality.
=> Fix typos in TODO comments and notifications reference

Cargo.lock, linera-service-graphql-client/Cargo.toml, linera-service-graphql-client/tests/test_check_service_schema.rs
When the schema snapshot test fails, it's hard to read the output.
Use [`similar_asserts::assert_eq`](https://github.com/mitsuhiko/similar-asserts) instead of `std::assert_eq`, which gives a nice diff on failure.
Caused test to fail and checked output locally.
=> `linera-service-graphql-client`: use `similar-asserts` for schema snapshot

linera-core/src/client/mod.rs, linera-views/src/test_utils/mod.rs
This PR fixes two minor typos in comments:
- Corrects "subcribes" to "subscribes" in client/mod.rs
- Corrects "scenarion" to "scenario" in test_utils/mod.rs
These changes only affect comments and do not modify any functional code.
=> Fix typos: correct spelling

.github/workflows/explorer.yml, .github/workflows/long_faucet_chain_test.yml, .github/workflows/performance_summary.yml, .github/workflows/scylladb.yml
This PR updates the actions/checkout GitHub Action from v3 to v4
Reference: [actions/checkout v4 release](https://github.com/actions/checkout/releases)
=> Update actions/checkout to v4 

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
When syncing a chain, a client needs to also process the latest timeout certificate from the validators, so that it knows what the current round is, and it can propose blocks. This is currently missing in `try_synchronize_chain_state_from`.
Process the timeout certificate.
A client test was extended to verify that client will process the timeout certificate requested by another client.
- These changes should be released in a new SDK, and
- ported to `main`.
- #3839
=> When syncing, also process timeout certificates.

.github/workflows/rust.yml
The tests for EVM were not enabled for the CI.
The cargo command is changed to `cargo test evm` which makes some small repetition with other tests. But that is fine.
The CI.
None.
=> Enable three EVM tests that were forgotten.

.github/workflows/rust.yml, linera-execution/src/evm/database.rs, linera-execution/src/evm/mod.rs, linera-execution/src/evm/revm.rs
Several variables such as block height are available in the `block` variable in the EVM. Support was missing.
The `BlockEnv` is computed from the `runtime`. The `gas_limit` could not be put since the limit in `Resources`
does not appear to be available from the `runtime`.
The CI.
Documentation on the `BlockEnv` is available in https://docs.rs/revm-primitives/15.2.0/revm_primitives/env/struct.BlockEnv.html
=> Add the computation of the BlockEnv for EVM.

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
When syncing a chain, a client needs to also process the latest timeout certificate from the validators, so that it knows what the current round is, and it can propose blocks. This is currently missing in `try_synchronize_chain_state_from`.
Port the fix from https://github.com/linera-io/linera-protocol/pull/3840 to `main`.
A client test was extended to verify that client will process the timeout certificate requested by another client.
- Closes #3839.
=> When syncing, also process timeout certificates. (main port)

.github/workflows/docker-compose.yml, .github/workflows/explorer.yml, .github/workflows/long_faucet_chain_test.yml, .github/workflows/performance_summary.yml, .github/workflows/rust.yml, .github/workflows/scylladb.yml
Node 20 compatibility: switch all jobs to actions/checkout@v4. Pure maintenance, behavior unchanged.
=> build: update checkout action to v4

CLI.md, linera-faucet/server/src/lib.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
If the faucet chain gets very long, requesting a new chain becomes very slow for new wallets.
Make the faucet switch chains every 100 blocks.
I extended `test_end_to_end_faucet_with_long_chains`.
- be deployed as the faucet.
- Closes #3846.
=> Automatically rotate the faucet chain once it has a maximum length.

CLI.md, linera-faucet/server/src/lib.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
Backport of https://github.com/linera-io/linera-protocol/pull/3848.
If the faucet chain gets very long, requesting a new chain becomes very slow for new wallets.
Make the faucet switch chains every 100 blocks.
I extended `test_end_to_end_faucet_with_long_chains`.
- These changes should be deployed as the faucet.
- Backport of https://github.com/linera-io/linera-protocol/pull/3848.
=> Automatically rotate the faucet chain once it has a maximum length. (#3848)

CLI.md, Cargo.lock, linera-faucet/server/Cargo.toml, linera-faucet/server/src/lib.rs, linera-service/src/linera/command.rs, linera-service/tests/linera_net_tests.rs
As of https://github.com/linera-io/linera-protocol/pull/3852, the faucet switches chains every 100 blocks. That means it cannot be restarted with the same command line, because the original chain may be closed (and broke).
On restart, while the current chain is closed, keep switching to the last chain that it opened until we find the most recent one.
Also, change the default maximum length to 500 blocks to reduce the overhead and the number of chains that end up in the faucet wallet.
`test_end_to_end_faucet_with_long_chains` restarts the faucet now.
- These changes should be ported to the `main` branch.
- The faucet should be restarted with this.
- See https://github.com/linera-io/linera-protocol/pull/3852.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTR …
=> Find current chain on faucet restart.

linera-service/tests/fixtures/evm_example_counter.sol, linera-service/tests/linera_net_tests.rs
It was a little unclear whether an EVM smart contract failing would result in an error.
It turns out that yes the error are being passed down and a test is added for this feature.
SI is the point.
Normal realease.
None.
=> Add a test that en EVM failing function results in an error

docker/Dockerfile
We need the debug symbols in general, but we'll also require this once I add Pyroscope back
Stop stripping binaries, so that we have debug symbols in production
CI
=> Don't strip binaries

Cargo.lock, Cargo.toml, examples/Cargo.lock, linera-base/src/crypto/secp256k1/evm.rs, linera-ethereum/Cargo.toml
The versions of alloy used in examples/Cargo.toml and Cargo.toml had diverged and needed to be reunified.
Also the `alloy-signer-local` was unused and needed to be removed.
Both changes are done.
The elimination of `alloy-signer-local` is more important than it looks like. Version 0.9.2 depends on `c-kzg`.
Unfortunately, version 22.0.1 of REVM depends on `c-kzg` as well and a native library can be present only
one time in the linking process.
In other words, one block for the use of the next version of Revm has been cleared. Two more obstacles remain:
* The resolution of the issue https://github.com/bluealloy/revm/issues/2425
* The upgrade of Revm from version 22.0.1 to the next one with this bug correction and the change of the PR https://github.com/bluealloy/revm/pull/2464
When this is …
=> Alloy version bump and removal of `alloy-signer-local`

.github/workflows/docker_image.yml, scripts/deploy-validator.sh
These places were missed, and are the most important ones 🤦🏻‍♂️
Make sure we're building with release mode in the places we should be
CI
This doesn't seem to have affected our `testnet_babbage` image though, so this might be optional
=> Make sure we're building release images

linera-service/src/cli_wrappers/local_net.rs, linera-service/src/storage.rs, linera-service/tests/local_net_tests.rs
After #3787, it is no longer needed to initialize the shard of the dual-store databases separately.
Remove special code added in #2734
CI
=> Simplification storage initialization of the dual-store database backend

docker/Dockerfile
We need the debug symbols in general, but we'll also require this once I add Pyroscope back
Stop stripping binaries, so that we have debug symbols in production
CI
=> Don't strip binaries (Port of #3866)

linera-execution/src/lib.rs
While working through the `Resource`(`Tracker`) code I noticed we map `SendMessageRequest` to this struct but it wasn't used anywhere.
Remove unused struct. It seems like what we use instead is `SendMessageRequest<Vec<u8>>`.
N/A
=> Remove unused RawOutgoingMessage struct

CLI.md, Cargo.lock, linera-faucet/server/Cargo.toml, linera-faucet/server/src/lib.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
Automatic faucet chain rotation caused several issues. (See e.g. https://github.com/linera-io/linera-protocol/pull/3864.)
Revert it.
CI
=> Revert faucet chain rotation.

linera-service/tests/linera_net_tests.rs
There were some reports of `sync` after `follow-chain` not working. `follow-chain` is only used directly after `forget-chain` (for the same chain) in the tests currently, so that the chain is still in the database.
Also test `follow_chain` in `test_end_to_end_assign_greatgrandchild_chain`.
This seems fine on `main`. I will backport this to `testnet_babbage`.
- Backport to `testnet_babbage` and fix, if necessary.
=> Test that follow-chain also works with child chains.

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
If two clients make conflicting proposals, it can happen that both of them have their own proposal in their local node, so when retrying, they will retry in the same round, because their own pending proposal isn't treated as a "conflict".
Use the next round, even if the proposal is our own.
The added test reproduces the issue.
=> Fix a bug where clients don't recover from conflicting proposals.

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs
If two clients make conflicting proposals, it can happen that both of them have their own proposal in their local node, so when retrying, they will retry in the same round, because their own pending proposal isn't treated as a "conflict". This was fixed on the `main` branch in https://github.com/linera-io/linera-protocol/pull/3892.
Backport the fix.
`test_conflicting_proposals` was added.
- This is a backport of https://github.com/linera-io/linera-protocol/pull/3892.
=> Fix a bug where clients don't recover from conflicting proposals. (#3892 → testnet_babbage)

CLI.md, linera-base/src/data_types.rs, linera-client/src/chain_listener.rs, linera-client/src/client_context.rs, linera-client/src/unit_tests/chain_listener.rs, linera-faucet/server/src/lib.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs, linera-service/src/schema_export.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
If the faucet chain gets very long, requesting a new chain becomes very slow for new wallets.
Make the faucet switch chains every 100 blocks.
The previous attempt was reverted: https://github.com/linera-io/linera-protocol/pull/3852
This new approach makes it less problematic to restart the faucet:
The faucet now only uses the main chain (which in practice will usually be one of our root chains in the testnet) to create temporary child chains. It only provides each child with enough funds to serve 100 user requests. (That number is a config option.) Once the child's funds are exhausted, it is closed and removed from the wallet, and a new child is created from the main chain.
In particular, the main chain is never drained of all funds at once, it never gets closed, and it is never used to …
=> Rotate the faucet chain automatically.

linera-base/src/data_types.rs, linera-service/tests/linera_net_tests.rs
It should be possible to e.g. define a `const x: Amount` using some addition and multiplication. (I ran into this in https://github.com/linera-io/linera-protocol/pull/3893.)
Make more functions `const`. (Also fix a typo.)
N/A
=> Make numeric constructors and arithmetic const.

linera-chain/src/block.rs, linera-chain/src/certificate/confirmed.rs, linera-chain/src/data_types.rs
`MessageId` is now used only in the SDK, not in the protocol itself.
Remove unused functions.
CI
=> Remove unused message ID functions.

linera-core/src/client/mod.rs, linera-service/tests/linera_net_tests.rs
`sync` after `follow-chain` doesn't work.
Add a test (backport of https://github.com/linera-io/linera-protocol/pull/3887). Handle the case where a chain is uninitialized.
The test was backported.
- Closes #3891.
- Test for `main` (doesn't have the bug): https://github.com/linera-io/linera-protocol/pull/3887
=> Fix syncing after `follow-chain` for child chains.

Cargo.lock, Cargo.toml, examples/Cargo.lock, examples/Cargo.toml, linera-base/src/graphql.rs, linera-indexer/graphql-client/gql/operations_schema.graphql, linera-service/src/node_service.rs, linera-service/template/Cargo.toml.template, linera-views/src/graphql.rs
async-graphql is broken
Work around for https://github.com/async-graphql/async-graphql/issues/1703
Managed to run the counter demo locally and GraphQL Playground was working fine.
=> Patch GraphQL; update deps.

linera-base/src/identifiers.rs, linera-base/src/ownership.rs, linera-core/src/unit_tests/worker_tests.rs
The validators are not currently expected to start client processes automatically. So chains that enter fallback mode are effectively bricked.
Set the default fallback timeout to `MAX`, so validators will never sign a fallback timeout certificate.
(Only a default chain config change.)
=> Set default fallback duration to `MAX`.

examples/counter-no-graphql/README.md, examples/counter/README.md, linera-execution/src/evm/database.rs, linera-execution/src/evm/revm.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-service/tests/fixtures/evm_example_execute_message.sol, linera-service/tests/linera_net_tests.rs
We identified two problems with the EVM, which we correct now. Also, some typos from the closed PR #3883 are put there.
The `gas_limit` is added to the BlobkEnv variable.
A more serious problem is the constructor argument for the contract being run in `execute_message`. It was incorrect when running a non-trivial constructor on another chain. The serialization was missing.
A non-trivial constructor that does not do anything, just making a check, was introduced to `evm_example_execute_message.sol`. It triggers the previous problem.
=> Address two issues with EVM

kubernetes/linera-validator/templates/ingress.yaml
We were defining this config, but AFAIU we weren't actually using it
Use the config
Deployed a network with this change
=> Actually use backend config

linera-chain/src/chain.rs
This state hash computation can apparently take much longer than 10ms
Adjust the bucket sizes to be more generous and catch larger values
CI + have deployed networks with this already
=> Adjust state hash computation bucket

linera-service/src/linera/main.rs
When this path is executed from inside a docker container, which we usually run as root, `$HOME` will point to `/root`, but `dirs::config_dir()` will actually return `$HOME/.config`, but the `.config` directory won't be created yet.
Then when we call `fs_err::create_dir("/root/.config/linera")`, it can fail because `.config` won't exist yet.
Recursively create directories so that `.config` is also created, and the command succeeds from within Docker containers as well.
Deploys were failing with this, now they succeed.
=> Recursively create parent directories when creating config dir

docker/Dockerfile, docker/compose-server-entrypoint.sh, docker/compose-server-init.sh, docker/docker-compose.yml, docker/server-entrypoint.sh, docker/server-init.sh, kubernetes/linera-validator/scylla-manager.values.yaml, kubernetes/linera-validator/templates/shards.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl, linera-service/src/cli_wrappers/docker.rs, linera-service/src/cli_wrappers/helmfile.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/src/linera/net_up_utils.rs
Our benchmarks are currently using `DualStore`, so it makes sense for us to add support to use it if we need it. We won't ideally need this, as the plan is to get `ScyllaDB` to a state that we reach the big numbers with it.
This PR adds the `linera-protocol` side support for `DualStore` networks, as well as support for doing local `linera net up --kubernetes` runs with `DualStore`
Ran a local network with default params (scylladb) and `DualStore`, both work
=> Add dual store support

kubernetes/linera-validator/helmfile.yaml, kubernetes/linera-validator/scylla-setup/gke-daemonset-raid-disks.yaml, kubernetes/linera-validator/scylla-setup/local-csi-driver/00_namespace.yaml, kubernetes/linera-validator/scylla-setup/local-csi-driver/10_csidriver.yaml, kubernetes/linera-validator/scylla-setup/local-csi-driver/10_driver_serviceaccount.yaml, kubernetes/linera-validator/scylla-setup/local-csi-driver/10_provisioner_clusterrole.yaml, kubernetes/linera-validator/scylla-setup/local-csi-driver/20_provisioner_clusterrolebinding.yaml, kubernetes/linera-validator/scylla-setup/local-csi-driver/50_daemonset.yaml, kubernetes/linera-validator/scylla-setup/local-ssd-sc.yaml, kubernetes/linera-validator/scylla.values.yaml, kubernetes/linera-validator/templates/shards.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl
When deploying networks on GCP, using local SSDs give us good performance improvements.
Add support for deploying networks using local SSDs. Keep in mind that this will only be used when deploying GCP networks, this won't be used ever for local networks for obvious reasons (it already always runs on the local disk).
It made more sense for the YAML files to setup the local CSI driver to live here to avoid some directory gymnastics on the `linera-infra` side.
Deployed networks using this code
=> Add Local SSD support

CLI.md, docker/Dockerfile, docker/compose-proxy-entrypoint.sh, docker/compose-server-entrypoint.sh, docker/docker-compose.yml, docker/proxy-entrypoint.sh, docker/server-entrypoint.sh, docker/server-init.sh, kubernetes/linera-validator/helmfile.yaml, kubernetes/linera-validator/scylla.values.yaml.gotmpl, kubernetes/linera-validator/templates/proxy.yaml, kubernetes/linera-validator/templates/shards.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl, linera-indexer/lib/src/rocks_db.rs, linera-indexer/lib/src/scylla_db.rs, linera-service/src/linera-exporter/main.rs, linera-service/src/linera/main.rs, linera-service/src/proxy/main.rs, linera-service/src/server.rs, linera-storage-service/src/client.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/store.rs
We'll use replication factor of 1 in CI and locally, but probably will use 3 in deployed networks on GCP
Add an option to support that
CI + deployed network locally
=> Make ScyllaDB replication factor configurable

linera-views/src/backends/scylla_db.rs
`SimpleStrategy` is not recommended to be used in production
Use the recommended production setting
CI + deploy network with this
=> Use NetworkTopologyStrategy instead of SimpleStrategy

kubernetes/linera-validator/helmfile.yaml
When talking to the ScyllaDB contact, he said that using up to date charts is probably a good idea, to make sure we don't have any bugs that were fixed
Update ScyllaDB chart versions
Deployed network locally
=> Use newer ScyllaDB Chart versions

linera-rpc/src/grpc/server.rs, linera-rpc/src/simple/server.rs
The error log `Dropping cross-chain query` is printed on every retry attempt.
Print it only after the last attempt.
CI
=> Move cross-chain error log to after the loop.

CLI.md, linera-service/src/benchmark.rs, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/cli_wrappers/mod.rs, linera-service/src/cli_wrappers/remote_net.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/linera/command.rs, linera-service/src/linera/main.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
`--with-new-chain` and `--with-other-chains` are not necessary anymore; `request-chain` and `follow-chain` should be used instead.
Remove them, and the `FaucetOption` enum.
Also don't print the latest hash anymore: This was meant to avoid trusting the faucet or expired committees, but we already don't sync on `wallet init` anymore, so it's in the wrong place. I created #3909 to revisit this once we address the rest of the long-range attack issue.
The tests were updated to use `request-chain` instead.
- Before the next testnet, the Linera Manual needs to be updated.
- Closes https://github.com/linera-io/linera-protocol/issues/3399.
=> Remove 2 deprecated CLI options of `linera wallet init`.

linera-chain/src/data_types.rs, linera-chain/src/manager.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/temporary_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/format.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
When re-proposing a validated block from an earlier round there is a validated block certificate, signed by a quorum of validators, attesting the correctness of the outcome and the validity of the oracle responses—_and_ that the `authenticated_signer` is actually the one who originally submitted the block proposal to the validators!
This last part I missed in the special case where we re-propose an earlier proposal by a super owner from the fast round! In that case, there is no validated block certificate, which is why we disallow oracles. But we erroneously compare the `authenticated_signer` to the owner _re-proposing_ the block, rather than the original super owner.
Of course comparing it to the super owner is not enough: The regular owner must not be able to do something in the super …
=> Fix authenticated signer when re-proposing a fast block.

Cargo.lock, Cargo.toml, linera-views/src/backends/scylla_db.rs
Same as #3789, the rust driver crate also needs to be updated
Update crate and make things compile
CI + will deploy a network with this
=> Use newer Scylla driver crate version

kubernetes/linera-validator/helmfile.yaml
When deploying multiple networks in parallel, we need to make sure that helmfile is using the proper kube context and kube config, to prevent it from trying to deploy to an incorrect cluster.
Pass those in and use them when appropriate
Deployed networks in parallel using local SSD, it works.
=> Use proper kube context and kube config in helmfile

linera-client/src/client_context.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/data_types.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/graphql.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/system_execution_state.rs, linera-execution/src/unit_tests/system_tests.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/chain.rs, linera-service-graphql-client/gql/service_schema.graphql
Every initialized chain has a current epoch, and we are not using the `epoch` field to check whether a chain is initialized.
Make `epoch` not optional.
Also deduplicate some related chain client code.
CI
=> Make `epoch` not optional in `ChainInfo` and state.

linera-client/src/client_context.rs, linera-client/src/wallet.rs, linera-service/src/linera/main.rs
Right now if you don't specify a chain, the faucet will just use the default chain of the wallet. However, for the faucet, this will often be using the admin wallet, which means the default chain will be the admin chain.
Instead of using the default chain, use a non admin chain instead in this case.
Deployed a network with a faucet using this updated code, and it works as expected.
=> Use non admin chain for faucet if chain not specified

Cargo.lock, Cargo.toml, linera-faucet/server/src/lib.rs, linera-indexer/lib/src/common.rs, linera-service/src/util.rs
We cannot publish to crates with some dependencies are patched w/ github references.
Replace strings to use React @ 18.
CI and manually that GraphiQL playground works.
=> Replace React version and revert back to official graphql release

linera-core/src/client/mod.rs, linera-core/src/local_node.rs
The `client` module contains a lot of logic to get committee information out of a `ChainInfo` from the local node.
Move that logic into an extension trait in `local_node`.
Also rename `chain_info` to `fetch_chain_info`, because it can download it from the validators.
CI
=> Move committee getting logic into extension trait.

linera-faucet/server/src/lib.rs
It looks like the faucet on the testnet closed a chain but then failed to switch to a new one.
Remove the temporary chain ID from the mutex _before_ attempting to close it and remove it from the wallet, so that in case any of those steps fail, we will create a new temporary chain next time anyway.
Also, don't fail the request if we can't remove the chain from the wallet.
It's not clear yet what actually failed, but this change should be safe: we could deploy it so that next time something goes wrong, the faucet does not break entirely.
- Deploy a new faucet on the testnet.
=> Remove chain ID from mutex before closing it.

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-service/src/util.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
We want to move more functionality into `Client` (https://github.com/linera-io/linera-protocol/issues/3942) and in general simplify the logic.
`known_committees` currently returns the union of all committees known to the `ChainClient`'s local chain and the admin chain. This prevents moving its call sites to `Client`, and also doesn't make sense when we move towards addressing https://github.com/linera-io/linera-protocol/issues/285: The currently trusted committees cannot depend on which `ChainClient` instance caused the synchronization.
In `prepare_chain` make sure that the admin chain is always at least as up-to-date as the local chain.
Replace `known_committees` with `admin_committees`.
Update `test_change_voting_rights`: It makes sense that the test would fail now if we revoked the old …
=> Use admin chain instead of `known_committees`.

examples/rfq/src/state.rs
For a given type T, we can apply the derive statement for `SimpleObject` and `InputObject`. Those will implement the `Object` and `InputObject` GraphQL trait. For a given type, we should implement at most one of those. 
If both are introduced, then we should have an `input_name` statement associated to it so that the Input type has a different name to the output type.
This is generally satisfied in the code, with the exception of 4 types in RFQ.
The solution is to add the `input_name` statement.
It might be a better idea to remove some traits definition altogether. 
The CI. Currently, the RFQ passes only via the README.md test
None
=> Add `input_name` entry to some RFQ types.

linera-sdk/Cargo.toml
Docs are broken because they're trying to build testing code.
Don't document testing code.
`docs.rs` is the only way of testing this consistently that I know of.
=> `linera-sdk`: build docs without tests

linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/cli_wrappers/wallet.rs
To reproduce big numbers in benchmarks, we need to use multiple processes to exhaust the CPU on big VMs.
Right now, the only way to do that is manually starting one wallet per process, then manually starting all the benchmarks as well.
To reach big numbers like 1M TPS, I was using 4 different benchy instances, and spawning 12 processes on each. That means that I had to manually wallet init different wallets 48 times, then manually start the benchmark process 48 times... not ideal.
Let's automate this whole process with `linera multi-benchmark`. You can specify how many processes you want, and it'll gradually start them for you, so that TPS is gradually ramped up. The same arguments you pass to `linera benchmark` you can pass to this one as well, and it'll create all the processes with …
=> Introduce linera multi-benchmark

.github/workflows/rust.yml
Now that `linera-web` is in this repository, we should at least build it as part of our CI.  It has to be excluded from `default-members` due to requiring a nightly compiler, so let's add a separate job to build it.
Build it as part of CI.
CI.
=> Build `linera-web` in CI instead of `linera-client`

Cargo.lock, linera-client/Cargo.toml, linera-client/src/chain_listener.rs, linera-client/src/client_context.rs, linera-client/src/lib.rs, linera-client/src/persistent/indexed_db.rs, linera-client/src/persistent/mod.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/test_utils.rs, linera-faucet/server/src/lib.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli/main.rs, linera-service/src/node_service.rs, linera-service/src/schema_export.rs, linera-web/src/lib.rs
The `chain_description` function is duplicated between the `ClientContext` struct and the `ClientContext` trait due to `Sync`ness issues with `Persist`.  As requested by @deuszx in https://github.com/linera-io/linera-protocol/pull/3956, deduplicate it, which entails several proximal cleanups.
- Further our goal of making `ChainClient` a syntactic convenience for calling `Client` with a chain ID by removing the `ensure_has_chain_description` call from `make_chain_client` and correspondingly making `make_chain_client` sync.  This removes the need for the wallet to be `Sync`, even when we `tokio::spawn`.
- Merge `LocalPersist` and `Persist` using conditional compilation, as we do elsewhere.
- Split the provided functions in `ClientContext` into `ClientContextExt` to allow dropping …
=> Chain description duplication

linera-base/src/data_types.rs, linera-chain/src/block.rs, linera-chain/src/chain.rs, linera-chain/src/inbox.rs, linera-chain/src/outbox.rs, linera-core/benches/client_benchmarks.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/value_cache.rs, linera-core/src/worker.rs, linera-execution/src/evm/revm.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/system.rs, linera-execution/src/wasm/mod.rs, linera-rpc/src/grpc/server.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/metering.rs, linera-views/src/views/bucket_queue_view.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/log_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/queue_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/register_view.rs, linera-views/src/views/set_view.rs
The Prometheus metrics are behind a feature flag. In some files there are dozens of conditionally compiled items, and the metrics-only imports are often far away from the places where they are used. This makes it hard to add imports in the right places and keep track of interactions between different feature flags.
We also call `process_outgoing_messages` separately for each transaction which could cause some redundant loading of outboxes. Probably not a big issue since views stay in memory, but still unnecessary, and I will need to change this anyway soon for https://github.com/linera-io/linera-protocol/issues/3969.
Finally, there are a few redundantly separated `impl` blocks, and we're inconsistent whether we fully qualify or import `try_join_all`.
* Create `metrics` submodules in …
=> `metrics` submodules; other cleanups.

linera-views/src/backends/rocks_db.rs
Disk writes were growing a bit too fast with the old settings
Use a bigger buffer size, but less overall buffer memory.
Be more conservative on how soon we start slowing writes down.
Start compacting level 0 files sooner.
Increase overall parallelism and add subcompactions to improve efficiency.
Increase base file size to offset and balance a bit the other changes.
Ran benchmarks with this setting, performance was way better.
=> Further optimize RocksDB settings

kubernetes/linera-validator/helmfile.yaml, kubernetes/linera-validator/scylla-setup/gke-daemonset-raid-disks.yaml, kubernetes/linera-validator/scylla-setup/local-csi-driver/50_daemonset.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl
We're adding support for deploying ScyllaDB in the recommended way.
This is the `linera-protocol` side support for the `linera-infra` PR https://github.com/linera-io/linera-infra/pull/250.
Ran benchmarks with this. ScyllaDB's performance drastically increases when deploying it in the recommended way.
=> Support for running ScyllaDB in its own NodePool

linera-chain/src/chain.rs, linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/system.rs
We're passing around an `Option<TransactionTracker>` in order to do `maybe_tracker.map(|tracker| tracker.blobs.get(id))` which returns `None` anyway for missing blobs.
Simplify the APIs by assuming `TransactionTracker` is always available and for cases where we used to pass `None` - pass `TransactionTracker::default()`.
CI.
=> Use default TransactionTracker rather than None

linera-chain/src/chain.rs, linera-execution/src/resources.rs
`ResourceTracker.blocks` field was meant to track blocks created so far to charge a constant cost for it but that was removed in a recent PR.
Remove the field. It was unused anyway.
CI
=> Remove block field from ResourceTracker

Cargo.lock, Cargo.toml
Recent package upgrades led to both the `ring` and `aws_lc_rs` features being enabled for `rustls`, which therefore fails to pick a sensible default.
Disable the features in the AWS packages that cause `rustls/aws_lc_rs` to be enabled, so that `rustls` defaults to `ring`.
CI.
=> Fix `dynamodb` tests by disabling `aws_lc` crypto

linera-chain/src/block_tracker.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-chain/src/lib.rs, linera-core/src/chain_worker/actor.rs, linera-execution/src/execution.rs, linera-execution/src/lib.rs, linera-execution/src/policy.rs, linera-execution/src/resources.rs, linera-execution/src/runtime.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/revm.rs, linera-execution/tests/wasm.rs
Logic that tracks the resource consumption during block execution is scattered. The execution of block's transactions was imperative - we tracked every index (application, message, blob) in the main function logic which made reading and understanding harder. This meant an error of incompleteness was easy to miss.
Add a new struct `BlockExecutionTracker` (similar to `TransactionTracker`) that wraps the block-wide context of the underlying transaction execution. It's responsible for updating indices, updating resources used after transaction execution.
CI
=> Add BlockExecutionTracker 

kubernetes/linera-validator/grafana-dashboards/linera/general.json
We've had OOMs in the shards, and this metric doesn't seem to have caught it.
Replace the graph with a graph using a metrics that _does_ seem to catch when a pod was `OOMKilled`. 
I used this instead and saw the pods that were `OOMKilled` show there with the correct reason.
=> Add better OOM metrics to dashboards

linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-chain/src/block_tracker.rs, linera-chain/src/chain.rs, linera-execution/src/resources.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs
We are charging for all published blobs before we execute any operation in the block. This is wrong b/c we want the incoming grant to be able to cover the fees. The grants are processed during operation processing only so they are not taken into account at the beginning of the block processing.
Move the published blobs' resources tracking to the end of processing a transaction that published it. At this point any incoming grant is already processed. In order to do so, we track blob IDs referenced during transaction execution via `TransactionTracker.published_blobs` and consume it in `BlockExecutionTracker::process_txn_outcome`.
Also, charge for publishing user-created blobs only. `BlobType::Committee` is not accounted for.
CI.
- Nothing to do / These changes follow the usual release …
=> Account for published blobs in the resource at the end of transaction execution rather than upfront.

toolchains/stable/rust-toolchain.toml
Migrate to the latest stable Rust toolchain. Also needed for upgrading async-graphql.
Update toolchain to Rust 1.86.0
CI
These changes should be backported to the latest `testnet` branch
=> migrate to Rust 1.86.0

linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-chain/src/lib.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
Several corrections are done to the error handling.
The following unrelated simple changes are made:
* Removal of `InactiveLocalChain` which is never used.
* Addition of the size to `BlockTooLarge`.
* Addition of the timestamp to the timestamp errors.
* The `InactiveChain` of the `ExecutionError` now contains a specific `ChainId`.
* The ChainId of the `InactiveChain` is now printed as `{0}`, no longer as `{0:?}`.
The CI.
None.
=> Several corrections to the error handling.

linera-execution/src/evm/mod.rs, linera-execution/src/evm/revm.rs
There was an error in the gas accounting 
* The `Gas::new(0)` is replaced by a `Gas::new(gas_limit)`.
* The `EvmExecutionError` errors are now more precise.
The CI.
None
=> Correct a bug in the gas accounting of REVM

Cargo.toml, default.nix, linera-web/Cargo.toml, linera-web/build.bash
When we merged `linera-web` into this repository, I left some relative paths in `build.bash` that break the build script.
It would be nice to migrate back to `wasm-pack`, a more standard tool in the Rust world, but so far `wasm-pack` hasn't made a release that contains the necessary PR https://github.com/rustwasm/wasm-pack/pull/1443.
Instead of using relative paths, extract the necessary paths from `cargo metadata`.
Tested locally.  (We should really run `pnpm build` as part of the CI job, not just `cargo build`.)
=> `linera-web`: make location-independent

flake.lock
We're using Rust 1.86 now, but our `flake.lock` got left behind.
Update it.
Tested locally.
=> `flake.lock`: update to support Rust 1.86

CLI.md, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
Often after `follow-chain`, the user also wants to synchronize the chain. Adding this as an option allows doing that in the same command.
Add a `--sync` option.
In one test I used this instead of the `sync` command.
- Closes #3889.
=> Add `--sync` option to `follow-chain`.

linera-core/src/client/mod.rs
When trying to find "received certificates", faulty validators might send us certificates that didn't actually send anything to the chain in question, causing the client to unnecessarily process valid but irrelevant blocks.
Check that they actually sent something.
Since this only defends against some spam, isn't critical for security, and testing it would require considerably extending the test validators, I suggest not adding a test for this. CI will check if it _breaks_ anything (i.e. yields false positives).
- Closes https://github.com/linera-io/linera-protocol/issues/4025.
=> Check that downloaded sender chain blocks are relevant.

linera-service/src/linera-exporter/exporter_service.rs
=> fix typo exporter_service.rs

.github/workflows/explorer.yml
v3 is outdated. v4 is the latest stable version and works better with Node.js 20.
Official info: [setup-node v4 release](https://github.com/actions/setup-node/releases/tag/v4.0.0)
=> Update explorer.yml – bump setup-node to v4

Cargo.lock, Cargo.toml, linera-execution/Cargo.toml, linera-execution/src/evm/database.rs, linera-execution/src/evm/mod.rs, linera-execution/src/evm/revm.rs, linera-service/tests/fixtures/evm_basic_check.sol, linera-service/tests/fixtures/evm_example_counter.sol, linera-service/tests/linera_net_tests.rs
The smart contract addresses that we are using in the EVM are internally all the same: `Address::ZERO.create(0)`.
This creates consistency problems between Ethereum and Linera.
This internal address is available in solidity-based EVM smart contracts as `address(this)`.
We use the `CreateScheme::Custom { address }` that was previously introduced in REVM and merged in REVM-23.1.0.
We also switched to version 24.0.0 of REVM.
Next steps:
* Add the create/create2 functionality to the code.
* Add the transfer functionalities to the code and unify them with Linera.
* A CI test of the `address(this)` feature is being introduced.
* Also, additional checks are done for the contract address in `fn check_contract_initialization`.
None.
=> Make REVM address coincide with the one of Linera

linera-base/src/data_types.rs, linera-chain/src/chain.rs, linera-service/src/linera-exporter/state.rs
There is a conditionally compiled `impl From<u64> for BlockHeight`, but `BlockHeight`'s field is public, and we're using that directly almost everywhere.
Remove the impl, directly use `BlockHeight(n)` everywhere.
CI
=> Remove unnecessary `From` impl.

Cargo.lock, examples/Cargo.lock, kubernetes/linera-validator/templates/scylla-config.yaml, linera-views/Cargo.toml, linera-views/src/backends/scylla_db.rs
There are some optimization that we can do in how we're using ScyllaDB
This PR removes the use of:
* Non token aware queries
* Unpaged queries
* Most usages of `ALLOW FILTERING` (the ones remaining should be fine)
* Non prepared statements
Also:
* Tuned page creation and other settings a bit
* Some refactoring/code cleanup
CI + deployed a network, benchmarked it, and saw an over 10x decrease in ScyllaDB`s write latency
=> Optimize ScyllaDB usage

linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/test_utils.rs
Clippy rightly thinks that `Client::new` has `too_many_arguments`.
Use `ChainClientOptions` instead of passing in individual parameters.
CI
=> Use `ChainClientOptions` in more places.

linera-service/src/cli_wrappers/wallet.rs
That graphQL query can contain mutation publishing modules, for example, where all the contract bytes are currently being printed, making the logs become huge.
Truncate the query on the warning as well
CI
=> Truncate query output on query_node

linera-indexer/lib/src/common.rs, linera-indexer/lib/src/indexer.rs, linera-indexer/lib/src/plugin.rs
When renaming `clone_with_root_key` to `open_exclusive`, one error name was missed.
Update it to the new name
CI
=> Missed one rename still using CloneWithRootKey

.github/workflows/docker-compose.yml, .github/workflows/lint-check-all-features.yml, .github/workflows/rust.yml, .github/workflows/test-readmes.yml
Speed up and cut down CI costs.
`docker-compose` was ran on every push which seems unnecessary. It checks that our docker setup (that is expected to mimic validators' usage) is working. Since we care that it works on `main` and possibly release branches it doesn't have to run on every commit. **Now it runs on merge queue (before merge to `main`) and on release branches**
`test-readme-scripts` tests backwards compatibility. This is important but 95% of our PRs do not break them. We can detect it on `main` (and release branches) and fix right away. **Now it runs on merge queue (before merge to `main`) and on release branches**.
`lint-check-all-features` **runs on merge queue (before merge to `main`) and on release branches**.
`default-features-and-witty-integration-test` now runs on …
=> Small changes to speed up and trim down CI costs.

.github/workflows/docker-compose.yml, .github/workflows/lint-check-all-features.yml, .github/workflows/long_faucet_chain_test.yml, .github/workflows/test-readmes.yml
Wrong indentation for `merge_group`
Fix the identation.
CI
=> Fix merge queue trigger for CI

linera-base/src/data_types.rs, linera-chain/src/chain.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/chain_worker/state/mod.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-service-graphql-client/gql/service_schema.graphql, scripts/check_chain_loads.sh
When the client verifies incoming messages to its own chains, it doesn't need the sender chain's execution state, so computing the block execution there is unnecessary work.
Eventually we want to go even further and avoid even downloading some of the sender chain's blocks (see https://github.com/linera-io/linera-protocol/issues/3969).
As a preparation for #3969, we introduce an `unexecuted_blocks` map to the chain state: It maps block heights that are higher than `next_block_height`, i.e. haven't been executed yet, to block hashes.
We don't purge empty outboxes anymore. When updating the outboxes, we make sure that we haven't skipped any messages and compare to the next height to schedule: That allows us to update some outboxes even for loose blocks, ahead of execution.
For now we still …
=> Don't execute sender chains

CLI.md, linera-base/src/data_types.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/local_net_tests.rs
`finalize-committee` currently revokes all but the latest epoch. But sometimes we may want to keep more than one epoch.
Change this to `revoke-epochs <EPOCH>` and revoke only up to the specified one.
CI; tests were updated.
- Closes #3948
=> `revoke-epochs`

linera-service/src/proxy/grpc.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/value_splitting.rs, linera-views/src/error.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/reentrant_collection_view.rs
Several entries in the `ViewError` and `DynamoDbStoreInternalError` can be removed.
* The `TooLargeValue` is removed from `IndexedDbError` as it is unused.
* The `TooLargeValue` is removed from `MemoryStoreError`. This requires changing one test, which ought to be fine.
* The `TooLargeValue` is removed from `ViewError`.
* The unused errors for `DynamoDbStoreInternalError` are removed.
* No other unused errors were found.
The CI.
None.
=> Restructure the error types of `linera-views`.

linera-web/signer/tsconfig.json
There's some cleanup work being done in https://github.com/linera-io/linera-web/pull/49 that's incompatible with current configuration and yields `Uncaught ReferenceError: require is not defined` error.
Update the compilation options to more modern ones that fix the error.
CI
=> Fix TS compiler options.

linera-base/src/crypto/mod.rs, linera-base/src/crypto/signer.rs, linera-core/src/client/mod.rs, linera-persistent/src/lib.rs
We'd like to be able to use JavaScript exceptions as signer errors when JavaScript signers throw them, but currently these bounds prohibit this.
Make them conditionally compiled.
CI.
=> `linera-base`: remove `Send` and `Sync` bounds from signer errors on the Web

.github/workflows/benchmarks.yml
It times out while _building_.
Increase the timeout.
CI
=> Increase benchmark CI timeout.

.github/workflows/long_faucet_chain_test.yml
It's wasteful and slow to run this with 3000 blocks per chain in CI for every PR.
Run it with 1000 instead. Reduce the timeout.
CI
=> Reduce length in `test_end_to_end_faucet_with_long_chains`.

linera-chain/src/data_types.rs, linera-chain/src/unit_tests/data_types_tests.rs
We never explicitly check that a re-proposal's round is actually greater than the original proposal's. I couldn't find a way to actually exploit it because the checks inside the chain manager seem to implicitly cover all the cases, but it would be better to fail earlier, and it's a very cheap check.
Thanks, @deuszx, for pointing this out!
Add this to `BlockProposal::check_invariants`.
CI
=> Fail earlier if re-proposal round is wrong.

linera-web/signer/src/index.ts, linera-web/signer/src/local.ts, linera-web/signer/src/metamask.ts, linera-web/signer/src/private-key.ts, linera-web/signer/tests/index.test.ts
EmbeddedSigner name wasn't liked by the team. 
Rename to PrivateKeySigner.
None
=> Rename EmbeddedSigner to PrivateKeySigner

linera-core/src/worker.rs
The error message refers to a `Tick` operation, which doesn't exist anymore.
Update the message.
CI
=> Update timestamp error message.

kubernetes/linera-validator/grafana-dashboards/scylla/scylla-alternator.6.2.json, linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/linera_net_tests.rs
Description:  
This pull request addresses the following changes:
- Corrects the typo "avarage" to "average" in the description fields of the Grafana dashboard JSON for Scylla Alternator.
- Updates the test in linera_net_tests.rs by renaming the method call from set_preferred_owner to set_preferred_owner (fixing the function name to match the correct one).
=> Fix typos in Grafana dashboard and update test function in linera_net_tests.rs

.github/workflows/rust.yml, Cargo.lock, linera-web/Cargo.toml, linera-web/src/lib.rs, linera-web/src/signer.rs
https://github.com/linera-io/linera-protocol/issues/4113.  Specifically,
```
$ nix develop ..#nightly -c cargo clippy 
warning: unstable feature specified for `-Ctarget-feature`: `atomics`
|
= note: this feature is not stably supported; its behavior can change in the future
warning: `linera-witty` (lib) generated 1 warning
warning: `linera-base` (lib) generated 1 warning (1 duplicate)
warning: `linera-views` (lib) generated 1 warning (1 duplicate)
warning: `linera-execution` (lib) generated 1 warning (1 duplicate)
warning: `linera-chain` (lib) generated 1 warning (1 duplicate)
warning: `linera-storage` (lib) generated 1 warning (1 duplicate)
warning: `linera-version` (lib) generated 1 warning (1 duplicate)
warning: `linera-persistent` (lib) generated 1 warning (1 duplicate)
warning: …
```
=> `linera-web`: fix Clippy warnings and check Clippy in CI

linera-indexer/lib/src/rocks_db.rs, linera-indexer/lib/src/scylla_db.rs, linera-service/src/storage.rs, linera-storage-service/src/client.rs, linera-storage-service/src/common.rs, linera-storage-service/src/server.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/store.rs, linera-web/src/lib.rs
Storage backends should only receive configuration options that they actually use.
* Remove `CommonStoreInternalConfig` and `CommonStoreConfig` step by step
* Add missing CLI options to  `linera-storage-service`
Nothing changes from the user point of view.
This temporary creates a little more code duplication between `linera-service` and the binaries in `linera-indexer` and `linera-storage-service` but I think that's fine and should be fixed over time. 
Future work:
* We may re-evaluate whether `max_stream_queries` is best implemented as a method of `ReadableKeyValueStore`.
* I'm still conflicted about `max_concurrent_queries` and would very much like to remove it.
* It's not clear what happens if we pass the wrong replication factor for ScyllaDb.
* We may re-evaluate whether …
=> Remove CommonStoreInternalConfig and CommonStoreConfig

linera-chain/src/block_tracker.rs, linera-chain/src/chain.rs
As part of the bigger work we want to make sure that the execution of incoming messages can be paid for by the grant they carry. This is difficult to test now.
Extract transaction execution to `BlockExecutionTracker` to make testing simpler.
CI. This doesn't introduce new features - just a refactor.
=> Move transaction execution to `BlockExecutionTracker`

linera-client/src/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/node.rs
`synchronize_from_validators` is potentially expensive, and makes several chain info queries to the validators.
We call it for each chain when we start the chain listener. However, the chain listener also calls `ChainClient::listen`, which synchronizes again. Also, the latter calls `synchronize_from_validators` even for chains that are not tracked.
Remove the redundant calls.
CI
- Closes https://github.com/linera-io/linera-protocol/issues/4100.
=> Remove redundant synchronization.

kubernetes/linera-validator/templates/proxy.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl, linera-service/src/cli_wrappers/local_kubernetes_net.rs
Supporting multiple proxies requires making corresponding changes to Kube infrastructure. Primarily introducing a second headless service to act as a static DNS for proxy ordinal naming.
Add the headless service (no cluster IP) which enables cluster-wide DNS name resolution for members of a statefulset. (we did the same thing for shards).
=> Multiple proxies infrastructure

docker/Dockerfile, scripts/memleak_translate.sh
While using BPF's `memleak` to look into our server memory issue, I could not for the life of me get it to automatically translate the PC addresses into actual file names and file numbers.
Create a script that we can run with `memleak`'s output to translate these addresses for us using `addr2line`. Once we figure out how to do this in a more automated way (I'm assuming there must be a way), we can remove this. But for now, it is useful for debugging.
Have used this while debugging the memory issue in the server, the stacks get translated correctly
=> Script to translate addresses in executable to file names and line numbers

docker/debug/Dockerfile.debug
Production docker images are supposed to be as small as possible (more work on shrinking ours is planned).
If there's a production issue for example, we don't want to bloat the production Docker images by pre-installing a bunch of tools required for debugging.
Also depending on how constrained the resources already are (depending on the issue we're dealing with), installing different debugging tools on the spot might not be feasible.
Introduce a debugging Docker image, which contains already most tools one would generally use during debugging (other suggestions are welcomed).
Instructions on how to use it are in the Dockerfile comments
Have used this while debugging the server memory issue
=> Add Dockerfile.debug for debugging purposes

flake.nix, linera-web/package.json, linera-web/signer/package.json
`@linera/signer` was tested in an impure environment, so accidentally relies `npm` and `tsc` from outside the build environment.
Also, the shell hook I wrote in `flake.nix` puts `~/.cargo/bin` ahead of `$PATH`, so `.cargo/bin` can override tools from the build environment.
Use our existing `pnpm` instead of `npm`, and use `pnpm exec` to get `tsc` from the `devDependencies`.
Put `~/.cargo/bin` at the end of `PATH` instead of the front.
This CI and `linera-web`'s.
=> `linera-web`: fix external build

linera-core/src/client/mod.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
We want to optimize how we download certificates and distribute work among the validators in the future. To cancel requests to other validators for the same certificate, we need to be sure that we got the certificate we requested.
Compare the downloaded certificate's hash with the requested hash immediately.
Also, remove a redundant argument from `download_certificates`: We always use it with `validator_nodes()`.
CI
=> Detect early if a validator sent the wrong certificates.

linera-chain/src/block_tracker.rs
**Description:**
1. Corrected `timestmap` → `timestamp`
=> fix: typo in documentation files

linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-service/tests/local_net_tests.rs
Currently a validator cannot process a child chain without syncing all the ancestor chains up to the point where the child chain was created.
When a client uploads the first block of a chain, the validator should look up the committee and verify the signatures. It should then, based on that, accept the chain description blob, even if it doesn't have the parent chain.
CI
- closes #4085
=> Don't require ancestor chains in validators.

linera-web/.envrc, linera-web/rust-toolchain.toml
It's annoying to have to remember to select the nightly toolchain when building `linera-web`.
Add a `.envrc` for direnv/Nix and a `rust-toolchain.toml` symlink for rustup so that invoking Rust inside `linera-web` will get the right toolchain by default for users of those tools.
Tested locally by me (Nix) and @deuszx (rustup).
=> `linera-web`: add config for automatic nightly toolchain selection

.gitignore, linera-web/.envrc, linera-web/.gitignore, linera-web/package.json, linera-web/signer/typedoc.json, linera-web/tsconfig.json, linera-web/typedoc.json
Externals would like to see docs for the APIs they will need to integrate with.
Add configuration files to document source with [TypeDoc](https://typedoc.org/).
Generated docs locally and they look okay.
I tried to document `@linera/signer` as well, which contains example implementations of the signer interface, but it currently doesn't typecheck, so TypeDoc can't document it.
=> Generate docs for `linera-web` using TypeDoc

kubernetes/linera-validator/grafana-dashboards/linera/general.json
Error rates should be displayed as percentages. Now they're just a number.
Display them as percentages
Before:
After:
=> Error rates should use percentage as unit

Cargo.lock, Cargo.toml, linera-client/Cargo.toml, linera-client/src/benchmark.rs, linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-service/src/cli/main.rs, linera-service/src/cli_wrappers/wallet.rs
We were not processing the inboxes during the benchmarks, which caused the inboxes to just grow indefinitely.
Include the pending messages with the block proposals. This will cause each block to do a bit more work, which will likely force us to use smaller block sizes in the benchmarks to control latency, but will prevent the server's memory from growing indefinitely. 
Will deploy a network and make sure memory isn't linearly increasing anymore, as well as track the inbox sizes.
=> Include pending message bundles in benchmark block proposals

linera-client/src/benchmark.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs
When running benchmarks, if we're sending a very large TPS amount, it is useful to be able to ramp up that TPS.
Add an option to add a delay for subsequent chain groups to be started. This should be set proportionally to the amount of work (TPS) each chain group will be doing.
Tested against a local network, saw that the delay works as expected.
=> Add delay between chain groups for TPS ramp up

linera-client/src/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/test_utils.rs, linera-service/src/node_service.rs, linera-service/src/proxy/main.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs, linera-views/src/error.rs
The `ViewError::NotFound` was used in the query. We want to eliminate it from the `ViewError`. So, this case can be ironed out.
* The `ViewError::not_found` is removed.
* The `read_confirmed_block` returns an option.
* The `read_confirmed_blocks_downward` is eliminated from `linera-storage` and when needed it is inlined (two contexts, one being a test).
* The variant is added to the `ChainClientError`. There are no more functions in `ChainClient` whose error is `ViewError`. 
The CI.
None.
=> Eliminate the `NotFound` for the `read_confirmed_block*`.

linera-client/src/benchmark.rs, linera-core/src/client/mod.rs, linera-service/src/cli/main.rs
Since we redesigned the benchmark client, we don't use blocking threads there anymore, so setting this to a large number is no longer required.
Stop manually setting the number of blocking tokio threads
Have been testing this during my benchmarking
=> Stop setting tokio blocking threads manually for multi-benchmark

kubernetes/linera-validator/templates/shards.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl, linera-core/src/chain_worker/state/mod.rs
We'll be starting to set the tokio worker threads in the server binary from `lineractl`.
Add option for tokio worker threads and blocking threads.
Deployed a network locally with this, saw that it didn't set the env variable, as expected.
Deployed a network using `lineractl`, saw that it did set the env variable, as expected.
=> Add tokio threads options to shard deployment

kubernetes/linera-validator/templates/shards.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl, linera-client/src/benchmark.rs, linera-core/src/chain_worker/state/mod.rs
Right now we have a number of chain groups, all together trying to reach a certain BPS. They check if the BPS was reached by checking this one atomic variable.
However, you could reach a situation where one of the chain groups achieves the BPS, but the other `num_chain_groups - 1` chain groups all have block proposals in flight. Meaning that in the worse case we could be overshooting our BPS by 2 * BPS - 1 🤦🏻‍♂️
Make each chain group have a BPS share that they need to achieve, which is controlled by their own atomic variable.
The BPS control task will now sum all those atomic variables to make sure we reached the desired BPS/TPS.
This prevents the race condition that causes us to overshoot the BPS.
Tested on a deployed network. Was seeing before that we were overshooting by 1.5x. Now …
=> Shard BPS per chain group to prevent oversending requests

linera-base/src/unit_tests.rs, linera-sdk/src/base/conversions_from_wit.rs, linera-sdk/src/base/conversions_to_wit.rs, linera-sdk/src/contract/conversions_from_wit.rs, linera-sdk/src/contract/conversions_to_wit.rs, linera-witty/src/primitive_types/array.rs
@Twey found a bug in the handling of `[u8; 20]` in Witty.
Fix. Add a unit test.
CI
Fixes https://github.com/linera-io/linera-protocol/issues/4182
=> Fix witty handling of array20

kubernetes/linera-validator/templates/proxy.yaml
An omission of the correct `Service` name in the `serviceName` definition of the proxy statefulset meant that proxy instances could not be uniquely resolved by ordinal.
Update the `serviceName`.
As was suggested by @Twey, it might be better to not use ordinals, but instead do DNS lookups to resolve individual IP addresses and use those instead. Since individual proxy instances are undifferentiated, ordering is unimportant (unlike the current shard setup for example).
=> Fixed a bug where shards could not resolve individual proxies.

linera-chain/src/block.rs, linera-chain/src/chain.rs, linera-chain/src/data_types.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/tests/local_net_tests.rs
If a client creates a block receiving messages from a chain with gaps, and a validator doesn't have that chain yet, the client currently has no way of convincing the validator that the proposal is correct, because the validator expects the whole sender chain as proof of the sent messages.
Make validators accept confirmed certificates for blocks on chains with gaps. If there is a gap, blocks should only be preprocessed, instead of fully processed - like on the clients.
CI with an added test exercising the problematic scenario
- closes #4160
=> Leave gaps in sender chains on the validator side

.github/workflows/rust.yml
The file `LineraTypes.sol` is generated from the `LineraTypes.yaml` but this is not tested in the CI.
The `serdegen` is installed by using `cargo`. Then the file is generated and then tested for equality.
The CI is precisely the point.
None.
=> Test the generation of the code in the CI.

linera-web/.gitignore, linera-web/docs/README.md, linera-web/docs/classes/Client.md, linera-web/docs/classes/Frontend.md, linera-web/docs/classes/Wallet.md, linera-web/docs/functions/default.md, linera-web/docs/functions/initSync.md, linera-web/docs/functions/wasm_thread_entry_point.md, linera-web/docs/interfaces/Signer.md, linera-web/docs/type-aliases/ReadableStreamType.md, linera-web/package.json
Make the docs available in [`linera-documentation`](https://github.com/linera-io/linera-documentation/) without having to build them there.
Check them in.  It would be nice to check in CI that they haven't changed, but this is left as future work.
Use in `linera-documentation`.
=> `linera-web`: check in built Markdown docs

Cargo.toml, linera-execution/Cargo.toml
The `blst` library is used as a dependency in `revm`, but it has the disadvantage of being an encapsulation of a "C" library, which prevents its usage on Wasm.
Remove "blst" as a dependency. This is fine since an examination of the source code of "revm" reveals that if this feature is not enabled then "revm" uses the "ark-bls12-381" library. The name of the encapsulation being `crypto_backend`.
The CI.
None.
=> Remove the "blst" dependency.

linera-web/signer/src/metamask.ts
`linera-web` demos involving Metamask integration fail on devnet b/c we don't install the `buffer` dependency. 
Replace usage of `Buffer.from` with this simple utility. Otherwise all clients integrating with via the Metamask integration are required to install the `buffer` dependency and manually assigning the Buffer object to the browser's window object.
Manually
=> Add a utility function to map UInt8Array to Hex string

kubernetes/linera-validator/helmfile.yaml, kubernetes/linera-validator/scylla-setup/gke-daemonset-raid-disks.yaml, kubernetes/linera-validator/scylla-setup/local-ssd-sc.yaml, kubernetes/linera-validator/scylla-setup/nodeconfig.yaml, kubernetes/linera-validator/values-local.yaml.gotmpl
There's this `NodeConfig` that we can use to setup the disks properly for Scylla, and do a few other optimizations to the setup.
Use the `NodeConfig` for Scylla, but continue using the existing hook script to setup local SSD for the shards, when using `DualStore`. Make sure the Scylla stuff only runs in the Scylla VMs by using placements.
Deployed a network with these changes both using `DualStore` and using just `ScyllaDB`, both work.
=> Use NodeConfig to setup Scylla

linera-service/src/cli/main.rs
We don't need `--wait-for-outgoing-messages` anymore. Forgot to remove it on https://github.com/linera-io/linera-protocol/pull/4177
Remove the check enforcing it
Ran it
=> Remove unnecessary check

linera-service/src/proxy/grpc.rs
In the absence of an explicitly set limit, the GCP load balancer was defaulting to 100, effectively limiting the maximum number of chains in the wallet to 100 (as the client starts one stream per chain in the wallet).
Explicitly set the limit to as high a value as possible.
- CI
- Manually attempt to reproduce #3898 on the devnet after deploying the fix
=> Explicitly set max_concurrent_streams to u32::MAX-1

default.nix, flake.lock, flake.nix, linera-web/.envrc
We'd like people who like Docker to be able to use Docker to build our software.
Build a composite Rust toolchain using [`nixup`](https://github.com/Twey/nixup) that combines our stable and nightly Rust toolchains in a way that's compatible with rustup so we can combine both `devShell`s into one `devShell`.  Export a build output `packages.<arch>.container` that builds a Docker image containing the default development shell.
As an aside, clean up a couple of things in the Nix:
- fix macOS building
- filter the source with `nix-gitignore` to reduce the data copied to the Nix store
This has been tested locally on my machine (`x86_64-linux`) and @deuszx' macOS machine (`aarch64-arm-darwin`).
- [reviewer …
=> Add development environment in Docker

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-execution/src/system.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
The `ReadBlob` operation was added for testing; it reads a blob but then drops the result.
Rename it to `VerifyBlob` and only assert the blob's existence.
CI
- Closes #2490
=> Replace `ReadBlob` with `VerifyBlob`

linera-chain/src/block_tracker.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-execution/src/execution.rs, linera-execution/src/transaction_tracker.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/test_execution.rs
An examination of the source code reveals that the variable `next_message_index` is never used.
Eliminate it completely.
The CI.
None.
=> Remove the `next_message_index` as it is not used.

linera-chain/src/chain.rs, linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/node.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
The client will only send a block proposal to the validators if it has all events that were read during execution. Validators that don't have any of the events return an error.
* Unify all missing event errors: `EventsNotFound(Vec<EventId>)`.
* In the `ValidatorUpdater`, when making a proposal, send the publisher chains and retry.
A client test using the social example was extended. The new test fails without this functionality.
- Closes https://github.com/linera-io/linera-protocol/issues/4254.
=> Send missing events to validators.

linera-sdk/src/views/system_api.rs, linera-storage-service/src/client.rs, linera-storage/src/db_storage.rs, linera-views/src/backends/dual.rs, linera-views/src/backends/dynamo_db.rs, linera-views/src/backends/indexed_db.rs, linera-views/src/backends/journaling.rs, linera-views/src/backends/lru_caching.rs, linera-views/src/backends/memory.rs, linera-views/src/backends/metering.rs, linera-views/src/backends/rocks_db.rs, linera-views/src/backends/scylla_db.rs, linera-views/src/backends/value_splitting.rs, linera-views/src/context.rs, linera-views/src/store.rs, linera-views/src/test_utils/mod.rs, linera-views/src/test_utils/performance.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/set_view.rs
* Simplify code.
As pointed out by teammates, this optimization is only used for `DynamoDb` and doesn't apply to the databases that we use in production.
* Remove associated types Keys and KeyValues
* Remove the traits
I stop short of removing the iterator objects in DynamoDb. We could probably simplify the code some more but it's non-trivial and could be slightly slower. 
CI
=> Remove associated types Keys and KeyValues in KV store traits

linera-base/src/data_types.rs, linera-execution/solidity/Linera.sol, linera-execution/solidity/LineraTypes.sol, linera-execution/solidity/LineraTypes.yaml, linera-execution/src/evm/data_types.rs, linera-execution/src/evm/mod.rs, linera-execution/src/evm/revm.rs, linera-execution/tests/revm.rs, linera-service/tests/fixtures/erc20_shared.sol, linera-service/tests/fixtures/evm_example_execute_message.sol, linera-service/tests/fixtures/evm_example_process_streams.sol, linera-service/tests/fixtures/evm_test_linera_features.sol, linera-service/tests/linera_net_tests.rs
We want the EVM applications to be able to fully access the Linera functionalities.
Here we extend it by adding access to the Linera balances, authenticated signer
as well as other features.
The work simply adds the following functionalities to EVM applications:
* chain_timestamp
* chain_balance
* owner_balance
* owner_balances
* balance_owners
* authenticated_signer
* authenticated_caller_id
* query_service
As it was it looked simple but several problems showed up:
* New types have to be added, but since we do not have a type `uint256` in YAML file, we have to use a `[u8; 32]`.
* This forces a conversion to `uint256` to do in the code. The problem is that this externalize some types, so we have an `AccountOwnerBalance` and `AccountOwnerBalanceInner`.
* In order to force having all the …
=> Provide access to further linera functionalities in the EVM.

linera-base/src/prometheus_util.rs, linera-client/src/config.rs, linera-rpc/src/grpc/client.rs, linera-service/src/cli_wrappers/local_net.rs, linera-service/src/exporter/main.rs, linera-service/src/exporter/metrics.rs, linera-service/src/exporter/runloops/indexer/client.rs, linera-service/src/exporter/runloops/validator_exporter.rs, linera-service/src/exporter/storage.rs, linera-service/tests/local_net_tests.rs
A slightly adjusted backport of #4244
I also backported the PR that removes the necessity to provide a path to genesis config. This simplifies the command to run the exporter.
CI and manually.
=> Add metrics to the block exporter

linera-base/src/data_types.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
The client makes a lot of chain info queries, causing unnecessary round trips. One example is `ValidatorUpdater::send_chain_information`, where we always first request the chain info from the validator, to learn which blocks they are missing.
When reading events we are not always using the oracle mechanism. that can cause confirmed blocks to fail even though the proposal succeeded.
* In `send_chain_information`, always send the highest block right away. Often that is enough, and the response will confirm that.
* In `send_chain_information`, only send the timeout certificate if it is relevant for the validator.
* On `NodeError::InactiveChain`, send blobs, not certificates. (This may be unreachable anyway; needs a closer look: https://github.com/linera-io/linera-protocol/issues/3927)
* Use …
=> Avoid redundant chain info requests; fix event oracles.

linera-execution/src/execution_state_actor.rs, linera-execution/src/runtime.rs
In #4248 I needlessly moved `TransactionTracker` to the execution state actor and back.
Use the tracker in the runtime directly, call the actor only in the `None` case.
CI
=> Avoid moving the transaction tracker in `ReadEvent`.

linera-core/src/chain_worker/state/attempted_changes.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/worker.rs, linera-rpc/src/grpc/conversions.rs, linera-rpc/src/grpc/server.rs, linera-service/src/exporter/exporter_service.rs, linera-service/tests/linera_net_tests.rs
We want to include the information about published events in the notifications so that clients can choose whether they are interested in the particular blocks or not.
Add an `event_streams` field to the `NewBlock` notification, containing the stream IDs of streams to which the block published any events.
CI
- #4261 (this is just the validator-side part, the client-side part of actually using the event information in the notifications will be done in a follow-up PR)
=> Add information about published events to the NewBlock notification

linera-base/src/prometheus_util.rs, linera-chain/src/lib.rs, linera-chain/src/manager.rs, linera-client/src/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/node.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/updater.rs, linera-core/src/worker.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
We've noticed that in our app demos we make more than optimal # of requests when proposing a block. Obviously we should try to do as little work as possible.
CI
=> Update validators less eagerly - fewer queries when proposing a block

linera-chain/src/chain.rs, linera-core/src/chain_worker/state/mod.rs
We are currently debugging https://github.com/linera-io/linera-protocol/issues/4299. This could, among other things, be caused by calling `save()` on a chain state view while there are read-only clones of that view being used by other tasks.
Move the `save()` call to the relevant call site, and clear the shared chain views before saving.
Unfortunately this change did not fully fix the cache issue, though.
- Related to #4299
=> Don't save in `ensure_is_active`.

linera-client/src/benchmark.rs, linera-client/src/chain_listener.rs, linera-client/src/client_context.rs, linera-client/src/client_metrics.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/test_utils.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/schema_export.rs
We're changing things to use the full client flow from benchmarks. This is part of a whole refactor to make the benchmarks more "realistic".
By using the full flow, we also had to rewrite how we do the client logging of timing metrics. We'll have a timing tokio task running that will manage the histograms, and whoever wants to log the time of something sends a message to this tokio task.
Then every some number of seconds we print that information to the screen for the user.
Ran locally, saw the metrics being correctly printed
=> Use full client flow on benchmarks

Cargo.lock, linera-client/Cargo.toml, linera-client/src/benchmark.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs
Right now every chain sends a cross chain message to one other chain exclusively. So each chain needs to receive just one gRPC message from 1 other chain.
To make the benchmarks more realistic, we need to make it so that all chains send requests to all other chains, generating many more gRPC messages and network traffic.
Ran locally and saw that things work as expected
=> Send transactions to every other chain in the chain group

.github/workflows/rust.yml, Cargo.lock, linera-execution/src/lib.rs, linera-execution/src/system.rs, linera-explorer-new/server/database.js, linera-explorer-new/server/index.js, linera-explorer-new/src/components/BinaryDataSection.tsx, linera-explorer-new/src/components/BlockDetail.tsx, linera-explorer-new/src/components/CopyableHash.tsx, linera-explorer-new/src/components/ExpandableSection.tsx, linera-explorer-new/src/hooks/useDatabase.ts, linera-explorer-new/src/types/blockchain.ts, linera-explorer-new/src/utils/database.ts, linera-indexer/lib/Cargo.toml, linera-indexer/lib/src/db/mod.rs, linera-indexer/lib/src/db/sqlite/consts.rs, linera-indexer/lib/src/db/sqlite/mod.rs, linera-indexer/lib/src/db/sqlite/tests.rs
Currently only a few fields (from the header, body or messages) are stored in a denormalized way in a database – ie they are stored in dedicated fields – while the whole block is stored as a blob data. We want to show more details to user, this could be done in one of the two ways:
1. load the blob, deserialize in frontend
2. store in denormalized way and load directly in frontend
Implement the approach `#2` – add more fields to database tables and store block's details directly there. Also, use the new data to show on the frontend of the explorer.
Some refactoring was done as part of the PR:
- add a dedicated type `ExpandableSection` that shows only the metadata of the section and expands on click to show more
- add `CopyableHash` to present a text that can be copied.
Manual
- Nothing to …
=> Display more details.

linera-service/tests/local_net_tests.rs
Right now the tests start and run just for one second, which since we're doing a bunch of extra stuff now, it's not enough time. From the logs it seems like we're trying to kill things before some messages sent with `wait_for_outgoing_messages` (not coming from the benchmark specific code) actually get delivered. So it seems like we just wait forever in that case.
Run the tests for slightly longer (5 seconds instead of 1), and that seems to prevent us from killing things too early. Might be a good follow up to see if blocking cross chain messages should timeout?
CI should pass now
=> Run benchmark e2e tests for a bit longer

linera-execution/src/execution.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs, linera-execution/tests/test_execution.rs
Those functions were returning errors when no error could occur.
Simplify them.
CI.
None
=> Simplify the `add_outgoing_message(s)` functions.

linera-chain/src/certificate/lite.rs, linera-chain/src/data_types.rs, linera-chain/src/test/mod.rs, linera-chain/src/unit_tests/data_types_tests.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/worker_tests.rs, linera-core/src/updater.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/block.rs
The public key is known from the context everywhere, and having it explicitly in `Vote` and `LiteVote` just duplicates data and creates more error cases.
Remove the redundant field (with Claude).
CI
=> Remove public key from `Vote`.

Cargo.lock, Cargo.toml, linera-client/Cargo.toml, linera-client/src/benchmark.rs, linera-client/src/client_context.rs, linera-core/src/client/mod.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/cli_wrappers/wallet.rs
Right now the benchmark client processes only do transfer amongst chains in their wallets. We should have a way of these processes be able to send transfers to chains in other wallets.
Pass a file to the benchmark client processes with all the chain IDs (from across wallets) that we can send transfers to. Enable that via `multi-benchmark` with an option
Ran this with the new option locally against a local network, seems to do what it's supposed to.
=> Make chains transfer to each other across benchmark processes

linera-core/src/client/mod.rs, linera-faucet/client/src/lib.rs, linera-service/src/cli/main.rs, linera-service/src/exporter/runloops/validator_exporter.rs, linera-service/src/util.rs, linera-web/src/lib.rs
Web client keeps failing on block proposal due to the usage of std::time when constructing a proposal.
Fix all occurences of std::time to linera_base::time
CI and manual
=> Update more occurences of std::time to use linera_base::time

linera-chain/src/lib.rs, linera-client/src/error.rs, linera-core/src/client/mod.rs, linera-core/src/lib.rs, linera-core/src/local_node.rs, linera-execution/src/lib.rs
Public items make it hard to detect unused code.
I let Claude find and remove unused error variants. I also made some modules in `linera-core` private.
CI
=> Remove unused error variants; make some modules private.

linera-execution/src/system.rs, linera-indexer/lib/src/db/sqlite/mod.rs, linera-rpc/tests/snapshots/format__format.yaml.snap
This was a leftover from previous works.
Simple removal.
The CI.
None.
=> Remove the `ApplicationCreated` that is no longer useful.

linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-service/tests/linera_net_tests.rs
During the implementation of `transfer` operations in the EVM, we face the problem that while the 
`ContractRuntime::transfer` immediately debits the source, and the destination receives the amount
only on the next block.
While this makes complete sense if the destination chain is different from the source chain, there is a use
case for transfer operations within the same chain that are done immediately without emitting messages.
Fixes #3486 
The code of `SystemExecutionStateView::transfer` has been changed so that it does not emit a message if the source chain is the same as the destination chain.
The operations that have been corrected are:
* `Claim`
* `Transfer`
* `Withdraw`
The CI.
Several tests in `worker_test.rs` had to be changed because the emission of messages had changed.
The …
=> Make `ContractRuntime::transfer` synchronous for local transfers.

examples/counter-no-graphql/src/service.rs, linera-sdk/src/service/runtime.rs, linera-sdk/src/service/test_runtime.rs, linera-sdk/src/test/mock_stubs.rs
The `application-creator-chain-id` was not in `ServiceRuntime` which was an oversight.
Fixes #3606 
The implementation is straightforward.
The CI.
The test has been added to the `counter-no-graphql`.
None
=> Add the `application-creator-chain-id` to the ServiceRuntime.

linera-client/src/benchmark.rs, linera-service/src/cli/main.rs
Right now we're checking just the number of chains in a wallet, but if we're using cross wallet transfers, we need to take all chains from all wallets into consideration.
Take all chains from all wallets used in the benchmark into consideration
Ran this against a deployed network
=> Check transaction number on total chains

Cargo.lock, Cargo.toml, examples/Cargo.lock
HTTP/2 implementations are vulnerable to "MadeYouReset" DoS attack through HTTP/2 control frames. More information here: https://www.kb.cert.org/vuls/id/767506
Some `h2` versions that we're indirectly using are vulnerable to that attack.
Upgrading the necessary crates, so that they use `h2` versions that have the vulnerability patched, as suggested in this article: https://seanmonstar.com/blog/hyper-http2-didnt-madeyoureset/
CI
=> Upgrade h2 and hyper versions to prevent exploit

examples/native-fungible/tests/transfers.rs, linera-base/src/identifiers.rs, linera-chain/src/test/mod.rs, linera-chain/src/unit_tests/chain_tests.rs, linera-client/src/benchmark.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/benches/client_benchmarks.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-core/src/unit_tests/worker_tests.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/graphql.rs, linera-execution/src/system.rs, linera-execution/tests/test_system_execution.rs, linera-indexer/example/tests/test.rs, linera-rpc/tests/format.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-sdk/src/test/block.rs, linera-sdk/src/test/mod.rs, linera-service-graphql-client/gql/service_requests.graphql, linera-service-graphql-client/gql/service_schema.graphql, linera-service/benches/transfers.rs, linera-service/src/node_service.rs, linera-web/src/lib.rs
The Recipient type variant `Burn` is used only for tests. So, we remove it. This let the `Recipient` having just a variant `Account`. And so the `Recipient` type is eliminated.
Fixes #3580 
Straightforward from the description.
The CI.
The tests were restructured accordingly. For some tests the balance is now unchanged. For some tests we introduced another chain.
None.
=> Eliminate the `Recipient` type.

linera-core/src/client/mod.rs, linera-core/src/unit_tests/client_tests.rs, linera-service/src/node_service.rs, linera-web/src/lib.rs
This channel only adds a sender entry into a map. It doesn't need to be `async`.
Make it synchronous.
CI
=> Make `ChainClient::subscribe` synchronous.

linera-core/src/chain_worker/state/mod.rs, linera-service/src/exporter/state.rs, linera-service/src/exporter/storage.rs, linera-views-derive/src/lib.rs, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-2.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-3.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-4.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-5.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-6.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-7.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-8.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code.snap, linera-views/src/views/bucket_queue_view.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/hashable_wrapper.rs, linera-views/src/views/key_value_store_view.rs, linera-views/src/views/log_view.rs, linera-views/src/views/map_view.rs, linera-views/src/views/mod.rs, linera-views/src/views/queue_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/src/views/register_view.rs, linera-views/src/views/set_view.rs, linera-views/src/views/unit_tests/views.rs
An examination of the source code reveals that `clone_unchecked` never returns an error.
The case of `?` are due to the calls to `clone_unchecked`.
Remove the error case.
Note that there are second order effects. For example `fn chain_state_view` no longer needs to return an error.
But this is for subsequent works.
CI,.
None
=> Make the `clone_unchecked` a function that does not return errors.

kubernetes/linera-validator/helmfile.yaml
If running multiple deploys in parallel, you could accidentally run these kubectl commands in the wrong context.
Ensure that all kubectl commands have the proper args specified
Deployed a network with this, works as expected.
=> Always specify kube args in kubectl commands in helmfile

linera-service/src/cli_wrappers/local_net.rs, linera-service/src/exporter/tests.rs, linera-service/tests/local_net_tests.rs
We may want to run with more than 10 validators. A previous PR makes the work on more than 10 validators impossible.
Here we constrain the product `num_validator * num_shard`.
Fixes #4319 
We assign the ports according to the set constants.
For the test `linera-service/src/exporter/tests.rs` we have a leakage of the formula. But this is just one test.
The CI.
The wasm end-to-end tests were run with 20 validators and 1 shard.
None
=> Some update to the way ports are assigned.

examples/non-fungible/src/contract.rs, examples/non-fungible/src/lib.rs, examples/non-fungible/src/service.rs, linera-base/src/identifiers.rs, linera-execution/solidity/Linera.sol, linera-execution/solidity/LineraTypes.sol, linera-execution/solidity/LineraTypes.yaml, linera-execution/src/evm/revm.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/wasm/runtime_api.rs, linera-execution/tests/contract_runtime_apis.rs, linera-sdk/src/base/conversions_from_wit.rs, linera-sdk/src/base/conversions_to_wit.rs, linera-sdk/src/contract/conversions_from_wit.rs, linera-sdk/src/contract/conversions_to_wit.rs, linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs, linera-sdk/src/lib.rs, linera-sdk/src/service/runtime.rs, linera-sdk/src/service/test_runtime.rs, linera-sdk/wit/base-runtime-api.wit, linera-sdk/wit/contract-runtime-api.wit, linera-service/tests/linera_net_tests.rs
The `BaseRuntime` and `ContractRuntime` are a little bit disorganised with their input and output:
* `read_data_blob` / `assert_data_blob_exists` are taking a `CryptoHash` as input.
* `create_data_blob` is returning a `BlobId`.
The natural type is the `DataBlobHash` that is the natural type for this.
Previous to this PR, it is in the `linera-sdk`. We are forced to move it to `linera-base`.
The CI.
None.
=> Move to the use of DataBlobHash.

linera-client/src/client_context.rs
In https://github.com/linera-io/linera-protocol/pull/3099 I added a `prepare_chain` call that shouldn't be necessary, because `test_end_to_end_listen_for_new_rounds::storage_test_service_grpc` was flaky for me locally.
I believe the underlying issue may have been fixed in https://github.com/linera-io/linera-protocol/pull/4361.
Remove the unnecessary call again.
It now passed for me locally 10 times in debug and 10 times in release mode.
(I believe we didn't see the failure in CI.)
- Fixes https://github.com/linera-io/linera-protocol/issues/3100.
=> Remove unnecessary `prepare_chain` call.

Cargo.lock, Cargo.toml, examples/Cargo.lock, examples/Cargo.toml, examples/publish-read-data-blob/Cargo.toml, examples/publish-read-data-blob/README.md, examples/publish-read-data-blob/src/contract.rs, examples/publish-read-data-blob/src/lib.rs, examples/publish-read-data-blob/src/service.rs, examples/publish-read-data-blob/src/state.rs, linera-base/src/data_types.rs, linera-chain/src/block_tracker.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/transaction_tracker.rs, linera-execution/tests/test_execution.rs, linera-service/Cargo.toml, linera-service/tests/linera_net_tests.rs, linera-storage/src/lib.rs
Following PR #4247, PR #4278, and PR #3382, we face the scenario where a contract can create a blob
but not have it available right away. This concerns the access to Blob Bytecode, Blob ApplicationDescription, and
Blob Data.
This PR addresses those problems.
Fixes #4287 
Fixes #4279 
This PR addresses the problem with the data blob. But it also addresses the issues for the ApplicationDescription blob
and the contract blobs.
There are three scenarios to cover:
* The blob is created in one block and read in another block.
* The blob is created in one operation and read in the same operation.
* The blob is created in two different operations of the same block.
The first scenario is already working correctly.
The second scenario is addressed with the addition of the test of `created_blobs` in …
=> Resolve the blob persistence problem

Cargo.lock, Cargo.toml, linera-chain/src/manager.rs, linera-core/Cargo.toml, linera-core/src/chain_worker/state/guard.rs, linera-core/src/client/mod.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/src/exporter/test_utils.rs
Proposals by other chain owners that the client learns about from validators can fail to execute locally, e.g. due to different oracle values. But in multi-leader rounds, clients need to take not of such failed proposals anyway, so they know that they shouldn't also make a conflicting proposal in the same round.
Add another `signed_proposed_block` field to the chain manager to keep track of this.
A regression test was added; and it failed without this fix.
- Closes #2971.
=> Fix "skipped proposal" scenario; take note of proposals even if they fail.

linera-execution/src/system.rs
This is part of the execution state view, so we should cache its hash.
Make it a `HashedMapView`.
CI; I believe this should not change semantics, only slightly improve performance.
=> Make `event_subscriptions` a `HashedMapView`.

linera-execution/src/runtime.rs, linera-execution/src/unit_tests/runtime_tests.rs, linera-execution/tests/contract_runtime_apis.rs
Fix authenticated signer.
As pointed out in #4374, we were using the transaction instead of the last application on the calling stack, effectively ignoring whether calls were "authenticated" or not.
* Fix the bug
* Remove the field that caused the confusion in the first place
CI + new unit test
I verified that the new unit test fails before the fix.
=> Fix authenticated signer syscall and remove the offending field

Cargo.lock, examples/Cargo.lock, examples/counter/Cargo.toml, examples/counter/README.md, examples/counter/src/contract.rs, examples/counter/src/lib.rs, examples/counter/src/service.rs, examples/counter/src/state.rs, examples/counter/tests/single_chain.rs, examples/meta-counter/src/contract.rs, linera-core/src/unit_tests/wasm_client_tests.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-service/tests/linera_net_tests.rs
The `counter` example was processing GraphQL queries quite differently from other examples.
We put it in line with other examples.
Fixes #2854 
The work is fairly standard, but forces the introduction of a `CounterOperation` since the input
must satisfy the `GraphQLMutationRoot` trait.
The CI.
None.
=> Make the handling of GraphQL in the counter example in line with other contracts.

linera-base/Cargo.toml, linera-base/src/data_types.rs, linera-execution/src/runtime.rs, linera-execution/tests/test_execution.rs, linera-storage/src/lib.rs
We are doing some cloning operations for blobs. This occurs in the `TransactionTracker` with the `previously_created_blobs`.
Fixes #2389
The implementation is done with the `serde_with` for the serialization.
The CI.
A test has been introduced for this serialization and hash.
None
=> Switch the `Blob` from `Box<[u8]>` to `Arc<Box<[u8]>>`.

linera-base/src/data_types.rs, linera-base/src/identifiers.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/node_service.rs
The GraphQL definitions are a little bit inconsistent. Here we correct them.
Fixes #1308 
The following changes are made:
* Precising the role of the `ChainId`. For example, for `openChain`, a naive user may think that the input `chainId` is going to be the chain ID.
* Removing the fact that chains are subscribed to epoch changes from the admin chain. I think this is not useful as it is an implementation detail.
* Removing notes like "system API", which are not useful.
* Remove "(or activates)" which is unclear to me and probably obsolete.
* I added the EVM-relevant notes that occurred in a few places.
The CI should take care of the schema update.
None
=> Make sure all fields in the GraphQL schema are documented

linera-web/src/lib.rs
Help measure timings for benchmarking.
Add a log line when we start an application query.
- be released in a demo hotfix.
- be released in a demo hotfix.
=> `linera-web`: add a log output at the start of application queries

CLI.md, linera-client/src/benchmark.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs
Right now the default is for every chain to always send transfers to every other chain, in a way that in each block we cycle through the chains.
Add an option so that we continue sending chains to every other chain, but every block contains transactions to just one of the other chains, and we cycle through chains per block instead of per transfer.
Deploy a network and test this mode against it.
=> Add single destination per block option to benchmark client

linera-core/src/client/mod.rs, linera-core/src/unit_tests/wasm_client_tests.rs
I can't reproduce https://github.com/linera-io/linera-protocol/issues/4422 locally, so we have to try to get more helpful logs in CI if it happens again.
Improve log messages.
Also fix one `continue` in `synchronize_chain_state_from`: If we can't download any of the required blobs we can skip this proposal immediately, not just this blob.
CI
- Related to https://github.com/linera-io/linera-protocol/issues/4422.
=> Improve log messages in `synchronize_chain_state_from`.

linera-core/src/node.rs, linera-core/src/remote_node.rs, linera-core/src/unit_tests/test_utils.rs, linera-rpc/proto/rpc.proto, linera-rpc/src/client.rs, linera-rpc/src/grpc/client.rs, linera-rpc/src/message.rs, linera-rpc/src/simple/client.rs, linera-rpc/src/simple/server.rs, linera-rpc/tests/snapshots/format__format.yaml.snap, linera-service/src/exporter/test_utils.rs, linera-service/src/proxy/grpc.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs
Continuation of the work on improving performance of clients. Trying to decrease # of roundtrips between clients and validators.
It was noted that we often make two requests to download a certificate for blob:
1. `BlobLastUsedBy` – returning a certificate hash
2. `DownloadCertificate` – returning the certificate.
Here we introduce a new endpoint – `BlobLastUsedByCertificate(blob_id) -> ConfirmedCertifiate` – which does both things in one query.
Note that the new endpoint is introduced in proxy only.
This decreases number of necessary network roundtrips from 9 to 6:
CI
- Nothing to do / These changes follow the usual release cycle. **OR**
- These changes …
=> Fetch certificate last used the blob

linera-service/tests/linera_net_tests.rs
`test_wasm_end_to_end_allowances_fungible` is flaky: If client 2 hasn't finished syncing or processing notifications when `app2.assert_balances(expected_balances)` is called, the assertion can fail, because the block where the application was created isn't seen yet. Same for client 3.
Call `sync` _after_ creating the application.
CI: The test should not be flaky anymore.
=> Sync after publishing the app to make allowance test not flaky.

linera-rpc/src/grpc/client.rs
`is_retryable` was originally used only for gRPC _streams_, but is now used in other requests, too. The error-level logs in it are not appropriate anymore.
In particular, `NotFound` is expected in some cases. And in general, the logs should never be error-level, because they can be caused by a single faulty validator.
Fix logs and log levels.
CI
=> Fix spurious error logs in `is_retryable`.

.gcloudignore
After #4383, we now have a dangling symlink in the repository, that points to the compiled `linera-web` once built. However, `gcloud builds` (which is what we use in `lineractl` to build our Docker Images) doesn't like dangling symlinks.
Add the dangling symlinks to `.gcloudignore` to make sure `gcloud` commands ignore it, and the builds succeed.
Did a build with `gcloud builds` and now it works again
=> Ignore dangling symlinks for gcloud

kubernetes/linera-validator/templates/proxy.yaml, kubernetes/linera-validator/templates/shards.yaml, linera-service/src/cli_wrappers/helmfile.rs
We're splitting the proxies, shards, monitoring, etc into separate VMs for better resource management and isolation.
We need to add these tolerations to ensure that the proxies and shards will only get scheduled in the appropriate VMs
Deployed a network with these changes plus XXX, saw the pods were deployed into separate VMs, as expected
=> Add tolerations for shards and proxy pods

linera-core/src/client/mod.rs, linera-core/src/remote_node.rs, linera-service/src/cli/main.rs, linera-service/tests/local_net_tests.rs
We want to make sure the network works fine even after many reconfigurations, and even if none of the genesis validators are left.
At the end of the reconfiguration end-to-end test, initialize a new client, request a chain and publish a blob. This test actually failed! The following two changes make it pass:
* In `wallet init`, synchronize the admin chain, trusting the validators provided by the faucet (part of https://github.com/linera-io/linera-protocol/issues/4434).
* Fix a bug in `process_certificates`: Since we are handling a _certificate_, not a block proposal, we don't need additional proof for the missing blobs: The certificate itself is proof for them. So we should only download the blobs themselves, and not try to get another certificate for them.
The reconfiguration test was …
=> Extend reconfig test; sync on `wallet init`; fix blob fetching.

linera-client/src/benchmark.rs, linera-client/src/chain_listener.rs, linera-client/src/unit_tests/chain_listener.rs, linera-faucet/server/src/lib.rs, linera-service/src/node_service.rs, linera-web/src/lib.rs
Currently we don't synchronize the chains when starting up the client.  Now that we also don't pessimistically synchronize chains before performing operations, we sometimes run into the situation where we want to do something with a chain whose blocks haven't been seen yet (e.g. because it came from the faucet), which leads to an error.
Ideally when we find a block from the future we should synchronize the offending chain.  But for now it should be sufficient to make sure to synchronize the initial chains at startup.
Split `ChainListener::run` into two futures: the latter is the full chain listener loop, as before, but first there's an initialization step that synchronizes all the initial chains, and the caller can wait on this in serial to ensure the chains are synchronized before …
=> Two-phase chain listener

linera-core/src/unit_tests/test_utils.rs, linera-execution/src/test_utils/mock_application.rs
There are several `#[allow(dead_code)]` annotations without an explaining comment or link to an issue. Some of them seem to be unnecessary.
Remove them.
CI
=> Remove unnecessary `dead_code` attributes.

linera-base/src/crypto/hash.rs, linera-base/src/identifiers.rs, linera-base/src/unit_tests.rs
`AccountOwner::Address20`'s `Debug` impl prints something like:
```
Address20([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])
```
because the `hex_debug` attribute is in the wrong place.
Put the attribute directly on the field, not the enum variant. The `Debug` impl now says:
```
Address20(0a0a0a0a0a0a0a0a..)
```
Tried it locally.
- Should be backported to testnet and devnet.
=> Fix `Address20` debug format.

Cargo.lock, linera-execution/src/committee.rs, linera-execution/src/graphql.rs, linera-execution/src/policy.rs, linera-faucet/client/Cargo.toml, linera-faucet/client/src/lib.rs, linera-faucet/server/src/lib.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/cli/main.rs
In https://github.com/linera-io/linera-protocol/pull/4437 I used the existing `currentValidators` faucet query in `wallet init` and then made the client synchronize the initial admin chain from a committee where all these validators have the same weight.
Add a `currentCommittee` query that returns the actual current committee, and use that to synchronize.
The reconfiguration test exercises this.
- These changes should be backported to devnet and testnet, published in an SDK and deployed in the faucet.
- Closes https://github.com/linera-io/linera-protocol/issues/4434.
=> Add `currentCommittee` to the faucet; use it in `wallet init`.

kubernetes/linera-validator/scylla-setup/gke-daemonset-raid-disks.yaml
Now that we have multiple VMs for different things, we need to adjust the tolerations in the local-csi-driver so it runs in the VMs that could have local SSDs.
Add shards tolerations to local-csi-driver config
Deployed a dual store + local ssd network using this code, it works.
=> Add tolerations for the new shards VM when starting the local-csi-driver

linera-chain/src/block_tracker.rs, linera-core/src/unit_tests/wasm_worker_tests.rs, linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/lib.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs, linera-execution/src/test_utils/mod.rs, linera-execution/src/unit_tests/runtime_tests.rs, linera-execution/src/unit_tests/system_tests.rs, linera-execution/tests/contract_runtime_apis.rs, linera-execution/tests/fee_consumption.rs, linera-execution/tests/revm.rs, linera-execution/tests/test_execution.rs, linera-execution/tests/test_system_execution.rs, linera-execution/tests/wasm.rs
The transaction tracker is a field in the runtime but also passed into some execution state methods. In some cases, we take the tracker from the runtime, send it to the execution state actor, send it back and put it back into the runtime field. This is confusing and error-prone.
Make the `ExecutionStateActor` a struct that borrows the state, tracker and resource controller.
CI
=> Make execution state actor borrow txn tracker & resource controller.

linera-core/src/client/mod.rs
We try to avoid `let _ =` in general: https://github.com/linera-io/linera-protocol/pull/4413#discussion_r2302019697
Deduplicate the code to send timing information in the chain client implementation, and log a warning if sending fails.
CI
- (Would be no problem to backport.)
=> Extract `send_timing` method; log errors.

linera-core/src/unit_tests/client_tests.rs
This test is `#[ignore]`d because it's flaky: If the faulty validators respond before the other ones start processing the proposal, neither of them will have the proposal in their chain manager.
Also, `test_sparse_sender_chain` is flaky: If the randomly chosen validator (the first in the committee, i.e. by public key) is faulty, processing the notification will fail.
Explicitly handle the proposal in one of the validators to make sure the test is set up for the intended scenario.
In `test_sparse_sender_chain`, use two validators with no faulty one, so the selected validator is guaranteed to have the block.
I ran it 20 times locally and it always passed.
- (Backporting would be no problem.)
- Closes #3860.
- [reviewer …
=> Fix and re-enable `test_finalize_validated`.

linera-execution/src/execution.rs, linera-execution/src/execution_state_actor.rs, linera-execution/src/runtime.rs, linera-execution/src/system.rs
The `linera-execution` code has several possible cleanups.
The following operations are done:
* Make `fn close_chain` no longer async and no longer returning error.
* Make `fn handle_query` no longer async and no longer returning error.
* Make `fn finish_call` no longer returning error.
The CI.
None.
=> Clean the execution code.

linera-core/src/chain_worker/state.rs, linera-core/src/unit_tests/worker_tests.rs
`NewRound` notifications are mainly needed for single-leader mode, where they are triggered by timeout certificates.
However, in multi-leader mode, in case of failed proposals, they are also useful, so that the other owners can avoid making a conflicting proposal in the same round.
Send `NewRound` notifications in `handle_block_proposal`, too.
An assertion was added to a worker test.
- Closes #4472.
=> Send `NewRound` notifications after proposals.

linera-views-derive/src/lib.rs, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_C.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_C_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_CustomContext.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_CustomContext_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__GenericContext_T_.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__GenericContext_T__with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__path__to__ContextType.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__path__to__ContextType_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_C.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_C_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_CustomContext.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_CustomContext_with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__GenericContext_T_.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__GenericContext_T__with_where.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__path__to__ContextType.snap, linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__path__to__ContextType_with_where.snap
It has recently been indicated in PR #4347 that the use `ChainId` in a message would be a waste of space.
But there are other wastage of key space that can be reduced.
Fixes #2391
We check for the number of entries in views obtained by `linera-views-derive`. If lower than 256, we convert to `u8`.
It is likely that we need to remove as well the `linera_views::views::MIN_VIEW_TAG`.
CI.
It is definitely breaking the testnet.
None
=> Update the way that keys are build in views obtained by `linera-views-derive`.

linera-client/src/chain_listener.rs, linera-client/src/client_context.rs, linera-client/src/unit_tests/chain_listener.rs, linera-client/src/unit_tests/wallet.rs, linera-client/src/wallet.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli/main.rs, linera-service/src/schema_export.rs, linera-service/src/wallet.rs, linera-web/src/lib.rs
The `linera wallet show` presents the data on the chain being tracked. Other information can be added easily.
Fixes #2958 
The `epoch` is always present in the output of `chain_info_query`. So, it can be added to the `UserChain`
easily.
Possible extension:
* Adding if a chain is closed or not (it suffices to add a boolean to `ChainInfo`).
The readme test case fungible which is the only one with `linera wallet show` has been 
None.
=> Add `epoch` to the `UserChain` and `linera wallet show`

Cargo.lock, linera-rpc/Cargo.toml, linera-rpc/proto/rpc.proto, linera-rpc/src/grpc/client.rs, linera-service/src/exporter/test_utils.rs, linera-service/src/proxy/grpc.rs, linera-storage/src/db_storage.rs, linera-storage/src/lib.rs
During our performance tests it was found that proxies' bottleneck is (de)serialization of certificates when responding to `DownloadCertificatesByHeights` request.
It is a waste of CPU cycles to deserialize data (after loading from the DB) only to serialize it for transporting over gRPC protocol.
This PR:
- adds a new method on the storage `read_certificates_raw` which returns raw bytes of the requested certificates
- adds a new endpoint to `rpc.proto/ValidatorNode` – `DownloadRawCertificatesByHeight` that responds with (bcs) bytes of the requested certificates
- updates proxy code to serve the new endpoint
- the gRPC _client_  does NOT get a new method, instead the old `download_certificates_by_height` is modified to use the new endpoint. **This is safe:** b/c we will release this as a …
=> [testnet] Add new DownloadRawCertificatesByHeight endpoint and use it.

Cargo.lock, linera-web/Cargo.toml, linera-web/package.json, linera-web/signer/package.json
Release a new `linera/client` npm package
* Follow the version number of the rest of the crates.
* Changed the signer version from 0.1 to 0.15.1 as well
CI
=> [testnet] Update linera web client to 0.15.1

.github/workflows/remote_compatibility.yml
Test that we don't break clients (and to some degree validators) on the testnet branch
Run the e2e tests against the existing testnet in CI
Future work:
* An alternative approach would to set up a local network (validator + faucet) with exactly the same commit as the production environment. This could be done in different ways but requires more design.
* It would be nice to also hosted web applications somehow.
CI
=> [testnet] Test remote compatibility on the testnet branch

examples/publish-read-data-blob/README.md, linera-core/src/unit_tests/wasm_client_tests.rs, linera-execution/src/execution_state_actor.rs
#4413 introduced a bug where we record redundant oracle responses:
* `blob_used` itself already records the response, so there is no need to call `replay_oracle_response`.
* If the blob was published or created by this block, there is no reason to record an oracle response either.
Restore the old behavior.
This caused the remote tests against Testnet Conway to break, and with this fix on the `testnet_conway` branch, they work again.
=> Restore old behavior: Don't record oracle if blob known from same block.

linera-core/src/worker.rs
Now that we have sparse chains, `handle_confirmed_certificate` can be called for blocks higher than `next_block_height`. Those won't be _executed_, but we still store their blobs and events etc.
Only record block metrics for the blocks that actually get executed.
We should see more reasonable metrics.
=> Don't record block metrics when preprocessing.

linera-core/src/client/mod.rs
Not all validators are equal. Taking into account their weight during the shuffling makes the validators with more weight more responsible for accessing the
Fixes #2616 
We simply count the weights when doing the random shuffling.
The CI.
None.
=> Change the shuffling to take into account the weight.

configuration/compose/validator.toml, linera-service/src/cli_wrappers/local_kubernetes_net.rs, linera-service/src/cli_wrappers/local_net.rs, linera-service/src/server.rs
Some of the configs were wrong, as well as the port forwarding, making notifications stop working and 3 of the tests fail.
Do the required fixes (wrong address, port forwarding, etc). Fixes https://github.com/linera-io/linera-protocol/issues/4494
Started a local network with `net up --kubernetes`, ran e2e tests against it, they all pass.
=> Fix a few bugs in net up --kubernetes

linera-core/src/client/mod.rs, linera-service/src/cli/main.rs, linera-service/tests/linera_net_tests.rs
Backport of #4532.
`follow-chain` synchronizes the new chain only if `--sync` is specified. Otherwise it doesn't even verify that the chain exists.
Without `--sync`, still download the chain description. If that fails, don't add the chain to the wallet.
An end-to-end test was extended.
- Original PR to the main branch: #4532.
=> Always fetch the chain description on `follow-chain`. (Backport of #4532)

examples/pnpm-workspace.yaml
`fungible` was incorrectly named as the workspace member, instead of `native-fungible`, which could lead to some confusing issues when building the `native-fungible` frontend (e.g. `vite` would not be found during a Vite build step).
Fix it.
`pnpm install` in the `native-fungible` directory.
=> `pnpm-workspace.yaml`: name `native-fungible` as workspace member

Cargo.lock, Cargo.toml, linera-base/Cargo.toml, linera-base/src/time.rs
We ran into a variant of https://github.com/whizsid/wasmtimer-rs/issues/22, which was drastically slowing down the operation of `@linera/client` (see #4444 for details).  Additionally, `wasmtimer` doesn't look thread-safe: it uses [`parking_lot`](https://crates.io/crates/parking_lot), which will panic on Wasm if the lock ever tries to park.
Replace our dependency on `wasmtimer` with a [Linera fork](https://github.com/linera-io/kywasmtime/) of [`kywasmtime`](https://github.com/rom1v/kywasmtime), a package that exposes the same API but using the browser `clearTimeout` APIs instead of implementing its own priority queue.
I made a couple of patches to be more helpful for our usage, which are PR'd upstream as https://github.com/rom1v/kywasmtime/pull/3 and …
=> `linera-base`: expunge `wasmtimer` in favour of `kywasmtime`

CLI.md, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs
In operations, it is useful to be able to sync with all validators in one single operation.
Fixes #4488 
The implementation is straightforward.
The CI.
I did test with README.md kind of files and added a `linera sync-all-validators` function. And it does access to the validators without error.
I did not test that the syncing does happen, though.
I created issue #4535 that shows some idea for improving the syncing with validators.
Fully compatible with existing DevNet / TestNet.
None.
=> Implement the syncing with all validators functionality.

CLI.md, Cargo.toml, linera-indexer/lib/Cargo.toml, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-storage-service/Cargo.toml
It is hard to find out the ID of the admin chain, or to check the contents of blocks using the CLI client.
This PR adds some useful commands to the client: `show-network-description` (which contains the admin chain ID), `chain show-chain-description` and `chain show-block`.
TBD (could be backported to the testnet and devnet branches, but it's not strictly necessary).
=> Add some useful client commands

Cargo.lock, Cargo.toml, linera-service/Cargo.toml, linera-service/src/cli/main.rs, linera-service/src/proxy/main.rs, linera-service/src/server.rs, linera-views/src/backends/rocks_db.rs
jemalloc is more performant than the system allocator (and was even the Rust default for a while)
Add a feature that when enabled will use jemalloc as the allocator. We might decide to have this feature on by default eventually, but for now it'll be used for memory profiling, which is coming in the following PRs.
Deployed a network with this featured turned on, saw a slight performance improvement, and tested with the profiling code.
=> Add feature to use jemalloc as memory allocator

kubernetes/linera-validator/grafana-dashboards/profiling/jemalloc-memory.json, kubernetes/linera-validator/templates/grafana-pyroscope-dashboard-config.yaml
If we want to keep the investigation centered on Grafana, it would be useful to also have a memory profiling dashboard containing the flamegraphs
Add a dashboard containing the memory profile flamegraphs to Grafana
Will update with a screenshot
=> Add memory profiling dashboard

linera-core/src/unit_tests/value_cache_tests.rs, linera-core/src/value_cache.rs, linera-core/src/worker.rs
After a while, while benchmarking, some of our shards start OOMing. After inspecting memory profiles, it seems that the culprit is the `ValueCache` for blocks specifically.
Lower the size of the cache so that it fills up and start evicting entries before making the VM run out of memory.
Deploy a network with this code, benchmark it for a while and make sure that memory goes flat
=> Decrease block cache size, increase execution state cache size

docker/.env.production.template, scripts/backup-validator-keys.sh, scripts/deploy-validator.sh, scripts/extract-wallet-from-volume.sh, scripts/fix-validator-env.sh
Docker Compose validators lose configuration on restart because environment variables aren't persisted. The deploy-validator.sh script sets variables but doesn't save them to a .env file, causing validators to fail after docker-compose restart.
1. **Modified deploy-validator.sh** to create a .env file with all configuration
2. **Created fix-validator-env.sh** migration script for existing validators
3. **Fixed log output contamination** in PUBLIC_KEY generation
4. **Added backup scripts** for validator keys trapped in Docker volumes
- `scripts/deploy-validator.sh`: Now creates .env file for Docker Compose persistence and redirects logs to stderr to prevent PUBLIC_KEY contamination
- `scripts/fix-validator-env.sh`: Migration script to generate .env from legacy .deployment-info files …
=> Fix Docker Compose validator deployment environment persistence

examples/create-and-call/src/contract.rs, examples/ethereum-tracker/src/contract.rs, examples/how-to/perform-http-requests/src/contract.rs, examples/meta-counter/src/contract.rs, examples/publish-read-data-blob/src/contract.rs, linera-sdk/src/contract/runtime.rs, linera-sdk/src/contract/test_runtime.rs
The `call_application` and `instantiate` are taking a reference, but in contrast to those functions the `handle_query`
is taking a value which is immediate serialized. There is no reason for that. 
Make the change of having `handle_query` take a reference.
Also change `create_data_blob`.
The CI.
This is definitely breaking the smart contracts, though not the validator code.
None.
=> Change the argument of `handle_query`.

linera-web/package.json, linera-web/signer/package.json
I released 0.15.4 for https://github.com/linera-io/linera-protocol/pull/4595 and we should record that fact.
Bump the versions in the codebase.
No code changes.
=> `linera-web`: bump to 0.15.4

docker/debug/Dockerfile.debug
Since we might want to access this image from clusters in other cloud providers, it makes sense for it to be in the public registry.
Move it to public registry
Built and uploaded the image, and used it to debug something in a OVH cluster
=> Move Dockerfile.debug to public artifact registry

CLI.md, Cargo.toml, linera-base/src/crypto/hash.rs, linera-base/src/identifiers.rs, linera-base/src/unit_tests.rs, linera-service/src/cli/command.rs
Changes from #4570 left a few small oversights.
Fix an incorrect doc string, restore a deleted line from Cargo.toml, change the Debug implementation for CryptoHash (so that the commands printing out chain IDs are actually useful).
CI
=> Small fixes after #4570

linera-service/src/cli/main.rs, linera-service/src/proxy/main.rs, linera-service/src/server.rs
We're using the `unprefixed_malloc_on_supported_platforms` feature to be able to use `malloc_conf` instead of the prefixed `_rjem_malloc_conf`, as it's recommended, but MacOS is not one of the supported platforms.
Use the prefixed version for MacOS
Ran `linera net up` with memory profiling enabled from my MacOS, it works now
=> Add macOS support for memory profiling

linera-faucet/server/src/lib.rs, linera-metrics/src/monitoring_server.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/node_service.rs, linera-service/src/proxy/main.rs, linera-service/src/schema_export.rs, linera-service/src/server.rs
Currently, if we start a node service we get no metrics or memory profiling.
Add support for metrics and memory profiling from node service. Also fix the fact that it doesn't terminate with Ctrl+C (the faucet had the same thing, so I fixed it there too).
Start a node service locally, see that memory profile is enabled and working, and that killing it with Ctrl+C actually kills it
=> Add monitoring to node service

examples/native-fungible/index.html
Fungible demo frontend accepted only 20-byte accounts.
Modify the regex to also accept 32-bytes (64 chars).
Manual.
This is a testnet branch. Updates fungible demo can be released from it.
Solves https://github.com/linera-io/linera-protocol/issues/4562
=> Native fungible demo accepts 32-byte long address

Cargo.lock, Cargo.toml, docker/Dockerfile, kubernetes/linera-validator/helmfile.yaml, linera-base/Cargo.toml, linera-base/src/tracing.rs, linera-service/src/proxy/main.rs, linera-service/src/server.rs
Distributed tracing is a great way to debug different types of issues, including for example latency issues. So this is something we definitely want in general, and probably want by default in production as well.
Implement Distributed Tracing using Grafana Tempo. As it is a Grafana product, it integrates well with it, which is great for us. The visualizations also seem to be decent.
Deployed a network with this code and the `linera-infra` portion of this, and everything works as expected, and I can see the latency breakdowns (I got a really high latency outlier example):
I also chose this because it shows we might be waiting in the chain worker channel's queue for a while here 🤔 which might be worth investigating, which I'll do next.
- Nothing to do / These changes follow the usual …
=> Adding Tempo for distributed tracing

Cargo.lock, examples/Cargo.lock, linera-base/src/tracing.rs, linera-chain/src/chain.rs, linera-core/src/chain_worker/actor.rs, linera-core/src/chain_worker/state.rs, linera-core/src/worker.rs, linera-service/src/proxy/grpc.rs, linera-storage/Cargo.toml, linera-storage/src/db_storage.rs
Now that we have distributed tracing (after https://github.com/linera-io/linera-protocol/pull/4556), we need more instrumentation so we have data about more functions in the breakdowns.
Instrument more functions with `telemetry_only` so that we don't get spammed in our logs, but the spans still get sent to Tempo.
Tested this with https://github.com/linera-io/linera-protocol/pull/4556, saw the spans properly show in the breakdowns.
=> Add more instrumentation

linera-views/src/common.rs, linera-views/src/error.rs, linera-views/src/views/collection_view.rs, linera-views/src/views/reentrant_collection_view.rs, linera-views/tests/views_tests.rs
The reading of multiple keys in `CollectionView` does not work. This is unfortunate since the underlying
container of `CollectionView` is `async_lock::RwLock` which allows multiple read or one write. We `CollectionView`
should have the same semantics.
Fixes #4588 
The following steps are made:
* The `ReadGuardedView` is now an enum. The `Loaded` entry is when it is present in updates. The `NotLoaded` when accessed from storage.
* The `NotLoaded` contains some lock so as to avoid a write to be created and lead to incoherent state.
* As a consequence, when doing the `try_load_entry` of a view on storage, the updates is not changed. But that is fine, since it is anyway in the LRU cache.
* A `try_load_entries` has been introduced since we can now read multiple keys at once.
* The code of `fn …
=> Allow multi-read in `CollectionView`

linera-core/src/client/mod.rs
Backport of #4647
[`from_entropy` uses `getrandom` and is slower than `thread_rng`](https://docs.rs/rand/0.8.5/rand/trait.SeedableRng.html#method.from_entropy).
Use `thread_rng` to select validators: This does not need to be high-quality randomness.
CI
- This PR on `main`: #4647
- Original PR: #4505
=> Use `thread_rng` instead of `from_entropy`. (#4647)

linera-core/src/client/mod.rs
[`from_entropy` uses `getrandom` and is slower than `thread_rng`](https://docs.rs/rand/0.8.5/rand/trait.SeedableRng.html#method.from_entropy).
Use `thread_rng` to select validators: This does not need to be high-quality randomness.
CI
- Original PR: #4505
=> Use `thread_rng` instead of `from_entropy`.

linera-client/src/wallet.rs, linera-service/src/cli/main.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
It's useful to see the admin chain in the wallet, even for non-admin users.
Add the admin chain on `wallet init`.
Do not make chains the default unless we own them.
CI
I also ran the README tests locally.
- These changes _could_ be backported to the latest `testnet` branch, then
=> Track the admin chain by default.

Cargo.lock, Cargo.toml, linera-base/src/data_types.rs, linera-service/Cargo.toml, linera-service/src/cli/main.rs, linera-service/src/wallet.rs
It's hard to tell from `wallet show` which chain is the admin chain. The table layout uses a lot of horizontal space.
Improve the `wallet show` output:
```
WALLET (4 chains in total)
Child Chain [DEFAULT]
Chain ID:     a08244c18c828b7b89289f7164428e0b861fb462042416f6c2cfb1f4b53c8621
Owner:        0x86843df3f162b0a820724d37612ecde13c9a022d0cc96b765be127d34cec2d19
Timestamp:    2025-09-24 12:54:53.051239
Blocks:       0
Epoch:        0
Admin Chain
Chain ID:     82fc0ff002b793c66db0c57e657c05a30a98cd49d335f8125d0c3bdc4997ffa1
Owner:        No owner key
Timestamp:    2025-09-24 12:53:29.841442
Blocks:       0
Epoch:        0
Root Chain 1
Chain ID:     0b67f224ab915776d170eeb7d497e8d1ed831126f22eaf9138de48e3c47c8639
Owner:        No owner key
Timestamp:    2025-09-24 12:55:04.030389
Blocks: …
```
=> Improve `wallet show`.

linera-client/src/wallet.rs, linera-service/src/cli/main.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs
Backport of https://github.com/linera-io/linera-protocol/pull/4641.
It's useful to see the admin chain in the wallet, even for non-admin users.
Add the admin chain on `wallet init`.
Do not make chains the default unless we own them.
CI
I also ran the README tests locally.
- These changes _could_ be backported to the latest `testnet` branch, then
- PR on main: https://github.com/linera-io/linera-protocol/pull/4641
=> Track the admin chain by default. (#4641)

Cargo.toml
`cargo update && cargo build -p linera-views --features scylladb` currently fails, because some types in `scylla` are `Sync` in 1.1 but not 1.2 and later. This breaks `cargo install` in some cases.
Thanks to @kikakkz for pointing this out!
Fix the dependency to 1.1.
I did `cargo update` with this change and everything compiled without errors.
(In a separate PR, we could commit the updated lock file, too.)
=> Fix scylla dep to 1.1; doesn't build with later versions.

linera-core/src/chain_worker/mod.rs, linera-core/src/chain_worker/state.rs, linera-core/src/client/mod.rs
The huge amount of entries in the `received_log` seems to be making it impossible to sync the old GoL chain on Testnet Conway.
Limit the number of returned entries in a single response. Client should request more entries with an increased offset until the number of returned entries is less than the limit (indicating that there are no more entries).
CI; Manual testing on the testnet will show whether this fixes the syncing issue
=> Add a limit for the number of received_log entries in a chain info response

.github/workflows/docker_image.yml
Backport of https://github.com/linera-io/linera-protocol/pull/4674
Backport it
CI
=> [Backport of #4674] Use bigger GH runner for Docker Image CI

.github/workflows/docker_image.yml
We're timing out right now, and we won't want to wait for longer
Use a bigger GH runner for now, but we'll eventually move these out of GH runners
CI
=> Use bigger GH runner for Docker Image CI

docker/Caddyfile
This PR fixes the Caddy configuration in Docker Compose to properly handle gRPC-Web traffic by:
1. **Removing incorrect `Content-Type` header override** - Caddy was forcing all requests to have `application/grpc` content-type, which breaks gRPC-Web that requires `application/grpc-web+proto`
2. **Adding explicit OPTIONS handling** - Ensures CORS preflight requests are properly forwarded to the backend
3. **Simplifying proxy configuration** - Let the backend handle both gRPC and gRPC-Web protocols including CORS headers
The previous configuration was overriding all Content-Type headers to `application/grpc`, which prevented gRPC-Web clients from working correctly as they require specific content types like `application/grpc-web+proto`.
- Removed the forced Content-Type header
- Added …
=> Docker Compose: fix Caddy configuration for gRPC-Web

CLI.md, linera-client/src/client_options.rs, linera-core/src/client/mod.rs, linera-web/src/lib.rs
Backport of https://github.com/linera-io/linera-protocol/pull/4666.
Joining an unbounded number of concurrent tasks can cause spikes in memory usage.
Replace all the `[try_]join_all` calls in the client module with `buffer_unordered`, with a configurable limit.
CI
- PR to main: https://github.com/linera-io/linera-protocol/pull/4666
=> [Backport] Add an option to limit how many tasks are joined concurrently.

CLI.md, linera-client/src/client_options.rs, linera-core/src/client/mod.rs, web/@linera/client/src/lib.rs
Joining an unbounded number of concurrent tasks can cause spikes in memory usage.
Replace all the `[try_]join_all` calls in the client module with `buffer_unordered`, with a configurable limit.
CI
=> Add an option to limit how many tasks are joined concurrently.

linera-service/src/cli_wrappers/local_kubernetes_net.rs
Seems like there was some race condition on the block exporer stuff merging, which made CI not catch this bug.
Only load images when the exporter mode is enabled.
CI
=> Fix image loading on net up --kubernetes

linera-views/src/views/map_view.rs
The `fn entries` should be using a `multi_get`, but the function was missing.
It was introduced straightforwardly, by taking `CollectionView` / `ReentrantCollectionView` as a model.
The unit test have been added for the functionality.
It is fully compatible with TestNet / DevNet and could impact the GoL which is using `MapView`.
None.
=> Introduce the `multi_get` for `MapView` and make the `fn entries` used it.

.github/workflows/rust.yml, scripts/wait-for-kubernetes-service.sh
Right now the networks get started as a bg process. So if it fails, we can't really see the logs showing why it failed to start.
Write a simple script, to give us the logs while waiting for the faucet to start.
CI
=> Show logs of network starting on remote net tests

linera-faucet/server/build.rs, linera-faucet/server/src/lib.rs, linera-faucet/server/src/tests.rs, linera-service/src/cli/main.rs
The current metrics we have on the faucet its stuff that we're exporting in the client code, but we don't have any faucet specific metrics.
Add some faucet specific metrics.
Deploy a network with this code, see the faucet metrics being exported. Used this to create a dashboard as well with these metrics:
=> Adding some faucet metrics

.github/workflows/rust.yml
The order of things got messed up in a previous PR
Fix it, and make sure everything is setup before calling the `resource-control-policy` commands.
CI
=> Use --with-faucet on remote-net-test

CLI.md, linera-chain/src/chain.rs, linera-chain/src/lib.rs, linera-client/src/benchmark.rs, linera-client/src/chain_listener.rs, linera-client/src/unit_tests/chain_listener.rs, linera-core/src/client/mod.rs, linera-core/src/local_node.rs, linera-core/src/notifier.rs, linera-core/src/unit_tests/client_tests.rs, linera-faucet/server/src/lib.rs, linera-service-graphql-client/gql/service_schema.graphql, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/src/node_service.rs, linera-service/tests/linera_net_tests.rs, linera-service/tests/local_net_tests.rs, web/@linera/client/src/lib.rs
`find_received_certificates_from_validator` and `find_received_certificates` can take a lot of time (and memory) if there are a lot of incoming messages.
Only do them as part of `synchronize_from_validators`. On notification, `prepare_chain` and when we're about to propose a block, only download what's necessary.
Download and process sender certificates in batches, to avoid the high memory usage.
Download them in a background task in the node service, with some sleep time in between, to limit interference with the other node service tasks.
(Mostly written with Claude Sonnet 4.5.)
CI
A new test was added for the updated `prepare_chain`. `test_sparse_sender_chain` already exists, and tests notification handling with a sparse chain.
- These changes should be backported to `testnet_conway`, …
=> Don't do heavy syncing of sender chains unless requested.

linera-core/src/client/mod.rs
Right now we're going through the validators always in the same order, which is not ideal
Shuffle the validator order
CI
=> Shuffle validator order in download_missing_sender_blocks (Backport of 4724)

CLI.md, Cargo.lock, linera-service/Cargo.toml, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs, linera-service/src/cli/net_up_utils.rs, linera-service/src/cli_wrappers/wallet.rs, linera-service/tests/local_net_tests.rs, linera-service/tests/snapshots/local_net_tests__storage_service_linera_net_up_simple.snap
Quality of life: it's pretty annoying when using `linera net up` to have to repeat the faucet URL all the time.
Support setting the faucet URL through an environment variable for the CLI, akin to `LINERA_WALLET` and friends.  This reduces the need for repeating the URL a lot when testing on a local network.
Used locally.
=> `linera-service`: faucet URL env var

linera-chain/src/manager.rs
https://github.com/linera-io/linera-protocol/pull/4688 fixed a bug where the chain manager would set its `signed_proposal` but not update the current round accordingly. However, some existing chains may already be in a bad state.
Detect the bad state and recompute the current round.
Backport and see if it makes the affected chains recover. Otherwise we should never see the warning log.
- Original bug fix: https://github.com/linera-io/linera-protocol/pull/4688
=> Make chain manager recover from `current_round` bug.

CLI.md, linera-client/src/client_context.rs, linera-client/src/client_options.rs, linera-service/src/cli/command.rs, linera-service/src/cli/main.rs
`change-ownership` is pretty hard to use (and unsafe)
* Add a command show-ownership
* Refuse to change ownerwhip to 0 owners
* Use JSON outputs consistently
CI + tested manually
=> Add command to show ownership configuration of a chain

linera-core/src/client/mod.rs
I removed `BlobsNotFound` handling here in https://github.com/linera-io/linera-protocol/pull/4688 because I thought it was unreachable, but I can see this error in `testnet_conway` sometimes.
Restore handling logic: download blobs if necessary.
It fixed that error for me on `testnet_conway`.
- Introduced in #4688.
=> Restore `BlobsNotFound` handling on `retry_pending_cross_chain_requests`.

linera-core/src/updater.rs
Backport of #4748.
`send_chain_information_for_senders` can cause many requests if there are lots of sender chains. The `MissingCrossChainUpdate` code was written with user chains in mind, that would only receive messages from a handful of other chains.
Send only the requested missing update.
That can mean that there will be many iterations of that loop, if the validator is very far behind, but it should be more lightweight than `send_chain_information_for_senders`.
CI
- PR to main: #4748
=> Send only the relevant sender chain on `MissingCrossChainUpdate`. (#4748)

linera-views/src/backends/scylla_db.rs
Without the double quotes, if we use a reserved keyword like `default`, it will fail.
Use double quotes to make it explicit that we're talking about an identifier. Then we can use whatever identifier we want. Should unblock https://github.com/linera-io/linera-protocol/pull/4569
CI
=> Surround namespace with quotes in ScyllaDB

linera-service/src/cli/main.rs, linera-storage/src/lib.rs, linera-views/src/backends/scylla_db.rs
I found this inconsistency after copying a default wallet to a different directory. Then, I couldn't use the copy.
* Use the same default value for all configuration modes
* Use the value that is less likely to break user wallets
CI + testnet manually
TBD -- This may break validator deployments if they used the default namespace value.
=> fix default storage namespace
