linera-io/linera-protocol

README.md
docker/run-client.sh
docker/setup.sh
scripts/run_local.sh

* `client` is now `linera`.
* Change `client.db` to `linera.db`.
* `assign` takes an effect ID, not chain ID and certificate.
* `--genesis genesis.json` is only used when creating a wallet.

Fix bash scripts

---

linera-service/src/linera.rs
linera-service/src/project.rs

Users need an easy way to unit test their applications.
Add `linera project test` which:
1. Tries to find the `linera-test-runner` binary, if it cannot find it downloads it using `cargo install`
2. Runs the tests with the runner piping stdin and stdout.
3. Fails if the underlying tests fail.
Strictly speaking this is waiting on the crate `linera-test-runner` to be installed. But I tested it out without the `linera-test-runner` and by putting it manually in `~/.cargo/bin` and both have the desired behaviour.
Integration tests will be added as soon as the crate is available, otherwise they will fail.

Added `linera project test`

---

README.md
docker/run-client.sh
linera-service/src/linera.rs
linera-service/tests/integration_tests.rs
scripts/run_local.sh

We currently use both underscores (`_`) and hyphens (`-`) for our CLI commands and options.
Use hyphens everywhere. That seems to be most common, and is also `structopt`'s default.

Use hyphens for CLI commands.

---

Cargo.lock
Cargo.toml
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-examples/Cargo.lock
linera-examples/Cargo.toml
linera-examples/counter-graphql/Cargo.toml
linera-examples/counter/Cargo.toml
linera-examples/counter2/Cargo.toml
linera-examples/crowd-funding/Cargo.toml
linera-examples/crowd-funding2/Cargo.toml
linera-examples/fungible/Cargo.toml
linera-examples/fungible2/Cargo.toml
linera-examples/meta-counter/Cargo.toml
linera-examples/reentrant-counter/Cargo.toml
linera-examples/reentrant-counter2/Cargo.toml
linera-examples/social/Cargo.toml
linera-execution/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/src/test/integration/chain.rs
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-views/src/test_utils/mod.rs
linera-views/tests/queueview_tests.rs
linera-views/tests/views_tests.rs

While investigating the Rust compiler crashes and compilation breakages caused by `cargo update`, I learned that it's possible to centralize the dependency versions of all crates in a workspace. Cargo has a feature called ["workspace dependency inheritance"](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace), where the dependency is defined in the workspace, and all crates in the workspace can just reference the dependency.
This makes it easier to keep versions consistent, to update dependencies, and to debug issues when upgrading dependencies.
List all dependencies in the workspace manifest, and update all crates to inherit the necessary dependencies.
Features usually still need to be enabled per crate, but I did provide some …

Centralize dependency versions

---

.github/workflows/rust.yml
Cargo.lock
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/worker.rs
linera-rpc/Cargo.toml
linera-rpc/src/config.rs
linera-rpc/src/grpc_network.rs
linera-rpc/src/simple_network.rs
linera-service/src/chain_listener.rs
linera-service/src/lib.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/readme_test.rs

The actual fix is 6721bbbb623884fa77b2169da65bf750f582a436 : we cannot assume that the chain listener will be faster than the graphql API to synchronize and process inboxes.
I managed to consistently reproduce the latest error seen in CI by introducing a delay in the listener (11fb2b240876ae202fdf05410fb6f6ccc6441d6b). The error disappears after the fix.
Other related improvements in the PR include:
* Dropping cross-chain messages at random (note: we don't handle that in the e2e tests yet)
* Making sure that e2e tests if client commands or servers crash.
* Fix the benchmark command (broken by a race condition with the readme test)
* Exit NodeService as soon as listener or graphql stops
* Some CI nits
* Some renamings in client commands
Synchronizing from validators is expensive. I created …

Fix e2e tests

---

Cargo.lock
examples/Cargo.lock
linera-core/Cargo.toml

#674 updated the crates in the workspace to use the same dependency versions by centralizing them in the workspace manifest. Unfortunately, `linera-core` was left out of that process.
Change the Cargo manifest of `linera-core` to inherit the dependency specifiers from the workspace manifest.
Also update the `Cargo.lock` again with `cargo update` to ensure everything is working correctly.

Inherit workspace dependencies in `linera-core`

---

linera-core/src/client.rs
linera-core/src/node.rs
linera-service/src/chain_listener.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

Hopefully the last one this time!
What was happening is that we were calling `synchronize_from_validators` immediately after receiving the first notification from a validator V. However, this function only has to talk to a quorum. So it may miss the new message if V is 
not part of the quorum.
The fix is to do what we had in mind anyway: synchronize blocks with the author of the notification that we just received.

Fix race condition in e2e tests

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-core/src/data_types.rs
linera-core/src/node.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/conversions.rs
linera-rpc/src/grpc_network.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/chain_listener.rs
linera-storage/src/lib.rs
linera-views/src/map_view.rs

We already merged the `UpdateRecipient` messages, so that a single one summarizes all updates for the same recipient. But as a response, currently multiple `ConfirmUpdatedRecipient` are sent.
Merge the `ConfirmUpdatedRecipient` messages, so that only one response is necessary for each update message.
Closes https://github.com/linera-io/linera-protocol/issues/442

Send only one ConfirmUpdatedRecipient per UpdateRecipient.

---

Cargo.lock
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/worker.rs
linera-rpc/Cargo.toml
linera-rpc/proto/rpc.proto
linera-rpc/src/conversions.rs
linera-rpc/src/grpc_network.rs

The [protocol definition](https://github.com/linera-io/linera-protocol/blob/a6958ea72271a38bb3528d9f1b03d23d7f55839d/linera-rpc/proto/rpc.proto) and [conversion logic](https://github.com/linera-io/linera-protocol/blob/a6958ea72271a38bb3528d9f1b03d23d7f55839d/linera-rpc/src/conversions.rs) are complicated because the internals of our data types are represented in the protocol.
Serialize and deserialize more types in `conversions.rs` and represent them as `bytes` in the protocol. Use bincode instead of BCS, since it can be more efficient in some cases.
The downside is that in some cases the serialized bytes in the protocol messages are now different from the bytes that the signatures and hashes refer to.
Closes https://github.com/linera-io/linera-protocol/issues/281

Simplify gRPC messages, use bincode.

---

examples/reentrant-counter/src/contract.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-core/src/client.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-rpc/tests/staged/formats.yaml

We've been mixing up the concepts of `EffectId` (where the index ranges over `Vec<Effect>`) and `OperationId` (where the index ranges over `Vec<Operation>`). In this PR, I tried to clean up things and not to create an actual type `OperationId`. As a consequence, I switched application-ids to use the effect counter instead of the operation counter and created a new effect for published applications.

fix computation of effect_id while executing system operations

---

linera-service/src/linera.rs

We need this to show accurate chain state in GraphiQL after performing CLI commands.
Also filed #704 because I tried the using the CLI in parallel with the node service during debugging and (as expected) it goes horribly wrong.

synchronize node service with validators on startup

---

examples/fungible/src/contract.rs
examples/fungible/src/lib.rs
examples/fungible/src/service.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-service/tests/end_to_end_tests.rs

This is similar to the system operation.
One minor difference is that `AccountOwner`s can be applications here but this use case is not yet supported. (Authenticated caller is not forwarded through effects yet: #708)

Add claim operation to the `fungible` app

---

examples/counter/src/service.rs
examples/counter/web-frontend/src/App.js
examples/fungible/web-frontend/src/App.js
examples/social/src/service.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/src/proxy.rs
linera-service/src/server.rs
linera-service/tests/end_to_end_tests.rs

* Fix the syntax for the notification requests that was broken in https://github.com/ma2bd/linera-protocol/commit/6dcfec496ad735b415bd8131f3a3e2a6c6e4e53a
* Use an `async-graphql` hack called `MergedObject`s to extend `ChainStainView` with a `chainId` field.
* Make sure the default logging level for binaries is INFO.
* Rename `execution_operation` into `increment` in the counter GraphQL.
* Make sure to save the intermediate wallet state in publish-and-create (in case of a failure later)

Fix counter UI + misc

---

examples/reentrant-counter/src/state.rs
examples/social/src/state.rs
linera-views-derive/src/lib.rs
linera-views/tests/hashable_tests.rs
linera-views/tests/queueview_tests.rs

We were wrongly assuming that `Context` is in the scope.

Fix import in linera-views-derive

---

.github/workflows/documentation.yml
linera-sdk/Cargo.toml
linera-views/Cargo.toml

Current documentation in docs.rs for `linera-sdk` and `linera-views` was only built for `x86_64-unknown-linux-gnu` and doesn't include any features. This makes it impossible to view the documentation for test helper types and functions.
Add metadata to be read by docs.rs that adds target architectures and features.
I'm not sure how to test this, and I'm a bit worried it might break documentation if there are conflicts between features and the WebAssembly architecture.

Add `docs.rs` metadata to SDK and views manifest files

---

Cargo.lock
examples/Cargo.lock
examples/fungible/Cargo.toml
examples/fungible/tests/cross_chain.rs
linera-sdk/Cargo.toml
linera-sdk/src/test/integration/chain.rs

The only integration test example that was in the repository was accidentally removed during the restructuring of the examples (#695).
Restore the test from before it was removed.

Restore integration test in fungible application

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/crowd-funding/Cargo.toml
examples/crowd-funding/src/contract.rs
examples/crowd-funding/src/lib.rs
examples/crowd-funding/src/service.rs
examples/crowd-funding/src/state.rs
linera-service/Cargo.toml
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

* Import changes for previous draft PR #634 to make the crowd-funding app multi-chain
* Fix another (theoretical) race condition in e2e tests by adding manual "process_inbox" commands
* Fix the injection of the application id of fungible in crowd-funding (must parameters instead of initialization arguments)
* Add command "notify" to make campaigns multi-user before the real fix (#718)
* Add support for missing CLI arguments in e2e test
* Finally import GraphQL changes and fix e2e test from #716

Make crowd funding multi-chain + add tests

---

Cargo.lock
examples/Cargo.lock
examples/counter/tests/single_chain.rs
linera-core/Cargo.toml
linera-core/src/client.rs
linera-rpc/src/grpc_network.rs
linera-rpc/src/node_provider.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs

gRPC notification streams can fail or end for different reasons. We currently don't retry on any of them.
Retry for some gRPC error codes.
This also replaces `async_stream::stream!` with `futures::stream::unfold` to remove one dependency and use fewer macros.
Closes https://github.com/linera-io/linera-protocol/issues/687.

Retry disconnected notification streams.

---

examples/crowd-funding/src/contract.rs
examples/crowd-funding/src/lib.rs
examples/crowd-funding/src/service.rs
linera-core/src/client.rs
linera-execution/src/system.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

If an application was created on chain A, currently the only way to use it on chain B is for B to receive an application effect from A. And there's no way to request that.
Add a `RequestApplication` operation and system effect to request a particular application by ID from another chain. If processed, it is answered with a `RegisterApplications` effect that contains the requested application and its dependencies. So in the example above:
* B could execute a `RequestApplication { chain_id: A, application_id }` operation.
* That would trigger a `RequestApplication(application_id)` effect to A.
* A would process it and send a `RegisterApplications` back to B.
* After processing that, the application can be used on B.
Partly addresses https://github.com/linera-io/linera-protocol/issues/718.

Allow requesting an application to register it on a chain.

---

Cargo.lock
linera-service/Cargo.toml
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs

Multiple instances of `linera` could access the same wallet, causing concurrent modifications of the underlying wallet file resulting in UB.
Use advisory locking with the `file-lock` crate. A temporary file is created while the wallet is being written to avoiding unintentionally wiping out the contents of the wallet.

Added advisory locking to wallet

---

linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs

Some commands panicked if there were any chains that we don't have the private key to.
Apply those commands only to owned chains.
This also updates the reconfiguration test so that the node service has the key and can receive new committees. That means the other client does not have the key to that chain when it uses those commands.

Fix some commands so they work with non-owned chains.

---

scripts/install_hooks.sh

Pre-Push hooks were using `udeps` being inconsistent with CI.
Change it to Machete

Hooks script now uses cargo machete like CI

---

examples/counter/Cargo.toml

This is for the compilation of `cargo test` in `counter` that fails.

Reintroduce a missing entry in Cargo.toml

---

linera-chain/src/data_types.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/worker.rs
linera-rpc/src/client.rs
linera-rpc/src/conversions.rs
linera-rpc/src/grpc_network.rs
linera-rpc/src/rpc.rs
linera-rpc/src/simple_network.rs

Currently [`DbStoreClient::write_certificate` clones the list of signatures](https://github.com/linera-io/linera-protocol/blob/a6958ea72271a38bb3528d9f1b03d23d7f55839d/linera-storage/src/lib.rs#L315) before serializing it.
Put the signatures in `LiteCertificate` into a `Cow`. When deserializing, it is owned, but when it is taken from a `&Certificate`, it is borrowed and doesn't need to be cloned.

Allow creating lite certificates without cloning the signatures.

---

linera-chain/src/chain.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-views-derive/src/lib.rs
linera-views/src/collection_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/tests/reentrant_tests.rs

The PR implements the multi loading for the `ReentrantCollectionView`.
But it does more:
* It also replaces the `channels` and `outboxes` by a `ReentrantCollectionView`.
* The `ReentrantCollectionView` and `ReentrantCustomCollectionView` are now supported by the `GraphQL` macros.
* The `chain.rs` code has been restructured for accounting of that and should work better out of it.
This is an improvement with respect to preceding code, more improvements are needed using async streams. That being said, I think the API is of general interest whether we end up using only async streams or not.

Implement `try_load_multi_entry_*` for `ReentrantCollectionView`

---

examples/crowd-funding/src/contract.rs
examples/crowd-funding/src/service.rs
examples/crowd-funding/src/state.rs
examples/fungible/src/contract.rs
examples/fungible/src/service.rs
examples/fungible/src/state.rs
examples/reentrant-counter/src/contract.rs
examples/reentrant-counter/src/service.rs
examples/reentrant-counter/src/state.rs
examples/social/src/contract.rs
examples/social/src/service.rs
examples/social/src/state.rs
linera-sdk/src/views/mod.rs
linera-views-derive/src/lib.rs

It can be confusing for new users of the SDK to understand why they need to use generic context types when writing applications with views.
Provide view type aliases and alternative derive macros that don't require a generic context type parameter.
Blocked by #727 
Blocked by #737 
Closes #675

Remove generics from application views

---

linera-chain/src/chain.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs

After the previous merge, I realize that there are more places where we can use `try_load_entries` and reduce the asynchronicity burden.

Use `try_load_entries_*` more systematically

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-views-derive/Cargo.toml
linera-views-derive/src/lib.rs
linera-views-derive/src/util.rs

The problem is the following. The following code does not compile
```rust
struct TestView<C> {
view: RegisterView<C, String>,
}
#[derive(GraphQLView)]
struct BlockView<C> {
bids: CollectionView<C,String, TestView<C>>,
asks: CollectionView<C,String, TestView<C>>,
}
```
The reason is that the code for `TestViewEntry` is generated two times.
The solution is to generate two codes: `TestViewBlockViewbidsEntry` and `TestViewBlockViewasksEntry` so as to avoid the namespace collision.
This is the only solution that makes sense. This is because the generated code refers both to the key and to the value. So, we cannot generate a `TestViewEntry` at the level of the `TestView`.

Resolve a bug in GraphQL

---

linera-core/src/worker.rs
linera-storage/src/lib.rs

There was a loop over values of `blobs` that was really easy to speed up by having just one call to the database.

Improvement to storage

---

linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs

`WasmApplication` only stored the bytecodes for the application, which meant that it recompiled them for every execution. This is inefficient.
Store the compiled `Module` (together with the required `Engine` instance) in `WasmApplication`.
Part of #739 
Closes #750 by including it

Avoid recompiling WASM bytecodes

---

linera-core/src/worker.rs
linera-views/src/log_view.rs

The loop over the heights is ridiculous in terms of asynchronicity. Though the solution requires the introduction of a `multi_get` for `LogView`.

Reduce asynchronicity in `confirmed_log`

---

Cargo.lock
examples/Cargo.lock
examples/counter/src/lib.rs
examples/counter/src/service.rs
examples/crowd-funding/src/lib.rs
examples/crowd-funding/src/service.rs
examples/fungible/src/lib.rs
examples/fungible/src/service.rs
examples/meta-counter/Cargo.toml
examples/meta-counter/src/lib.rs
examples/meta-counter/src/service.rs
examples/reentrant-counter/src/contract.rs
examples/reentrant-counter/src/lib.rs
examples/reentrant-counter/src/service.rs
examples/reentrant-counter/src/state.rs
examples/social/src/lib.rs
examples/social/src/service.rs
linera-base/src/abi.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-sdk/src/lib.rs
linera-sdk/src/service/exported_futures.rs

Application authors should not have to write boilerplate code to serialize and deserialize requests coming into services.
Use associated types in Services to define types and perform serde in the background.

Implement Service ABIs using associated types in Rust

---

linera-core/src/worker.rs
linera-storage/src/lib.rs

There was more asynchronicity that could be eliminated from the storage writing by using the batches.

Improve the storage writing

---

linera-service/src/project.rs
linera-service/template/Cargo.toml
linera-service/template/config.toml
linera-service/template/contract
linera-service/template/lib
linera-service/template/service
linera-service/template/state
linera-service/tests/end_to_end_tests.rs

`linera project new` is untested resulting in unintended regressions.
Split `linera project new` into a 'debug' mode and 'release' where the former uses relative directories to `linera-sdk` and the latter uses `crates.io`.
Closes #653 .

Added tests for `linera project new`

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/manager/multi.rs
linera-chain/src/manager/single.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/src/client.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/examples/generate-format.rs
linera-rpc/src/conversions.rs
linera-rpc/src/rpc.rs
linera-rpc/tests/staged/formats.yaml
linera-sdk/src/test/integration/block.rs
linera-sdk/src/test/integration/chain.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-storage/src/lib.rs

For chains with full consensus we will need additional `Value` variants, such as timeout certificates, which won't contain a block, effects and a state hash. So `Value` needs to be an `enum` again.

Turn Value back into an enum

---

linera-service/src/project.rs
linera-service/tests/end_to_end_tests.rs

The `linera project test` command was pointing to an empty crate.
Now it's pointing to `linera-sdk` and pulling the `test-runner` binary.
Also we now have tests for `linera project test`.

Fix `linera project test`

---

linera-chain/src/data_types.rs
linera-chain/src/manager/mod.rs
linera-chain/src/manager/multi.rs
linera-chain/src/manager/single.rs
linera-core/src/client.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera.rs
linera-storage/src/lib.rs

Otherwise the `MultiOwnerManager` makes validators potentially double-sign, because they could sign different `ConfirmedBlock`s in different rounds.

Add a round number to ConfirmedBlock.

---

Cargo.toml
examples/Cargo.toml
linera-core/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views/Cargo.toml
linera-views/src/lib.rs
linera-views/src/unit_tests/views.rs
linera-views/tests/operations_tests.rs
linera-views/tests/views_tests.rs

We sometime compile the linera-sdk for the native platform (for instance here: https://github.com/linera-io/linera-documentation/pull/20). In this PR, we try not always to compile rocksdb in this case.

rocksdb feature in linera-views

---

linera-chain/src/chain.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/updater.rs
linera-execution/src/committee.rs
linera-execution/src/graphql.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera.rs

This introduces a short grace period, proportional to how long it took to reach a quorum, to allow additional validators to contribute signatures or chain information.
One place where this is useful is `send_certificate`: When updating validators, we re-send the full certificate to everyone whose signature isn't in it. With the grace period, often every validator will have signed it, and only `LiteCertificate`s need to be sent.
This also fixes a bug: We need to recompute the total and thresholds when adding and removing validators.

After reaching quorum, wait for additional validators.

---

linera-chain/src/data_types.rs
linera-chain/src/manager/multi.rs
linera-chain/src/manager/single.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/examples/generate-format.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera.rs
linera-storage/src/lib.rs

This is less ambiguous, especially since we also use `serde_json::Value`.

Rename Value to CertificateValue.

---

linera-service/Cargo.toml

I added a feature `linera-views/rocksdb` in a previous PR. For some reason, this makes `cargo publish --dry-run --no-verify` fail on `linera-service` (but not `linera-storage`). It would appear that removing `rocksdb` from the dev dependency of `linera-service` works around the issue (at least temporarily). The code still builds because the feature is added anyway by `linera-storage` via feature unification.
Note: It's unclear to me why `linera-storage` passes `cargo publish --dry-run --no-verify`. Perhaps an inconsistent behavior of `--no-verify`?

hack to avoid failing docrs tests due to the new feature

---

linera-chain/src/data_types.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/tracker.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-rpc/proto/rpc.proto
linera-rpc/tests/staged/formats.yaml
linera-sdk/src/test/integration/block.rs
linera-service/src/chain_listener.rs

This is a preliminary step before renaming `Effect` into `Message`. It's also useful by itself.

rename `Message` into `IncomingMessage`

---

Cargo.lock
examples/Cargo.lock
examples/counter/tests/single_chain.rs
examples/crowd-funding/Cargo.toml
examples/crowd-funding/tests/campaign_lifecycle.rs
examples/fungible/Cargo.toml
examples/fungible/src/lib.rs
examples/fungible/tests/cross_chain.rs
examples/social/tests/cross_chain.rs
linera-sdk/Cargo.toml
linera-sdk/src/test/integration/block.rs
linera-sdk/src/test/integration/chain.rs
linera-sdk/src/test/integration/validator.rs

The Crowd-Funding application didn't have any integration tests. This was because a few features were missing from the integration test framework to allow writing the tests smoothly.
Write two initial integration tests, and implement the necessary features in the test framework to get them to work. This includes:
1. Refactoring the helper function to publish bytecodes to receive the path where the bytecodes should be built and obtained. This allows building and publishing bytecodes from other repositories.
2. Adding ABI support to the test helper functions, making them more type-safe and consistent with the application.
3. Being able to set a block's timestamp, to simulate time in the tests.
4. Returning effect IDs from blocks added to chains, to avoid manually crafting `EffectId`s and …

Add initial integration tests for Crowd Funding application

---

linera-execution/src/committee.rs

have doubts about the use of get_lower_bound
no reference was found
compiled successfully after deletion

delete useless code

---

.github/workflows/kubernetes.yml
README.md
docker/Dockerfile
docker/run-proxy.sh
docker/run-server.sh
linera-service/Cargo.toml
linera-service/tests/end_to_end_tests.rs
scripts/run_local.sh

This is needed so that `cargo install -p linera-service` is a good citizen and doesn't pollute the `PATH` of user shells.

rename binaries `proxy` and `server` into `linera-proxy` and `linera-server`

---

linera-core/src/client.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-execution/src/system.rs
linera-rpc/examples/generate-format.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/node_service.rs

For voting on pricing we will soon add additional admin operations.
This deduplicates the `admin_id` check, and removes the field from the admin operations: What needs to be checked is just that the current chain is the admin chain.

Separate admin from other system operations.

---

Cargo.lock
examples/Cargo.lock
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/Cargo.toml
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/module_cache.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-storage/src/lib.rs

Different applications are able to use the same bytecode for execution. It's therefore possible to reuse the compiled WebAssembly module for a bytecode between two applications.
Create a `ModuleCache` type that caches compiled WebAssembly modules for specific bytecodes. The cache attempts to limit its total memory usage, but it does so based on the bytecode size instead of trying to measure the module's size.
Closes #739

Cache compiled bytecodes

---

linera-core/src/client.rs

We're supposed to call `prepare_chain()` in case the local node is somehow missing blocks compared to the wallet state.
Most client operations should call `self.execute_operation(..)` anyway.
Good catch @firedpeanut !
I created a task to track the lag of tests: https://github.com/linera-io/linera-protocol/issues/823

fix: add missing calls to prepare_chain()

---

linera-service/src/config.rs

Users are sometimes confused when running a node service and using the `linera` binary at the same time with the same wallet. Closes #830 
Provide a more descriptive message which also hints as to why the contention is happenning.

Added more descriptive message for wallet lock contention

---

linera-base/src/identifiers.rs

Implemented Clone/Copy, PartialEq/Eq, PartialOrd/Ord, Debug and Hash traits for SessionId, ApplicationId and BytecodeId.
I only haven't implemented Serialize and Deserialize, because I wanted to make sure which ones exactly I should implement, or if it's really just all of them. Please let me know if I should just do all of them, and I'll update this PR with it, and set it up for review.
For now, just
`cargo check` and `cargo test && cargo clippy --all-targets`
Happy to learn how I could test this better though, before officially putting this up for review :)

Implement derived traits manually for ApplicationId, SessionId, BytecodeId

---

linera-execution/src/applications.rs
linera-execution/src/system.rs
linera-sdk/src/test/integration/chain.rs

This also parallelizes `bytecode_locations`.

Don't fail a block if requested app not found.

---

linera-service/src/node_service.rs

Node service errors have two issues:
1. Errors returned by an application's service were not being captured (this could be a parsing error for example).
2. Errors were not correct JSON and therefore were not being parsed correctly by GraphiQL.

Better Node Service errors

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/manager/single.rs
linera-core/src/node.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-service/src/linera.rs
linera-storage/src/lib.rs

This is in preparation for public chains, but makes sense on its own:
* `already_validated_block` only needs the height, not the whole block, and will need to be applied to leader timeouts as well, which won't contain an actual block.
* The pending block in the single owner manager is always a confirmed block. This would be an `InternalError` (should actually be unreachable), not an invalid proposal.
* `cache_recent_value` now takes a `Cow`, to avoid unnecessarily cloning a certificate that's already cached.
* Some other minor changes, like a `Vote::value` getter, a `rustfmt` fix, and a stricter `assert!`.

Minor fixes and improvements for worker and chain manager.

---

linera-chain/src/data_types.rs
linera-rpc/src/conversions.rs

Did everything listed on #786, except making the fields private. Could someone give me a bit more context on that one? It'll require a lot of changes, so I want to make sure we need it first.
`cargo +nightly fmt && cargo check && cargo test && cargo clippy --all-targets`

Optimize Certificate::is_signed_by

---

linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/module_cache.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs

When a WebAssembly module fails to be loaded, the error reported to the user doesn't provide any details to why it failed to load. These details may be useful to quickly diagnose issues.
Show the message generated from the internal error source.
Also, split the error variant to make it clear if the contract module failed to load or the service module failed to load.

Display cause of module load error

---

linera-service/src/project.rs
linera-service/template/Cargo.toml.template

1. Projects created by `linera project new` don't use release profile optimizations resulting in large bytecode sizes.
2. Projects created by `linera project new` do not have an associated git repository, meaning that users have to manually `git init`.
1. Add the release profile optimisations to `Cargo.toml.template`.
2. Initialize a git repository when creating a project.

Linera project new optimisations and git repository

---

Cargo.lock
examples/Cargo.lock
examples/counter/Cargo.toml
examples/counter/src/contract.rs

`Counter::handle_application_call` always prints an error message even though there are no errors.
Remove the log call.

Remove log probably used for debugging

---

Cargo.lock
Cargo.toml
linera-witty/Cargo.toml
linera-witty/README.md
linera-witty/src/lib.rs
linera-witty/src/primitive_types/flat_type.rs
linera-witty/src/primitive_types/mod.rs
linera-witty/src/primitive_types/simple_type.rs

The goal is to implement a new crate that generates host side code to interact with Wasm guest modules through a WIT interface. The first step is to represent the fundamental WebAssembly and WIT primitive types.
Use a sub-set of the Rust types as the fundamental primitive types. There are actually two sub-sets: `SimpleType`s and `FlatType`s. A `SimpleType` is part of the set of fundamental types defined for WIT (through the Component Model). The set of `FlatType`s is a sub-set of the set of `SimpleType`s, and represent the types that are natively supported in a WebAssembly virtual machine.
The types are in separate modules because more functionality will be added to them later.

Create initial Witty crate with primitive type definitions

---

linera-chain/src/chain.rs
linera-execution/src/pricing.rs

If fees would exceed `u128::MAX`, they cannot be paid anyway, so block execution should fail.

Fail block execution if fees overflow.

---

Cargo.lock
Cargo.toml
linera-witty/Cargo.toml
linera-witty/src/lib.rs
linera-witty/src/memory_layout/element.rs
linera-witty/src/memory_layout/flat_layout.rs
linera-witty/src/memory_layout/layout.rs
linera-witty/src/memory_layout/mod.rs
linera-witty/src/primitive_types/maybe_flat_type.rs
linera-witty/src/primitive_types/mod.rs

With the fundamental WIT and Wasm types defined previously by #880, the next step is to prepare to handle more complex types. These types are eventually made up of fundamental types, either WIT fundamental types to store in memory or Wasm primitive types to be passed through the host/guest interface as function parameters or result lists.
Create a `Layout` trait to allow representing the memory layout of complex types. Types that implement this trait are heterogeneous lists (thanks to the [`frunk`](https://docs.rs/frunk) crate) of (optional) fundamental WIT types.
`Layout` types can be "flattened". This means that they can be transformed into a layout suitable for using in the host/guest function interface. A `FlatLayout` trait represents a heterogeneous list made up of Wasm primitive …

Add memory layout traits to Witty

---

.github/workflows/rust.yml

The cargo-machete build currently fails because grep-cli v0.1.8 doesn't compile.
Using `--locked` everywhere prevents that kind of surprise: Now the build can only fail if the tool itself publishes a broken version, not if a dependency does.

Use packaged Cargo.lock when installing cargo tools.

---

linera-sdk/src/bin/test-runner/mock_system_api.rs
linera-sdk/src/test/integration/mock_stubs.rs
linera-sdk/src/test/integration/mod.rs

Writing tests for Linera has some small differences to writing normal Rust tests. The biggest one being that unit tests run inside a WebAssembly virtual machine while integration tests must not. Another one is that unit tests that use system APIs must have proper mocks set up.
Incorrectly running the tests leads to some confusing compile errors, which makes it hard to figure out where the root cause is.
If the unit tests are compiled for a target other than Wasm, an explicit runtime error will appear, explaining that it should either run the unit tests with a Wasm VM or make sure they are only executed if the test target is Wasm. For this error to appear instead of other more confusing errors, the mock API for unit tests had to be stubbed in the integration tests module.
~If a Wasm …

Help with diagnosing test errors

---

Cargo.lock
linera-witty/Cargo.toml
linera-witty/src/lib.rs
linera-witty/src/runtime/error.rs
linera-witty/src/runtime/memory.rs
linera-witty/src/runtime/mod.rs
linera-witty/src/runtime/traits.rs

Some types require dynamic memory to be allocated so that they can be sent between the host and the guest Wasm module instance. Wasmer and Wasmtime have slightly different ways to access the guest memory, so an abstraction over them is needed.
Create a `Runtime` trait to represent the runtime implementation (initially the plan is to support Wasmer and Wasmtime), and have an `Instance` trait to represent a guest Wasm module instanced for a specific runtime. Because runtimes have different ways to call guest functions, and because the allocations must be handled by the guest according to WIT's canonical ABI, an `InstanceWithFunction` generic trait is defined. The trait is parameterized with an heterogeneous list of parameters and another list of results. The trait provides the …

Add abstraction to access guest Wasm module memory

---

linera-chain/Cargo.toml
linera-chain/src/data_types.rs
linera-chain/src/manager/mod.rs
linera-chain/src/manager/multi.rs
linera-chain/src/manager/single.rs
linera-core/src/client.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/conversions.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera.rs

This PR contains some minor changes in preparation for BFT chains, as well as a liveness fix for the existing multi-owner chain manager:
Assume there are four equally-weighted validators, A, B, C, and D.
Then for _safety_ purposes, one faulty validator is tolerated.
This change addresses the following _liveness_ issue:
In round 0, block X is proposed, and all validators vote to validate it, so there is a `ValidatedBlock` certificate. However, it only gets sent to A at first, who votes to confirm it, so A has locked block X.
The other validators first see block Y proposed in round 1. Since they haven't locked any block yet, they vote to validate it. Even if they later receive the `ValidatedBlock` certificate from round 0, they now won't vote to confirm it anymore. The three of them create …

Fix liveness issue for multi owner chain manager.

---

linera-views-derive/src/lib.rs
linera-views/src/common.rs

In order to handle the journal (and possibly other management structures), we need to have a way to store administrative data in the key-value store.
This leads to the use of the `MIN_VIEW_TAG` which allows this administrative work to be done. This is done for `MapView`, `SetView`, etc. but not for the struct views.
Implement the `MIN_VIEW_TAG` for the struct views. This allows the use of the journaling for the struct views.

Correct a bug in the construction of views for struct views

---

examples/counter/web-frontend/src/App.js
examples/counter/web-frontend/src/GraphQLProvider.js
examples/counter/web-frontend/src/index.js
examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/fungible/README.md
examples/fungible/src/lib.rs
examples/fungible/web-frontend/src/App.js
examples/fungible/web-frontend/src/GraphQLProvider.js
examples/fungible/web-frontend/src/index.js
examples/social/README.md
examples/social/src/lib.rs
linera-core/src/client.rs
linera-core/src/node.rs
linera-explorer/graphql/schema.graphql
linera-explorer/src/lib.rs
linera-rpc/src/grpc_network.rs
linera-rpc/tests/staged/formats.yaml
linera-sdk/src/contract/system_api.rs
linera-sdk/src/service/system_api.rs
linera-service/src/chain_listener.rs
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs
linera-service/tests/end_to_end_tests.rs

If `linera service` is started for one chain, due to the file lock on the wallet, it's not possible to also start a service for any other chain. So e.g. sending tokens to another local chain will not update its balance.
Make `linera service` listen for and update all owned chains, not just the default chain. All mutations should specify the chain they are applied to explicitly. If a new chain is opened and the wallet contains the secret key for it, it should also be tracked.
This PR is most of the reverted https://github.com/linera-io/linera-protocol/pull/878, with a few changes:
* I didn't add `new_chains` to the `NewBlock` notification. Instead, I'm reading the block itself and check its outgoing messages. This means we're reading every block from disk again; we could later add a flag …

Make node service process all owned chains.

---

linera-witty-macros/Cargo.toml
linera-witty-macros/src/lib.rs
linera-witty-macros/src/unit_tests/wit_load.rs
linera-witty-macros/src/wit_load.rs
linera-witty/Cargo.toml
linera-witty/src/lib.rs
linera-witty/src/runtime/error.rs
linera-witty/src/runtime/memory.rs
linera-witty/src/runtime/mod.rs
linera-witty/src/runtime/test.rs
linera-witty/src/runtime/traits.rs
linera-witty/src/type_traits/implementations/custom_types.rs
linera-witty/src/type_traits/implementations/frunk.rs
linera-witty/src/type_traits/implementations/mod.rs
linera-witty/src/type_traits/implementations/std/floats.rs
linera-witty/src/type_traits/implementations/std/integers.rs
linera-witty/src/type_traits/implementations/std/phantom_data.rs
linera-witty/src/type_traits/implementations/std/primitives.rs
linera-witty/src/type_traits/implementations/std/string.rs
linera-witty/src/type_traits/implementations/std/tuples.rs
linera-witty/src/type_traits/implementations/std/vec.rs
linera-witty/src/type_traits/mod.rs
linera-witty/src/util/mod.rs
linera-witty/src/util/split.rs
linera-witty/tests/common/types.rs
linera-witty/tests/wit_load.rs
linera-witty/tests/wit_type.rs

Complex types should be able to be loaded from guest Wasm modules into host types.
Create a `WitLoad` type that represents types that can be loaded from a guest Wasm module's memory or from a flat layout sent by the guest, both following WIT conventions.
Include a derive macro for the new trait, that currently only supports `struct`s. The generated code loads each field in sequence.
The new macro is tested with the help of a `FakeInstance` that simulates a Wasm guest instance for a `FakeRuntime`.
Part of #906

Create a `WitLoad` trait

---

linera-sdk/src/test/unit/mod.rs
linera-sdk/src/views/system_api.rs
linera-storage/src/lib.rs
linera-storage/src/memory.rs
linera-views/DESIGN.md
linera-views/README.md
linera-views/src/batch.rs
linera-views/src/collection_view.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lib.rs
linera-views/src/log_view.rs
linera-views/src/lru_caching.rs
linera-views/src/map_view.rs
linera-views/src/memory.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/register_view.rs
linera-views/src/rocksdb.rs
linera-views/src/set_view.rs
linera-views/src/value_splitting.rs
linera-views/src/views.rs
linera-views/tests/hashable_tests.rs
linera-views/tests/operations_tests.rs
linera-views/tests/queueview_tests.rs
linera-views/tests/reentrant_tests.rs

Following points:
* The `KeyValueStoreClientBigValue` takes a KayValueStoreClient and builds one that respects the size limitations.
* Put it in `RocksDB` and the memory containers.
I considered using the `parse_u32_from_uleb128` as initially suggested. But it is hard for me how this is an improvement since it can still return errors.

linera-views: Add module to support splitting large values across multiple keys

---

linera-witty-macros/src/lib.rs
linera-witty-macros/src/unit_tests/wit_store.rs
linera-witty-macros/src/wit_store.rs
linera-witty/src/lib.rs
linera-witty/src/type_traits/implementations/custom_types.rs
linera-witty/src/type_traits/implementations/frunk.rs
linera-witty/src/type_traits/implementations/std/floats.rs
linera-witty/src/type_traits/implementations/std/integers.rs
linera-witty/src/type_traits/implementations/std/phantom_data.rs
linera-witty/src/type_traits/implementations/std/primitives.rs
linera-witty/src/type_traits/implementations/std/string.rs
linera-witty/src/type_traits/implementations/std/tuples.rs
linera-witty/src/type_traits/implementations/std/vec.rs
linera-witty/src/type_traits/mod.rs
linera-witty/tests/common/types.rs
linera-witty/tests/wit_store.rs

Complex types should be able to be sent to guest Wasm modules from the host.
Create a `WitStore` trait that represents types that can be stored in a guest Wasm module's memory or lowered into its flat layout so that it can be sent to the guest, both following WIT conventions.
Include a derive macro for the new trait, that currently only supports `struct`s. The generated code stores each field in sequence.
Part of #906

Create a `WitStore` trait

---

linera-witty/src/runtime/memory.rs
linera-witty/src/runtime/unit_tests/memory.rs
linera-witty/src/type_traits/implementations/frunk.rs
linera-witty/src/type_traits/implementations/mod.rs
linera-witty/src/type_traits/implementations/tests.rs
linera-witty/tests/common/types.rs

The `WitType`, `WitLoad` and `WitStore` implementations for `frunk` heterogeneous lists (`HCons` and `HNil` types) weren't respecting the alignment of its elements when reading and writing to memory. This meant that they didn't correctly implement WIT's [canonical ABI specification](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#alignment).
Respecting the alignment for its elements is not simple because the lists are represented by recursive types. The `HCons` type for example can check the alignment of its element (the "head") or of the rest of the list (the "tail"). However, the alignment of a list is defined as the largest alignment of its elements. So using the tail's alignment is not the correct solution. Instead, the alignment of the first …

Fix internal alignment in `frunk` heterogeneous lists

---

linera-witty-macros/src/lib.rs
linera-witty-macros/src/unit_tests/wit_load.rs
linera-witty-macros/src/unit_tests/wit_store.rs
linera-witty-macros/src/unit_tests/wit_type.rs
linera-witty-macros/src/util.rs
linera-witty-macros/src/wit_load.rs
linera-witty-macros/src/wit_store.rs
linera-witty-macros/src/wit_type.rs
linera-witty/src/lib.rs

The code generated by Witty derive macros is non-trivial and is mostly equivalent to the implementation for `frunk`'s heterogeneous lists.
Refactor the Witty derive macros to generate code that use heterogeneous lists instead of code to manually handle each field in a type. This reduces the amount of code generated, centralizes the more complex code in the implementations for `frunk` types and hopefully improves readability of the generated code.
The unit and integration tests that already exist cover the behavior which the refactoring must not change.
This is an unexpected extra work related to of #906.

Use heterogeneous lists in code generated by Witty derive macros

---

linera-core/src/client.rs
linera-core/src/node.rs
linera-core/src/tracker.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/worker.rs
linera-service/src/chain_listener.rs

If an invalid notification with a high block number gets added to the tracker, other, valid, notifications get ignored, and the client fails to update its chains.
`NewBlock` notifications with a correct height but a wrong block hash.
Don't add invalid notifications to the tracker, and filter out `NewBlock` notifications with a wrong hash.
Notifications are already tested and this doesn't break the tests. However, testing invalid notifications would require implementing malicious test validators, which we also don't do for other (more complex) scenarios yet.

Ignore invalid notifications.

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
linera-witty/Cargo.toml
linera-witty/src/imported_function_interface/parameters.rs
linera-witty/src/imported_function_interface/results.rs
linera-witty/src/lib.rs
linera-witty/src/runtime/error.rs
linera-witty/src/runtime/mod.rs
linera-witty/src/runtime/wasmer/function.rs
linera-witty/src/runtime/wasmer/memory.rs
linera-witty/src/runtime/wasmer/mod.rs
linera-witty/src/runtime/wasmer/parameters.rs
linera-witty/src/runtime/wasmer/results.rs
linera-witty/test-modules/Cargo.toml
linera-witty/test-modules/src/export/getters.rs
linera-witty/test-modules/src/export/operations.rs
linera-witty/test-modules/src/export/setters.rs
linera-witty/test-modules/src/export/simple_function.rs
linera-witty/test-modules/wit/export.wit
linera-witty/test-modules/wit/getters.wit
linera-witty/test-modules/wit/operations.wit
linera-witty/test-modules/wit/setters.wit
linera-witty/test-modules/wit/simple-function.wit
linera-witty/tests/common/test_instance.rs
linera-witty/tests/wit_import.rs

The new Witty crate should generate host code that's compatible with the [Wasmer](https://wasmer.io) runtime.
Create a feature gated `wasmer` module in `linera_witty::runtime`, with implementations for the Witty traits. There are two `Instance` implementations, one for newly created instances (`EntrypointInstance`) and one for instances made available inside host functions called by the guest module (`ReentrantInstance`).
Reuse the integration tests for `wit_import`.
Part of #906

Add support for Wasmer in Witty

---

linera-chain/src/chain.rs
linera-chain/src/manager/mod.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/ownership.rs
linera-execution/src/system.rs
linera-explorer/graphql/schema.graphql
linera-rpc/examples/generate-format.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/chain_listener.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

Currently a new chain is always single-owner, with 1.5 round trips. There needs to be a way to open a new multi-owner chain, e.g. for future public chains.
This generalizes the `OpenChain` operation and message, and adds a new `open-multi-owner-chain` command and mutation, so that multi-owner 2.5 round-trip chains can be created.
The node service only tracks newly created single-owner chains for now: To what extent it should automatically select keys for new chains still needs discussion.
A new end-to-end test creates a chain with two owners and asserts that both can create blocks.
Closes https://github.com/linera-io/linera-protocol/issues/896.

Allow creating multi-owner chains.

---

linera-witty-macros/Cargo.toml
linera-witty-macros/src/lib.rs
linera-witty-macros/src/wit_export/function_information.rs
linera-witty-macros/src/wit_export/mod.rs
linera-witty/Cargo.toml
linera-witty/src/exported_function_interface/guest_interface.rs
linera-witty/src/exported_function_interface/mod.rs
linera-witty/src/exported_function_interface/result_storage.rs
linera-witty/src/lib.rs
linera-witty/src/runtime/mod.rs
linera-witty/src/runtime/test.rs
linera-witty/src/runtime/wasmer/export_function.rs
linera-witty/src/runtime/wasmer/mod.rs
linera-witty/src/runtime/wasmtime/export_function.rs
linera-witty/src/runtime/wasmtime/mod.rs
linera-witty/test-modules/Cargo.toml
linera-witty/test-modules/src/import/getters.rs
linera-witty/test-modules/src/import/operations.rs
linera-witty/test-modules/src/import/setters.rs
linera-witty/test-modules/src/import/simple_function.rs
linera-witty/test-modules/wit/entrypoint.wit
linera-witty/test-modules/wit/import.wit
linera-witty/tests/common/test_instance.rs
linera-witty/tests/wit_export.rs
linera-witty/tests/wit_import.rs

The new Witty crate should allow the host to export functions to guest Wasm modules.
Add an `ExportTo<Target>` helper trait and implement a `wit_export` attribute macro that should be used in `impl` blocks. The macro implements `ExportTo` to different Wasm runtime targets, depending on the enabled feature flags. The implementations export the host functions in the `impl` block to guest Wasm instances.
Some generic integration tests were written to check that some different types of host functions can be exported to Wasm guest instances using Wasmtime and Wasmer, and check that the host functions are properly called. The same tests can also run with a `MockInstance` when no Wasm runtimes are enabled to allow some testing without compiling in a Wasm runtime and without having to compile the …

Add `wit_export` attribute macro to export host functions to Wasm modules

---

linera-witty-macros/src/wit_export/function_information.rs
linera-witty/test-modules/src/export/setters.rs
linera-witty/tests/common/test_instance.rs
linera-witty/tests/wit_export.rs
linera-witty/tests/wit_import.rs

Some bits and pieces of technical debt accumulated while the `linera-witty` crate was being merged, which includes one serious bug: exported host functions that were fallible weren't correctly detected and couldn't be used.
Fix the off-by-one bug that prevented fallible functions from being detected by the `wit_export` macro.
Apply some minor fixes that aren't related to any of Witty's specific features. These include:
- Improving documentation
- Increasing test coverage
- Renaming a parameter for consistency
Fallible functions are required for reentrancy, so the next PR will include integration tests that cover it.
Unexpected work related to #906.

Fix detection of fallible functions in Witty

---

linera-service/src/project.rs

`cargo install linera` was broken because relative paths were used to determine the version of `linera-sdk` and `linera-views`.
Use the `linera` binary version.
There is no practical way to test this. `cargo install --bin linera --path .` works however it also worked last time.

`linera project new` version derived from binary version

---

Cargo.lock
linera-witty-macros/Cargo.toml
linera-witty-macros/src/wit_export/function_information.rs
linera-witty/Cargo.toml
linera-witty/src/runtime/borrowed_instance.rs
linera-witty/src/runtime/mod.rs
linera-witty/src/runtime/test.rs
linera-witty/test-modules/Cargo.toml
linera-witty/test-modules/src/reentrancy/getters.rs
linera-witty/test-modules/src/reentrancy/global_state.rs
linera-witty/test-modules/src/reentrancy/operations.rs
linera-witty/test-modules/src/reentrancy/setters.rs
linera-witty/test-modules/src/reentrancy/simple_function.rs
linera-witty/test-modules/wit/global-state.wit
linera-witty/test-modules/wit/reentrancy.wit
linera-witty/tests/common/test_instance.rs
linera-witty/tests/reentrancy.rs
linera-witty/tests/wit_export.rs
linera-witty/tests/wit_import.rs
linera-witty/tests/wit_load.rs
linera-witty/tests/wit_store.rs
linera-witty/tests/wit_type.rs

One of the main goals of the Witty crate is to make it easy to export host functions to guest Wasm modules in a reentrant manner, i.e., allowing the host functions to call back to the guest before returning.
Allow reentrant functions to be defined in `impl` blocks that use the `#[wit_export]` attribute procedural macro by having the functions have a generic type parameter representing the Wasm runtime-specific caller instance. The macro automatically detects this and generates code that will handle the parameter in a special manner.
Since the caller type has to be borrowed by the handler closure, the runtime instance traits must also be implemented for `&mut T`, not just `T` anymore.
Some new integration tests are included which have reentrant functions. These functions are called by the …

Add reentrancy support to Witty

---

examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/social/README.md
examples/social/src/lib.rs

If no `--wallet` and `--storage` is specified, `linera` uses the `LINERA_WALLET` and `LINERA_STORAGE` environment variables, so we set these in the example `README.md` files.
The `crowd_funding` and `social` examples use two wallets, though, so it is confusing if one of them is implicit.
Also, a `LINERA_WALLET1` was missed in the `crowd_funding` README.
In the `crowd_funding` and `social` examples, use `LINERA_WALLET1` and `LINERA_STORAGE1` or `2` and specify them on the command line everywhere.
No code was changed, and we currently don't have tests for the README file commands.

Make wallet and storage explicit in READMEs with multiple wallets.

---

linera-witty-macros/src/wit_export/function_information.rs
linera-witty-macros/src/wit_export/mod.rs
linera-witty/tests/common/test_instance.rs
linera-witty/tests/reentrancy.rs

After support for reentrant functions was added to Witty (#960), the only way to declare a function as reentrant was to add a generic parameter in the function. This also required adding the constraints for that type in the function, and this code quickly became repetitive in types that exported multiple reentrant functions.
Allow the generic type parameter for the caller (and its constraints) to be defined once in the `impl` block and then shared by all functions inside the block.
Uses the same integration tests for reentrancy as #960.
Closes #963

Simplify generics for exporting reentrant functions with Witty

---

linera-chain/src/data_types.rs
linera-chain/src/manager/mod.rs
linera-chain/src/manager/multi.rs
linera-core/src/client.rs
linera-core/src/tracker.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-explorer/graphql/schema.graphql
linera-explorer/src/graphql.rs
linera-rpc/tests/staged/formats.yaml
linera-sdk/src/test/integration/chain.rs
linera-service/src/chain_listener.rs
linera-service/src/linera.rs
linera-storage/src/lib.rs

For the BFT consensus protocol, validators will need to notify clients when a new consensus round starts, and sign to skip a round if it times out.
Add a `NewRound` notification reason, and a `LeaderTimeout` certificate value.
These values aren't used yet, so there is nothing to test. This PR is in preparation for the BFT consensus, to keep the diff with the main branch small.
Public chains issue: https://github.com/linera-io/linera-protocol/issues/464
BFT consensus draft: https://github.com/linera-io/linera-protocol/pull/928

New round notification, leader timeout value

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/crowd-funding/src/lib.rs
examples/crowd-funding/src/service.rs
examples/fungible/src/lib.rs
examples/fungible/src/service.rs
examples/matching-engine/src/lib.rs
examples/matching-engine/src/service.rs
examples/social/src/lib.rs
examples/social/src/service.rs
linera-sdk-derive/Cargo.toml
linera-sdk-derive/README.md
linera-sdk-derive/src/lib.rs
linera-sdk-derive/src/utils.rs
linera-sdk/Cargo.toml
linera-sdk/src/graphql.rs
linera-sdk/src/lib.rs
linera-service/tests/end_to_end_tests.rs

The MutationRoot used for the GraphQL flavour of Linera services was boilerplate and can be code generated.
A derive macro is used on top of operations which are the only mutations that are made to state. 
Tested by unit tests and integration tests in the form of it being used by example applications.
Closes #876.

Code generate mutation root

---

kubernetes/dev/validator/linera-proxy.yaml
kubernetes/dev/validator/linera-server.yaml
kubernetes/dev/validator/linera-serviceaccount.yaml

Motivation for this is that we need to move things to GCP as a first step towards having Elastic Validators deployed on GCP.
These are the initial configs to deploy the existing static Validators into GCP
Deploy validators to GCP, call them through a client in my laptop to do a transaction and also benchmark.
Issue: #910

Kubernetes deployment for Validators

---

examples/counter/tests/single_chain.rs
examples/crowd-funding/tests/campaign_lifecycle.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/Cargo.toml
linera-execution/src/wasm/system_api.rs
linera-execution/tests/wasm.rs

Some tests were deadlocking. This happened when a Wasm application performs a call to a synchronous system API that was asynchronous under the hood. The way to make the call synchronous was to block on the thread, which prevented the code to advance if there was only one worker thread for the Tokio runtime.
As a temporary solution, notify Tokio that the worker thread is about to block, and ensure that tests that need it have more than one worker thread.
Current tests should now not deadlock in some scenarios.
A proper fix should be implemented in #971

Workaround deadlock in tests during calls to sychronous system APIs

---

examples/fungible/README.md
examples/fungible/src/lib.rs
examples/social/README.md
examples/social/src/lib.rs

`realpath` doesn't work on MacOS shells by default.
Use `$PWD` instead. This is good enough and also less verbose.
Tried one example by hand.

avoid `realpath` in README files

---

linera-core/Cargo.toml
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-service/src/node_service.rs

By the book, `anyhow` should not be used in libraries
Create a new error type `ChainClientError` to replace anyhow
CI
fixes #66 
I created #987 to finish replacing `is_err` in worker tests.
See also #907 and #904

Create ChainClientError to replace anyhow

---

linera-chain/src/manager/mod.rs
linera-chain/src/manager/multi.rs
linera-core/src/data_types.rs
linera-core/src/worker.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/conversions.rs
linera-rpc/tests/staged/formats.yaml

This is part of the BFT protocol implementation, but doesn't contain actual handling logic yet.
Add a field to the chain info query to request leader timeout votes. In the future, this will be used to make the validators sign `LeaderTimeout` certificates if a round is stalled, but for now the handlers are stubs.
No tests yet, since this doesn't include the handling logic yet.
This is mainly to reduce the diff with my WIP for https://github.com/linera-io/linera-protocol/issues/464.

Extend chain info query and chain manager with stubs for leader timeouts.

---

linera-chain/src/manager/mod.rs
linera-chain/src/manager/multi.rs
linera-chain/src/manager/single.rs
linera-core/src/client.rs
linera-execution/src/ownership.rs
linera-rpc/tests/staged/formats.yaml

`ChainClient::share_ownership` should only add the new owner, not remove any existing ones.
For multi-owner chains, `share_ownership` should take a list of all existing owners and add the new one.
This PR also adds a sanity check to the single-owner manager, and a minor cleanup to `worker.rs`.
There are already tests for `share_ownership`. If desired, we can add new ones for the case where there are multiple existing owners, but the details of this will soon change again, when weights are added, so it would be easier to add more tests after that.
This is mainly to reduce the diff with my WIP for https://github.com/linera-io/linera-protocol/issues/464.

Fix share_ownership: Don't remove keys.

---

linera-execution/src/committee.rs
linera-rpc/tests/staged/formats.yaml

Epochs are expected to last hours rather than minutes, so a `u32` can still represent half a million years' worth of epochs. With a `u64`, the upper four bytes would always be wasted.
Represent the epoch as a `u32`.
This doesn't change the logic, only the limit of the epoch number.
N/A

Make Epoch a u32

---

linera-core/src/unit_tests/client_test_utils.rs
linera-service/src/linera.rs
linera-service/src/server.rs
linera-service/src/storage.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/rocks_db.rs
linera-storage/src/scylla_db.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/lru_caching.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/unit_tests/dynamo_db_context_tests.rs
linera-views/src/unit_tests/views.rs
linera-views/src/value_splitting.rs
linera-views/tests/operations_tests.rs
linera-views/tests/views_tests.rs

The development of the database code has led to different APIs which are a downside. This work unifies and simplifies a lot of database stuff and unfortunately leads to a lot of changes. If needed, this could be broken up into several PRs.
The following changes were made:
* The `create_if_missing` argument is passed to each constructor and the `restart_database` has been removed.
* That led to the introduction of `test_table_existence` code for detecting if there is a table or not.
* We introduced a `new_for_testing` that remove the database before creating it. It is useful for tests.
* Thus we have 4 arguments, `max_concurrent_queries`, `max_stream_queries`, `cache_size` and `create_if_missing`. This led to the introduction of a type `CommonStoreConfig` for RocksDb, DynamoDb, and …

Restructuration of the database API code

---

linera-core/src/unit_tests/client_test_utils.rs

A change was forgotten in the previous PR. It passed the CI, but could not be run two times.
That PR addresses that.
Replace `new` by `new_for_testing`.
The CI should show it, but otherwise, the problem is visible by running the tests on branch `main`
two times. The first time it passes, but not the next.

Missed correction

---

examples/crowd-funding/src/contract.rs
examples/crowd-funding/tests/campaign_lifecycle.rs
examples/fungible/src/contract.rs
examples/matching-engine/src/contract.rs
linera-base/src/data_types.rs
linera-chain/src/manager/mod.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-chain/src/unit_tests/outbox_tests.rs
linera-core/src/tracker.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-execution/src/committee.rs
linera-execution/src/system.rs
linera-execution/src/unit_tests/applications_tests.rs
linera-rpc/src/conversions.rs
linera-service/src/config.rs
linera-service/src/linera.rs
linera-storage/src/lib.rs

The wrapped numbers' `zero` and `max` functions don't work in constant contexts. `max` also shadows [`Ord::max`](https://doc.rust-lang.org/std/cmp/trait.Ord.html#method.max).
The standard library uses constants instead.
`impl_wrapped_number!`, as opposed to `impl_strictly_wrapped_number!`, only contains functionality specific to `BlockHeight`.
Rename the strict variant to `impl_wrapped_number!` and remove the other one. Replace `zero` and `max` by constants.
No logic is changed.
N/A

Clean up impl_wrapped_number macro.

---

linera-base/src/data_types.rs
linera-chain/src/lib.rs
linera-chain/src/test.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/benches/client_benchmarks.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/system.rs
linera-rpc/src/conversions.rs
linera-service/src/linera.rs

The worker tests contain a lot of repetitive code, mostly for creating blocks. The lack of utilities also makes it hard to write new tests.
Add utility functions for block creation, execution state and others, and deduplicate a lot of code in the `worker_tests` and `wasm_worker_tests`.
Logically, the tests should be unchanged. This is just a refactoring.
N/A

Add test utilities for creating blocks.

---

linera-base/src/identifiers.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/applications.rs
linera-execution/src/graphql.rs
linera-execution/src/lib.rs
linera-rpc/examples/generate-format.rs
linera-rpc/tests/staged/formats.yaml

Avoid name collisions.
I thought we could remove `linera-execution::ApplicationId` entirely but it's tricky because of pub/sub channels.
CI

rename linera-execution::ApplicationId into GenericApplicationId

---

configuration/prod/validator_1.toml

Prod validators should use Grpc by Default.
Change the validator.toml to Grpc.
Coming with the Kubernetes integration tests.

Changed validator protocol to Grpc

---

Dockerfile.aarch64

Enable local validators for Apple Silicon built in Docker and deployed on `kind`.
A second Dockerfile which is customised for `aarch64`.
`docker build -f Dockerfile.aarch64 .`

Added Dockerfile for aarch64 used to run validators locally

---

linera-service/src/linera.rs
linera-service/src/server.rs
linera-service/src/storage.rs

`run_with_storage` has an unnecessarily complicated trait bound that depends on several feature flags.
Make the `Runnable` trait work with any `Store` implementation whose `ContextError` can be converted to a `ViewError`. That's all we really need for `run_with_storage`.
Possible alternatives:
* Add an associated `type ContextError` and require that it's `From<S::ContextError>`. In both our `Runnable` implementations that would be set to `ViewError`.
* On the other hand, we could also _remove_ the associated `type Output`, since it's always `()`.
N/A

Simplify Runnable trait.

---

kubernetes/linera-validator/build_and_redeploy.sh
kubernetes/linera-validator/templates/server.yaml

Shard pods used ephemeral storage meaning that if a shard died the corresponding rocksdb instance would also die.
Until we support ScyllaDB, this workaround introduces persistent volumes to Pods so that the rocksdb instance behind each shard is persisted even if a pod dies.
Tested manually by killing a pod and verifying that the RocksDB directory is unchanged when the `ReplicaSet` controller spins up a new pod.
https://kubernetes.io/docs/concepts/storage/persistent-volumes/

Persistent volumes for shards

---

linera-indexer/Cargo.toml
linera-service/src/client.rs

Try to figure out one question left in #1028
Make `rocksdb` a required feature by `linera-indexer`, instead of `default`.
CI

iterate on #1028

---

linera-explorer/package.json
linera-explorer/src/components/utils.ts
linera-explorer/vite.config.ts

Explorer tests are failing because of unstability of environment or wasm file not available 
- retry intialization of wasm file
- change test environment from 'appy-dom' to 'jsdom'

More stable environment for vitest

---

linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs

A quick way to address #989 is to let clients remove incoming messages that fail one by one. To do so, we need better error reporting.
Add a second parameter `ChainExecutionContext` when converting `ExecutionError` into `ChainError`.
CI

Report the execution step that triggered an execution error

---

linera-indexer/example/tests/test.rs
linera-service-graphql-client/tests/test.rs
linera-service/src/client.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/readme_test.rs
linera-service/tests/wasm_end_to_end_tests.rs

A near-term objective that we have is to make the end-to-end tests to other storage systems than RocksDB. That is ScyllaDB and DynamoDB with the emphasis on ScyllaDB. This PR exposes the underlying storage systems. It builds the tests but put them as ignore since some do not work.
Doing that PR exposed a number of issues with the code:
* The code in `linera.rs` uses a `LocalNetwork` and it is taking a RocksDb. Not sure what would be the right way to do.
* Now to the meat of the problem, an `enum Database` was created with three values: `RocksDb`, `DynamoDb` and `ScyllaDb`.
* The tests in `end_to_end_tests.rs` and `wasm_end_to_end_tests.rs` were demultiplicated to handle the `RocksDb`, `DynamoDb` and `ScyllaDb`. All the DynamoDb and ScyllaDb have been put as ignore and the resolution …

Expose the end to end tests to different Storage systems

---

README.md
docker/local-tests/run-server.sh
linera-core/src/unit_tests/client_test_utils.rs
linera-indexer/example/tests/test.rs
linera-indexer/lib/src/rocks_db.rs
linera-indexer/lib/src/scylla_db.rs
linera-service-graphql-client/tests/test.rs
linera-service/Cargo.toml
linera-service/src/client.rs
linera-service/src/database_tool.rs
linera-service/src/linera.rs
linera-service/src/server.rs
linera-service/src/storage.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/readme_test.rs
linera-service/tests/wasm_end_to_end_tests.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/rocks_db.rs
linera-storage/src/scylla_db.rs
linera-views/Cargo.toml
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/memory.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/unit_tests/dynamo_db_context_tests.rs
linera-views/src/unit_tests/views.rs
linera-views/tests/views_tests.rs
scripts/run_local.sh

The readme test was missing for ScyllaDb, this PR addresses it. This forces a number of changes.
The restructuration is wide-ranging for this simple operation:
* The handling of the different storage has been moved from `storage.rs` to a new file `aggregator.rs` in the linera_views. This is done because the aggregation of the storages is functionally different from what we do with it.
* The `create_if_missing` is eliminated. Instead, when calling `new`, you should have an existing database. If you want to create a new one, then use the `new_for_testing` which is used for the tests.
* For non-test related use, there is a call to `initialize` added to a `linera.rs` and `server.rs` and a new `linera-db` program for initializing.
* The `linera-db` does 3 different operations: delete_all, …

Implement readme test for ScyllaDb

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/updater.rs

To support the full BFT consensus protocol, the `linera` client will need the ability to request `LeaderTimeout` votes from validators once a round has timed out.
Add `ChainClient::request_leader_timeout`.
Includes a client test.
An end-to-end test will be added in the future, when the rest of the client-side functionality is added.
Part of https://github.com/linera-io/linera-protocol/issues/464.

Implement ChainClient::request_leader_timeout

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-indexer/example/src/main.rs
linera-indexer/lib/src/indexer.rs
linera-indexer/lib/src/plugin.rs
linera-indexer/lib/src/rocks_db.rs
linera-indexer/lib/src/runner.rs
linera-indexer/lib/src/scylla_db.rs
linera-indexer/plugins/src/operations.rs
linera-sdk/src/test/integration/validator.rs
linera-service/src/storage.rs

We use the name `client` for implementations of `Store`, `ValidatorNode`, and others.
This gets confusing in contexts where different kinds of clients are in play.
Rename `client` to `store` if it is outside of `linera-storage` and `linera-views` and refers to a `Store` implementation.
Rename `client` to `node` if it refers to a `ValidatorNode` implementation.
No logic is changed.
N/A

Rename "client" to "store" or "node" to disambiguate.

---

linera-core/src/unit_tests/worker_tests.rs

To fix #987 
Tried replace is_err() with suitable messages with already exisiting messages

[Issue #987] Replace is_err() with suitable messages

---

kubernetes/linera-validator/redeploy.sh
kubernetes/linera-validator/templates/server.yaml

There were some changes made in how storage works, so we need to adapt our local run to it
1. Copy the client's db generated in the Dockerfile over to `/tmp` so things work properly
2. Make sure server's db is initialized before running the server
Run cluster locally, make sure everything works

Fix local Kubernetes run after storage changes

---

examples/amm/src/lib.rs
linera-service/src/cli_wrappers.rs
linera-service/tests/wasm_end_to_end_tests.rs

fixes #828
* Use typed ABI interfaces as in the rest of the code.
* Convert to `serde_json::Value` then `async_graphql::Value` via the trait `InputType`.
CI

Avoid using `String::replace` to quote JSON in GraphQL queries

---

.github/workflows/dynamodb.yml
.github/workflows/scylladb.yml

It's sometimes hard to tell what went wrong if the ScyllaDB or DynamoDB CI fails.
Enable WARN-level logs, just like in `rust.yml`.
This should make debugging easier, but doesn't change production code.
N/A

Enable WARN-level logging for ScyllaDB/DynamoDB CI.

---

linera-service/src/cli_wrappers.rs
linera-service/src/linera.rs

Local network testing often requires multiple wallets - `linera net up` only initializes a single wallet meaning users need to do this manually.
Add ` --wallets` argument to `linera net up` to specify the number of extra wallets required (defaults to 0).
Run `linera net up --wallets 3`; in a new terminal use the export commands for one of the extra wallets and run `linera sync-balance`.

linera net up optionally generates extra wallets

---

linera-chain/src/manager/multi.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs

For the BFT protocol to be live, the leader of the current round must be able to:
* fetch all the honest validators' locked blocks (a `ValidatedBlock` certificate),
* find the one with the highest round number,
* re-propose that block in the current round, citing the locked block certificate,
* and be sure that this certificate will still be in a greater or equal round than the honest validators' locked blocks.
That is only guaranteed if between the first and last point nobody else can change the validators' locked blocks. That's why sending a `ValidatedBlock` certificate from a past round to a validator won't update their locked block.
However, the leader's client itself is also using a chain manager to collect all the locked blocks, and needs to keep track of the latest one, even if …

Update locked block from past rounds if we're not a validator.

---

.github/workflows/documentation.yml
.github/workflows/dynamodb.yml
.github/workflows/explorer.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml
Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml

Faster CI
Use Ubuntu 16 cores instead of 8 cores
CI
Comparing to #1067:
- Scylladb goes from 8min to 5min
- DynamodDb goes from 9min to 8min :-|
- Rust goes from 37min to 28min

CI: use 16 cores instead of 8 cores

---

linera-core/src/unit_tests/wasm_client_tests.rs
linera-execution/src/execution.rs

Failing user messages currently block chains because clients do not have the logic to skip them (#904, #989).
Skip messages creating user errors for now. This is not the desired semantics (#989) but we need to unblock users (#1071).
CI
fixes #904
fixes #1071

Quick fix to skip failing user messages

---

Cargo.lock
linera-indexer/example/Cargo.toml
linera-indexer/example/tests/test.rs
linera-service/Cargo.toml
linera-service/src/cli_wrappers.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

* Make the number of validators and shards configurable in `linera net up`
* Make the default number of shards depend on the database during testing
* Improve output of `linera net up` (not perfect but already better)
* Use rocksdb with 1 shards by default
I also verified that the temporary directory was cleaned up (unless one presses ^C first).
```
cargo run --bin linera -- net up --wallets 1 --validators 2 --shards 3
```
Sample output:
```
[...]
A local Linera network was started using the following temporary directory:
/var/folders/3y/9r0jlrxj6mncs9d2m1vpvqqh0000gn/T/.tmpKOuBhd
To use the initial wallet of this network, set the following environment variables:
export LINERA_WALLET="/var/folders/3y/9r0jlrxj6mncs9d2m1vpvqqh0000gn/T/.tmpKOuBhd/wallet_0.json"
export …
```

Make the numbers of validators and shards configurable in `linera net up` and e2e tests

---

linera-views/src/scylla_db.rs

ScyllaDb is fast developing as our main system and so we need to provide as good a support as possible.
Following two improvements are made:
* The `table_name` are tested for validity before creating and having an error later.
* The `table_name` is no longer used for the key. We need to have a dummy key unfortunately.
The CI should do it.

Minor improvements to `ScyllaDb` support

---

linera-views/src/scylla_db.rs

We want to have better support for concurrency in `ScyllaDb`. This PR allows to read several keys at once.
It is quite straightforward and follows what is done for `DynamoDb`.
The CI should suffice.

Better code for reading several keys in `ScyllaDb`.

---

kubernetes/linera-validator/build_and_redeploy.sh
kubernetes/linera-validator/templates/ingress.yaml

There's a wait to tell helm commands to wait until things are initialized. See @christos-h's comments on #1073
Stop using `sleep` and use `--wait` instead
CI

Removing sleep from build_and_redeploy.sh

---

linera-views/src/dynamo_db.rs

The work on the end-to-end tests has revealed some bugs.
The following corrections are done:
* The limit being used was the one for the batch, not the one for the transactions. That is 16M instead of the 4M size. The batch size is removed since we no longer use this feature.
* When checking is the fast path is feasible we used the number of transactions (limit is 100), but actually, we also need to check for the size.
* The error that required the most work for correction is that the journal was put into a single entry. Since it is limited to 400K, this created another error.
* An assert statement was added for the size of the serialized object. Since size is the key point, it makes sense to compute the exact size.
* When creating the journals, each block (which has at most 400K) is …

Resolve bugs in DynamoDb support.

---

Cargo.lock
linera-base/src/crypto.rs
linera-service/Cargo.toml
linera-service/src/cli_wrappers.rs
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/src/server.rs
linera-service/tests/end_to_end_tests.rs
scripts/run_local.sh

Writing documentation where the generated keys are predictable. This should help readability and eventually testability of the bash scripts in CI.
* Add new CLI options to store a PRNG seed in wallets
* Use it for all key generation
* Same for validator keys
PR is on top of #1080  
I ran the `scripts/run_local.sh` manually several times and followed the README file of crowd-funding.
I also run `linera net up` several times and inspected the temporary directory.

Make key generation (optionally) reproducible for manual testing

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/worker.rs
linera-service/src/chain_listener.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs

In https://github.com/linera-io/linera-protocol/pull/1066 we are seeing a deadlock that is related to the notification stream.
Also, the notification stream for GraphQL subscribers should be based on the local node's view, instead of a merged and filtered version of subscriptions to the validators. It should only contain notifications for the specified chain IDs.
Finally, local workers should share a value cache and delivery notifications, since they also share the same storage.
Add a `ChainClientBuilder` that creates notifiers and a value cache. All `ChainClient`s build with it will share clones of the same notifiers and cache.
`QueryRoot::subscribe` returns a stream from the local notifier.
This fixes the failing test in https://github.com/linera-io/linera-protocol/pull/1066.
- …

Share notifiers and cache among chain clients; listen to local notifications.

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_test_utils.rs

`ChainClient::new` is now only used in a test.
Use the builder in the test; remove `new`.
No change in logic or functionality.

Remove unused ChainClient::new.

---

examples/meta-counter/src/contract.rs
linera-chain/src/data_types.rs
linera-core/src/client.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/system.rs
linera-rpc/tests/staged/formats.yaml

The application ID is not necessarily derived from the block's last outgoing message: There might be additional messages created by the application's initialization itself.
Find the created application IDs by inspecting the outgoing messages. Do the same for published bytecode and created chains.
Possible alternatives:
* Group the outgoing messages in `ExecutedBlock` by the transaction that created them.
* Put [the application messages](https://github.com/linera-io/linera-protocol/blob/d98e798f99bc6b78d5136d8eeefb1e50ad3fc44a/linera-execution/src/execution.rs#L273) before the `CreatedApplication` message.
* Explicitly include the created application IDs as a separate field in the `ExecutedBlock`.
I extended the `meta-counter` to send a no-op message to itself on `initialize`. That broke …

Fix application ID computation.

---

Cargo.lock
examples/Cargo.lock
linera-sdk/Cargo.toml
linera-sdk/src/bin/test-runner/main.rs

* `test-runner --help/--version` doesn't work.
* I need `--version` to work to add version checking (for all linera binaries) in a next PR.
* Use `structopt` to parse the command line
Not making a separate crate just yet because of the mocked APIs.
Not renaming the test-runner yet because `test_rocks_db_project_test` expects the runner to be installable with `cargo install linera-sdk` from the network.
CI

Improve CLI parsing in Wasm test runner

---

Cargo.lock
linera-explorer/package.json
linera-indexer/example/Cargo.toml
linera-indexer/example/tests/test.rs
linera-indexer/graphql-client/Cargo.toml
linera-indexer/graphql-client/tests/test.rs
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service-graphql-client/tests/test.rs
linera-service/src/cli_wrappers.rs
linera-service/src/linera.rs
linera-service/src/project.rs
linera-service/src/schema_export.rs
linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs

We have three ways to obtain Linera binaries at the moment: release mode (look up in CARGO_HOME), debug mode (cargo build), test-runner (look up in CARGO_HOME + cargo install if needed).
This is rather complicated and create some subtle limitations:
* We cannot run tests in release mode (it will fetch the binaries with cargo install)
* We cannot rename the test runner because `cargo install` from the network would break CI.
In the long term, `cargo` should eventually provide a way to depend on the binaries of another crate (https://github.com/rust-lang/cargo/issues/9096). In the meantime, we only have partial solutions. At least we're going for a simple one here (removing lots of code such as the feature detection).
1) Use a single `resolve_binary` function what all the cases.
* In …

Simplify dependencies to Linera binaries

---

linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-service/src/storage.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/lib.rs
linera-storage/src/memory.rs
linera-storage/src/rocks_db.rs
linera-storage/src/scylla_db.rs
linera-storage/src/unit_tests/dynamo_db.rs
linera-storage/src/unit_tests/rocks_db.rs
linera-storage/src/unit_tests/scylla_db.rs

The trait `Store` is currently implemented by e.g. `RocksDbStoreClient`, not by `RocksDbStore`. This is confusing.
Rename `RocksDbStore` to `RocksDbStoreInner`, and `RocksDbStoreClient` to `RocksDbStore`. Same for the other backends.
Also rename `make_test_client` to `make_test_store`.
Only renaming, no new logic.
- Discussion on an earlier PR: https://github.com/linera-io/linera-protocol/pull/1045#discussion_r1331943190

Rename some storage types to match the `Store` trait name.

---

linera-explorer/src/lib.rs
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/src/project.rs
linera-service/src/storage.rs
linera-service/src/util.rs

Compared to using `anyhow!` or `bail!` directly,
* The `anyhow::Context` methods are more concise and preserve more information about the original error. (The resulting `anyhow::Error` can still be downcast.)
* `anyhow::ensure!` is more concise and—at least if the condition is not a negation—often more readable.
Replace some usages of `anyhow!` and `bail!`.
Import `Context as _` to avoid confusion with `linera-views`' `Context` trait.
Qualify `anyhow::ensure!` to avoid confusion with `linera-base`'s `ensure!` macro.
We could extend the latter at some point to accept formatting arguments.
- Related discussion: https://github.com/linera-io/linera-protocol/pull/1107#discussion_r1353232197
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTR …

Use anyhow's ensure and Context where appropriate.

---

linera-service/src/database_tool.rs
linera-service/src/storage.rs
linera-views/src/dynamo_db.rs
linera-views/src/scylla_db.rs
linera-views/src/unit_tests/dynamo_db_context_tests.rs

When working, it is useful to have the list of tables that have been created.
The proposal is introducing the feature and consist of the following actions:
* Exposition of the already existing `list_tables` of `DynamoDb`.
* Creation of the `list_tables` functionality for `ScyllaDb`.
* Addition of the feature to the `linera-db` tool.
The list is printed directly with a `println` statement and I could not find a better way.
It is not part of the CI but I have tested the feature on my laptop both for `ScyllaDb` and `DynamoDb`.
- [reviewer …

Reads the list of all the tables that have been installed for `DynamoDb` and `ScyllaDb`.

---

linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs

Fix `cargo build --bins && target/debug/linera net up` after #1107 
Make `util::resolve_binary` return an absolute path.
The issue occurs when the current binary is a relative path. Before #1107, `cargo_force_build_binary` was calling `.canonicalize()`.
CI
The new integration test covers this use case:
```
cargo build --bins && target/debug/linera net up
```

add missing canonicalize for util::resolve_binary

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-core/Cargo.toml
linera-core/benches/client_benchmarks.rs
linera-core/benches/recorder.rs
linera-service/Cargo.toml
linera-service/src/lib.rs
linera-service/src/server.rs
linera-storage/Cargo.toml
linera-storage/src/lib.rs
linera-views-derive/src/lib.rs
linera-views/Cargo.toml
linera-views/src/lib.rs

We're moving everything to Prometheus
So getting rid of the `metrics` crate usage
Ran the benchmark locally, saw the metrics in Prometheus

Change all metrics crate usage to Prometheus

---

linera-core/src/unit_tests/client_test_utils.rs
linera-service/src/cli_wrappers.rs
linera-service/tests/end_to_end_tests.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/scylla_db.rs
linera-views/src/batch.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/scylla_db.rs
linera-views/src/test_utils/mod.rs
linera-views/src/unit_tests/views.rs
linera-views/tests/operations_tests.rs
linera-views/tests/views_tests.rs

The ScyllaDB support is not crash-resistant and that is a problem for operations
We use the batch that allows us to implement this feature. The following changes are done:
* Introduction of a `get_random_key_prefix` for obtaining a `key_prefix`.
* Movement of `get_table_name` and related from `common.rs` to `test_utils.rs`.
* Expansion of the tests to detect more problems.
* Introduce the `write_batch` using the ScyllaDb batches.
There are some limitations on size and I am inquiring on how to address them without changing the rust code.
CI
- [reviewer …

Introduction of crash resistant batching for ScyllaDB.

---

Cargo.lock
Cargo.toml

We currently have problems with the `res_peer` test case. Bumping the version of RocksDB is a possible way to address the problem. If it does not work then it should not help.
Update the `Cargo.toml` and `Cargo.lock` files.
CI

Bump the version of RocksDB.

---

linera-views/src/scylla_db.rs
linera-views/tests/operations_tests.rs

The case of prefix of the form `[255, ..., 255]` is handled separately in some storages. It deserves to be tested.
A bug in the `ScyllaDb` code is corrected. However, that error does not appear to introduce a bug so there is more discussion to be had with `ScyllaDb` people.
The improved CI.

Correct an error in `ScyllaDb` and handle one more scenario in the tests

---

linera-execution/src/wasm/system_api.rs

Calls to the `find_key_values` function available in the Wasm system API could hang. The root cause was that the host future that executes the functionality was not added to the contract's host future queue.
This led to two issues, the first is that execution could be non-deterministic, since the call could complete before or after other asynchronous calls in different validators since the host future queue could not enforce deterministic completion order of the future.
The second is that execution could hang. This happened when the call to the store layer didn't complete immediately and there were no other remaining asynchronous calls still in execution. More precisely, when the host future queue is empty and when the call returns `Poll::Pending`. When it eventually needs to progress …

Fix hang in `find_key_values`

---

docker/Dockerfile
docker/Dockerfile.aarch64
docker/Dockerfile.local
docker/Dockerfile.local-aarch64
docker/server-entrypoint.sh
docker/server-init.sh
kubernetes/linera-validator/Chart.lock
kubernetes/linera-validator/build_and_redeploy.sh
kubernetes/linera-validator/templates/scylladb.yaml
kubernetes/linera-validator/templates/server.yaml
linera-service/src/storage.rs

Linera validators require a horizontally scalable database, in this case ScyllaDB.
Add ScyllaDB as the default database for Kubernetes validators - replacing RocksDB. 
For now this is a single instance (not the horizontally scalable Helm deployment).
1. `./build_and_redeploy.sh --clean`
2. Copy/Paste the generated wallet exports
3. `linera sync-balance`

Scylla db in validator

---

linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/util_tests.rs

* Some variable names were confusing
* The case of a current binary (e.g. `linera`) in the PATH was working only for interactive bash shells. It appears that only those set $0 to be the full resolved path. Non-interactive bash shell will $0 set to `linera`. (This happens to me in the next PR.)
* Fix variable names
* Use `std::env::current_exe()` instead of `argv[0]` to find the fully resolved path to current executable.
* Add the long-overdue unit tests.
CI

Fix resolve_binary (again)

---

README.md
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/readme_test.rs
linera-service/tests/util_tests.rs
scripts/linera_net_helper.sh

Deprecate the bash logic to spawn a local test network, make sure we catch regression with `linera net up`
* Separate stdout and stderr in `linera net up`
* Interpret stdout in bash to define the appropriate wallet environment variables
* Create a helper script with some logics to wait for READY! to be output so that we don't have to use `sleep` in bash
* Introduce an option --with-wallet N to select a different pair of environment variables ending with _$N
* Add signal handlers so that ^C (SIGINT) and SIGTERM don't create zombie processes.
* Rename linera --wallets M into --extra-wallets M. If present (including M=0), the stdout is modified, so that environment variables end with _{0..=M}
CI
Also works in interactive shells (although it's a bit dirty as adds a `trap`)
```
source …
```

Make it possible to use `linera net up` in bash scripts

---

Cargo.lock
examples/Cargo.lock
linera-chain/Cargo.toml
linera-chain/src/chain.rs

Going through the metrics here: https://docs.google.com/spreadsheets/d/1tHo8iKzrlkuYeN2Yu7a6MfwQd-P2KNA9BlnhcASoEQY/edit?pli=1#gid=0
Implementing number of blocks executer Counter metric

Log number of blocks executed metric

---

Cargo.lock
examples/Cargo.lock
linera-execution/Cargo.toml
linera-execution/src/execution.rs

Implementing number of rounds in proposals Histogram metric
Ran validator locally, published and created a Fungible application, and saw metric properly logged:

Log Wasm fuel used per block

---

linera-indexer/example/tests/test.rs
linera-service-graphql-client/tests/test.rs
linera-service/src/cli_wrappers.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

Production code should usually return errors instead of panicking.
Use `anyhow` in `cli_wrappers` instead of `unwrap()`, `panic!` and `expect()`.
Only `build_example` and `example_path` was made test-only, since these are about the Linera example applications.
- Supersedes https://github.com/linera-io/linera-protocol/pull/1124.

Use anyhow in CLI wrappers instead of panicking.

---

linera-service/tests/readme_test.rs
scripts/linera_net_helper.sh

Fix `RUST_LOG=debug cargo test readme` (broken by #1126)
Call `trap SIGPIPE` to keep `tee` alive.
CI

Fix RUST_LOG=debug cargo test readme

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/manager/mod.rs
linera-chain/src/manager/multi.rs
linera-chain/src/manager/single.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/src/client.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-execution/src/system.rs
linera-explorer/src/components/Block.test.ts
linera-explorer/src/components/Blocks.test.ts
linera-rpc/src/conversions.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql
linera-service-graphql-client/src/service.rs

When creating a new application, publishing bytecode or opening a new chain, we currently iterate through the executed block's outgoing messages to find the ID of the message used in the application ID, bytecode ID or chain ID.
In general, the current `ExecutedBlock` structure does not allow mapping the transactions (incoming messages and operations) to the outgoing messages they produced. The outgoing messages are all in one single vector.
Store another vector of cumulative message counts. This way, one can look up the index of the first outgoing message belonging to a particular transaction.
There are already tests for the three chain operations that use this. These would fail if we now returned wrong IDs.
- Might need to bump the major/minor version number in the next release of the …

Add message counts to `ExecutedBlock`.

---

.github/workflows/dynamodb.yml
.github/workflows/scylladb.yml

We do this for Rocksdb tests. Applications are built in the middle of the tests otherwise.
Copy the relevant CI step.
CI

CI: build example applications ahead of tests for DynamoDb and ScyllaDb

---

Cargo.lock
examples/Cargo.lock
linera-chain/src/data_types.rs
linera-core/Cargo.toml
linera-core/src/worker.rs

Implementing number of rounds in certificates Histogram metric

Log number of rounds in certificates

---

README.md
linera-service/src/linera.rs
linera-service/template/linera_net_helper.sh
scripts/linera_net_helper.sh

Currently `linera_net_helper.sh` requires the Linera repository.
Create a new command `linera net helper` that prints the script on stdout.
Users may append the script to their `~/.bash_profile` or `source` it every time.
Modified README example.

Make Linera net helper script available to users of `cargo install`

---

linera-rpc/src/grpc_network.rs

Implementing server request count Counter metric

Log server request count

---

Cargo.lock
examples/Cargo.lock
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-core/src/worker.rs
linera-execution/Cargo.toml
linera-execution/src/execution.rs

It's wasteful to clone a whole certificate, since it can potentially contain large blobs of data like bytecode.
We were meaning to measure the fuel usage per block, not per user action.
Avoid cloning the certificate: Just copy the round number and certificate type description.
Move the fuel log to `execute_block`.
@andresilva91: Could you repeat the local test you did for https://github.com/linera-io/linera-protocol/pull/1137 and confirm the outcome is the same?

Prometheus log fixes

---

scripts/linera_net_helper.sh

@ma2bd and I were discussing what could be done to improve this script, since it currently causes `tee` to throw a lot of errors which are then suppressed, with some performance implications.  I meditated on it a little bit and came up with the following simplification, which seems to work in my tests.
Instead of using `tee` in the spawned process and trap `SIGPIPE` to ensure it isn't accidentally terminated, let `sed` print its pattern space directly, and then simply pick up the FIFO with `cat` (in the background) when it's done.
An alternative approach is possible if we're willing to have `linera net up` (and similar commands that output commands to be sourced on `stdout`) close the channel when they're done, which is slightly simpler.  It's not clear to me what the convention is within …

Simplify linera_net_helper script

---

linera-chain/src/chain.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-execution/src/execution.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-sdk/src/test/integration/chain.rs
linera-service/src/node_service.rs

#1151 was a bit heavy handed and broke name patterns in `linera-chain` and `linera-execution`.
Partially undo #1151
CI

Partially undo renaming of query_application

---

configuration/k8s-local/validator_1.toml
configuration/local/validator_1.toml
configuration/local/validator_2.toml
configuration/local/validator_3.toml
configuration/local/validator_4.toml
configuration/prod/validator_1.toml
docker/local-tests/setup.sh
kubernetes/linera-validator/templates/ingress.yaml
kubernetes/linera-validator/templates/prometheus.yaml
kubernetes/linera-validator/templates/proxy.yaml
linera-rpc/src/config.rs
linera-service/src/cli_wrappers.rs
linera-service/src/grpc_proxy.rs
linera-service/src/proxy.rs
linera-service/src/server.rs

We need metrics on the Proxy side
Adding Prometheus metrics support on the proxy side
1. Ran validator locally with `./build_and_redeploy.sh --port-forward --clean` with a test metric (v10 on Graphite has it)
2. Port forwarded the Prometheus UI `kubectl port-forward prometheus-linera-core-kube-prometheu-prometheus-0 9090`
3. Went to http://127.0.0.1:9090/graph to see the metric properly logged:

Log proxy side metrics to Prometheus

---

linera-service/src/grpc_proxy.rs

Implementing proxy request count Counter metric
1. Ran validator locally with `./build_and_redeploy.sh --port-forward --clean`
2. Built the binaries with `cargo build --features benchmark`
3. Ran a benchmark against it with `./linera benchmark`
4. Port forwarded the Prometheus UI `kubectl port-forward prometheus-linera-core-kube-prometheu-prometheus-0 9090`
5. Went to http://127.0.0.1:9090/graph to see the metric properly logged:

Log proxy request count

---

linera-service/src/database_tool.rs
linera-views/src/common.rs

The three entries `max_concurrent_queries`, `max_stream_queries` and `cache_size` were not used for the `linera_db` tool. So it is better to remove them.
* Simplify the input 
* Implement a `Default` for the `CommonStoreConfig`.
The CI should do as needed.

Simplify the input for `linera_db`.

---

linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-chain/src/test.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/committee.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/policy.rs
linera-execution/src/pricing.rs
linera-execution/src/runtime.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/config.rs
linera-service/src/linera.rs
linera-views/src/batch.rs
linera-views/src/key_value_store_view.rs

We need to implement the storage fees for the linera-protocol. This version implements it in a rather straightforward way. We are counting the number of reads and writes, not the total data used.
* The `pricing.rs` module is significantly extended to separate writes from reads.
* The `remaining_fuel` is replaced by a `runtime_meter` that accounts for all the operation being done.
* As opposed to what we initially planned, all the computation is done in `runtime.rs`.
* As discussed beforehand, we also added limits and those limits are part of the `pricing.rs` code.
CI so far, needs to extend.
- Release is blocked and/or …

Implement storage fees and limits

---

linera-service/src/chain_listener.rs
linera-service/src/config.rs
linera-service/src/linera.rs

* Avoid generating fake-key pairs in the case of `linera wallet init --with-other-chains ID`
* Better support unowned chains in the wallet
* Be consistent in listening to all of them
* Introduce `UserChain::make_other`
* Make sure to handle failures of `process_inbox` in the chain listener
* Listen to all chains in the wallet (we will refine later)
CI

Listen to all the chains in the wallet

---

.dockerignore
docker/Dockerfile.copy
kubernetes/linera-validator/build_and_redeploy.sh

Development cycles are slow when deploying a local cluster because of how slow the Docker build is, which also slows down CI.
Let's have an option to build locally the binaries (outside of Docker) then just copy them over to build the image. This should speed up development cycles for people using Linux. AFAIK there are no Apple M1 Silicon Docker images that we could use, so people not using Linux (me) are out of luck on this.
This will be triggered in the following PR by CI, which we'll use as a test for this (I can't test it locally because I don't have a Linux machine)

Copy existing binaries to Docker image

---

.github/workflows/kubernetes.yml

CI is slow
Now we can copy over binaries instead of building them inside Docker, which should be faster. So let's do that.
The Kubernetes CI test used to take 15+ minutes, on this PR it took 6 minutes. So hopefully this will ease a bit our GitHub CI costs

Change Kubernetes CI to copy existing binaries

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/src/faucet.rs
linera-service/src/lib.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs

For Devnet new users should be able to start using the network by just requesting a new user chain with some tokens from a faucet.
Add a `linera faucet` command that works like `linera service` except its only query is a `claim` mutation that creates a new chain for a given public key, and adds some tokens to it.
Rate limiting will be added in a separate PR.
An end-to-end test that verifies that a new chain has been created and credited.

Add linera faucet command.

---

linera-execution/src/wasm/runtime_actor/mod.rs
linera-execution/src/wasm/runtime_actor/tests.rs
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs

Sending a request to a `RuntimeActor` was expected to never fail, and would panic if that ever happened. Unfortunately, that can happen for example in tests, because if the test fails while the actor is still running tear-down will start and ends up dropping the `RuntimeActor`, potentially before stopping the Wasm guest thread. This means that the Wasm guest could attempt to call a system API from the runtime actor even though it had already stopped.
Don't panic when sending a message to the runtime actor fails. Return an error instead, and handle it gracefully by stopping the Wasm guest's execution.
This PR also contains a few minor fixes to how fuel configuration errors are logged. The effect is that a `debug` log message was missing for when Wasmtime failed to read the fuel, and a log …

Dont panic if the `RuntimeActor` stops

---

linera-execution/src/wasm/runtime_actor/mod.rs

PR #1148 introduced a `RuntimeActor` type, but it's inner loop's functionality was hard to understand.
Simplify the second loop used to wait for the handlers to finish, and document every step of the `run` function.
Functionality is unchanged.
Nothing is needed.

Improve clarity of `RuntimeActor` code

---

linera-chain/src/chain.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/system.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/faucet.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

The faucet currently creates two blocks for each user: One to create their chain and then one to transfer their initial balance.
And in general, a chain without any balance can't be used for anything, so the command-line and GraphQL commands for opening a chain will usually be followed by a transfer as well.
Add a `balance` field to the `OpenChain` operation and message itself, so the parent chain can send an initial amount of tokens along that is credited to the child from the start.
The faucet test now exercises this.

Add initial balance to OpenChain.

---

kubernetes/linera-validator/build_and_redeploy.sh

We might want to standardize formatting for these scripts. I use `shell-format` for shell scripts, Dockerfile, gitignore, etc
Formatting `build_and_redeploy.sh` with it
CI

Running formatter on build_and_redeploy

---

kubernetes/linera-validator/build_and_redeploy.sh

There was a bug in the `${copy+--build-arg binaries=target/release}` line I missed during review. From my understanding, like this if `copy` is set at all, even just `copy=`, it'll still trigger the substitution. Which means this will always trigger the copy code path.
Another thing was that `uname -m` on the mac returns `arm64`, and we're actually looking for `aarch64`.
Also, if `docker build` fails, we should fail the script.
For the first issue, changing to use `${copy:+--build-arg binaries=target/release}` instead. In this case, only if `copy` is actually set to something the substitution will be triggered.
For the second issue, changed that portion of the code back closer to what it used to be.
For the third one, fail the script if `docker build` fails.
Tested the different …

Some fixes on build_and_redeploy

---

linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

For devnet and testnet, clients need an easy way to initialize their wallet with a new chain and some tokens from the faucet.
Add a `--faucet` argument to the `wallet init` command. If a URL is specified, it will claim tokens from the faucet service at that URL.
The faucet end-to-end test has been extended.

Add --faucet argument to wallet init command.

---

.cargo/config.toml
Cargo.lock
Cargo.toml
docker/Dockerfile
linera-explorer/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-service-graphql-client/Cargo.toml

Right now with `openssl` cross compiling is a very difficult task
Using `rustls` instead to make that easier
To cross compile:
1. Make sure you have the target you want installed: `rustup target add aarch64-unknown-linux-gnu`
2. Install a cross-compilation toolchain that includes a compiler and associated linker for the target you're trying to build. On MacOS, you can do: `brew install aarch64-linux-gnu`
3. Compile project: `cargo build --target aarch64-unknown-linux-gnu --release`

Use rustls instead of openssl

---

kubernetes/linera-validator/build_and_redeploy.sh
test-cloudbuild-local.yaml

Since the recent Dockerfile changes, cloud build has been broken
Seems like GCP was using an older version of Docker for the cloud builds, that was triggering some bug where the `builder_copy` stage was being triggered everytime, regardless of the arguments. Forcing an up to date version of Docker to be used fixes that bug. Also, `COPY --chmod` requires `BuildKit`, so just doing separate commands as installing `BuildKit` on GCP seems non-trivial.
Ran `./build_and_redeploy.sh --port-forward --clean --cloud`, saw everything work as intended

Fix Cloud builds

---

kubernetes/linera-validator/values-local-with-cloud-build.yaml

When trying to `helm install` with an image that was built with cloud build, it was failing
Mimick `values` for local runs instead of GCP runs
`./build_and_redeploy.sh --port-forward --clean --cloud`, saw everything build and be deployed locally correctly

Fix helm install when running Cloud built image locally

---

linera-service/src/config.rs
linera-service/src/linera.rs

There's no need for root chains to be initialized with different timestamps.
They also all have a `ChainDescription::Root(_)` description, as none of them are children.
Move the `timestamp` field out of the `chains` field: There's only one, for all chains.
Replace the chain description with a `u32`: the _root_ chain number.
There were no significant changes in the business logic.

Simplify GenesisConfig.

---

linera-service/src/faucet.rs

We would like the Faucet to accept incoming external connections.
Change the server IP from 127.0.0.1 to 0.0.0.0.
CI.

Faucet listens for connections of 0.0.0.0 instead of 127.0.0.1

---

.github/workflows/rust.yml
linera-core/src/notifier.rs
linera-explorer/src/lib.rs
linera-indexer/lib/src/indexer.rs
linera-service-graphql-client/src/utils.rs
linera-views/src/dynamo_db.rs
rust-toolchain.toml

I was working on updating GraphQL and I ran into an internal compiler error:
```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: Canonical { value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [Binder { value: OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 0, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(None) })), bound_vars: [] }, Binder { value: OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 2, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(1), BoundRegion { var: 1, kind: BrAnon(None) })), bound_vars: [] }, Binder { value: OutlivesPredicate(ReLateBound(DebruijnIndex(1), BoundRegion { var: 3, kind: BrAnon(None) }), ReLateBound(DebruijnIndex(1), BoundRegion { …
```

`rust-toolchain.toml`: bump Rust to latest stable (1.73)

---

linera-views/src/common.rs
linera-views/src/log_view.rs
linera-views/src/queue_view.rs
linera-views/src/register_view.rs

The `from_bytes_opt` is doing some `clone()` operations which can actually be removed.
Implement the simplification
The CI.

Simplify the `from_bytes_opt`.

---

linera-core/src/client.rs
linera-service/src/faucet.rs
linera-service/src/linera.rs
linera-service/src/unit_tests/faucet.rs

A faucet shouldn't give away tokens as quickly as it can serve requests, otherwise someone could quickly claim all of them and empty the faucet.
Add an `--end-timestamp` parameter to `faucet`. The tokens are then released at a constant rate, so that they don't run out before the specified time.
A client test was added to check the rate limiting logic.

Add --limit-rate-until to faucet command.

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/wasm-tests/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml
linera-witty/test-modules/Cargo.toml

The update in validator configuration files with the addition of optional TLS for GRPC connections introduced breaking changes.
Bump the minor version.
CI
@ma2bd to release on `crates.io` after it's been merged into `main`.

Bumped versions to 0.6.0

---

examples/fungible/src/lib.rs
linera-base/src/crypto.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-execution/src/system.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-explorer/src/entrypoint.rs
linera-explorer/src/lib.rs
linera-rpc/src/config.rs
linera-sdk/src/bin/linera-wasm-test-runner/main.rs
linera-sdk/src/contract/system_api/private.rs
linera-sdk/src/test/integration/chain.rs
linera-service-graphql-client/src/service.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-views/src/memory.rs
linera-views/tests/operations_tests.rs
linera-witty-macros/src/wit_import.rs
scripts/check_copyright_header/src/main.rs

The types annotation is something that we want to avoid. In particular for the `collect()` it was put because it was needed. Except that it is not. This PR cleans up that art of the code.
Straightforward given the stated contraints
CI

Clean types in `collect()` statements.

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/chain_listener.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs
linera-service/tests/end_to_end_tests.rs

After unsuccessfully proposing a valid fast block, it is not safe to propose a different block at the same height anymore.
Currently, we don't store the proposed block in the wallet, and there is no command to retry it.
Store the pending block in the wallet, and add a `retry-pending-block` command that will send it to the validators again.
For this to work, all the commands that involve block proposals need to save the wallet even if they fail.
An end-to-end test was added, where a block proposal fails and is retried.

Save pending block in wallet; add retry command.

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/src/faucet.rs
linera-service/src/linera.rs

We want to make joining the devnet and testnet as convenient as possible, so the only data needed to join should be the address of the faucet.
Add a `genesisConfig` endpoint to the faucet, and allow `wallet init` to get it from there.
The faucet end-to-end test uses this now.
- Need to document this for devnet.
- Closes #1245.

Let faucet provide the genesis config.

---

linera-chain/src/data_types.rs
linera-service/src/config.rs
linera-service/src/linera.rs

The faucet, or even the genesis validators, after a while, shouldn't be considered to be trusted. (No single entity should be, and _former_ validators shouldn't be either.)
Verify that the new chain was actually created and assigned to the user.
Print a warning with instructions for the user to verify the downloaded data
The faucet end-to-end test exercises this code.
It's not clear that the added code and CI costs are worth having tests feeding a client different kinds of garbage data.

Verify data after initializing the wallet.

---

linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/runtime_actor/handlers.rs
linera-execution/src/wasm/runtime_actor/mod.rs
linera-execution/src/wasm/runtime_actor/requests.rs
linera-execution/src/wasm/runtime_actor/sync_response.rs
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
linera-sdk/src/views/system_api.rs
linera-sdk/view_system_api.wit

It is currently possible to achieve non-deterministic execution of contracts by causing data races when reading and writing to storage. This is undesirable because it would mean certificates could be rejected because some of their transactions execute differently on different validators.
Use a `RwLock` from [`async-lock`](https://docs.rs/async-lock/latest/async_lock/struct.RwLock.html) to prevent data races when accessing the contract system API runtime.
However, since the lock is write-preferring, it's also necessary to ensure there is never an attempt to acquire the write lock more than once at any given moment. To achieve this, all system APIs that acquire a write lock need to be blocking (synchronous). To help enforce this new rule, those system APIs were changed to use a new …

Use a `RwLock` over the contract system runtime to prevent data races

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-views-derive/src/lib.rs
linera-witty-macros/src/util.rs
linera-witty-macros/src/wit_export/function_information.rs
linera-witty-macros/src/wit_import.rs

`syn` has released a new major version.  The upgrade isn't particularly painful, and it allows us to use crates that depend on the newer `syn` (such as `prettyplease` for prettifying code, e.g. for https://github.com/linera-io/linera-protocol/pull/1237#discussion_r1395301520).
Upgrade `syn` to 2.0.39.
Build and run CI tests.
This change should be invisible to consumers.
- https://github.com/linera-io/linera-protocol/pull/1237

Upgrade `syn` to v2

---

.github/workflows/documentation.yml
.github/workflows/dynamodb.yml
.github/workflows/explorer.yml
.github/workflows/kubernetes.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml

When a test deadlocks, this currently costs 360 minutes of a 16-core machine.
* Add timeouts for test jobs
* Reduce the number of cores for certain jobs
Note that the default `ubuntu-latest` has 2 cores and is free for opensource projects (up to a limit).
Otherwise, github charges per minute per core.
CI

CI: add timeouts and reduce CPU costs

---

.github/workflows/rust.yml
flake.lock
flake.nix
rust-toolchain.toml
toolchains/build/rust-toolchain.toml
toolchains/lint/rust-toolchain.toml

It is unfortunate that our linting toolchain is only specified in the GitHub actions, as this requires local developers to keep their local nightly updated to match that file.
This PR moves the specification of our linting toolchain out of the GitHub actions into a dedicated toolchain file.  Different toolchains are stored in `toolchains/{name}/rust-toolchain.toml`, which should make it possible to select between them in CI by running the action from that directory.  Eventually this will no longer be necessary, as `rustup` [is planning to add support for multiple toolchain files](https://github.com/rust-lang/rustup/issues/2686).
We also add a new `devShell` to the Nix flake that references the linting toolchain file, allowing `nix develop .#lint` to drop the developer into a shell …

Codify linting toolchain

---

linera-service/src/config.rs
linera-service/src/linera.rs

We want to identify and distinguish different networks, like devnet vs. testnet vs. mainnet.
Add a network name to the genesis config.
This is not being used for anything yet.

Add a network name to the genesis config.

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/runtime_actor/handlers.rs
linera-execution/src/wasm/runtime_actor/requests.rs
linera-execution/src/wasm/system_api.rs
linera-execution/tests/test_execution.rs
linera-sdk/mock_system_api.wit
linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
linera-sdk/src/test/unit/mod.rs
linera-sdk/src/views/system_api.rs
linera-sdk/view_system_api.wit
linera-storage/src/lib.rs
linera-views/src/collection_view.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/hashable_wrapper.rs
linera-views/src/key_value_store_view.rs
linera-views/src/log_view.rs
linera-views/src/lru_caching.rs
linera-views/src/map_view.rs
linera-views/src/memory.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/register_view.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/set_view.rs
linera-views/src/value_splitting.rs
linera-views/src/views.rs
linera-views/tests/operations_tests.rs

We need to handle the maximal key size in a cleaner way. So, we had to 
The feature took much trouble to implement and the solution was the following:
* For ScyllaDb, we declare the limit to be 1M while the total size is actually 16M for a transaction.
* We cannot have a hard constant because for the `KeyValueStoreClient` it depends on the size of the `base_key`.
* For the system_api, we need to have a constant that is not dependent on the underlying storage.
* In the end we should have size problem before accessing to the database.
The CI should take care of it.
There is nothing specific about the PR that impacts the release.

Implement a `max_key_size()`

---

linera-chain/src/lib.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/resources.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/wasm.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/lib.rs
linera-storage/src/memory.rs
linera-storage/src/rocks_db.rs
linera-storage/src/scylla_db.rs

* Code cleanups
* Validators shouldn't have to load Wasm services
* split UserApplication trait into UserContract + UserService
* split WasmApplication trait into WasmContract and WasmService
* remove Arc in ExecutionRuntime
* minor code improvements
CI

Split WasmApplication into WasmContract and WasmService

---

Cargo.lock
Cargo.toml
docker/Dockerfile
linera-service/Cargo.toml
linera-service/src/cli_wrappers/docker.rs
linera-service/src/cli_wrappers/helm.rs
linera-service/src/cli_wrappers/kind.rs
linera-service/src/cli_wrappers/kubectl.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/util.rs
linera-service/src/linera.rs
linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

We want to replace `build_and_redeploy`, and also set things up to run end to end tests agaist a locally running Kubernetes cluster.
This is an initial version. We don't have number of validators or numbers of shards being respected in this version, this will be done in a follow up PR.
Ran it:
Then ran `sync-balance` against it, and it succeeded.

linera net up --kubernetes initial version

---

kubernetes/linera-validator/build_and_redeploy.sh

Having the exports prints are still useful, because we have `linera net up` and `build_and_redeploy`, which tell you to point to different wallets and storage.
So if you use `linera net up`, then go back to using `build_and_redeploy`, and you don't know you have to export the `/tmp` wallet and storage, connection to your validator will fail, and if you don't know this you'll be confused :)
Having prometheus info is useful and we should've added a while back.
Add the proposed prints
Run `build_and_redeploy`, saw the prints

Print more useful info on build_and_redeploy

---

linera-service/src/chain_listener.rs

The `end_to_end_queries` test would sometimes hang due to a deadlock.
Two locks are shared between the `NodeService` and the `ChainListener`, one for a chain client and one for the `ClientContext`. In most places, the chain client lock is acquired before the context lock. However, there was one place where the context lock was acquired before the chain client lock.
Always acquire the chain client lock before the context lock.

Fix deadlock in `ChainListener`

---

linera-explorer/src/entrypoint.rs
linera-explorer/src/graphql.rs
linera-explorer/src/lib.rs
linera-indexer/example/tests/test.rs
linera-indexer/lib/src/service.rs
linera-service-graphql-client/tests/test.rs
linera-service/src/cli_wrappers/wallet.rs

Asynchronous `reqwest::Client` do not have timeouts be default resulting in tests which can hang indefinitely.
Add a timeout of 30 seconds to all `reqwest::Client`.

Add timeouts for reqwest clients

---

.github/workflows/rust.yml
flake.lock
flake.nix
linera-core/src/data_types.rs
linera-explorer/src/lib.rs
linera-views-derive/src/lib.rs
linera-views/src/queue_view.rs
linera-views/tests/views_tests.rs
toolchains/build/rust-toolchain.toml
toolchains/lint/rust-toolchain.toml

Re-implement https://github.com/linera-io/linera-protocol/pull/1251 without using `working-directory`, which is apparently forbidden in combination with `uses`.

Codify lint toolchain, Mk.II

---

kubernetes/linera-validator/build_and_redeploy.sh
linera-service/src/cli_wrappers/helm.rs

With the new init container for ScyllaDB, sometimes we're exceeding the default 5m timeout
Increase the timeout to 10m to make sure we always succeed in initializing the clusters
Ran locally, was gonna fail, but didn't with the increased timeout

Increase Helm Install timeout to 10m

---

linera-views/src/key_value_store_view.rs
linera-views/src/map_view.rs

The work on the stored_size revealed some underlying problems with the `MapView` and `KeyValueStoreView`.
The following was done: the resolution of the bug.
No further work was done because the important is first to get some correct code, but several more issues need to be addressed in subsequent works:
* Use of the trie data structure would be needed to get faster runtime.
* Getting the store implemented.
* Stronger test infrastructure for detecting such problems (but that should be in the store PR.
No improvement to tests was done but should be in subsequent PR.
No relevant entries for release are needed.

Resolution of two bugs in the MapView and KeyValueStoreView.

---

linera-indexer/example/tests/test.rs
linera-service-graphql-client/tests/test.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs

Right now, if something goes wrong when initializing the cluster, those kind clusters created will just linger there, as well as everything else
Let's make sure that if there's an error, we'll clean things up properly
In the case of failure, we're now cleaning things up: https://gist.github.com/andresilva91/1f180b5e38480652cc96f25f9a623254

Properly cleanup if something fails on linera net up --kubernetes

---

linera-views/src/key_value_store_view.rs
linera-views/src/map_view.rs
linera-views/src/set_view.rs
linera-views/tests/key_value_store_view.rs
linera-views/tests/map_view_tests.rs
linera-views/tests/views_tests.rs

For the purpose of storage fees, we need to keep track of the total size stored.
This PR should address #1263.
The following decision were done:
* The key size and the value sizes are tracked separately. However, instead of having this tracked separately, we track a pair (u64,u64) along.
* The tests for `MapView` were reinforced in view of the detected problems that led to PR #1284.
* Random checks were implemented for `KeyValueStoreView` that led to the detection of aforementioned bugs.
* Instead of reinventing the wheel, the `ByteMapView` was used.
* The `insert`, `remove` and `remove_by_prefix` functions are left. However, they are calling the `write_batch`and so become `async`. But it was better to keep the functionality.
* Change the `get` functions in `ByteMapView` and …

Implement the support of `stored_size` for `KeyValueStoreView`.

---

linera-core/src/client.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/updater.rs
linera-rpc/src/client.rs
linera-rpc/src/grpc_network.rs
linera-rpc/src/node_provider.rs
linera-rpc/src/simple_network.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera.rs
linera-service/src/schema_export.rs

Continue simplify the client code after #1220 and #1283
* Define enum `CrossChainMessageDelivery` to allow forcing `wait_for_outgoing_messages = true` for individual certificate uploads
* Use it when needed, notably when uploading certificates corresponding to received messages
CI
Some CLI options are removed

Remove retry loops when sending certificates

---

linera-service/src/cli_wrappers/docker.rs
linera-service/src/cli_wrappers/helm.rs
linera-service/src/cli_wrappers/kind.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs

It was brought to my attention that we could further parallelize the cluster initialization
Parallelizing the for loop that we use to do `helm install` and other parts of the initialization
Ran with multiple validators, starting them up is much faster!
https://gist.github.com/andresilva91/252f77f08ec93b564c05bae4dfb1d3b7

Parallelize cluster initialization

---

docker/server-init.sh
kubernetes/linera-validator/templates/server.yaml

Right now when we're trying to initialize the shards, we check for ScyllaDB and just fail if it's not ready. That makes Kubernetes go into a `CrashLoopBackoff`, which is an exponential backoff, which will make us wait much more than we need.
Change the script to wait for the initialization instead of failing
Started clusters locally, a few seconds after ScyllaDB is `Running`, the shards also start being initialized. Initialization felt a lot faster

Wait for Scylladb initialization instead of failing

---

linera-sdk/src/test/integration/chain.rs

GraphQL errors in tests are currently not surfaced, and as a result `Null` is returned when something goes wrong with no indication as to what happened.
Panic if the response from the GraphQL query includes errors, making sure to include the errors and the offending query in the output.
CI.
This affects only tests, so no version bump is required.

`linera-sdk`: surface GraphQL errors in failure output

---

linera-views/src/collection_view.rs
linera-views/src/key_value_store_view.rs
linera-views/src/log_view.rs
linera-views/src/map_view.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/set_view.rs
linera-views/src/views.rs

The merging of the PR #1287 was actually done a little bit prematurely, so this PR actually
do after merge corrections.
* Add documentation for the subtle `|| self.was_cleared` for the `total_size`.
* Do the same trick for the hash.
* Replace the `ByteMapView<SizeData>` by `ByteMapView<u32>` which takes less space.
* Add the check of overflow for the `add_assign`.
The CI does it.
That should not change anything.

Improvement to the `stored_size` code.

---

linera-chain/src/chain.rs
linera-execution/src/policy.rs
linera-execution/src/resources.rs
linera-execution/src/runtime.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/linera.rs
linera-views/src/key_value_store_view.rs
linera-views/src/views.rs

In the storage fees, we want to take into account the total used size by the smart contract. This PR implements that and addresses the issue #1228 
The name used is `storage_bytes_stored` which is fairly self-explanatory. The implementation is done via the implemented features in `KeyValueStoreView`. 
The CI does it.
No impact right now, but we would like of course to test it.

Implement the total stored size in storage fees

---

linera-witty-macros/src/lib.rs

PR #1294 added support for a new `#[witty_specialize_with]` attribute that generates code for generic types with some predefined specializations. However, using the attribute did not work because the compiler complained of an unrecognized attribute.
Unfortunately the tests didn't capture the error because the tests did not run the procedural macro directly, running only the internal implementation instead (skipping the compiler).
Properly register the attribute so that it can be used in real-world scenarios.

Register `#[witty_specialize_with]` attribute

---

configuration/k8s-local/validator_1.toml

This was a bug that we found while trying to run e2e tests with Kubernetes. This will break notifications when we deploy things with anything that uses this config, like `build_and_redeploy` for example
Fix the config
Run and make sure notifications work

Fix k8s-local config hosts

---

linera-views/src/common.rs
linera-views/src/key_value_store_view.rs
linera-views/src/map_view.rs

While implementing the `delete=clear+save` we saw a number of problems. Here are the ones for prefixes
Two bugs were addressed:
* One when we insert a prefix bug it is already matched by existing prefixes.
* One in `MapView` where a prefix has been deleted and the `for_each_key_*` is used for the same prefix. Then we need to remove the prefix from consideration.
The CI and a better check.
None.

Address two bugs with the handling of prefixes

---

linera-witty-macros/src/util/specialization.rs
linera-witty/src/runtime/test.rs
linera-witty/tests/common/types.rs
linera-witty/tests/wit_load.rs
linera-witty/tests/wit_store.rs
linera-witty/tests/wit_type.rs

PR #1294 allowed specializing generic types before deriving Witty traits, and while writing some tests for #1318 I realized that there was a bug in supporting specialization of types inside tuples. Tuples were simply not specialized.
Specialize tuple types.
Adds some unit tests that cover both #1318 and this fix.

Fix Witty specialization inside tuple types

---

linera-service/src/cli_wrappers/docker.rs
linera-service/src/cli_wrappers/helm.rs
linera-service/src/cli_wrappers/kind.rs
linera-service/src/cli_wrappers/kubectl.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/util.rs

We don't always need the output. Also, for `kind delete` that gets called on drop, we shouldn't mess with stdout/stderr at all, because it can hang waiting on a buffer flush that never happens, because the tokio runtime is already shutting down.
Call more suitable methods
Tested running e2e tests with Kubernetes

Use more suitable tokio Command functions

---

kubernetes/linera-validator/build_and_redeploy.sh

Right now `--copy` won't work for mac users, because it'll need to copy binaries from a cross compiled directory, which is currently not supported
Support specifying which directory to copy the binaries from
Ran `./build_and_redeployh --port-forward --clean --copy-bins-dir target/aarch64-unknown-linux-gnu/release --copy` to test, saw that everything works as expected

Enable --copy for mac users on build_and_redeploy

---

linera-execution/src/runtime.rs
linera-views-derive/src/lib.rs
linera-views/src/reentrant_collection_view.rs

Adds a local `ReadGuardedView` and `WriteGuardedView` for `ReentrantCollectionView` to parallel that of `CollectionView`.
This is currently just an `async_lock::RwLock{Read,Write}GuardArc` inside, but rather than expose that foreign type, this change lets us expose only our own types — and, importantly, implement traits on them.
https://github.com/linera-io/linera-protocol/pull/1280 requires implementing `async_graphql::OutputType` for our lock types.  Unfortunately, since the locks are remote types, we can't implement traits on them.
In non-reëntrant collections, types `ReadGuardedView` and `WriteGuardedView` already exist.  This PR extends that to the reëntrant case by adding parallel `Read`- and `WriteGuardedView` types for `CollectionView`.
CI is sufficient.
This PR changes the API of …

`linera-views`: Add local guard newtypes

---

.github/workflows/kubernetes.yml
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

We need to pass all e2e and wasm e2e tests with the local Kubernetes deployment
They all pass, but right now is not feasible to have all tests creating one cluster each in parallel in CI, so doing just one test of each for now
Run the tests against the local Kubernetes deployment, they pass

Pass one e2e and one wasm e2e test with Kubernetes

---

linera-chain/src/manager.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/worker_tests.rs

The `ChainManagerInfo` is large, and makes stack overflows more likely. Changes like https://github.com/linera-io/linera-protocol/pull/1305 trigger them in some scenarios.
~Also, some people were seeing compiler panics with Rust 1.73.0.~
Box some fields in `ChainManagerInfo` ~and upgrade Rust to version 1.74.0~.

Box chain manager info fields

---

kubernetes/linera-validator/templates/ingress.yaml
kubernetes/linera-validator/templates/proxy.yaml

The GKE Ingress was killing connections after the 30 second default. 
This meant that idle notification streams were being killed and had to be re-established.
Set the idle connection timeout to the largest possible value. 
This is a temporary measure. Longer term we may want to implement a health-check or heartbeat protocol to keep idle connection alive instead.

Increased ingress connection timeouts

---

linera-sdk/src/views/system_api.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lru_caching.rs
linera-views/src/memory.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/value_splitting.rs
linera-views/tests/store_tests.rs

Sometimes we want to test the existence of a key without downloading the full value.
* The `KeyValueStore` trait was extended appropriately.
* For `DynamoDb` and `ScyllaDb` some code directly using the facility of the database was coded. This was not possible for `RocksDb`.
* For `ValueSplitting` that was straightforward to do and immediately gain.
* For `LruCaching` we use the cache for the key/value but we could conceivably have added code for the caching of the test existence.
* For `AppStore` we have not yet coded the passing of those tests and instead use the read.
So, there is possibility of further PR depending on the outcome of the discussion here.
The CI was extended appropriately.
The manual might have to be changed.
- [reviewer …

Support directly testing the existence of keys without downloading the key.

---

examples/amm/src/contract.rs
examples/amm/src/lib.rs
examples/crowd-funding/README.md
examples/crowd-funding/src/contract.rs
examples/crowd-funding/src/lib.rs
examples/fungible/README.md
examples/fungible/src/contract.rs
examples/fungible/src/lib.rs
examples/fungible/tests/cross_chain.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-service-graphql-client/tests/test.rs
linera-service/tests/wasm_end_to_end_tests.rs

It's difficult to recognize fungible tokens based on their application ID.
Add a "ticker symbol" parameter.
The READMEs were updated, and I tried running them even with an added temporary assertion in the fungible `initialize` implementation. (No need to commit that assertion, because https://github.com/linera-io/linera-protocol/issues/1332 will do that for all apps.)

Add a ticker symbol to the fungible example.

---

examples/fungible/web-frontend/src/App.js

My update to the `fungible` Web frontend in #1280 was incorrect.  This fixes it so that balance can once again be displayed.
Update the query and result-handling code to correctly get the balance using the new GraphQL entry API.
Open the `fungible` front-end according to the `README` and look at the balance.
This is a bugfix.
- PR that introduced the bug: https://github.com/linera-io/linera-protocol/pulls/1280

`fungible`: fix web frontend for new GraphQL API

---

linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/runtime_actor/handlers.rs
linera-execution/src/runtime_actor/mod.rs
linera-execution/src/runtime_actor/senders.rs
linera-execution/src/runtime_actor/tests.rs
linera-execution/src/wasm/common.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-execution/tests/test_execution.rs

Next step after #1351 in order to run contracts on a single thread (https://github.com/linera-io/linera-protocol/issues/1193)
* Create an abstract interface that hides the actor channel.
* Remove the previous trait (now an internal interface)
We stop short of making the `UserContract` and `UserService` traits generic w.r.t. an implementation of the new interface (i.e. using a generic type to replace `{Contract,Service}RuntimeSender`). This is not blocking me right now and can be done later if needed.
CI

Create new runtime interface for the contract execution thread

---

linera-execution/src/execution.rs
linera-execution/src/runtime.rs
linera-execution/tests/test_execution.rs

It's currently possible to cause a `panic` inside validator shards by returning custom errors from applications. This happens because an assertion is triggered due to a bug introduced recently. The bug happens because the runtime application call stack is not updated when ignoring user errors.
Always update the application call stack before checking for errors.
A unit test was added for the scenario where an application returns a custom user error. Execution should finish successfully.
Closes #1344

Fix panic on user application errors

---

flake.lock
flake.nix

The Rust version from #1353 isn't available in our locked Nix build environment.
Atop #1353, upgrade the Nix lock to a newer version of `rust-overlay` that has the new Rust version.
CI.

Nix update

---

build-image.yaml

We want to keep the infra related stuff outside this repo
Moving `build-image.yaml` to `linera-infra`
Will test in the `linera-infra` PR

Moving build-image.yaml to linera-infra

---

flake.nix

`librocksdb-sys` is very slow to build because it builds `rocksdb` from source.  This [used to be necessary](https://github.com/jsgf/rocksdb-sys) due to an allocator mismatch, but [newer `rocksdb`](https://github.com/rust-rocksdb/rust-rocksdb) no longer mentions it, and seems to work fine without any special handling.
Pull in `rocksdb` as a build dependency in our Nix environment, and set an environment variable `ROCKSDB_LIB_DIR` that instructs `librocksdb-sys` on where to find it.
This won't help people building without Nix, but serves as a template for them to set up their own manual solutions (e.g. by imperatively `apt-get install`ing `rocksdb` and either adding `export ROCKSDB_LIB_DIR=/usr/lib` to `~/.bashrc` or similar or adding it to your project [`direnv`](https://direnv.net/) …

`flake.nix`: use a prebuilt `rocksdb` to speed compilation

---

linera-service/src/cli_wrappers/local_net.rs

Running `LINERA_SERVER_PARAMS="--tokio-threads=1"` currently fails because the argument is appended to the end of the command line, and that means it ends up included in the arguments of the sub-command instead of being part of the global arguments.
Append the `LINERA_SERVER_PARAMS` before the sub-command, so that it's not included in the sub-command's arguments.
Tested manually by running the end-to-end tests with the `LINERA_SERVER_PARAMS="--tokio-threads=1"` and adding a `panic!("{:?}", options.tokio_threads);` line to `server.rs`'s `main`.

Append environment arguments before the sub-command arguments

---

Cargo.lock
Cargo.toml
examples/amm/src/contract.rs
examples/counter/src/contract.rs
examples/crowd-funding/src/contract.rs
examples/fungible/src/contract.rs
examples/matching-engine/src/contract.rs
examples/meta-counter/src/contract.rs
examples/reentrant-counter/src/contract.rs
examples/social/src/contract.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-sdk/src/test/integration/mock_stubs.rs
linera-sdk/src/test/unit/mod.rs
linera-sdk/wasm-tests/Cargo.toml
linera-sdk/wasm-tests/src/lib.rs

Ensure all examples validate their parameters inside `initialize`, to prevent an application to be created with parameters that can't be deserialized.
This is supposed to be a new recommendation for developers, so the examples should show it as a best practice.
It's currently possible to create an application that is bricked because its parameters are invalid and can't be deserialized.
Create the best practice of validating the application parameters inside the contract's `initialize` method. This ensures that the application creation fails if the parameters are invalid.
All examples were updated to include this new best practice.
The Counter unit tests were updated to configure the mock application parameters. A unit test for the failure scenario could not be written, because it would …

Validate application parameters inside `initialize` of every example

---

linera-service/tests/wasm_end_to_end_tests.rs

The matching engine end-to-end test now fails because of an invalid GraphQL query, _in addition_ to https://github.com/linera-io/linera-protocol/issues/1159.
Fix the GraphQL query.
The test is `#[ignore]`d, but increasing the timeouts as described in https://github.com/linera-io/linera-protocol/issues/1159, together with this fix, makes it pass for me again.
- https://github.com/linera-io/linera-protocol/issues/1159

Fix MatchingEngineApp::get_account_info.

---

linera-core/src/worker.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

The original motivation for the `contains_key` was to have a more efficient `check_no_missing_bytecode`. This PR addresses it.
The name of the new functionality is perhaps controversial. I called it `contains_hash`.
The CI.
No change.

Introduce `contains_hash` for the `Storage`

---

linera-core/src/node.rs
linera-execution/src/committee.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/faucet.rs
linera-service/src/linera.rs

The genesis config is not enough for a client to join the network in general: The current validators could be different and the genesis validators already offline.
Add a `currentValidators` endpoint.
The faucet end-to-end test tests this: `wallet init` now requests the current list of validators.
- Closes https://github.com/linera-io/linera-protocol/issues/1361.

Add a faucet endpoint to return the current list of validators.

---

linera-core/src/client.rs
linera-core/src/node.rs
linera-rpc/tests/staged/formats.yaml

`ChainClient::find_received_certificates` downloads all certificates received by the chain from every validator every time e.g. the `sync-balance` command is executed.
Look them up locally before downloading any certificates. Don't download what we already have.
I tried it out and it took less than 1 instead of 27 seconds to run `sync-balance`.

Speed up `find_received_certificates`.

---

linera-views/src/common.rs
linera-views/src/key_value_store_view.rs
linera-views/src/map_view.rs

The terminology `GreatestLowerBoundIterator` is not great and `SuffixClosedSetIterator` is a better name.
We did that renaming and also renamed `is_index_absent` into `contains_key`.
The CI.
Nothing changes.

Rename `GreatestLowerBoundIterator` to `SuffixClosedSetIterator`

---

linera-base/src/lib.rs
linera-base/src/sync.rs

See if we can avoid `std` instead of `once_cell` (which many people use but why not)
Implement `struct Lazy`
```
cargo test -p linera-base
```

Add linera_base::sync::Lazy

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

The implementation for the shared local kubernetes cluster will require us to lock a `futures::lock::Mutex` from inside `make_client`
Making `make_client` async here to avoid too many changes in one PR
CI

Make make_client async

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

Open chain can receive an initial balance parameter, but we're currently not using it
As we're gonna use this in the shared local kubernetes cluster wasm e2e tests PR, doing this change here so we don't have too many changes in one PR
CI

Add initial_balance parameter to open_and_assign

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/wallet.rs

For passing all wasm e2e tests with the shared local kubernetes, we need to have a higher initial funding when creating the genesis config
Implementing that missing functionality
CI

Add initial_funding parameter to create_genesis_config

---

.github/workflows/kubernetes.yml
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs

We need to share the same Kubernetes cluster when running the e2e tests, because the initialization time is too high and we would use a lot more resources in CI
Implemented a shared kubernetes cluster that replaces the existing testing one. Will try e2e tests next, and if they all pass I'll merge the two files in a following PR
CI

Pass all Wasm e2e tests with Shared Kubernetes cluster

---

linera-execution/src/lib.rs
linera-execution/src/runtime_actor/senders.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-execution/tests/test_execution.rs

Allow experimenting with alternative system runtime implementations
Add a type parameter to `UserContract` and `UserService`.
This was mostly uneventful. The only issue is that `write_batch` had to be moved to `BaseRuntime` otherwise we get a error due to the conflicting blanket implementations in `system_api.rs`. On the plus side, I removed the duplicated code there.
CI

Allow different system runtime implementations

---

linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/runtime_actor/handlers.rs
linera-execution/src/runtime_actor/mod.rs
linera-execution/src/runtime_actor/senders.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/wasm.rs
linera-storage/src/lib.rs

* #1393 made the Wasm code generic w.r.t. system runtimes but the global map of applications is still specialized.
* Eventually support reentrant calls
* Separate code (module) and contract instances.
* Use a factory trait `UserContractModule` to generate instances of each possible runtime (currently only one exists)
Adding system runtimes will involve patching the trait `UserContractModule` (in a trivial way). I think that's fine.
nits:
* Move some trait bounds to Wasm (this is needed to re-use the trait internally in runtime implementations)
* Rename legacy runtime senders
* Move runtime to contract objects, remove it from trait calls: this is what we want in the end for reentrancy. It turns out it was easy to do already and makes the code nicer. The Wasm code can probably be heavily …

Dynamic support for experimental runtimes

---

linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-rpc/src/conversions.rs

In https://github.com/linera-io/linera-protocol/pull/1305 the DynamoDB failed with a stack overflow again. The problem seems to be `ChainInfo`, which has a lot of fields.
`Box` `ChainInfo` in several method signatures, so it is on the heap instead of the stack.
No logic was changed, and it does fix the https://github.com/linera-io/linera-protocol/pull/1305 tests.
- Problem surfaced in https://github.com/linera-io/linera-protocol/pull/1305.

Box ChainInfo to prevent stack overflows.

---

examples/Cargo.lock
examples/matching-engine/Cargo.toml
examples/matching-engine/src/contract.rs
examples/matching-engine/src/lib.rs
examples/matching-engine/src/state.rs

The matching engine is currently using the Price type and a trick of reverting the price. We need that trick because the best ask price is the smallest one and the best bid price is the highest one.
That trick works but pollutes the output since the result of GraphQL which is unfortunate and makes the program difficult to use.
* The types `PriceAsk/PriceBid` are introduced with their own CustomSerialize implementations.
* This led to a simpler and more straightforward code for `contract.rs`.
The CI should address it. Unfortunately, the corresponding end-to-end test is currently ignored
and I could not make it work on my laptop.
More tests are added to the serialization to make sure it works.
No change.
- [reviewer …

Introduce `PriceAsk/PriceBid` for the matching engine.

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs

Currently any failure to execute `helm` or some other things in `LocalKubernetesNet::run` will be silently ignored, as the results of executing these operations are dropped, and a blanket `Ok(())` returned instead.
Don't drop the results; instead, collect them into the `Result` that is returned.
CI.
Bugfix.

`linera-service`: don't drop errors in `LocalKubernetesNet::run`

---

linera-witty/src/runtime/borrowed_instance.rs
linera-witty/src/runtime/test.rs
linera-witty/src/runtime/traits.rs
linera-witty/src/runtime/wasmer/mod.rs
linera-witty/src/runtime/wasmtime/mod.rs

PR #1310 added support for using custom user data when exporting host functions to guest Wasm modules. However, only a single getter was made available to access the data in a shared manner. Accessing the data using an exclusive mutable reference was possible behind the hood, but was unfortunately left out at the API level. There's no reason to not include it.
Add a `Instance::user_data_mut()` getter method to retrieve an exclusive mutable reference to the underlying data.
The new API will be covered later when `linera-execution` uses Witty.
Internal change, nothing needed.

Allow mutable access to custom user data

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/runtime.rs
linera-execution/src/system.rs
linera-execution/tests/test_execution.rs

Solve #989
* Remove failing messages repeatedly by staging execution in the client. This relies on previous PR #1029.
* Make system messages fallible
* Stop ignoring user errors during execution of Wasm applications
In the future, this could be made linear-time using additional features in `linera-views`.
CI + new unit test

Have client discard incoming messages that fail to execute

---

flake.nix

Allow running the Kubernetes tests locally in the Nix-specified development environment.
Add `kind` and `kubernetes` to the Nix flake.
Try to `linera net up --kubernetes` from within the development environment.
Minor patch.

`flake.nix`: add kind and Kubernetes

---

examples/matching-engine/src/contract.rs
examples/matching-engine/src/state.rs
examples/matching-engine/tests/transaction.rs
linera-service/tests/end_to_end_tests.rs

In a previous PR about the matching engine it was identified that the authentication was inadequate. In particular it was possible for anyone to cancel anyone orders. This PR addresses that.
* The authentication was done following the pattern of the `fungible` application.
* This led to some errors in the integration test that were corrected.
* This also led to some errors in the end-to-end test that were also corrected.
The CI should do the job. However, one proposal would be to enable again the test for `test_wasm_end_to_end_matching_engine` if only for `rocksdb`. This would likely detect some problems.
No relevant entries.

Correct the authentication of the matching engine application.

---

linera-service/tests/end_to_end_tests.rs

The matching engine end-to-end test is challenging for our system. However, it passes the `RocksDB` storage and so it should be enabled for it. That should help detect some issues.
Enable it.
The CI does it.
No change.

Enable the end-to-end test for the matching_engine.

---

linera-base/src/identifiers.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/policy.rs
linera-execution/src/resources.rs
linera-execution/src/runtime.rs
linera-execution/src/runtime_actor/handlers.rs
linera-execution/src/sync_runtime.rs
linera-execution/src/system.rs
linera-execution/src/wasm/mod.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-storage/src/db_storage.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/lib.rs
linera-storage/src/memory.rs
linera-storage/src/rocks_db.rs
linera-storage/src/scylla_db.rs

* Use one thread for all contract calls of a transaction (#1193)
* One step closer to share memory states between distinct calls of the same application in the same transaction (#488)
* Create a new "synchronous" implementation of the system API traits
* Improve error handling
* Make the new runtime the default (but do not remove the old one for now)
CI

Add synchronous runtime and make it the default for Wasm system APIs

---

docker/Dockerfile

We don't do anything related to Google Cloud Build on this Dockerfile anymore. We use it for building a Docker image by either building the binaries from within the container, or copying existing binaries into the container.
Remove the comment, as it's not relevant anymore
CI

Remove Google Cloud Build comment from Dockerfile

---

examples/amm/src/contract.rs
examples/amm/src/lib.rs

The AMM smart contract security is possibly incorrect. Additional checks were added.
The security of smart contracts is based on the following principles:
* Only the user chain can authenticate a user.
* Thus the operations that are not done locally can be authenticated and that is the `Swap` operations.
It is an open question to me whether this protection is actually needed since the operations rely on fungible which is itself authenticated.
The CI still pass after those changes.
It would be nice to improve the documentation of the security of Linera.

Improve authentication of AMM smart contract.

---

examples/meta-counter/src/service.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/service_system_api.wit
linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
linera-sdk/src/lib.rs
linera-sdk/src/service/system_api/private.rs
linera-sdk/wasm-tests/src/lib.rs

The system call for querying another application was unnecessarily `async`.
Make the system call synchronous, removing the promise APIs for it, and update the higher level API to not be `async`.
This changes the SDK and the system API, so:
- Need to bump the major version number in the next release of the crates.
This is part of issue #1152, but does **not** close it.

Make `try-query-application` system API synchronous

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

We will add a `linera-benchmarks` binary to measure the network's performance. These will use the CLI wrappers.
Extend the CLI wrappers so that they provide the needed functionality:
* Add `parameters` and `required_application_ids` to `create_application`.
* Add `request_application`.
* Make `build_application` not test-only.
`create_application` is already used in tests. The others will be used by the fungible benchmark, and otherwise are not used in production code yet.

Extend CLI wrappers to prepare for benchmarks.

---

kubernetes/linera-validator/grafana-dashboards/linera-general.json
kubernetes/linera-validator/templates/config.yaml
kubernetes/linera-validator/templates/grafana-dashboards-config.yaml
kubernetes/linera-validator/values-local.yaml

We'll have some dashboards that will contain different data that we're interested in monitoring. To do that we need a way of defining and persisting Grafana dashboards.
Create dashboards in Grafana, export the JSON, add it to our codebase and make sure that JSON gets imported when Grafana is initialized
Infra side PR: https://github.com/linera-io/linera-infra/pull/20
Deployed locally, saw that the imported dashboard was there

Persist Grafana dashboards

---

linera-views/src/collection_view.rs
linera-views/src/key_value_store_view.rs
linera-views/src/log_view.rs
linera-views/src/map_view.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/register_view.rs
linera-views/src/set_view.rs
linera-views/src/views.rs
linera-views/tests/views_tests.rs

We recently eliminated the `delete` and `write_delete` because they were essentially not used and actually
we could do instead a `clear + save`.
It turns out that having that `delete=clear + save` was not so easy and required changing some code in the flush of the views.
That PR is not critical, but I think it keeps us honest to have it working as expected and so I think it is important long term.
The corrections were done for the following views:
* `QueueView`
* `KeyValueStoreView`
* `RegisterView`.
The idea is that if we do a clear and then the flush then nothing should be left.
Corresponding changes were done in the tests that in fact revert previous changes.
That CI test should do the trick and was not so easy to get correct.
The fact that the `flush + save` does not leave anything is …

Reintroduction of `delete=clear + save`.

---

linera-chain/src/chain.rs

Fix a bug with message counters
* Add an assert
* Fix the bug
Code with further improved in the next PR 1429.
* CI
* remove the fix, keep the assert, run `cargo test -p linera-core test_memory_claim_amount`.

fix outgoing message count for rejected input messages

---

linera-chain/src/chain.rs
linera-core/src/unit_tests/worker_tests.rs
linera-service/src/faucet.rs

During local testing I sometimes ran into the situation where I killed and restarted the faucet, and then its local storage was not in sync with the wallet.
Call `synchronize_from_validators` on startup.
(Also: Remove another unused `mut`.)
Locally, this solved the issue for me.

Synchronize faucet balance from validators on startup.

---

kubernetes/linera-validator/grafana-dashboards/linera-general.json

The dashboard was accidentally committed with an absolute time range
Changing to last hour instead
Deployed locally, saw dashboard with the updated time, auto updating as expected

Default to last hour on linera general dashboard

---

linera-rpc/src/grpc_network.rs
linera-rpc/src/simple_network.rs

Small performance improvement
Fix the condition to skip the RNG if the failure is 0 (as expected in production).
CI

performance fix: do not call RNG for testing failures when not needed

---

linera-service/src/benchmark.rs
linera-service/tests/end_to_end_tests.rs

The benchmark fails if there are fewer transfers per wallet than there are wallets, because then not every application is installed on every chain.
Only check those tokens that are expected to have a nonzero balance.
The test was changed to have three wallets and only one transfer per wallet, with uniform distribution. So each app is registered on the chain where it was created, and on _one_ more chain, but not on the third one. This fails without the fix.

Benchmark: Don't check chains that didn't receive a transfer.

---

.github/workflows/rust.yml
examples/amm/README.md
examples/amm/src/lib.rs
examples/counter/README.md
examples/counter/src/lib.rs
examples/matching-engine/README.md
examples/matching-engine/src/lib.rs
examples/meta-counter/README.md
examples/meta-counter/src/lib.rs

The newly added READMEs were not added to the example applications' crate-level documentation.
Add them to the `lib.rs` files and use `cargo-rdme`.
The checks were added to CI.

Use cargo-rdme for the new example READMEs, too.

---

linera-rpc/src/config.rs
linera-rpc/src/grpc_network.rs

When I tried out the fungible benchmark locally I often saw the cross-chain message queue overflow.
When making the remote `handle_cross_chain_message` call, don't `await` the result before making the next one.
(Also: The benchmark shouldn't fail if we send fewer transactions per wallet than we have wallets.)
It locally fixes the problem for me.

Handle cross-chain messages in parallel.

---

linera-execution/src/wasm/system_api.rs
linera-sdk/mock_system_api.wit
linera-sdk/service_system_api.wit
linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
linera-sdk/src/lib.rs
linera-sdk/src/service/system_api/private.rs
linera-sdk/src/test/unit/mod.rs
linera-sdk/wasm-tests/src/lib.rs

Application services can call other application's services to execute queries. The API to execute those calls had a return type that included a `Result` with a `String` error type. The error type is not useful for the services, because it can only indicate an error in the Linera execution mechanism, and not in the called service. Such error should be reported to the user directly instead of to the caller application.
Change the APIs to not be fallible.
No new features added, so no extra coverage needed. Existing tests should catch any regressions.
This PR changes the system API and the SDK, so
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/C …

Remove `String` error types from APIs to query other application services

---

linera-core/src/worker.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/server.rs

The system will require that all workers have access to the same data. In that case, it is unnecessary for the recipient of a cross-chain message to store the certificates, because they were already stored by the sender.
Don't save certificates received in a cross-chain message.
The tests still pass, because we already don't use RocksDB with multiple shards anymore, and the other databases are already shared between all shards.

Remove redundant write_certificates.

---

docker/Dockerfile

The proxy needs to make calls to validators over TLS - therefore requiring CA certificates.
Add CA certificates to primary container.
Checked implicitly in linera-infra.

Docker container has openssl and ca-certificates

---

CLI.md
linera-chain/src/manager.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/lib.rs
linera-execution/src/ownership.rs
linera-execution/src/system.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/linera.rs
linera-service/src/node_service.rs

The round timeouts are currently hard-coded, but different use cases may require different timeouts on different chains.
Make the timeouts configurable as part of the ownership config.
A unit test for the round timeout computation was added.

Make round timeouts configurable.

---

linera-sdk/src/contract/storage.rs
linera-sdk/src/service/storage.rs
linera-sdk/src/views/system_api.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lru_caching.rs
linera-views/src/memory.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/value_splitting.rs
linera-views/tests/store_tests.rs

The `KeyValueStore` trait is quite complex so it makes sense to split it.
We separate the write and read part of the functions.
The CI does the job of it.
No change.

Split the KeyValueStore trait.

---

linera-base/src/crypto.rs
linera-base/src/data_types.rs
linera-base/src/graphql.rs
linera-base/src/identifiers.rs
linera-base/src/lib.rs

Make sure that we document public APIs in `linera-base` going forward.
* Add `#![deny(missing_docs]] to `linera-base`
* Add the missing docs
* Skip error enums because the docs are duplicating the strings.
CI

deny missing docs in linera-base

---

linera-chain/src/manager.rs
linera-core/src/client.rs
linera-core/src/unit_tests/worker_tests.rs

If a validator signed to confirm a fast block, that must be treated as a locked block for the protocol to be safe.
Add the corresponding check to the chain manager and to the chain client.
The new worker test fails without the fix.
- Closes https://github.com/linera-io/linera-protocol/issues/1479.

A fast block proposal must be treated as locked.

---

Cargo.lock
Cargo.toml
linera-service/Cargo.toml
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/src/project.rs
linera-service/src/server.rs
linera-service/src/util.rs

`std::fs` errors are not comprehensive (intentionally) when it comes to reporting why an `fs` operation failed. For example, a file will be reported as missing without the file name being provided in the error itself, making debugging difficult.
Move to `fs_err` which is a drop-in replacement for `std::fs` with convenient error reporting.
Before:
```
The system cannot find the file specified. (os error 2)
```
After:
```
failed to open file `does not exist.txt`
caused by: The system cannot find the file specified. (os error 2)
```
Tested by CI.

linera-service uses fs_err for better errors

---

linera-chain/src/manager.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/ownership.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera.rs
linera-service/src/node_service.rs

`WaitForTimeout` should only be returned with a realistic timeout. We have been using `Duration::MAX` for rounds that don't time out, which is confusing.
Make timeouts `Option`s.
The tests have been updated.

Make timeouts optional. Don't return Timestamp::MAX as a timeout.

---

linera-views/src/batch.rs
linera-views/src/dynamo_db.rs
linera-views/src/journaling.rs
linera-views/src/lib.rs
linera-views/src/lru_caching.rs
linera-views/src/scylla_db.rs
linera-views/src/simple_store.rs

While reviewing #1419 in depth, I thought I would try to make the code nicer to help me understand it.
* Generally try to keep names short and trust the type system of Rust.
* Make some comments shorter (or more neural)
* Rename SimplifiedBatchIter into BatchValueWriter and move two methods around.
* Rename the module `simple_store` into `journaling` (the thing we care about!)
There should be no changes in the algorithms at all.
CI

Code style improvements after #1419

---

linera-chain/src/manager.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs

If there is a validated block certificate in a past round on a multi-owner chain, any owner needs to re-propose the latest such block, since the validators are not allowed to vote for anything else. This is currently not working in all cases.
Add a test where a client has a local pending block in multi-leader round 0, but there is also a validated block certificate in round 1. If the client now tries to commit any operation, it has to first re-propose that validated block (_not_ its older local pending block), and then, on the next block height, the operation itself.
Fix the test and a few related issues:
* The chain manager should return `Skip` if it receives its locked block again.
* The client needs to call `process_certificate` if it finalized someone else's validated block.
* The …

Test and fix re-proposing a validated block.

---

linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/tests/test_execution.rs

Messages sent by called applications were not preceded by system messages to register the application to receive the message on the destination chain. This meant that receiving the messages would fail unless the application was already registered or if a chain owner requests for the application manually.
Rewrite `update_execution_outcomes_with_app_registrations` to check for outgoing messages in all execution outcomes of the call stack. System messages are then created for all outgoing user application messages to their respective destination chains.
Some unit tests were added to cover different scenarios of called applications sending messages.
Fixes #1417

Fix missing application registration messages

---

linera-chain/src/manager.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs

`ChainManagerInfo::next_round` says `None` if we are in the fast round and there is already a proposal. However, if that proposal is our own pending block, we _should_ retry.
In `execute_block`, set `can_propose` to `true` in this case.
A test for this case was added.

Test and fix re-proposing a pending block in the fast round.

---

examples/counter/README.md
examples/counter/src/lib.rs
examples/fungible/README.md
examples/fungible/src/lib.rs

Each time the README tests are executed, they modify the `package-lock.json` of the web frontends for the counter and fungible example applications.
Add `--no-save` to the `npm install` commands in the READMEs to avoid updating the lock files. Whenever we do want to update their dependencies, we should make a separate PR for that.
Running `cargo test readme` now doesn't update the lock files anymore.

Don't update npm lock files in README tests.

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs

Simplify the code a little
Remove one `ref` left in the code
Note: `ref` is almost never needed: https://doc.rust-lang.org/rust-by-example/scope/borrow/ref.html
CI

nit: remove the only `ref` in the codebase

---

linera-views/src/batch.rs
linera-views/src/journaling.rs

As [pointed out](https://github.com/linera-io/linera-protocol/pull/1483#discussion_r1450127052) by @afck, my last-minute change PR #1483 that was incorrect.
Partially revert commit a12f10a8b70bf5baa0 from PR #1483 to bring back `next_batch_size`
CI

Address @afck's comment on #1483

---

linera-views/src/collection_view.rs
linera-views/src/graphql.rs
linera-views/tests/collection_tests.rs
linera-views/tests/views_tests.rs

The work done recently for `ReentrantCollectionView` has revealed some similar issues with
`CollectionView`, which we now correct.
* The `load_entry` has been renamed as `load_entry_or_insert`.
* The `contains_key` is added to the `CollectionView`.
* The `try_load_entry` is now a true `&self` function (e.g. the hash does not change) though the interior mutability is still needed.
* The `try_load_entry` is now returning an `Option<ReadGuardedView<W>>`.
The function `try_load_entry` has been added to the tests.
The CI test has been improved.
No change. The documentation of the library is changed accordingly.

Improvements on `CollectionView`, resolution of bug and API change.

---

CLI.md
linera-service/src/benchmark.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs

`linera wallet init --faucet URI` creates a (default) chain implicitly. This caused some confusion because `linera wallet init --genesis FILE` does not.
* Require that `--new-chain` is passed `linera wallet init --faucet URI --new-chain`
* Create type `FaucetOption`
CI

Create option `--new-chain` to explicitly request a chain from a faucet

---

linera-service/Cargo.toml
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/remote_net.rs
linera-service/tests/end_to_end_tests.rs

As a way to also test the devnet, we need the e2e tests to run against it also
Implement the config for that, and run the tests with it
Ran `cargo test -p linera-service --features scylladb,remote_net --test end_to_end_tests -- remote_net_grpc`, all tests passed

Run e2e tests against Devnet

---

linera-service/src/benchmark.rs

If you run `linera-benchmark` outside of `linera-protocol` you cannot resolve the `examples/fungible` path and you just get a not-found error.
Add some context to the error.

Added helpful error message if the examples cannot be found

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/mod.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/utils/mock_application.rs
linera-sdk/src/log.rs

Every time an application calls another, a new instance of the callee application is created. However, the ability to reuse an instance may increase performance and allow the application to use volatile memory that is persisted for longer than one call.
As a first step, the instance should be reused if there are multiple calls to the application inside the *same transaction*.
Store a map of loaded applications in the runtime, and reuse entries if an application is called again in the same transaction.
There's a small issue with this. The `SyncRuntimeInternal` contains the map but it is placed inside an `Arc<Mutex<_>>` that is then used as the runtime implementation. Each loaded application has a copy of the `Arc<Mutex<_>>` to use as its runtime. This leads to a circular dependency where …

Reuse contract and service instances inside transaction

---

linera-service/src/config.rs
linera-service/src/linera.rs

See if we can let wallets follow any chain (not just root chains)
Remove the need for a chain description
Tested manually
```
linera_spawn_and_read_wallet_variables linera net up
linera faucet
```
then
```
export LINERA_WALLET_1=wallet_1.json
export LINERA_STORAGE_1=rocksdb:client_1.db
export LINERA_WALLET_2=wallet_2.json
export LINERA_STORAGE_2=rocksdb:client_2.db
linera -w 1 wallet init --faucet http://localhost:8080 --with-new-chain
linera -w 1 wallet show  # Note CHAIN_ID1 
linera -w 2 wallet init --faucet http://localhost:8080 --with-new-chain --with-other-chains $CHAIN_ID1
linera -w 2 service &
linera -w 1 close-chain $CHAIN_ID1
```
kill service then check the height of $CHAIN_ID1 seen by wallet 2 with
```
linera -w 2 show
```

Generalize --with-other-chain

---

kubernetes/linera-validator/scylla.values.yaml

ScyllaDB occasionally runs out of connections due to running out of memory for new connections.
Increase the dev profile default resources.
Implicitly in CI.

Increase scylladb dev resources

---

CLI.md
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera.rs
linera-service/tests/end_to_end_tests.rs

* Make sure the number of initial root chains and their initial amount are configurable in `linera net up`
* Bring back a meaningful `linera benchmark`
* Add the missing options and CLI parameters
* Make sure the initial amount in the local kubernetes tests matches the local net
```
linera_spawn_and_read_wallet_variables \
linera net up --other-initial-chains 1000 --validators 4
linera benchmark
```

Add missing genesis options in cli wrappers

---

linera-chain/src/chain.rs
linera-core/src/worker.rs

The default histogram buckets don't map particularly well to some metrics. Finding optimal values will require some discussion and experimentation. However, we could use better temporary values until then.
Tweak the buckets of some histogram metrics, to use temporary values that are better than the defaults.
Manually executed the Crowd-Funding integration tests tweaked to print out the metrics in the end.
Internal changes, nothing needed.

Tweak default histogram buckets

---

kubernetes/linera-validator/templates/proxy.yaml
kubernetes/linera-validator/values-local.yaml

Metrics on the proxy side were not working
Fix it
Ran locally, saw metrics:

Fix Prometheus metrics on Proxy

---

linera-chain/src/chain.rs
linera-rpc/src/grpc_network.rs
linera-service/src/grpc_proxy.rs

All latency metrics should be in ms
Do that
Ran e2e tests locally, saw metrics logged with higher ms amounts

Standardize latency metrics to ms

---

.github/workflows/kubernetes.yml

Prometheus is actually kinda finicky. Pretty easy to break. One YAML like that you accidentally remove, and it silently breaks lol
Add a check in CI to make sure PRs are not breaking this. Could be a pretty severe issue to silently not have metrics once we're in prod
CI

Make sure Prometheus metrics work in CI

---

kubernetes/linera-validator/grafana-dashboards/linera-general.json

The dashboard was not really organised or useful before. 
Add:
1. Segregation between cluster metrics and execution metrics.
2. Add some basic cluster level metrics (cpu, mem, network)
3. Add units to existing and new dashboards

Updated Linera General Grafana dashboard

---

CLI.md
linera-chain/src/chain.rs
linera-core/src/unit_tests/client_tests.rs
linera-execution/src/policy.rs
linera-execution/src/resources.rs
linera-execution/tests/wasm.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/linera.rs

* Part of the effort to finalize sender fees (#1474)
* The current policy (notably on messages) is difficult to explain
Follows PR #1534
* Align the field names of ResourceControlPolicy with `linera_sdk::Resources`
* Do not use BCS-serialized sizes of protocol objects: developers (and soon the runtime for grant computations) cannot do anything with these.
* Charge per outgoing message and per byte in the argument of a user message.
* Charge per operation and per byte in the argument of a user operation.
* Simplify `ResourceTracker` to not contain policy data.
CI

Improve resource policy

---

linera-core/src/client.rs
linera-rpc/src/grpc_network.rs
linera-rpc/src/mass.rs
linera-rpc/src/simple_network.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

The benchmark uses `max-proposals` only as a maximum, and uses at most as many chains as there are already in the wallet. This is inconvenient if one wants to e.g. test with 100 chains against devnet.
The `max-in-flight` parameter is only respected with the simple network client, not with gRPC, which handles all requests in sequence.
Rename `max-proposals` to `num-chains` and create more chains if necessary.
Use `buffer_unordered` to handle up to `max-in-flight` requests concurrently also with gRPC.
Tested manually against devnet.
- This is stacked on top of #1542.

Benchmark: Respect num-chains and max-in-flight parameters.

---

.github/workflows/rust.yml
linera-protocol.code-workspace

For VSCode users, right now `rust-analyzer` doesn't recognize anything in the examples folder. That makes the red squiggles for errors, auto complete, jump to definition, etc not work from within the examples folder.
The reason for that is because examples isn't included in the workspace. I'm adding with this PR a workspace file. If you open your `linera-protocol` checkout using File -> Open Workspace from File and choose this file, it'll open a workspace with both the root directory and the examples directory in it, making all `rust-analyzer` features work on the examples folder as well.
Tested locally, I see errors in examples now (in my WIP code for another PR)

Add workspace file with examples

---

linera-chain/src/chain.rs
linera-rpc/src/grpc_network.rs
linera-service/src/grpc_proxy.rs

@jvff pointed out to me that `.as_millis()` returns an integer, so we lose precision for microseconds and so on, because it gets capped. I also remembered that's why I went with seconds to begin with, because at least we got full precision 😅
Roll back to using `.as_secs_f64()`, but multiply by 1000.0 so we have the values in milliseconds
Make sure we have floating point precision again

Don't use .as_millis()

---

.github/workflows/rust.yml
linera-execution/src/system.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

The `linera benchmark` command currently isn't tested at all (it's marked `cfg(benchmark)` instead of `cfg(feature = "benchmark")`).
Move the benchmark part into a separate test, use the correct feature attribute, and change the arguments so that it also tests creating new chains.
I changed `rust.yml` so that this also runs in CI.
- Related: https://github.com/linera-io/linera-protocol/pull/1543

An end-to-end test for the benchmark command.

---

linera-core/src/client.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/tests/end_to_end_tests.rs

The benchmark should be easy and fast to use in different scenarios.
Make the initial balance for newly created chains configurable, so it can be used with different fee structures and different faucet settings.
Make the transactions per block configurable, so we can test with more than one.
Create more than one new chain per block to speed up the setup process.
The existing test covers the non-trivial part: creating multiple new chains in one block.

Add more benchmark options.

---

.github/workflows/kubernetes.yml
Cargo.lock
examples/Cargo.lock
linera-base/Cargo.toml
linera-base/src/lib.rs
linera-base/src/prometheus_util.rs
linera-chain/src/chain.rs
linera-core/src/worker.rs
linera-rpc/src/grpc_network.rs
linera-service/src/grpc_proxy.rs
linera-storage/src/db_storage.rs
linera-views-derive/src/lib.rs
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_save_delete_view_code-2.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_save_delete_view_code-3.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_save_delete_view_code-4.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_save_delete_view_code.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_view_code-2.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_view_code-3.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_view_code-4.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_view_code.snap
linera-views/src/lib.rs

Ideally we would want a way to set a namespace to all our registered metrics
Created wrappers for the metric registration macros we're using, and made sure we set the linera namespace for all of them. Setting the namespace will also add a prefix to the exported metrics. We need to only use these wrappers from now on when registering new metrics, otherwise the namespace won't be properly set

Create wrappers for registering Prometheus metrics

---

CLI.md
linera-base/src/data_types.rs
linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/policy.rs
linera-execution/src/resources.rs
linera-execution/src/runtime.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

The current code is difficult to adapt for #1474 and other missing features like #1537.
* Add the missing code to price write operations
* Remove `RuntimeCounts` and `RuntimeLimits`
* Introduce `ResourceController` to keep together a (fixed) policy, a tracker, and a balance.
* The balance is systematically decreased when a new operation is "tracked".
* Use a similar idea in `ChainStateView::execute_block`. This requires generalizing the code so that we can store the resource funding balance in the system execution view (where transactions can modify it any time).
Follows #1535
CI
We may want to update [linera-infra/validators/scripts/create_and_upload_genesis.sh](https://github.com/linera-io/linera-infra/blob/21164476fc8c25359932714ac3d8ccc4b9dbdce5/validators/scripts/create_and_upload_gen …

Refactor fee computation during runtime execution

---

Cargo.lock
examples/Cargo.lock
linera-base/src/prometheus_util.rs
linera-chain/src/chain.rs
linera-execution/Cargo.toml
linera-execution/src/execution_state_actor.rs
linera-execution/src/wasm/mod.rs

Linera aims to be a low-latency block chain, and execution is in the critical path. Therefore, we should measure different parts related to execution.
Create a `MeasureLatency` helper extension trait to make it easy to add new latency measurements, and add histogram metrics for different execution parts.
No functionalities changed, just manually executed and printed all metrics.

Add some metrics related to execution

---

linera-views/src/metering.rs

PR #1521 and PR #1545 added some helper functions and types to `linera-base` for other crates to use. One of them places the metrics in a Linera specific namespace, while the other allows measuring latency using RAII.
Update the metrics in `linera-views` to use the new helpers.
No new functionalities, so no new tests are needed.

Update metrics in `linera-views` to use Prometheus helpers

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/tests/end_to_end_tests.rs

`linera benchmark` currently only creates native token transfer operations.
Add an optional argument so the user can specify a fungible token application that is registered on their default chain. The benchmark will use that instead of the native token.
Extended the end-to-end test.

Optionally use the fungible app in linera benchmark.

---

linera-service/src/cli_wrappers/local_net.rs
linera-service/tests/end_to_end_tests.rs

We are seeing timeouts in CI, possibly because the benchmark test runs with 15 chains.
Use 4 chains.
Hopefully CI passes now. :crossed_fingers: 

Reduce the number of chains in the benchmark e2e test.

---

linera-service/src/linera/client_context.rs

This `stream::iter` and corresponding `await` is redundant.
Remove them.
N/A

Remove unnecessary stream::iter.

---

CLI.md
Cargo.lock
examples/Cargo.lock
linera-execution/Cargo.toml
linera-execution/src/system.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

This PR replaces #1489 to apply the final suggested changes and merge it. All credit should go to @ashu26jha 
To add command to `subscribe` and `unsubscribe` to other chains, earlier it was only possible through GraphQL mutation, after successfully merge this PR, it can be done through CLI. For example:
`linera subscribe --subscriber $CHAIN_2 --publisher $CHAIN_1 --channel admin`
Added subscribe and unsubscribe in [`linera.rs`](https://github.com/linera-io/linera-protocol/blob/main/linera-service/src/linera.rs) also had to add `clap::ValueEnum` in the `SystemChannel`
Closes #1342

Added command to subscribe and unsubscribe to other chains

---

.github/workflows/kubernetes.yml
kubernetes/linera-validator/templates/scylla-manager-service-monitor.yaml
kubernetes/linera-validator/templates/scylla-service-monitor.yaml
kubernetes/linera-validator/values-local.yaml

ScyllaDB already exposes 440 Prometheus metrics
Scrape the Prometheus endpoint with our Prometheus instance to have access to those metrics
Ran e2e tests against the cluster locally, saw the metrics on Prometheus

Enable ScyllaDB monitoring

---

linera-views/src/batch.rs
linera-views/src/dynamo_db.rs
linera-views/src/journaling.rs
linera-views/src/memory.rs
linera-views/src/scylla_db.rs
linera-views/tests/store_tests.rs

The recent merging of the PR on the ScyllaDb journaling left some issues unanswered and a documentation insufficient. The current PR addresses that
* When the iterator reaches a state that it should not reach, then it is "unreachable()" instead of returning something non-sensical.
* The sizes of keys are kept on track for the size of the transaction.
* The changes are fully documented.
On the test side, now the ScyllaDb passes the same tests as the DynamoDb and Memory.
The CI.
No impact.

Some fix to Journaling

---

Cargo.lock
examples/Cargo.lock
linera-base/Cargo.toml
linera-base/build.rs
linera-base/src/lib.rs
linera-base/src/version_info.rs
linera-base/versions.sh
linera-core/Cargo.toml
linera-core/src/node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/codec.rs
linera-rpc/src/conversions.rs
linera-rpc/src/grpc_network.rs
linera-rpc/src/rpc.rs
linera-rpc/src/simple_network.rs
linera-rpc/tests/staged/formats.yaml
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/grpc_proxy.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs
linera-service/src/server.rs

https://github.com/linera-io/linera-protocol/issues/1555
Expose version info:
Run each of these types of query and check that the output is correct.
- Fixes https://github.com/linera-io/linera-protocol/issues/1555.

Expose version info to end users

---

CLI.md
linera-base/src/identifiers.rs
linera-chain/src/chain.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/worker.rs
linera-execution/src/execution.rs
linera-execution/src/resources.rs
linera-execution/src/system.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/conversions.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/benchmark.rs
linera-service/src/chain_listener.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/faucet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/schema_export.rs
linera-service/tests/end_to_end_tests.rs

* Support funding from authenticated accounts (#1537)
* Allow system balance to be modified from native apps (such as #1547)
* Fix `local-balance` when blocks have fees (or when system messages are failing)
* Create a notion of "3-way merge" for balances (this is classical)
* In the case of authenticated accounts, we may also withdraw from the chain account if the owner's account is not enough. (It could also be the opposite, but this feels nicer.)
* Extend `ChainInfoQuery` to support requesting the balance of a user
* In `client.rs`, rename `local_balance` into `query_balance` (from the name of the CLI command calling it) then use `stage_block_execution_and_discard_failing_messages` in `query_balance` to avoid failing if a message fails.
* Extend CLI to allow querying account balances
CI

Support funding from authenticated accounts

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

Avoid confusing people if possible
Create a new (adhoc) method in CLI wrapper.
An error message still appears on stderr (the uncaught Rust error) but it's not a wall of ERROR logs any more.
CI

silence expected scary errors in test

---

CONTRIBUTING.md
linera-base/src/version_info.rs
linera-indexer/lib/src/rocks_db.rs
linera-indexer/lib/src/runner.rs
linera-indexer/lib/src/scylla_db.rs
linera-indexer/lib/src/service.rs
linera-rpc/examples/generate-format.rs
linera-rpc/proto/rpc.proto
linera-sdk/src/bin/linera-wasm-test-runner/main.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/benchmark.rs
linera-service/src/cli_wrappers/remote_net.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/database_tool.rs
linera-service/src/faucet.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs
linera-service/src/server.rs
linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs

Help with debugging
* Make the --version option of linera binaries print the full VersionInfo
* Print a warning when the version of the faucet doesn't match the version of the linera tool
In my understanding, the version information are only computed when `linera-base` is recompiled. This can give unexpected results when developing with incremental builds --> I created https://github.com/linera-io/linera-protocol/issues/1573
* `linera --version`
* CI
* Tried the faucet manually with different version and got something like this
```
2024-01-28T02:06:40.354322Z  WARN linera: Make sure to use a Linera client compatible with this network.
----- Faucet ------
Linera protocol: v0.6.0
Built from git commit: 54fdd8cf52002774e7518ac3e55220871165ccdc-dirty
RPC API hash: …
```

Make the --version option of linera binaries print the full VersionInfo.

---

linera-execution/src/system.rs

The current error logs are confusing.
Rename the variant and fix the text.
Note: this issue was found because of separate problem: https://github.com/linera-io/linera-protocol/issues/1576
CI

fix error name: NoSuchChannel -> AlreadySubscribedToChannel

---

linera-core/src/unit_tests/client_tests.rs

This assertion fails occasionally, but with a low probability, so it is hard to reproduce.
Print the unexpected result if it fails again.
Wait until it fails again.
- https://github.com/linera-io/linera-protocol/issues/1581

Print more information if request_leader_timeout test assert fails.

---

docker/Dockerfile
linera-service/src/cli_wrappers/docker.rs

Docker images can be labeled, so we should add a label for the commit hash
Add the commit hash label
Built the image, ran
```
docker inspect --format='{{ index .Config.Labels "git_commit" }}' linera-test:latest
```
and got the commit hash the image was built on

Add git_commit label to Dockerfile

---

linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-storage/src/rocks_db.rs
linera-storage/src/unit_tests/rocks_db.rs
linera-views/src/rocks_db.rs
linera-views/tests/store_tests.rs
linera-views/tests/views_tests.rs

Some tests in RocksDb fail because of the object `TempDir` going out of the scope. This makes some `RocksDb` tests fail.
* The `create_rocks_db_test_store` is returning a store and a temporary directory.
* The `make_test_storage` is also returning storage and a temporary directory.
* The `create_rocks_db_test_context` is eliminated since unused.
* The test `test_rocks_db_big_write_read` is now enabled.
The proposed solution is definitely making the code less nice. The following alternatives were considered:
* The initial idea was to put an `Arc<Option<TempDir>>` for the `RocksDbStore` and the `RocksDbStoreConfig`. However, that adds an entry that is carried over and that is only relevant to the tests.
* For `create_rocks_db_test_store` this is fine. However for the …

Expand the scope of the temporary directories in `RocksDb`

---

linera-indexer/example/tests/test.rs
linera-service-graphql-client/tests/test.rs
linera-service/src/cli_wrappers/docker.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/linera/main.rs
linera-service/tests/end_to_end_tests.rs

To make the end-to-end tests work with fees, a faucet, and ultimately Devnet, I will need to add some functionality to `LineraNet` and `LineraNetConfig`. This will be easier if the code is simplified first. Also, there are some test `impl`s that lack configuration options other `impl`s have, and this refactoring will make it easier to add them.
Make `SharedLocalKubernetesNetTestingConfig` wrap a `LocalKubernetesNetConfig` and replace `LocalNetTestingConfig` with a test-specific constructor for `LocalNetConfig`.
CI includes the end-to-end tests with the shared Kubernetes configuration.
- This is in preparation for https://github.com/linera-io/linera-protocol/issues/1620.

Deduplicate LineraNetConfig impls.

---

linera-views/src/scylla_db.rs

The existing code for `ScyllaDb` forces the recompilation over and over of Queries. While this is fast, there is no justifiable reason to do so. The PR resolves that issue.
A composed type encompassing the different types of queries has been created.
The CI should do the job.
Not relevant.

Support prepared queries in the `ScyllaDb` code

---

.github/workflows/scylladb.yml
docker_scylla/Dockerfile
docker_scylla/modif_scylla.yaml
linera-views/tests/store_tests.rs

The tombstone mechanism in ScyllaDb is limited to 10000 tombstones by default.
This PR extends it to 200000.
* Add to the store_test.rs a test that triggers the error with the default settings of ScyllaDB.
* Add the creation of a modified ScyllaDB image (which is very fast).
* Modify the CI accordingly.
The CI should do it.
More work is needed for the Kubernetes.

Expand the size in the tombstone correction.

---

kubernetes/linera-validator/scylla.values.yaml
kubernetes/linera-validator/templates/scylla-config.yaml

The query tombstone limit by default in ScyllaDB is 10000 - which we are hitting quite quickly due to performing deletes frequently, probably in the `QueueView` associated with Inboxes.
Increase the Tombstone limit until we implement something more sustainable long term.
Thanks @MathieuDutSik and @andresilva91 for helping out on this.

Bump tombstone limit

---

.github/workflows/documentation.yml
.github/workflows/dynamodb.yml
.github/workflows/explorer.yml
.github/workflows/kubernetes.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml

We previously switched to my fork of the Rust toolchain GitHub actions, `Twey/setup-rust-toolchain`, in order to be able to override the toolchain specified in `rust-toolchain.toml`.
Now that this work [has been merged](https://github.com/actions-rust-lang/setup-rust-toolchain/pull/26) into the upstream, we can rejoin to the upstream version.
Revert to the upstream version.
CI.
None needed: CI change.
- https://github.com/actions-rust-lang/setup-rust-toolchain/pull/26

`.github/workflows`: use upstream Rust actions

---

.github/workflows/rust.yml
scripts/check_copyright_header/src/main.rs

This script gives no useful feedback when it fails, requiring manual hunting down of the offending files.
Print the file on which it fails, as well as the reason for which it is failing.
Also, as a bonus, support multiple input files, allowing for use with globbing.
CI.  I have also manually tested a negative example locally.

`scripts/check_copyright_header`: give more useful feedback

---

.github/workflows/rust.yml
Cargo.toml
examples/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views/Cargo.toml

Trailing commas are good :)
This PR previously added a `tomlfmt.toml` that configured the `multiline_trailing_comma` feature.  Unfortunately, this exposed a bug in `cargo-sort` that meant it was impossible to format the workspace `Cargo.toml` to its liking.  Furthermore, on inspection of the documentation, it turns out that `multiline_trailing_comma` should be on by default.
I added [a PR](https://github.com/DevinR528/cargo-sort/pull/70) fixing these bugs, and the test that should have caught them.
Point our CI's `cargo sort` to my branch.
CI
- https://github.com/DevinR528/cargo-sort/pull/70

Fix a couple of bugs in `cargo-sort`

---

Cargo.lock
linera-views-derive/src/lib.rs
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-2.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-3.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code-4.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_clonable_view_code.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_sharable_view_code-2.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_sharable_view_code-3.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_sharable_view_code-4.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_sharable_view_code.snap
linera-views/Cargo.toml
linera-views/src/collection_view.rs
linera-views/src/common.rs
linera-views/src/hashable_wrapper.rs
linera-views/src/key_value_store_view.rs
linera-views/src/log_view.rs
linera-views/src/map_view.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/register_view.rs
linera-views/src/set_view.rs
linera-views/src/test_utils/mod.rs
linera-views/src/test_utils/test_views.rs
linera-views/src/unit_tests/views.rs
linera-views/src/views.rs

Because views have their state split between the memory type and the persistent storage, it's not safe to share them trivially (using Clone, for example). That's because one view might update the persistent storage with data that conflicts with the memory state of the other view, and that other view has no way to know that it became stale.
However, it is still useful in some scenarios to share views while ensuring the states are valid by other means (e.g., ensuring there is only one of the view instances used for writing to the view).
This is some initial work for https://github.com/linera-io/linera-protocol/issues/1616, in order to be able to share the ChainStateView without having to wait for a ChainGuard unnecessarily.
Create a `SharableView` trait with a `share_unchecked` method. This …

Add a `SharableView` trait

---

linera-execution/src/graphql.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

`assert_approx` asserts a balance with an allowed error margin of 0.1 tokens, because of fees. But having approximate asserts in tests is not a good idea in the long run and can cause false positives as well as negatives.
Remove them, or replace them with either exact comparisons where feasible, or with inequalities, or use owner accounts or the fungible application to make them exact.
The tests should still all serve their intended purpose. In most cases it is only about checking whether a message has arrived.
- Close #1637.

Get rid of `*_approx` in the end-to-end tests.

---

flake.lock
linera-execution/src/util/mod.rs
linera-execution/tests/utils/mod.rs
linera-rpc/src/grpc_network.rs
linera-service/src/grpc_proxy.rs
linera-views/src/test_utils/mod.rs
linera-views/tests/key_value_store_view.rs
toolchains/build/rust-toolchain.toml
toolchains/lint/rust-toolchain.toml

This allows us to use `async fn` in many ([internal](https://blog.rust-lang.org/2023/12/21/async-fn-rpit-in-traits.html#--impl-trait-in-public-traits)!) traits instead of relying on `async_trait`, which adds a lot of noise to documentation.
Bump our build toolchain to Rust 1.75.  Additionally, update our lint toolchain to a more recent nightly.
CI.

Update toolchain to 1.75

---

CONTRIBUTING.md
Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-execution/Cargo.toml
linera-execution/build.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/sanitizer.rs
linera-execution/tests/wasm.rs
linera-views/src/lib.rs

For the #1608 we will need the Linera protocol crates to compile to Wasm.  Prometheus does not compile to Wasm, and even if it did we have nowhere to put the metrics when we're running in the browser.
Feature-gate Prometheus behind a `metrics` feature, as is done elsewhere in the codebase, that can be disabled when compiling to Wasm.
Build with `--no-default-features --features wasmer` to check that all metrics code has been correctly excised.
No special care required.  The feature flag is enabled by default, so consumers should see no API change unless they explicitly disable it.

`linera-execution`: Feature-gate Prometheus

---

linera-base/src/identifiers.rs
linera-core/benches/client_benchmarks.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/system.rs
linera-service/src/benchmark.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/tests/end_to_end_tests.rs

We'll need `Account` for the Native fungible app, but we can't add a dependency on `linera-execution`
Move `Account` to `linera-base`
CI

Moving system::Account to linera-base

---

linera-rpc/src/grpc_network.rs
linera-service/src/grpc_proxy.rs

Silence lint warnings when not running clippy on nightly (probably caused by #1643).
Use `#![allow(unknown_lints)]` twice.
CI + ran clippy locally

silence "unknown lints" warning in two files

---

kubernetes/linera-validator/templates/prometheus.yaml

We're now using c3 VM type on GCP, which is incompatible with `pd-standard`
Use `pd-balanced` instead. Local runs can keep using `pd-standard`, which is why I'm not altering anything there. Also setting reclaim policy to `Retain` now, as the default was `Delete` before, which is not what we want.
Restarted Prometheus pod using this StorageClass on the devnet

Creating pd-balanced StorageClass for GCP

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-execution/src/resources.rs
linera-execution/src/system.rs
linera-execution/tests/fee_consumption.rs

* Make e2e tests easier to write
* Clarify the role of chain accounts as fee grants
* Prepare #1626 (which will replace this code but we're changing the semantics now)
* Charge the chain account before the owner account
* Refund the owner account (note: in #1626, we check if the owner account exists first. This makes little difference because there are no refund right now)
CI

Default to charging fees from the chain account

---

linera-views/src/dynamo_db.rs
linera-views/src/scylla_db.rs

Several operations are not paged and this can create problems.
* The reading of all tables in `DynamoDb` is done using pagination.
* The same is done for `DynamoDb`.
* The `read_value_internal` and `contains_key_internal` are both paged even if 0 or 1 keys are expected to happen.
The CI does not change. But this functionality has been revealed when writing the PR https://github.com/linera-io/linera-protocol/pull/1640.
No change.

Implement pagination for `DynamoDB` and `ScyllaDB`.

---

linera-witty-macros/src/unit_tests/wit_store.rs
linera-witty-macros/src/util/fields.rs

If a single field was marked to be skipped by Witty, then the code generated for `WitStore` would not compile. This happened because the code generation used a single underscore (`_`) for ignoring the field, but did not add the field name. That was incorrect.
In other words, for the following input:
```rust
#[derive(WitStore)]
pub struct MyType {
#[witty(skip)]
skipped: u8,
not_skipped: u8,
}
```
the following destructuring was generated:
```rust
let MyType {
not_skipped,
_,
} = self;
```
where the correct would be:
```rust
let MyType {
not_skipped,
skipped: _,
} = self;
```
Simplify the code generation and always use two dots instead.
In other words, for the example above, the following is now generated:
```rust
let MyType {
not_skipped,
..
} = self;
```
A new unit test was added to …

Fix code generated for `struct`s with named fields where only one field is skipped

---

CLI.md
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/lib.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/worker.rs
linera-execution/src/execution.rs
linera-execution/src/system.rs
linera-service/src/linera/client_options.rs

Messages with assets can accidentally get sent to chains that get closed without receiving them. The assets are then lost, unless the closed chain is still able to reject and send them back.
Change what "closing a chain" means: The owners are _not_ removed, and can continue making blocks, but the blocks are now required to
* contain no operations and
* not _accept_ all messages.
But they can still reject messages, so they bounce back to the sender.
The client tests were updated.
- Closes https://github.com/linera-io/linera-protocol/issues/1653.

Closed chains still reject messages.

---

.github/workflows/rust.yml
Cargo.lock
linera-service/src/util.rs
linera-storage-service/Cargo.toml
linera-storage-service/src/child.rs
linera-storage-service/src/client.rs
linera-storage-service/src/lib.rs
linera-storage-service/tests/store_test.rs

The CI is running with a service that needs to be run before running the tests which is not great.
* A subprocess is created and dropped at the end of the scope.
* A duration has to be introduced to wait for the process to be active.
* The `env!("CARGO_BIN_EXE_...")` method is used for obtaining the binary.
The CI as it is the whole point.

Implement a child process for the linera storage server

---

linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-core/src/unit_tests/client_tests.rs

Closed chains should be able to reject messages, even if their chain balance is empty.
Waive the block fee on closed chains. Rejecting messages is already free anyway.
Since empty blocks are now free of charge but still create work for the system, disallow them: They are not necessary anymore, even in single-leader mode, because every leader should be able to see the same incoming messages eventually.
The client test was extended.
- #1661

Waive block fee on closed chains; disallow empty blocks.

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-core/src/unit_tests/client_tests.rs

Closed chains should reject all messages, including protected ones.
Make an exception to the rule: now protected messages _can_ be rejected, but only on closed chains.
The client test was extended.
- #1661 

Allow rejecting protected messages on closed chains.

---

linera-core/src/worker.rs

`WorkerError::InvalidEpoch` currently contains the received, but not the expected epoch.
In one place, we erroneously put the expected epoch in it.
Put both epochs in the error.
This only makes the error more informative.

Put both the received and the expected epoch in the InvalidEpoch error.

---

linera-storage-service/src/child.rs
linera-storage-service/src/client.rs

The existing code for the storage service server still had some waiting period. It has now changed
to a better check of existence.
* Introduce a function for testing existence.
* Remove the `Result<Command>` that was not needed.
* Put the loop structure as in other such similar test in the code.
CI should do it.
Not relevant.

Address the test of existence of child storage service server

---

linera-storage/src/db_storage.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/journaling.rs
linera-views/src/memory.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/value_splitting.rs
linera-views/tests/admin_tests.rs

For every `impl AdminKeyValueStore<E> for T`, the error type `E` is determined by `T`.
Just like with e.g. `Context` or `KeyValueStore`, whose errors are associated types.
Make it an associated type instead.
(Only refactoring.)

Make Error an associated type of AdminKeyValueStore.

---

linera-chain/src/lib.rs
linera-chain/src/manager.rs

We use `ChainError::InsufficientRound(round)` both if the round is expected to be _at least_ and _strictly greater than_ `round`. The error message only describes the first case.
Add a new error variant for the strict inequality.
This only distinguishes more error variants.

Improve InsufficientRound error message.

---

linera-service/src/faucet.rs
linera-service/src/linera/main.rs
linera-service/src/unit_tests/faucet.rs

The faucet doesn't store the pending block in its wallet if `open_chain` fails. If the process is then restarted, it doesn't remember it and won't retry the pending block.
Update the wallet before returning in the error case, just like `NodeService` does.
The unit test was extended.

The faucet must remember the pending block after a restart.

---

linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-service/src/config.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-storage/src/lib.rs

Child chains automatically get subscribed to the admin chain, but root chains currently are not.
In general, all chains that aren't closed will usually want to be subscribed, so they get notified about new committees.
Make root chains be subscribed on initialization.
The tests were updated.
- Closes https://github.com/linera-io/linera-protocol/issues/1671.

Root chains are subscribed to admin chain from the start.

---

linera-witty-macros/src/util/mod.rs
linera-witty-macros/src/util/specialization.rs
linera-witty-macros/src/wit_export/caller_type_parameter.rs
linera-witty-macros/src/wit_export/function_information.rs
linera-witty-macros/src/wit_export/mod.rs

The `#[wit_export]` macro had very limited support for generic types. The type either could not have any generic type parameters or was required to have only a single generic type parameter that was assumed to be the caller type parameter. This made it hard to use on types that needed other type parameters.
Properly extract the `Generics` information for the `impl` block and use the `Specializations` helper type to specialize the caller type parameter.
The `CallerTypeParameter` was tweaked to help with the process of specializing the caller type parameter with a concrete caller type. The `Specializations` and `Specialization` types were updated so that they could be used as helpers to specialize the types.
- [reviewer …

Improve generics support for the `#[wit_export]` macro

---

Cargo.lock
linera-witty-macros/Cargo.toml
linera-witty-macros/build.rs
linera-witty-macros/src/lib.rs
linera-witty-macros/src/util/mod.rs
linera-witty-macros/src/util/specialization.rs
linera-witty-macros/src/wit_export/function_information.rs
linera-witty-macros/src/wit_export/mod.rs
linera-witty/Cargo.toml
linera-witty/build.rs
linera-witty/src/lib.rs
linera-witty/src/runtime/error.rs
linera-witty/src/runtime/mod.rs
linera-witty/tests/common/test_instance.rs
linera-witty/tests/reentrancy.rs
linera-witty/tests/wit_export.rs
linera-witty/tests/wit_import.rs

The `mock-instance` feature flag used in Witty were a little inconsistent, because it represented an instance that's only used for testing, and should therefore be enabled by a `test` feature flag instead. There was also an inconsistency with other crates which have started to use `cfg_aliases`, while Witty did not.
Replace the `mock-instance` feature flag with the `test` feature flag, and use some `cfg` aliases to improve readability.
Nothing new was added, so no new tests are needed.

Refactor Witty feature flags

---

scripts/linera_net_helper.sh

`.tmp` files in the current directory are annoying, and also the current formulation breaks if `TMPDIR` is set without a trailing slash (as it often is).
We don't need to prepend the argument to `mktemp -d` with `$TMPDIR`, as it's respected by default, so let's just remove it. 
CI.
Should be invisible to users, [unless they have a really weird workflow](https://xkcd.com/1172/).

`scripts/linera_net_helper.sh`: stop littering the current directory with temp files

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/matching-engine/src/contract.rs
examples/matching-engine/src/state.rs
flake.lock
linera-base/Cargo.toml
linera-base/src/crypto.rs
linera-execution/src/util/mod.rs
linera-execution/src/util/sync_response.rs
linera-rpc/Cargo.toml
linera-rpc/src/conversions.rs
linera-service/Cargo.toml
linera-service/src/config.rs
linera-service/src/linera/main.rs
linera-witty-macros/src/util/specialization.rs
linera-witty/tests/common/test_instance.rs
toolchains/lint/rust-toolchain.toml

We previously had an old version of `rand` pinned in several crates as `rand07`.  This version had several disadvantages, including being more error-prone when used in conditional builds (it unconditionally exported features that would panic at runtime).
Upgrade `rand` to 0.8 across the board.  In order to do this we:
- bump `ed25519` to 2.2
- bump `ed25519-dalek` to 2.1.1
- bump `ahash` to 0.7.8 and also 0.8.8 (we use both 0.7 and 0.8 transitively)
- bump `crc32c` to 0.6.5
- bump the nightly Rust to 2024-02-14
One might reasonably express surprise, especially at the last update.  Because we are on the nightly treadmill for our lint workflow, we get no backwards compatibility guarantees with regards to stable features.  Since a number of our dependencies have just jumped a compatibility …

Upgrade to `rand` 0.8 everywhere

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/updater.rs

`CommunicateAction` always tries to put together a `Certificate`, except if it's `AdvanceToNextBlockHeight`. That requires a lot of case distinctions and optional values in the code, since almost all of what happens in `communicate_chain_updates` applies only to the other variants. We also have several unreachable errors.
Separate the code; replace `AdvanceToNextBlockHeight` by a new function. Call the new function `communicate_chain_updates` and rename the other one to `communicate_chain_action`. Remove unreachable errors.
The protocol logic was not changed.

Simplify ValidatorUpdater.

---

linera-chain/src/manager.rs
linera-core/src/unit_tests/worker_tests.rs

`check_validated_block` returns `Skip` if the block matches the locked one, even if the locked one is from an earlier round.
In that case we still need to make a new signature, with the new round.
A test was extended; it would fail without this fix.

Don't skip if locked block is from different round.

---

linera-execution/build.rs
linera-execution/src/lib.rs
linera-execution/src/test_utils/mock_application.rs
linera-execution/src/test_utils/mod.rs
linera-execution/tests/fee_consumption.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/wasm.rs
linera-views/README.md
linera-views/src/lib.rs

Mock applications are useful for `linera-chain` tests, too.
Make the `linera-execution` test utilities available for other crates.
Tests that make use of this will be added in an upcoming PR.

Make linera-execution test utilities public.

---

docker/Dockerfile

While deploying devnet, we ran into an issue with the container images. Building our crates failed because the `linera-storage-service` crate's files were missing.
Ensure `linera-storage-service` is copied into the container images.
Source code not affected, so nothing is needed.
- This is required for the smooth deployment of the devnet

Add `linera-storage-service` to Dockerfile

---

.cargo/config.toml
.github/workflows/rust.yml

The redundant target in the documentation is required for `cargo-rdme` to create a link. I broke this in one case in #1694 to fix a `cargo doc` warning.
~Revert the change~ (already done in https://github.com/linera-io/linera-protocol/pull/1659); move the exemption from `rust.yml` to `config.toml` so we don't see that warning locally.
CI, and I ran `cargo doc` locally again.

Add redundant target exemption to config.toml.

---

linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-chain/src/test.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-core/src/client.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/linera/client_context.rs

To implement e.g. atomic swaps, applications will need to create temporary chains that can only be used for a single purpose.
A "chain application" can optionally be configured, and then only operations belonging to that chain are allowed.
A unit test was added.
- Will look simpler once rebased on top of https://github.com/linera-io/linera-protocol/pull/1696.
- Closes https://github.com/linera-io/linera-protocol/issues/1652.

Chain applications

---

linera-base/src/lib.rs
linera-base/src/ownership.rs
linera-chain/src/manager.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/graphql.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-rpc/examples/generate-format.rs
linera-service-graphql-client/src/service.rs
linera-service/src/faucet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-storage/src/lib.rs

For https://github.com/linera-io/linera-protocol/issues/305 applications will need to be able to open new chains, so we will add a `contract_abi` function in `linera-sdk`.
Move `ChainOwnership` and `TimeoutConfig` to `linera-base`, so they are available in `linera-sdk`.
This only moves two types.
- Preparation for https://github.com/linera-io/linera-protocol/issues/1650.

Move ChainOwnership to linera-base.

---

linera-chain/src/manager.rs

This function is unused; it didn't cause a warning because it's public.
Remove it.
N/A

Remove unused ChainManager::is_active.

---

linera-service/src/cli_wrappers/remote_net.rs

We want the testing URL to be configurable in order to test arbitrary devnets before promotion.
Add an optional env var to specify the faucet URL.

Faucet URL for testing is configurable via an env var

---

linera-sdk/src/contract/mod.rs

The signature definition of the `__contract_handle_session_call` WIT proxy function had incorrectly swapped the `session_state` parameter with the `argument` parameter.
Use the correct order of parameters in the proxy function signature, swapping the `argument` parameter with the `session_state` parameter.
Since both parameters have the same type and this is only in an external function signature, the behavior with the different order is exactly the same, which is why this wasn't caught before.
Nothing needed, because in practice this only changes the parameter name.

Fix parameter order in WIT proxy function

---

linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-execution/tests/test_execution.rs
linera-sdk/contract_system_api.wit

`close_chain` should return a `Result`; if the application is not authorized it should return `Err`.
Change the return type to `result<tuple<>, closechainerror>`.
Unfortunately we cannot use dashes in the error type due to a wit-bindgen bug.
`test_close_chain` was updated.
- #1722 

Make open_chain return a result.

---

.github/workflows/rust.yml

Currently linting stops at the first failure.  This means that any future linting errors will be eclipsed by earlier ones, and the developer can push a fix to a linting error only for the job to fail at a later error. 
The lint step runs on a small machine, and is therefore free for us as an open-source project.  By continuing on error we can allow all lint feedback to be collected in one run, which will hopefully allow developers to run the CI less often. 
Add `continue-on-error` to the Rust lint job, ensuring that it will run to completion even if one step continues.
CI.
No user-visible changes.
- [`continue-on-error` in the GitHub actions documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error)
- [reviewer …

`.github`: continue on error in Rust lint workflow

---

examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/fungible/src/contract.rs
examples/fungible/src/lib.rs
examples/fungible/src/service.rs
examples/fungible/src/state.rs
examples/fungible/web-frontend/src/App.js
examples/native-fungible/src/contract.rs
examples/native-fungible/src/service.rs
examples/native-fungible/src/state.rs
linera-execution/src/wasm/conversions_to_wit.rs
linera-sdk/src/service/conversions_from_wit.rs
linera-service/src/benchmark.rs
linera-service/tests/end_to_end_tests.rs

It was raised during #1675 that we might want to revert everything to use that `accounts` abstraction instead
Revert `fungible` back to using `accounts`, implement that for `native-fungible` using a new system API
CI

Support accounts query on native fungible as well

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-service/Cargo.toml
linera-service/src/grpc_proxy.rs

We need to be able to make RPC calls from the Web browser for https://github.com/linera-io/linera-protocol/issues/1609.
The accepted way to do this seems to be to use `grpc-web`, which supports almost all gRPC functionality.
Notably it does _not_ support gRPC's client-streaming functionality (streaming data from the client to the server).  I don't think this is an issue for now, but may require us to construct a more sophisticated transport in the future.
This PR implements the server side of the transport, exporting a `grpc-web`–compatible Web server from the gRPC proxy. 
gRPC usually uses HTTP/2, which browsers don't expose natively. The server uses this to dispatch: if the client requests HTTP/1.1, it will trigger the `grpc-web` pathway, while an HTTP/2 request will pass through to the …

`linera-service`: export a `grpc-web`–compatible endpoint

---

examples/crowd-funding/tests/campaign_lifecycle.rs
examples/fungible/src/state.rs
examples/matching-engine/tests/transaction.rs

The fungible account leaves empty accounts in the map. This wastes space and makes it confusing to assert balances in tests, because there is an artificial difference between "zero" and "absent".
Always remove empty accounts.
The affected tests have been updated.

Remove empty fungible accounts.

---

linera-base/src/identifiers.rs
linera-core/src/worker.rs
linera-execution/src/execution.rs
linera-execution/tests/test_execution.rs

`update_execution_outcomes_with_app_registrations` iterates over a `HashMap`, which does not have the same order each time. That makes execution nondeterministic.
Use a `BTreeMap` instead.
Also include more information in the `IncorrectMessages` error to help debug problems like this in the future.
I ran into this problem in an extended matching engine integration test, which I will add in an upcoming PR.
Also, the `test_multiple_messages_from_different_applications` was updated.
- Introduced in https://github.com/linera-io/linera-protocol/pull/1486.

Fix non-deterministic RegisterApplications messages.

---

linera-base/src/data_types.rs

`NaiveDateTime::from_timestamp_opt` is deprecated. This causes `test_project_new` to fail in CI now because of the warning.
Use `DateTime::from_timestamp`.
The test passes now.

Remove deprecated NaiveDateTime::from_timestamp_opt.

---

examples/fungible/src/lib.rs
examples/matching-engine/src/contract.rs
examples/matching-engine/src/state.rs
examples/matching-engine/tests/transaction.rs
linera-service/tests/end_to_end_tests.rs

Currently the matching engine keeps all tokens on the order book chain. Owners have to claim them to get them back to their own chains.
This means the chain can't be used for atomic swaps: When closing the chain, the matching engine application does not have permissions to move those tokens back to their owners' chains. Users may also find it surprising or inconvenient in general.
Whenever an order is filled or cancelled, send the tokens to the owner's chain.
The integration test was updated.
- #305 

Send tokens back to owner chain when orders are filled or cancelled.

---

linera-service/src/cli_wrappers/wallet.rs

Some functions in the CLI wrappers keep retrying for almost seven minutes. That means that failing tests hang for that long until they finally print the line in which they failed.
Reduce this to 36 seconds.
This should still be enough time to not make the tests flaky.

Fail earlier in retrying CLI wrapper functions.

---

Cargo.lock
linera-witty-macros/src/unit_tests/wit_load.rs
linera-witty-macros/src/wit_load.rs
linera-witty/Cargo.toml
linera-witty/src/runtime/error.rs
linera-witty/tests/wit_load.rs

While debugging the issue fixed by #1716, I ran into the `linera_witty::RuntimeError::InvalidVariant` error. However, it wasn't as useful as it could be, because it didn't show what invalid value it read nor which type is was trying to load.
Add some more information to the error variant, so that it can show what type was being loaded and what the invalid discriminant was.
A unit test was added for the error scenario.
Nothing needed, because Witty isn't used yet.

Improve invalid discriminant error

---

linera-indexer/example/tests/test.rs
linera-service-graphql-client/tests/test.rs
linera-service/tests/end_to_end_tests.rs

The introduction of the service led to larger runtime for the tests. We want to downgrade the usage of RocksDb so that the CI costs and time in second become more manageable
We kept the `RocksDb` in the Database for the following reasons:
* The `RocksDb` is used in the `linera` program and replacing it is not completely straightforward.
* The `service` is not working for the `matching_engine` and we want to have the `matching_engine` tested by at least one system.
In addition the `service` was used to replace for two tests that were overlooked in the previous PR.
This is only a first step in the reduction of the cost of the CI for the end-to-end tests.
The CI is the point of it.
Not relevant.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#revi …

Reduce usage of RocksDB in tests

---

examples/matching-engine/src/contract.rs
examples/matching-engine/src/lib.rs
examples/matching-engine/src/state.rs
examples/matching-engine/tests/transaction.rs
linera-sdk/src/test/integration/block.rs

To use the matching engine as an atomic swap application we need to make sure that nobody can close the chain while there are still users' tokens on it.
Add a `CloseChain` operation to the matching engine: If the application has the permission to do so, it will close the chain, but first it will cancel all orders and send the tokens back to the users.
If the matching engine is also configured to be the only one authorized to execute operations, no chain owner can close the chain using the system operation. They have to go through the matching engine, ensuring that the tokens get sent back.
The test was updated; instead of directly cancelling all remaining bids, some of them are only cancelled implicitly through `CloseChain`.
- #305 
- [reviewer …

Add a CloseChain operation to the Matching Engine.

---

linera-core/benches/client_benchmarks.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/unit_tests/faucet.rs

After PR on services, some refactoring opportunities were identified and are now done here.
* Renaming the input `i/j` in `local_net` as `validator/shard`.
* Renaming the `MakeMemoryStorage` as `MemoryStorageBuilder` and similar.
CI should do it since no functionality is introduced.
No impact.

Some refactor

---

CLI.md
Cargo.lock
linera-core/src/client.rs
linera-service/Cargo.toml
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/tests/end_to_end_tests.rs

Explaining how to use the matching engine example for atomic swaps in the README will be much easier if we can just change the ownership of the existing chain, rather than create a new chain and another application.
Also, changing a chain's ownership from the command line should be possible anyway.
Add a `change-ownership` command.
To make it more consistent with the `open-multi-owner-chain` command, a few parameters are renamed.
A test was added.
- #305 

Add a change-ownership command.

---

linera-core/src/unit_tests/wasm_client_tests.rs
linera-views/src/test_utils/mod.rs
linera-views/tests/map_view_tests.rs
linera-views/tests/store_tests.rs

The CI is taking a lot of time. This costs money and also hinders development.
The following are done:
* The size of the scenarios in the `num_reads` is decreased which makes the test 10 times faster.
* The wasmer tests `create_application`, `run_application_with_dependency`, `user_pub_sub_channel` and `cross_chain_message` are all taking more than 60s. But they are very similar and the storage used is not key. Therefore they are marked as `#[ignore]`.
* The `map_view_mutability` test is reduced in size.
Random tests are useful of course and they are kept. However, the probability of catching a bug decreases as the size increases. Therefore it does not make sense to have such large test cases. They are useful in development but not in CI.
That is precisely the point.
- …

Several adjustments to accelerate the CI.

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
examples/non-fungible/Cargo.toml
examples/non-fungible/src/contract.rs
examples/non-fungible/src/lib.rs
examples/non-fungible/src/service.rs
examples/non-fungible/src/state.rs
linera-service/Cargo.toml
linera-service/tests/end_to_end_tests.rs

We need an NFT app
* Created a new `NonFungibleTokenAbi`, it has `Mint`, `Transfer`, `Claim` operations, `Transfer`, `Claim` messages, `Mint`, `Transfer`, `Claim` application calls.
* No sessions support, specially as these are going away soon
* NFT app has a local state of the NFTs, keyed by token ID. Token ID is deterministically generated by hashing `chain_id`, `application_id`, and the NFT's metadata.
Created an e2e test, so CI
* Write `README`
* NFT UI?

Non Fungible Token App

---

linera-execution/src/wasm/wasmtime.rs

Wasmtime's `consumed_fuel` returns the total amount of fuel consumed since execution started, instead of the amount of fuel consumed since the last time fuel was added. That value was incorrectly used to consume fuel from the runtime, so fuel consumption values in Wasmtime was incorrect for any application that performed system API calls.
Obtain the remaining fuel and manually calculate how much fuel was consumed.
Unfortunately we're currently using an old version of the `wasmtime` dependency, so there isn't any simple API to get the remaining fuel. The way to do it with the current version used is to call `consume_fuel(0)`, because it returns the amount of remaining fuel. However, if the fuel amount is zero, it returns an error instead, so a workaround is used to add one unit of fuel …

Fix Wasmtime fuel consumption calculation

---

CLI.md
examples/matching-engine/README.md
examples/matching-engine/src/lib.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

We want to demonstrate how to do atomic swaps on Linera.
Extend the Matching Engine README to show how to configure the chain for atomic swaps.
For convenience, and consistency with other commands, make the `--chain-id` argument for `change-application-permissions` optional.
The README is tested by `test_script_in_readme`. I also tried it manually.
- Closes #305 

Add atomic swaps to Matching Engine README.

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-service/src/chain_listener.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs

We are using `Arc<Mutex<ChainClient<_, _>>>` like an object in several places, but have to use `Self::foo(this)` syntax because `Mutex` is not defined in our own crates. Some of these functions also have unnecessarily complicated trait bounds.
Create an `ArcChainClient` wrapper and make these functions methods of it. Simplify the trait bounds.
(Only refactoring.)

Add an ArcChainClient wrapper

---

examples/non-fungible/README.md
examples/non-fungible/src/contract.rs
examples/non-fungible/src/lib.rs
examples/non-fungible/src/service.rs
examples/non-fungible/web-frontend/src/App.js
linera-service/tests/end_to_end_tests.rs

This was an oversight on the initial implementation, we need to make sure that we're authenticated as who we expect to be authenticated as
Add `minter` to the `mint` mutation, and check authentication
e2e tests + I've also tested in the web UI to make sure that if we're connected to just one node service, mutations from a different account will fail authentication

Adding minter to mint mutation for NFTs

---

.github/workflows/scylladb.yml
Cargo.lock
examples/Cargo.lock
linera-service/tests/end_to_end_tests.rs
linera-storage-service/Cargo.toml
linera-storage-service/proto/key_value_store.proto
linera-storage-service/src/client.rs
linera-storage-service/src/common.rs
linera-storage-service/src/server.rs
linera-storage-service/tests/store_test.rs
linera-views/src/test_utils/mod.rs

The service store is limited to 4M in size which is a classic limit of GRPC server. This prevents
having the matching engine test working on `service`. Here we address this limitation.
The following steps were done:
* The submission of the write_batch was changed so that now we incrementally submit the batch. In the case of big values, we split into some blocks which are then put together.
* We did not use the value-splitting mechanism since we are in full control of both sides of the divide. The lack of use of the value-splitting gets us better speed.
* The limitation of 4M also applies to the returning values. That limitation is for tonic, which may be specific to tonic. This limits to the `read_value_bytes`, `read_multi_values_bytes`, `find_keys_by_prefix`, and …

Make the `linera-storage-service` handle requests and replies that have size higher than 4M.

---

linera-service/src/grpc_proxy.rs

To my great embarrassment, in https://github.com/linera-io/linera-protocol/pull/1735 I in fact added gRPC-Web support to the wrong service on the proxy (the internal notifications service, instead of the external-facing validator node service).
Fix it.
As in the original PR.  The new test in https://github.com/linera-io/linera-protocol/pull/1738 would catch it. 
No special handling required.

`linera-service`: enable gRPC-Web on the right service

---

Cargo.lock
Cargo.toml
linera-rpc/Cargo.toml
linera-rpc/build.rs
linera-rpc/src/grpc/mod.rs
linera-rpc/src/grpc/server.rs
linera-rpc/src/lib.rs
linera-service/Cargo.toml
linera-service/src/grpc_proxy.rs

In debugging and developing against gRPC services, reflection is very helpful.  For example, it allows for much easier use of tools like `grpcurl` when the correctness of implementation of the relevant services is unknown. 
Use the `tonic-reflection` crate to add reflection to both the internal validator node service and the `linera-service` gRPC proxy.
CI for regressions.
Technically adds API (backwards-compatible but forwards-incompatible), so we could bump the minor version number. 

`linera-service`: implement gRPC reflection

---

linera-service/src/cli_wrappers/docker.rs

```
warning: `to_string` applied to a type that implements `Display` in `format!` args
```
Remove the redundant `.to_string()`.

Remove redundant to_string call.

---

linera-core/src/client.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs

Currently we pass ownership of the `ChainClient` into `apply_client_command`, and then into the closure, and back out again, due to lifetime issues.
Use `ArcChainClient` instead.
This doesn't add new functionality.

Make apply_client_command use an ArcChainClient.

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
flake.nix
linera-core/Cargo.toml
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/updater.rs
linera-execution/src/lib.rs
linera-rpc/Cargo.toml
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/grpc/mod.rs
linera-rpc/src/grpc/node_provider.rs
linera-rpc/src/grpc/pool.rs
linera-rpc/src/grpc/transport.rs
linera-rpc/src/lib.rs
linera-rpc/src/mass_client.rs
linera-rpc/src/node_provider.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/node_provider.rs
linera-rpc/tests/transport.rs
linera-service/src/chain_listener.rs
linera-service/src/faucet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs

Atop #1801, #1802.
The client half of https://github.com/linera-io/linera-protocol/issues/1609.
When compiling with `web`, replace our existing gRPC client with a Wasm-compatible gRPC-Web–based client using `tonic-web-wasm-client`.
Since [browser objects are neither `Send` nor `Sync`](https://github.com/rustwasm/wasm-bindgen/issues/2753), a large part of this work is then to enable non–`Send` equivalents of various traits for structs containing non–`Send` objects.  `linera-core` in particular now never assumes that the client struct is `Send`.  `linera-service`, however, does.  In order to enable this, I have used [`trait-variant`](https://crates.io/crates/trait-variant) to construct, as automatically as possible, local and non-local variants of relevant traits.
Task list:
As part of this …

Web client

---

examples/amm/src/contract.rs
examples/crowd-funding/src/contract.rs
examples/fungible/src/contract.rs
examples/matching-engine/src/contract.rs
examples/meta-counter/src/contract.rs
examples/native-fungible/src/contract.rs
examples/non-fungible/src/contract.rs
linera-sdk/src/contract/runtime.rs

Having side-effects from `Drop` is not idiomatic Rust, so sending should be made explicit.
Split the original `send_message` API in two: the original that sends the message immediately without any extra configuration, and a new `prepare_message` that returns the builder but requires a call to `send_to` in order to send the message.
API refactor, so existing tests should catch any regressions.
Changes the SDK API, so

Refactor guest runtime API to send messages

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/wasm-tests/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage-service/Cargo.toml
linera-storage/Cargo.toml
linera-version/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml
linera-witty/test-modules/Cargo.toml

We want to upgrade Devnet.
Set the crate versions to 0.10.0, so we can publish them and deploy the upgraded Devnet.
Only version changed.

change protocol version to 0.10.0 on the main branch

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-service/src/chain_listener.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/tests/end_to_end_tests.rs

CLI commands don't work in all cases in single-leader mode.
Add an end-to-end test and fix the issues:
* `process_pending_block_without_prepare` should not fail with a "conflicting proposal" error if there is a timeout for the current round. Instead, it should return `WaitForTimeout`.
* `process_inbox` and `apply_client_command` need to actually listen for notifications from the validators, so that they know when a new round begins. Currently they only listen to the local node, but the local node doesn't get updated automatically.
* Synchronize from the validators and return a notification stream from `ChainClient::listen`: Aside from test code, this is what we want at all call sites.
* Update the wallet when `watch`ing if we get notifications about new blocks.
* When we try to finalize a …

Fix round notification handling for CLI commands.

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/wasm-tests/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage-service/Cargo.toml
linera-storage/Cargo.toml
linera-version/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml
linera-witty/test-modules/Cargo.toml

Version 0.10.0 has been published, so the main branch contains work for 0.11.0 now.
Update the `linera-*` crate versions.
(Only a version change.)

change protocol version to 0.11.0 on the main branch

---

linera-version/build.rs
linera-version/src/version_info/type.rs

I think that `PWD`, when building a build script, used to be set to the directory containing `build.rs`.  We used this fact to run `cargo manifest`, getting information about the current package for `linera-version`.  However, it seems that if this was ever the case, it no longer is, breaking `cargo install`.  We should probably be relying on `CARGO_MANIFEST_DIR` instead.
Replace `PWD` with `CARGO_MANIFEST_DIR` when building `linera-version`.
`(cd /tmp; cargo install --path /path/to/linera-protocol/linera-service)`
This is a hotfix.  It shouldn't break any working flows.
- [old discussion about the behaviour of `PWD` vs `CARGO_MANIFEST_DIR`](https://internals.rust-lang.org/t/build-scripts-pwd-and-cargo-manifest-dir-strangeness/16833)
- [documentation about Cargo environment variables for …

`linera-version`: use `CARGO_MANIFEST_DIR` instead of `PWD`

---

linera-service/tests/end_to_end_tests.rs

`unwrap_or_default` can hide errors
Remove it
CI

Stop using unwrap_or_default in e2e tests

---

linera-witty/src/type_traits/implementations/std/tuples.rs

The previous `unit` native type was removed from the Component Model.
It is still possible to represent a unit type using an empty tuple type `tuple<>`.
Not currently used, but was manually tested while getting `linera-execution` to work with Witty.

Use `tuple<>` for the unit type

---

linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql
linera-views/src/graphql.rs

When we added the ability to do more complex queries on our `linera-views` data structures, we introduced several intermediate data types in the GraphQL that need unique type names.  GraphQL type names are a lot more syntactically restrictive than Rust type names, so we introduced a very basic name mangling scheme that is sufficient to cover all the cases originally covered by the `GraphQlView` derive macro and preserves human-readability. 
However, recently, we've seen an influx of issues in which people want to use more complex types in their `async_graphql::SimpleObject` types that cause these GraphQL type names to collide, resulting in a build error.
Introduce a more unique naming scheme by appending a hash of the Rust type name to the generated GraphQL type name.  This mangling …

`linera-views`: avoid generating duplicate GraphQL type names

---

examples/fungible/src/contract.rs

The `Credit` message was being sent from the Fungible Token application without tracking. This meant that if the message failed to be delivered, the transferred tokens would not be returned to the sender.
Track the sent `Credit` message.
TODO

Fix `Credit` message tracking in Fungible Token

---

CLI.md
Cargo.lock
linera-core/Cargo.toml
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-service/Cargo.toml
linera-service/src/linera/client_options.rs

Users may not always want to automatically accept all incoming messages when running a CLI command. Once fallback owners are implement, validators will also use `linera service` to act as chain owners, and they will want to reject most messages.
Add a configurable message policy to the client options, so you can choose to:
* ignore all messages (except `OpenChain`),
* reject and skip as much as possible, or
* accept all messages (the default).
A client test was added.
- Closes https://github.com/linera-io/linera-protocol/issues/1842.
- See also: https://github.com/linera-io/linera-protocol/issues/1621

Add a configurable policy for incoming messages.

---

linera-views/src/dynamo_db.rs

The futures returned by `aws-sdk-dynamodb` are large, and frequently lead to stack overflow in `linera-views::dynamodb`.
Box them using `futures::FutureExt::boxed` to move them to the heap before `await`ing them.
CI.
No user-visible changes.

`linera-views::dynamodb`: box `aws-sdk-dynamodb` futures

---

Cargo.lock
examples/Cargo.lock
linera-sdk/src/views/system_api.rs
linera-storage-service/Cargo.toml
linera-storage-service/src/client.rs
linera-views/Cargo.toml
linera-views/src/batch.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/journaling.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lru_caching.rs
linera-views/src/memory.rs
linera-views/src/metering.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/test_utils/mod.rs
linera-views/src/value_splitting.rs

In order to support non-`Send` Linera view stores on the Web, we need local variants of the store traits that don't require `Send`.
Replace `async-trait` with native AFIT, and use `trait-variant` to automatically create local and non-local variants.
CI build should catch regressions.
This changes the trait interfaces, which is a backward-incompatible change (for people using `linera-views` directly).

`linera-views`: add local variants of store traits

---

examples/Cargo.lock
linera-core/Cargo.toml
linera-core/src/client.rs
linera-service/Cargo.toml

`linera-execution` already depends on `clap` and works fine with Wasm and in the browser. `linera-core` depends on `linera-execution` anway, so `clap` is always a dependency.
Remove the `clap` feature and unconditionally derive `clap::ValueEnum` for `MessagePolicy`.
Doesn't change any logic.
- #1842

Make clap non-optional in linera-core.

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-views/Cargo.toml
linera-views/build.rs
linera-views/src/indexed_db.rs
linera-views/src/lib.rs
linera-views/tests/store_tests.rs

#1610 
Add an IndexedDB storage backend to `linera-views`.
This branch uses a patched fork of `indexed_db_futures` because of https://github.com/Alorel/rust-indexed-db/pull/34, which will otherwise break our non-Web Wasm build.
A set of tests is added to CI.
No user-visible changes (yet).
- Fixes #1610.

IndexedDB views backend

---

.github/workflows/documentation.yml

Sometimes if we merge two PRs quickly they will race to push to our GitHub pages, causing one to fail.
Make the concurrency group on the job coarser so that if a job is already running, cancel it before attempting a publish. 
CI on `main`.  We could deliberately merge two PRs in quick succession?
Shouldn't change anything from the outside.
- [GitHub workflow concurrency reference](https://docs.github.com/en/actions/using-jobs/using-concurrency)

`.github/workflows/documentation`: supersede in-progress publishes

---

linera-witty/src/type_traits/implementations/std/collections.rs
linera-witty/src/type_traits/implementations/std/mod.rs
linera-witty/src/type_traits/implementations/std/time.rs
linera-witty/src/type_traits/implementations/tests.rs

As part of recent additions to the system API, we need to send `std::time::Duration` and `std::collections::BTreeMap` through the WIT interface.
Implement the Witty types (`WitType`, `WitLoad` and `WitStore`) for those types.
Added some round-trip unit tests for the new types.

Implement Witty traits for `BTreeMap` and `Duration`

---

Cargo.lock
linera-witty/Cargo.toml
linera-witty/build.rs
linera-witty/src/type_traits/implementations/log.rs
linera-witty/src/type_traits/implementations/mod.rs
linera-witty/src/type_traits/implementations/tests.rs

Contracts and Services support logging messages, specifying a log level using the `log::Level` type. This type needs to be available in the WIT boundary.
Implement the Witty traits for the `log::Level` type, but place them behind a feature gate so that the `log` dependency is only included if requested.
Added a round-trip unit test for the `log::Level` type.

Implement Witty traits for `log::Level`

---

linera-service/tests/end_to_end_tests.rs

Many of the `async` tests panic when an error occurs instead of propagating the error using the try operator (`?`). The reasoning for this was that panics preserve the backtrace. However, if `anyhow::Error` is used, it automatically captures and displays a backtrace as well.
If the try operator (`?`) is used instead of panics, the code becomes slightly less noisy.
Change the end-to-end tests to return `anyhow::Result<()>` and replace `Result::unwrap` calls with the try operator.
Two tests were temporarily changed to fail, to test if CI shows the backtrace even if the try operator is used.
Only affects tests, so nothing needed.

Use `anyhow::Error` in end-to-end tests

---

CLI.md
linera-service/src/config.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

We need a way to forget the keys from a chain
Create a `linera wallet forget-keys` command
`linera wallet show` before:
`linera wallet show` after:

linera wallet forget-keys command

---

CLI.md
linera-service/src/config.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

We need a way to forget a chain from a wallet
Create a `linera wallet forget-chain` command
`linera wallet show` before:
`linera wallet show` after (chain not there anymore):

linera wallet forget-chain command

---

linera-rpc/src/grpc/mod.rs

Some applications in practice are already limited by the gRPC message size.
This will be addressed by implementing pagination for chain infos, and splitting out bytecodes in the future.
Increase the gRPC message size for now.
- https://github.com/linera-io/linera-protocol/issues/1850

Increase the gRPC message size limit to 16 MiB.

---

linera-service/tests/end_to_end_tests.rs

#1878 incorrectly added a newline typo between one of the end-to-end tests and its attributes, deviating from the formatting convention.
Fix the formatting so that there isn't a newline separating the test function and its attributes.
Whitespace change, so no new coverage is needed.

Remove newline incorrectly added between the test and its attributes

---

linera-base/src/ownership.rs
linera-chain/src/manager.rs
linera-core/src/worker.rs

In the chain manager, whenever `leader_timeout`, `locked` or `proposed` changes, that potentially starts a new round, in which case the round timeout resets. We pass into `update_timeout` the round that is ending and then check whether that is actually at least the current one.
In some cases this requires computing the "previous round"—or rather the highest round that _could_ have been the previous one. This is confusing and unnecessarily complicated, and would be further complicated by the new `Round` type we will need for fallback owners.
Add a `current_round` field to the `ChainManager`. After each change to one of the mentioned fields, call `update_current_round` to update that and the timeout. Remove `previous_round`.
The current round is already checked in and relied on by several …

Simplify current_round computation; remove previous_round.

---

linera-witty/src/type_traits/register_wit_types.rs
linera-witty/tests/wit_type.rs

When generating WIT snippets, the necessary types need to be collected from a dependency graph. To prevent cycles and repeated declarations, a `HashMap` was used to ensure every WIT type is only declared once. However, `HashMap` has a random order, so regenerating the same snippet would lead to a different order of WIT types inside it. This made it hard to see if the WIT file was up-to-date, which would make it hard to use in tests for example.
Use a `BTreeMap` instead of a `HashMap` to ensure that multiple runs registering the same types have the same order.
Some tests already sorted the declarations using a `BTreeMap`, so the extra sorting was removed and the test should now cover the generated order of the types.
Internal changes, so nothing is needed.
- [reviewer …

Ensure WIT types are registered in a deterministic order

---

linera-execution/src/wasm/wasmer.rs

Running AI models in WASM requires simd128 instructions. The `Singlepass` compiler does not support this.
Change to the `Cranelift` compiler backend for services.
Existing tests should capture any potential regressions.

Service engine uses Cranelift instead of Singlepass

---

examples/matching-engine/README.md
examples/matching-engine/src/lib.rs
linera-core/benches/client_benchmarks.rs
linera-core/src/client.rs
linera-core/src/lib.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-service/src/unit_tests/faucet.rs

We use `test_case` in some places, but not in `worker_tests`, which has a lot of boiler plate. We also use `unwrap()` in lots of tests where we could use `anyhow`, which also supports backtraces.
Use `test_case` and `anyhow`. Move `client::client_test_utils` to `test_utils`.
I tried it locally for the memory and RocksDB cases. Let's double-check that the tests are still executed in the CI logs once they're done.

Use test_case in worker_tests.

---

linera-execution/src/wasm/mod.rs

Wasmer errors were not being displayed resulting in making debugging applications difficult.
Display Wasmer error in the error message.
Has been tested manually.

Display error in WasmExecutionError::ExecuteModuleInWasmer

---

.github/workflows/rust.yml
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/src/server.rs
linera-service/src/storage.rs
linera-storage-service/src/server.rs

`rocksdb` is an optional flag, but the build fails without it.
Fix it.
There are still a few warnings if neither `rocksdb` nor `kubernetes` are enabled, but with `kubernetes` alone there are no warnings, and the build succeeds now.
I added this to CI:
```bash
cargo clippy --no-default-features --features kubernetes --locked
```

Fix the build without RocksDB.

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

The Matching Engine end-to-end test would sometimes fail in CI. This was caused by a race condition in the test, where some queries to node services to obtain token balances for the final assertions raced the notifications to the node services about the blocks that send the final tokens.
Wait until the node services receive the blocks that send the messages, so that they can execute them and receive the remaining tokens.
I managed to increase the frequency of the race condition significantly by adding a delay when proxying the notification to the node service, just before the following line:
https://github.com/linera-io/linera-protocol/blob/538ce38b3f9a1c41c9dcd4a957f959b66fa2b5cf/linera-service/src/grpc_proxy.rs#L398
After the fix, I could not reproduce the error.
- …

Wait for refund messages before final assertions in Matching Engine end-to-end test

---

.github/workflows/rust.yml
linera-service/src/linera/main.rs
linera-service/src/linera/net_up_utils.rs

There are some warnings when building with `--no-default-features`.
Move the functions that are used only with the `kubernetes` or `rocksdb` feature to a separate module.
I added this to CI:
```bash
cargo clippy --no-default-features --locked
```

Fix warnings when building with --no-default-features.

---

linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-core/src/data_types.rs
linera-core/src/worker.rs
linera-rpc/tests/format.rs
linera-service-graphql-client/src/service.rs

The `linera_chain::manager` module has a lot of documentation, which doesn't appear e.g. on docs.rs, because the module is private.
Make the module public.
(no new logic)

Make linera_chain::manager public, so the docs get published.

---

linera-witty-macros/src/lib.rs
linera-witty-macros/src/wit_export/function_information.rs
linera-witty-macros/src/wit_export/mod.rs
linera-witty-macros/src/wit_import.rs
linera-witty-macros/src/wit_interface.rs
linera-witty/src/lib.rs
linera-witty/src/test.rs
linera-witty/src/wit_generation/mod.rs
linera-witty/tests/common/wit_interface_test.rs
linera-witty/tests/reentrancy.rs
linera-witty/tests/wit_export.rs
linera-witty/tests/wit_import.rs

Witty will allow generating WIT files from Rust items. To achieve that goal, it needs to generate WIT interfaces.
Create a `WitInterface` trait that provides the WIT snippets and type dependencies necessary for the interface. Automatically generate the implementation of this trait from `#[wit_export]` and `#[wit_import]` macros.
The expected snippets are now checked in the integration tests.
Only affects Witty, so nothing needed.
- This is part of #906 but does not close it.

Create a `WitInterface` trait to allow creating of WIT interface snippets

---

CLI.md
linera-base/src/data_types.rs
linera-base/src/ownership.rs
linera-base/src/unit_tests.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/inbox.rs
linera-chain/src/manager.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-execution/src/committee.rs
linera-execution/src/wasm/conversions_from_wit.rs
linera-execution/src/wasm/conversions_to_wit.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/contract_system_api.wit
linera-sdk/src/contract/conversions_from_wit.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/linera/client_options.rs
linera-service/src/node_service.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

We plan to support both public chains—where the validators are always the block proposers—and a fallback mode—where the validators take over proposing blocks if the chain owners fail to include an unskippable (i.e. tracked or protected) message for a long time.
Add a `Round::Validator(u32)` variant for rounds in which a validator is the leader. These come after all other round types.
If an unskippable message is in the inbox for longer than `fallback_duration`, the validators will sign a timeout certificate for the last non-`Validator` round, and effectively make themselves the leaders. If `fallback_duration` is zero, they are always leaders.
A worker test was added.
- …

Add fallback/public mode to the chain manager.

---

Cargo.lock
examples/Cargo.lock
linera-execution/Cargo.toml
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/service_system_api.wit
linera-sdk/src/service/runtime.rs

We would the Service to download blobs from the internet.
Add a `fetch_url` API which will return a vector of bytes given a URL string. Here are some extra considerations:
1. How can we make this API more general?
i.   Should we take arbitrary `reqwests`
ii.  Should we provide our own comprehensive HTTP API?
2. Use `url::Url` instead?

Added a Service API to fetch a blob of bytes from a URL

---

.github/workflows/rust.yml
Cargo.lock
examples/Cargo.lock
linera-execution/Cargo.toml
linera-execution/src/lib.rs
linera-execution/src/wasm/entrypoints.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/system_api.rs
linera-views/Cargo.toml
linera-views/src/batch.rs
linera-witty/src/runtime/error.rs
linera-witty/src/runtime/wasmtime/export_function.rs
linera-witty/src/runtime/wasmtime/function.rs

Witty allows specifying WIT interfaces using Rust code, and supports different host Wasm runtimes. We are currently migrating our code to use Witty.
Create the system API interfaces for contracts and services (and the view system APIs, which will later be refactored to more closely follow how the host divides the system APIs) and create the contract and service entrypoints.
The added functionality is not used yet, but the intention is to replace existing functionality later one, and existing tests should catch regressions.
For now, only new (and temporarily unused) functionality is added, so nothing is needed.

Use Witty to declare the application interfaces

---

Cargo.lock
Cargo.toml
linera-service/Cargo.toml
linera-service/src/config.rs
linera-service/tests/end_to_end_tests.rs

The [`file-lock`](https://crates.io/file-lock) crate only supports POSIX operating systems, which prevents `linera-service` from compiling on Windows.
Use the `fs4` crate instead, creating a custom `FileLock` wrapper to keep the same API.
I looked into other options, but they all seemed to require further changes to our code, because usually they have a guard with a lifetime linking it to the `&mut File`. While this makes sense in a lot of scenarios, it would better match our current code if there was something like `lock_owned()`, but I couldn't find a crate that supported that.
One minimal integration test was added.
Internal refactor, so in theory nothing needed, but it would be nice to release a patch version with this change.
- [reviewer …

Replace `file-lock` dependency with `fs4` in order to support non-POSIX operating systems

---

linera-witty/src/runtime/wasmer/mod.rs
linera-witty/tests/common/test_instance.rs

The `InstanceBuilder` type in Witty allows creating a Wasm module instance for running with the Wasmer runtime. It had a parameter that took ownership of the Wasmer `Engine`, but there's no need for taking ownership. Not taking ownership also allows the `Engine` instance to be reused, which is something we do in `linera-execution`.
Use a shared reference instead of taking ownership.
No new functionality added, so no new coverage is needed.
Changes are internal to Witty, so nothing needed.

Receive `wasmer::Engine` by reference in `InstanceBuilder` constructor

---

linera-service-graphql-client/tests/test.rs
linera-service/src/chain_listener.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/config.rs
linera-service/src/lib.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/schema_export.rs
linera-service/src/unit_tests/faucet.rs
linera-service/src/wallet.rs
linera-service/tests/end_to_end_tests.rs

Writing tests (e.g. for https://github.com/linera-io/linera-protocol/issues/1906) would be easier if the `WalletState` didn't require being backed by a file.
Make `Wallet` (formerly `InnerWallet`) public, move most methods from `WalletState` to it, and make `ClientContext::wallet` return that.
No logic was changed; this will simplify writing tests in the future.

Make Wallet public and usable in tests with ClientContext.

---

linera-witty/src/runtime/wasmer/mod.rs

When using Witty to prepare a Wasm module to run with the Wasmer runtime, it is sometimes useful to access the `Store` and the `wasmer::Instance` to do some Wasmer specific operations.
Add some additional Wasmer-specific getter methods to access the `wasmer::Instance` and the `Store`.
No additional functionality is being added, and existing tests should catch any regressions.

Add some Wasmer specific getters to Witty

---

.github/workflows/rust.yml
Cargo.lock
examples/Cargo.lock
linera-execution/src/lib.rs
linera-execution/src/wasm/mod.rs
linera-sdk/Cargo.toml
linera-sdk/src/bin/wit_generator.rs
linera-sdk/src/lib.rs
linera-sdk/src/mock_system_api.rs
linera-sdk/wit/contract-entrypoints.wit
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/contract.wit
linera-sdk/wit/mock-system-api.wit
linera-sdk/wit/service-entrypoints.wit
linera-sdk/wit/service-system-api.wit
linera-sdk/wit/service.wit
linera-sdk/wit/unit-tests.wit
linera-sdk/wit/view-system-api.wit

With Witty, the source of truth for the WIT interface is the Rust code. Witty can then be used to generate the WIT files that `wit-bindgen` can use inside the applications. But this requires a custom binary to actually generate the needed WIT files, and they must also be kept up-to-date with the Rust source of truth.
Create a new binary in `linera-sdk` that generates the WIT files for the SDK. The same binary can also check if the files are up-to-date with its expected contents.
A new CI step was added to run the binary to check if the WIT files are up-to-date.
The mock system API was also rewritten to use Witty, so that its WIT files can be generated.
I manually tested if the binary returns a non-zero status code if the files differ from their expected contents.
The WIT files aren't used …

Generate WIT files using a custom binary

---

linera-base/src/data_types.rs
linera-core/src/client.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-service/src/faucet.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

For `ChainListener` unit tests we will need to use the `TestClock`, and `sleep` calls need to wake up whenever the simulated time is set high enough.
Add `sleep` to `TestClock`, which only waits until it receives a value from a channel. `TestClock::set` and `add` send to these channels accordingly.
Inside `TestClock` we use a standard mutex, not an asynchronous one, since the guard is never held across an `await` point. (And it would be ironic if `current_time` was `async`!)
This will be used in tests in a later PR.

Add TestClock::sleep to make sleeps respect simulated time.

---

linera-execution/src/wasm/system_api.rs
linera-sdk/wit/service-system-api.wit

The `fetch_url` service system API is fairly new, and unfortunately was left out of the new `ServiceSystemApi` type that exports the APIs using Witty.
Add the method to `ServiceSystemApi` and regenerate the WIT files (~but first check if CI catches the missing update to the WIT files~ Done).
The API will be covered by an AI demo.
The `ServiceSystemApi` and new WIT files aren't used yet, so nothing is needed.

Add `fetch_url` to `ServiceSystemApi` type exported by Witty

---

.github/workflows/rust.yml
Cargo.toml
linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/remote_net.rs

`cargo check-all-features` currently fails due to `proptest` requiring either `std` or `alloc` (thanks @Twey for pointing that out), and prints a few warnings about `remote_net`. 
Use `proptest` with default features, and make the whole `remote_net` module test-only.
`check-all-features` without `--all-targets` was added to CI.

Run check-all-features also without --all-targets.

---

linera-core/src/unit_tests/test_utils.rs
linera-service/src/cli_wrappers/local_net.rs
linera-storage-service/src/child.rs
linera-storage-service/tests/store_test.rs

The function `get_free_port` is returning a string which is not what one expects.
Introduce a `get_free_endpoint` function that returns the endpoint.
Change `get_free_port` so that it now returns the port.

Rename the `get_free_port` and introduce one for endpoint.

---

examples/amm/README.md
examples/amm/src/contract.rs
examples/amm/src/lib.rs
examples/amm/src/state.rs
linera-sdk/src/abis/fungible.rs
linera-service/tests/end_to_end_tests.rs

Right now the tokens stay in the AMM chain, but they shouldn't. They should be sent back to the proper chains.
To do this, we had to do a few things:
- We had to redesign the AMM from Swaps executed remotely, Adding/Removing liquidity executed locally to Swaps and Adding liquidity executed remotely, removing liquidity executed locally
- Implemented a concept of shares based on the amount of liquidity that you add. You also can't remove more liquidity than you added now
- Improved the e2e tests to cover all these different cases
e2e tests

[amm] Send tokens back to owner's chains

---

examples/amm/README.md
examples/amm/src/lib.rs
examples/amm/src/service.rs
linera-service/tests/end_to_end_tests.rs

Right now we have this `operation` mutation for no reason. Not sure why I ever did it like that tbh
Use `GraphQLMutationRoot` instead. Much cleaner and simpler.
CI

Remove redundant operation mutation from AMM

---

linera-core/src/worker.rs

While handling a cross-chain request confirming that the recipients have been update, some fallible operations are performed. If one of them fail, the changes to the chain state are reverted, but the notification of some delivery notifiers is not. This means that the delivery notifiers might receive incorrect notifications in some edge cases.
Only notify the delivery notifiers after all fallible operations have succeeded.
Tests should be written for this, but it not trivial to induce storage errors in order to reproduce the scenario. Therefore issue #1934 was opened to write the test later.
Bug fix, so nothing needed except maybe releasing a new patch version.

Fix incorrect delivery notifications for rejected blocks

---

toolchains/build/rust-toolchain.toml

While using `async fn` in a trait without `async_trait`, I ran into a compiler warning that was a bit annoying. There is a way around it, by requiring that `Self: Sized`, but it seems like [the lint has been removed](https://github.com/rust-lang/rust/pull/120360) on the latest stable.
Update Rust to the latest stable version.
CI should catch any issues with the new Rust version.
If developers use the old version, they'll run into the same lint. It's not a blocker, but it is annoying and might be surprising. So I'd suggest

Update Rust to version 1.77.0

---

linera-chain/src/data_types.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-explorer/src/components/Block.test.ts
linera-explorer/src/components/Block.vue
linera-explorer/src/components/Blocks.test.ts
linera-explorer/src/components/Blocks.vue
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/test/integration/block.rs
linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql
linera-service-graphql-client/src/service.rs
linera-service/src/chain_listener.rs
linera-service/src/linera/main.rs

`ExecutedBlock` is a `Block` plus all the fields of a `BlockExecutionOutcome`. We will add more fields to that, so they would have to be added to both types.
Use `BlockExecutionOutcome` inside `ExecutedBlock` instead.
No changed logic.

Use BlockExecutionOutcome in ExecutedBlock.

---

linera-views/src/scylla_db.rs

Running a naked select over the entire `table_linera` table could yield a very large number of rows which are unecessary.
Just use `LIMIT 1` to perform the same logical operation more efficiently.
CI

Bounded the `exists` query for ScyllaDB

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
linera-sdk/src/contract/mod.rs
linera-sdk/src/contract/wit.rs
linera-sdk/src/lib.rs
linera-sdk/src/service/mod.rs
linera-sdk/src/service/wit.rs
linera-sdk/src/test/unit/wit.rs

Newer versions of `wit-bindgen` [support generating a macro to export the WIT functions](https://docs.rs/wit-bindgen/latest/wit_bindgen/macro.generate.html#exports-the-export-macro) and [exporting that macro](https://docs.rs/wit-bindgen/latest/wit_bindgen/macro.generate.html#options-to-generate). This allows the removal of the proxy functions between the applications and the SDK.
Update `wit-bindgen` to the latest version, export the macros used to export the contract and service entrypoints and remove the proxy functions.
This is a refactor, and existing tests should catch any regressions.
This makes an invisible change to the SDK API, so
- [reviewer …

Update `wit-bindgen` to 0.24.0

---

linera-sdk/src/contract/mod.rs

The contract state should only be stored when the contract instance requests it to be stored, or at the end of the transaction if it did not override `finalize`. However, the state was being stored after every execution of the contract, whether it wanted it or not.
Don't store the contract state automatically after every execution.
Issue #1956 was opened to track a test for this.
Fixes a bug without changing the API so:
- Need to bump the patch version number in the next release of the crates.

Remove incorrect store of the contract state

---

flake.lock

This keeps our Nix flake working, as the previous lock file is too old to know about Rust 1.77 (from [the Rust overlay we use](https://github.com/oxalica/rust-overlay)).
Bump the lock file for our Nix flake.
I have already used it locally.
No user-visible changes — except that Gitpod users and other consumers of our Nix flake will continue to be able to use it.

`flake.lock`: update to gain access to Rust 1.77

---

examples/native-fungible/src/contract.rs
examples/native-fungible/src/service.rs
examples/native-fungible/src/state.rs

An `EmptyState` helper type was recently introduced (#1950), which allows replacing the custom empty state type in the Native Fungible application.
Use the `EmptyState` type as the state for the Native Fungible application.
This is a refactor of the application, and the existing end-to-end test should catch any regressions.
Only changes the Native Fungible application, so nothing needed (assuming we are not deploying this application automatically on devnet).
Closes #968

Use `EmptyState` in Native Fungible application

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
linera-service/template/Cargo.toml.template
linera-witty/Cargo.toml
linera-witty/src/runtime/wasmer/mod.rs

`wasmer-vm` works only in a native interpreter environment (i.e. with `wasmer/sys`), and doesn't even compile for `wasm32-unknown-unknown`.  Thankfully, we only depend on `wasmer-vm` to get access to `StoreObjects`.
I have patched `wasmer` in https://github.com/wasmerio/wasmer/pull/4546 to expose the required `StoreObjects` struct, meaning we can now access `StoreObjects` without depending on `wasmer-vm`.  This change will be released in Wasmer 4.2.9, but until then we can patch our `wasmer` dependency to use the version from GitHub that merges my patch.
CI.

`linera-witty`: use `wasmer` from `git` to avoid `wasmer-vm` dependency

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-execution/Cargo.toml
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-sdk/wit/contract-system-api.wit

On the Web, we cannot use Wasmer's external metering support, as the browser Wasm implementation doesn't have support for it.
Instead, introduce:
- a function to the contract API that consumes fuel
- an instrumentation step implementation using the `wasm-instrument` crate that calls that function.
CI should cover it.
This seems to be compatible with existing Wasmer fuel calculation.  However, this behaviour is probably not to be relied upon.

`linera-execution`: use instrumentation for Wasmer metering

---

linera-witty-macros/src/wit_export/mod.rs
linera-witty/src/runtime/wasmer/export_function.rs
linera-witty/src/runtime/wasmer/mod.rs
linera-witty/tests/common/test_instance.rs

Since `wasmer::Instance` isn't `Send` on the Web, we need to avoid passing it in a `FunctionEnvMut`, which is required to be `Send`.
Thankfully, we didn't need to pass the `wasmer::Instance` in the first place.  `wasmer::Exports` is sufficient to access the exports — not their values, which requires an additional `Store`, but we're already passing in that store later.
CI.

Don't pass `wasmer::Instance` in a `wasmer::FunctionEnvMut`

---

Cargo.lock
examples/Cargo.lock
examples/amm/Cargo.toml
examples/crowd-funding/Cargo.toml
examples/fungible/Cargo.toml
examples/llm/Cargo.toml
examples/matching-engine/Cargo.toml
examples/meta-counter/Cargo.toml
examples/native-fungible/Cargo.toml
examples/non-fungible/Cargo.toml
examples/social/Cargo.toml
linera-sdk-derive/src/lib.rs
linera-sdk/src/contract/mod.rs
linera-sdk/src/lib.rs
linera-sdk/src/service/mod.rs
linera-service/template/Cargo.toml.template

Linera applications always had to depend on the `bcs` and `serde-json` crates, because some macros assumed that they were always available. This can be confusing to users because they need to add dependencies to crates that they don't use directly. It also leads to some lint complaints (from `cargo machete` for example).
Re-export the two crates from `linera-sdk` and update the macros to use those re-exports.
This changes the dependencies and touches the macros. Existing tests should cover these changes and catch any regressions.
This changes the SDK, so: …

Remove `bcs` and `serde-json` dependencies requirement for applications

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
linera-service/template/Cargo.toml.template
linera-witty/Cargo.toml

Git dependencies are a pain to maintain, as we have to patch every `Cargo.toml` that might be a workspace root.  Now that Wasmer has released a prerelease, we can just use that version instead.
Replace our Wasmer git dependency patch with a prerelease version.
CI.
None required.
- Closes https://github.com/linera-io/linera-protocol/issues/1966

Replace git `wasmer` dependency with prerelease

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs

Services should have a read-only view into the application state. However, it was previously possible to call `write_batch` from services and change the application state.
Remove access to `write_batch` from services, by making it only available in the `ContractRuntime` trait instead of the `BaseRuntime` trait which is shared by contracts and services.
In the `wasm` module the system API needs to be refactored to change the API and remove `write-batch` from the service WIT interface. However, the WIT system API interfaces need to be refactored in a larger way, so issue #1977 was opened to track it and a workaround was introduced in the meantime.
The bug was discovered by writing a unit test, which failed before this PR. After this PR, the test no longer compiles, so it wasn't included in …

Move `write_batch` into `ContractRuntime`

---

examples/amm/src/contract.rs
examples/counter/src/contract.rs
examples/crowd-funding/src/contract.rs
examples/fungible/src/contract.rs
examples/llm/src/contract.rs
examples/matching-engine/src/contract.rs
examples/meta-counter/src/contract.rs
examples/native-fungible/src/contract.rs
examples/non-fungible/src/contract.rs
examples/social/src/contract.rs
linera-sdk/src/contract/mod.rs
linera-sdk/src/lib.rs
linera-service/template/contract.rs.template

It's not immediately obvious that `finalize` is called at the end of a transaction, and that applications should implement it to persist their state across transactions.
Make the `finalize` method take ownership of `self`, so that there's a stronger hint that this is the last call to the `Contract` implementation type. Also rename `finalize` into `store`, so that it is clearer what is the main thing applications should do when finishing up. In order to be consistent, the `new` constructor was also renamed into `load`, which also makes it clearer that it's the ideal place to load the application state.
This is a refactor with the only change in behavior being the change in taking ownership of `self` when `store` (previously known as `finalize`) is called. This last change would lead to …

Rename `new` and `finalize` to `load` and `store`

---

linera-service/src/project.rs
linera-service/template/config.toml.template

Instead, the `wasm32-unknown-unknown` target should be specified manually.
Linera applications are built targeting `wasm32-unknown-unknown`, and previously unit tests also had to be executed targeting the same platform. This has since changed, and it doesn't make sense anymore to configure the default target for all `cargo` commands.
Don't generate the `.cargo/config.toml` file for new applications when running `linera project new`.
This change is "backwards compatible"-ish, because applications still compile and test correctly with or without this change, but the commands to build and test change, so:
- [reviewer …

Don't create `.cargo/config.toml` in new projects

---

.cargo/config.toml
examples/amm/README.md
examples/amm/src/lib.rs
examples/counter/README.md
examples/counter/src/lib.rs
examples/fungible/README.md
examples/fungible/src/lib.rs
examples/native-fungible/README.md
examples/native-fungible/src/lib.rs
examples/non-fungible/README.md
examples/non-fungible/src/lib.rs

The custom Wasm test runner was removed (#1974), and the custom Cargo configuration file to set the default target to Wasm for the examples was removed with it. However, some of the README files for the examples still assume that the default target is set to `wasm32-unknown-unknown`, and the custom test runner is still configured at the repository root.
Remove the custom test runner configuration and update the README files.
No code was added or removed, so no testing needed.

Clean-up example application READMEs and Cargo config

---

.github/workflows/rust.yml
linera-ethereum/Cargo.toml
linera-ethereum/README.md
linera-ethereum/src/lib.rs
linera-ethereum/tests/ethereum_test.rs

The Ethereum tests require the foundry (for anvil) and solc (the solidity compiler) for effective running.
Users working on different aspects may not want to enable those.
* The Ethereum tests are feature-gated.
* There is additional documentation in `linera-ethereum` on how to install Foundry and solc.
The CI has been changed but the same tests are being applied.
No changes.

Feature gate the Ethereum tests

---

linera-chain/src/data_types.rs
linera-chain/src/test.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/grpc/conversions.rs
linera-rpc/src/grpc/server.rs
linera-rpc/src/lib.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/linera/main.rs

With user blobs on the way, the existing usage of `blob` in the code base can be confusing
Rename `blob` to what it actually is, a `hashed_certificate_value`
CI

blob -> hashed_certificate_value

---

.github/workflows/docker.yml
docker/Dockerfile

The docker image build broke due to a new crate being added to the workspace which was not explicitly copied in Docker.
Build the docker image when Rust code changes.
Also fixed the missing dependencies.
CI

Fix docker image eth

---

Cargo.toml
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage-service/Cargo.toml
linera-storage/Cargo.toml
linera-version/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml

Updating our package metadata across the workspace is a pain.
Move shared metadata into our `Cargo.toml`'s [`workspace.package`](https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table) key, and refer to it from there.
CI.
It would also be good to test publishing, but I failed to find a safe way to dry-run publishing.
Bureaucracy — no user-visible changes.

Workspace metadata

---

default.nix
flake.lock
flake.nix

The `linera-web` repository wants to compile `linera-protocol` as well, plus some other tools, but with the current setup must duplicate its build environment.
Instead of just a dev shell, make a real package for `linera-service` using [Crane](https://crane.dev/).  Then, we can re-use that package's `buildInputs` in `linera-web`.
Tested locally.
Since Nix is not currently a supported install path, no documentation is required.  Nix-based environments (e.g. on [Gitpod](https://gitpod.io/)) should also continue to work the same.

`flake.nix`: use a Nix package to facilitate sharing

---

Cargo.lock
examples/Cargo.lock
linera-version/Cargo.toml

Fix cargo publish for `linera-version`
Apply the same fix as for `linera-base`
Used in `devnet_2024_03_26`
To be cherry-picked in `devnet_2024_05_07` as well

fix async-graphql-derive for linera-version as well

---

linera-ethereum/Cargo.toml

`linera-ethereum` was not included in #2015 (possibly a rebase issue)
Use workspace metadata in linera-ethereum as well
CI

Use workspace metadata in linera-ethereum as well

---

.github/workflows/rust.yml
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/worker.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-service/src/chain_listener.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs

The APIs when running on Wasm and non-Wasm should be the same.
Enable it!  In order to do so, we have to make some traits non-`Send` on the Web, since the Web fetch futures are not `Send`.
CI.
Nothing special required.

`linera-execution`: enable `fetch_url` on Wasm environments

---

.github/workflows/rust.yml
examples/Cargo.lock
examples/Cargo.toml
examples/hex-game/Cargo.toml
examples/hex-game/README.md
examples/hex-game/src/contract.rs
examples/hex-game/src/lib.rs
examples/hex-game/src/service.rs
examples/hex-game/src/state.rs
examples/hex-game/tests/hex_game.rs
linera-sdk/src/test/block.rs
linera-sdk/src/test/chain.rs
linera-sdk/src/test/validator.rs

Multi-owner chains can be useful for playing games where owners make moves without having to wait for anyone to receive a message.
Implement [Hex](https://en.wikipedia.org/wiki/Hex_(board_game)) as a game that is played using operations, not messages.
A unit and an integration test was added.

Add hex-game example.

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/worker.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs

Currently, processing a chain on the client creates network actions for all other chains it sends messages to. This leads to cross-chain requests that create chain states on storage for those other chains. These other chains might not be relevant to the client, which means it wastes storage and hinders performance.
As a real world example, the faucet chain is used to create new chains. Every block creates a new chain. That means that when a user uses the wallet to create a chain using the faucet, it will keep in storage the initial chain states for all chains created by the faucet before it.
Add an optional `tracked_chains` field to `WorkerState`, and only create `NetworkActions` for those tracked chains.
Did a quick manual test and saw that the time to create a chain using the faucet was …

Limit network actions to tracked chains

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/worker.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/src/unit_tests/chain_listener.rs

This PR is a port of #2035 to the `devnet_2024_05_07` branch.
Currently, processing a chain on the client creates network actions for all other chains it sends messages to. This leads to cross-chain requests that create chain states on storage for those other chains. These other chains might not be relevant to the client, which means it wastes storage and hinders performance.
As a real world example, the faucet chain is used to create new chains. Every block creates a new chain. That means that when a user uses the wallet to create a chain using the faucet, it will keep in storage the initial chain states for all chains created by the faucet before it.
Add an optional `tracked_chains` field to `WorkerState`, and only create `NetworkActions` for those tracked chains.
Did a quick manual …

Limit network actions to tracked chains (in `devnet_2024_05_07`)

---

linera-core/src/local_node.rs

Mitigate GRPC errors due to large batches
This is a quick fix where the max-batch value is hardcoded.
I created #2045 for a more principle approach.
CI + tested in producttion on `devnet_2024_03_26` branch

FIX: Download certificates in batches, rather than all at once.

---

linera-core/src/client.rs
linera-core/src/lib.rs
linera-core/src/unit_tests/value_cache_tests.rs
linera-core/src/value_cache.rs
linera-core/src/worker.rs

The `WorkerState` has an internal LRU cache of certificate values. This helps with network usage, because it allows clients to only send the full `Certificate` once, and send `LiteCertificate`s (without the `CertificateValue`) afterwards.
The `WorkerState` also includes some helper methods to interface with the cache. These methods would have to be duplicated in the new `ChainWorkerState` type.
Move the cache functionality into a new `CertificateValueCache` type, so that the methods don't have to be duplicated in the new `ChainWorkerState`.
Also add metrics to the cache, so that the number of cache hits and misses is tracked.
Some unit tests were added specifically for the new type.
Internal refactor, nothing needed.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/ …

Create a `CertificateValueCache`

---

linera-core/src/unit_tests/value_cache_tests.rs
linera-core/src/value_cache.rs

If a certificate value is inserted in the `CertificateValueCache`, there's a high chance it will be used again soon. This is also true if the value is already in the cache, so it should be promoted as if it was just recently inserted.
Promote values that were attempted to be inserted in the cache but were already present.
Unit tests were added for the new behavior.
Internal changes, so nothing needed.

Promote reinserted values in cache

---

.github/workflows/docker.yml

Reduce the scope for running the Docker CI workflow.
If `Cargo.toml` changes we can pick up most workspace changes.

Docker CI workflow is more strict

---

linera-service/tests/end_to_end_tests.rs

Some tests in the CI are frequently failing for largely unknown reasons. It makes sense to disable some of them for the ease of the developer and to isolate what goes wrong.
* The test `test_wasm_end_to_end_non_fungible` is disabled as it is affected by the error `Error: Could not find application URI: .... after 15 tries`.
* The test `test_wasm_end_to_end_fungible` is disabled as it is affected by the error `Error: Could not find application URI: .... after 15 tries`.
* The test `test_end_to_end_reconfiguration::scylladb_grpc` is disabled as it is affected by timeouts.
We are testing less things.
Not relevant.

Disable 3 tests that frequently fail.

---

.github/workflows/rust.yml

The Ethereum tests are failing for mysterious reasons. It is better to disable them in order not to block the development process.
The change is done in the CI code
The tests are disabled.
Not relevant.

Disabling Ethereum tests

---

linera-service/tests/end_to_end_tests.rs

The synchronization has a number of errors. This PR addresses one though it does not occur in commonly used CI.
The history of that error is interesting. In another PR a proposal was made to change the way end-to-end tests.
That PR failed and showed a different error than the usual ones.
That error can be reliably reproduced by running the test in a docker instance on one's laptop. The proposed correction addresses that error.
The CI should do the job, but those bugs were not revealed by the existing CI. Instead, one can see those bugs by running the tests in a local docker instance.
Not relevant.

Address two synchronization errors.

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-ethereum/src/provider.rs

Ethereum has just been removed from the CI. But in order to progress, we need to have it running.
* Put the Ethereum at first to fail first.
* Upgrade alloy to the latest.
* Specify the version of foundry used.
That is the point. Looking that it worked.
Not relevant.

Reintroduce Ethereum in the CI

---

linera-sdk/build.rs
linera-sdk/src/bin/wit_generator.rs
linera-sdk/src/test/mod.rs

The documentation in docs.rs is failing to build. It's happening because it attempts to build the crate for the `wasm32-unknown-unknown` target with all features enabled, which does not work. Right now only the library part of the crate can compile to Wasm, and with the `test` feature disabled.
Ensure that the `wit-generator` binary does not lead to compiler errors when compiling `linera-sdk` for `wasm32-unknown-unknown`, and ensure that the integration test parts of the `test` module is only compiled for non-Wasm target architectures.
This now makes `cargo build -p linera-sdk --target wasm32-unknown-unknown` and `cargo build -p linera-sdk --all-features --target wasm32-unknown-unknown` work.
Nothing needed, but the changes to the documentation should only appear with the next release.
- …

Fix `linera-sdk` docs.rs build

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-witty/test-modules/Cargo.toml

Need to prepare future releases
* Update all the crates of the main workspace to v0.12.0
* Use workspace versioning for all crates in the main workspace
* Examples have their own workspace and are not concerned.
* `git grep contact@linera.io`
* CI
This prepares future breaking changes

Update the crates of the main workspace to v0.12.0 with workspace config

---

docker/Dockerfile
docker/proxy-init.sh
kubernetes/linera-validator/templates/proxy.yaml
linera-base/src/data_types.rs
linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/grpc/conversions.rs
linera-rpc/src/message.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/grpc_proxy.rs
linera-service/src/linera/main.rs
linera-service/src/linera/net_up_utils.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs
linera-service/src/server.rs
scripts/run_local.sh

We need to be able to download blobs directly from the Proxy as part of the user blobs work. Fixes #2028
This PR does a few things:
* Adds a storage connection to the Proxy
* Adds an entrypoint for downloading a blob given a blob ID
WIP

GRPC entrypoint to download a blob

---

linera-ethereum/src/client.rs
linera-ethereum/src/provider.rs
linera-ethereum/src/test_utils/mod.rs
linera-ethereum/tests/ethereum_test.rs

The function `non_executive_call` was not taking a block. This is a problem for validator coherency.
The non-executive call is now taking a block number.
The test is added to the `ethereum_test.rs`.
Not relevant.

Add the block to the non_executive_call.

---

CLI.md
linera-base/src/data_types.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-execution/tests/test_execution.rs
linera-sdk/wit/contract-system-api.wit
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/faucet.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

When opening a new chain, in addition to the chain ownership, users and contracts should be able to configure application permissions: which application's operations and messages are allowed or even mandatory on the new chain, and which applications can close the chain.
Extend the `open-multi-owner-chain` CLI command, the `openMultiOwnerChain` node service mutation, and the `open_chain` system API function.
Existing tests were extended.
- Closes https://github.com/linera-io/linera-protocol/issues/2071.

Extend open chain functions in CLI, node service and system API.

---

linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-core/src/chain_worker/config.rs
linera-core/src/chain_worker/mod.rs
linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/lib.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-sdk/src/test/chain.rs

The `WorkerState` constantly loads and stores the `ChainStateView` for the chains it is responsible for, which leads to repeated (and often times unnecessary) serialization and deserialization.
Keep the `ChainStateView` cached in memory for a longer period of time inside longer lived `ChainWorkerState` types. These are split-off from the `WorkerState`, and are responsible for a single chain. For now the `WorkerState` creates and destroys the `ChainWorkerState` on every request, which makes the functionality practically the same as before. But this paves the way to have a `ChainWorkerActor` type that is longer lived and wraps the `ChainWorkerState`.
This is an internal refactor, so existing tests should catch regressions.
Internal refactor, so nothing is needed.
- [reviewer …

Split off `ChainWorkerState` from `WorkerState`

---

linera-rpc/src/simple/server.rs
linera-rpc/src/simple/transport.rs
linera-service/src/prometheus_server.rs
linera-service/src/proxy.rs
linera-service/src/server.rs

The `ToSocketAddrs::to_socket_addrs` function performs a blocking DNS lookup, so it should be avoided inside asynchronous contexts.
Also, there were a few cases where a string was built just to have its parts parsed out again, which is a bit inefficient.
Use `tokio::net::lookup_host` instead of `.to_socket_addrs`, because it performs a non-blocking DNS lookup better suited for asynchronous contexts.
Refactor how `SocketAddr`s are built and passed around, to minimize the amount of parsing.
As a consequence of this refactoring, there's a little new feature. The listening address for the metrics server can now be a host name instead of an IP address. This allows using `localhost`, for example.
This is an internal refactor, and CI should catch any regressions.
Internal refactor, so nothing is …

Refactor usage of `SocketAddr`

---

linera-rpc/src/simple/transport.rs

The simple server implementation had a `ServerHandle::kill` method that was never used. It also used a redundant `AbortHandle` for the server task, because `JoinHandle::abort` could be used instead.
Remove the unused `kill` method and the redundant `AbortHandle` channel.
Removed code that wasn't used, so no extra test coverage is needed.
Internal refactor, so nothing is needed.

Clean-up simple server shutdown

---

linera-rpc/src/grpc/server.rs

The creation of `SocketAddr`s was recently optimized (#2088), but one expression was missed. In the expression, a `String` is built just so that it could be parsed again, instead of parsing just the `IpAddr` and passing the port value directly.
Refactor to only parse the `IpAddr`.
Internal refactor, so no extra coverage is needed. CI should catch any regressions.
Internal refactor, so nothing is needed.

Parse only `IpAddr` instead of parsing a new string for `SocketAddr`

---

linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/local_node.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-storage/src/lib.rs

Now that we can download blobs, using the chain info query isn't needed anymore.
Use the `download_blob` entry point instead, to download the blob directly from the validator proxy.
Existing tests should catch regressions.
- Based on @andresilva91's #2079.

Replace blob chain info query usage with blob download

---

linera-rpc/src/grpc/server.rs
linera-rpc/src/simple/server.rs
linera-rpc/src/simple/transport.rs
linera-service/src/proxy.rs
linera-service/src/server.rs

While refactoring to replace `tokio::spawn`s with spawning on `JoinSet`s, I realized it would help if the spawning of servers was synchronous and infallible. That means that the `spawn*` methods only spawn tasks, and do no other work.
Refactor server `spawn*` methods to be infallible and (mostly) synchronous. The `spawn_{grpc,simple}` methods in `linera-service` are still asynchronous but they only `await` the collection of the handles, which can be done in a spawned task as well. However, that requires some further refactoring so that the caller awaits all the tasks, which I left for the next PR.
In terms of functionality, the visible part of the changes is error reporting. Before it would log a separate error message if an error occurred while a task was starting (for example when …

Refactor server spawning to be synchronous and infallible

---

linera-sdk/build.rs
linera-sdk/src/bin/wit_generator.rs
linera-sdk/src/ethereum.rs
linera-sdk/src/test/mod.rs

The build on `docs.rs` is [failing](https://docs.rs/crate/linera-sdk/0.11.3/builds/1227306). This was fixed on `main` by #2064, but it should also be fixed in the next patch release of the SDK.
Cherry-pick the fix from `main`, and disable initial support for Ethereum when compiling for `wasm32-unknown-unknown`.
This now makes `cargo build -p linera-sdk --target wasm32-unknown-unknown` and `cargo build -p linera-sdk --all-features --target wasm32-unknown-unknown` work.
No functionality has changed except for disabling Ethereum support (which is currently not documented). Nothing is needed except releasing a new patch version.

Fix `linera-sdk` docs.rs build (#2064)

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
linera-execution/Cargo.toml
linera-execution/build.rs
linera-execution/src/lib.rs
linera-execution/src/test_utils/mock_application.rs
linera-execution/src/wasm/system_api.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-witty/Cargo.toml
linera-witty/src/runtime/wasmer/export_function.rs
linera-witty/src/runtime/wasmer/function.rs
linera-witty/src/runtime/wasmer/memory.rs
linera-witty/src/runtime/wasmer/mod.rs

We would like to be able to execute application blocks in the browser wallet.
Make `linera-execution`'s `wasmer` feature work on the Web:
CI build of `linera-core`, and manual client worker build in `linera-web`.
Once the Web wallet is all working as intended, we should [add some tests](https://github.com/linera-io/linera-protocol/issues/1989) using `wasm-bindgen-test`.

Wasm on the Web

---

examples/Cargo.lock

CI on main fails because the examples `Cargo.lock` needs to be updated.
Update it.
I'm not sure if this was only caught after merging, while the tests on the PR itself were green. `cargo build --locked --release --target wasm32-unknown-unknown` should have caught this. Maybe a dependency was updated?

Update examples Cargo.lock.

---

linera-service/src/proxy.rs

I ran into another instance of a `String` allocation just to parse a `SocketAddr`. Some of these cases were removed in previous PRs (#2088, #2093). 
Parse only the `IpAddr` instead, reusing the port value. This avoids an allocation and parsing of the port value.
This is an internal refactor. Existing tests should catch any regressions.
This is an internal refactor, so nothing is needed.

Avoid allocating a `String` to parse `SocketAddr`

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
linera-execution/Cargo.toml

Wasmer released 4.3.0 to `crates.io`, breaking our patch.
Update our patched Wasmer to version 4.3.1.  Also, patch without a version constraint to help ensure this doesn't happen again.
CI.
None required.

`Cargo.lock`: update patched version of `wasmer`

---

.github/workflows/docker.yml
configuration/compose/validator.toml
docker/Dockerfile
docker/compose-proxy-entrypoint.sh
docker/compose-server-entrypoint.sh
docker/compose-server-init.sh
docker/compose.sh
docker/docker-compose.yml

Our reference validator implementation runs with Kubernetes. This may be overkill for certain situtations / usecases.
We now support a lighter validator running on Docker Compose. This doesn't come with all the bells and whistles of the Kubernetes deployment such as observability and monitoring.
There is lot's of room for improvement here:
1. Add faucet for single-validator network
2. Add multiple shards (if it is deemed performant)
3. Add capabilities to join existing network
Manually tested for now, see above.

Run single validator with Docker Compose

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
linera-execution/Cargo.toml

We cannot publish crates to `crates.io` that rely on non-`crates.io` dependencies or patches. 
Publish `linera-` versions of the Wasmer crates we use, which we can depend upon until necessary changes are upstreamed.
CI.
None required.

`wasmer`: use Linera fork `linera-wasmer` for the time being

---

Cargo.lock
linera-rpc/Cargo.toml
linera-rpc/src/grpc/server.rs
linera-rpc/src/simple/server.rs
linera-rpc/src/simple/transport.rs
linera-service/Cargo.toml
linera-service/src/grpc_proxy.rs
linera-service/src/linera/net_up_utils.rs
linera-service/src/prometheus_server.rs
linera-service/src/proxy.rs
linera-service/src/server.rs
linera-service/src/util.rs

When shutting down the server and the proxy, any active connections should be closed gracefully.
Move the code to listen for UNIX signals that indicate the user requested the process to stop from the `linera` binary to the `linera-service` library. Tweak it so that it uses a [`CancellationToken`](https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html) to notify tasks that they should shutdown.
Refactor the simple TCP and UDP servers so that they can gracefully shutdown when requested.
Issue #2111 tracks implementation of tests for this functionality. I drafted some initial tests in a separate [branch](https://github.com/jvff/linera-protocol/compare/graceful-shutdown..graceful-shutdown-tests#diff-dfc6c0645ad6ae581de82afaec88c92e55b565a53d3437fcf5467f807000e571) and …

Implement graceful shutdown of server and proxy

---

examples/hex-game/src/contract.rs
examples/hex-game/src/lib.rs
examples/hex-game/src/service.rs
examples/hex-game/src/state.rs
examples/hex-game/tests/hex_game.rs
linera-base/src/data_types.rs
linera-chain/src/chain.rs
linera-core/src/chain_worker/state.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/src/wasm/system_api.rs
linera-execution/tests/fee_consumption.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/contract/conversions_to_wit.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/contract/test_runtime.rs
linera-sdk/src/test/block.rs
linera-sdk/src/test/chain.rs
linera-sdk/src/test/validator.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-service/src/unit_tests/chain_listener.rs
linera-storage/src/db_storage.rs

The block timestamp itself can be used by contracts to verify that the current block is validated _after_ a certain point.
We should add an oracle (for regular blocks only!), so contracts can call `runtime.assert_before(some_time)`, which will panic if at validation, the current time is not _before_ `some_time`.
Add an `assert_before_ oracle to the service and contract runtime.
A clock using the oracle was added to the Hex game, and two tests were added.
- Closes #2077.

Add an assert_before oracle.

---

.github/workflows/rust.yml
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-indexer/example/tests/test.rs
linera-service-graphql-client/tests/test.rs
linera-service/Cargo.toml
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/database_tool.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/readme_test.rs
linera-storage-service/Cargo.toml
linera-storage-service/src/lib.rs
linera-storage-service/tests/store_test.rs

We have worked with the storage service, but it is quite different from other storage systems.
* A feature `storage_service`is introduced. It is used for enabling tests based on storage service.
* The functionality of the storage service is not feature gated, only the tests.
* The practice of spawning a storage service is kept as it is still needed for the `linera net up`.
* The `end_to_end_tests.rs` is restructured. Since RocksDb tests are not enabled, by default, no tests are enabled if no feature is selected.
* The `cargo test` runs locally if only the corresponding witty has been precompiled.
* A storage service is spawned in the CI before running the tests similarly to what is done for `ScyllaDb` and `DynamoDb`.
* The names like `service_grpc` are renamed as …

Eliminate the spawning of the storage service in the `cargo test`

---

linera-chain/src/data_types.rs
linera-chain/src/manager.rs
linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/updater.rs
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/unit_tests/faucet.rs

When there is any validated block certificate in an earlier round, an honest round leader (both in multi- and single-leader rounds) should re-propose that block in the current round.
This is currently only working if the earlier block was proposed by the current round leader itself, or doesn't have an authenticated signer.
Also, the client is currently failing in some cases where it tries to update the validators and inform them about the highest locked block: They will return an error if that block is older than their own most recent vote. But actually, informing them about the highest locked block should be unnecessary anyway, because the block will be included in the proposal.
Check the authenticated signer only if there is no validated block included in the proposal. If there is, that …

Fix re-proposing another owner's proposal from an earlier round.

---

linera-ethereum/src/client.rs
linera-ethereum/src/provider.rs
linera-ethereum/tests/ethereum_test.rs

The `get_balance` takes an `Option<u64>` with `None` corresponding to latest which is not congruent with an Oracle.
We simply replace `Option<u64>` by `u64` in a straightforward way.
The tests are actually simplified by the 
This actually makes the API coherent with the manual of the release plan.

Remove the Optionality to the `get_balance`.

---

linera-service/src/cli_wrappers/wallet.rs

The error "Failed to post query" often occur in the CI, but it is not so descriptive.
The function being called is systematically added to the error. The query itself is added in some cases by replacing `context` by `with_context`. 
This improves the CI.
Not relevant.

Improve the accuracy of the output 

---

linera-storage-service/Cargo.toml
linera-storage-service/build.rs
linera-storage-service/src/client.rs
linera-storage-service/src/common.rs

Metrics are available for `ScyllaDb`, `DynamoDb`, `RocksDb` but not for storage service.
Two changes are made:
* Add the LRU caching for the client. We expect gains from that because it saves at least one gRPC call.
* Add the Metering for the `ServiceStoreClient`. 
The CI should do the job.
Not relevant.

Add metrics to the `storage_service`

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs

`test_re_propose_validated` is currently flaky: Client 1 can only re-propose the validated block if it can download it from validator 0, but depending on timing, validator 0 may not have stored it as its locked block before the updater was canceled due to the faulty validators' errors.
In the client, process all certificates for validated blocks as soon as we have them, so that client 0 in the test is guaranteed to have it in its local chain manager.
In the test, get the certificate from client 0 and directly send it to validator 0 to make sure it has processed it, too.
I reproduced the flakiness locally with ScyllaDB, and this fixed it. CI will show if there are any remaining issues.
- The test was added in https://github.com/linera-io/linera-protocol/pull/2118.
- [reviewer …

Fix the flaky test_re_propose_validated.

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs

In the future the local node client will live on the protocol client instead of each chain client, so needs to be safely shareable.  Thankfully, the `LocalNodeClient` uses an `Arc<Mutex<…>>` inside it, so never needs to be called via a unique `&mut` reference.
Change the `&mut self` parameter for all local node client functions to `&self`, taking advantage of the inner `Arc<Mutex<…>>`.
CI.
None required.

`linera-core`: remove unnecessary `&mut` from `local_node`

---

linera-core/src/client.rs
linera-core/src/unit_tests/test_utils.rs
linera-service/src/linera/client_context.rs
linera-service/src/unit_tests/chain_listener.rs

In the future, the `ChainClientBuilder` will, rather than just being a factory for chain clients, also take on functionality related to being a client for the protocol as a whole.
Rename `ChainClientBuilder` to simply `Client`.
CI.
- This is a minor version bump.

`linera-core`: rename `ChainClientBuilder` to `Client`

---

linera-service/src/config.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/wallet.rs

In the future, `ClientContext` will contain a `Client`, and therefore will not be constructible until a storage client is available. 
Instead of constructing a `ClientContext` to do wallet operations in the CLI, just construct a `WalletState` (a persisted wallet file) instead.
CI.
No user-visible changes.

`linera-service`: move wallet-only operations out of `ClientContext`

---

linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

In the future, the `ClientContext` will contain a `Client`, which needs to be constructed with access to a `Storage` instance.  However, currently the `ClientContext` is constructed outside the `Job`, which is the only place the `Storage` is available.
Move the construction of the `ClientContext` into the `Job`, so it has access to storage.
CI.
None required.

`linera-service`: give `ClientContext` access to storage

---

linera-chain/src/data_types.rs
linera-chain/src/lib.rs
linera-chain/src/manager.rs
linera-chain/src/test.rs
linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/linera/client_context.rs

Originally `BlockAndRound` was exactly the part of the block proposal that was signed. But now, if you re-propose a validated block from an earlier round, you also have to sign at least the oracle records from that block. This is currently solved with a temporary `ProposalPayload` structure. Also, the block is duplicated in `BlockProposal`, since it is contained in the earlier round's certificate and in `BlockAndRound`.
Replace `BlockAndRound` with `ProposalContent`, which also contains an optional list of oracle records. Use a lite certificate instead of a certificate if it is a retry from an earlier round.
To simplify the code a bit, remove the option to re-propose a validated block without including the certificate. (Currently, the manager would accept that.)
The tests have been …

Refactor BlockProposal.

---

linera-core/src/join_set_ext.rs
linera-core/src/lib.rs
linera-rpc/src/grpc/mod.rs
linera-rpc/src/grpc/server.rs
linera-rpc/src/simple/server.rs
linera-rpc/src/simple/transport.rs
linera-service/src/grpc_proxy.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/src/proxy.rs
linera-service/src/server.rs

There are quite a few calls to `tokio::spawn` in the code. However, in order to run the code on the browser (for the web wallet), `tokio::spawn` does not work because execution is single-threaded. The solution is to spawn tasks in a `LocalSet`, so that it runs inside the same worker thread.
Create a `JoinSetExt` trait with a few extension methods for [`tokio::task::JoinSet`](https://docs.rs/tokio/latest/tokio/task/struct.JoinSet.html). One of the extension methods allows spawning a new task in the `JoinSet`, and its behavior is determined during compilation by the `web` feature. If the `web` feature is enabled, `JoinSet::spawn_local` is used. Otherwise, `JoinSet::spawn` is used, which is the same as `tokio::spawn`.
The code is then refactored to use `JoinSet`s to keep track of the spawned …

Spawn tasks in `JoinSet`s

---

linera-service/Cargo.toml
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

We want to enable the `LocalNet` in parallel with a shared set of validators. However, PR #2096 has indicated that some protocol issues may have to be resolved. Since PR #2096 was using the same schema for `make_client` it makes sense to enable it for the Kubernetes.
This PR enables the Kubernetes tests to work in parallel by disabling the Mutex `INTEGRATION_TEST_GUARD` for the Kubernetes runs.
This is not sufficient to have the end-to-end tests working in Kubernetes. The node services have to run on disjoint ports. The chosen solution is to remove the `run_node_service(None)` from the end-to-end tests and instead use a `run_node_service(port)` with `port` obtained from a `get_node_port`. That function `get_node_port` returns increasing port numbers starting from `8080`. It is not …

Enable Kubernetes CI to work in parallel

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/src/chain_worker/state.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-explorer/src/components/Block.test.ts
linera-explorer/src/components/Block.vue
linera-explorer/src/components/Blocks.test.ts
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/test/block.rs
linera-sdk/src/test/chain.rs
linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql
linera-service-graphql-client/src/service.rs
linera-service/src/chain_listener.rs

In the execution outcome, oracle records are grouped by transaction, but outgoing messages are in a single flat vector.
For consistency, group outgoing messages by transaction, too.
As a follow-up and/or alternative, we might consider:
* Changing `MessageId`, so that there is a _transaction_ index, and another index for the message _within_ that transaction's outcome.
* We could merge the two vectors and have something like:
```rust
struct TransactionExecutionOutcome {
messages: Vec<OutgoingMessage>,
oracle_responses: Vec<OracleResponse>,
}
```
Only refactoring.
- Need to bump the minor version number in the next release of the crates.

Group outgoing messages by transaction.

---

linera-chain/src/chain.rs
linera-chain/src/inbox.rs
linera-chain/src/outbox.rs
linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-execution/src/applications.rs
linera-execution/src/execution.rs
linera-execution/src/system.rs
linera-service/src/node_service.rs

The client node currently loads `ChainStateView` directly from storage when it needs to read some information from it. This is inefficient because it requires reloading the `ChainStateView` (which means deserializing its data) every time. It also holds a lock while doing so, preventing others to access the same chain state.
The goal is to keep the `ChainStateView` in memory for a longer amount of time. In order to do so, each `ChainWorkerState` (introduced in #2055) becomes the owner of its respective `ChainStateView`. That means that it will hold a lock on the `ChainStateView` and the client node won't be able to access it as it is currently accessed.
Access the `ChainStateView` through the `WorkerState` in the `LocalNode`. The `ChainStateView` is wrapped inside an …

Allow client node to read `ChainStateView` outside the `ChainWorkerState`

---

.github/workflows/kubernetes.yml
linera-service/Cargo.toml
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

Kubernetes CI was not triggered on #2101 (which was missed) and now it's broken.
```
thread 'test_wasm_end_to_end_social_user_pub_sub::kubernetes_grpc' panicked at linera-service/src/cli_wrappers/local_kubernetes_net.rs:177:18:
called `Result::unwrap()` on an `Err` value: Error getting write lock to wallet "/tmp/.tmp5do90t/wallet_0.json". Please make sure the file exists and that it is not in use by another process already.
```
* This seems related to #2101 so revert commit bd98cdfb81bd368dd87ae382ca3e0a31954f01b0.
* Activate CI 
CI

Revert "Enable Kubernetes CI to work in parallel (#2101)"

---

linera-core/src/client.rs
linera-core/src/unit_tests/test_utils.rs
linera-service/src/chain_listener.rs
linera-service/src/faucet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs
linera-service/src/unit_tests/chain_listener.rs
linera-service/src/unit_tests/faucet.rs

In order to have a multi-chain protocol client we can wrap at higher levels in ways that allow us to create wrapped chain clients, that client needs to have access to a local node.
Move the `LocalNodeClient` out of `ChainClient` and into `Client`, where it can be accessed through a reference (currently in an `Arc`, as we need to `tokio::spawn` it).
Then, remove the `Storage` parameter from functions on `linera_service::linera::client_context::ClientContext`, as we can now retrieve it directly from the `Client` (so long as we're in an async context). 
CI.
None required.

Global local client

---

linera-service/src/linera/client_context.rs

The message policy from the client options is not actually used.
Set it when creating the client builder.
There are already client tests for the message policy; it just wasn't set as specified on the CLI.
- Original PR: https://github.com/linera-io/linera-protocol/issues/1842

Use the message policy specified on the CLI.

---

linera-base/src/crypto.rs
linera-core/src/client.rs
linera-indexer/plugins/src/operations.rs
linera-service/tests/end_to_end_tests.rs
linera-views/tests/queueview_tests.rs
toolchains/build/rust-toolchain.toml

Rust 1.79.0 was released.
Upgrade, and fix a few new Clippy lints.
Existing tests should catch any regressions.

Upgrade to Rust 1.79.0

---

.github/workflows/docker.yml
docker/compose.sh

Docker compose validators do not work on MacOS.
Add the appropriate Build args to make it work locally.
This _has_ been tested locally and will be tested by CI on Linux, however due to the limited size of MacOS runners, testing on CI is not currently possible as building the container will OOM.

Docker compose works for MacOS

---

linera-service/src/cli_wrappers/local_net.rs

Faster CI
* Wait 100ms before the first try in `ensure_grpc_server_has_started`
* Wait less in case of error as well
CI

Fix ensure_grpc_server_has_started

---

linera-sdk/src/test/validator.rs

The SDK integration test framework would allow creating new chains, but to do so it would call `Storage::create_chain`. That call acquires a chain guard for the admin chain, which can hang if there's a chain worker loaded for the admin chain already.
Create sub-chains from the admin chain using the worker instead.
Existing integration tests were executed with the chain workers, and they passed.
This may change the semantics of integration tests that rely on the first call to `new_chain` to return the admin chain. So I'd suggest:

Create new chains from admin chain for integration tests

---

linera-chain/src/data_types.rs
linera-chain/src/lib.rs
linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/grpc/conversions.rs
linera-rpc/src/message.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/grpc_proxy.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs

We need to be able to download certificate values directly from the Proxy. Fixes #2029
Adds an entrypoint for downloading a certificate value given a hash
CI for now, will replace chain info queries in following PR

Endpoint to download a certificate value

---

linera-version/src/version_info/type.rs

The `RPC API hash` and `WIT API hash` were showing the same value which is not what one expects.
The explanation was that the paths were incorrect. Once corrected, we obtained reasonable values.
We check that the hashes are different.
Not relevant.

Correct the paths for the computation of the `RPC API hash` and `WIT API hash`

---

linera-service/src/faucet.rs
linera-service/src/node_service.rs

The instability in CI and in particular for `make_application` is a constant problem. The GraphQL cache could be an explanation for our problems. This PR closes the possibility.
Replace the `#[Object]` by `#[Object(cache_control(no_cache))]`. 
Putting `n_try = 1` for the `make_application` and running the end-to-end tests locally did not reveal a change of behavior. However, the PR is still interesting as it removes one explanation for the CI problems.
Not relevant.

Disable the cache for the objects used in the NodeService and Faucet

---

linera-chain/src/data_types.rs
linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/updater.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap

Now that we can download certificates, using the chain info query isn't needed anymore
Use the download certificate entrypoint instead
CI

Replace certificate chain info query usage with certificate download

---

linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/src/grpc/server.rs
linera-service/src/grpc_proxy.rs

The current proto struct is called `Certificate`, but it isn't really representing that
Rename it to what it actually represents
CI

Certificate -> CertificateRequest on rpc.proto

---

linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/message.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/grpc_proxy.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs

There are also cases where we need to be able to download one certificate directly from the Proxy.
Adds an endpoint for downloading a certificate given it's hash
CI for now, will replace chain info queries in following PR

Endpoint to download a Certificate

---

linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/test_utils.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap

Right now we have `request_sent_certificates_in_range` in the chain info query. We don't need to go all the way to the server to get these certificates.
With the new endpoints, as discussed on Slack, we could modify this to return just the certificate hashes, and then download the certificates from the proxy directly using the new endpoints.
CI

Replace request_sent_certificates_in_range and use the download of certificates

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

This should make the end-to-end tests less flaky and slightly faster by making sure cross-chain messages have been processed when the test observes the result.
Suppose an application is registered on chain A:
* If chain B requests that application from chain A, we have to wait for
- chain A to process the request, and
- chain B to process the response…
* If chain A sends an application message to chain B, we have to wait for
- chain B to process the message…
…before we can expect the application to be registered on chain B.
In the tests, we currently just retry in a loop until this has happened.
Call `process_inbox` in the right places, and remove the retry loop.
All affected tests run in CI.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#revi …

Remove retry loop from make_application.

---

linera-version/src/version_info/type.rs

The additional assert statements for the `RPC API hash` and the `WIT API hash` are creating issues with some other checks. So, we disable them here.
Direct removal of the assert statements.
No change.
Not relevant.

Disable the assert statements for the `RPC API hash` and `WIT API hash`.

---

linera-core/src/client.rs

Client commands (e.g. `transfer`) automatically retry if a conflicting block gets confirmed at the same height. Since the validators might see different oracle values than the local node, even in the case of success, the confirmed block might look different than the one that was computed locally. This would currently make the client retry the command that already succeeded.
Compare only the `Block`, not the `ExecutedBlock`, since the former doesn't contain oracle records.
A test will be added in https://github.com/linera-io/linera-protocol/issues/2154.
- #2154 

Don't retry proposal if the block got confirmed, even with different oracle values.

---

linera-service/Cargo.toml
linera-service/src/cli_wrappers/local_net.rs
linera-service/tests/end_to_end_tests.rs

For the `run_node_service` we want the ports to be all distinct instead or `8080` and similar.
We introduced the `get_node_port` function.
The CI should do it and not change.
Not relevant.

Introduction of the `get_node_port`.

---

linera-core/src/client.rs

Minor optimization: Remove a redundant call (involving a database query or at least requesting data from another task).
The chain info query in `propose_block` is redundant: The function is called in only one place, and at the call site we already have the chain info.
Remove the query, pass the required data (the chain manager info) into `propose_block`.
Also, deduplicate clearing the pending block in a few places.
The existing tests should catch any regression.

Remove redundant local chain info query from `propose_block`.

---

linera-base/src/data_types.rs
linera-core/src/chain_worker/state.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

For example, if we know a certain blob was published, and we try to use it, but some of the validators don't have it, we need to be able to know the certificate that last used the blob so that we can sync validators to also have that blob. That's one use case for this, but there are more. Part of #2033
Track what `Certificate` last used the blob. As of right now, the only "usage" is publishing a blob, but in the future we'll also use it in the `read_blob` system API call, when we replace `Bytecode` with blobs, etc.
CI + will use this in following PRs

Track the certified block that published a blob last

---

linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/message.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/grpc_proxy.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs

Building on top of #2156, there we will need this endpoint for the client to communicate with the validators. Fixes #2030
Adds an endpoint to get what `Certificate` last used a blob.
CI for now, but will use this in following PRs

Endpoint to request which certificate published a blob last in a given validator

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-core/src/chain_worker/state.rs
linera-core/src/unit_tests/worker_tests.rs

First step towards #1475
Outgoing messages are already grouped by transaction. Do not flatten them when creating the `MessageBundle`s.
CI

Do not merge message bundles from different transactions

---

linera-base/src/data_types.rs
linera-core/src/chain_worker/state.rs
linera-execution/src/execution.rs
linera-execution/src/system.rs
linera-rpc/tests/snapshots/format__format.yaml.snap

We'll need blobs are oracles to be able to properly check things for #2151. Fixes #2032
Add blobs as oracles
CI + will be used in following PRs

Add blobs as oracle records

---

linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/tests/snapshots/format__format.yaml.snap

This cleans up the three error types that were partially introduced in this PR #2014. We don't need the three error types, we can cover all cases with just one
Replace the three errors with one
CI

Replace [Blobs|ApplicationBytecodes|ApplicationBytecodesAndBlobs]NotFound by ApplicationBytecodesOrBlobsNotFound

---

linera-core/src/client.rs
linera-core/src/notifier.rs

Notifications may sometimes be processed twice (which is fine, if inefficient) or missed (which is not fine).
Make sure we process all notifications exactly once, by clearing the notification queue.
CI.
None required.

`linera-core`: handle notifications exactly once

---

linera-core/src/client.rs
linera-service/src/linera/client_context.rs

There were some occasional test failures with the error message saying that messages were out of order on the local node. After some discussion and debugging during the offsite, @afck suggested it could be a race condition because the client may try to propose a block with some messages that are already in a pending block that will be proposed first.
Retrieve the list of incoming messages to include in the block proposal _after_ handling the pending block. That way the messages are not repeated in both blocks.
After this fix, I could not reproduce the error that I was running into periodically.
Fixes a bug. There are no visible changes, so nothing is needed besides publishing a patch version.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#revi …

Fix client block proposal race condition

---

flake.lock

We are now using Rust 1.79 in our `rust-toolchain.toml`, but we haven't updated our `flake.lock`, so Nix-based building (e.g. on GitPod) fails.
Update `flake.lock`.
I tested locally.
None required.

`flake.lock`: update for Rust 1.79

---

linera-service/tests/end_to_end_tests.rs

When running `test_open_chain_node_service`, sometimes an error message would appear saying that there was a failure to receive a message due to insufficient funds. This happened because the test would create a new chain without providing it any tokens and ignore it for the rest of the chain. The error could be ignored, but while debugging another issue in the test, the error message led to a false lead that took some time away from the root cause.
Provide 1 token to the newly created chain.
After this fix, the error message does not appear anymore.
Only fixes a bug in a test, so nothing is needed.

Fix unrelated error in test due to a chain with zero balance

---

linera-core/src/chain_worker/state.rs

#2163 makes the `ChainWorkerActor` be reused across requests to the `WorkerState`. This improves performance because the `ChainStateView` does not need to be reloaded for every request. However, the PR was causing the `test_open_chain_node_service` test would fail, and the normal logs would show that the validators rejected a block because messages were out of order.
The trace log however, would show that first the validators would reject a block because it was missing the incoming messages (this is normal). After the cross-chain messages had been propagated, reproposing the block failed because the validator complained that those messages were already received.
The cause was that the chain state was not being properly discarded on error conditions. The `ChainWorkerActor` owns a …

Fix handling of chain state changes in `ChainWorkerState`

---

CLI.md
linera-execution/src/policy.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/linera/net_up_utils.rs

Simulate a devnet-like configuration locally with `linera net up`
Add an option `ResourceControlPolicyConfig`
Tested manually
```
cargo run --release --bin storage_service_server memory --endpoint 127.0.0.1:1235 &
cargo run --bin linera -- --storage service:tcp:127.0.0.1:1235:TEST net up --policy-config devnet
cargo run --bin linera -- faucet --amount 1000 --port 8079 &
export LINERA_FAUCET_URL=http://localhost:8079/
cargo test -p linera-service --features remote_net
```

Add option `--policy-config` to `linera net up`

---

linera-core/src/chain_worker/state.rs

PR #2180 created some wrapper types to ensure that changes to the `ChainStateView` in the `ChainWorkerState` are rolled back on early termination. However, the heuristic I used to select which methods to move to the wrapper types was incomplete. I only checked the methods that had calls to `chain.save()` or `chain.rollback()`, but some methods still perform changes that were assumed to be dropped after the request completed.
Use a broader and more cautious heuristic instead: every method that has a `&mut self` receiver and uses the `ChainStateView`'s fields or methods *must* use one of the wrapper types. The only exception to the rule is the `get_chain_state_view`, which uses `chain.clone_unchecked()`. This is an exception because that method is derived on the `ChainStateView` and does …

Fix further incorrect leftover changes to `ChainStateView`

---

linera-chain/src/data_types.rs
linera-execution/src/graphql.rs
linera-indexer/lib/src/indexer.rs
linera-indexer/lib/src/plugin.rs
linera-indexer/plugins/src/operations.rs
linera-service/src/faucet.rs
linera-service/src/node_service.rs
linera-views/src/graphql.rs

The use case of graphQL caches is to cases where the data consistency is not that important (social media, etc.). But that is not the case for blockchains.
* The `async_graph::`prefix is removed in 3 instances.
* To, the `#[Object]` entries, a `cache_control(no_cache)` is added.
* It has not been added to the `examples` which may be needed.
This may remove some errors occurring in the CI, though at the present time we cannot point out CI failures to GraphQL errors.
Not relevant.

Disable all graphql caches

---

linera-views/src/hashable_wrapper.rs
linera-views/src/unit_tests/views.rs

When a view wrapped in a `WrappedHashableContainverView` is cleared and flushed, its state in the persistent storage was cleared. However, the value of the persisted hash value that was cached in memory was not cleared, making it different than the value that was actually persisted (which was an empty value, because it was also cleared). When `rollback` is called, it uses the cached stored value to update the cached staged value, which set it to an invalid value.
Clear the cached value of the stored hash value when it is cleared from disk.
A unit test was added that reproduces a minimal scenario, and that fails without the fix and passes with the fix.
This is a bug fix, so nothing is needed except releasing a new patch version.
- [reviewer …

Fix rollback making cached hash value incorrect

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/src/grpc/server.rs
linera-rpc/src/simple/server.rs
linera-service/src/chain_listener.rs
linera-service/src/faucet.rs
linera-service/src/linera/client_context.rs
linera-service/src/node_service.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs
linera-service/src/server.rs
linera-service/src/unit_tests/faucet.rs

The worker spawns a `ChainWorkerActor` to handle each request. This is inefficient because it loads from storage the chain state every time. This should be cached in memory in order to avoid paying the overhead of deserializing the chain state every time.
Keep an LRU cache with some running `ChainWorkerActor`s, each responsible for a different chain.
The size of the cache should be configurable by the validators, because there's a tradeoff between chain execution latency and memory usage.
This is an internal refactor, so existing tests should catch any regressions.
I manually ran the Crowd-Funding `collect_pledges` integration test and collected some metrics before and after this PR.
Before:
```
linera_load_view{base_key="001db1936dad0717597a7743a8353c9c0191c14c3a129b258e9743aec2b4f05d03", …
```

Keep `ChainWorkerActor` running in an LRU cache

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/test_utils/mock_application.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/bin/wit_generator.rs

In order to have application services to live longer than a single query, the `SyncRuntime` needs to be longer lived. However, `SyncRuntime` contains cyclic `Arc` references inside, which means that if it is dropped without clearing its internal `loaded_applications` field, it will leak memory. Therefore, there needs to be a safe way to let `SyncRuntime` to be used by other modules in a way that it can be dropped safely.
Rename `SyncRuntime` into `SyncRuntimeHandle`, and create a new `SyncRuntime` wrapper type over the `SyncRuntimeHandle`. The new wrapper type represents the execution lifetime, and when it is dropped, it will clear the `loaded_applications` so that the internal `SyncRuntimeHandle` can be safely dropped without causing a memory leak.
A few unit tests were added to check if …

Make `SyncRuntime` represent the execution lifetime

---

.github/workflows/docker.yml
docker/compose.sh
docker/docker-compose.yml
kubernetes/linera-validator/helmfile.yaml
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/linera/main.rs

The name `linera-test` for the Linera Docker image is no longer representative of the function of the image.
Rename the Linera Docker image from `linera-test` to `linera`.

Rename instances of linera-test to linera

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/test_utils/mock_application.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/bin/wit_generator.rs

PR #2192 was merged when GitHub Actions was a bit flaky, and I didn't realize that no checks had been executed. The PR introduced a bug which CI caught on later PRs. PR #2205 reverted the buggy PR in order to unblock development.
The bug was that inside `ServiceSyncRuntime::run_query` the new `SyncRuntime` wrapper type wasn't used. This meant that the `Drop` implementation for that type wasn't used, so it didn't properly clear the map of loaded applications. That meant that the service runtime ended up leaking, and this prevents it from closing the endpoint to the execution state actor, so it never finishes running the query.
Restore the original contents of PR #2192, and use an instance of the `SyncRuntime` in `run_query`, so that it clears the loaded applications when the function …

Make `SyncRuntime` represent the execution lifetime (second attempt)

---

linera-views/src/scylla_db.rs
linera-views/src/test_utils/mod.rs

In ScyllaDb, we are currently doing the multi-key reading with a `join_all` which is suboptimal.
* The `run_reads` was updated by adding the reading of keys. Curiously the `read_value_bytes`was not tested before.
* Premature terminations if the set of keys is empty have been added. Several levels are needed since the LruCaching means that the final query could be empty while the initial one was not.
* The scenario code has been changed to get a larger variety of examples.
* The entry `k IN (?,?,?,?)` construction is used and this returns the values in disorder.
* Therefore a `HashMap<Vec<u8>,Vec<usize>>`Rust cannot deduce the types)  is needed to determine if a key is missing and the query of `k,v` allows to match the result with the queries.
The `Box::pin` is …

Implement multi key reading in one single requests in ScyllaDb.

---

linera-chain/src/chain.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state.rs
linera-execution/src/execution.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/test_utils/mod.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs

In order to keep services running across different queries, the `ServiceSyncRuntime` type must outlive the queries it handles. The runtime must run in a single thread and does not implement `Send` (because the `User{Contract,Service}Instance` types used for the `loaded_applications` does not implement `Send`). Therefore, the current approach of `spawn_blocking` the runtime thread only before handling a query does not work.
Make the service runtime run as an actor, executing on its own `spawn_blocking` thread and waiting for `ServiceRuntimeRequest`s to handle. The thread is started by the `ChainWorkerActor`, in preparation for the next PR which will use the incoming chain worker requests to determine if the runtime should be restarted or not.
Existing CI tests should catch any regressions, …

Run service runtime as an actor spawned by the chain worker

---

linera-service/src/cli_wrappers/remote_net.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/config.rs
linera-service/src/lib.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/persistent/file.rs
linera-service/src/persistent/mod.rs
linera-service/src/proxy.rs
linera-service/src/server.rs
linera-service/src/util.rs
linera-service/tests/end_to_end_tests.rs

The browser doesn't have access to a filesystem.  In order to store and load wallet configuration, we must use a different backend, such as [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage).  Currently, though, the `linera-service` crate assumes filesystem access, and stores configuration as JSON on the filesystem.
Generalize the `WalletState` struct with a new trait that represents any data that can be persisted.  Move the previous behaviour into an implementation of that trait specialized to filesystem storage.
CI.
None required.

Generalize client storage from the filesystem

---

linera-views-derive/src/lib.rs
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-2.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-3.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-4.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-5.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-6.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-7.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code-8.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__generate_crypto_hash_code.snap
linera-views/src/views.rs

The function `crypto_hash_mut` is required by Issue #2175.
The implementation is done straightforwardly.
No specific tests were implemented for this feature.
Not relevant.

Implement the `crypto_hash_mut` function

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs

The command `linera benchmark` was hanging because multiple `ChainWorkerActor`s were created to handle the same chain. This led to them attempting to acquire the chain guard, and blocking forever when it failed. The duplicate actors were created because the same process created more than one `WorkerState` instance.
Use the local node in the client instead of creating temporary `WorkerState` instances.
After this PR, `linera benchmark` now executes correctly.
Fixes a user visible bug, so at least a new patch version should be released.

Fix conflicting `ChainWorkerActor`s when running benchmarks

---

.github/workflows/rust.yml
linera-core/benches/client_benchmarks.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/worker.rs
linera-service/src/chain_listener.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/faucet.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs
linera-service/src/unit_tests/chain_listener.rs
linera-service/src/unit_tests/faucet.rs
linera-service/src/wallet.rs
linera-service/tests/end_to_end_tests.rs

In order to facilitate the creation of `ChainClient`s, move protocol- or chain-global state off the `ChainClient` and into the `Client`.
Add a `DashMap<ChainId, ChainState>` to the `Client`, and allow individual `ChainClient`s to access their state through their client reference.
CI.
None required.

`linera-core`: shared client state

---

.github/workflows/kubernetes.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml
linera-storage-service/Cargo.toml

* Avoid wasting $$ with long timeouts
* Shorten wait time
- restore global timeouts
- more verbose logs
- do not active the feature "rocksdb" by default in linera-storage-service
- remove preliminary build steps (whose features may not match the tests)
- ~~avoid recompiling linera CLI~~
- move web tests to a separate action
CI

CI improvements

---

linera-views/src/scylla_db.rs
linera-views/src/test_utils/mod.rs

The recently merged PR about the `read_multi_values_bytes` for ScyllaDb is sometimes the limit that queries need to have a size of at most 100.
The solution is to split queries into chunks of at most 100. This is done with the `join` logic that was used before.
A test with 150 entries has been added to the CI.
Not relevant.

Split `read_multi_values_bytes` queries for ScyllaDb in chunks of 100

---

linera-service/src/config.rs
linera-service/tests/end_to_end_tests.rs

In CLI commands, if no weights are specified, each new validator gets weight 100. This was done so that it's easy to later add e.g. a "half-weight" validator.
However, at genesis, validators are still assigned weight 1.
Assign weight 100 to each genesis validator, too.
Any regressions should be caught by existing tests.

Give validators weight 100 by default.

---

examples/hex-game/README.md
examples/hex-game/src/lib.rs
linera-service/src/chain_listener.rs
linera-service/tests/readme_test.rs

It's difficult to figure out how to use set up a game chain and play Hex on it.
Also, I was surprised that I needed to run `process-inbox` explicitly.
Add detailed instructions to the README.
Synchronize from the validators when starting the node service, so `process-inbox` does not need to be run manually.
Hex was added to the `readme_test` module.

Extend the hex-game README with detailed usage instructions; sync from validators in chain listener.

---

linera-chain/src/manager.rs
linera-core/src/client.rs

In #2133 I inadvertently introduced a race condition in which the client could propose two blocks at the same height at the same time.
Take a lock while building a block so that blocks are always strictly ordered.
CI, repeatedly.
Bugfix: no need.

`linera-client`: fix block height race

---

linera-service/tests/readme_test.rs

When running the README scripts tests, application logs were not being displayed. It also didn't work if the `RUST_LOG` environment variable was configured.
The cause was that the test always overrides the `RUST_LOG` environment variable with an incorrect value.
Fix the value configured for the `RUST_LOG` environment variable and only configure it if it's not already set, allowing the environment outside the test to configure the logging level.
I manually added some logs to the Counter example application and ran the readme tests. The logs appeared correctly, both when `RUST_LOG` was overriden and when it was not.
Nothing needed, because this only affects tests.

Improve logging in README tests

---

linera-views/src/hashable_wrapper.rs
linera-views/tests/hashable_tests.rs

The hashable wrapper did not invalidate the hash when the view is deleted which is potentially dangerous. This is an obstacle to the implementation of `has_pending_changes`.
The `fn flush` returns true if the views is deleted. This can happen in two scenarios:
* The view is cleared
* The `QueueView` is used and the `load_all`commend is used with a `new_back_values` that is empty.
In both scenarios, the view is deleted from the storage.
So, there is a scenario where we could get a value of `self.hash` in `hashable_wrapper` which is not trivial while it has been cleared:
* We call `clear` which sets `self.hash` to `None` in the hashable_wrapper.
* We compute the hash in hashable_wrapper which resets the hash to a value that is the value of the default.
* We do a `save` that calls the flush …

Set the `self.hash` to `None` in the `hashable_wrapper`

---

linera-core/src/updater.rs

During investigations of end-to-end test failures, it has appeared that in some cases no error occurred but the validators returned two different proposals. This error pattern was not covered.
The `NoConsensus` error is added to the enum statements.
The error contains the committee threshold and the obtained weights and the number of validators that proposed it.
That error sometimes occurred in tests but relatively rarely. The CI remains unchanged.
Not relevant.

Add another entry to `CommunicationError`.

---

linera-base/src/data_types.rs
linera-base/src/identifiers.rs
linera-chain/src/data_types.rs
linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-execution/tests/test_execution.rs
linera-sdk/src/contract/conversions_from_wit.rs
linera-sdk/src/contract/conversions_to_wit.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/contract/test_runtime.rs
linera-sdk/src/service/conversions_from_wit.rs
linera-sdk/src/service/conversions_to_wit.rs
linera-sdk/src/service/runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

We need a `read_blob` system API so that users are able to use blobs that were already published before. This is part of #2073
This implements the `read_blob` system API, handling the oracle records properly for it as well. For this PR we're not dealing with lagging validators, we'll do that in a following PR. For now if a validator doesn't have the blob, it'll just fail the block proposal.
Added a test for when we try to read a blob that wasn't published yet, and making sure we fail in that case.

read_blob system API

---

linera-client/src/client_context.rs
linera-client/src/client_options.rs
linera-client/src/config.rs
linera-client/src/persistent/file.rs
linera-client/src/persistent/mod.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/main.rs
linera-service/src/server.rs
linera-service/src/util.rs

We would like to introduce a browser-compatible storage backend for the wallet in order to manage wallets inside the [Web wallet](https://github.com/linera-io/linera-web).  While #2194 introduced the general framework to do so, the implementations in `linera-client` remained specific to the filesystem backend.
Generalize the implementations of client functionality in `linera-client` to any implementation of `Persist<Target = Wallet>`.
CI, since `linera-client` will be tested by the existing `linera-service` tests.
Backwards-compatible API change (minor bump).

`linera-client`: generalize over `Persist<Target = Wallet>` implementation

---

linera-base/src/data_types.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/lib.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/src/chain_worker/state.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-execution/src/execution.rs
linera-execution/src/runtime.rs
linera-execution/src/system.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/tests/fee_consumption.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-explorer/src/components/Block.test.ts
linera-explorer/src/components/Blocks.test.ts
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql
linera-service-graphql-client/src/service.rs

The `OracleResponses` and `OracleRecord` types were just wrappers for iterators or vectors of responses, and are not really needed. The former was also a source of potential bugs: When replaying, we _still_ want to return the replayed oracle responses together with the execution outcomes, so they end up in the `ExecutedBlock`. Also, when executing a system operation that created an application, we should still preserve the oracle responses returned by the initial system operation, rather than _overwriting_ them with the ones from the contract initialization. (This potential bug didn't manifest itself yet, since so far no system operation both uses an oracle and creates an application.)
Remove the two types, and fix the potential issues.
I changed the assertion in `process_confirmed_block` …

Remove the OracleRecord and OracleResponses types; never throw away responses.

---

Cargo.lock
examples/amm/README.md
examples/amm/src/lib.rs
examples/crowd-funding/src/contract.rs
examples/matching-engine/README.md
examples/matching-engine/src/lib.rs
linera-base/Cargo.toml
linera-base/tests/command_tests.rs
linera-service/src/cli_wrappers/helmfile.rs

https://github.com/linera-io/linera-protocol/pull/2235 enabled some tests that had accidentally been disabled due to a missing feature flag.  However, those tests do not compile, thereby now breaking builds using `--all-targets`.
In addition, the `examples` directory contained some crates that are no longer `clippy`-clean.
Disable the tests, adding issue https://github.com/linera-io/linera-protocol/issues/2239 to track the fix.  Tweak the formatting of the `examples` crates to be `clippy`-clean.
None required.

Fix lints + disable non-compiling test module

---

linera-views-derive/src/lib.rs
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_C.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_C_with_where.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_CustomContext.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_CustomContext_with_where.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__GenericContext_T_.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__GenericContext_T__with_where.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__path__to__ContextType.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_custom__path__to__ContextType_with_where.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_C.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_C_with_where.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_CustomContext.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_CustomContext_with_where.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__GenericContext_T_.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__GenericContext_T__with_where.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__path__to__ContextType.snap
linera-views-derive/src/snapshots/linera_views_derive__tests__test_generate_view_code_metrics_custom__path__to__ContextType_with_where.snap
linera-views/src/collection_view.rs
linera-views/src/common.rs
linera-views/src/hashable_wrapper.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lib.rs
linera-views/src/log_view.rs
linera-views/src/map_view.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/register_view.rs
linera-views/src/set_view.rs
linera-views/src/views.rs

The loading of the views leads to a flurry of independent `read_value_bytes` which strain the storage. This PR groups the access into a single query.
* The `pre_load` and `post_load` are introduced.
* The `NUM_INIT_KEYS` static variable is introduced because so far the loading leads to a constant number of reads per view.
* The `fn load` was changed to use the `pre_load` / `post_load`.
Next steps:
* Possibly put the `fn load` as a trait function. But we have now 3 kinds of such load functions so maybe the unification is not a good idea.
* Change the `try_load_entries_mut` of `reentrant_collection_view` so that it uses the `pre_load` / `post_load`.
The CI of the view is already challenging enough and do not need to be expanded.
How much of an improvement has been …

Implement `pre_load`/ `post_load`for the views.

---

linera-chain/src/chain.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/test_utils/mock_application.rs
linera-execution/src/test_utils/mod.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs
linera-sdk/src/service/mod.rs

Application services have a read-only view of the application state on a chain. They were initially designed to be short-lived, handling a single query per execution. However, that is inefficient for some applications that may want to cache data in memory to handle multiple queries (e.g., the LLM example could store the AI model weights in memory).
Make services long-lived, restarting them only if the worker executes an operation that may change the chain state.
Two new unit tests were written for long-lived services.
A new major version (or equivalent version representing a breaking change) should be released, because this new feature can lead to incompatible behavior with applications that expect the service to restart after every query.
- [reviewer …

Make application services keep running across queries

---

linera-core/src/unit_tests/worker_tests.rs

After #2216 was merged, the Scylla DB tests in CI started failing on main. This happens because the test uses Tokio's paused time feature, where the clock is advanced as much as possible every time the workers become idle. This means that all timeouts fire immediately after a real packet is sent over the network, because the workers become idle while waiting for the response.
Don't pause time in the new tests.
This fixes some tests in CI, so CI should pass with this PR.
Nothing needed, because it only changes two tests.

Unfreeze time in long-lived service tests

---

examples/meta-counter/src/contract.rs
linera-base/src/identifiers.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-explorer/src/components/Block.test.ts
linera-explorer/src/components/Blocks.test.ts
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/contract/conversions_to_wit.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/contract/test_runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql
linera-service-graphql-client/src/service.rs

Event streams will in the future replace broadcast channels, and also enable other blockchains to more easily interpret Linera data, e.g. to facilitate bridges.
As a first step, add an `emit` method to the contract runtime, and record emitted events in blocks.
An `emit` call was added to the meta-counter, and we assert that the event is in the resulting certificate.
- Closes https://github.com/linera-io/linera-protocol/issues/2229.

Contracts can emit events, record them in blocks.

---

examples/llm/README.md
examples/llm/src/lib.rs
examples/llm/src/service.rs

With the recent support to keep services running across queries (PR #2216), the LLM application can be optimized to not have to fetch the model weights on every query.
Fetch the model when the service is created, and reuse it in every query.
Tested manually, and saw an expected decrease in latency after the first query (for which the service is initially created).
Nothing needed, because only changes an example application.

Cache the LLM model inside the service

---

linera-sdk/src/test/block.rs
linera-sdk/src/test/chain.rs
linera-sdk/src/test/validator.rs

While writing a benchmark to attempt to stress the CPU, there was some contention to access the `WorkerState`. That happened because the integration test helpers in `linera-sdk` shared the same `WorkerState` instance using an `Arc<Mutex<_>>`. This is unnecessary, because the `WorkerState` was designed to be cloned for each request, and has internal fields which are properly shared.
Clone the `WorkerState` when needed, and don't wrap it in an `Arc<Mutex<_>>`.
Tested manually with the benchmark, but CI should catch any regressions because this is an internal refactor.
Nothing needed because this is an internal refactor.

Fix contention for `WorkerState` in SDK integration test framework

---

linera-base/src/tracing.rs
linera-chain/src/chain.rs
linera-execution/src/execution_state_actor.rs
linera-views/src/reentrant_collection_view.rs
linera-views/tests/random_container_tests.rs

The `try_load_entry_or_insert` has the annoying feature that it takes a `&mut self` and returns a readable object.
* The `try_load_entry_or_insert` is eliminated.
* The tests are adjusted accordingly.
* The code is changed so that the missing is handled in the code.
* The `load_entry_or_insert` of `CollectionView` is removed as well.
CI
Not relevant.

Remove the `try_load_entry_or_insert` from the `ReentrantCollectionView`.

---

linera-sdk/src/test/block.rs
linera-sdk/src/test/validator.rs

During my attempts to create a benchmark with native token transfers, I leveraged the code from `linera-sdk`'s integration test framework. However, there was no way to do native token transfers, and this feature will likely be needed for application tests.
Add a helper method that allows adding native token transfers to blocks. Also mint all native tokens at once and place them in the admin chain.
Test manually, by running the benchmark that performs multiple transactions.
A new minor SDK release to include the new feature.

Add test helpers for native token transfers

---

linera-service/tests/end_to_end_tests.rs

Local running of the `test_wasm_end_to_end_non_fungible::scylladb_grpc` produced the error `Error: invalid type: null, expected struct NftOutput` in about 23% of the runs. This is an annoying problem.
The solution taken was to reorder the `process_inbox` operations after the
```
app1.claim(
&fungible::Account {
chain_id: chain2,
owner: account_owner1,
},
&nft1_id,
&fungible::Account {
chain_id: chain1,
owner: account_owner1,
},
)
.await;
```
When the code is run it bumps in the contract code of `execute_operation` with
```
if source_account.chain_id == self.runtime.chain_id() {
let nft = self.get_nft(&token_id).await;
self.check_account_authentication(nft.owner);
self.transfer(nft, target_account).await;
} else {
self.remote_claim(source_account, token_id, target_account)
}
```
The `if` …

Correct the ordering of the process_inbox operations for the NFT test

---

linera-sdk/src/test/validator.rs

When running integration tests, there should be native tokens available for test transfers. The admin chain was supposed to have all minted tokens when the test starts in #2278, but the change was left out by mistake.
Set the admin chain's balance to `Amount::MAX` when it is created.
Tested manually while running a transfers benchmark without IO.
Nothing needed, because this fixes a bug that is not present in any released versions.

Mint all native tokens when creating admin chain

---

CLI.md
linera-client/src/chain_listener.rs
linera-service/src/schema_export.rs

Help debug missing or misplaced "process_inbox" commands in e2e tests (e.g. #2281)
* e2e tests cannot rely on the automatic process-inbox behavior of the node service because of race conditions.
* We are placing `process_inbox` commands manually but it's easy to make mistakes and unstable tests.
Create option `--listener-skip-process-inbox` to deactivate process inbox in the chain listener.
This forces deterministic block production in e2e tests
* Cherry-pick https://github.com/linera-io/linera-protocol/pull/2283/commits/0c01a570e5fee3360e5813aca7c3ce00e8a2f54e from PR #2283 to reactivate the test below for the storage service
* Run
```
cargo run --release --bin storage_service_server memory -- --endpoint 127.0.0.1:1235
LINERA_CLIENT_SERVICE_PARAMS=--listener-skip-process-inbox …
```

Add option to skip "process_inbox" in the node service

---

.github/workflows/rust.yml
linera-storage-service/Cargo.toml
linera-storage-service/src/common.rs
linera-storage-service/src/server.rs
scripts/run_local.sh

All Linera binaries follow the pattern `linera-xxx`
Rename `storage_service_server` into `linera-storage-server`
CI

rename storage_service_server into linera-storage-server

---

linera-service/src/cli_wrappers/wallet.rs
linera-service/src/proxy.rs
linera-service/tests/end_to_end_tests.rs

`test_end_to_end_reconfiguration` in TCP mode is failing, unless validator 5 (which never gets removed in the test) has a very high voting weight.
Don't restart a validator's shard with TCP: The proxy only seems to reconnect successfully with gRPC.
(I also added the address to the log message when a proxy fails to forward a message to a shard, so that we know which shard can't be reached. It helped me debug this.)
In the loop where we remove the first four validators, always process the inbox _before_ shutting down the removed validator: If there are less than four validators left, removing one means the others don't have a quorum, so the clients must process the change while the validator is still up.
The test now uses the same weight (100) for all validators.
- Closes …

Fix reconfiguration end-to-end test.

---

linera-chain/src/chain.rs
linera-core/src/chain_worker/state.rs
linera-core/src/updater.rs
linera-views/src/reentrant_collection_view.rs
linera-views/tests/random_container_tests.rs

The `try_load_entries` is inserting entry in the view which is not great for a `&self`. This was corrected. Also, the `pre_load` / `post_load` could be used to improve the code.
The implementation was straightforward. Now the `try_load_entries` is returning a `Vec<ReadGuarded<W>>`.
The next step would be to use the `contains_keys` operation in the `try_load_entries`.
CI. The tests have been changed accordingly.
Not relevant.

Changes to `try_load_entries(_mut)`

---

linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/views/mock_key_value_store.rs
linera-sdk/src/views/system_api.rs
linera-sdk/wit/view-system-api.wit
linera-storage-service/proto/key_value_store.proto
linera-storage-service/src/client.rs
linera-storage-service/src/server.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/indexed_db.rs
linera-views/src/journaling.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lru_caching.rs
linera-views/src/memory.rs
linera-views/src/metering.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/test_utils/mod.rs
linera-views/src/value_splitting.rs

It has emerged from code inspection that several `contains_key` operations can be grouped together to
bring speed improvement to the code. This PR introduces the trait function. The use in the code will come
in later PRs.
The implementation was done in a very straightforward way and without difficulties considering
that we already have the `contains_key` and the `read_multi_values_bytes` functions.
For the test, only a few lines were added to the `run_reads` function that does the job in question.
The documentation will need to be updated.

Introduce the function `contains_keys` for the `KeyValueStore` trait.

---

linera-base/src/crypto.rs
linera-client/src/client_context.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/grpc/server.rs
linera-rpc/src/mass_client.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-sdk/src/test/chain.rs
linera-service/src/linera/main.rs
linera-service/src/schema_export.rs

We currently have a situation in `linera-core` in which we lock an async `Mutex` and then perform an async task (to communicate with validators over the network).  This makes it difficult to access different chain clients at the same time, as failure to drive the task holding the lock can result in deadlocks.
Remove the offending mutex entirely.  `tonic::client::Grpc` is the root cause of the mutability requirement, but can be easily and cheaply cloned, removing the need for the mutex.
Incidentally, there was a trait `linera_core::worker::ValidatorWorker` that was never abstracted over; I've removed this after confirming with @afck we had no plans to abstract over it in the future.
CI.
Refactor only: no special care required.
- [reviewer …

`linera-core`: remove double-locking behaviour

---

linera-core/src/chain_worker/state.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs
linera-views/src/common.rs
linera-views/src/reentrant_collection_view.rs

After the merging of the PR implementing `contains_keys`, it is important to implement its usage over the code. This was done as well as other corrections.
* The `try_load_entries` is now using the `contains_keys` instead of a vector of handles and a `join`.
* In the storage, the function `write_hashed_certificate_values_hashed_blobs_certificate` was introduced which allows grouping 3 different writes into a single one. 
* The `contains_hashed_certificate_values` was introduced in order to group the contains operations.
* The `contains_blobs` was introduced in order to group the calls into a single one.
* The `contains_certificate` and `read_certificate` codes are grouped into a single operation. No more join.
CI
Not relevant.
- [reviewer …

Implement the use of `contains_keys` and other corrections.

---

CLI.md
linera-client/src/client_options.rs
linera-client/src/config.rs
linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/message.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/grpc_proxy.rs
linera-service/src/linera/main.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs
linera-service/tests/end_to_end_tests.rs

Before adding a new validator to a testnet we want to check whether they are online and have a compatible version and genesis config.
Make `set-validator` check the validator's version and genesis config before creating the new committee. (Can be omitted with `--skip-online-check`.)
Add a `query-validator` command that works just like `query-validators`, but instead of querying the current committee it queries a given address, and it prints a warning if the version or genesis config is incompatible.
`set-validator` is already used, and `query-new-validator` was added to the reconfiguration end-to-end test.
- Closes https://github.com/linera-io/linera-protocol/issues/2288

Add query-validator command, and make set-validator check version.

---

linera-chain/src/chain.rs
linera-core/src/chain_worker/state.rs
linera-core/src/updater.rs
linera-views/src/reentrant_collection_view.rs

The code has several times the following pattern
```
let indices = view.indices().await?;
let subviews = view.try_load_all_entries(&indices).await?;
```
which is inherently inefficient. 
The `try_load_all_entries` and `try_load_all_entries_mut` are introduced and used in the code.
The `try_load_all_entries` is used appropriately in the code which results in an overall simplification of the code.
The CI.
Not relevant.

Implement `try_load_all_entries` for `ReentrantCollectionView`.

---

.github/workflows/rust.yml
linera-base/src/tracing.rs
linera-rpc/src/grpc/server.rs
linera-service/src/benchmark.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/proxy.rs

There is currently a typo in the `linera-service` tests that [results in an error](https://github.com/linera-io/linera-protocol/pull/2257/files#r1686167112) and presumably fails to show debug logs from some parts of our tests.
Our tracing subscriber currently chooses a JSON output automatically if `stderr` is not connected to a TTY; I believe this is sensible behaviour in general but we should be able to override it, since sometimes we want human-readable output from subprocesses whose output is processed.
Fix the typo.  Add a `plain` log format and activate it explicitly in CI.  Set our CI log level to `DEBUG` so we see `INFO` and `DEBUG` messages that can be helpful for our developers to understand what's gone wrong in a CI run.
Check CI output.
None needed.
- [reviewer …

Improve logging output

---

linera-execution/src/lib.rs

Events were renamed to messages but a comment wasn't updated.
Update comment.

Fixed typo on MessageKind

---

Cargo.lock
linera-views/Cargo.toml
linera-views/benches/reentrant_collection_view.rs

While updating #2274, I saw a tiny refactor opportunity and thought it would improve readability and slightly increase performance.
However, I didn't see that @MathieuDutSik already had opened PR #2294 for the change. I also wrote a micro-benchmark for the change, and that's what this PR contains instead. The benchmark shows that there's an improvement when the method is used.
Add a micro-benchmark to compare the usage of the `try_load_all_entries`
Nothing needed, because this only adds a benchmark.
Nothing needed, because this only adds a benchmark.

Benchmark `ReentrantCollectionView::try_load_all_entries`

---

linera-chain/src/data_types.rs
linera-chain/src/lib.rs
linera-core/benches/client_benchmarks.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/node_service.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

We need to update lagging validators if they're not aware of blobs that have already been published.
A few things had to be done here:
- Write the actual code to update the lagging validators. This is initially used in two places: when we're first staging block execution, and when we're synchronizing the chain state from the validators.
- Created test only `ReadBlob` `SystemOperation` to be able to test this without creating or modifying existing applications.
- Added `hashed_certificate_values` and `hashed_blobs` to `process_validated_block`. This was an existing bug because we check for missing blobs there, but didn't pass the information along on a retry.
- We had to move `synchronize_chain_state` and `try_synchronize_chain_state_from` to the client, so that we could properly call the …

Update lagging validators on blob reads

---

.github/workflows/documentation.yml

I'm seeing a suspicious failure on main
Use `cargo install --locked` for this test
CI

CI: lock dependencies in cargo install

---

flake.lock

Currently our Nix environment doesn't include Rust 1.80, so builds using Nix (e.g. on GitPod) will fail.
Bump our Nix flake to include Rust 1.80 in our Nix environment.
Tested locally.
No special handling required.

`flake.lock`: update to enable Rust 1.80

---

linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/client_tests.rs

Many `ChainClient` methods are undocumented. The test-only `read_blob` is used only twice.
Add documentation, remove `read_blob`. Also use `while let` instead of `loop` where appropriate and add a few trace logs.
CI

Minor cleanups in the ChainClient implementation.

---

linera-views/src/reentrant_collection_view.rs
linera-views/src/unit_tests/views.rs

CI failed with PR #2273. The investigation showed that `ReentrantCollectionView::has_pending_changes` returns `true` if there was a previous call to `ReentrantCollectionView::try_load_entries`.
This happens because `has_pending_changes` checks if its `updates` map is empty, but `try_load_entries` needs to insert loaded entries into the map in order to ensure that they are safely accessed.
Keep track of the entries that have been loaded from disk but are unchanged, using a separate `BTreeMap`.
A few of unit tests were added to reproduce the issue. The first test fails before this PR and passes with this PR, and the other two tests cover bugs temporarily introduced while implementing the proposed fix.
- Need to …

Fix `ReentrantCollectionView::has_pending` returning `true` if it has cached but unchanged entries

---

linera-service/tests/end_to_end_tests.rs

With the advent of the `ProcessInbox::Skip` we can identify some `process_inbox` operations that are not needed.
* 2 process inbox operations related to transfer were removed.
* 1 process inbox related to the matching engine was removed.
* Documentation of `process_inbox` when available was put.
The CI.
Not relevant.

Remove 3 `process_inbox` that are not needed.

---

linera-service/tests/end_to_end_tests.rs

CI was having intermittent failures when running the `test_wasm_end_to_end_social_user_pub_sub` test ([e.g.](https://github.com/linera-io/linera-protocol/actions/runs/10160563243/job/28097195712#step:8:8087)). This was caused by a race condition between the poster and the subscriber, where sometimes the poster would post a message before handling the subscriber's subscription request.
Process the inbox of the poster before posting the message. An assertion was also added to check that the poster's node service contains the subscriber's block requesting for the subscription. This increases the chance that it has already produced a block to accept the subscription.
Nothing needed, because this only fixes a bug in an existing test.
Nothing needed, because this only affects tests.
- [reviewer …

Fix subscription race condition in social pub-sub test

---

linera-base/src/tracing.rs

We have several places in our code where we effectively nuke the environment, so can't override this behaviour with `RUST_LOG_FORMAT=plain`, but nevertheless still want non-JSON output. 
Don't output JSON when `stderr` is not a terminal, just disable ANSI colouring.
Check CI.
Mostly a cosmetic change; no version bump required.

`linera_base::tracing`: don't try to guess when the caller wants JSON

---

linera-core/src/chain_worker/actor.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/worker.rs

Currently the `linera_core::worker` has a pattern in which it takes an async mutex (`futures::lock::Mutex`) and holds it while doing other async work.  This results in deadlocks if the future that holds the mutex is not known and being polled at the same time.  
Restructure `linera_core::worker` so that mutexes are not held over `await` points.  Once this is done, there is no need to use the heavyweight `futures::lock::Mutex`, and we can replace it with the much lighter `std::sync::Mutex`, whose guards also conveniently don't implement `Send` and so will error if accidentally held over an `await` point.
Also, add a (static) test to ensure that the future returned from `ChainClient::listen` (with memory storage and the test provider) is `Send`, ensuring that even if we remove …

`linera_core::worker`: don't hold mutexes over `await` points

---

linera-base/src/data_types.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/client_tests.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/system.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/contract/conversions_from_wit.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/service/conversions_from_wit.rs
linera-sdk/src/service/runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-service/src/node_service.rs
linera-storage/src/lib.rs

The `HashedBlob` type should guarantee that, unless you use a function containing `unchecked`, the hash in the ID always matches the content.
Make `HashedBlob` fields private
CI

Make HashedBlob's fields private

---

linera-base/src/data_types.rs
linera-base/src/identifiers.rs
linera-client/src/client_context.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/value_cache_tests.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/contract/conversions_from_wit.rs
linera-sdk/src/contract/conversions_to_wit.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/service/conversions_from_wit.rs
linera-sdk/src/service/conversions_to_wit.rs
linera-sdk/src/service/runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-storage/src/db_storage.rs

As we replace different existing functionality with blobs, we'll need different blob types.
Make `BlobId` into an enum
CI

Make BlobId into enum

---

examples/llm/README.md
examples/llm/src/lib.rs

Since #2258, the model is no longer downloaded from a local server. Unfortunately the README was not updated to reflect that.
Update the README file to remove the mention of setting up a local HTTP server with the models.
CI should catch any issues with the README file.
Nothing needed, because this only changes the README file.

Remove python HTTP server from LLM example README

---

linera-views/src/hashable_wrapper.rs
linera-views/src/lru_caching.rs

The async locks are not adequate for the locking of memory resources. It is preferable to simply wait for the memory to be released.
* The `Mutex` in `hashable_wrapper` is replaced from async_lock to sync lock.
* The same is done for the Lru caching. This requires eliminating the drop and replacing it with scopes.
The next steps are doing the same for `ReentrantCollectionView` and `KeyValueStoreView`.
The CI.
Not relevant.

Replace async locks by sync locks in `HashableWrapper` and `LruCachingStore`.

---

linera-execution/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/src/views/mock_key_value_store.rs
linera-views/benches/reentrant_collection_view.rs
linera-views/src/batch.rs
linera-views/src/collection_view.rs
linera-views/src/key_value_store_view.rs
linera-views/src/log_view.rs
linera-views/src/map_view.rs
linera-views/src/memory.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/register_view.rs
linera-views/src/set_view.rs
linera-views/src/unit_tests/views.rs
linera-views/src/value_splitting.rs
linera-views/tests/hashable_tests.rs
linera-views/tests/random_container_tests.rs
linera-views/tests/store_tests.rs
linera-views/tests/views_tests.rs

The work on the global memory store revealed some issues with the memory context/store. They are here addressed separately.
* Renaming `TestMemoryStoreInternal` as `LimitedMemoryStore`.
* Eliminate `TestMemoryStore`.
* Rename `create_memory_store` as `create_test_memory_store` and same for `context`.
* Put `create_test_memory_context/store` under a `#[cfg(with_testing)]` which forces some changes in two `Cargo.toml` files.
CI.
Not relevant.

Several memory store refactorings.

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-service/Cargo.toml
linera-version/Cargo.toml
linera-version/api-hashes.json
linera-version/build.rs
linera-version/src/main.rs
linera-version/src/version_info/mod.rs
linera-version/src/version_info/type.rs
linera-version/tests/up_to_date.rs
scripts/test_publish.sh

Currently `linera-service --version` is broken on installations resulting from `cargo install linera-service`.  This is because the information we need to generate the API hashes (from `linera-rpc`, `linera-sdk`, and `linera-service-graphql-client`) isn't necessarily available at build time, these crates not being dependencies of `linera-service`.
Instead, compute the hashes at commit-time, except for the git commit hash, which would be computationally difficult to commit to git.  The git commit hash can instead be read from a special-purpose file `.cargo_vcs_info.json` added to the packaged crate by `cargo publish` at publish time.
Also, add a test to CI that ensures that file is up-to-date.
I have tested locally by modifying my Cargo cache, and by using the `scripts/test_publish.sh` …

`linera-version`: use a committed cache of the API hashes

---

linera-chain/src/inbox.rs
linera-chain/src/outbox.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/applications.rs
linera-execution/src/test_utils/system_execution_state.rs
linera-storage-service/src/server.rs
linera-storage/src/memory.rs
linera-views/src/key_value_store_view.rs
linera-views/src/memory.rs
linera-views/src/test_utils/mod.rs
linera-views/src/value_splitting.rs
linera-views/tests/admin_tests.rs
linera-views/tests/store_tests.rs
linera-views/tests/views_tests.rs

The memory store has the weakness that it does not implement the namespace. Each instance is a specific one.
* A global variable `MEMORY_STORES` for storing the existing memory stores is introduced.
* The implementation uses `std::sync::Mutex` to avoid being async.
* The switch from `read().await` to `read()?` leads to some `PoisonError` being emitted which are converted with relevant `From` operators.
* The `now_or_never` calls are eliminated when the stores are created, which is cleaner. The `async` features of the stores are blanks.
* The `MemoryStore` is now using a `Arc<RwLock<MemoryStoreMap>>` and the `MutexGuard` is eliminated.
* The `admin_test` has been added for the `memory` and the `admin_test` has been strengthened by adding multiple connections to the …

Make the memory stores persistent within a run.

---

linera-service/src/schema_export.rs

`cargo run --locked --bin linera-schema-export` fails with:
```
thread 'main' panicked at linera-service/src/schema_export.rs:168:10:
storage: NotExistentNamespace
```
Call `MemoryStorage::initialize` instead of `MemoryStorage::new`, to create the namespace.
With this change, `linera-schema-export` works for me locally.
- Possibly related: https://github.com/linera-io/linera-protocol/pull/2316

Fix schema_export: create namespace before using it.

---

examples/non-fungible/README.md
examples/non-fungible/src/contract.rs
examples/non-fungible/src/lib.rs
examples/non-fungible/src/service.rs
linera-base/src/data_types.rs
linera-sdk/src/service/test_runtime.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/end_to_end_tests.rs

Right now we just have the NFT's image "payload" (the bytes of the image) loaded in the example app's state.
Let's use blobs instead for that
e2e test was modified to work with blobs

Add blobs to NFT example

---

examples/crowd-funding/tests/campaign_lifecycle.rs
examples/fungible/src/lib.rs
examples/fungible/tests/cross_chain.rs
examples/matching-engine/tests/transaction.rs
linera-chain/src/data_types.rs
linera-sdk/src/test/block.rs
linera-sdk/src/test/chain.rs
linera-sdk/src/test/mod.rs
linera-sdk/src/test/validator.rs

After https://github.com/linera-io/linera-protocol/issues/1475, we won't be able to accept or reject messages individually anymore, only whole message _bundles_. The linera-sdk tests currently handle messages individually, by ID.
Use messages from a whole certificate instead. Return the certificate from `try_sign`.
The existing tests should catch regressions.
- Preparation for https://github.com/linera-io/linera-protocol/issues/1475

Don't use individual message IDs in linera-sdk testing.

---

linera-storage-service/src/server.rs

A typo in the input prevents the use of RocksDb for the linera-storage-service.
The problem is addressed directly.
It has been tested locally that after the correction, the storage-service works with RocksDb.
Not relevant.

Correct an issue for the memory-storage-service.

---

linera-views/src/key_value_store_view.rs
linera-views/src/reentrant_collection_view.rs

It is preferable to use sync locks for memory access when possible.
For the `KeyValueStoreView` the work is very similar to the for `HashableWrapper`.
For the `ReentrantCollectionView` the mutex is eliminated. However, a way to remove the inner async `RwLock` could not be found.
The compilation and the CI.
Nit relevant.

Replace async locks by sync locks for `KeyValueStoreView` and `ReentrantCollectionView`.

---

examples/non-fungible/README.md
examples/non-fungible/src/contract.rs
examples/non-fungible/src/lib.rs
examples/non-fungible/src/service.rs
examples/non-fungible/web-frontend/src/App.js
linera-base/src/identifiers.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/contract/conversions_from_wit.rs
linera-sdk/src/contract/conversions_to_wit.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/contract/test_runtime.rs
linera-sdk/src/lib.rs
linera-sdk/src/service/conversions_from_wit.rs
linera-sdk/src/service/conversions_to_wit.rs
linera-sdk/src/service/runtime.rs
linera-sdk/src/service/test_runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-service/tests/end_to_end_tests.rs

We don't want `BlobId` exposed to the SDK. Users will only be aware of `Data` blobs, the other types will be only internally used.
Only expose `Data` blobs to the SDK, and assume when dealing with blobs that it's a `Data` blob. Because of that we don't need to use `BlobId` everywhere, and can just use the hash of the `Data` blob in most places.
CI + also retested the NFT UI

Ensure only data blobs are present in SDK/System API calls

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-execution/tests/test_execution.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/wit/contract-system-api.wit

The `open_chain` method allows contracts to create new chains. It returns the new chain ID. To assign a key to the new chain and add it to their wallet, users need the _message ID_, however.
Return both the message ID and the chain ID.
The test was extended.
This will also be used in the hex-game example soon.
- #2326 

open_chain returns the message ID.

---

linera-execution/src/execution.rs

For any bundle with user applications, `RegisterApplications` is retroactively inserted at the beginning to make sure those applications are registered in the recipient chain. This is a problem if the first message is `OpenChain`, which is required to be the first message in the bundle.
Insert `RegisterApplications` before the first _user_ application instead of at the beginning. This makes sure that `OpenChain` is never replaced as the bundles first message, and keeps its message ID correct in more (but not all) cases.
Tests should catch any regressions. The workaround itself will be used and tested in an upcoming PR, where hex-game will create its own temporary chains.
- This is a partial workaround for https://github.com/linera-io/linera-protocol/issues/2362
- [reviewer …

Insert RegisterApplications before the first user outcome.

---

linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-core/src/chain_worker/state/temporary_changes.rs

The linera-sdk `TestValidator` directly calls `execute_block`, without first handling the immediate message. That currently fails if it's the first block of a new child chain, because it has not been initialized yet.
In `execute_block`, if it's block 0 of a child chain and the first message is `OpenChain`, execute that message before doing anything that requires the chain to be active.
The feature itself was tested locally and will be used soon when the hex-game is extended to automatically create temporary chains.

ChainStateView::execute_block can now activate a chain.

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-core/src/client.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/Cargo.toml
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/test/chain.rs
linera-storage/src/lib.rs

Sometimes publishing application fails because the bytecodes are too large, and hit gRPC message size limits when sending the block proposal.
Compress the bytecodes using Zstandard when including them in the `SystemOperation::PublishBytecode`. Use a new `CompressedBytecode` type to represent the compressed bytecode, and make it simple to convert to and from an uncompressed `Bytecode`.
CI should catch any regressions, since end-to-end tests cover publishing bytecodes and using them in applications.
A new major version must be released, because this breaks backward compatibility with bytecode publishing.

Compress Wasm bytecodes when publishing

---

linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/test_utils/mock_application.rs

- Resolve #2249
- split the `assert_no_more_expected_calls` into two - itself & `assert_no_active_instances`
CI

feat: split-off `MockApplication::assert_no_more_expected_calls` into two

---

.github/workflows/rust.yml
linera-service/src/schema_export.rs

https://github.com/linera-io/linera-protocol/pull/2348 broke the `schema_export` by reverting https://github.com/linera-io/linera-protocol/pull/2350. 
Fix it again, and add it to CI to make sure it won't break again.
Added a check to CI, not only that `schema_export` works, but also that the schema is up-to-date.

Fix schema_export

---

examples/Cargo.lock
examples/Cargo.toml
examples/fungible/src/contract.rs
examples/hex-game/Cargo.toml
examples/hex-game/README.md
examples/hex-game/src/contract.rs
examples/hex-game/src/lib.rs
examples/hex-game/src/service.rs
examples/hex-game/src/state.rs
examples/hex-game/tests/hex_game.rs
linera-sdk/src/test/chain.rs

We want to make it easier to create temporary chains, and demonstrate that in the example applications.
As a first step, make `hex-game` create its temporary chains automatically, rather than having the users set them up manually.
The tests were extended.
- Preparation for #2326.

Make hex-game create temporary chains for each game.

---

.github/workflows/rust.yml
linera-execution/Cargo.toml
linera-execution/src/lib.rs
linera-execution/src/runtime.rs

The `http_post` oracle is only safe if all validators use an HTTP proxy (https://github.com/linera-io/linera-protocol/issues/2188). Both `http_post` and `query_service` will need fees and limits (https://github.com/linera-io/linera-protocol/issues/2127).
For now, feature-gate these oracles. With the default features, they are not enabled and contract calls that try to use them fail.
Users can continue to develop applications with them if they use the `unstable-oracles` feature for local development, but the public testnets will only support them once they are safe.
This does _not_ disable blobs, which also use the oracle mechanism, since they are essential to the system. Fees and limits for them will be added soon as part of https://github.com/linera-io/linera-protocol/issues/1981.
The …

Feature-gate the http_post and query_service oracles.

---

linera-indexer/lib/src/indexer.rs
linera-indexer/lib/src/plugin.rs
linera-indexer/lib/src/runner.rs
linera-indexer/lib/src/service.rs
linera-indexer/plugins/src/operations.rs
linera-sdk/src/views/system_api.rs
linera-storage-service/src/client.rs
linera-storage-service/src/common.rs
linera-storage/src/db_storage.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/indexed_db.rs
linera-views/src/journaling.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lru_caching.rs
linera-views/src/memory.rs
linera-views/src/metering.rs
linera-views/src/rocks_db.rs
linera-views/src/scylla_db.rs
linera-views/src/test_utils/mod.rs
linera-views/src/value_splitting.rs

The use of the `AdminKeyValueStore` makes the code quite complicated in the `linera-storage`. A cleanup is needed in that respect.
Ideally, we would like to have `KeyValueStore = ReadableKeyValueStore + WritableKeyValueStore + AdminKeyValueStore`. However, this can not be done due to two obstacles:
* The `ViewContainer` is taking a `Context` to build a store. So, if it were to implement the `AdminKeyValueStore` then it would need to have the `Config` type and that is just the first problem that comes to mind.
* The `MeteredStore` cannot create its own store without knowing where to put the metrics and there is no simple way to do that since this is context-dependent.
Therefore, the solution was to have a `KeyValueStore` that implements all 3 traits and a `RestrictedKeyValueStore` that …

Change of the `KeyValueStore`trait.

---

examples/meta-counter/src/contract.rs
examples/meta-counter/src/lib.rs
linera-core/Cargo.toml
linera-core/src/unit_tests/wasm_client_tests.rs

As of https://github.com/linera-io/linera-protocol/pull/2396, `cargo test` fails because the `query_service` oracle call isn't allowed anymore.
Make the failing test only trigger the oracle call if the `unstable-oracles` feature is enabled.
`cargo test` passes for me now, both with and without the flag.

Make cargo test work with and without the unstable-oracles feature.

---

CLI.md
linera-client/src/client_context.rs
linera-client/src/client_options.rs
linera-client/src/util.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs

Some clients (for example the faucet) should only process incoming messages from pre-specified chains (for example the admin chain for epoch changes).
Modify `MessagePolicy` to have a notion of a restricted chain.

Message Policy accepts messages from specific chains.

---

Cargo.lock
examples/Cargo.lock
linera-client/src/storage.rs
linera-core/Cargo.toml
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-indexer/lib/src/rocks_db.rs
linera-service/src/cli_wrappers/local_net.rs
linera-storage-service/src/server.rs
linera-storage/Cargo.toml
linera-storage/src/rocks_db.rs
linera-views/benches/stores.rs
linera-views/src/rocks_db.rs
linera-views/src/unit_tests/views.rs
linera-views/tests/admin_tests.rs
linera-views/tests/store_tests.rs
linera-views/tests/views_tests.rs

The RocksDb test stores require tracking of the temporary directory. This complicates working with that store and prevents further unification with other stores that do not require them.
* The `PathWithGuard`type is introduced for the RocksDb.
* This allows the removal of `_dir` entries all around.
The next step is to introduce the creation of a default test config in `AdminKeyValueStore`. But since that work is fairly independent from this one, this is for another PR.
The CI.
Not relevant.

Make the temporary directory of the RocksDb instances part of the store and the configuration.

---

examples/social/src/contract.rs
examples/social/src/lib.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql

Some channels, like the admin one, have a lot of subscribers. Handling all the `Subscribe` messages on-chain causes scalability issues.
In the long term, channels will be replaced with events anyway. (https://github.com/linera-io/linera-protocol/issues/365)
Handle them off-chain, and send all earlier messages to the subscriber.
User applications' subscriptions are still handled on-chain, and re-send only the latest message.
The tests have been updated and should catch any regressions.

Handle Subscribe and Unsubscribe offchain.

---

linera-client/src/client_context.rs
linera-client/src/unit_tests/chain_listener.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/worker.rs
linera-service/src/linera/main.rs

This PR is a port of #2035 to the `main` branch.
Currently, processing a chain on the client creates network actions for all other chains it sends messages to. This leads to cross-chain requests that create chain states on storage for those other chains. These other chains might not be relevant to the client, which means it wastes storage and hinders performance.
As a real world example, the faucet chain is used to create new chains. Every block creates a new chain. That means that when a user uses the wallet to create a chain using the faucet, it will keep in storage the initial chain states for all chains created by the faucet before it.
Add an optional `tracked_chains` field to `ChainWorkerState`, and only create `NetworkActions` for those tracked chains. The set of tracked chains is …

Limit network actions to tracked chains (in `main`)

---

Cargo.lock
linera-sdk/Cargo.toml

`cargo test -p linera-sdk --no-default-features` was running into a compile error. For some weird reason, the `with_testing` configuration alias was not being enabled when only `#[cfg(test)]` was active.
Enable the `test` feature when `#[cfg(test)]` is enabled, which makes it follow the same convention as used in other crates.
Ran `cargo test -p linera-sdk --no-default-features` manually, and it now succeeds.
Nothing needed, because this just fixes compilation of an unreleased version.

Enable `test` feature when testing `linera-sdk`

---

scripts/deploy-validator.sh

Validator on-boarding could get a bit tedious. We received feedback for a script that would take care of the entire deployment process.
Add a script, `deploy-validator.sh` which validators can optionally use to deploy a validator in preparation to joining the network.

Added a 'one-click' deploy-validator.sh script

---

.github/workflows/explorer.yml
linera-explorer/.gitignore
linera-explorer/package-lock.json

Our CI is broken due to out-of-sync dependencies on `linera-explorer` that cause `vue-tsc` to not see the usage of components inside the Vue `<template>`.
Commit `package.lock` to make this test more deterministic.
CI.
None required.
- [Some people suggest this should be fixed by using `compilerOptions.jsx = "preserve"`](https://github.com/vuejs/language-tools/issues/1729), but we do this and it didn't help — so either this isn't the solution for us or we aren't using our `tsconfig.json`.

`linera-explorer`: fix build

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-base/src/data_types.rs
linera-execution/src/lib.rs

Bytecode compression was recently introduced (#2382). However, this means that the bytecode must be decompressed after it has been loaded from storage. Currently, decompression uses the `zstd` crate, which uses the Zstandard library installed on the system. Unfortunately, that library is not available in Wasm.
Use `ruzstd` to decompress the bytecode in Wasm. Compression is not supported by `ruzstd`, so bytecodes can't be published, but at least they can be decompressed so that they can executed.
I commented out parts of the code to make it always decompress using `ruzstd`, and ran the end-to-end tests manually to confirm they pass (because they publish and use bytecodes).
Nothing is needed, because this only affects Wasm targets, for which we haven't released anything yet.
- [reviewer …

Use `ruzstd` to decompress bytecodes in Wasm

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-execution/src/wasm/wasmtime.rs
linera-witty/src/runtime/wasmtime/export_function.rs
linera-witty/src/runtime/wasmtime/function.rs

The `wasmtime` dependency we used was getting old, and we'll need a [fix](https://github.com/bytecodealliance/wasmtime/pull/9170) from the next version to be released, in order to fix a Witty issue (#2406).
Update `wasmtime` to the latest available version (24.0.0), and apply the necessary changes to use its updated API. To [fix a dependency version resolution issue](https://github.com/linera-io/wasmer/pull/1), a new version of our `wasmer` fork had to be used (4.3.6-linera.3).
CI should catch any regressions caused by this dependency update.
Nothing needed, because this is an internal refactor.
- Closes #1785

Update `wasmtime` to version 24.0.0

---

examples/amm/src/contract.rs
examples/crowd-funding/src/contract.rs
examples/hex-game/src/contract.rs
examples/matching-engine/src/contract.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/contract/test_runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit

Once we replace application descriptions with blobs, we won't have the creator's chain id in the `ApplicationId` anymore.
This PR creates another system API call in preparation for that.
CI

Create get-application-creator-chain-id system-api call

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-execution/src/wasm/system_api.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/service/runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-witty/src/exported_function_interface/guest_interface.rs
linera-witty/src/runtime/wasmer/export_function.rs
linera-witty/src/runtime/wasmer/function.rs
linera-witty/src/runtime/wasmer/parameters.rs
linera-witty/src/runtime/wasmtime/export_function.rs
linera-witty/src/runtime/wasmtime/parameters.rs

When exporting functions with a specific signature type (with parameters that are flattened to exactly 16 flat types and with a return type that flattens to more than one flat type) to a Wasm instance, Witty's `#[wit_export]` macro would incorrectly lower all parameters and return types to the type.
This is different from what was specified in the [specification](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md#flattening).
Don't lower the parameters of functions if they can be flattened into 16 flat types, even if the return type is lowered into the heap.
Ran tests manually to ensure that the `test_memory_run_application_with_dependency` passes without the dummy parameter that was introduced previously as a workaround before this fix.
- Need to bump the …

Fix Witty export of functions with 16 parameters

---

linera-chain/src/chain.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs

With https://github.com/linera-io/linera-protocol/pull/2407, cross-chain updates can now trigger more cross-chain updates, if the first one contains a `Subscribe` message. Since we don't create new network actions after handling a cross-chain update, the second update is only sent the next time a certificate or chain info request is submitted for that chain.
Handle them recursively, so all inboxes are updated as soon as possible.
A test was updated to check that the outbox is empty. I verified that that check would fail without this fix.

Recursively handle network actions triggered by subscriptions.

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-execution/src/wasm/system_api.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/service/runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-witty/src/exported_function_interface/guest_interface.rs
linera-witty/src/runtime/wasmer/export_function.rs
linera-witty/src/runtime/wasmer/function.rs
linera-witty/src/runtime/wasmer/parameters.rs
linera-witty/src/runtime/wasmtime/export_function.rs
linera-witty/src/runtime/wasmtime/parameters.rs

The PR used a Git revision instead of a released version. This breaks publishing crates.
Revert the change and only try again once a new version of [Wasmtime](https://github.com/bytecodealliance/wasmtime) is released with the referenced fix.
- Closes #2430 because it's no longer needed
- Reopens #2406

Revert "Fix Witty export of functions with 16 parameters"

---

.github/workflows/rust.yml
linera-rpc/Cargo.toml
linera-views/Cargo.toml
linera-views/src/indexed_db.rs

Make sure we're Clippy-clean, at least for default features.
Add `web-default` features to all Web-capable targets that we can use when running Clippy for the Web.  Make Clippy's suggested changes.  Add commands to CI to run Clippy against these features under the `wasm32-unknown-unknown` target.
We can't use `--all-features`, despite our `build.rs` magic, because we can't have target-specific _and_ feature-specific dependencies.  So e.g. `aws-smithy` will always try to build as a dependency of `linera-views` with `--all-features` (or the `dynamodb` feature in general), even if marked as a non-`wasm32` dependency, and it will fail to build on `wasm32-unknown-unknown`.
CI.
Adds a feature flag to `linera-rpc`, so should technically be a minor version bump.
- Fixes …

CI: run Clippy on `web-default` features for Web-compatible crates

---

linera-service-graphql-client/gql/service_schema.graphql
linera-service-graphql-client/tests/test.rs
linera-service-graphql-client/tests/test_check_service_schema.rs

The Linera service GraphQL schema file is out-of-date, and CI didn't catch it.
Remove the unnecessary feature gates from the service schema test, so `cargo test` runs it, and update the schema file.
Locally, the test failed (without any feature flags) with the outdated file, so CI should catch that in the future, too.

Update service schema, remove feature gates from test.

---

linera-views/src/backends/rocks_db.rs

The way we handle `root_key` in `RocksDb` creates multiple instances of the RocksDb which left many open files.
We just concatenate the `root_key` with the `key`.
CI
Not relevant.

Remove the handling of `root_key` in `RocksDb` via separate instances.

---

linera-core/src/client.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-sdk/src/test/validator.rs
linera-service/src/linera/main.rs
linera-service/src/server.rs

We ran into some hangs in a test, and the root cause was that we reached the limit of Tokio's blocking threads. That happened because after #2216, every `ChainWorkerActor` instance spawns a separate blocking thread to run the service runtime.
As an initial fix, the limit of active chain workers should be reduced to below the maximum number of blocking threads (512). Because clients track much less chains than validators, the number can also be different depending on the context.
Add a `chain_worker_limit` parameter to the `WorkerState` constructor, and use different values depending on the context.
CI should catch regressions caused by this parameter tweak. Reducing the number of chain workers to below the limit of blocking threads made the test that initially discovered the issue pass.
- …

Use different chain worker cache sizes depending on the context

---

linera-core/src/worker.rs

After #2444, chain worker evictions became more common in the token transfer benchmark. That uncovered a race condition, that happens in the following scenario:
1. One instance of `WorkerState` sends a request to a chain worker actor for chain "A"
2. Another instance of `WorkerState` sends a request to a new chain worker actor for chain "B", which ends up evicting the worker for chain "A" while it's still running
3. Another instance of `WorkerState` sends a request for chain "A", but that requires creating a new chain worker actor for chain "A"
4. Now there are two chain worker actors for chain "A" racing to change the chain state
While fixing this issue, a second issue was uncovered. There's a memory leak in `WorkerState`, because the finished tasks in `chain_worker_tasks` are never …

Fix race condition after evicting an active chain worker

---

CLI.md
linera-chain/src/chain.rs
linera-client/src/client_context.rs
linera-client/src/client_options.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/test/chain.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/main.rs

A few comments and identifiers in the code are outdated, most of them related to https://github.com/linera-io/linera-protocol/pull/2343.
Update them: Use "message bundles" instead of "messages" where appropriate, and remove an outdated comment about admin subscriptions.

Update outdated comments and identifiers

---

linera-core/src/client.rs

Needed to call `ChainClient` functions on the Web, where `P` may be non-`Send`.
Remove the `Send` bound on `P`, which isn't used anyway.
CI.
None.

`linera-client`: relax unnecessary `Send` bound on `P`

---

CLI.md
examples/llm/README.md
examples/llm/src/lib.rs
linera-chain/src/chain.rs
linera-client/src/client_context.rs
linera-client/src/client_options.rs
linera-client/src/unit_tests/chain_listener.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/config.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-core/src/client.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/test_utils/mod.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/test_system_execution.rs
linera-execution/tests/wasm.rs

The long-lived services are somehow experimental and are mostly used for the LLM demo.
Stability issues were solved but we should probably not activate long-lived services by default anyway.
* Add a configuration option
* Use short-lived service instances by default
* Not breaking for validators
* May affect users but they can pass an option on the CLI

Make service runtime short-lived by default

---

Cargo.lock
linera-client/src/client_context.rs
linera-core/Cargo.toml
linera-core/src/join_set_ext.rs
linera-core/src/lib.rs
linera-core/src/worker.rs
linera-rpc/src/grpc/mod.rs

Tokio's `spawn_local` needs to be called from the context of a `LocalSet`, which is annoying to set up when our entry point is in JavaScript, and besides would block the browser worker, which is undesirable.
Instead, use the browser's event loop.
CI for the native case; `linera-web` will test this in the browser case.
None.

`linera_core::join_set_ext`: replace `spawn_local` with `wasm_bindgen_futures::spawn_local`

---

CLI.md
Cargo.lock
examples/Cargo.lock
linera-chain/Cargo.toml
linera-chain/src/chain.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-client/src/client_options.rs
linera-execution/src/lib.rs
linera-execution/src/policy.rs
linera-execution/src/resources.rs
linera-execution/tests/fee_consumption.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/main.rs

We can't allow blocks to be arbitrarily large; e.g. they need to fit in a single gRPC message. See https://github.com/linera-io/linera-protocol/issues/1538 for more details.
Add a block size limit to the policy and enforce it.
A unit test was added to `linera-chain`.
- Closes https://github.com/linera-io/linera-protocol/issues/2455.
- Part of https://github.com/linera-io/linera-protocol/issues/1538.

Add a block size limit

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-rpc/src/grpc/server.rs
linera-service/src/grpc_proxy.rs

The Tonic API changes between 0.11 and 0.12, and previously I avoided bumping it for this reason.  But I bumped it when investigating something unrelated, and the API changes aren't really scary.
Bump our `tonic` dependency to the latest version (0.12.2).
CI.
None required.

Update tonic: 0.11 → 0.12

---

linera-service/src/cli_wrappers/wallet.rs

In some error messages, the size of the output is too large to be manageable.
The text from other part of `wallet.rs` is used for the `with_context` code.
CI.
Not relevant.

Reduce the size of output in case of failure.

---

linera-core/src/client.rs

In `client.rs` there are several places where we pass a mutable vector of certificates into local node functions, and then handle those certificates in the notifier.
Move this functionality into `Client` functions, to unclutter the call sites a bit.
No logic has changed. CI should catch any regressions.

Simplify notification handling in client.rs

---

linera-core/src/client.rs

In an upcoming optimization (synchronizing the admin chain less often) I will need to use `ChainClient` methods from within `synchronize_received_certificates_from_validator`. (We will sync the admin chain in that function when necessary, and then call `known_committees`.)
Make `synchronize_received_certificates_from_validator` a method. This also reduces the number of its parameters.
Just a refactoring. Existing tests should catch any regression.

Make synchronize_received_certificates_from_validator a method.

---

linera-base/src/data_types.rs
linera-core/src/client.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-sdk/src/test/chain.rs
linera-storage/src/lib.rs

When bytecode compression was introduced (#2382), compression and decompression ran in asynchronous tasks. Since these operations are CPU bound, they are best executed in separate non-blocking threads. This allows handling more IO bound operations.
Spawn Tokio's blocking threads to compress and decompress bytecodes.
CI should catch any regressions from this is an internal refactor.
Nothing needed, because this is an internal refactor.

Compress and decompress bytecodes in blocking thread

---

linera-chain/src/unit_tests/chain_tests.rs
linera-core/src/client.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs

Currently the client synchronizes the admin chain in addition to the user's chain (or whatever chain is currently being used) in every call to `find_received_certificates`, to make sure we have all committees, even the ones that have been created by the admin chain but not handled yet by the other chain. That is wasteful.
Work on this uncovered another issue: Bytecode blobs are not recorded as oracle responses, but then are expected to be present when we try to load the bytecode.
Synchronize the admin chain only when we encounter an incoming message from a future epoch.
Record the service and contract bytecode blobs as oracle responses whenever we register an application.
No new features were added, and the admin chain change was just an optimization, where existing tests should catch any …

Sync admin chain only when needed; fix bytecode blobs.

---

linera-chain/src/unit_tests/chain_tests.rs
linera-execution/src/system.rs

There was a "PR race condition" when merging to `main`, where #2471 changed the API to compress/decompress bytecodes but #2473 updated some tests and added bytecodes compressed with the previous API. Merging both of them caused `main` to break.
Fix the tests to use the new `compress()` method instead of the removed `From` implementation.
CI should reveal if this fixes the tests that were broken.
Nothing needed, as this only affects tests.

Fix compression of bytecodes in tests

---

linera-core/src/client.rs

Several end-to-end tests are unstable on main. It's not clear to me yet why, but if the tests repeatedly pass on this PR, the optimization in https://github.com/linera-io/linera-protocol/pull/2473 is to blame.
Revert the optimization.
See if CI passes _multiple times_ to make sure this is actually related.
- Original PR: https://github.com/linera-io/linera-protocol/pull/2473

Revert admin chain sync optimization.

---

linera-base/src/lib.rs
linera-base/src/tracing.rs
linera-base/src/tracing_web.rs
linera-service/src/benchmark.rs
linera-service/src/linera/main.rs
linera-service/src/proxy.rs
linera-service/src/server.rs

When debugging issues, it is hard to navigate through the log because it contains messages from multiple sources (validators, proxies, clients, etc.).
Allow logging each source to different log file, all stored in a single directory specified by a `LINERA_LOG_DIR` environment variable. If the variable isn't set, no log files are written.
Tested manually by running some end-to-end tests with the environment variable set.
Release a new minor version update, because this is a new feature that's backwards compatible with previous versions.

Log to separate files

---

linera-client/src/chain_listener.rs
linera-core/src/client.rs

This is a backport of https://github.com/linera-io/linera-protocol/pull/2479 to devnet.
The node service listens to notifications from the validators about new blocks, so calling `prepare_chain` should never be necessary.
Don't call `prepare_chain`.
We use both `ProcessInbox` policies in the tests, so any regressions should be caught.
- PR for the main branch: https://github.com/linera-io/linera-protocol/pull/2479

In the node service, don't unnecessarily call prepare_chain. (Devnet backport.)

---

linera-base/src/data_types.rs

Introducing bytecode compression (#2382) results in a CPU overhead. It is `expected` to be fairly low, but it should be measured to be sure.
Add latency metrics for compressing and decompressing bytecodes.
CI should catch any regressions caused by introducing the metrics.
Nothing needed, because this just adds two latency metrics.

Add metrics for compression and decompression latency

---

linera-views/Cargo.toml
linera-views/benches/queue_view.rs
linera-views/src/context.rs
linera-views/src/lib.rs
linera-views/src/views/bucket_queue_view.rs
linera-views/src/views/mod.rs
linera-views/src/views/queue_view.rs
linera-views/tests/random_container_tests.rs

The `QueueView` is used for the protocol and this leads to painful-to-read loops where we read the front, then deleting and so on until we get what we want. This leads to many storage calls which are not storage friendly.
The following change was proposed:
* It was identified that only the `front`, `delete_front`, and `push_back` are used in the protocol. So, this is what needs to be optimized.
* The arrangement of keys is made so that when the view is loaded the front is loaded as well. 
* So, the `BucketQueueView` has `fn front` being a regular function. But of course, it has a cost in that the `delete_front` needs to be async and can return an error.
* All the other functions of `QueueView` are implemented in `BucketQueueView`.
The protocol has not been changed so far but could be …

Implement the `BucketQueueView`

---

linera-base/src/tracing.rs

After allowing logging to files (#2484), the log files seem to include some ANSI escape codes, which seem to enable some record names to appear in italic. This makes the log files harder to view in an editor.
This could be a bug in `tracing-subscriber`. I can investigate more later when I have some more time.
Making the layer without ANSI escape sequences come first seems to workaround the issue.
The consequence seems to be that italics also becomes disabled in the terminal output, but IMHO that's a minor issue.
Manually tested to see if italics was removed.
New patch version, as this fixes a tiny bug.

Workaround ANSI escape codes in log files

---

CLI.md
linera-client/src/client_context.rs
linera-client/src/client_options.rs
linera-core/src/client.rs
linera-execution/src/system.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/tests/linera_net_tests.rs

The variant `SystemOperation::ReadBlob` is marked as `#[cfg(with_testing)]`, causing format divergence depending on the compilation mode.
Make `ReadBlob` a real thing, with a CLI and a node-service mutation etc as least until we decide otherwise.
I created #2490 to suggest removing`read_data_blob` or renaming it into `verify_data_blob` on the main branch.
CI
Cherry-pick on the devnet branch, then run:
```
export LINERA_FAUCET_URL=https://faucet.devnet-2024-09-04.linera.net
cargo test -p linera-service --features remote-net data_blob
```
Need to be cherry-picked on the devnet branch.

Stabilize `SystemOperation::ReadBlob`

---

linera-client/src/chain_listener.rs

In the chain listener we automatically process the inbox when we are notified about an incoming message. If we don't own the chain in question, we skip this.
However, we currently don't reset the timeout, so this would retry processing the inbox repeatedly.
Reset the timeout in _all_ cases. Also fix a few log statements.
This was found running `test_wasm_end_to_end_social_user_pub_sub::storage_service_grpc` locally: It doesn't make the test fail, but it creates a lot of log messages.
- We should release a patch version of the client to fix this.

Reset timeout in chain listener if we don't own the chain.

---

linera-client/src/client_context.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/tests/linera_net_tests.rs

Data blobs are identified by the hash of their content. Blob IDs are an internal concept.
Currently the `publish-data-blob` command and the `publishDataBlob` node service mutation return blob IDs.
Make them return the hashes instead.
The tests have been updated.
- Closes https://github.com/linera-io/linera-protocol/issues/2491.

publish-data-blob should return the hash, not blob ID.

---

linera-client/src/chain_listener.rs
linera-sdk/Cargo.toml

The `linera-core/test` feature was enabled in `linera-sdk` for no reason.
Disable it. Also improve a log message.

Remove the test feature from linera-core in linera-sdk.

---

examples/llm/rust-toolchain.toml
examples/rust-toolchain.toml

I was running `linera project publish` from `examples` and run into a compiler error due to version mismatch
Create a toolchain file in `example/`.
CI + tested manually

fix rust-toolchain for examples

---

linera-service/tests/linera_net_tests.rs

We want to get better performance measurements, so we can optimize end-to-end latency.
Add an end-to-end test that makes a number of transfers in a loop.
In each iteration it waits until the receiver gets a `NewBlock` notification, so the loop only continues after:
* the sender's block has been confirmed,
* the receiver's node service got a notification and ran `process_inbox_without_prepare`,
* the receiver's block got confirmed.
The number of iterations is configurable using the `LINERA_TEST_ITERATIONS` environment variable. This also applies to the `test_end_to_end_faucet_with_long_chains` test.
This runs with 100 iterations in CI.
Locally, one can use
```bash
LINERA_TEST_ITERATIONS=250 RUST_LOG=info cargo test -p linera-service \
--features storage-service …
```

Add an end-to-end test that doubles as a latency benchmark.

---

CLI.md
examples/amm/README.md
examples/amm/src/lib.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-client/src/client_options.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-execution/src/lib.rs
linera-execution/src/policy.rs
linera-execution/src/resources.rs
linera-execution/tests/fee_consumption.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/main.rs

Block execution time needs to be limited.
Add a per-block fuel limit to the resource control policy. This doesn't address the problem completely yet: We also need to limit some oracle and host function calls.
I added a client test.
- Part of https://github.com/linera-io/linera-protocol/issues/2457

Add a fuel limit for blocks.

---

linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/updater.rs

When the client sends a block proposal to a validator, and the block reads blobs or receives messages it doesn't know, the sends back a corresponding error message and the client sends the missing data.
Currently, if _both_ messages _and_ blobs are missing, it only sends one of the missing pieces and then fails.
In that case, retry twice, to make sure the validator has all the data.
Also, to reduce round-trips, if the validator complains about _one_ missing blob, we send _all_ missing blobs. This is similar to what we do for messages.
A regression test was added. This fails without the fix.
Since this is a client-side fix, it could easily be backported, if needed.

Resend proposal if both messages and blobs are missing.

---

linera-service/src/cli_wrappers/local_net.rs

The `RocksDb` option of `Database` cannot be used since the `storage` is used by the proxy and by the validators, so even in the case of just one worker, the RocksDb would be shared between two programs and that is not possible.
Remove the `RocksDb` from the `Database` and the relevant code.
CI
Not relevant.

Remove the RocksDb option in `Database`.

---

linera-client/src/lib.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/updater.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service/src/linera/main.rs

We pass around a lot of pairs `(ValidatorName, impl LocalValidatorNode)`, where we use the name to check signatures and output log messages about that validator.
Group them in a `struct NamedNode`, and move the signature checks into its methods to simplify the updater and client code.
Only refactoring; CI should catch regressions.

Add struct NamedNode.

---

linera-views/Cargo.toml
linera-views/src/context.rs

The `store_timings` provides timings but Prometheus is the technique that we are using. So, that code
needs to be removed.
Straightforward removal.
CI
The `store_timings` feature is eliminated.

Remove the `store_timings` feature

---

linera-client/src/chain_listener.rs
linera-client/src/wallet.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/updater.rs
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/grpc/node_provider.rs
linera-rpc/src/node_provider.rs
linera-rpc/src/simple/node_provider.rs
linera-rpc/tests/transport.rs
linera-service/src/linera/main.rs
linera-service/src/schema_export.rs

* The word `Local` is used for local (vs remote) nodes.
* Simplify the code by exposing only the definition that is relevant for a particular configuration.
Use `cfg(web)` to remove `LocalValidatorNode(Provider)` and `LocalNotificationStream`
CI

Remove LocalValidatorNode(Provider) and LocalNotificationStream

---

CLI.md
linera-client/src/chain_clients.rs
linera-client/src/chain_listener.rs
linera-client/src/client_options.rs
linera-client/src/unit_tests/chain_listener.rs
linera-service/src/faucet.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs
linera-service/src/unit_tests/faucet.rs
linera-service/tests/local_net_tests.rs

We would like the faucet to listen for notifications from the admin change, especially for reconfigurations so that it can automatically update epoch.
Add a chain listener to the faucet service. This will work with #2303 so that the faucet _only_ listens for messages from the admin chain.

Faucet has a chain listener

---

linera-client/src/wallet.rs
linera-core/src/client.rs
linera-core/src/client/chain_state.rs
linera-core/src/client/mod.rs

`ChainState` contains the `pending_block` as well as the expected `next_block_height`. The former is always at the next block height.
Move `ChainState` into its own submodule, make its fields private, and make it guard its own invariant.
Existing tests should catch any regressions.

Move ChainState to a submodule and make it guard its own invariant.
