linera-io/linera-protocol

linera-views/src/common.rs
linera-views/src/log_view.rs
linera-views/src/queue_view.rs
linera-views/src/views.rs

This means in particular implementing the `read_multi_key` trait function.

Use the `read_multi_key_bytes` for the `LogView` and `QueueView`

---

scripts/run_local.sh

For some users when starting a local net, defaulting to 4 validators is not necessarily optimal; at the same time we would like to be able to vary the number of validators for testing.
Make `run_local.sh` configurable over the number of validators and shards per validator.
Defaults to 1 validator with 4 shards.
Even though the number of shards configurable, given that our validator configuration is currently statically defined in `configuration/`, changing the number of shards won't work for now and will be handled in a future PR.

run_local.sh is now configurable in number of validators and shards

---

linera-views/src/common.rs
linera-views/src/log_view.rs
linera-views/src/queue_view.rs

Should be relatively unambiguous.

Some removal of some back/forth operation.

---

linera-service/tests/end_to_end_tests.rs

Arising from two PR being merged at the same time.

Test correction

---

examples/Cargo.lock
examples/counter/Cargo.toml
examples/counter/tests/single_chain.rs

It is a small thing, but since we should have integration tests for all the contracts, here it goes.

Integration test for counter

---

examples/Cargo.lock
examples/social/Cargo.toml
examples/social/tests/cross_chain.rs

This is the integration test for the social media example app.

Integration test for the social example.

---

examples/crowd-funding/src/contract.rs
linera-execution/src/graphql.rs
linera-views-derive/src/lib.rs
linera-views-derive/src/util.rs

Add final underscore to the entries

---

linera-core/src/worker.rs
linera-rpc/src/simple_network.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

* Reduce log-verbosity overall (since INFO is now the default)
* Do not call process_inbox every time in GraphQL mutations

Minor changes in node service + logs

---

Cargo.lock
examples/Cargo.lock
linera-chain/Cargo.toml
linera-chain/src/chain.rs
linera-sdk/src/views/system_api.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/key_value_store_view.rs
linera-views/src/lru_caching.rs
linera-views/src/memory.rs
linera-views/src/rocksdb.rs

This requires implementing a `MAX_CONNECTIONS` constant for the `KeyValueStoreClient` and `Context`.

Implement stream for asynchronicity

---

linera-service/src/linera.rs

Our wallet config lives in the Linera config dir by default (arch dependent, but on Linux `~/.config/linera`). Our storage however defaults to an in-memory db or needs to be specified explicitly every time, `--storage rocksdb:/path/to/db`
The default storage now lives alongside the wallet, i.e. `~/.config/linera/wallet.db`.

Default storage is in config dir

---

linera-storage/src/memory.rs

optimize code use self

---

linera-execution/src/committee.rs

better understanding of calculation formulas

add comments for calculating threshold

---

.github/workflows/rust.yml
examples/fungible/README.md
examples/fungible/src/lib.rs
examples/fungible/web-frontend/src/App.js

Linera currently has a few example applications, but new users have no starting point in the repository to describe how to use the applications.
Write an initial `README.md` file that describes the Fungible Token application and how to use it.
Also fix two small issues with the GraphQL schema in the web frontend.
Developed together with #794, and that PR should be merged first.

Add README file for the Fungible Token application

---

linera-storage/src/lib.rs

change id to chain_id

---

.github/workflows/kubernetes.yml
README.md
docker/Dockerfile
docker/run-proxy.sh
docker/run-server.sh
linera-core/src/unit_tests/wasm_client_tests.rs
linera-service/Cargo.toml
linera-service/tests/end_to_end_tests.rs
scripts/run_local.sh

Builds are reproducible enough so that fuel consumption is stable on Linux but that's more of an accident.

Fix tests on macos

---

linera-sdk/src/lib.rs

sdk: add debug SessionCallResult

---

linera-sdk/src/views/mod.rs
linera-sdk/src/views/system_api.rs

delete use KeyValueStore

---

Cargo.lock
examples/Cargo.lock
linera-storage/Cargo.toml
linera-storage/src/memory.rs
linera-views/Cargo.toml
linera-views/src/batch.rs
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/lru_caching.rs
linera-views/src/memory.rs
linera-views/src/rocksdb.rs
linera-views/src/test_utils/mod.rs
linera-views/tests/operations_tests.rs

Several things:
* Simplification of the construction of test context for users.
* Resolution of several bugs in the DynamoDb and batch codes.
* Introduction of a much more rigorous testing framework for the `KeyValueStoreClient` that allows us to find the above problems.

Adding tests and fixing bugs in KeyValueStoreClient

---

linera-base/src/identifiers.rs

Implementing the last 2, Serialize and Deserialize
`cargo test`
#768

Implement Serialize/Deserialize for BytecodeId/ApplicationId

---

linera-base/src/crypto.rs
linera-base/src/identifiers.rs

Fix ApplicationId::Deserialize + nits

---

examples/counter/src/lib.rs
examples/fungible/src/lib.rs
examples/matching-engine/src/lib.rs
examples/meta-counter/src/lib.rs
examples/reentrant-counter/src/lib.rs
examples/social/src/lib.rs

Removed what I could, a couple of the `Decentralized` ones don't compile if I remove them for some reason
`cargo test`
This is stacked on top of #861
#768

Remove derives

---

linera-service/src/storage.rs

optimize match in service storage

---

examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs

fix doc error

---

scripts/Cargo.lock
scripts/Cargo.toml
scripts/check_copyright_header/Cargo.toml
scripts/check_copyright_header/src/main.rs

As title, this was suggested as a follow up on #842
Run tests

Use thiserror on check_copyright_header

---

linera-base/src/data_types.rs
linera-base/src/identifiers.rs
linera-chain/src/data_types.rs
linera-core/src/client.rs
linera-core/src/tracker.rs
linera-core/src/worker.rs
linera-execution/src/lib.rs
linera-rpc/src/conversions.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-storage/src/lib.rs

- block hash in notifications RPC
- chains RPC
-  block and blocks RPCs

Block explorer RPCs

---

linera-sdk/src/test/integration/chain.rs

Integration tests would fail when running for projects outside the examples provided in the `linera-protocol` repository. That was because the path where the test searched for the built WebAssembly binaries was unfortunately hard-coded and ignored the `repository` parameter passed to the function.
Change the code so that the WebAssembly binaries are looked for inside the provided `repository` parameter instead, and also search the parent directories as a fallback because the crate could be in a workspace.

Fix directory where binaries are searched in during integration tests

---

Cargo.lock
Cargo.toml
linera-explorer/.gitignore
linera-explorer/Cargo.toml
linera-explorer/README.md
linera-explorer/graphql/applications.graphql
linera-explorer/graphql/block.graphql
linera-explorer/graphql/blocks.graphql
linera-explorer/graphql/chains.graphql
linera-explorer/graphql/schema.graphql
linera-explorer/html/app.html
linera-explorer/html/applications.html
linera-explorer/html/block.html
linera-explorer/html/blocks.html
linera-explorer/html/operation.html
linera-explorer/index.html
linera-explorer/js/applications.js
linera-explorer/js/block.js
linera-explorer/js/blocks.js
linera-explorer/js/index.js
linera-explorer/js/json.js
linera-explorer/js/operation.js
linera-explorer/package.json
linera-explorer/src/graphql.rs
linera-explorer/src/js_utils.rs
linera-explorer/src/lib.rs
linera-explorer/webpack.config.js

PR following #858 
- multi chains
- blocks/block interface
- applications list

Block explorer v1

---

examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-chain/src/unit_tests/inbox_tests.rs
linera-core/src/node.rs
linera-core/src/notifier.rs
linera-core/src/tracker.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-explorer/graphql/schema.graphql
linera-explorer/src/graphql.rs
linera-explorer/src/lib.rs
linera-rpc/src/conversions.rs
linera-sdk/src/lib.rs
linera-service/src/chain_listener.rs
linera-service/src/config.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-service/tests/end_to_end_tests.rs

Closes https://github.com/linera-io/linera-protocol/issues/865.

Make node service process all owned chains.

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml

#902 made incompatible changes to the node service's GraphQL API.
Increase the minor version number.

Bump version to 0.3.

---

.github/pull_request_template.md

Standardize github Pull Requests and encourage best practices.
This template
Copy pasted the template here. Looks like to need to land first on the main branch to be picked by GH.
* https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

initial template for new PRs

---

linera-service/src/project.rs
linera-service/tests/end_to_end_tests.rs

`linera project publish-and-create` did not work with our examples since they are in a workspace.
`linera project publish-and-create` now works with workspaces.
Added a test in `end_to_end` test. Also tested manually using the `linera` binary.

linera project publish-and-create now uses workspace

---

linera-explorer/graphql/applications.graphql
linera-explorer/graphql/block.graphql
linera-explorer/graphql/blocks.graphql
linera-explorer/graphql/notifications.graphql
linera-explorer/src/lib.rs

- hash argument as required CryptoHash for graphql queries

Fix graphql queries argument requirement

---

linera-service/src/client.rs

Some types in the client wrapper are wrong: They should be public keys, not owners. The tests all pass because the type doesn't matter; the keys are read from strings and then converted back to strings.
Use the correct type, `PublicKey`.
This is only used by tests anyway.
N/A

Fix types in client wrapper: PublicKey, not Owner

---

CONTRIBUTING.md

While debugging stuck tests, I had to use several different techniques for identifying what is going on. I think it makes sense to share them to a wider audience.
The developed techniques are shared in the `CONTRIBUTION.md` file.
There is no real way unless one has a stooped test. But one could use the branch `dynamo_db_big_value` from `https://github.com/MathieuDutSik/linera-protocol_second` and to run the test `cargo test client::client_tests::wasm::test_dynamo_db_run_application_with_dependency::wasmer --features aws`.
This was the original motivation for this development.
The links are available in the text of the contribution.md file.

Introduce more debugging techniques

---

.github/workflows/scylladb.yml
linera-service/src/storage.rs
linera-views/src/rocks_db.rs

Sadly, it looks like we're not running ScyllaDb unit tests in CI after #953.
* Fix copy-paste bug.
* Rename a few things to follow the coding guidelines and/or improve readability.
CI

ScyllaDb follow-ups

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
examples/amm/Cargo.toml
examples/amm/src/contract.rs
examples/amm/src/lib.rs
examples/amm/src/service.rs
examples/amm/src/state.rs
linera-service/Cargo.toml
linera-service/src/client.rs
linera-service/tests/end_to_end_tests.rs

Did my best effort to understand what an AMM is and implement the simplest version of it I could think of that would work, and that would allow me to run end to end tests in the same format as other examples.
Please critique away and show me how to make this better :)
Run end to end test

[example] AMM

---

linera-execution/src/committee.rs

The GraphQL server fails to serialize some operations due to the presence of maps indexed by something other than strings (Epoch, ValidatorName).
cf [async-graphql](https://github.com/async-graphql/async-graphql/blob/master/value/src/serializer.rs#L439-L640)
Make the human readable serialization of Epoch and ValidatorName as string. 
- Checking GraphiQL for the block 0 after a run_local.sh. The OpenChain operation should be visible and not null as before this PR
- Adding an OpenChain operation in tests in #975

GraphQL BTreeMap keys as strings

---

linera-core/src/local_node.rs
linera-core/src/notifier.rs
linera-core/src/unit_tests/client_test_utils.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-service/src/grpc_proxy.rs

Fix bugs. Help with client tests and with fixing #940 down the road.
* Fix existing code in local node
* Fix the case of `NewBlock` in `fully_handle_certificate_with_notifications`
* Implement `subscribe` in tests
* Add a simple test
CI

Correctly support subscriptions in local node and test node

---

kubernetes/dev/validator/linera-proxy.yaml

Missed altering this in one of the previous PRs
Fix it
Testing locally with minikube

Fixing linera-proxy Kubernetes port

---

linera-rpc/src/simple_network.rs

Better error reporting
Changing `NodeError` feels a bit overkill, so just adding a log.
CI

(easy) add 1 logging in simple_network

---

README.md
linera-chain/src/data_types.rs
linera-indexer/Cargo.toml
linera-indexer/src/common.rs
linera-indexer/src/indexer.rs
linera-service/src/client.rs

Address reviewers' comments + fix a few things
(see commit titles)
CI

Follow ups with indexer PR #993

---

linera-service/src/client.rs

Both local Docker build and Gcloud build were failing with this error for me:
```
error[E0061]: this function takes 1 argument but 2 arguments were supplied
--> linera-service/src/client.rs:153:20
|
153  |         let path = resolve_binary("linera", None).await?;
|                    ^^^^^^^^^^^^^^         ------
|                                           | |
|                                           | unexpected argument of type `std::option::Option<_>`
|                                           help: remove the extra argument
|
note: function defined here
--> linera-service/src/client.rs:1023:14
|
1023 | pub async fn resolve_binary(name: &'static str) -> Result<PathBuf> {
|              ^^^^^^^^^^^^^^ ------------------
error[E0061]: this function takes 1 argument but 2 arguments …
```

Fixing Docker build

---

Dockerfile
Dockerfile.aarch64

There's one # missing, which makes the box not be aligned
Add the missing #
CI

Add missing # to top of Dockerfile

---

.github/workflows/explorer.yml

The explorer CI is failing.
Clear the npm package cache before `npm install`. Thanks @maxtori for the help!
CI should pass now.
Example failed build: https://github.com/linera-io/linera-protocol/actions/runs/6188082339/job/16799309751?pr=1024

Fix explorer CI.

---

linera-indexer/Cargo.toml
linera-service/src/client.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/rocks_db.rs
linera-storage/src/scylla_db.rs
linera-views/src/dynamo_db.rs
linera-views/src/scylla_db.rs

Several problems were identified for the end-to-end tests and I was asked to do a separate PR about this.
The following corrections were made:
* Correct the compilation via the `cargo test` command.
* Make the detection of features effectively work.
* Make the compilation of the code as called from `client.rs` work for more than one feature.
The CI should do it, but a separate `cargo test` also done on a computer also helps.

Address Compilation errors and correct `detect_current_features`.

---

kubernetes/linera-validator/redeploy.sh

We need to track our metrics
We'll be using Prometheus + Grafana to log and track our metrics
Ran the script, port forwarded for grafana, managed to access the web dashboard

Adding Prometheus/Grafana to Helm deployment

---

linera-indexer/lib/src/common.rs
linera-indexer/lib/src/lib.rs
linera-indexer/lib/src/scylla_db.rs

Indexer with ScyllaDB storage
ScyllaDB runner for the indexer enabled with `scylladb` feature.
Should work the same as RocksDB if ScyllaDB tests are good.

Scylladb indexer

---

Dockerfile
Dockerfile.aarch64
Dockerfile.local

This parameter is needed now
Add the parameter to all Dockerfiles
Ran the Dockerfiles, made sure everything works

Add --storage param to Dockerfiles when creating config files

---

linera-service/src/database_tool.rs

None of the tracing logs were showing for me
Add the tracing subscriber, so the tracing logs show on stdout
Ran the tool, I can see the logs now

Make sure tracing works on database_tool

---

.github/workflows/explorer.yml

Perhaps help with CI stability
`npx vite` runs the server and never exists. It's unclear what it tests -> remove.
`npm run test` doesn't exit (not sure why) -> add `-- run` at the end.
CI

simplify .github/workflows/explorer.yml

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml

Make a new release of the protocol
We made some breaking changes to the CLI but we are before v1 so perhaps v0.4.1 is ok.
CI

prepare new release

---

.github/pull_request_template.md

Small nit, link are actually below now in the template, not above
Fix the wording
CI

Nit on PR Template

---

.github/workflows/kubernetes.yml

We have Kubernetes deployments that we're using now, so we need to have a CI to make sure we're not breaking the local run
Update old Kubernetes CI to do what we do in the current local deployment
CI

Updating local Kubernetes CI

---

linera-service/src/chain_listener.rs
linera-service/src/linera.rs
linera-service/src/node_service.rs
linera-storage/src/lib.rs

Minor fixes + make sure process_inbox cannot kill the ChainListener task
See commits
CI

fix: Make sure process_inbox cannot kill the ChainListener task

---

.github/workflows/dynamodb.yml
.github/workflows/explorer.yml
.github/workflows/kubernetes.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml

Stacked PRs were not triggering CI
Make sure all PRs, including stacked ones, trigger CI
CI

Make sure CI runs on every PR, even if stacked

---

.github/workflows/kubernetes.yml

I thought this was already in 16 also, but it isn't, so upping it like the others
Increase from 4 to 16 cores, like all the other tests
CI

Up Kubernetes CI to 16 cores

---

.github/workflows/documentation.yml
.github/workflows/dynamodb.yml
.github/workflows/explorer.yml
.github/workflows/kubernetes.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml

Save a few bucks
* Kubernetes/dockers changes should not affect the Rust crates
* A few `.md` files at the root cearly affect nothing
testinprod

ignore certain changed paths during pull requests

---

Cargo.lock
examples/Cargo.lock
linera-core/src/unit_tests/client_test_utils.rs
linera-indexer/example/Cargo.toml
linera-indexer/example/tests/test.rs
linera-service-graphql-client/tests/test.rs
linera-service/Cargo.toml
linera-service/src/cli_wrappers.rs
linera-service/src/linera.rs
linera-service/src/storage.rs
linera-service/tests/end_to_end_tests.rs
linera-service/tests/wasm_end_to_end_tests.rs
linera-storage/src/dynamo_db.rs
linera-storage/src/scylla_db.rs
linera-views/Cargo.toml
linera-views/src/common.rs
linera-views/src/dynamo_db.rs
linera-views/src/scylla_db.rs
linera-views/src/unit_tests/views.rs
linera-views/tests/operations_tests.rs
linera-views/tests/views_tests.rs

The end-to-end tests are very important and we want to support them. Here it is for `ScyllaDb`as `DynamoDb` has a different set of issues.
The PR does the following:
* We use a shared server for the `ScyllaDb` and `DynamoDb` storages.
* The `get_table_name` is now changed to generate random table_names. This is then similar to `RocksDb`. This is because the orderly generation of the `table_name` would lead to abstraction leakage in the tests which we do not want to have. Note that the preexisting system with the `get_table_name` was restarting from 0 when going from one test file to another.
* One side consequence is that `get_table_name` is no longer async.
* The `LocalNetwork` now takes a `table_name` in its constructor. The `new_for_testing` is using the `get_table_name`. ses a …

Support `ScyllaDb` for the end-to-end tests

---

kubernetes/linera-validator/build_and_redeploy.sh

Small typo, should be `helm`
Fix typo
CI

Fix typo in build_and_redeploy

---

.github/workflows/rust.yml

Follow up from previous PR, we need to enforce sorting
Add sorted check to linter
CI

Check if Cargo.toml is sorted on linter

---

linera-service/src/database_tool.rs

It was deemed preferable by practitioners that the error code returned by `linera-db` reflects the conclusion of the request. This is thus implemented.
We simply use a `std::process` and write down the stuff accordingly.
The CI has not changed, but the feature was tested on the command line

Introduce error codes for `linera-db` tool

---

docker/Dockerfile.aarch64
docker/Dockerfile.local-aarch64

Small fix
Missing line break
Run it

Small Dockerfile fix

---

linera-chain/src/chain.rs

Implementing metrics in https://docs.google.com/spreadsheets/d/1tHo8iKzrlkuYeN2Yu7a6MfwQd-P2KNA9BlnhcASoEQY/edit?pli=1#gid=0
Implementing block execution latency Histogram metric
With this one, since it's a Histogram, you can do more stuff, like get the p99:
For this benchmark, the p99 for block execution latency was 4.95 milliseconds

Log block execution latency metric

---

linera-storage/src/lib.rs
linera-views/src/lib.rs

Was raised to my attention on https://github.com/linera-io/linera-protocol/pull/1133 that there's a preferred way to word these
Word it in the preferred way
CI

Nit: change wording of counter creation expect

---

.github/workflows/kubernetes.yml

Sleep is no longer necessary since adding the `--wait` flag to `helm` install.
Remove the `sleep` command.
CI.

Remove sleep from kubernetes GH action

---

README.md
examples/fungible/README.md
examples/fungible/src/lib.rs
linera-service/src/linera.rs
linera-service/src/util.rs
linera-service/tests/readme_test.rs

Test all README files in CI. This is a first step.
* Switch to `linera net up`
* Use the recent improvement of the linera CLI tool: helper script and PRNG seed.
* Add an integration in `linera-service` (perhaps not ideal but this guarantees that the linera binaries have been compiled)
new test in CI
- stacked on top of #1154

Test the bash quotes of the README files of fungible in CI

---

linera-rpc/src/grpc_network.rs

Implementing server request success Counter metric. We'll be able to calculate the error and success rate using this and the error counter

Log server request success

---

linera-rpc/src/grpc_network.rs

Implementing server request error Counter metric. With this and the success one, we'll be able to calculate the error and success rate of the server
Added some test code to force some errors, ran validator locally, ran a benchmark against it, and saw metric properly logged:

Log server request error

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/counter/web-frontend/package-lock.json
examples/fungible/web-frontend/package-lock.json
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-explorer/package.json
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml

Make a release
Bump major version.
CI

Prepare release of crates v0.5.0

---

Cargo.lock
examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/fungible/src/lib.rs
examples/social/README.md
examples/social/src/lib.rs
linera-service/Cargo.toml
linera-service/tests/readme_test.rs

We would like to ensure that bash snippets in our example READMEs are not broken.
Add tests that execute the bash in the examples.
Run `cargo test -p linera-service`.
These changes only affect testing and should be safe to release.
- https://github.com/linera-io/linera-protocol/issues/1180
- https://github.com/linera-io/linera-protocol/issues/1176
- https://github.com/linera-io/linera-protocol/issues/1177

Test example bash snippets

---

linera-rpc/src/grpc_network.rs

Following feedback from #1146
Implementing a per type latency metric

Log server request latency per request type

---

linera-service/src/grpc_proxy.rs

Implementing proxy request success Counter metric. We'll be able to calculate the error and success rate using this and the error counter
1. Ran validator locally with `./build_and_redeploy.sh --port-forward --clean`
2. Built the binaries with `cargo build --features benchmark`
3. Ran a benchmark against it with `./linera benchmark`
4. Port forwarded the Prometheus UI `kubectl port-forward prometheus-linera-core-kube-prometheu-prometheus-0 9090`
5. Went to http://127.0.0.1:9090/graph to see the metric properly logged:

Log proxy request success

---

linera-service/src/grpc_proxy.rs

Implementing proxy request error Counter metric. With this and the success one, we'll be able to calculate the error and success rate of the server
Will add some test code to force some errors, run validator locally, run a benchmark against it, and see if the metric is properly logged

Log proxy request error

---

.editorconfig

The .editorconfig file is a cross-editor standard, supported by many editors, for specifying basic codebase style settings for editors. See https://editorconfig.org/ for more information.
These defaults aren't intended to be final, but should help code style consistency.  They are based for now on discussion with @ma2bd in person and in code review.
@ma2bd has preferences around code style.  I was tempted to configure my editor with a `.dir-locals.el`, but thought if I use a `.editorconfig` instead then we can commit it and other people can benefit.
- …

Adds a .editorconfig file with preferred defaults

---

linera-core/src/client.rs

A deadlock would occur in some end-to-end tests which used multiple applications.
The deadlock would occur in the stream returned by the `ChainClient::listen` method when a future inside the stream was "paused" while holding a lock, and the stream then continued executing but eventually attempted to lock the same lock again.
The pause happened inside the `SelectAll` returned by a `future::select_all` call, because it selects the next notification received by any of the connected validators through `stream::Next` futures. The `stream::Next` future calls `poll_next` in the internal stream, advancing it. When the `select_all` call completes, all futures are dropped, but the streams remain. However, they cease to be polled (and therefore "pause") until the next iteration calls …

Fix deadlock in `ChainClient::listen`

---

linera-core/src/worker.rs

Implementing transaction count Counter metric

Log transaction count

---

CONTRIBUTING.md

Fix some typos in CONTRIBUTING.md

Update CONTRIBUTING.md - Fix some typos

---

examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/fungible/README.md
examples/fungible/src/lib.rs

Very small PR to slightly improve example docs.

Use `--with-wallet` in examples

---

kubernetes/linera-validator/build_and_redeploy.sh

Not being used anymore
Remove it
CI

Remove unused opt_list

---

linera-chain/src/chain.rs
linera-core/src/worker.rs
linera-rpc/src/grpc_network.rs
linera-service/src/grpc_proxy.rs

Now that we know Prometheus better, these comments are not needed anymore
Remove comments
CI

Remove unnecessary comments

---

linera-chain/src/chain.rs

The introduction of storage fees leads to the introduction of corresponding metrics for the storage that can be tracked via Prometheus.
The implementation is very straightforward.
The CI should take care of it.

Add `prometheus` metrics related to the `storage`.

---

kubernetes/linera-validator/build_and_redeploy.sh

For most cases, if a command fails in a script, the whole script should fail
Using `errexit` (`set -e`) to make that happen. In cases where we want the failure to be allowed, use `|| true`
Ran the script, works as intended

Using errexit on build_and_redeploy.sh

---

.github/workflows/kubernetes.yml
kubernetes/linera-validator/build_and_redeploy.sh

Some adjustments are needed after the TLS changes
Make sure it runs as expected for local runs
Run it, see that it works. I need to compile the binaries that will be used for generating the configs with the proper features for this to work.

Fix build_and_redeploy

---

linera-storage/src/lib.rs

From the documentation (https://prometheus.io/docs/practices/naming/#labels):
> Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.
Oversight on my part, this can cause a huge amount of data to Prometheus, so let's remove it for now. We can figure out another solution if we ever need this level of cardinality. Thanks @ma2bd for pointing out
Kubernetes CI should fail if these metrics are failing to be logged

[prometheus] Don't log high cardinality labels

---

linera-views/src/common.rs
linera-views/src/key_value_store_view.rs
linera-views/src/map_view.rs
linera-views/tests/map_view_tests.rs
linera-views/tests/queueview_tests.rs
linera-views/tests/reentrant_tests.rs
linera-views/tests/views_tests.rs

The work on the `stored_size` revealed several missing features for the `MapView`. This PR implements them.
It is unsure whether they will be used for the `stored_size` but they should be useful anyway.
The functions have been added only for the `ByteMapView` for which the feature makes sense:
* Addition of `key_values` and `count` functions for getting the data.
* Addition of a function `remove_by_prefix` for the removal of keys matching a prefix.
* Expand the features of the `for_each_key_while` by adding the prefix as an option.
* Addition of a strong random-based test framework (which identified several problems during development).
The tests have been significantly strengthened, which allows for the new features tested reasonably by random
computations.
The documentation is expanded …

Improvements to `MapView`

---

linera-rpc/src/node_provider.rs
linera-rpc/src/simple_network.rs
linera-rpc/src/transport.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/tests/end_to_end_tests.rs

I need this feature to simplify the client but it's not supported by the UDP mode.
* Rather than removing UDP files, it's actually faster to fix the issue (in a quick and dirty way).
* Make UDP usable again :) and add a test
CI

UDP network can now wait for outgoing messages

---

linera-core/src/client.rs
linera-core/src/updater.rs

Simplify client code after #1220
Do not retry any more in case of an error `InactiveChain` during `handle_certificate`.
CI

Remove unnecessary retry loop after #1220

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/linera.rs

Right now if you Ctrl+C before initialization ends, it won't properly clean things up. For Kubernetes specially, this can be problematic as the clusters will stay there using resources of the machine.
Make it so that if a signal is caught during initialization, it'll halt initialization and properly clean things up before exiting the process
Sanity checked regular `linera net up`: https://gist.github.com/andresilva91/58914f9dd0e76a2b41b95e615f51e07e
Tested `linera net up --kubernetes` in normal settings: https://gist.github.com/andresilva91/10e48a52e9e00f698dc6728e8eabecc2
And interrupting in the middle of the initialization: https://gist.github.com/andresilva91/1a0e78512ef238f1e6646174e75dbea4

Catch signals during initialization also

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs

The issue here was if that we don't strip the binaries we're using, all the binaries together can have over 4 GB. When loading these images (each 4 GB) into the clusters, if you do a lot of them in parallel you can quickly OOM your Docker.
These big binaries slow things down in a lot of ways, so for now people should just make sure they'e using stripped binaries, and we can remove the concurrency limitation for loading the images also
Run 4 validators locally, make sure things work with no issues

Stop limiting docker image loading concurrency

---

linera-views/src/reentrant_collection_view.rs

With recent changes (https://github.com/linera-io/linera-protocol/pull/1300), `try_load_entry{,_mut}` starts to look quite complex.
Currently `try_load_entry` has some duplicated code, and then `try_load_entry_mut` duplicates that code again.  This PR refactors them to share more code, by adding two helper functions, and thereby reduces the complexity of the two individual functions.
CI.
Should be a straightforward refactor that is invisible to users.  However, I'd really like a review from @MathieuDutSik to check that I haven't broken any logic here, since I moved around some of the boolean checks.
- https://github.com/linera-io/linera-protocol/pull/1300

`linera-views`: refactor `try_load_entry{,_mut}`

---

linera-rpc/src/grpc_network.rs

If the gRPC client subscribing to a node loses its connection, it currently waits before retrying.
Retry immediately; if that fails, too, add a delay.
Only timeouts were changed.

Retry immediately if gRPC client loses connection.

---

examples/fungible/web-frontend/package-lock.json
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/runtime_actor/handlers.rs
linera-execution/src/wasm/common.rs
linera-execution/src/wasm/mod.rs
linera-execution/tests/test_execution.rs

Another step towards running contracts on a single thread (#1193)
*  Make contract trait sync and create the contract execution thread in the runtime
CI

Manage the contract execution thread generically from the runtime

---

examples/fungible/web-frontend/README.md

The README file for the fungible app's UI contains an outdated URL.
Update it with the URL from the fungible's app's own README.

Update fungible UI README file.

---

linera-service/src/linera.rs

The warning message about long-range attacks is confusing and unnecessarily alarming, especially for devnet.
Make it INFO-level, and only state the data, rather than giving advice.
No changed logic.

Clarify the wallet init warning.

---

.github/workflows/rust.yml
CLI.md
Cargo.lock
Cargo.toml
linera-sdk/src/bin/linera-wasm-test-runner/main.rs
linera-service/Cargo.toml
linera-service/src/linera.rs
linera-service/src/schema_export.rs
linera-service/src/server.rs

We would like to revamp our CLI to use a consistent set of conventions for commands.  A first step towards doing this is to have a document in which the entirety of our current CLI is laid out for inspection.  Additionally, going forward, it would be nice to have automated documentation for our CLI that users can peruse.
Add a `CLI.md` that is automatically generated from our `clap` command structure, and a CI lint to check it is up-to-date.
Note that the lint is in the `test` job, not the `lint` job, as it requires a built `linera`.
Inspect [`CLI.md`](https://github.com/linera-io/linera-protocol/blob/6e023754979f6c1203841f602511c81d4c07db75/CLI.md).
This change only adds documentation.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer-c …

Document CLI

---

examples/fungible/src/contract.rs
examples/fungible/src/service.rs
examples/fungible/src/state.rs
examples/fungible/web-frontend/src/App.js

Different instances of the fungible token application are hard to distinguish based on the application ID.
Display the ticker symbol next to the balance in the UI.
I tested the example manually.
(It doesn't fix the display of the amount itself yet.)
- Closes #1339

Display fungible ticker symbol in the UI.

---

linera-core/src/client.rs
linera-core/src/updater.rs

We will call `stage_block_execution` repeatedly anyway in a next PR for #989
Change the definition of `CommunicationAction::SubmitBlock`
CI

move the client call to stage_block_execution outside of the communication action

---

linera-chain/src/chain.rs
linera-core/src/worker.rs
linera-service-graphql-client/gql/service_schema.graphql

- Add helper fields to chain state for better performance measurement
- Add 3 new fields to `ChainTipState` struct
- Close #927

feat: add 3 new fields to `ChainStateView::tip_state`(ChainTipState)

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs

`local_kubernetes_net` spends some effort converting vectors to vectors for `join_all`, which is unnecessary.
This small patch removes the conversions back and forth, simplifying the code and hopefully gaining a little performance.
CI.
Minor patch.

`linera-service`: remove some unnecessary allocations

---

linera-service/src/cli_wrappers/docker.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/linera.rs

Cross compiling is a pain in general
Adding option to just build within the container
Ran passing binaries, still works.
Ran passing binaries and the new flag, fails as expected.
Ran passing the new flag, builds within container and starts cluster as expected.

Adding option to net up --kubernetes to build within docker container

---

.github/workflows/rust.yml
examples/amm/src/contract.rs
examples/amm/src/lib.rs
examples/amm/src/service.rs
examples/amm/src/state.rs

All our source code files should start with a copyright header, and that is checked by CI. However, CI ignored the example applications, which should also have copyright headers.
Include the `examples` directory in the check for headers task in CI, and add missing headers.
Manually executed the tool before and after to check for missing headers.

Check copyright headers in examples

---

linera-core/src/worker.rs

An unnecessary `mut` is misleading; it indicates that a variable is mutated.
Remove unnecessary `mut`s.

Remove unnecessary mut.

---

linera-views/src/collection_view.rs
linera-views/src/map_view.rs
linera-views/tests/map_view_tests.rs

Mathieu Baudet has recently found some bugs for the hashing of the MapView. This PR addresses it.
* Add an hashing test as part of the random unit test.
* Correction of the bugs.
* Extension by adding the `get_mut` and `get_mut_or_default` to the test code.
It has been checked that with the additional test code but without the corrections the bugs are triggered.

Resolution of bugs for the hashing in MapView

---

linera-service/src/benchmark.rs
linera-service/src/linera.rs

Help with debugging the benchmark tool
* Activate tracing logs
* Add a few logs
CI + tested manually

improve logging in benchmark tool

---

CONTRIBUTING.md

The need for debugging metrics is very important. The executive decision has been to use the Prometheus system
The explanation has been added to the `CONTRIBUTING.md` file. If there is a demand, the insertion
of the scripts to process the results could be done.
It has worked for me on my laptop.

Explain how to run Prometheus locally

---

linera-chain/src/manager.rs

The consensus protocol is complex and needs good documentation to be understandable.
Extend the chain manager documentation and comments a bit, and give names to some intermediary values to improve readability.

Add more docs and comments to chain manager; minor refactoring.

---

examples/amm/README.md
examples/amm/src/lib.rs
examples/matching-engine/tests/transaction.rs
examples/meta-counter/README.md
examples/meta-counter/src/lib.rs
examples/social/src/lib.rs

Found few typos while reading the docs. Hope I could be of any help.

chore: proofreading the docs

---

linera-base/src/crypto.rs
linera-core/src/data_types.rs

Solve clippy warning
Move the function to `linera_base::crypto`
CI

remove one clippy:allow

---

linera-views/src/map_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/set_view.rs
linera-views/tests/map_view_tests.rs
linera-views/tests/reentrant_collection_tests.rs

The functionality is a very natural fit for the recently introduced functionality in the context.
* Introduce the functionality in `MapView` and its siblings.
* Introduce the functionality in `ReentrantCollectionView`and its siblings.
* A small optimization in the `SetView` which already had it.
The functionality was not introduced in `CollectionView` which likely still has some issues.
The tests were significantly expanded to reflect the new functionality.

Introduce the `contains_key` functionality for the `MapView` and `ReentrantCollectionView`.

---

.github/workflows/kubernetes.yml
linera-service/src/cli_wrappers/local_kubernetes_net.rs

I think this was accidentally deleted on #1412
Redoing the changes
CI

Restrict setting binary dir to CI

---

linera-service/src/linera.rs

We currently use microseconds and seconds but most measurements are a few seconds or less.
* Switch CLI reporting consistently to milliseconds
* nit: remove `...`
CI

switch CLI reporting consistently to milliseconds

---

examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs

Several IDs and links in the crowd-funding README are outdated.
Fix them.
I tested it locally.

Fix crowd-funding README.

---

examples/social/README.md
examples/social/src/contract.rs
examples/social/src/lib.rs
examples/social/tests/cross_chain.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-service/tests/end_to_end_tests.rs

The queries in the social example README are outdated.
Fix them.
I tested it locally.

Fix social README.

---

INSTALL.md
examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
linera-service/src/util.rs
linera-service/tests/readme_test.rs

Test GraphQL quotes in README files
* Interprete `gql` quotes if a `uri` is given
* Add a pause after GraphQL mutations
CI

Test GraphQL quotes in README files

---

examples/amm/README.md
examples/amm/src/lib.rs
examples/counter/README.md
examples/counter/src/lib.rs
examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/matching-engine/README.md
examples/matching-engine/src/lib.rs
examples/meta-counter/README.md
examples/meta-counter/src/lib.rs
examples/social/README.md
examples/social/src/lib.rs

README files quickly become stale if we don't test the queries in them.
Test the GraphQL queries in more readme.
Yes!

Test GraphQL quotes in more README files.

---

linera-views/src/lru_caching.rs

It is of general interest to know how well the cache is performing. Thus some metrics can be introduced for that purpose.
We introduce two metrics for cache success and cache fault. Those two are triggered by the feature "metrics". Maybe we could use instead "metric_cache_performance".

Introduce tracking of cache performance.

---

linera-execution/src/execution_state_actor.rs
linera-execution/src/resources.rs
linera-execution/src/runtime.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-views/src/batch.rs

Fees should be paid for storage operations.
Update the `RuntimeCounts` when `write_batch` is executed.
A new unit test was added to check that the resource consumption is calculated correctly.
Closes #1530

Update resource counters with write operations

---

linera-service/Cargo.toml
linera-service/src/linera/client_context.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs

`linera.rs` is quite large, and contains multiple complex structures.
Split it into submodules.
This is only a refactoring.

Split the linera binary target into submodules.

---

.github/workflows/kubernetes.yml

Name is wrong, it's not just Wasm e2e tests anymore
Fix name
CI

Fix kubernetes CI naming

---

linera-chain/src/chain.rs
linera-core/src/worker.rs
linera-rpc/src/grpc_network.rs
linera-service/src/grpc_proxy.rs
linera-storage/src/db_storage.rs
linera-views/src/lib.rs
linera-views/src/lru_caching.rs

As discussed in the warroom
Make metrics either not public or use `#[doc(hidden)]`
CI

Make metrics public or #[doc(hidden)]

---

kubernetes/linera-validator/values-local.yaml

We've set retention on the devnet
So setting it here locally also to replicate the devnet configs
Ran locally to make sure deploy works as expected + CI

Adjust loki/prom retention

---

linera-storage/src/chain_guards.rs

The `ChainGuards` map centralizes access to individual chain states. This may cause lock contention, so it seems like a candidate for refactoring to increase performance. However, this should be measured if possible.
~Create two gauge metrics. The first counts the number of simultaneous attempts to acquire a chain guard lock for the same chain ID. It is incremented before attempting to acquire the internal mutex and decremented after it is acquired. The second metric is just the maximum value of the first gauge, which allows seeing how many requests fought for the same chain at any given moment.~
Add a histogram metric for the latency to acquire a chain guard lock. This value should spike up when lock contention happens.
I ran an integration test and printed the metrics. The maximum …

Measure lock contention in `ChainGuards`

---

kubernetes/linera-validator/grafana-dashboards/scylla-manager/scylla-manager.2.2.json
kubernetes/linera-validator/grafana-dashboards/scylla/alternator.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-advanced.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-cql.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-detailed.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-os.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-overview.4.3.json
kubernetes/linera-validator/templates/grafana-dashboards-config.yaml
kubernetes/linera-validator/templates/scylla-dashboards-config.yaml
kubernetes/linera-validator/templates/scylla-manager-dashboards-config.yaml
kubernetes/linera-validator/values-local.yaml

ScyllaDB and Scylla Manager also expose some dashboards for us
Add those dashboards to our dashboards

Add Scylla and Scylla Manager dashboards to Grafana

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/wasm-tests/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml
linera-witty/test-modules/Cargo.toml

Have a crate number to release the SDK
Change crate version to 0.7.0
CI
Sadly, we now have to redeploy the devnet candidate due to the change in commit number.

change crate version to 0.7.0 on the devnet branch

---

CLI.md
linera-service/src/benchmark.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/tests/end_to_end_tests.rs

Try to make the CLI more consistent with the client library.
* Add commands `linera local-balance`, `linera process-inbox` and `linera sync`
* Mark `linera sync-balance` as deprecated but do not remove it
* Try to improve logs while we're at it
CI
New CLI feature
Possibly

improvements to the CLI

---

linera-storage/src/db_storage.rs

Workers load chains to handle different requests, and they are not cached. This seems like an opportunity for optimizations, but we'd like to measure the impact first.
Keep track of the chain load times to determine the impact it has on overall execution time.
I ran the Crowd-Funding integration test and printed out the metric results. There were 260 chain load operations even though 94 blocks were executed. That seems excessive, especially considering less than 20 chains were used. The total time spent loading chains was 7 ms, which was aproximately 2% of the total execution time of the test.

Measure the latency to load a chain

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-base/src/version_info.rs
linera-base/versions.sh

https://github.com/linera-io/linera-protocol/pull/1590

`VersionInfo`: add `get()` method to dynamically get version info

---

kubernetes/linera-validator/grafana-dashboards/linera-general.json
kubernetes/linera-validator/grafana-dashboards/scylla-manager/scylla-manager.2.2.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-advanced.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-alternator.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-cql.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-detailed.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-os.4.3.json
kubernetes/linera-validator/grafana-dashboards/scylla/scylla-overview.4.3.json
kubernetes/linera-validator/templates/scylla-dashboards-config.yaml

Right now it can be hard to find different dashboards because they're all in one folder
Add tags to our dashboards to make them easier to find

Improve dashboard tags

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/wasmer.rs
linera-execution/src/wasm/wasmtime.rs
linera-execution/tests/fee_consumption.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/utils/mod.rs
linera-execution/tests/wasm.rs

@afck ran into a weird issue in some end to end tests where the following assertion failed:
https://github.com/linera-io/linera-protocol/blob/1152968c192014cebe09ed9ebe411a034f35ff8e/linera-execution/src/runtime.rs#L928
I investigated the remaining fuel in different places of the code, and realized that the `ResourceTracker` would calculate the remaining fuel from the remaining account balance and the fuel price. This meant that any other resource that is consumed and tracked in a way that updates the balance causes a state mismatch between the remaining fuel in the `ResourceTracker` and the `WasmerContractInstance`. That happens because Wasmer keeps track of the remaining fuel, and it was not updated with the changes to the `ResourceTracker`. That stale state was later used in a call to …

Fix fuel consumption tracking

---

linera-indexer/graphql-client/tests/test.rs
linera-service-graphql-client/tests/test.rs

Doesn't seem to be needed, but please lmk if I'm missing something
Removing it
CI

Removing uneeded Rc usages

---

linera-execution/src/system.rs

It's hard to currently estimate the number of open chains in a validator.
Add a counter metric for the number of times the `OpenChain` system operation is executed. This at least allows estimating the number of chains opened per shard, and summing the values allows estimating the number of micro-chains.
Manually tested by printing the metrics while running the reconfiguration end-to-end test.

Add a metric for the number of times `OpenChain` is executed

---

.github/workflows/documentation.yml
.github/workflows/dynamodb.yml
.github/workflows/kubernetes.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml

Spare $$
Filter paths more aggressively. Notably run DB jobs only when we worked on databases.
CI

Reduce work in CI

---

CLI.md
examples/amm/src/contract.rs
linera-base/src/data_types.rs
linera-core/src/unit_tests/client_tests.rs
linera-execution/src/policy.rs
linera-execution/tests/wasm.rs
linera-sdk/src/contract/conversions_from_wit.rs
linera-sdk/src/service/conversions_from_wit.rs
linera-sdk/wasm-tests/src/lib.rs
linera-service/Cargo.toml
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/remote_net.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_options.rs
linera-service/src/linera/main.rs
linera-service/tests/end_to_end_tests.rs

The end-to-end tests should work both with a local network and with the Devnet.
Make the local tests use fees, too, and fix the tests accordingly.
I ran it against Devnet. In CI, it has fees now, too.
- Closes #1620.

Make end-to-end tests work with non-zero fees, and with Devnet.

---

CONTRIBUTING.md
linera-indexer/lib/src/rocks_db.rs
linera-indexer/lib/src/runner.rs
linera-indexer/lib/src/scylla_db.rs
linera-indexer/lib/src/service.rs
linera-rpc/examples/generate-format.rs
linera-sdk/src/bin/linera-wasm-test-runner/main.rs
linera-service/src/benchmark.rs
linera-service/src/database_tool.rs
linera-service/src/linera/client_options.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs
linera-service/src/server.rs
linera-version/src/version_info/mod.rs

nicer logs
Add the newline only where it's needed.
```
cargo test -p linera-service
target/debug/linera --version
```

nit: about empty log line when starting services

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/counter/web-frontend/package-lock.json
examples/fungible/web-frontend/package-lock.json
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/wasm-tests/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage/Cargo.toml
linera-version/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml
linera-witty/test-modules/Cargo.toml

Make a new release
change protocol version to 0.9.0 on the main branch
CI

change protocol version to 0.9.0 on the main branch

---

examples/counter/web-frontend/package-lock.json
examples/fungible/web-frontend/package-lock.json

fix CI (sorry)
revert two bogus changes in json files from #1697
CI

revert two bogus changes in json files from #1697

---

linera-chain/src/chain.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/src/system.rs
linera-rpc/tests/staged/formats.yaml
linera-service/src/chain_listener.rs
linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs

A collection of fields/arguments are shared between the `OpenChain` operation, message, and the `open_chain` function, and we will add more soon, e.g. for https://github.com/linera-io/linera-protocol/issues/1652.
Create a struct with these fields instead.
Only refactoring.

Add OpenChainConfig.

---

linera-execution/src/runtime.rs
linera-execution/tests/test_execution.rs

The `next_message_index` in the operation/message context specifies the index of the _first_ message sent as an outcome of this operation/message. It's currently wrongly used for every `open_chain` call.
Add the number of messages already in the outcomes to `next_message_index`.
`test_open_chain` was updated and reproduced the issue.
- #1720 

Use the correct message index in open_chain.

---

examples/amm/README.md
examples/amm/src/lib.rs
examples/counter/README.md
examples/counter/src/lib.rs
examples/fungible/README.md
examples/fungible/src/lib.rs
examples/matching-engine/README.md
examples/matching-engine/src/lib.rs

A change in how the PRNG generates these hashes happened, and we didn't update it here
Updating hashes
CI
Will write a graphql test in the `README`, and maybe also an UI test, to make sure this is caught by CI

Fix fungible README hashes

---

.github/workflows/rust.yml
examples/native-fungible/README.md

We just merged the initial version of the Native Fungible app, now it needs a `README`
Wrote the `README` for the native fungible token, mostly linking to the fungible one
Ran through it manually, everything works. Did a transaction in the UI also successfully. + CI

Native fungible README

---

linera-core/src/unit_tests/client_tests.rs

In this test the client requests a timeout certificate before the round has timed out. The honest validators will respond with a chain info that does not contain a timeout vote, while the malicious validator in this test always returns an "unexpected state hash" error.
In most cases this means that the chain updater will see at least two `MissingVoteInValidatorResponse` errors, and thus return that error as `Trusted`, which the test asserts.
However, sometimes the malicious validator and one of the honest validators respond ≥ 20% faster than the other two honest validators, so the updater will see _one_ `MissingVoteInValidatorResponse` and _one_ unexpected state hash response. At that point it realizes that the remaining voting weight is not enough anymore to reach a quorum of votes, so …

Fix flaky leader timeout test.

---

linera-views/src/queue_view.rs
linera-views/tests/queueview_tests.rs

The issue was identified in issue #1692 and is now addressed.
It was simply a hash invalidation that was missing. Otherwise the test was reenabled and restructured a little bit.
The CI should do it.
Not relevant.
- Fixes #1692

Address the hash invalidation problem in QueueView

---

examples/fungible/README.md
examples/fungible/src/lib.rs
examples/native-fungible/README.md
examples/native-fungible/src/lib.rs
linera-service/src/util.rs

We had an issue recently where the owners we were setting in the README were wrong. A GraphQL test would catch that because it would fail.
Create GraphQL tests
CI

Add graphQL tests to fungible/native-fungible READMEs

---

README.md

Use a logo image that we own
* Replace logo by SVG image
* Tweak the first sentences
Browse https://github.com/ma2bd/linera-protocol/tree/logo

update logo and first sentences

---

CLI.md
linera-chain/src/data_types.rs
linera-core/src/client.rs
linera-core/src/data_types.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/system.rs
linera-rpc/proto/rpc.proto
linera-sdk/src/lib.rs
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/linera/client_options.rs

We sometimes spell the abbreviation of "identifier" "ID" and sometimes "id".
Use "ID" consistently.
Only comments and documentation text was changed.
- Need to do the same for linera.dev.

Consistently spell ID.

---

linera-service/src/node_service.rs

While debugging the GraphQL tests inside the `fungible` README I had this error pop up for me, but it had no context.
I think it's good to know what chain is the unknown chain, so adding that context to the error
CI

Add more context to Unknown Chain error

---

linera-rpc/Cargo.toml
linera-rpc/build.rs
linera-rpc/src/client.rs
linera-rpc/src/config.rs
linera-rpc/src/grpc/mod.rs
linera-rpc/src/lib.rs
linera-rpc/src/node_provider.rs
linera-rpc/src/simple/mod.rs
linera-service/Cargo.toml

For https://github.com/linera-io/linera-protocol/issues/1609 we will need to disable both these features, as neither will work in the browser.
Add feature flags that we can disable on the Web.
- atop https://github.com/linera-io/linera-protocol/pull/1736.

RPC feature flags for server and simple network

---

linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs

The Linera Wasm SDK tests failed after migrating to use the system APIs through the new runtime types. After investigating the issue, the cause was that there was a user-after-free of the query argument. This happened because the mock system API simply forwarded the `Vec` pointer back to the guest, which then created a `Vec` from it. However, the original `Vec` was then dropped, making the second `Vec` invalid.
Pass a clone of the `Vec` back to the guest.
After this fix, the tests in #1771 pass.
Could be released with a patch version increment.

Clone query argument in mock `try_query_application` API

---

examples/non-fungible/README.md

NFT app needs a README
Like the Native Fungible's README, a good portion of this refers back to the Fungible's README.
Manually followed the README to test the web UI

NFT App README

---

examples/non-fungible/web-frontend/package-lock.json
examples/non-fungible/web-frontend/src/App.js

Images would be a cooler demo :D
Make the NFT UI store images as payload
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/HlciHFAoHZW62zn13apJ/8d486abb-5098-48a0-8d56-5417fda4236a.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/HlciHFAoHZW62zn13apJ/8d486abb-5098-48a0-8d56-5417fda4236a.mov">Screen Recording 2024-03-15 at 19.34.33.mov</video>

Use images as NFT's payload

---

linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs

`ClientContext::apply_client_command` handles round timeouts and makes sure the wallet gets saved even if a command fails. In some places we still do that manually, or incompletely.
Use `apply_client_command` where appropriate.
The existing tests apply; some of this will be tested in more depth when https://github.com/linera-io/linera-protocol/issues/1796 is fixed.

Use apply_client_command where appropriate.

---

linera-service/tests/end_to_end_tests.rs

Mostly a nitpick. The Non Fungible test was in between the two Fungible tests ha
Keep Fungible tests together
CI

Move non fungible e2e test

---

.github/workflows/rust.yml
examples/native-fungible/README.md
examples/native-fungible/src/lib.rs
examples/non-fungible/README.md
examples/non-fungible/src/lib.rs
linera-service/tests/readme_test.rs

These were currently not tested
Make required changes to the READMEs to allow them to be properly tested
`readme_test` in CI

Including native-fungible and non-fungible READMEs into the readme test

---

examples/non-fungible/README.md
examples/non-fungible/src/contract.rs
examples/non-fungible/src/lib.rs
examples/non-fungible/src/state.rs
linera-service/tests/end_to_end_tests.rs

TSIA, @afck had some comments there raising some interesting points
Address the comments
e2e tests + also tested the web UI to make sure the wrong behavior is fixed

Addressing left over comments from 1774

---

Cargo.lock
examples/Cargo.lock
examples/native-fungible/Cargo.toml
examples/native-fungible/src/lib.rs
examples/native-fungible/src/service.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/service_system_api.wit
linera-sdk/src/service/system_api/mod.rs
linera-service/tests/end_to_end_tests.rs

Some `MapView` queries were missing, as indicated per https://github.com/linera-io/linera-protocol/issues/1798
Implement those missing queries
Tested using GraphiQL, made sure new queries work and display expected results + also added coverage for these in the e2e tests

Feature parity for GraphQL queries between native-fungible and fungible

---

.github/workflows/kubernetes.yml

Metrics in the server are now behind the `metrics` feature
Make sure that we enable that feature in CI
CI

Fix prometheus metrics CI

---

examples/amm/src/contract.rs
examples/amm/src/lib.rs
examples/counter/src/contract.rs
examples/counter/src/lib.rs
examples/crowd-funding/src/contract.rs
examples/crowd-funding/src/lib.rs
examples/fungible/src/contract.rs
examples/fungible/src/lib.rs
examples/matching-engine/src/contract.rs
examples/matching-engine/src/lib.rs
examples/meta-counter/src/contract.rs
examples/meta-counter/src/lib.rs
examples/native-fungible/src/contract.rs
examples/non-fungible/src/contract.rs
examples/non-fungible/src/lib.rs
examples/social/src/contract.rs
examples/social/src/lib.rs
linera-base/src/abi.rs
linera-execution/src/lib.rs
linera-sdk/src/contract/mod.rs
linera-sdk/src/lib.rs
linera-sdk/wasm-tests/src/lib.rs
linera-service/template/contract.rs.template
linera-service/template/lib.rs.template

Addressing #1721
Move `Message` to `Contract`
CI

Move Message from ContractAbi to Contract

---

linera-execution/src/lib.rs

@ma2bd's comment https://github.com/linera-io/linera-protocol/pull/1825#discussion_r1539270911
Address it and add the properly modified version of the function back
CI

Add fn user back to Message

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-chain/Cargo.toml
linera-core/Cargo.toml
linera-execution/Cargo.toml
linera-explorer/Cargo.toml
linera-indexer/example/Cargo.toml
linera-indexer/graphql-client/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-rpc/Cargo.toml
linera-sdk-derive/Cargo.toml
linera-sdk/Cargo.toml
linera-sdk/wasm-tests/Cargo.toml
linera-service-graphql-client/Cargo.toml
linera-service/Cargo.toml
linera-storage-service/Cargo.toml
linera-storage/Cargo.toml
linera-version/Cargo.toml
linera-views-derive/Cargo.toml
linera-views/Cargo.toml
linera-witty-macros/Cargo.toml
linera-witty/Cargo.toml
linera-witty/test-modules/Cargo.toml

https://github.com/linera-io/linera-protocol/pull/1837 fixes building for docs.rs.
Release a new patch version.
(Only a version change.)
- https://github.com/linera-io/linera-protocol/pull/1837
- #1826 

change protocol version to 0.10.1 on the devnet_2024_03_26 branch

---

Cargo.lock
examples/crowd-funding/tests/campaign_lifecycle.rs
examples/fungible/src/lib.rs
examples/fungible/tests/cross_chain.rs
examples/matching-engine/tests/transaction.rs
linera-sdk-derive/src/lib.rs
linera-sdk/src/abis/fungible.rs
linera-sdk/src/abis/mod.rs
linera-sdk/src/lib.rs
linera-service/Cargo.toml
linera-service/src/benchmark.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/client_context.rs

Issue #1658
Move the fungible ABI to `linera_sdk`
CI

Move Fungible ABI to linera SDK

---

.github/workflows/kubernetes.yml
linera-core/build.rs
linera-core/src/worker.rs
linera-service/Cargo.toml
linera-service/build.rs
linera-service/src/grpc_proxy.rs
linera-service/src/lib.rs
linera-service/src/proxy.rs
linera-service/src/server.rs

Server metrics are behind `with_metrics` but proxy metrics aren't
Put proxy metrics also behind `with_metrics`
CI

Put proxy metrics behind with_metrics

---

docker/Dockerfile

Right now metrics logging is behind this `metrics` feature
Make sure we compile using `metrics`
CI

Make sure we have metrics enabled in our Docker images

---

linera-service/src/linera/client_context.rs
linera-service/src/linera/main.rs

#1680
Remove `push_to_all_chains`, as it's not something we want to do
CI

Remove push_to_all_chains

---

linera-base/src/data_types.rs
linera-base/src/ownership.rs
linera-core/src/client.rs
linera-core/src/unit_tests/worker_tests.rs
linera-service/src/linera/main.rs
linera-views-derive/src/lib.rs
linera-witty-macros/src/wit_export/mod.rs

Typos and wrong comments are confusing!
Fix them.

Fix some typos and comments.

---

linera-storage-service/README.md
linera-storage-service/src/lib.rs
linera-views/README.md
linera-views/src/lib.rs

While browsing on `crates.io` I realized that the `delete` was still present for the description for `linera-views`.  The PR addresses that.
The `README.md` of `linera-views` and `linera-storage-service` are upgraded.
No change
The release will indeed change the appearance on the `creates.io`.

Update to the `README.md` and corresponding changes.

---

linera-explorer/src/types/json-formatter-js.d.ts

Not sure what happened here, but the Linera Explorer tests started failing on main. Seems likely to be an upstream change
The module wasn't being found, so declaring the module ourselves
CI

Fix Linera Explorer

---

examples/non-fungible/web-frontend/README.md

Currently it has verbatim what the create-react-app generates
Slightly modify it, based on the `fungible`'s web frontend README
CI

Adjusting NFT Webfrontend README

---

examples/amm/README.md
examples/amm/src/contract.rs
examples/amm/src/lib.rs
examples/amm/src/state.rs

This was raised during the weekly eng sync by @afck as a good follow up
Created the `CloseChain` operation, as well as added e2e tests for it, and tried to mimmick the Matching Engine's atomic swaps explanations here also
CI

Adding CloseChain operation to AMM

---

linera-chain/src/chain.rs
linera-chain/src/lib.rs
linera-core/src/unit_tests/wasm_worker_tests.rs

We cannot allow the same grant to be reused across different messages
Disallow that with an error for now
CI

Disallow grants for broadcast channels

---

linera-execution/src/runtime.rs

It is from the time before the view system for the data of smart contracts. The "simple" system was eliminated but the entry remained.
Simply eliminate it.
CI
Not relevant.

Clean up some leftover code

---

linera-core/src/unit_tests/wasm_worker_tests.rs

https://github.com/linera-io/linera-protocol/pull/1941#discussion_r1577480011
Address comment
CI

Address comment on #1941

---

linera-core/src/worker.rs

Useful metric to have
Implement it

Add num_blocks metric

---

INSTALL.md

We have a Nix flake, but its usage is undocumented.
Document it.
Read the documentation :)
Developer documentation–only change: no release needed.

`INSTALL.md`: add instructions for using the Nix flake

---

linera-core/benches/client_benchmarks.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-service/src/chain_listener.rs
linera-service/src/node_service.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

As discussed in eng meeting, making these names a bit less generic
Rename things. Names turned out a bit longer, which I think was expected, but please lmk if you guys have better name suggestions :)
CI

value -> hashed_certificate_value

---

linera-base/src/identifiers.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

This is the first step for supporting user blobs (issue #1981)
Add blob support to `linera-storage::Storage`, and implement the functions.
Will test this in the `PublishBlob` operation, but open to suggestions of testing specific for this PR, if you guys think it should be done

Add support for blobs in linera-storage::Storage

---

examples/llm/README.md
examples/llm/src/lib.rs

Improve the README file of the LLM example
* add TODO link to blob task
* clarify application URL
This is a quick fix. After #1981 we should be able to do a much better job.
tested manually

Improve the README file of the LLM example

---

linera-ethereum/Cargo.toml

A correction had been forgotten.
Solve it.
No change.
Not relevant.

Forgotten correction.

---

linera-witty/Cargo.toml

fix `cd linera-witty && cargo publish`
fix `Cargo.toml`
published the crate

fix linera-witty for `cargo publish`

---

examples/fungible/web-frontend/src/App.js
examples/non-fungible/web-frontend/src/App.js

GraphQL name changed, so this also needs to change
Change name in UIs
Successfully used the UIs

Account -> FungibleAccount on UI

---

linera-core/src/unit_tests/worker_tests.rs

I could be wrong, but this looks like debug logs that got accidentally merged
Remove them
CI

Remove debug logs

---

linera-core/src/worker.rs

We're currently creating the `required_hashes` `HashSet` just to check if we have any unneeded values
If we upgrade it to a `HashMap`, we can reuse it later and avoid having to create the `value_hashes` `HashSet` also, which optimizes things a bit
CI

Small optimization in check_no_missing_bytecode

---

kubernetes/linera-validator/grafana-dashboards/linera-general.json

We don't have anything tracking these yet, even though they're pretty useful to know
Add some very basic graphs, we can iterate further/improve as we go

Adding error rate/latency metrics to dashboard

---

linera-base/src/data_types.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/value_cache_tests.rs
linera-core/src/updater.rs
linera-core/src/value_cache.rs
linera-core/src/worker.rs

We need to use `CertificateValueCache` for other types as well
Make it more generic so we can support caching blobs also
Added some tests

Generalize CertificateValueCache

---

linera-core/src/unit_tests/client_tests.rs

We want to test the following two scenarios:
1) Client A makes a block proposal with a blob. One validator is down. The other three validated the block but don’t confirm it. Now the validator comes back up but another one goes down. Client B (who doesn’t have the blob) then re-proposes that block in the next round.
2) Client A proposes a block with a blob, and it gets confirmed, but one of the four validators is down and doesn’t learn about it at all. Then that validator comes back up but another goes down (so now only two are up and have the blob). Client B proposes a child of that block.
For 1), we modified the existing `test_propose_validated` test.
For 2), we created a new test `test_publish_blob`.
The tests created

Add PublishBlob UnitTest

---

linera-service/src/util.rs

Sometimes we want to ignore code blocks that would be useful in READMEs (for example code blocks which download models).
Add functionality to the README parser to ignore base codeblocks ending with `ignore`.
Added tests.

Readme tests ignore bash blocks ending with `ignore`

---

packages.txt
scripts/publish.sh
scripts/test_publish.sh

* Eventually fix PR #802
* Test crate publishing
* Create a package list `packages.txt`
* Create `scripts/test_publish.sh` using a combination of `cargo index` and `cargo-local-registry`
* Create `scripts/publish.sh`
CAVEAT: `cargo index` uses `Cargo.lock` so it must be accurate.
```
scripts/test_publish packages.txt ~/tmp_registry
```

Test publish

---

linera-service/src/linera/net_up_utils.rs

A new task is spawned to listen for UNIX signals indicating that the local network should stop. The task notifies when a signal is received using a channel. However, the futures for receiving the signals are already channels, so there's an extra level of redundancy there.
One possible use-case for the extra channel is to detect if the sender endpoint is dropped, which according to the code would not terminate the network. I think that this behavior is neither wanted nor correct, because the sender endpoint in the task listening for UNIX signals would only be dropped if the Tokio signal handlers panic for some reason. Even if that happens, the local network should be teared down.
Listen for UNIX signals (or rather, the streams that notify when those signals are detected) on the main task. …

Listen for signals in the main task

---

.github/workflows/documentation.yml
packages.txt

* Fix #802 --> test docrs again
* Test crate publishing
Use the script introduced in the previous PR #2065
CI

Test publish ci

---

linera-explorer/package.json
linera-explorer/tsconfig.json

Tests don't pass.
Make tests pass.
Update `vue-tsc` to a version that is compatible with our version of `typescript`, and fix resulting `tsconfig.json` errors.
CI.
None required.

`linera-explorer`: fix build

---

linera-storage-service/src/client.rs

This reverts commit 4f7d9948a05b9243d5f727b0b0e2650de7403aad.
Fix `cargo test -p linera-service test_end_to_end_matching_engine --features storage_service`
* Revert #2181 for now
I tried #2190 as a fix but it doesn't seem to do anything, at least on my laptop.
CI + local runs before/after
```
target/release/storage_service_server memory --endpoint 127.0.0.1:1235
LINERA_STORAGE_SERVICE=127.0.0.1:1235 cargo test -p linera-service test_end_to_end_matching_engine --features storage_service
```

Revert PR #2181

---

linera-core/src/chain_worker/state.rs

Trying to make a code a bit more easy to audit after the recent refactoring (this is just a start)
change a number of `pub` into `pub(super)` after discussing with @jvff 
CI

nits in state.rs

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/test_utils/mock_application.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/src/wasm/mod.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/bin/wit_generator.rs

CI seems to be timing out after #2192 was merged.
Revert #2192.
CI should catch any issues, because this just undos some changes.

Revert "Make `SyncRuntime` represent the execution lifetime (#2192)"

---

Cargo.lock
examples/Cargo.lock
linera-storage-service/Cargo.toml
linera-storage-service/src/client.rs
linera-storage-service/src/server.rs
linera-views/src/test_utils/mod.rs

The `storage_service_server` did not have logs.
Some print statements are added for tracing.
In passing, it was found that the `read_value_bytes` was not tested and so relevant functions are added.
The CI is improved by this work.
Not relevant.

Add print statements for the `storage_service_server`

---

CONTRIBUTING.md
docker/Dockerfile
examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/fungible/README.md
examples/fungible/src/lib.rs
examples/gen-nft/src/lib.rs
examples/gen-nft/web-frontend/src/App.js
examples/native-fungible/README.md
examples/native-fungible/src/lib.rs
examples/non-fungible/README.md
examples/non-fungible/src/lib.rs
examples/non-fungible/web-frontend/src/App.js
examples/social/src/lib.rs
linera-core/src/client.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/persistent/file.rs
linera-service/src/wallet.rs

We're inconsistent in some places spelling "ID" and using one vs. two spaces. There are also usages of `map_or(false, …)`, which can be replaced with the new `is_some_and`.
Use a single space after periods everywhere, "ID" instead of "id", and use `is_some_and` where appropriate.

Minor fixes: typos, simplifications.

---

packages.txt

Fix the package-publish test on CI.
Add `linera-client` to `packages.txt`.
CI.
None required.

`linera-client`: add to `packages.txt`

---

linera-core/src/chain_worker/actor.rs

The chain worker contains a lot of critical code, so it should provide as much information as possible to help debug any issues.
Most importantly, warn if a response from the `ChainWorkerActor` is ignored. Log every request the actor receives (at the tracing level) and also improve the name of the `ChainWorkerActor`'s span and link it to the span of the task that spawned the worker.
I ran the `worker_tests` manually with `RUST_LOG=trace` and looked at the new log messages.
Nothing is needed, since only log messages have been changes.

Improve `ChainWorkerActor` logging

---

examples/gen-nft/README.md

Fix README file for NFT demo app
Add the missing wasm compilation target.
The CI.
Not relevant.

Fix the `README.md` file of the NFT example app

---

examples/Cargo.lock
examples/llm/Cargo.toml
examples/llm/src/service.rs

One of the use cases for blockchains in AI is traceability of the models used. In a first step in that direction, we should ensure that the model fetched by the service is as expected.
Ensure that the hash of the fetched model weights and tokenizer match some predetermined values.
Ran the example manually and saw that it fails to run if the hash doesn't match.
Nothing needed, because this only changes the LLM example.

Check the hash of the model and tokenizer bytes

---

CONTRIBUTING.md

The Wasm test framework has changed.
Fix docs

fix Wasm test commands in CONTRIBUTING.md

---

Cargo.lock
Cargo.toml
clippy.toml
examples/Cargo.lock
linera-base/Cargo.toml
linera-base/src/lib.rs
linera-base/src/tracing.rs
linera-client/src/chain_listener.rs
linera-client/src/lib.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/worker.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/server.rs

We have tracing dependencies, but very little tracing infrastructure: we don't have much insight into how our functions are running, and getting debugging information out usually involves adding prints.  After we do get output, it arrives in an unstructured format, and (when running tests) interleaved so we can't tell which timelines belong together.
- Write a standardized tracing-initialization function, in `linera-base` for now, so that all our binaries behave the same;
- Introduce tracing instrumentation at key points in the codebase (at level `trace`, disabled on release builds);
- Make sure different client invocations are differentiated in the logs, by logging the wallet ID;
- Provide a structured output format (JSON) for traces.
The initialization in this PR is configurable through …

Tracing infrastructure

---

examples/llm/src/service.rs

It might be useful to the user to know reason for a delay to answer a query, so it makes sense to show when the application service started downloading the model.
There were also some other log messages that are more useful for debugging, so they could have a their log level changed.
Add and tweak log messages around downloading the model and the tokenizer, and reduce the level of some other log messages.
Tested manually by running the application and checking the logs in the node service.
Nothing needed, because this only changes an example application.

Improve logs in LLM example

---

linera-service/tests/end_to_end_tests.rs

I suspect #2051 was fixed
Reactivate test_wasm_end_to_end_non_fungible_service_grpc
Tested locally + CI

reactivate test_wasm_end_to_end_non_fungible_service_grpc

---

.github/workflows/benchmarks.yml
Cargo.lock
linera-sdk/src/test/validator.rs
linera-service/Cargo.toml
linera-service/benches/transfers.rs

Having good performance is a major goal of the protocol. It is expected that in most cases storage and networking will be bottlenecks. However, we should also isolate the other parts to ensure there are no bottlenecks there.
Add a benchmark that runs many transfers across chains concurrently, without using any networking or persistent storage. Runs this benchmark after every PR has been merged, printing the obtained metrics during the run.
Ran manually, but will also manually start a CI before the PR is merged.
Nothing needed, because this only affects CI.

Benchmark cross-chain transfers without IO in CI

---

linera-storage/src/db_storage.rs

The `BaseKey` variants are named inconsistently: Most are named after the value, but the blob ones are named after the key. Also, `Value` is too general.
Rename `BlobId` and `BlobStateId` to `Blob` and `BlobState`.
Rename `Value` to `CertificateValue`.
(Only renaming.)

Rename the BaseKey variants in storage.

---

linera-storage-service/src/common.rs
linera-views/src/views.rs

Fix grammar in comment
Fix grammar in comment
--> feel free to land the PR for me <--
CI

fix comment

---

linera-core/src/client.rs

`process_notification` checks whether a notification is redundant (e.g. because we already know the new block), logs a debug message and then (as of (#1183)[https://github.com/linera-io/linera-protocol/pull/1183]—my bad!) just continues handling the notification as if it were new.
Return from `process_notification` if the notification isn't new. This should reduce the number of unnecessary chain info requests.

Don't handle redundant notifications.

---

linera-chain/src/data_types.rs
linera-core/src/client.rs

This is a follow up from #2220: https://github.com/linera-io/linera-protocol/pull/2220#discussion_r1694135909
Make sure that the certificates we're getting actually use the blob
CI

Make sure last used by certificate is valid

---

linera-views/src/reentrant_collection_view.rs

When loading multiple entries in the `ReentrantCollectionView`, a single read for a batch of keys is issued. The batch is built from the keys for each entry, which means that the result is an array with chunks of values, one chunk for each entry. Accessing the chunks was done through indices, but since there were other usages for positions in different arrays and indices as the entries' keys, it could lead to confusion.
Replace the index calculations for the array with the batch read results with [`slice::chunks_exact`](https://doc.rust-lang.org/std/primitive.slice.html#method.chunks_exact).
Nothing needed, because this is an internal refactor and CI should catch any regressions.
Nothing needed, because this is an internal refactor with no changes visible to users.
- [reviewer …

Use `chunks_exact` when post-loading multiple entries

---

linera-storage/src/lib.rs

I mixed up PRs and merged #2330 before doing a final tweak to the documentation.
Rephrase the warning so that it's clearer to read
Nothing needed, because this only affects documentation.
Nothing needed, because this only affects documentation.

Tweak chain race warning

---

linera-base/src/data_types.rs
linera-base/src/identifiers.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/unit_tests/test_utils.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/system.rs
linera-execution/src/wasm/system_api.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/client.rs
linera-rpc/src/grpc/client.rs
linera-rpc/src/message.rs
linera-rpc/src/simple/client.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-sdk/src/contract/runtime.rs
linera-sdk/src/service/runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-service-graphql-client/gql/service_schema.graphql
linera-service/src/grpc_proxy.rs
linera-service/src/node_service.rs
linera-service/src/proxy.rs
linera-service/src/schema_export.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

We renamed this in a previous PR, but some names were still incorrect
Use blob content wherever is appropriate 
CI

Some leftover renames after BlobContent

---

examples/non-fungible/web-frontend/src/App.js
examples/non-fungible/web-frontend/src/GraphQLProvider.js

UI is now outdated since we're not using Blobs on the NFT example
Update UI to also use blobs
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/HlciHFAoHZW62zn13apJ/86647f85-e5e0-4c14-b9a5-4bbd39e16443.mov">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/HlciHFAoHZW62zn13apJ/86647f85-e5e0-4c14-b9a5-4bbd39e16443.mov">Screen Recording 2024-08-06 at 12.08.07.mov</video>

Align NFT UI with using blobs

---

linera-core/src/chain_worker/state/attempted_changes.rs
linera-execution/src/execution.rs

These two bugs should get resolved when https://github.com/linera-io/linera-protocol/issues/2167 and https://github.com/linera-io/linera-protocol/issues/365 are implemented.
Add TODOs in the code.
Only comments were added.
- The bugs: https://github.com/linera-io/linera-protocol/issues/2351, https://github.com/linera-io/linera-protocol/issues/2362

Add TODO comments for two bugs.

---

examples/non-fungible/src/contract.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/runtime.rs
linera-execution/src/system.rs
linera-execution/src/wasm/system_api.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/contract/test_runtime.rs
linera-sdk/src/service/runtime.rs
linera-sdk/src/service/test_runtime.rs
linera-sdk/wit/contract-system-api.wit
linera-sdk/wit/service-system-api.wit
linera-storage/src/lib.rs

This is a follow up suggested on #2354
Check if the `Blob` exists before actually minting the NFT
CI

Check if blob exists before minting NFT

---

linera-sdk/src/contract/test_runtime.rs

The test runtime should have the same methods as the contract runtime. That was missed in https://github.com/linera-io/linera-protocol/pull/1720 and https://github.com/linera-io/linera-protocol/pull/2327.
Add the missing methods.
These aren't used in any test yet, but the implementation is simple.
They will be used in an upcoming PR when the Hex Game is extended to automatically open temporary chains.

Add open_chain to the test runtime.

---

linera-core/src/chain_worker/state/temporary_changes.rs

We are going to handle subscriptions offchain in an upcoming PR, so validators will not always agree on the last channel message before unsubscribing.
The block in which `Unsubscribe` was _sent_, however, is the same for everyone. So we can make the inboxes appear consistent by filtering out channels we already unsubscribed from.
Filter out channels we unsubscribed from when collecting pending messages.
The behavior will be the same except in edge cases; existing tests should catch any regressions.

Filter messages from unsubscribed channels.

---

linera-base/src/crypto.rs
linera-base/src/identifiers.rs
linera-client/src/client_options.rs
linera-client/src/storage.rs
linera-sdk/src/service/test_runtime.rs
linera-service/src/project.rs
linera-views/src/set_view.rs

I found a few unclear formulations, typos and a bit of `std::` noise.
Import `std` submodules/types, fix typos, improve formulations.
Existing tests should catch any regressions.

Minor fixes: documentation, imports

---

linera-core/src/chain_worker/state/attempted_changes.rs
linera-sdk/src/test/validator.rs
linera-views/src/batch.rs
linera-views/src/collection_view.rs
linera-views/src/key_value_store_view.rs
linera-views/src/log_view.rs
linera-views/src/map_view.rs
linera-views/src/queue_view.rs
linera-views/src/reentrant_collection_view.rs
linera-views/src/register_view.rs
linera-views/src/set_view.rs
rustfmt.toml

fixes #2370
Enable [format_code_in_doc_comments](https://rust-lang.github.io/rustfmt/?version=v1.7.0&search=#format_code_in_doc_comments)
CI

Format code in doc comments

---

linera-sdk/Cargo.toml
linera-sdk/src/views/system_api.rs

- Resolve #1986 
- Add the unit test for `MockKeyValueStore`
CI

chore: add test for `MockKeyValueStore`

---

Cargo.lock
examples/Cargo.lock
linera-chain/Cargo.toml
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-client/src/client_context.rs
linera-client/src/unit_tests/chain_listener.rs
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/client.rs
linera-core/src/unit_tests/test_utils.rs

Some log messages are very long; on the other hand, there are a few places where additional logs would be helpful. Also, the nicknames are the same for all clients in tests.
Make the nicknames different, add a few log messages, shorten others.
I found these more helpful when debugging a test locally.

Improve log messages.

---

examples/Cargo.lock
linera-base/Cargo.toml
linera-base/src/data_types.rs
linera-base/src/identifiers.rs
linera-chain/src/chain.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-chain/src/unit_tests/inbox_tests.rs
linera-client/src/client_options.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-core/src/client.rs
linera-core/src/local_node.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/worker.rs
linera-execution/src/applications.rs
linera-execution/src/graphql.rs
linera-execution/src/lib.rs
linera-service-graphql-client/src/service.rs
linera-service/src/node_service.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

We'll use these in blobs soon
Move them to `linera-base`
CI

Move UserApplication[Description|Id] to linera-base

---

CLI.md
linera-client/src/client_options.rs
linera-service/src/linera/main.rs

We're actually only publishing data blobs through that command
Alter the command name so it's a better description of what's happening
CI

Change CLI command to publish-data-blob

---

linera-client/Cargo.toml
linera-client/src/chain_listener.rs
linera-core/Cargo.toml
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-core/src/client.rs
linera-sdk/src/test/validator.rs
linera-service/Cargo.toml
linera-service/src/faucet.rs
linera-storage/Cargo.toml
linera-storage/build.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

Simplify code
* Remove DbStorageInner. The PR starts by making it private to show that it is not used anywhere.
* A few additional simplifications (see commits)
CI

 remove DbStorageInner

---

linera-service/tests/linera_net_tests.rs

Some issues have previously appeared as the chain used for the Faucet became quite long. These sorts of issues should be caught during tests.
Add an end-to-end test with a reasonably long chain used by a Faucet, and ensure that it can be used to initialize new wallets.
Adds a new end-to-end test to CI.
Nothing needed, because this only adds a test.
- Closes #2336

Test creating many microchains from a Faucet

---

flake.lock

https://github.com/linera-io/linera-protocol/pull/2463
Bump the Rust overlay in `flake.lock`.
Tested locally.
None.

`flake.lock`: update for Rust 1.81.0

---

Cargo.lock
Cargo.toml
examples/Cargo.lock

Prepare the next breaking SDK release
Bump the major version number
CI

update crates to next release v0.13.0

---

scripts/test_publish.sh

Fix the instructions in the doc
add missing documentation
manually tested + follow the CI

add missing documentation after #2337

---

linera-core/src/client.rs
linera-core/src/updater.rs

I found several comments that could be improved, and some unnecessary code.
Improve the comments, remove unused code, simplify away unnecessary complications.
Logic hasn't changed. CI should catch any regressions.

Minor cleanups in linera-core.

---

linera-chain/src/unit_tests/chain_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-execution/src/execution.rs
linera-execution/src/execution_state_actor.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs

Fix the issue with bytecode blobs uncovered by #2473
Cherry pick part of #2473
CI

Fix bytecode blobs

---

linera-core/src/unit_tests/wasm_client_tests.rs

This is a backport of https://github.com/linera-io/linera-protocol/pull/2477 to devnet.
We hurried to merge https://github.com/linera-io/linera-protocol/pull/2473 yesterday, so we don't have a regression test yet.
Add a regression test.
I checked locally that without https://github.com/linera-io/linera-protocol/pull/2473 it fails, as expected.
- PR for the main branch: https://github.com/linera-io/linera-protocol/pull/2477
- Regression test for: https://github.com/linera-io/linera-protocol/pull/2473

Test: message from non-creator chain also registers apps. (Devnet backport.)

---

linera-core/src/unit_tests/wasm_client_tests.rs

We hurried to merge https://github.com/linera-io/linera-protocol/pull/2473 yesterday, so we don't have a regression test yet.
Add a regression test.
I checked locally that without https://github.com/linera-io/linera-protocol/pull/2473 it fails, as expected.
- Regression test for: https://github.com/linera-io/linera-protocol/pull/2473

Test: message from non-creator chain also registers apps.

---

linera-service/tests/linera_net_tests.rs

For some reasons, some compilation error were not caught.
The failing combination was `cargo test --no-run --features remote-net`.
CI.
Not relevant.

Correct compilation error

---

Cargo.lock
Cargo.toml
examples/Cargo.lock

Release fixes #2473 #2476 and #2493
Update to v0.12.1
CI

update crates to next release v0.12.1

---

examples/llm/rust-toolchain.toml
scripts/yank.sh

Yank old crates easily
Create a new script 
Tested manually

create script to yank old crates

---

examples/amm/README.md
examples/amm/src/lib.rs

The AMM README contains a few GraphQL mutations but doesn't say the URL of the GraphiQL where they should be entered.
Thanks @edwardluu for pointing that out!
Add the URLs to the README.
Only text was changed.
- Closes https://github.com/linera-io/linera-protocol/issues/2408.

Clarify URLs in the AMM README.

---

linera-chain/src/chain.rs
linera-core/src/client.rs

We need to measure performance in order to know how to optimize it. We don't have any metrics on the higher-level client functions yet.
Add latency histograms for the most important client functions.
No logic was added, only measurements.

Add latency metrics for client functions.

---

examples/amm/README.md
examples/amm/src/lib.rs
linera-client/src/chain_listener.rs
linera-core/src/client.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/updater.rs

https://github.com/linera-io/linera-protocol/pull/2501, https://github.com/linera-io/linera-protocol/pull/2505 and https://github.com/linera-io/linera-protocol/pull/2515 fix bugs in the client and an example README file.
Backport them to `testnet_boole`.
CI, and the added test, should catch any regressions.
We should release a new patch version of the client.
- #2501
- #2505
- #2515

Backport fixes #2501, #2505 and #2515.

---

linera-storage-service/build.rs
linera-storage-service/src/server.rs
linera-views/src/backends/scylla_db.rs
linera-views/tests/admin_tests.rs

As in title, there are some inconsistencies with the code.
The crates `linera-views` and `linera-storage-service` were corrected.
The executable status of `build.rs` was corrected.
CI
Not relevant.

Replace some `feature = "X"` entries and replace them by `with_X`.

---

linera-storage/src/db_storage.rs
linera-storage/src/lib.rs
linera-views/src/backends/dual.rs
linera-views/src/backends/mod.rs

We're templed to use Rocksdb for chains and the storage service for blobs and certificates.
Define a generic`DualStore`.
The main difficulty was to inject the criterion that will decide which store is in charge of each root key. We use a marker type for this.
The rest is essentially boilerplate.
CI

Allow combining different stores

---

CLI.md
linera-client/src/chain_clients.rs
linera-client/src/chain_listener.rs
linera-client/src/client_options.rs
linera-client/src/unit_tests/chain_listener.rs
linera-service/src/faucet.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs
linera-service/src/unit_tests/faucet.rs
linera-service/tests/local_net_tests.rs

Cherry-pick faucet listener onto testnet-boole

Backport #2410 -- Faucet has a chain listener

---

.github/pull_request_template.md

Clarify how to release changes
* Add more options
* Remove the check boxes (which confuse github)
copy-pasted here

iterate on the new github template

---

linera-ethereum/src/client.rs

The CI is failing because of a lowercase / uppercase problem.
The `.to_lowercase()` function is added.
The CI.
Not relevant.
None.

Some correction of lowercase error.

---

Cargo.lock
linera-rpc/Cargo.toml
linera-views/src/backends/metering.rs

So far the `metering.rs` has the latencies. But other statistics from the storages are of importance.
Add some metrics representing the use case of the systems. Those metrics can be used subsequently in
benchmarking.
The CI
Not relevant.

Improve the metrics for the storage

---

README.md

Fix the instructions so that they can be followed and work.
Update README instructions on the simple Linera example setup to match the current requirements for the Linera Storage Service.
Didn't work with old instructions, works with new ones.
- Nothing to do.

Update README instructions to include instructions to build linera storage service

---

default.nix
flake.nix

When discussing reproducible builds with @deuszx yesterday, I realized that our Nix package build (invoked by `nix build`) was broken by #2516.
Fix it.
Tested locally by running `nix build`.

Fix Nix flake build

---

linera-service/src/cli_wrappers/wallet.rs

`test_wasm_end_to_end_fungible::native_storage_service_grpc` sometimes fails for me locally with:
```
INFO linera::main:node_service{port=7080}: linera_client::chain_listener: Received new notification: Notification { chain_id: 1db1936dad071759, reason: NewBlock { height: BlockHeight(0), hash: 0bda205e22e95d5f } }
thread 'test_wasm_end_to_end_fungible::native_storage_service_grpc' panicked at linera-service/tests/linera_net_tests.rs:136:56:
called `Result::unwrap()` on an `Err` value: raw_query: failed to post query=query { accounts { entry(key: "User:7136460f0c87ae46f966f898d494c4b40c4ae8c527f4d1c0b1fa0f7cff91d20f") { value } } }
Caused by:
0: error sending request for url (http://localhost:7081/chains/1db1936dad0717597a7743a8353c9c0191c14c3a129b258e9743aec2b4f05d03/applications/e19426ba1 …
```

Retry in ApplicationWrapper::raw_query.

---

README.md

I forgot to add an explanation of `linera-client` in the top-level `README.md`.
Add it.
Documentation change only.

`README.md`: explain `linera-client`

---

Cargo.lock
Cargo.toml
examples/Cargo.lock

We recently ran into some segmentation faults that occurred infrequently, but without a known cause. It could be related to Wasmer's code generation, so updating the dependency to the latest version could solve the issue.
Use the latest version with upstream changes from Wasmer.
CI should catch any regressions by the update.
- Nothing to do / These changes follow the usual release cycle, because the changes should be backwards compatible.

Update `wasmer` to version `4.4.0-linera.5`

---

examples/amm/README.md
examples/amm/src/lib.rs

Small grammar error in AMM README
Fix it
CI

Miscellaneous fixes in AMM README

---

linera-core/src/client/mod.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_tests.rs
linera-execution/src/lib.rs
linera-storage/src/db_storage.rs
linera-views/src/views/mod.rs

In some places of the code, there's no reason for us to error one blob at a time
Make errors return multiple blobs, also tried to clean up the code a bit but open to feedback
CI

Return multiple blobs not found at once

---

Cargo.lock
linera-chain/Cargo.toml
linera-chain/src/unit_tests/chain_tests.rs
linera-client/Cargo.toml
linera-core/Cargo.toml
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/worker_tests.rs
linera-execution/Cargo.toml
linera-execution/src/execution.rs
linera-execution/src/lib.rs
linera-execution/src/system.rs
linera-execution/src/test_utils/mod.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/wasm.rs
linera-rpc/Cargo.toml
linera-sdk/Cargo.toml
linera-service/Cargo.toml
linera-storage-service/Cargo.toml
linera-storage/Cargo.toml
linera-storage/src/lib.rs
linera-views/Cargo.toml

The docs test is failing on main
Revert #2627 to take a different approach on this: if we change how we're using `add_blob`, we don't need to change any dependencies!
CI + I ran `test_publish.sh` locally and it succeeds

Remove add_blob from ExecutionRuntimeContext and fix dependencies

---

linera-core/src/client/mod.rs

This optimization runs `try_synchronize_chain_state_from` in a task that can be canceled, since it is called by `communicate_with_quorum`. That could potentially mean that a certificate gets processed but the task gets canceled before its notifications are handled.
In general, we should make sure that `communicate_with_quorum` only communicates with the validators but doesn't change the state of local chains.
Revert it; we need a better way to implement this optimization.
Nothing to do / These changes follow the usual release cycle.
- https://github.com/linera-io/linera-protocol/pull/2641

Revert "Sync admin chain only when needed".

---

.github/workflows/long_faucet_chain_test.yml
linera-service/tests/linera_net_tests.rs

The `testnet_boole` branch had some CI failures related to the long faucet chain test, which had some recent updates on `main`. These updates fix an issue that's likely the same encountered in the `testnet_boole` branch.
Backport the fixes.
CI should now not fail on the long faucet chain test.
- Nothing to do, this is already the backport.

Backport long faucet chain test fixes

---

linera-service/src/proxy/grpc.rs

A malicious actor could send a `download_certificates(hashes)`  – with `hashes` being a very long vector – and cause a memory leak (or even crash an app) b/c we are not limiting the number of certificates we read from storage at once.
Read certificates from the underlying storage in batches of 100 at once.
Closes https://github.com/linera-io/linera-protocol/issues/2658

Read certificates from storage in batches of 100

---

linera-sdk/src/contract/runtime.rs
linera-sdk/src/contract/test_runtime.rs

This is a port of #2656 to `testnet_boole`, to ensure that the documentation is up to date in any releases made from that branch.
The documentation for `ContractRuntime::query_service` was incorrect, because it led the reader to believe that it was only possible to query the current application's service, while in fact it could be used to query any application's service.
Fix the documentation.
Nothing needed, because this only affects documentation.
- Nothing to do, because the updated documentation should be released with the next version automatically.

Fix query target in `ContractRuntime::query_service` documentation (port to testnet)

---

linera-core/src/client/mod.rs

Several `remote-net` tests are failing with `testnet-boole` because the node service isn't handling notifications as expected. The reason is that the `subscribe` requests to each validator are made in sequence, and we don't process any incoming notifications before that loop has finished.
Don't block on `subscribe()`. Instead, put the `subscribe` request itself into the notifications stream.
With this and https://github.com/afck/linera-protocol/commit/8277005b3ff53527da7f830da64b3207a5dabe76 (a quick hack that will be replaced with https://github.com/linera-io/linera-protocol/pull/2666 soon), all the `remote-net` tests passed for me with `testnet-boole`.
- Nothing to do / These changes follow the usual release cycle. (We will cut a new branch soon anyway.)
- [reviewer …

Don't block on subscribe.

---

linera-storage-service/src/client.rs

The `linera-storage-service` is using a locking mechanism to control the access to the client. This establishes a contention point.
A previous attempt was PR #2181 which unfortunately had some connection errors. I could not reproduce those errors locally. However, that was a false track. The documentation of `Channel` for tonic indicates clearly that cloning Channels is the way to go.
Further experiments in [rust_example_codes](https://github.com/MathieuDutSik/rust_example_codes) (see `test_grpc03_latency`) indicates that having a `Channel` created by a `connect_lazy` achieves the best performance (surprisingly, using `connect` achieves the same performance).
Therefore, the proposed changes simplify the code.
The CI should address the correctness.
The PR should not introduce instability …

Use `Channel` in the `linera-storage-service`

---

linera-views/src/views/bucket_queue_view.rs
linera-views/tests/random_container_tests.rs

A bug of `BucketQueueView` has been introduced.
The problem is revealed by running the benchmarks.
The CI.
Not relevant.

Correct two bugs in the `BucketQueueView`.

---

linera-client/src/client_context.rs

We're only using two fields of `ClientOptions` inside `ClientContext`, but we're passing the whole thing in. 
Stop passing `ClientOptions` directly and pass just the two fields instead. This will also make for example creating test `ClientContext` objects easier.
CI

Stop using ClientOptions in ClientContext directly

---

.github/workflows/benchmarks.yml
.github/workflows/docker.yml
.github/workflows/documentation.yml
.github/workflows/long_faucet_chain_test.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml

See if we can get CI for the commits of release branches
Follow what we did previously on c6f5b00b2017e6158dbdc090bf70e3e0fc71f4c6
CI + test in prod

CI: run certain tests also on the release branches

---

.github/workflows/docker.yml
.github/workflows/long_faucet_chain_test.yml
.github/workflows/rust.yml
Cargo.lock
Cargo.toml
docker/compose.sh
examples/Cargo.lock
kubernetes/linera-validator/helmfile.yaml
linera-core/src/client/mod.rs
linera-core/src/data_types.rs
linera-service/src/cli_wrappers/local_net.rs
scripts/deploy-validator.sh

(TESTING) Devnet 2024 10 21

---

linera-core/src/client/mod.rs

@afck found this issue on the testnet where if we try to publish a blob and it fails, it would basically brick the chain.
The reason why that happened was that we validated the block, but didn't confirm it (because it failed), then when we try to process any other block in that chain, the highest validated block would be this publish blob block. When we would try to confirm it, we would check if we have the blobs we're trying to publish locally.
We checked the `local_node`'s cache, which AFAIU gets nuked once the `linera` process dies, the `ChainState`'s `pending_blobs`, which AFAIU also gets nuked, and then we checked storage, which won't have the blob because the block isn't confirmed.
What we were missing is the `ChainManager`'s `pending_blobs`, which we add to when we create a …

Read from ChainManager's pending blobs when proposing block

---

linera-base/src/identifiers.rs

The [`SystemMessage::OpenChain`](https://github.com/linera-io/linera-protocol/blob/main/linera-execution/src/system.rs#L214) variant would appear in GraphQL responses as `null` (issue #2694). This happened because it was being converted to an [`async_graphql::Value`](https://docs.rs/async-graphql/latest/async_graphql/enum.Value.html) with the [`async_graphql::to_value`](https://github.com/async-graphql/async-graphql/blob/c572a411cd25bfd67fef54208c58d8e4b371e0a7/value/src/serializer.rs#L38-L40) function. That function used a [custom serializer](https://github.com/async-graphql/async-graphql/blob/c572a411cd25bfd67fef54208c58d8e4b371e0a7/value/src/serializer.rs#L42-L256), which only supported serialization of maps with [keys that serialized to …

Fix conversion of `SystemMessage::OpenChain` message to `async_graphql::Value`

---

linera-service/src/project.rs
linera-service/template/Cargo.toml.template
linera-service/template/contract.rs.template
linera-service/template/lib.rs.template
linera-service/template/service.rs.template
linera-service/template/tests/single_chain.rs.template
linera-service/tests/local_net_tests.rs

**Summary:** This pull request updates the necessary files to generate required template files to get started, when executing the command ```linera project new project-name```.
**Changes Made:**
- Added required dependencies to facilitate project initialization.
- Included unit test files to provide examples of test implementation. In ```contract.rs``` and ```service.rs```.
- Added an additional `Integration`  test file to evaluate ```Query``` and ```Operation```, ensuring proper functionality.
**Testing:** All test cases have been successfully executed.

Update Project template

---

linera-explorer/README.md

This README was just showing how to build the Block Explorer code
Include also instructions on how to serve the web application and open it in your browser
Went through the steps myself

Update Block Explorer README

---

linera-service/tests/linera_net_tests.rs

We have several errors when running this without the `INTEGRATION_TEST_GUARD`. When looking for a solution of the problem, the test was found lacking. The improvements proposed are of general interest.
* The "unwrap()" were replaced by "?" when possible.
* The "Missing message notification" now contain the index of the transfer.
* There are two schemes for failing to receive notification. Now they are separate.
The CI should do the job as the changes do not change the tst itself.
Not relevant.

Improvement to the `test_end_to_end_repeated_transfers`.

---

linera-client/src/persistent/file.rs

In `linera_client::persistent::File::read_or_create`, we currently create the `Dirty` object before attempting to create the value that we'd like to consider the file dirty with respect to.  This means that if the file is empty we generate a spurious ‘dropped while dirty’ error, especially in the case of `read`, where the ‘create’ pathway always errors.
```
2024-10-29T14:21:40.346400Z ERROR linera::main: linera_client::persistent::dirty: object dropped while dirty
Error: persistence error: I/O error: path does not exist: /home/debian/.config/linera/wallet.json
```
Re-order the operations so that we create the `Dirty` object after the value, to remove the spurious error.
CI.
- [reviewer …

`linera-client`: improve error behaviour on open failure

---

linera-rpc/src/grpc/client.rs

Tentatively fix CI
Partially revert commit a374a4391d5b5f2576fa2db6870a9a792ff76a5a.
CI

Partially revert "Better logging for subscriptions (#2735)"

---

linera-core/src/chain_worker/state/mod.rs
linera-core/src/client/mod.rs
linera-core/src/remote_node.rs

Synchronizing the admin chain on devnet-2024-10-21 is very slow. https://github.com/linera-io/linera-protocol/pull/2737 improved that.
Port https://github.com/linera-io/linera-protocol/pull/2737 to `main`, too.
This only improves performance, as we verified on devnet-2024-10-21. CI should catch any regressions.
- This is a port of https://github.com/linera-io/linera-protocol/pull/2737.
- `devnet_2024_10_21` version: https://github.com/linera-io/linera-protocol/pull/2737

Optimize `synchronize_received_certificates_from_validator`. (#2737)

---

Cargo.lock
Cargo.toml
examples/Cargo.lock

We're going to release SDK v0.13.0 soon. So the main branch should have the next number.
Upgrade crate version to v0.14.0
CI
main branch only

Upgrade crate version to v0.14.0

---

linera-sdk/src/service/mod.rs

We have a convenient logging infrastructure for the Linera SDK that sends logs to the host application using our system API.  However, in the case of the service, the interpretation of the query happens before that infrastructure is initialized, meaning any errors about the deserialization get lost.
Initialize logging before deserializing the query.
I used it.

`linera_sdk::service`: initialize logging before deserializing query

---

flake.nix
linera-service/template/rust-toolchain.toml.template

We need to be able to use threading for the Web client (specifically Wasm atomics), and these are only enabled in nightly Rust.
Build for the Web using a nightly compiler.  Keep the native build working using a stable compiler, to ensure we don't accidentally lose stable compatibility.
CI.

Build with nightly Rust on the Web

---

linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

When checking for blobs and when getting blobs, we should be trying to get them only from the places where they're expected to be
Look for blobs in the expected places
CI

Look for blobs in the expected places

---

linera-core/src/client/mod.rs
linera-core/src/worker.rs
linera-rpc/src/grpc/client.rs

Found some fields that weren't being logged, but IMHO would be useful (and won't pollute the output).
Log the extra fields
CI

Stop skipping some fields on instrument

---

.github/workflows/docker_image.yml

This is a port of https://github.com/linera-io/linera-protocol/pull/2780
Port it
Merge it and see jobs being pushed

Push all tags individually in Docker Image CI (#2780)

---

linera-core/src/client/mod.rs

We need to port #2793 here
Port it over
CI

Stop updating tracker on first entry we couldn't get or verify (port of #2793)

---

linera-chain/src/data_types.rs
linera-chain/src/manager.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-core/src/client/mod.rs
linera-core/src/data_types.rs
linera-core/src/worker.rs

While reading the end-to-end flows for proposing a block by a client I've stumbled upon few places where some changes could lead to readability (and in once case performance) improvements.

Small refactors while reading the code

---

scripts/deploy-validator.sh

The default deployment mode should be building an image locally.
Add an optional `--remote-image` flag to `deploy_validator.sh`.

deploy-validator.sh uses configurable image.

---

linera-core/src/client/mod.rs
linera-core/src/local_node.rs
linera-core/src/remote_node.rs
linera-core/src/updater.rs
linera-witty-macros/src/wit_export/caller_type_parameter.rs

Some code, mostly related to downloading blobs, is lacking comments and can also be simplify.
Simplify and comment.
No new functionality was added; CI should catch regressions.
- We could backport these to devnet and testnet, to facilitate any future backports.
- Discussion leading to this: https://github.com/linera-io/linera-protocol/pull/2847#pullrequestreview-2424002900

Simplify and comment some blob-related code.

---

linera-chain/src/block.rs
linera-chain/src/certificate.rs
linera-client/src/client_context.rs
linera-core/benches/client_benchmarks.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/client/mod.rs
linera-core/src/remote_node.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_utils.rs
linera-core/src/unit_tests/wasm_client_tests.rs
linera-core/src/worker.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs

Follow-up to #2803 .
Closes https://github.com/linera-io/linera-protocol/issues/2841

Use ConfirmedBlockCertificate where possible, without breaking compatibility.

---

.github/workflows/rust.yml
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/inbox.rs
linera-chain/src/lib.rs
linera-chain/src/manager.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-client/src/chain_listener.rs
linera-client/src/persistent/indexed_db.rs
linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-core/src/client/mod.rs
linera-core/src/data_types.rs
linera-core/src/local_node.rs
linera-core/src/node.rs
linera-core/src/remote_node.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-core/src/worker.rs
linera-rpc/src/grpc/client.rs
linera-sdk/src/test/chain.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-storage/src/db_storage.rs
linera-storage/src/lib.rs
linera-witty-macros/src/wit_export/caller_type_parameter.rs

This is a draft PR with devnet backports, just to run CI. We will not merge this, but push directly instead.

Devnet backports

---

Cargo.lock
Cargo.toml
examples/Cargo.lock

Prepare the SDK release.
Update crates to next release v0.13.1
CI

update crates to next release v0.13.1

---

CONTRIBUTING.md
linera-ethereum/README.md
linera-ethereum/src/lib.rs

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "unintentially" to "unintentionally".
Corrected "Anabling" to "Enabling".
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

linera-service/tests/local_net_tests.rs

fixes #2051
reactivate test_end_to_end_reconfiguration::scylladb_grpc
CI

Reactivate test_end_to_end_reconfiguration::scylladb_grpc

---

linera-core/benches/recorder.rs
linera-service/src/linera/main.rs

The timings that show are not precise enough and hard to parse.
* Each "Operation confirmed in X ms" is replaced by a more precise statement.
* More timings are added for other operations.
The CI.
This PR mostly impacts the log obtained by running the CI. This is useful for operators on the TestNet / DevNet.

More timings of `linera` operations and description of the operations beings timed.

---

linera-service/template/contract.rs.template
linera-service/template/lib.rs.template
linera-service/template/service.rs.template
linera-service/template/tests/single_chain.rs.template
linera-service/tests/local_net_tests.rs

The code generated by `cargo project new` had a few formatting inconsistencies shown by `cargo fmt`.
Fix the formatting issues and check the formatting in CI.
A unit test was updated to also run `cargo fmt --check`.
- Nothing to do, these changes should be included in the next SDK release.
- Closes #2730

Fix formatting of code generated by `cargo project new`

---

.github/workflows/docker.yml
Cargo.toml

We want to achieve as much performance as possible. LTO is an opportunity for this.
The following changes are done:
* Use the LTO for the release compilation.
* Disable debug, though that is less important.
(A) CI is used for correctness.
(B) For the benchmarking, we use the storage-service with 10 runs, the first one being discarded. Three kinds of variables are obtained:
* Prometheus histograms
* Prometheus fault / (fault + success) variables.
* The CI log entries.
Prometheus histogram:
* 3.20 ms(main), **1.94 ms**(lto): block execution latency
* 0.55706 ms(main), **0.52813 ms**(lto): bytecode decompression latency
* 0.13201 ms(main), **0.12184 ms**(lto): contract instantiation latency
* 0.01713 ms(main), **0.01407 ms**(lto): key value store view get latency
* 0.19724 ms(main), …

Use the LTO for the release compilation

---

examples/counter/src/lib.rs

I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3

chore: correct typos docs

---

linera-rpc/src/grpc/client.rs
linera-service/Cargo.toml
linera-service/src/proxy/grpc.rs

https://github.com/linera-io/linera-protocol/pull/3042 applies to `main`, too.
Forward-port it.
See https://github.com/linera-io/linera-protocol/pull/3042.
- Port of https://github.com/linera-io/linera-protocol/pull/3042.
- Related to https://github.com/linera-io/linera-protocol/issues/3029.

Map view error to appropriate status; don't retry if `NotFound`/`AlreadyExists`. (#3042)

---

examples/amm/README.md
examples/amm/src/lib.rs
examples/counter/README.md
examples/counter/src/lib.rs
examples/crowd-funding/README.md
examples/crowd-funding/src/lib.rs
examples/fungible/README.md
examples/fungible/src/lib.rs
examples/gen-nft/README.md
examples/gen-nft/src/lib.rs
examples/matching-engine/README.md
examples/matching-engine/src/lib.rs
examples/native-fungible/README.md
examples/native-fungible/src/lib.rs
examples/non-fungible/README.md
examples/non-fungible/src/lib.rs
examples/social/README.md
examples/social/src/lib.rs
linera-core/src/worker.rs
linera-service/src/node_service.rs
linera-service/src/project.rs

* `wait_for_next_round` is duplicated.
* `MissingExecutedBlockInProposal` is never created now that we have different types for different certificate variants.
* In `Project::create_new` some of the DEBUG logs are uppercase and some lowercase.
* Some of the GraphQL snippets in the READMEs are indented with 2 and some with 4 spaces.
* Remove the duplicated function from `node_service`.
* Remove the unused error variant.
* Make the debug messages consistently uppercase.
* Indent GraphQL with 2 spaces, like on the GraphQL website.

Minor cleanups

---

linera-service/src/linera/main.rs

We would like `linera query-validators` to provide a concise summary of the state of the network on stdout.
Report:
1. Which validators are faulty and why
2. The fraction of healthy validators in the network.
This will be back-ported to `testnet-archimedes` since it needs to be used for the daily network health-check.

linera query-validators has usable output on stdout.

---

linera-core/src/worker.rs

Forgot to address the comments on #3038 before merging
Address comments
CI

Address comments from #3038

---

linera-core/src/worker.rs

TSIA, this is a port of 3038 + 3058 (which are just comments I forgot to address from 3038)
Cherry picked the commits
CI

Port of 3038 to testnet

---

.github/workflows/kubernetes.yml
kubernetes/linera-validator/helmfile.yaml
kubernetes/linera-validator/scylla-manager.values.yaml

Better testing for ScyllaDB validators.
Add `kind` workflow back in.

Reinstate kind workflow

---

examples/social/web-frontend/README.md

This pull request fixes a typo in the `README.md` file. The word "avaiable" has been corrected to "available."
- Corrected the typo in line 9 of `examples/social/web-frontend/README.md` from "avaiable" to "available."
- No related issue.

Fix typo Update README.md

---

linera-storage/src/db_storage.rs

(Based on this comment: https://github.com/linera-io/linera-protocol/pull/3108#discussion_r1910373160.)
Methods like `add_blob_to_batch` would be more readable if they were `Batch` methods without the `_to_batch` suffix.
Add a `BatchExt` trait with these methods.
(Pure refactoring.)
- Original discussion: https://github.com/linera-io/linera-protocol/pull/3108#discussion_r1910373160

Add `BatchExt` trait.

---

linera-rpc/src/grpc/conversions.rs

In #3121 I added gRPC message types but forgot to write conversion unit tests.
Add the missing tests.
This!
- PR with missing tests: #3121

Add conversion tests for pending blobs.

---

linera-core/src/unit_tests/worker_tests.rs

#3168 and #3169 were merged without rebasing on each other, breaking the build.
Fix the broken line.
With this and #3171 CI should work again.

Fix a line that was missed when renaming.

---

examples/matching-engine/src/contract.rs
linera-views/src/backends/dual.rs

While reviewing documentation found several errors in comments
SDK soon.

fix: code comments errors

---

examples/amm/src/contract.rs

Corrected error message in the Message::Swap handler so that it reflects the swap operation rather than adding liquidity.
SDK soon.

Fix misleading error message

---

examples/agent/src/main.rs
examples/matching-engine/src/lib.rs
linera-base/src/command.rs

Fix code comments errors

---

linera-base/src/prometheus_util.rs
linera-sdk/src/abis/fungible.rs

Fix code messages errors

---

linera-core/src/client/mod.rs
linera-ethereum/src/common.rs

Fix bug report message and comment error

---

examples/amm/src/lib.rs
examples/crowd-funding/README.md

examples/amm/src/lib.rs
by given - by the given
examples/crowd-funding/README.md
themself - themselves

spelling issue 

---

linera-execution/src/runtime.rs
linera-indexer/plugins/src/template.rs
linera-rpc/src/simple/transport.rs

Fix function comments errors

---

CLI.md
linera-client/src/client_context.rs
linera-client/src/client_options.rs
linera-client/src/unit_tests/chain_listener.rs
linera-core/src/client/mod.rs
linera-core/src/remote_node.rs
linera-core/src/unit_tests/test_utils.rs
linera-service/src/linera/main.rs

This is a backport of #3232.
See #3232.
CI
- Original PR: #3232

Limit waiting for a single node when downloading blobs. (#3232)

---

linera-witty-macros/src/util/mod.rs
linera-witty-macros/src/util/specialization.rs
linera-witty-macros/src/wit_export/caller_type_parameter.rs

Improve variables and comments

---

linera-sdk/src/service/mod.rs
linera-storage-service/src/child.rs
linera-views/benches/reentrant_collection_view.rs

Fix errors in messages and comments

---

linera-sdk/src/abis/fungible.rs
linera-views/src/backends/scylla_db.rs
linera-witty-macros/src/util/fields.rs
linera-witty-macros/src/wit_export/caller_type_parameter.rs
linera-witty-macros/src/wit_export/function_information.rs

Improve variables and comments errors

---

linera-witty/src/type_traits/mod.rs
linera-witty/tests/common/test_instance.rs
linera-witty/tests/common/wit_interface_test.rs

Fix typos in comment messages

---

examples/hex-game/README.md
linera-chain/src/block.rs
linera-service-graphql-client/gql/service_schema.graphql

examples/hex-game/README.md
second player player at - removed duplicate
linera-chain/src/block.rs
of same - of the same

removed duplicate

---

linera-client/src/client_context.rs

Using `futures::future::join_all` should not be necessary here
Use `tokio::task::JoinSet` directly instead, and capture results.
CI

Use tokio::task::JoinSet directly in mass_broadcast

---

linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/cli_wrappers/mod.rs
linera-service/src/cli_wrappers/remote_net.rs

This does not seem to be used anywhere
Remove it
CI

Remove policy function from LineraNetConfig

---

linera-client/src/client_context.rs
linera-service/src/linera/main.rs

Will start paralellizing some parts of this existing flow
Paralellize creating the benchmark chains

make_benchmark_chains improvements

---

linera-client/src/client_context.rs
linera-service/src/linera/main.rs

Will start paralellizing some parts of this existing flow
Paralellize supplying the fungible tokens

supply_fungible_tokens improvements

---

linera-chain/src/manager.rs
linera-sdk/Cargo.toml
linera-views/src/backends/journaling.rs

chore: fix some typos

---

linera-chain/src/certificate/mod.rs

deleted`
[`ValidatedBlock`]` - [`ValidatedBlock`]

fix mod.rs

---

CONTRIBUTING.md
examples/amm/README.md
examples/gen-nft/README.md
examples/rfq/README.md
examples/social/README.md
linera-views/DESIGN.md

Fixed some typos, hope it'll help in some way

fix: multiple typos of different importance

---

examples/matching-engine/tests/transaction.rs
linera-execution/src/lib.rs
linera-service-graphql-client/gql/service_schema.graphql

exchange of token - fix - exchange for token `2x`
An message - fix - A message

update lib.rs / transaction.rs 

---

linera-rpc/src/grpc/client.rs

This is a port of #3312.
The gRPC status log currently does not show which validator connection it is about.
Include the validator address in the log.
CI
- Nothing to do.
- Related to #3300
- Testnet Archimedes version: #3312

Include validator address in gRPC status log.

---

linera-rpc/src/config.rs

(e.g an IP address)
(e.g., an IP address)

correction config.rs

---

linera-sdk/src/lib.rs

Messages are `messages` sent across chains - Messages are sent across chains

removed duplicate lib.rs

---

linera-ethereum/src/provider.rs

fix function name provider.rs

---

linera-execution/src/committee.rs

correction `arcticle` committee.rs

---

linera-service/src/cli_wrappers/local_net.rs

fix code local_net.rs

---

kubernetes/linera-validator/helmfile.yaml
kubernetes/linera-validator/templates/grafana-cloud-auth-secret.yaml
kubernetes/linera-validator/values-local.yaml.gotmpl

We need this to deploy one validator with Grafana Cloud
Port to `testnet_archimedes`
CI

Port of #2994 - Send Prometheus metrics to Grafana Cloud

---

linera-service/src/benchmark.rs
linera-service/src/server.rs

linera-service/src/benchmark.rs
amount - number
linera-service/src/server.rs
hards not supported - hards are not supported

correction issues

---

linera-views/benches/reentrant_collection_view.rs

linera-views/benches/reentrant_collection_view.rs
completed - completely   * correction*

correction reentrant_collection_view.rs

---

linera-views/src/backends/metering.rs

_read_value_number_none_cases - _read_value_none_cases

spelling errors metering.rs

---

linera-client/src/client_context.rs

@afck suggested this on PR https://github.com/linera-io/linera-protocol/pull/3374, but I forgot to address before merging
Remove the clone
CI + run benchmark

Avoid doing a clone

---

examples/fungible/web-frontend/README.md
examples/hex-game/README.md

owner must be have - owner must have
`linera -with-wallet 1` - `linera --with-wallet 1`

fix issues

---

examples/matching-engine/README.md
examples/rfq/src/state.rs
examples/social/src/lib.rs

Fix comment errors

---

linera-ethereum/README.md
linera-ethereum/src/lib.rs

changed:
test works - tests work

spelling error

---

linera-faucet/server/src/lib.rs
linera-sdk-derive/src/utils.rs

changed: 
try - Try 
`Ident`- - `Ident`.

grammar and spelling issues

---

linera-client/src/benchmark.rs

The BPS control task is actually the task that will probably be doing the most work when we're at higher BPS numbers
Making it `spawn_blocking` did seem to increase the client's performance
Ran it locally, saw that the client's performance increased slightly

Make BPS control task spawn blocking

---

kubernetes/linera-validator/grafana-dashboards/linera/general.json

This one is actually looking at error rate across different method names, which is interesting
Make sure the graph shows the method names in an easier to read way
Deployed a network, saw the graph with the better legend

Fix legend for one graph

---

examples/social/web-frontend/README.md

changed:
mentoined - mentioned

spelling issue

---

README.md

Improve README with social links
Add links to x and discord

chore: added shields and links to x and discord

---

linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/test_helpers.rs
linera-witty/src/exported_function_interface/result_storage.rs
linera-witty/src/runtime/borrowed_instance.rs
linera-witty/src/runtime/test.rs
linera-witty/src/runtime/wasmer/mod.rs
linera-witty/src/runtime/wasmtime/mod.rs
linera-witty/src/wit_generation/stub_instance.rs

- Create test_helpers.rs
- Refactor assets
Ref: #1649
SDK soon.

chore: create test helpers to to improve assertions

---

linera-witty/tests/wit_export.rs

linera-witty/tests/wit_export.rs
or return values -  or a return value x2

correction wit_export.rs

---

linera-execution/src/lib.rs
linera-execution/src/runtime.rs

Remove dead code and prepare future changes
* remove dead code ApplicationCallOutcome
* remove default for type parameter in RawExecutionOutcome and RawOutgoingMessage
CI

Small cleanup in linera-execution / messages

---

linera-execution/src/runtime.rs
linera-execution/src/unit_tests/runtime_tests.rs
linera-execution/tests/contract_runtime_apis.rs
linera-execution/tests/fee_consumption.rs
linera-execution/tests/test_execution.rs
linera-execution/tests/wasm.rs

fixes #3467
Use the transaction tracker for messages as well
CI

Fix message ordering

---

linera-views/src/test_utils/mod.rs
linera-views/tests/store_tests.rs

Following the merging of PR #3502 the test was missing.
Add the test from PR #3496.
The test is the whole point.
Not relevant.
None

Add the test for the behavior of the cache in the shared scenario.

---

linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/client/mod.rs
linera-core/src/worker.rs
linera-faucet/server/src/lib.rs

https://github.com/linera-io/linera-protocol/issues/3499
Pass a span with each request.
CI.
- Fixes #3499.

Tracing improvements

---

linera-chain/src/block.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-chain/src/unit_tests/chain_tests.rs
linera-chain/src/unit_tests/data_types_tests.rs
linera-core/src/unit_tests/wasm_worker_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/worker.rs
linera-execution/src/execution.rs
linera-execution/src/runtime.rs
linera-execution/src/transaction_tracker.rs
linera-explorer/src/components/Block.test.ts
linera-explorer/src/components/Blocks.test.ts
linera-rpc/src/grpc/server.rs
linera-rpc/src/simple/server.rs
linera-rpc/tests/snapshots/format__format.yaml.snap
linera-service-graphql-client/gql/service_requests.graphql
linera-service-graphql-client/gql/service_schema.graphql
linera-service-graphql-client/src/service.rs

resolves #3378
This is a rebase of #3494 authored by @usagi32 
CI

Add user operation results in execution outcome

---

kubernetes/linera-validator/grafana-dashboards/linera/execution.json
kubernetes/linera-validator/grafana-dashboards/linera/general.json

Noticed we were missing some more stuff for containers and ScyllaDB
Add these dashboards
This was altered in place and checked

A few more dashboard changes

---

kubernetes/linera-validator/grafana-dashboards/linera/execution.json
kubernetes/linera-validator/grafana-dashboards/linera/general.json
kubernetes/linera-validator/grafana-dashboards/linera/storage.json
kubernetes/linera-validator/grafana-dashboards/linera/views.json
kubernetes/linera-validator/grafana-dashboards/linera/vms/ethereum.json

As I'm investigating things with the benchmarks, saw more useful things we could add/alter here
This adds better CPU graphs, OOM event counters, etc
Deployed a network and saw the updated graphs

More dashboard changes

---

examples/agent/src/main.rs
examples/crowd-funding/src/state.rs

examples/agent/src/main.rs
How can I help! - How can I help?
examples/crowd-funding/src/state.rs
and still - and can still

correction comments 

---

linera-rpc/src/simple/client.rs
linera-sdk/src/contract/runtime.rs

Fix comments for consistency 
SDK soon.

Small changes in comments

---

linera-execution/tests/test_execution.rs
linera-explorer/src/lib.rs

Fixed duplicated comment for another function and deleted extra (`)
SDK soon.

fix: incorrect function comment

---

README.md

docs: added a badge to the docker workflow

---

linera-base/src/lib.rs

Helps with compiling linera on windows.

linera windows

---

linera-indexer/lib/src/common.rs
linera-indexer/lib/src/service.rs
linera-service-graphql-client/src/service.rs

I introduced an `.unwrap()` in https://github.com/linera-io/linera-protocol/pull/3632.
Return an error instead.
CI
- Related to https://github.com/linera-io/linera-protocol/pull/3632.

Improve GraphQL client errors.

---

linera-explorer/src/components/Block.vue
linera-explorer/src/components/Blocks.vue

* #3625 broke the block explorer due to the new address format.
* A number of fields were added recently but are not displayed.
* Fix display of address
* Add missing display sections
Run a local client, make a few transfers, run a node service, run the explorer.

Fix and update block explorer

---

linera-execution/src/policy.rs
linera-rpc/proto/rpc.proto

Fix minor typos in code

---

.github/workflows/rust.yml
examples/counter/src/contract.rs
examples/counter/src/lib.rs
examples/counter/src/service.rs
examples/counter/tests/single_chain.rs
examples/fungible/src/contract.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/lib.rs

Help with Rust quotes in the dev manual
* Add mdbook anchors
* Rewrite some of the comments
CI + used in a next PR in the mdbook
- These changes should be backported to the latest `mainnet` branch and the next testnet branch (`babbage`)

Add mdbook anchors to various source files

---

linera-client/src/storage.rs
linera-views/src/backends/lru_caching.rs

fix some typos in comment
SDK soon.

chore: fix some typos in comment

---

linera-storage/src/lib.rs
scripts/check_chain_loads.sh

Remove dead code
Remove `load_active_chain`
CI

remove load_active_chain

---

CLI.md
linera-indexer/example/tests/test.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/src/linera/command.rs
linera-service/src/linera/main.rs
linera-service/src/node_service.rs
linera-service/src/schema_export.rs

This reverts commit 7fe154eac9672a506fb11bf98a102096c92890a1.
fix CI
revert #3718
This was showing the issue for me locally:
```
target/debug/linera-storage-server memory --endpoint 127.0.0.1:1235
LINERA_STORAGE_SERVICE=127.0.0.1:1235 cargo test --features storage-service test_wasm_end_to_end_social_user_pub_sub
```

Revert "Allow the node service to select arbitrary ports (#3718)"

---

linera-views/src/backends/lru_caching.rs

The LRU cache is defined as "Least Recently Used", that is that the last unused entry gets removed.
The code did not implement this idea.
We correct the LRU so that access to a cache entry leads to a change in the position.
The CI.
Normal release.
None.

Correct the LRU cache functionality.

---

linera-core/src/client/mod.rs
linera-core/src/remote_node.rs

When downloading blobs or certificates from validators, it is better to contact the latest validators. The "local" ones may already be offline, or the client may fail to even obtain them, if the to-be-synchronized chain does not exist in the database yet.
Use the latest committee, so synchronizing works even if the chain does not exist in storage yet.
https://github.com/linera-io/linera-protocol/pull/3732 works for me now.
- Fixes https://github.com/linera-io/linera-protocol/issues/3733.

Use the latest committee instead of the "local" one.

---

linera-rpc/src/grpc/server.rs

We were not logging on failures before, but the proxy logs on failures, which makes the data confusing
Log latency on failures
CI + will look at this while debugging the `babbage` performance issue

Log server latency on failures also

---

scripts/deploy-validator.sh

was accidentally deleted by #3602
bring it back + remove pyroscope data
yolo

Bring back missing script "deploy-validator.sh"

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-faucet/client/Cargo.toml

0.14.0 will soon be released from a separate branch.
Bump crate version to 0.15.0 on `main`
CI

Prepare release of version 0.15.0 in the future

---

examples/counter/src/contract.rs
examples/counter/src/lib.rs
examples/counter/src/service.rs
examples/counter/tests/single_chain.rs
examples/fungible/src/contract.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/lib.rs

Help with Rust quotes in the dev manual
Port #3682 (mdbook anchors)
CI
Manually picked

Port PR #3682 to new testnet branch (mdbook anchors)

---

examples/how-to/perform-http-requests/README.md

correction README.md

---

linera-service/src/benchmark.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/linera_net_tests.rs

The publish_module should have a `VmRuntime` as argument.
Simply implement the feature.
The CI
None.

Expand the `publish_module` of the `ClientWrapper`.

---

linera-core/src/client/mod.rs

When debugging protocol issues it is often useful to see the stages of a block proposal from the client's perspective.
Add debug logs.
(Also remove two unnecessary local variables.)
I used them for debugging today with `RUST_LOG=linera_core::client=debug`.

Add more debug logs to `client.rs`.

---

.github/workflows/scylladb.yml
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/storage.rs

#3870 was incomplete and CI didn't catch it
Bring back the logic to diversify local rocksdb directories when testing
CI

Fix CI after #3870

---

Cargo.lock
linera-client/Cargo.toml
linera-client/src/client_context.rs
linera-client/src/config.rs
linera-client/src/error.rs
linera-service/src/linera/main.rs
linera-service/src/linera/net_up_utils.rs
linera-service/src/proxy/grpc.rs
linera-service/src/proxy/main.rs
linera-service/tests/local_net_tests.rs
linera-storage/src/lib.rs

Refactor the code for query_validator(s)
- Introduce some helper functions in `linera_client`
@Twey I made the new functions available to `web` , adding a dependency to `linera-version`. I figured version checks could be helpful in the web as well.
CI + tested manually

Improve code for validator checks

---

.github/workflows/docker_image.yml
docker/Dockerfile
docker/compose.sh
linera-service/src/cli_wrappers/docker.rs
scripts/deploy-validator.sh

This should've been the case from the start, but I was lazy and did the other way around, which turned out to complicate things more actually
Make release the default
CI + will start a network with debug mode

Make release the default mode for Dockerfile

---

kubernetes/linera-validator/scylla-manager.values.yaml

Last updates for the ScyllaDB versions
Update the versions
CI + will deploy a network with this

Update versions inside scylla-manager config

---

linera-base/src/data_types.rs
linera-base/src/identifiers.rs
linera-base/src/prometheus_util.rs
linera-chain/src/block.rs
linera-chain/src/chain.rs
linera-chain/src/data_types.rs
linera-client/src/wallet.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/client/mod.rs
linera-core/src/local_node.rs
linera-core/src/worker.rs
linera-views/src/views/key_value_store_view.rs

Using [cargo-workspace-unused-pub](https://crates.io/crates/cargo-workspace-unused-pub) I found some unused code. Of course it is often legitimate to have public code that is not used within the workspace, but I believe most of the items it found are actually not needed.
Remove some unused code.
CI—and a careful review so that I don't remove anything that is meant for other users of the crates.

Remove unused code.

---

linera-client/src/client_context.rs
linera-client/src/client_options.rs
linera-client/src/config.rs
linera-client/src/unit_tests/wallet.rs
linera-service/src/linera/main.rs
linera-service/tests/local_net_tests.rs

Now that the `testing_prng_seed` is contained within the signer these do nothing.
Delete them.
CI.

Remove `WalletState` and `SignerState`

---

linera-core/src/client/mod.rs

We want to move more logic to `Client` (see #3942). Specifically `update_from_info` currently only updates the chain client state correctly if the chain info happens to be the one for the `ChainClient`'s own chain. It should _always_ update the chain client state, however.
Move `update_from_info` to `Client`.
(Also `process_certificate`. More to follow.)
CI
- Part of #3942.

Move some `ChainClient` functions to `Client`.

---

linera-service/Cargo.toml
linera-service/src/cli/command.rs
linera-service/src/cli/main.rs
linera-service/src/cli/mod.rs
linera-service/src/cli/net_up_utils.rs
linera-service/src/lib.rs
scripts/check_chain_loads.sh

This will be useful to reuse the code here in other places
Create module
CI

Creating cli module

---

Cargo.lock
Cargo.toml
linera-service/Cargo.toml
linera-service/src/benchmark.rs
linera-service/src/cli/command.rs
linera-service/src/cli/main.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/local_net_tests.rs

We'll be using this command more broadly
Abstract the parameters out into a struct
CI

Abstract benchmark command out

---

Cargo.lock
Cargo.toml
examples/Cargo.lock

Prepare release of SDK 0.14.1
Update crate version
CI

prepare release of SDK 0.14.1

---

linera-explorer/src/components/Application.vue
linera-explorer/src/components/Applications.vue
linera-explorer/src/components/utils.ts
linera-explorer/src/lib.rs
linera-explorer/src/main.ts

Fix explorer UI on the testnet branch
Remove broken `short_app_id` function
CI + tested manually as in the README
Should be ported to main but it won't be enough

Fix explorer UI on the testnet branch

---

.github/workflows/documentation.yml

Fix CI after #4012
Install cargo-local-registry from our fork on github: https://github.com/ma2bd/cargo-local-registry/tree/master
We won't need this after https://github.com/dhovart/cargo-local-registry/pull/198 is released
CI

Fix CI after #4012

---

README.md

- Add a "Key Features" section highlighting main advantages of Linera
- Add explicit system prerequisites for the quickstart guide
- Include a new "Contributing" section with basic guidelines

docs: improve README with features, prerequisites and contribution guide

---

kubernetes/linera-validator/templates/proxy.yaml
kubernetes/linera-validator/values-local.yaml.gotmpl
linera-service/src/cli_wrappers/local_kubernetes_net.rs

Update Kubernetes manifests (and local network) for multiple proxies.

Infrastructure side of multiple proxies.

---

linera-web/signer/src/index.ts
linera-web/signer/src/metamask.ts

Simpler onboarding.
Integrate w/ MetaMask.
Manual in linera-web repository.

Add metamask integration

---

docker/compose-proxy-entrypoint.sh
docker/compose-server-entrypoint.sh
docker/proxy-entrypoint.sh
docker/server-entrypoint.sh
linera-service/src/cli/main.rs
linera-service/src/cli/net_up_utils.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/linera-exporter/main.rs
linera-service/src/proxy/main.rs
linera-service/src/server.rs
linera-service/src/storage.rs

Simplify CLI
Pass the genesis config path only when using a memory store.
CI

Remove unnecessary genesis-config parameters

---

linera-service/src/exporter/README.md
linera-service/src/exporter/runloops/block_processor/mod.rs

This pull request corrects minor spelling mistakes in the documentation and code comments to improve clarity and professionalism.

Fix Typos in Documentation and Comments

---

README.md

docs: updated Apache license icon

---

kubernetes/linera-validator/grafana-dashboards/linera/general.json

We did this for the proxy/server containers
Do it for the ScyllaDB containers also
Modified the dashboard from the UI and exported this JSON with the changes.

Stop tracking regular page faults for ScyllaDB also

---

linera-views/src/test_utils/performance.rs

Some problems in the test were identified some time ago with the test. Here it is corrected.
Clear by the text.
The CI.
None.

Correct a small problem from a previous cancelled PR.

---

linera-client/src/benchmark.rs
linera-core/src/client/mod.rs

We're only measuring the full e2e block times. We should measure some breakdowns of this as well.
Add measurements for some breakdowns of the data as well.
Deploy a network, benchmark it and see the numbers. Output looks like this:
```
benchmark{pid=322175} 2025-06-25T03:05:47.154243Z  INFO linera::main:block_time_quantiles: linera_client::benchmark: Block time p99: 1143 ms
benchmark{pid=322175} 2025-06-25T03:05:47.154262Z  INFO linera::main:block_time_quantiles: linera_client::benchmark:   ├─ Get pending message bundles p99: 10 ms
benchmark{pid=322175} 2025-06-25T03:05:47.154266Z  INFO linera::main:block_time_quantiles: linera_client::benchmark:   ├─ Submit fast block proposal p99: 485 ms
benchmark{pid=322175} 2025-06-25T03:05:47.154268Z  INFO linera::main:block_time_quantiles: …
```

Print further breakdown of timings on the benchmark client side

---

Cargo.lock
linera-client/src/config.rs
linera-service/Cargo.toml
linera-service/build.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/exporter/common.rs
linera-service/src/exporter/exporter_service.rs
linera-service/src/exporter/main.rs
linera-service/src/exporter/proto/indexer.proto
linera-service/src/exporter/runloops/block_processor/mod.rs
linera-service/src/exporter/runloops/block_processor/walker.rs
linera-service/src/exporter/runloops/indexer/client.rs
linera-service/src/exporter/runloops/indexer/conversions.rs
linera-service/src/exporter/runloops/indexer/indexer_exporter.rs
linera-service/src/exporter/runloops/indexer/mod.rs
linera-service/src/exporter/runloops/mod.rs
linera-service/src/exporter/runloops/validator_exporter.rs
linera-service/src/exporter/state.rs
linera-service/src/exporter/storage.rs
linera-service/src/exporter/test_utils.rs
linera-service/src/linera/main.rs
linera-service/src/linera/net_up_utils.rs
linera-service/tests/local_net_tests.rs

This PR just backports the indexer destination #3949 to the babbage testnet that's already part of the main branch.

testnet backport of the indexer exporter

---

linera-execution/src/runtime.rs

The function `prepare_for_call` is returning an `OperationContext` that is never used.
Remove it.
CI.
None.

Simplify the `prepare_for_call` function.

---

linera-chain/src/chain.rs
linera-execution/src/evm/database.rs

fix minor issue in the comment
SDK soon.

chore: fix minor issue in the comment

---

linera-web/signer/package.json

Hey devs, fixed reference
https://github.com/linera-io/linera-protocol/linera-web/signer/#readme -> dead reference 
https://github.com/linera-io/linera-protocol/tree/main/linera-web/signer -> new reference

chore: fix reference 

---

linera-service/src/cli_wrappers/local_net.rs
linera-service/src/exporter/README.md
linera-service/src/exporter/main.rs

Keep consistent casing in binary arguments.
Minor fix.
CI should cach regressions.

Kebab cased config-path exporter arg.

---

linera-client/src/config.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/exporter/common.rs
linera-service/src/exporter/exporter_service.rs
linera-service/src/exporter/main.rs
linera-service/src/exporter/runloops/block_processor/mod.rs
linera-service/src/exporter/runloops/block_processor/walker.rs
linera-service/src/exporter/runloops/indexer/indexer_exporter.rs
linera-service/src/exporter/runloops/mod.rs
linera-service/src/exporter/runloops/task_manager.rs
linera-service/src/exporter/runloops/validator_exporter.rs
linera-service/src/exporter/state.rs
linera-service/src/exporter/storage.rs
linera-service/src/exporter/test_utils.rs
linera-service/tests/local_net_tests.rs

Backport #4207 to Testnet Babbage.

Committee destination (#4207)

---

linera-core/src/chain_worker/state/attempted_changes.rs

Right now looking up a committee goes less efficient way through storage, even though in most cases the relevant committee should already be available in the system execution state.
Do a lookup via the system execution state first and hit storage only if it's not there.
CI

Optimize committee lookup in `process_confirmed_block`

---

linera-web/src/lib.rs

A partner wants to see the chain balance.
Add a function to get the current chain balance.
CI.

`linera-web`: support getting balance

---

linera-core/src/chain_worker/actor.rs
linera-core/src/chain_worker/delivery_notifier.rs
linera-core/src/chain_worker/mod.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/chain_worker/state/temporary_changes.rs
linera-core/src/lib.rs
linera-core/src/unit_tests/value_cache_tests.rs
linera-core/src/value_cache.rs

There is some code that is public but shouldn't be. Some of it is actually unused.
Remove it.
CI
Tests specifically for unused functions were removed.

Remove unused code from `linera-core`.

---

kubernetes/linera-validator/helmfile.yaml
kubernetes/linera-validator/values-local.yaml.gotmpl

We're adding back the local ssd option to lineractl
Do the config changes necessary for it
Tested by deploying networks using lineractl

Add back local ssd related configs

---

.env.indexer-test
docker/Dockerfile.indexer-test
docker/README.indexer-test.md
docker/docker-compose.indexer-test.yml
docker/exporter-config.toml

Currently, testing that all of the components work correctly is a difficult and complicated task.
Add a Dockerfile that builds the pieces necessary to run all of the
components locally:
- validator network
- storage service
- block exporter
- indexer destination
and allows for running it with docker compose.
Manual. To test, follow the new README instructions.

Dockerize setup

---

linera-views/src/backends/lru_caching.rs

Reduce public APIs
Hide some internal functions in `linera-views/src/backends/lru_caching.rs`
CI

Making more functions private in LRU cache

---

linera-core/src/chain_worker/actor.rs

Simplify code after #4209
* Inline `ChainWorkerActor::load`
* Simplify code
CI

Clean up linera-core/src/chain_worker/actor.rs

---

.github/workflows/benchmarks.yml
.github/workflows/docker-compose.yml
.github/workflows/docker_image.yml
.github/workflows/documentation.yml
.github/workflows/dynamodb.yml
.github/workflows/lint-check-all-features.yml
.github/workflows/long_faucet_chain_test.yml
.github/workflows/rust.yml
.github/workflows/scylladb.yml
.github/workflows/test-readmes.yml
linera-base/src/data_types.rs
linera-base/src/ownership.rs
linera-chain/src/lib.rs
linera-chain/src/manager.rs
linera-core/src/chain_worker/state/attempted_changes.rs
linera-core/src/chain_worker/state/mod.rs
linera-core/src/client/mod.rs
linera-core/src/data_types.rs
linera-core/src/node.rs
linera-core/src/unit_tests/client_tests.rs
linera-core/src/unit_tests/worker_tests.rs
linera-core/src/updater.rs
linera-rpc/proto/rpc.proto
linera-rpc/src/grpc/conversions.rs
linera-rpc/tests/snapshots/format__format.yaml.snap

We are seeing "missing vote" errors in some scenarios, although it's not clear it can currently be reproduced on `main`.
Include in the error message whether it was a missing vote due to a proposed block, validated block or requested timeout.
Make validators return errors instead of just skipping in more cases. Now we only skip signing and return the chain info if we either aren't a validator (don't have signing keys) or we already have signed the requested vote.
Otherwise these changes should both make "missing vote" errors less likely (impossible, with non-faulty validators) and easier to debug.
- [reviewer checklist](https://github.com/linera-io/linera-protocol/blob/main/CONTRIBUTING.md#reviewer …

Improve "missing vote" errors.

---

linera-core/src/worker.rs

Right now there's a few things wrong with how we're logging metrics for confirmed certificates:
1. Even if processing the confirmed block fails, we still log the transactions and everything from the block, as if it succeeded.
2. If the certificate has already been processed, we log the transactions and everything else again, as if it's a new block, which causes over reporting.
Fix the two issues with the logging.
CI + will test in a deployed network that I don't see the over reporting anymore.

Properly log metrics for confirmed certificates

---

linera-chain/src/block.rs
linera-chain/src/block_tracker.rs
linera-execution/src/transaction_tracker.rs
linera-views/src/backends/rocks_db.rs

Some variables are public without reason, and some inexact comments.
Straightforward corrections.
The CI.
None

Make some variables private and other corrections.

---

linera-chain/src/block_tracker.rs

We pass the `TransactionOutcome` by reference and then clone it. This can be avoided.
The following was done.
* The increment to the resource was put ahead of the addition of the data to avoid usage after the move.
CI.
None.

Avoid some clone operation.

---

.github/workflows/rust.yml
CLI.md
linera-chain/Cargo.toml
linera-chain/src/data_types.rs
linera-client/Cargo.toml
linera-client/src/benchmark.rs
linera-client/src/client_context.rs
linera-client/src/error.rs
linera-client/src/lib.rs
linera-indexer/example/Cargo.toml
linera-indexer/lib/Cargo.toml
linera-indexer/plugins/Cargo.toml
linera-service/Cargo.toml
linera-service/src/cli/command.rs
linera-service/src/cli/main.rs
linera-service/src/cli_wrappers/wallet.rs
linera-service/tests/linera_net_tests.rs
linera-service/tests/local_net_tests.rs

This code doesn't need to be behind a feature anymore
Remove benchmark feature
CI

Remove benchmark feature

---

linera-client/src/client_options.rs
linera-client/src/wallet.rs
linera-explorer/src/js_utils.rs
linera-faucet/server/src/lib.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/exporter/runloops/mod.rs
linera-storage-service/src/client.rs
linera-storage/src/db_storage.rs
linera-views/src/common.rs

An examination of the code indicates that some variables and functions should have a restricted scope.
The changed files are self-explanatory.
CI.
None

Restrict the scope of some variables and functions.

---

linera-client/src/client_metrics.rs

Right now we print the timings every 5 seconds (by default), regardless if we're recording any timings yet.
Only print the timings, if any were recorded in the last interval
Ran against a local network, and worked as expected.

Be less spammy with timings

---

linera-service/src/exporter/runloops/block_processor/mod.rs
linera-service/src/exporter/runloops/indexer/indexer_exporter.rs
linera-service/src/exporter/runloops/mod.rs
linera-service/src/exporter/runloops/task_manager.rs
linera-service/src/exporter/runloops/validator_exporter.rs
linera-service/src/exporter/storage.rs

Some clone operations no longer need to have an error type. This simplifies the code.
Straightforward.
The CI.
None

Corrections for the clone operations.

---

linera-service/src/cli_wrappers/local_net.rs

There are several bugs related to proxies in the `local_net` setup, some of which are causing error messages like:
```
forward_notifications{…}: linera_rpc::grpc::server: proxy: could not send notification error=status: Unavailable, message: "tcp connect error"
```
The tests pass anyway because only the first proxy is actually used.
Fix the bugs.
The tests now pass without those errors, even if I use multiple proxies. (We don't, by default.)

Fix multi-proxy support in `local_net`.

---

linera-service/tests/fixtures/erc20_shared.sol

fix some minor issues in comment
N/A
CI

chore: fix some minor issues in comment

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-client/Cargo.toml
linera-service/Cargo.toml

0.15.0 is the version for Testnet Conway.
Switch the main branch to 0.16.0.
CI

Prepare release of version 0.16.0 in the future

---

linera-client/Cargo.toml
linera-service/Cargo.toml

Some warnings were emitted during compilation that are annoying.
Correct the Cargo.toml as needed.
The CI.
None.

Some correction to the Cargo.toml entries.

---

.github/actions/get-solc/action.yml
.github/actions/get-solc/solc_download.sh
.github/workflows/rust.yml

CI is broken
Backport the fix for `solc` installer.
CI

Solc testnet fix

---

examples/native-fungible/index.html

Code assumed that the owner is at 0-th index.
Specify owner for the balance query instead of assuming it's at 0-th index
Manual.
- 

Fix balance query in the fungible web demo.

---

linera-client/src/benchmark.rs

Currently if the chain listener fails to start, we just continue with the benchmarks. However, if we want to ensure they're more "realistic", we should enforce that the chain listener is properly running.
Error out if the chain listener fails to start
Benchmark a network using this.

Error out if chain listener fails to start in benchmark client

---

linera-execution/src/test_utils/mod.rs

chore: fix the problematic backtick in the comment

---

docker/debug/Dockerfile.debug

This came up while debugging the benchmarks, there's some things missing from the image still.
Add more useful debugging things to the image
I've built and pushed this, and also used it while debugging already

Adding a few more things to the Dockerfile.debug image

---

linera-views-derive/src/lib.rs

The code in `lib.rs` has several failure scenarios that result in crashes, panics, or other errors.
Fixes #744 
It is completely possible to implement views for unnamed structs, that is:
```rust
pub struct CounterState(pub RegisterView<u64>);
```
However, we choose to make this illegal.  The reason is that this kind of structs would not be used in the protocol code and it is also not allowed by `async_graphql::SimpleObject`.
What this PR does is to add several error patterns without panic to the macro code:
* Unnamed structs lead to explicit error.
* Track the error produced by `RegisterView<u64>` which can be produced by missing Context or by missing view macro.
* structs must have at least one entry.
The CI.
None.

Improvement to the `linera-views-derive` code

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
linera-client/Cargo.toml
linera-service/Cargo.toml

Release a new SDK, notably because the faucet API changes
Bump version to 0.15.1
CI

Prepare release SDK 0.15.1

---

CLI.md
linera-service/src/cli/main.rs
linera-service/src/server.rs

testnet backport of #4549
see #4549
CI

testnet backport of #4549: fix prehistoric about-message

---

CLI.md
linera-service/src/cli/main.rs
linera-service/src/server.rs

Incredible that this text from Fastpay survived until now
Fix the text
CI

fix prehistoric about-message

---

Cargo.lock
Cargo.toml
examples/Cargo.lock
examples/pnpm-workspace.yaml
linera-base/Cargo.toml
linera-base/src/time.rs
linera-web/package.json
linera-web/signer/package.json

Release SDK 0.15.3

---

examples/counter/README.md
examples/counter/src/contract.rs
examples/counter/src/lib.rs
examples/counter/src/service.rs
examples/counter/tests/single_chain.rs
examples/fungible/src/contract.rs
linera-sdk/src/contract/runtime.rs
linera-sdk/src/lib.rs

Fix documentation
Port PR #3682 to the new testnet branch
CI
This time, I'm also going to make a PR to main: #4496

[testnet] Port PR #3682 (mdbook anchors) to the testnet branch

---

examples/vite.config.ts

Make it harder to accidentally deploy the demo apps without setting their required environment variables.
Add a Vite plugin that checks the requisite variables are set (though not sensible) at build time.

`examples/vite.config.ts`: check for required environment variables

---

CLI.md
linera-base/src/crypto/hash.rs
linera-base/src/identifiers.rs
linera-base/src/unit_tests.rs
linera-service/src/cli/command.rs

The oversights after #4570 are also present on `testnet_conway`
Port #4603 to `testnet_conway`
CI

Port of #4603 to Conway

---

linera-core/src/client/mod.rs

This seems to make the remote-net tests flaky.
Revert #4505 and #4649.
CI

Revert weighted validator shuffling

---

examples/native-fungible/index.html

The import map got lost somewhere, which breaks the example.
Put it back.
Tested in production!

`examples/native-fungible`: don't forget the import map (#4574)

---

linera-core/src/client/mod.rs

Backport of https://github.com/linera-io/linera-protocol/pull/4721
Synchronize sender blocks, including its sender dependencies (i.e. past blocks in which sender chain had sent a message to our).
CI
- These changes should be released in a new SDK,

Fix sender block sync.

---

CLI.md
docker/Dockerfile.indexer
kubernetes/linera-validator/exporter-config.toml.tpl
kubernetes/linera-validator/templates/block-exporter.yaml
kubernetes/linera-validator/templates/explorer.yaml
kubernetes/linera-validator/templates/indexer.yaml
kubernetes/linera-validator/values-local.yaml.gotmpl
linera-faucet/server/build.rs
linera-faucet/server/src/lib.rs
linera-faucet/server/src/tests.rs
linera-rpc/src/config.rs
linera-service/src/cli/command.rs
linera-service/src/cli/main.rs
linera-service/src/cli/net_up_utils.rs
linera-service/src/cli_wrappers/docker.rs
linera-service/src/cli_wrappers/helmfile.rs
linera-service/src/cli_wrappers/local_kubernetes_net.rs
linera-service/src/cli_wrappers/local_net.rs
linera-service/src/config.rs

Back porting block explorer PR, and faucet debugging tools
Backport the PRs
CI

Backport of 4582 4691 4692

---

linera-client/src/client_context.rs
linera-service/src/cli/main.rs
linera-service/src/cli_wrappers/wallet.rs

Port of https://github.com/linera-io/linera-protocol/pull/4746.
It helps with debugging consensus issues to get a quick overview of which round the validators are in, and if there are any other discrepancies compared to the local node.
Add more information to `query-validator[s]`. In `query-validators`, show any data that differs from the local node, for every validator.
Example `query-validators` output:
```
Querying validators about chain 3e6bdd095d2e4e30f12e8da38ea1409f2442696b01badbda4226577df09479ff.
Local Node:
Linera protocol: v0.15.4
RPC API hash: dYdv0oSjieFam5sNCUoabG3O2HkATGwTHFKiudkk94o
GraphQL API hash: WkChYtBRBRRD6+FZP+CxcpytMknWIi3dgV3nEBcUkck
WIT API hash: vwRMPCb+RzZbBCJ3PmC6AprU5ns+1ivKT6xQTMxrs58E
Source code: …
```

Add more info to `query-validator[s]`; show only diff in `query-validators`.
